CAF format: icarus::opdet::PMTReadoutWindowMaker< Time, Interval > Class Template Reference
icarus::opdet::PMTReadoutWindowMaker< Time, Interval > Class Template Reference
Algorithm turning readout seeds into a list of readout windows.
#include <PMTReadoutWindowMaker.h>
Classes
struct Window_t
A single contiguous readout window.
Public Types
using TimePoint_t = Time
Type of time used.
using TimeInterval_t = Interval
Type of time interval used.
Public Member Functions
PMTReadoutWindowMaker (TimeInterval_t readoutWindow, TimeInterval_t preTriggerWindow, std::string logCategory="PMTReadoutWindowMaker")
Constructor: specifies all the algorithm parameters.
Configuration query
TimeInterval_t buffer () const
Returns the total time of a readout buffer.
TimeInterval_t preBuffer () const
Returns the time of the readout buffer before its seed.
TimeInterval_t postBuffer () const
Returns the time of the readout buffer after its seed.
Algorithm operations
std::vector< Window_t > makeWindows (std::vector< TimePoint_t > const &seeds) const
Returns a list of readout windows from the specified seeds.
std::vector< Window_t > operator() (std::vector< TimePoint_t > const &seeds) const
Returns a list of readout windows from the specified seeds.
Private Attributes
TimeInterval_t const fPreBuffer
Extension of readout buffer before trigger.
TimeInterval_t const fPostBuffer
Extension of readout buffer after trigger.
Detailed Description
template<typename Time, typename Interval>
class icarus::opdet::PMTReadoutWindowMaker< Time, Interval >
Algorithm turning readout seeds into a list of readout windows.
Template Parameters
Time type of the time point of the primitives
Interval type of the interval between time points
Given a definition of readout window in the configuration, this algorithm builds a list of readout windows around "seeds". A seed is a time when the trigger of the readout window happens, and each readout window will include a pre-trigger buffer (preBuffer()) before that time and a post-trigger buffer (postBuffer()) after it.
This class is designed to work with LArSoft timescale data types like detinfo::timescales::electronics_time, but it can also be used with simple data types (like double), provided that the Interval template parameter is correctly set.
Definition at line 45 of file PMTReadoutWindowMaker.h.
Member Typedef Documentation
TimeInterval_t
template<typename Time , typename Interval > using icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::TimeInterval_t = Interval
Type of time interval used.
Definition at line 52 of file PMTReadoutWindowMaker.h.
TimePoint_t
template<typename Time , typename Interval > using icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::TimePoint_t = Time
Type of time used.
Definition at line 51 of file PMTReadoutWindowMaker.h.
Constructor & Destructor Documentation
PMTReadoutWindowMaker()
template<typename Time , typename Interval > icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::PMTReadoutWindowMaker (TimeInterval_t readoutWindow, TimeInterval_t preTriggerWindow, std::string logCategory = "PMTReadoutWindowMaker< Time, Interval >")
Constructor: specifies all the algorithm parameters.
Parameters
readoutWindow the total time of the readout window
preTriggerWindow the time of the window preceding a readout seed
logCategory name of the stream to send console messages to
Definition at line 158 of file PMTReadoutWindowMaker.h.
Member Function Documentation
buffer()
template<typename Time , typename Interval > TimeInterval_t icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::buffer () const inline
Returns the total time of a readout buffer.
Definition at line 101 of file PMTReadoutWindowMaker.h.
References icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::postBuffer(), and icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::preBuffer().
makeWindows()
template<typename Time , typename Interval > auto icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::makeWindows (std::vector< TimePoint_t > const & seeds) const
Returns a list of readout windows from the specified seeds.
Parameters
seeds the list of seeds to be considered
Returns
a list of readout windows
Each seed generates a readout window with the size specified by the algorithm configuration (buffer()) for each of the time seeds specified in the list.
Overlapping windows are merged.
The seeds are expected to be sorted in increasing time.
Definition at line 170 of file PMTReadoutWindowMaker.h.
References icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::Window_t::setStop().
Referenced by icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::operator()().
operator()()
template<typename Time , typename Interval > std::vector< Window_t > icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::operator() (std::vector< TimePoint_t > const & seeds) const inline
Returns a list of readout windows from the specified seeds.
Parameters
seeds the list of seeds to be considered
Returns
a list of readout windows
Each seed generates a readout window with the size specified by the algorithm configuration (buffer()) for each of the time seeds specified in the list.
Overlapping windows are merged.
The seeds are expected to be sorted in increasing time.
Definition at line 134 of file PMTReadoutWindowMaker.h.
References icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::makeWindows().
postBuffer()
template<typename Time , typename Interval > TimeInterval_t icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::postBuffer () const inline
Returns the time of the readout buffer after its seed.
Definition at line 107 of file PMTReadoutWindowMaker.h.
References icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::fPostBuffer.
Referenced by icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::buffer().
preBuffer()
template<typename Time , typename Interval > TimeInterval_t icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::preBuffer () const inline
Returns the time of the readout buffer before its seed.
Definition at line 104 of file PMTReadoutWindowMaker.h.
References icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::fPreBuffer.
Referenced by icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::buffer().
Member Data Documentation
fPostBuffer
template<typename Time , typename Interval > TimeInterval_t const icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::fPostBuffer private
Extension of readout buffer after trigger.
Definition at line 148 of file PMTReadoutWindowMaker.h.
Referenced by icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::postBuffer().
fPreBuffer
template<typename Time , typename Interval > TimeInterval_t const icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::fPreBuffer private
Extension of readout buffer before trigger.
Definition at line 145 of file PMTReadoutWindowMaker.h.
Referenced by icarus::opdet::PMTReadoutWindowMaker< Time, Interval >::preBuffer().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Algorithms/PMTReadoutWindowMaker.h