CAF format: icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t Struct Reference
icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t Struct Reference
Public Member Functions
double multiplicationStageGain (unsigned int i=1) const
Returns the gain of the specified multiplication stage.
double firstStageGain () const
Returns the gain from the first stage of PMT multiplication.
unsigned int nDynodes () const
Number of dynodes in the PMTs.
void setVoltageDistribution (std::vector< double > &&Rs)
Sets voltageDistribution by stealing and normalizing Rs.
Public Attributes
std::vector< double > voltageDistribution
double dynodeK
Gain from stage with voltage dV is proportional to dV^K.
double gain
Total typical gain of a PMT.
Detailed Description
Definition at line 395 of file PMTsimulationAlg.h.
Member Function Documentation
firstStageGain()
double icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::firstStageGain () const inline
Returns the gain from the first stage of PMT multiplication.
Definition at line 440 of file PMTsimulationAlg.h.
References multiplicationStageGain().
multiplicationStageGain()
double icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::multiplicationStageGain (unsigned int i = 1) const
Returns the gain of the specified multiplication stage.
Parameters
i index of multiplication stage (default: first, 1)
The gain is assumed to be the product of gains from each multiplication stage. The stages are supposed to be connected by \(N \) resistors of known value, whose weight relative to the total (series) resistance is in PMTvoltageDistribution. The total gain (known from gain) is:
\[ \mu = \prod_{i} \mu_{i} \]
and the gain of each stage \(i \) is
\[ \mu_{i} = a (\Delta V_{i})^{k} \]
with \(k \) a known constant (dynodeK) and \(a \) an unknown one. Considered the total applied voltage (cathode to last dynode) to be \(\Delta V \), the total resistance \(R = \sum_{i} R_{i} \) and the weight of each stage \(\rho_{i} = R_{i} / R \) (stored in PMTvoltageDistribution), the potential on stage \(i \) is
\[ \Delta V_{i} = \Delta V \rho_{i} \]
(supporting a circuit current of \(\Delta V / R \)) and therefore
\[ \mu = \prod_{i} a (\Delta V \rho_{i})^{k} \]
that allows to find
\[ a \Delta V^{k} = \sqrt[N]{\frac{\mu}{(\prod_{i} \rho_{i})^{k}}} \]
With this constant known, the gain of each stage is also known:
\[ \mu_{i} = a (\Delta V)^{k} (\rho_{i})^{k} \]
This function returns \(\mu_{i} \), with i starting from 1 to nDynodes() included.
Definition at line 70 of file PMTsimulationAlg.cxx.
References dynodeK, gain, nDynodes(), and voltageDistribution.
Referenced by firstStageGain().
nDynodes()
unsigned int icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::nDynodes () const inline
Number of dynodes in the PMTs.
Definition at line 443 of file PMTsimulationAlg.h.
References voltageDistribution.
Referenced by multiplicationStageGain().
setVoltageDistribution()
void icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::setVoltageDistribution (std::vector< double > && Rs)
Sets voltageDistribution by stealing and normalizing Rs.
Definition at line 87 of file PMTsimulationAlg.cxx.
Member Data Documentation
dynodeK
double icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::dynodeK
Gain from stage with voltage dV is proportional to dV^K.
Definition at line 403 of file PMTsimulationAlg.h.
Referenced by multiplicationStageGain().
gain
double icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::gain
Total typical gain of a PMT.
Definition at line 405 of file PMTsimulationAlg.h.
Referenced by multiplicationStageGain().
voltageDistribution
std::vector<double> icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::voltageDistribution
Voltage distribution of the PMT. Each number represents the relative weight of the resistor between the two arms of a multiplication stage.
Definition at line 400 of file PMTsimulationAlg.h.
Referenced by multiplicationStageGain(), and nDynodes().
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/PMT/Algorithms/PMTsimulationAlg.h
icaruscode/icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx