CAF format: icarus::trigger::ApplyBeamGateClass Class Reference
icarus::trigger::ApplyBeamGateClass Class Reference
Helper applying a beam gate to any gate.
#include <ApplyBeamGate.h>
Public Types
using microseconds = util::quantities::intervals::microseconds
Type aliases.
using optical_tick = detinfo::timescales::optical_tick
using optical_time_ticks = detinfo::timescales::optical_time_ticks
Public Member Functions
ApplyBeamGateClass (icarus::trigger::BeamGateStruct &&beamGate, std::string const &logCategory="ApplyBeamGateClass")
Constructor: gets the gate (in optical ticks) and its duration (in time).
icarus::trigger::OpticalTriggerGate const & gate () const
Returns the beam gate as a icarus::trigger::OpticalTriggerGate.
template<typename Gate >
Gate gateAs () const
Returns the beam gate as the specified gate type Gate.
template<typename Gate >
Gate apply (Gate gate) const
Returns a copy of gate in AND with this beam gate.
template<typename GateColl , typename GateObj = typename GateColl::value_type>
std::vector< GateObj > applyToAll (GateColl const &gates) const
auto asSimulationTime () const
Returns the gate as a simulation time range.
auto tickRange () const
Returns the range of the beam gate as start and stop tick.
microseconds length () const
Returns the length of the gate (in time units).
optical_time_ticks lengthTicks () const
Returns the length of the gate (in time units).
bool operator== (ApplyBeamGateClass const &other) const
Comparison operators.
bool operator!= (ApplyBeamGateClass const &other) const
Private Attributes
icarus::trigger::BeamGateStruct const fGate
Detailed Description
Helper applying a beam gate to any gate.
The gate starts from detinfo::DetectorClocks::BeamGateTime() (with an optional delay) and has length specified on construction.
The assumption that the optical tick clock starts with the electronics time is used.
Access to beam gate range may happen in a few ways: in simulation time scale and in optical time ticks. In all cases, the returned object supports the calls to start(), stop() and duration().
Definition at line 85 of file ApplyBeamGate.h.
Member Typedef Documentation
microseconds
using icarus::trigger::ApplyBeamGateClass::microseconds = util::quantities::intervals::microseconds
Type aliases.
Definition at line 92 of file ApplyBeamGate.h.
optical_tick
using icarus::trigger::ApplyBeamGateClass::optical_tick = detinfo::timescales::optical_tick
Definition at line 93 of file ApplyBeamGate.h.
optical_time_ticks
using icarus::trigger::ApplyBeamGateClass::optical_time_ticks = detinfo::timescales::optical_time_ticks
Definition at line 94 of file ApplyBeamGate.h.
Constructor & Destructor Documentation
ApplyBeamGateClass()
icarus::trigger::ApplyBeamGateClass::ApplyBeamGateClass (icarus::trigger::BeamGateStruct && beamGate, std::string const & logCategory = "ApplyBeamGateClass") inline
Constructor: gets the gate (in optical ticks) and its duration (in time).
Definition at line 98 of file ApplyBeamGate.h.
Member Function Documentation
apply()
template<typename Gate > Gate icarus::trigger::ApplyBeamGateClass::apply (Gate gate) const inline
Returns a copy of gate in AND with this beam gate.
Definition at line 116 of file ApplyBeamGate.h.
References gate(), and icarus::trigger::mulGates().
applyToAll()
template<typename GateColl , typename GateObj > std::vector< GateObj > icarus::trigger::ApplyBeamGateClass::applyToAll (GateColl const & gates) const
Returns a collection of copies of the specified gates each in AND with this beam gate.
Definition at line 197 of file ApplyBeamGate.h.
References gate().
Referenced by icarus::trigger::TriggerSimulationOnGates::produceForThreshold().
asSimulationTime()
auto icarus::trigger::ApplyBeamGateClass::asSimulationTime () const inline
Returns the gate as a simulation time range.
Definition at line 126 of file ApplyBeamGate.h.
References icarus::trigger::BeamGateStruct::asSimulationRange().
gate()
icarus::trigger::OpticalTriggerGate const & icarus::trigger::ApplyBeamGateClass::gate () const inline
Returns the beam gate as a icarus::trigger::OpticalTriggerGate.
Definition at line 107 of file ApplyBeamGate.h.
References icarus::trigger::BeamGateStruct::asGate().
Referenced by apply(), applyToAll(), and gateAs().
gateAs()
template<typename Gate > Gate icarus::trigger::ApplyBeamGateClass::gateAs () const inline
Returns the beam gate as the specified gate type Gate.
Definition at line 112 of file ApplyBeamGate.h.
References gate().
length()
microseconds icarus::trigger::ApplyBeamGateClass::length () const inline
Returns the length of the gate (in time units).
Definition at line 132 of file ApplyBeamGate.h.
References icarus::trigger::BeamGateStruct::duration().
lengthTicks()
optical_time_ticks icarus::trigger::ApplyBeamGateClass::lengthTicks () const inline
Returns the length of the gate (in time units).
Definition at line 135 of file ApplyBeamGate.h.
References tickRange().
operator!=()
bool icarus::trigger::ApplyBeamGateClass::operator!= (ApplyBeamGateClass const & other) const inline
Definition at line 141 of file ApplyBeamGate.h.
operator==()
bool icarus::trigger::ApplyBeamGateClass::operator== (ApplyBeamGateClass const & other) const inline
Comparison operators.
Definition at line 139 of file ApplyBeamGate.h.
tickRange()
auto icarus::trigger::ApplyBeamGateClass::tickRange () const inline
Returns the range of the beam gate as start and stop tick.
Definition at line 129 of file ApplyBeamGate.h.
References icarus::trigger::BeamGateStruct::asOptTickRange().
Referenced by lengthTicks().
Member Data Documentation
fGate
icarus::trigger::BeamGateStruct const icarus::trigger::ApplyBeamGateClass::fGate private
Definition at line 147 of file ApplyBeamGate.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/ApplyBeamGate.h