CAF format: util::details::ArtHandleTracker< Event, Handle > Class Template Reference
util::details::ArtHandleTracker< Event, Handle > Class Template Reference
Tracks art handle objects.
#include <ArtHandleTrackerManager.h>
Public Member Functions
ArtHandleTracker (Event const &event, Handle handle)
Constructor: records all the needed information.
Handle const & handle () const
Returns the tracked handle.
art::Provenance const * provenance () const
Returns the provenance information of the handle.
Public Member Functions inherited from util::ArtHandleTrackerInterface< Event >
virtual ~ArtHandleTrackerInterface ()=default
Virtual destructor (does nothing).
bool removeCachedProduct ()
std::any handlePtr () const
Returns a container for a pointer to the managed handle. Caveat emptor.
std::string productClass () const
Returns the name of the class of handled data product.
std::type_info const * productType () const
Returns the name of the class of handled data product.
art::InputTag inputTag () const
Returns the tag of handled data product.
bool hasSameDataProduct (util::ArtHandleTrackerInterface< Event > const &other) const
Returns whether this and the other objects handle the same data product.
Private Member Functions
Virtual method implementation
virtual bool doRemoveCachedProduct () override
Actually removes the cache.
virtual std::any doHandlePtr () const override
Returns a pointer to the managed handle, wrapped in std::any.
virtual std::string doProductClass () const override
Returns the name of the class pointed by the handle.
virtual std::type_info const * doProductType () const override
Returns the C++ type of the handled data product.
virtual art::InputTag doInputTag () const override
Private Attributes
Event const * fEvent = nullptr
Handle fHandle
Additional Inherited Members
Protected Member Functions inherited from util::ArtHandleTrackerInterface< Event >
Detailed Description
template<typename Event, typename Handle>
class util::details::ArtHandleTracker< Event, Handle >
Tracks art handle objects.
Template Parameters
Handle type of handle being tracked
Note
Due to my limited expertise with metaprogramming (and/or for C++ limitations?) I need one tracker per data type. The util::ArtHandleTrackerManager class should mitigate the hassle deriving from this limitation.
Definition at line 724 of file ArtHandleTrackerManager.h.
Constructor & Destructor Documentation
ArtHandleTracker()
template<typename Event , typename Handle > util::details::ArtHandleTracker< Event, Handle >::ArtHandleTracker (Event const & event, Handle handle) inline
Constructor: records all the needed information.
Definition at line 766 of file ArtHandleTrackerManager.h.
Member Function Documentation
doHandlePtr()
template<typename Event , typename Handle > virtual std::any util::details::ArtHandleTracker< Event, Handle >::doHandlePtr () const inline override private virtual
Returns a pointer to the managed handle, wrapped in std::any.
Implements util::ArtHandleTrackerInterface< Event >.
Definition at line 744 of file ArtHandleTrackerManager.h.
References util::details::ArtHandleTracker< Event, Handle >::handle().
doInputTag()
template<typename Event , typename Handle > virtual art::InputTag util::details::ArtHandleTracker< Event, Handle >::doInputTag () const inline override private virtual
Returns the input tag of the handled data product. Deferred implementation of inputTag().
Implements util::ArtHandleTrackerInterface< Event >.
Definition at line 757 of file ArtHandleTrackerManager.h.
doProductClass()
template<typename Event , typename Handle > virtual std::string util::details::ArtHandleTracker< Event, Handle >::doProductClass () const inline override private virtual
Returns the name of the class pointed by the handle.
Implements util::ArtHandleTrackerInterface< Event >.
Definition at line 748 of file ArtHandleTrackerManager.h.
References util::details::productClassOf().
doProductType()
template<typename Event , typename Handle > virtual std::type_info const * util::details::ArtHandleTracker< Event, Handle >::doProductType () const inline override private virtual
Returns the C++ type of the handled data product.
Implements util::ArtHandleTrackerInterface< Event >.
Definition at line 752 of file ArtHandleTrackerManager.h.
References util::details::ProvenanceGetter< Handle, typename >::productType().
doRemoveCachedProduct()
template<typename Event , typename Handle > virtual bool util::details::ArtHandleTracker< Event, Handle >::doRemoveCachedProduct () inline override private virtual
Actually removes the cache.
Implements util::ArtHandleTrackerInterface< Event >.
Definition at line 735 of file ArtHandleTrackerManager.h.
handle()
template<typename Event , typename Handle > Handle const & util::details::ArtHandleTracker< Event, Handle >::handle () const inline
Returns the tracked handle.
Definition at line 770 of file ArtHandleTrackerManager.h.
Referenced by util::details::ArtHandleTracker< Event, Handle >::doHandlePtr().
provenance()
template<typename Event , typename Handle > art::Provenance const * util::details::ArtHandleTracker< Event, Handle >::provenance () const inline
Returns the provenance information of the handle.
Definition at line 773 of file ArtHandleTrackerManager.h.
Member Data Documentation
fEvent
template<typename Event , typename Handle > Event const* util::details::ArtHandleTracker< Event, Handle >::fEvent = nullptr private
Definition at line 726 of file ArtHandleTrackerManager.h.
fHandle
template<typename Event , typename Handle > Handle util::details::ArtHandleTracker< Event, Handle >::fHandle private
Definition at line 728 of file ArtHandleTrackerManager.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h