CAF format: icarus::KeyValuesData::Item Struct Reference
icarus::KeyValuesData::Item Struct Reference
Representation of a single item of data: a key and several values.
#include <KeyValuesData.h>
Public Types
using pair_t = std::pair<std::string, std::vector<std::string>>
template<typename T >
using UseBase = icarus::details::KeyValuesConverter<icarus::details::BaseWrapper<T>>
Alias for numerical base conversion.
Public Member Functions
Item (std::string key)
Constructs a new item assigning it a key (which should not be changed).
bool operator< (Item const &other) const noexcept
Lexicographic order by key (case-sensitive).
Setting interface
Item & addValue (std::string value)
Item & addValue (std::string_view value)
template<typename BIter , typename EIter >
Item & addValues (BIter begin, EIter end)
Appends a sequence of values to this key.
void clear ()
Removes all the values.
Direct access to key and values
std::string const & key () const noexcept
Returns the key of the item.
std::vector< std::string > & values () noexcept
Returns all item values, as strings.
std::vector< std::string > const & values () const noexcept
Returns the key of the item.
std::string const & value (std::size_t index=0) const noexcept
Returns the value at index (unchecked) with no conversion.
std::optional< std::string > optionalValue (std::size_t index) const noexcept
Returns the value at index with no conversion, no value if not present.
std::size_t nValues () const noexcept
Returns the number of values currently present.
Query interface
template<typename T , typename Conv >
T getAs (std::size_t index, Conv converter) const
Returns the requested value, converted into type T
template<typename T >
T getAs (std::size_t index) const
Returns the requested value, converted into type T
template<typename T , bool IgnoreFormatErrors = false, typename Conv >
std::optional< T > getOptionalAs (std::size_t index, Conv converter) const
Returns the requested value, converted into type T
template<typename T , bool IgnoreFormatErrors = false>
std::optional< T > getOptionalAs (std::size_t index) const
Returns the requested value, converted into type T
template<typename T >
T getNumber (std::size_t index, unsigned int base) const
Returns the requested value, converted into a number of type T
template<typename T >
T getNumber (std::size_t index) const
Returns the requested value, converted into type T
template<typename T >
std::optional< T > getOptionalNumber (std::size_t index, unsigned int base) const
Returns the requested value, converted into a number of type T
template<typename T >
std::optional< T > getOptionalNumber (std::size_t index) const
Returns the requested value, converted into type T
template<typename T , typename Conv = details::KeyValuesConverter<T>>
std::vector< T > getVector (Conv converter={}) const
Returns all the values, each converted into type T
template<typename T , typename Conv = details::KeyValuesConverter<T>>
std::vector< T > getSizedVector (Conv converter=Conv{}) const
Returns all the values, each converted into type T
Private Member Functions
template<typename T , typename Iter , typename Conv >
std::vector< T > convertVector (Iter begin, Iter end, Conv converter) const
template<typename T >
std::optional< T > convertStringInto (std::string const &valueStr) const
Conversion functions.
Detailed Description
Representation of a single item of data: a key and several values.
Values can be added directly accessing the values data member, or with addValue() method call.
Access to the values happens by index, with nValues() indices starting from 0 available. Direct access to values() is expected, and additional shortcuts are available:
getAs(), getOptionalAs() to convert to an arbitrary type; the standard conversion uses from_chars(), and specialization is possible
getNumber(), getOptionalNumber() to convert to a number
getVector() to convert to a vector of values (each like in getAs())
getSizedVector() to convert to a vector of values; the first value is the size of the actual values.
Definition at line 193 of file KeyValuesData.h.
Member Typedef Documentation
pair_t
using icarus::KeyValuesData::Item::pair_t = std::pair<std::string, std::vector<std::string>>
Definition at line 195 of file KeyValuesData.h.
UseBase
template<typename T > using icarus::KeyValuesData::Item::UseBase = icarus::details::KeyValuesConverter<icarus::details::BaseWrapper<T>>
Alias for numerical base conversion.
Template Parameters
T type of the number to be converted
Example of usage:
auto const i16
  = item.getAs<int>(0U, icarus::KeyValuesData::Item::UseBase<int>{ 16 });
converts the first value of item into an integer (int) with base 16.
Definition at line 209 of file KeyValuesData.h.
Constructor & Destructor Documentation
Item()
icarus::KeyValuesData::Item::Item (std::string key) inline
Constructs a new item assigning it a key (which should not be changed).
Definition at line 215 of file KeyValuesData.h.
Member Function Documentation
addValue() [1/2]
Item & icarus::KeyValuesData::Item::addValue (std::string value) inline
Appends a string value to the list of values.
Returns
this same object (allows queueing calls in the same statement)
Definition at line 227 of file KeyValuesData.h.
Referenced by icarus::details::KeyedCSVparser::parse().
addValue() [2/2]
Item & icarus::KeyValuesData::Item::addValue (std::string_view value) inline
Appends a string value to the list of values.
Returns
this same object (allows queueing calls in the same statement)
Definition at line 229 of file KeyValuesData.h.
addValues()
template<typename BIter , typename EIter > Item & icarus::KeyValuesData::Item::addValues (BIter begin, EIter end) inline
Appends a sequence of values to this key.
Definition at line 235 of file KeyValuesData.h.
Referenced by icarus::details::KeyValueParser::parse().
clear()
void icarus::KeyValuesData::Item::clear () inline
Removes all the values.
Definition at line 240 of file KeyValuesData.h.
Referenced by icarus::details::KeyValueParser::parse().
convertStringInto()
template<typename T > std::optional< T > icarus::KeyValuesData::Item::convertStringInto (std::string const & valueStr) const inline private
Conversion functions.
Definition at line 480 of file KeyValuesData.h.
convertVector()
template<typename T , typename Iter , typename Conv > std::vector< T > icarus::KeyValuesData::Item::convertVector (Iter begin, Iter end, Conv converter) const private
Definition at line 777 of file KeyValuesData.h.
getAs() [1/2]
template<typename T > T icarus::KeyValuesData::Item::getAs (std::size_t index) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
Parameters
index the index of the requested value
Returns
the requested value as an object of type T
Exceptions
ValueNotAvailable if no value is available with that index
ConversionFailed if the value could not be converted to type T
Conversion is performed via an helper class icarus::details::KeyValuesConverter which can be specialized if needed, and that uses from_chars() for conversion.
Definition at line 692 of file KeyValuesData.h.
getAs() [2/2]
template<typename T , typename Conv > T icarus::KeyValuesData::Item::getAs (std::size_t index, Conv converter) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
Conv type of a functor for conversion of the value into type T
Parameters
index the index of the requested value
converter a functor for conversion of the value into type T
Returns
the requested value as an object of type T
Exceptions
ValueNotAvailable if no value is available with that index
ConversionFailed if the value could not be converted to type T
Conversion is performed via converter object, functor taking a string and returning an object of type std::optional<T>. The functor can decline the conversion by returning an empty std::optional, or directly throw an exception on error.
Definition at line 677 of file KeyValuesData.h.
References key(), icarus::KeyValuesData::size(), and values().
getNumber() [1/2]
template<typename T > T icarus::KeyValuesData::Item::getNumber (std::size_t index) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
Conv type of a functor for conversion of the value into type T
Parameters
index the index of the requested value
converter a functor for conversion of the value into type T
Returns
the requested value as an object of type T
Exceptions
ValueNotAvailable if no value is available with that index
ConversionFailed if the value could not be converted to type T
Conversion is performed via converter object, functor taking a string and returning an object of type std::optional<T>. The functor can decline the conversion by returning an empty std::optional, or directly throw an exception on error.
Definition at line 730 of file KeyValuesData.h.
getNumber() [2/2]
template<typename T > T icarus::KeyValuesData::Item::getNumber (std::size_t index, unsigned int base) const
Returns the requested value, converted into a number of type T
Template Parameters
T type of number to convert the value into
Parameters
index the index of the requested value
base (default: 10) numerical base of the input number
Returns
the requested value as a number of type T
Exceptions
ValueNotAvailable if no value is available with that index
ConversionFailed if the value could not be converted to type T
See getAs() for details.
Note that the number must have no base prefix (e.g. "F5" for hexadecimal rather than "0xF5").
Definition at line 723 of file KeyValuesData.h.
getOptionalAs() [1/2]
template<typename T , bool IgnoreFormatErrors = false> std::optional< T > icarus::KeyValuesData::Item::getOptionalAs (std::size_t index) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
IgnoreFormatErrors (default: true) how to treat conversion errors
Parameters
index the index of the requested value
ignoreFormatErrors (default: false) ignore conversion errors
Returns
the requested value, or an empty optional on failure
Exceptions
ConversionFailed if the value could not be converted to type T
Conversion is performed via converter object, functor taking a string and returning an object of type std::optional<T>. The functor can decline the conversion by returning an empty std::optional, or directly throw an exception on error.
If no value is available for the specified index, an empty optional is returned.
An exception is thrown on conversion failures unless IgnoreFormatErrors is true, in which case an empty optional is also returned.
Definition at line 713 of file KeyValuesData.h.
getOptionalAs() [2/2]
template<typename T , bool IgnoreFormatErrors = false, typename Conv > std::optional< T > icarus::KeyValuesData::Item::getOptionalAs (std::size_t index, Conv converter) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
IgnoreFormatErrors (default: true) how to treat conversion errors
Conv type of a functor for conversion of the value into type T
Parameters
index the index of the requested value
converter a functor for conversion of the value into type T
Returns
the requested value, or an empty optional on failure
Exceptions
ConversionFailed if the value could not be converted to type T
Conversion is performed via converter object, functor taking a string and returning an object of type std::optional<T>. The functor can decline the conversion by returning an empty std::optional, or directly throw an exception on error.
If no value is available for the specified index, an empty optional is returned.
An exception is thrown on conversion failures unless IgnoreFormatErrors is true, in which case an empty optional is also returned.
Definition at line 698 of file KeyValuesData.h.
References icarus::KeyValuesData::size().
getOptionalNumber() [1/2]
template<typename T > std::optional< T > icarus::KeyValuesData::Item::getOptionalNumber (std::size_t index) const
Returns the requested value, converted into type T
Template Parameters
T type to convert the value into
Conv type of a functor for conversion of the value into type T
Parameters
index the index of the requested value
converter a functor for conversion of the value into type T
Returns
the requested value as an object of type T
Exceptions
ValueNotAvailable if no value is available with that index
ConversionFailed if the value could not be converted to type T
Conversion is performed via converter object, functor taking a string and returning an object of type std::optional<T>. The functor can decline the conversion by returning an empty std::optional, or directly throw an exception on error.
Definition at line 743 of file KeyValuesData.h.
getOptionalNumber() [2/2]
template<typename T > std::optional< T > icarus::KeyValuesData::Item::getOptionalNumber (std::size_t index, unsigned int base) const
Returns the requested value, converted into a number of type T
Template Parameters
T type of number to convert the value into
Parameters
index the index of the requested value
base (default: 10) numerical base of the input number
Returns
the requested value, or an empty optional on failure
Exceptions
ConversionFailed if the value could not be converted to type T
See getOptionalAs() for details.
Note that the number must have no base prefix (e.g. "F5" for hexadecimal rather than "0xF5").
Definition at line 736 of file KeyValuesData.h.
getSizedVector()
template<typename T , typename Conv = details::KeyValuesConverter<T>> std::vector< T > icarus::KeyValuesData::Item::getSizedVector (Conv converter = Conv{}) const
Returns all the values, each converted into type T
Template Parameters
T type to convert the value into
Conv type of a functor for conversion of the value into type T
Parameters
converter a functor for conversion of the value into type T
Returns
a vector with all the converted values
Exceptions
MissingSize on any error converting the first value to a size
WrongSize if the actual number of values does not match the size
ConversionFailed if any value could not be converted to type T
The first value (mandatory) is converted to represent the size of the vector. That is used as verification when converting all the other elements: if there is the wrong number of elements, an exception is thrown.
Conversion of each element is performed by getAs<T, Conv>().
An exception is also thrown on conversion failure of any of the values.
Definition at line 760 of file KeyValuesData.h.
References icarus::KeyValuesData::empty(), and icarus::KeyValuesData::size().
getVector()
template<typename T , typename Conv = details::KeyValuesConverter<T>> std::vector< T > icarus::KeyValuesData::Item::getVector (Conv converter = {}) const
Returns all the values, each converted into type T
Template Parameters
T type to convert the value into
Conv type of a functor for conversion of the value into type T
Parameters
converter a functor for conversion of the value into type T
Returns
a vector with all the converted values
Exceptions
ConversionFailed if any value could not be converted to type T
Conversion of each element is performed by getAs<T, Conv>().
An exception is thrown on any conversion failure.
Definition at line 750 of file KeyValuesData.h.
key()
std::string const & icarus::KeyValuesData::Item::key () const inline noexcept
Returns the key of the item.
Definition at line 253 of file KeyValuesData.h.
Referenced by getAs(), and icarus::details::KeyedCSVparser::parse().
nValues()
std::size_t icarus::KeyValuesData::Item::nValues () const inline noexcept
Returns the number of values currently present.
Definition at line 276 of file KeyValuesData.h.
operator<()
bool icarus::KeyValuesData::Item::operator< (Item const & other) const inline noexcept
Lexicographic order by key (case-sensitive).
Definition at line 468 of file KeyValuesData.h.
optionalValue()
std::optional< std::string > icarus::KeyValuesData::Item::optionalValue (std::size_t index) const inline noexcept
Returns the value at index with no conversion, no value if not present.
Definition at line 668 of file KeyValuesData.h.
value()
std::string const & icarus::KeyValuesData::Item::value (std::size_t index = 0) const inline noexcept
Returns the value at index (unchecked) with no conversion.
Definition at line 264 of file KeyValuesData.h.
values() [1/2]
std::vector< std::string > const & icarus::KeyValuesData::Item::values () const inline noexcept
Returns the key of the item.
Definition at line 259 of file KeyValuesData.h.
values() [2/2]
std::vector< std::string > & icarus::KeyValuesData::Item::values () inline noexcept
Returns all item values, as strings.
Definition at line 258 of file KeyValuesData.h.
Referenced by getAs().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/details/KeyValuesData.h