CAF format: icarus::opdet::CustomPulseFunction< T > Class Template Reference
icarus::opdet::CustomPulseFunction< T > Class Template Reference
Describes the waveform from a single photoelectron.
#include <CustomPulseFunction.h>
Classes
struct PulseStats_t
Record of collected information on the pulse shape.
Public Types
using ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
using Time = typename Base_t::Time
Type of time being used.
using ParameterValue_t = double
Type of value for parameters (TFormula).
using NameAndValue_t = std::pair<std::string, ParameterValue_t>
Type of parameter name/value definition.
using PulseParameters_t = std::vector<NameAndValue_t>
Type of list of all function parameters.
Public Types inherited from icarus::opdet::PhotoelectronPulseFunction< T >
using ADCcount = util::quantities::counts_f
Type for ADC counts (floating point).
using Time = T
Type of time being used.
Public Member Functions
CustomPulseFunction (std::string const &expression, PulseParameters_t const &parameters, Time peakTime)
Constructor: chooses shape and the values of its parameters.
CustomPulseFunction (std::string const &expression, PulseParameters_t const &parameters, std::string const &peakTime)
Parameter accessors.
ParameterValue_t parameter (std::string const &name) const
Returns the value of the parameter specified by name.
Public Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
ADCcount evaluateAt (Time time) const
Evaluates the pulse at the given time.
ADCcount operator() (Time time) const
Alias of evaluateAt().
Time peakTime () const
Returns the time at which the first peak is found.
ADCcount peakAmplitude () const
Returns the amplitude of the first peak in ADC counts.
ADCcount baseline () const
Returns the baseline of the pulse in ADC counts.
int polarity () const
Returns the polarity of the pulse (+1: positive, or -1: negative).
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints on stream the parameters of this shape.
void dump (std::ostream &&out, std::string const &indent="") const
std::string toString (std::string const &indent, std::string const &firstIndent) const
Returns the parameters of this shape as a descriptive string.
std::string toString (std::string const &indent="") const
Private Types
using Base_t = icarus::opdet::PhotoelectronPulseFunction<T>
Private Member Functions
CustomPulseFunction (std::string const &expression, PulseParameters_t const &parameters)
Constructor implementation.
virtual ADCcount doEvaluateAt (Time time) const override
Evaluates the pulse at the given time.
virtual Time doPeakTime () const override
Returns the time at which the first peak is found.
virtual ADCcount doPeakAmplitude () const override
Returns the amplitude of the first peak in ADC counts.
virtual void doDump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const override
Prints on stream the parameters of this shape.
PulseStats_t extractStats (Time peakTime) const
Extracts statistics from pulse shape.
Static Private Member Functions
static std::string checkMissingParameters (TFormula const &formula, PulseParameters_t const &parameters)
static std::string checkExcessParameters (TFormula const &formula, PulseParameters_t const &parameters)
static void setParameters (TFormula &formula, PulseParameters_t const &parameters)
Sets the value of the parameters of formula.
Private Attributes
TFormula fFormula
Formula of the shape.
PulseStats_t fStats
Collected information about the pulse.
Additional Inherited Members
Protected Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
virtual ADCcount doBaseline () const
Returns the baseline of the pulse.
virtual int doPolarity () const
Returns the polarity of the pulse (+1 or -1).
Detailed Description
template<typename T>
class icarus::opdet::CustomPulseFunction< T >
Describes the waveform from a single photoelectron.
Template Parameters
Time type of time unit to be used
This functor (class behaving like a function) describes the shape of the response to a single photoelectron as a custom shape.
The shape is a formula interpreted via ROOT's TFormula. It is assumed to start at time 0.0 (in Time units).
Definition at line 54 of file CustomPulseFunction.h.
Class Documentation
icarus::opdet::CustomPulseFunction::PulseStats_t
struct icarus::opdet::CustomPulseFunction::PulseStats_t
template<typename T>
struct icarus::opdet::CustomPulseFunction< T >::PulseStats_t
Record of collected information on the pulse shape.
Definition at line 122 of file CustomPulseFunction.h.
Class Members
bool negativePulse Whether the pulse is considered negative.
ADCcount peakAmplitude Pulse amplitude at peak time.
Time peakTime Time of the pulse peak.
Member Typedef Documentation
ADCcount
template<typename T > using icarus::opdet::CustomPulseFunction< T >::ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
Definition at line 61 of file CustomPulseFunction.h.
Base_t
template<typename T > using icarus::opdet::CustomPulseFunction< T >::Base_t = icarus::opdet::PhotoelectronPulseFunction<T> private
Definition at line 57 of file CustomPulseFunction.h.
NameAndValue_t
template<typename T > using icarus::opdet::CustomPulseFunction< T >::NameAndValue_t = std::pair<std::string, ParameterValue_t>
Type of parameter name/value definition.
Definition at line 68 of file CustomPulseFunction.h.
ParameterValue_t
template<typename T > using icarus::opdet::CustomPulseFunction< T >::ParameterValue_t = double
Type of value for parameters (TFormula).
Definition at line 65 of file CustomPulseFunction.h.
PulseParameters_t
template<typename T > using icarus::opdet::CustomPulseFunction< T >::PulseParameters_t = std::vector<NameAndValue_t>
Type of list of all function parameters.
Definition at line 71 of file CustomPulseFunction.h.
Time
template<typename T > using icarus::opdet::CustomPulseFunction< T >::Time = typename Base_t::Time
Type of time being used.
Definition at line 63 of file CustomPulseFunction.h.
Constructor & Destructor Documentation
CustomPulseFunction() [1/3]
template<typename T > icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction (std::string const & expression, PulseParameters_t const & parameters, Time peakTime)
Constructor: chooses shape and the values of its parameters.
Parameters
expression mathematical expression of pulse shape
parameters the list of named parameters and their values
peakTime expression of time of the maximum amplitude of the shape
The shape mathematical expression must be compatible with ROOT 6 TFormula. The formula must have a single independent variable, time measured in the Time scale. The value 0 of that time corresponds to when the photoelectron is emitted from the photocathode.
The peak time argument is used to report when the peak happens. It would be possible to compute it in a general way, but the implementation of that functionality is complicate enough to get it right and fast, that it's better to rely on user's knowledge. The value may be either a number or a string. The number (Time) directly represents the time of the peak, while the expression is another TFormula expression that can use the same parameters as the shape expression, so that for example it is possible to indicate the peak time of a shape like exp(-(x - [mu])**2) as [mu]. In this case, the peak time expression must use no variable.
Definition at line 197 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::extractStats(), icarus::opdet::CustomPulseFunction< T >::fStats, and icarus::opdet::PhotoelectronPulseFunction< T >::peakTime().
CustomPulseFunction() [2/3]
template<typename T > icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction (std::string const & expression, PulseParameters_t const & parameters, std::string const & peakTime)
Definition at line 210 of file CustomPulseFunction.h.
CustomPulseFunction() [3/3]
template<typename T > icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction (std::string const & expression, PulseParameters_t const & parameters) private
Constructor implementation.
Definition at line 231 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::checkExcessParameters(), icarus::opdet::CustomPulseFunction< T >::checkMissingParameters(), icarus::opdet::CustomPulseFunction< T >::fFormula, and icarus::opdet::CustomPulseFunction< T >::setParameters().
Member Function Documentation
checkExcessParameters()
template<typename T > std::string icarus::opdet::CustomPulseFunction< T >::checkExcessParameters (TFormula const & formula, PulseParameters_t const & parameters) static private
Returns a message about parameters which are not in formula.
Returns
a message about excess parameters, empty if none
Definition at line 317 of file CustomPulseFunction.h.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction().
checkMissingParameters()
template<typename T > std::string icarus::opdet::CustomPulseFunction< T >::checkMissingParameters (TFormula const & formula, PulseParameters_t const & parameters) static private
Returns a message about parameters in formula missing in parameters.
Returns
a message about missing parameters, empty if none
Definition at line 289 of file CustomPulseFunction.h.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction().
doDump()
template<typename T > void icarus::opdet::CustomPulseFunction< T >::doDump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const override private virtual
Prints on stream the parameters of this shape.
Parameters
out the stream to write into
indent indentation string, prepended to all lines except first
indentFirst indentation string prepended to the first line
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 266 of file CustomPulseFunction.h.
doEvaluateAt()
template<typename T > virtual ADCcount icarus::opdet::CustomPulseFunction< T >::doEvaluateAt (Time time) const inline override private virtual
Evaluates the pulse at the given time.
Parameters
time time to evaluate the shape at
The scale of the time is defined by the transition time passed at construction.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 149 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::fFormula.
doPeakAmplitude()
template<typename T > virtual ADCcount icarus::opdet::CustomPulseFunction< T >::doPeakAmplitude () const inline override private virtual
Returns the amplitude of the first peak in ADC counts.
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 156 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::fStats, and icarus::opdet::CustomPulseFunction< T >::PulseStats_t::peakAmplitude.
doPeakTime()
template<typename T > virtual Time icarus::opdet::CustomPulseFunction< T >::doPeakTime () const inline override private virtual
Returns the time at which the first peak is found.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 153 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::fStats, and icarus::opdet::CustomPulseFunction< T >::PulseStats_t::peakTime.
extractStats()
template<typename T > auto icarus::opdet::CustomPulseFunction< T >::extractStats (Time peakTime) const private
Extracts statistics from pulse shape.
Definition at line 251 of file CustomPulseFunction.h.
References icarus::opdet::CustomPulseFunction< T >::PulseStats_t::negativePulse, icarus::opdet::CustomPulseFunction< T >::PulseStats_t::peakAmplitude, and icarus::opdet::CustomPulseFunction< T >::PulseStats_t::peakTime.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction().
parameter()
template<typename T > ParameterValue_t icarus::opdet::CustomPulseFunction< T >::parameter (std::string const & name) const
Returns the value of the parameter specified by name.
setParameters()
template<typename T > void icarus::opdet::CustomPulseFunction< T >::setParameters (TFormula & formula, PulseParameters_t const & parameters) static private
Sets the value of the parameters of formula.
Definition at line 345 of file CustomPulseFunction.h.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction().
Member Data Documentation
fFormula
template<typename T > TFormula icarus::opdet::CustomPulseFunction< T >::fFormula private
Formula of the shape.
Definition at line 129 of file CustomPulseFunction.h.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction(), and icarus::opdet::CustomPulseFunction< T >::doEvaluateAt().
fStats
template<typename T > PulseStats_t icarus::opdet::CustomPulseFunction< T >::fStats private
Collected information about the pulse.
Definition at line 131 of file CustomPulseFunction.h.
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction(), icarus::opdet::CustomPulseFunction< T >::doPeakAmplitude(), and icarus::opdet::CustomPulseFunction< T >::doPeakTime().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Algorithms/CustomPulseFunction.h