CAF format: icarus::trigger::DiscriminatedAdderSignal Class Reference
icarus::trigger::DiscriminatedAdderSignal Class Reference
Produces discriminated optical waveforms for PMT adders.
Classes
struct Config
Public Types
using microseconds = util::quantities::intervals::microseconds
using TriggerGateData_t = icarus::trigger::OpticalTriggerGate::GateData_t
The type of data produced for a single channel.
using Parameters = art::SharedProducer::Table<Config>
Public Member Functions
DiscriminatedAdderSignal (Parameters const &config, art::ProcessingFrame const &frame)
virtual void produce (art::Event &event, art::ProcessingFrame const &) override
Creates the data products.
template<typename BIter , typename EIter >
auto computeSimpleBaselines (BIter begin, EIter end, microseconds interval) const -> std::pair< double, double >
template<typename Waveform >
auto computeSimpleBaselines (Waveform const &waveform, microseconds interval) const -> std::pair< double, double >
Private Types
using electronics_time = detinfo::timescales::electronics_time
using WaveformWithBaseline = icarus::trigger::WaveformWithBaseline
using RelTimeInterval_t = icarus::ns::util::TimeInterval<microseconds>
Time interval from an unspecified reference.
using TimeInterval_t = icarus::ns::util::TimeInterval<electronics_time>
Time interval in electronics time.
using WaveformsByChannel_t = icarus::ns::util::GroupByIndex<WaveformWithBaseline>
Map of waveform information records per channel.
Private Member Functions
std::pair< raw::OpDetWaveform, std::vector< WaveformWithBaseline const * > > makeAdderWaveform (TimeInterval_t const &timeInterval, std::vector< std::vector< WaveformWithBaseline const * > > const &waveforms, raw::Channel_t channel=std::numeric_limits< raw::Channel_t >::max()) const
Returns the samples of a waveform added from the specified ones.
void removeChannels (std::vector< raw::Channel_t > &channels) const
Removes the channels configured as missing from a channelList.
bool isMissingChannel (raw::Channel_t channel) const
Returns whether channel is in the configured missing channel list.
TimeInterval_t computeTimeInterval (std::vector< std::vector< WaveformWithBaseline const * > > const &waveforms, TimeInterval_t const &timeInterval) const
Returns the time interval where the waveforms should be added.
std::pair< std::valarray< float >, std::vector< WaveformWithBaseline const * > > addWaveformsInInterval (TimeInterval_t const &timeInterval, std::vector< std::vector< WaveformWithBaseline const * > > const &waveforms, raw::Channel_t channel=std::numeric_limits< raw::Channel_t >::max()) const
Returns the samples of a waveform added from the specified ones.
template<typename Samples >
raw::OpDetWaveform packWaveform (raw::Channel_t channel, electronics_time startTime, Samples const &samples) const
Packs the specified samples at startTime into a raw::OpDetWaveform.
TimeInterval_t waveformTimeCoverage (raw::OpDetWaveform const &waveform) const
Returns the interval covered by the waveform, in electronics time.
icarus::trigger::TriggerWindowDefs_t createAdderWindows (geo::GeometryCore const &geom) const
Returns the PMT channel composition of each adder window.
template<typename StartTime , typename StopTime >
std::ptrdiff_t tickDistance (StartTime start, StopTime time) const
Returns the number of optical ticks from start to stop.
template<typename BIter , typename EIter >
std::pair< double, double > computeSimpleBaselines (BIter begin, EIter end, microseconds interval) const
template<typename Waveform >
std::pair< double, double > computeSimpleBaselines (Waveform const &added, microseconds interval) const
Static Private Member Functions
static WaveformsByChannel_t groupByChannel (std::vector< WaveformWithBaseline > const &waveformInfo)
template<typename T >
static constexpr util::quantities::millivolt to_mV (util::quantities::counts_as< T > ADC)
Converts an ADC count into voltage of a 14 bit ADC, 2 V peak-to-peak.
Private Attributes
art::InputTag const fWaveformTag
Input optical waveform tag.
art::InputTag const fBaselineTag
Input waveform baseline tag.
art::InputTag const fWaveformMetaTag
Input waveform metadata tag.
float const fAmplitudeScale
Scale factor for input waveform amplitude.
RelTimeInterval_t const fTimeInterval
Range of time to create adders on.
std::map< icarus::trigger::ADCCounts_t, std::string > fSelectedThresholds
Thresholds selected for saving, and their instance name.
std::vector< raw::Channel_t > const fMissingChannels
Channels to skip.
bool const fSaveWaveforms
Whether to save raw::OpDetWaveform.
bool const fSavePMTcoverage
Whether to save sbn::OpDetWaveformMeta.
bool const fSaveMetaAssns
Whether to save input waveform associations.
int const fAdderChannelOffset
Channel number offset for adder waveforms.
unsigned int const fChannelsPerAdder
Channels per adder.
std::string const fLogCategory
Category name for the console output stream.
std::unique_ptr< icarus::trigger::TriggerGateBuilder > fTriggerGateBuilder
Algorithms to simulate trigger gates out of optical channel output.
geo::GeometryCore const & fGeom
Cached geometry service provider.
microseconds const fOpticalTick
Duration of an optical tick.
Static Private Attributes
static constexpr double mVperADC = 2'000. / (1<<14)
Conversion from ADC# to mV for an ADC sampling 2 V with 14 bits.
static std::string const AdderDataProductSuffix { "adder" }
Suffix used for the instance name of some data products.
static std::string const PMTDataProductSuffix { "" }
Suffix used for the instance name of some data products.
Detailed Description
Produces discriminated optical waveforms for PMT adders.
This module produces a "discriminated waveform" for each adder module and for each configured threshold, via an algorithm of the class of icarus::trigger::TriggerGateBuilder (TriggerGateBuilder configuration parameter).
The input is PMT optical waveforms: this module composes them into added analogue signals, then discriminates them. No distortion is applied to the PMT waveforms before or after the addition.
Thresholds are ultimately chosen by the tool in charge of actually running the discrimination algorithm. Out of the thresholds that this algorithm produces, it is possible to choose only a subset of them (SelectThresholds).
Output data products
std::vector<raw::OpDetWaveform>, std::vector<icarus::WaveformBaseline> and their one-to-one associations (only if SaveWaveforms is set): waveforms from the adders; in this emulation, the waveforms are "reproduced" from the already digitized PMT waveforms, in contrast with the hardware which performs an analogue sum. The channel number is unique on each of them, but it has no set meaning beyond that. In addition, a baseline object is saved for each waveform (their baseline is 0 by construction since they originate from baseline-subtracted PMT waveforms), and an association art::Assns<raw::OpDetWaveform, icarus::WaveformBaseline>between them (which is trivial since the two data products are parallel).
std::vector<sbn::OpDetWaveformMeta> (only if SavePMTcoverage is set): parallel to the std::vector<raw::OpDetWaveform> data product, each entry in the collection is matched with the corresponding one in the adder waveform collection; if SaveWaveforms is set, an association art::Assns<raw::OpDetWaveform, sbn::OpDetWaveformMeta> is also produced (which is also trivial since the two data products are parallel).
for each threshold thr (in ADC counts), data products are created with an instance name equivalent to the threshold (e.g. for a threshold of 700 ADC counts, the data product instance name will be "700"):
a data product of type std::vector<icarus::trigger::OpticalTriggerGate::GateData_t>, with one entry per adder module; each gate object has as index in the vector the number of the optical channel;
an art association, one trigger gate data to many optical waveforms, of each trigger gate data (as above) with all the optical waveforms which contributed to it; the order of the association pairs is the same as the one of the trigger gate data, i.e. by channel, and some trigger gate data entries may be not associated to any waveform and therefore they can not be listed in the association; association pairs within the same optical channel are sorted by optical waveform timestamp; the type of the association is art::Assns<icarus::trigger::OpticalTriggerGate::GateData_t, raw::OpDetWaveform>. If SaveMetaAssns is set, also an association art::Assns<icarus::trigger::OpticalTriggerGate::GateData_t, sbn::OpDetWaveformMeta> (just like the previous one, but associating to the waveform metadata instead of the waveform itself).
ifSaveWaveformsis set, an association art::Assns<icarus::trigger::OpticalTriggerGate::GateData_t, raw::OpDetWaveform> to the adder waveforms; this will have the stringadderappended to the instance name, to distinguish it from the associations to the PMT waveforms.
ifSavePMTcoverageis set, an association art::Assns<icarus::trigger::OpticalTriggerGate::GateData_t, sbn::OpDetWaveformMeta> to the adder waveform metadata; this will have the stringadders` appended to the instance name, for consistency with the associations of the same trigger gate objects to the PMT waveforms.
Input data products
std::vector<raw::OpDetWaveform> (WaveformTag): a single waveform for each recorded optical detector activity; the activity belongs to a single channel, but there may be multiple waveforms on the same channel. The time stamp is expected to be from the electronics time scale and therefore expressed in microseconds.
art::Assns<raw::OpDetWaveform, icarus::WaveformBaseline> (BaselineTag): the baseline associated to each of the input waveforms.
art::Assns<raw::OpDetWaveform, sbn::OpDetWaveformMeta> (WaveformTag; only if SaveMetaAssns is set): associations between the input waveforms and their metadata (will be used to create associations to the discriminated waveforms).
Service requirements
The following services are required:
Geometry (for window definition)
an implementation of detinfo::DetectorClocksService
art message facility
Configuration parameters
A terse description of the parameters is printed by running lar --print-description DiscriminatedAdderSignal.
WaveformTag (input tag): the data product containing all optical detector waveforms.
BaselineTag (input tag): the data product containing the association between each input waveform (WaveformTag) and its estimated baseline.
WaveformMetaTag (input tag, optional): the data product containing the association between each input waveform (WaveformTag) and its metadata; if omitted, the tag from WaveformTag is used.
AmplitudeScale (real number, default: 1.0): how much to scale each input waveform.
TimeInterval (table, optional): limits the time range of the adders to the specified time interval; all time points are relative to the beam gate opening time. No more than two of the following must be specified:
Start (time, default: ages ago): start from this time point.
End (time, default: ages in the future): end at this time point.
Duration (time, default: ages): duration of the time interval.
MissingChannels (list of integers): list of the PMT channel numbers (as reported in the WaveformTag input collection) to be excluded. Note that in the hardware bad channels may be included in the adder input.
TriggerGateBuilder (tool configuration): configuration of the art tool used to discriminate the optional waveforms; the tool interface is icarus::trigger::TriggerGateBuilder.
SelectThresholds (sequence of ADC thresholds): if specified, only the waveforms discriminated with the thresholds in this list will be saved by the module; if not specified, all the thresholds produced by the algorithm will be saved.
Note
If a requested threshold is not eventually produced by the algorithm, an exception will be thrown by the module.
ChannelOffset (integer, default: 15000): this offset is added to the channel number of the waveforms of the adders.
ChannelsPerAdder (positive integer, default: 15): PMT are added in groups of this many into each adder channel. The PMT are split in walls and then grouped longitudinally. This number must be a divisor of the number of PMT on the wall (e.g. in ICARUS there are 90 PMT, so this value can only be 1, 2, 3, 5, 6, 9, 10, 15, 18, 30, 45 or 90).
SaveWaveforms (flag, default: false): if set, the waveforms from the adders are saved, otherwise only the discriminated waveforms are.
SavePMTcoverage (flag, default: true): produces a collection of sbn::OpDetWaveformMeta representing each of the output waveforms; trigger tools can use this information in place for the more space-hungry waveforms for further processing.
SaveMetaAssns (flag, default: true): if set, an association between the metadata of the input waveforms (from WaveformTag) and the discriminated waveforms is also saved.
LogCategory (string, default: "DiscriminatedAdderSignal"): label for the category of messages in the console output; this is the label that can be used for filtering messages via MessageFacility service configuration.
Definition at line 238 of file DiscriminatedAdderSignal_module.cc.
Class Documentation
icarus::trigger::DiscriminatedAdderSignal::Config
struct icarus::trigger::DiscriminatedAdderSignal::Config
Definition at line 249 of file DiscriminatedAdderSignal_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< float > AmplitudeScale
Atom< InputTag > BaselineTag
Atom< int > ChannelOffset
Atom< unsigned int > ChannelsPerAdder
Atom< string > LogCategory
Sequence< Channel_t > MissingChannels
Atom< bool > SaveMetaAssns
Atom< bool > SavePMTcoverage
Atom< bool > SaveWaveforms
OptionalSequence< ADC_Count_t > SelectThresholds
TimeIntervalOptionalTable< microseconds > TimeInterval
DelegatedParameter TriggerGateBuilder_
OptionalAtom< InputTag > WaveformMetaTag
Atom< InputTag > WaveformTag
Member Typedef Documentation
electronics_time
using icarus::trigger::DiscriminatedAdderSignal::electronics_time = detinfo::timescales::electronics_time private
Definition at line 362 of file DiscriminatedAdderSignal_module.cc.
microseconds
using icarus::trigger::DiscriminatedAdderSignal::microseconds = util::quantities::intervals::microseconds
Definition at line 242 of file DiscriminatedAdderSignal_module.cc.
Parameters
using icarus::trigger::DiscriminatedAdderSignal::Parameters = art::SharedProducer::Table<Config>
Definition at line 343 of file DiscriminatedAdderSignal_module.cc.
RelTimeInterval_t
using icarus::trigger::DiscriminatedAdderSignal::RelTimeInterval_t = icarus::ns::util::TimeInterval<microseconds> private
Time interval from an unspecified reference.
Definition at line 366 of file DiscriminatedAdderSignal_module.cc.
TimeInterval_t
using icarus::trigger::DiscriminatedAdderSignal::TimeInterval_t = icarus::ns::util::TimeInterval<electronics_time> private
Time interval in electronics time.
Definition at line 369 of file DiscriminatedAdderSignal_module.cc.
TriggerGateData_t
using icarus::trigger::DiscriminatedAdderSignal::TriggerGateData_t = icarus::trigger::OpticalTriggerGate::GateData_t
The type of data produced for a single channel.
Definition at line 245 of file DiscriminatedAdderSignal_module.cc.
WaveformsByChannel_t
using icarus::trigger::DiscriminatedAdderSignal::WaveformsByChannel_t = icarus::ns::util::GroupByIndex<WaveformWithBaseline> private
Map of waveform information records per channel.
Definition at line 372 of file DiscriminatedAdderSignal_module.cc.
WaveformWithBaseline
using icarus::trigger::DiscriminatedAdderSignal::WaveformWithBaseline = icarus::trigger::WaveformWithBaseline private
Definition at line 363 of file DiscriminatedAdderSignal_module.cc.
Constructor & Destructor Documentation
DiscriminatedAdderSignal()
icarus::trigger::DiscriminatedAdderSignal::DiscriminatedAdderSignal (Parameters const & config, art::ProcessingFrame const & frame) explicit
Definition at line 629 of file DiscriminatedAdderSignal_module.cc.
Member Function Documentation
addWaveformsInInterval()
auto icarus::trigger::DiscriminatedAdderSignal::addWaveformsInInterval (TimeInterval_t const & timeInterval, std::vector< std::vector< WaveformWithBaseline const * > > const & waveforms, raw::Channel_t channel = std::numeric_limits<raw::Channel_t>::max()) const private
Returns the samples of a waveform added from the specified ones.
Parameters
timeInterval the interval to fill
waveforms the list of waveforms (plus baseline) to include
channel (default: max possible value) channel number to assign
Returns
the added waveform and the list of the contributing waveforms
The returned waveform exactly covers the timeInterval. The input waveforms are assumed to be grouped by channel: each entry in waveforms is assumed to be the list of pointers to information records for all the relevant waveform on the same channel (empty lists are ignored, and there is no way to know which channel they might have belonged to). The returned list includes all and only the waveforms which have at least one sample in the requested time interval.
It is assumed that for each channel one of the input waveforms covers the whole timeInterval.
Definition at line 1237 of file DiscriminatedAdderSignal_module.cc.
References icarus::WaveformBaseline::baseline().
computeSimpleBaselines() [1/4]
template<typename BIter , typename EIter > std::pair< double, double > icarus::trigger::DiscriminatedAdderSignal::computeSimpleBaselines (BIter begin, EIter end, microseconds interval) const private
Returns a crude baseline estimation at the first interval and at the last one. The baseline is just the arithmetic average. This method takes the begin and end iterator to the waveform data.
computeSimpleBaselines() [2/4]
template<typename BIter , typename EIter > auto icarus::trigger::DiscriminatedAdderSignal::computeSimpleBaselines (BIter begin, EIter end, microseconds interval) const -> std::pair<double, double>
Definition at line 1409 of file DiscriminatedAdderSignal_module.cc.
computeSimpleBaselines() [3/4]
template<typename Waveform > std::pair< double, double > icarus::trigger::DiscriminatedAdderSignal::computeSimpleBaselines (Waveform const & added, microseconds interval) const private
Returns a crude baseline estimation at the first interval and at the last one. The baseline is just the arithmetic average. This method takes the whole waveform data collection.
computeSimpleBaselines() [4/4]
template<typename Waveform > auto icarus::trigger::DiscriminatedAdderSignal::computeSimpleBaselines (Waveform const & waveform, microseconds interval) const -> std::pair<double, double>
Definition at line 1425 of file DiscriminatedAdderSignal_module.cc.
computeTimeInterval()
auto icarus::trigger::DiscriminatedAdderSignal::computeTimeInterval (std::vector< std::vector< WaveformWithBaseline const * > > const & waveforms, TimeInterval_t const & timeInterval) const private
Returns the time interval where the waveforms should be added.
Parameters
waveforms the input waveforms, grouped by channel
timeInterval the interval outside we are not interested in adding
Returns
a time interval where addition should happen
The waveforms are specified as lists of pointers to waveform information records, each list pertaining a single channel. The information used from the record is the timestamp and the number of samples, both learnt from the optical waveform object.
The returned interval is guaranteed to be fully covered with data from all the channels in the input, and it never extends beyond timeInterval. It is possible that there is no sample available at all, in which case the returned interval is empty (starting and ending at timeInterval.start).
Definition at line 1144 of file DiscriminatedAdderSignal_module.cc.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::setOpeningAt().
createAdderWindows()
icarus::trigger::TriggerWindowDefs_t icarus::trigger::DiscriminatedAdderSignal::createAdderWindows (geo::GeometryCore const & geom) const private
Returns the PMT channel composition of each adder window.
Parameters
geom LArSoft geometry service provider
Returns
a list of adder windows, each with it list of contributing channels
Windows are defined as groups of 15 channels. The MissingChannels are not included in any window.
Definition at line 1372 of file DiscriminatedAdderSignal_module.cc.
groupByChannel()
auto icarus::trigger::DiscriminatedAdderSignal::groupByChannel (std::vector< WaveformWithBaseline > const & waveformInfo) static private
Returns a map channel -> waveforms on that channel. If waveformInfo changes, the returned map becomes invalid.
Definition at line 1388 of file DiscriminatedAdderSignal_module.cc.
isMissingChannel()
bool icarus::trigger::DiscriminatedAdderSignal::isMissingChannel (raw::Channel_t channel) const private
Returns whether channel is in the configured missing channel list.
Definition at line 1088 of file DiscriminatedAdderSignal_module.cc.
makeAdderWaveform()
auto icarus::trigger::DiscriminatedAdderSignal::makeAdderWaveform (TimeInterval_t const & timeInterval, std::vector< std::vector< WaveformWithBaseline const * > > const & waveforms, raw::Channel_t channel = std::numeric_limits<raw::Channel_t>::max()) const private
Returns the samples of a waveform added from the specified ones.
Parameters
timeInterval the interval to constrain the waveform into
waveforms the list of waveforms (plus baseline) to include
channel (default: max possible value) channel number to assign
Returns
the added waveform and the list of the contributing waveforms
The returned waveform starts at either timeInterval.start or the earliest of the specified waveform start times. Likewise, the waveform ends at either timeInterval.end or the latest of the waveform end times.
The input waveforms are assumed to be grouped by channel: each entry in waveforms is assumed to be the list of pointers to information records for all the relevant waveform on the same channel (empty lists are ignored, and there is no way to know which channel they might have belonged to).
This function uses computeTimeInterval() to determine the actual time interval that the added waveform needs to cover, and it performs the addition with addWaveformsInInterval(). See the documentation of those methods for additional details. The returned list includes all and only the waveforms which have at least one sample in the requested time interval.
Definition at line 1097 of file DiscriminatedAdderSignal_module.cc.
packWaveform()
template<typename Samples > raw::OpDetWaveform icarus::trigger::DiscriminatedAdderSignal::packWaveform (raw::Channel_t channel, electronics_time startTime, Samples const & samples) const private
Packs the specified samples at startTime into a raw::OpDetWaveform.
Definition at line 1338 of file DiscriminatedAdderSignal_module.cc.
produce()
void icarus::trigger::DiscriminatedAdderSignal::produce (art::Event & event, art::ProcessingFrame const &) override virtual
Creates the data products.
Definition at line 761 of file DiscriminatedAdderSignal_module.cc.
References icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >::addChannel().
removeChannels()
void icarus::trigger::DiscriminatedAdderSignal::removeChannels (std::vector< raw::Channel_t > & channels) const private
Removes the channels configured as missing from a channelList.
Parameters
channels the list of channels (see the description)
Returns
channels list except for the "missing" ones
Definition at line 1077 of file DiscriminatedAdderSignal_module.cc.
tickDistance()
template<typename StartTime , typename StopTime > std::ptrdiff_t icarus::trigger::DiscriminatedAdderSignal::tickDistance (StartTime start, StopTime time) const private
Returns the number of optical ticks from start to stop.
Definition at line 1400 of file DiscriminatedAdderSignal_module.cc.
to_mV()
template<typename T > static constexpr util::quantities::millivolt icarus::trigger::DiscriminatedAdderSignal::to_mV (util::quantities::counts_as< T > ADC) inline static constexpr private
Converts an ADC count into voltage of a 14 bit ADC, 2 V peak-to-peak.
Definition at line 567 of file DiscriminatedAdderSignal_module.cc.
waveformTimeCoverage()
auto icarus::trigger::DiscriminatedAdderSignal::waveformTimeCoverage (raw::OpDetWaveform const & waveform) const private
Returns the interval covered by the waveform, in electronics time.
Definition at line 1361 of file DiscriminatedAdderSignal_module.cc.
Member Data Documentation
AdderDataProductSuffix
std::string const icarus::trigger::DiscriminatedAdderSignal::AdderDataProductSuffix { "adder" } static private
Suffix used for the instance name of some data products.
Definition at line 623 of file DiscriminatedAdderSignal_module.cc.
fAdderChannelOffset
int const icarus::trigger::DiscriminatedAdderSignal::fAdderChannelOffset private
Channel number offset for adder waveforms.
Definition at line 401 of file DiscriminatedAdderSignal_module.cc.
fAmplitudeScale
float const icarus::trigger::DiscriminatedAdderSignal::fAmplitudeScale private
Scale factor for input waveform amplitude.
Definition at line 386 of file DiscriminatedAdderSignal_module.cc.
fBaselineTag
art::InputTag const icarus::trigger::DiscriminatedAdderSignal::fBaselineTag private
Input waveform baseline tag.
Definition at line 382 of file DiscriminatedAdderSignal_module.cc.
fChannelsPerAdder
unsigned int const icarus::trigger::DiscriminatedAdderSignal::fChannelsPerAdder private
Channels per adder.
Definition at line 403 of file DiscriminatedAdderSignal_module.cc.
fGeom
geo::GeometryCore const& icarus::trigger::DiscriminatedAdderSignal::fGeom private
Cached geometry service provider.
Definition at line 421 of file DiscriminatedAdderSignal_module.cc.
fLogCategory
std::string const icarus::trigger::DiscriminatedAdderSignal::fLogCategory private
Category name for the console output stream.
Definition at line 406 of file DiscriminatedAdderSignal_module.cc.
fMissingChannels
std::vector<raw::Channel_t> const icarus::trigger::DiscriminatedAdderSignal::fMissingChannels private
Channels to skip.
Definition at line 393 of file DiscriminatedAdderSignal_module.cc.
fOpticalTick
microseconds const icarus::trigger::DiscriminatedAdderSignal::fOpticalTick private
Duration of an optical tick.
Definition at line 423 of file DiscriminatedAdderSignal_module.cc.
fSaveMetaAssns
bool const icarus::trigger::DiscriminatedAdderSignal::fSaveMetaAssns private
Whether to save input waveform associations.
Definition at line 399 of file DiscriminatedAdderSignal_module.cc.
fSavePMTcoverage
bool const icarus::trigger::DiscriminatedAdderSignal::fSavePMTcoverage private
Whether to save sbn::OpDetWaveformMeta.
Definition at line 397 of file DiscriminatedAdderSignal_module.cc.
fSaveWaveforms
bool const icarus::trigger::DiscriminatedAdderSignal::fSaveWaveforms private
Whether to save raw::OpDetWaveform.
Definition at line 395 of file DiscriminatedAdderSignal_module.cc.
fSelectedThresholds
std::map<icarus::trigger::ADCCounts_t, std::string> icarus::trigger::DiscriminatedAdderSignal::fSelectedThresholds private
Thresholds selected for saving, and their instance name.
Definition at line 391 of file DiscriminatedAdderSignal_module.cc.
fTimeInterval
RelTimeInterval_t const icarus::trigger::DiscriminatedAdderSignal::fTimeInterval private
Range of time to create adders on.
Definition at line 388 of file DiscriminatedAdderSignal_module.cc.
fTriggerGateBuilder
std::unique_ptr<icarus::trigger::TriggerGateBuilder> icarus::trigger::DiscriminatedAdderSignal::fTriggerGateBuilder private
Algorithms to simulate trigger gates out of optical channel output.
Definition at line 414 of file DiscriminatedAdderSignal_module.cc.
fWaveformMetaTag
art::InputTag const icarus::trigger::DiscriminatedAdderSignal::fWaveformMetaTag private
Input waveform metadata tag.
Definition at line 384 of file DiscriminatedAdderSignal_module.cc.
fWaveformTag
art::InputTag const icarus::trigger::DiscriminatedAdderSignal::fWaveformTag private
Input optical waveform tag.
Definition at line 380 of file DiscriminatedAdderSignal_module.cc.
mVperADC
double icarus::trigger::DiscriminatedAdderSignal::mVperADC = 2'000. / (1<<14) static constexpr private
Conversion from ADC# to mV for an ADC sampling 2 V with 14 bits.
Definition at line 375 of file DiscriminatedAdderSignal_module.cc.
PMTDataProductSuffix
std::string const icarus::trigger::DiscriminatedAdderSignal::PMTDataProductSuffix { "" } static private
Suffix used for the instance name of some data products.
Definition at line 625 of file DiscriminatedAdderSignal_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/DiscriminatedAdderSignal_module.cc