CAF format: util::ArtHandleTrackerInterface< Event > Struct Template Reference
util::ArtHandleTrackerInterface< Event > Struct Template Reference abstract
Interface to facilitate the use of util::ArtHandleTracker specializations.
#include <ArtHandleTrackerManager.h>
Public Member Functions
virtual ~ArtHandleTrackerInterface ()=default
Virtual destructor (does nothing).
bool removeCachedProduct ()
std::any handlePtr () const
Returns a container for a pointer to the managed handle. Caveat emptor.
std::string productClass () const
Returns the name of the class of handled data product.
std::type_info const * productType () const
Returns the name of the class of handled data product.
art::InputTag inputTag () const
Returns the tag of handled data product.
bool hasSameDataProduct (util::ArtHandleTrackerInterface< Event > const &other) const
Returns whether this and the other objects handle the same data product.
Protected Member Functions
virtual bool doRemoveCachedProduct ()=0
Deferred implementation of removeCachedProduct().
virtual std::any doHandlePtr () const =0
Deferred implementation of handlePtr().
virtual std::string doProductClass () const =0
Deferred implementation of productClass().
virtual std::type_info const * doProductType () const =0
Deferred implementation of productType().
virtual art::InputTag doInputTag () const =0
Deferred implementation of inputTag().
Detailed Description
template<typename Event>
struct util::ArtHandleTrackerInterface< Event >
Interface to facilitate the use of util::ArtHandleTracker specializations.
This is NOT able to return the type of handle it's handling.
Definition at line 593 of file ArtHandleTrackerManager.h.
Constructor & Destructor Documentation
~ArtHandleTrackerInterface()
template<typename Event > virtual util::ArtHandleTrackerInterface< Event >::~ArtHandleTrackerInterface () virtual default
Virtual destructor (does nothing).
Member Function Documentation
doHandlePtr()
template<typename Event > virtual std::any util::ArtHandleTrackerInterface< Event >::doHandlePtr () const protected pure virtual
Deferred implementation of handlePtr().
Implemented in util::details::ArtHandleTracker< Event, Handle >.
Referenced by util::ArtHandleTrackerInterface< Event >::handlePtr().
doInputTag()
template<typename Event > virtual art::InputTag util::ArtHandleTrackerInterface< Event >::doInputTag () const protected pure virtual
Deferred implementation of inputTag().
Implemented in util::details::ArtHandleTracker< Event, Handle >.
Referenced by util::ArtHandleTrackerInterface< Event >::inputTag().
doProductClass()
template<typename Event > virtual std::string util::ArtHandleTrackerInterface< Event >::doProductClass () const protected pure virtual
Deferred implementation of productClass().
Implemented in util::details::ArtHandleTracker< Event, Handle >.
Referenced by util::ArtHandleTrackerInterface< Event >::productClass().
doProductType()
template<typename Event > virtual std::type_info const * util::ArtHandleTrackerInterface< Event >::doProductType () const protected pure virtual
Deferred implementation of productType().
Implemented in util::details::ArtHandleTracker< Event, Handle >.
Referenced by util::ArtHandleTrackerInterface< Event >::productType().
doRemoveCachedProduct()
template<typename Event > virtual bool util::ArtHandleTrackerInterface< Event >::doRemoveCachedProduct () protected pure virtual
Deferred implementation of removeCachedProduct().
Implemented in util::details::ArtHandleTracker< Event, Handle >.
Referenced by util::ArtHandleTrackerInterface< Event >::removeCachedProduct().
handlePtr()
template<typename Event > std::any util::ArtHandleTrackerInterface< Event >::handlePtr () const inline
Returns a container for a pointer to the managed handle. Caveat emptor.
Definition at line 604 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::doHandlePtr().
hasSameDataProduct()
template<typename Event > bool util::ArtHandleTrackerInterface< Event >::hasSameDataProduct (util::ArtHandleTrackerInterface< Event > const & other) const inline
Returns whether this and the other objects handle the same data product.
Definition at line 616 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::inputTag(), and util::ArtHandleTrackerInterface< Event >::productType().
inputTag()
template<typename Event > art::InputTag util::ArtHandleTrackerInterface< Event >::inputTag () const inline
Returns the tag of handled data product.
Definition at line 613 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::doInputTag().
Referenced by util::ArtHandleTrackerInterface< Event >::hasSameDataProduct().
productClass()
template<typename Event > std::string util::ArtHandleTrackerInterface< Event >::productClass () const inline
Returns the name of the class of handled data product.
Definition at line 607 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::doProductClass().
productType()
template<typename Event > std::type_info const * util::ArtHandleTrackerInterface< Event >::productType () const inline
Returns the name of the class of handled data product.
Definition at line 610 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::doProductType().
Referenced by util::ArtHandleTrackerInterface< Event >::hasSameDataProduct().
removeCachedProduct()
template<typename Event > bool util::ArtHandleTrackerInterface< Event >::removeCachedProduct () inline
Removes the cached data product from event. Handle is cleared and won't be valid any more.
Definition at line 600 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerInterface< Event >::doRemoveCachedProduct().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h