CAF format: icarus::HitCollectionAssociator Class Reference
icarus::HitCollectionAssociator Class Reference
A class handling a collection of hits and its associations.
#include <HitCreator.h>
Public Member Functions
void use_hits (std::unique_ptr< std::vector< icarus::Hit > > &&srchits)
Uses the specified collection as data product.
void put_into (art::Event &)
Moves the data into the event.
void put_into ()
Moves the data into the event.
Constructors
HitCollectionAssociator (art::Event &event, std::string instance_name, art::InputTag const &WireModuleLabel, art::InputTag const &RawDigitModuleLabel)
Constructor: sets instance name and whether to build associations.
HitCollectionAssociator (art::Event &event, art::InputTag const &WireModuleLabel, art::InputTag const &RawDigitModuleLabel)
Constructor: sets instance name and whether to build associations.
HitCollectionAssociator (art::Event &event, std::string instance_name, art::InputTag const &WireModuleLabel, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
HitCollectionAssociator (art::Event &event, art::InputTag const &WireModuleLabel, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
size_t size () const
Returns the number of hits currently in the collection.
void put_into (art::Event &)
Moves the data into the event.
void put_into ()
Moves the data into the event.
std::vector< icarus::Hit > const & peek () const
Returns a read-only reference to the current list of hits.
Protected Member Functions
void prepare_associations (std::vector< icarus::Hit > const &srchits)
Finds out the associations for the specified hits.
void prepare_associations ()
Finds out the associations for the current hits.
Protected Member Functions inherited from icarus::HitAndAssociationsWriterBase
HitAndAssociationsWriterBase (art::Event &event, std::string instance_name, bool doWireAssns, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
HitPtr_t CreatePtr (size_t index) const
Creates an art pointer to the hit with the specified index.
Protected Attributes
art::InputTag wires_label
Label of the collection of wires to associate.
art::InputTag digits_label
Label of raw digits collection to associate.
Protected Attributes inherited from icarus::HitAndAssociationsWriterBase
std::string prod_instance
Tame of the instance for data products.
std::unique_ptr< std::vector< icarus::Hit > > hits
Collection of hits.
std::unique_ptr< art::Assns< recob::ChannelROI, icarus::Hit > > WireAssns
Associations with wires.
std::unique_ptr< art::Assns< raw::RawDigit, icarus::Hit > > RawDigitAssns
Associations with raw digits.
art::Event * event = nullptr
Pointer to the event we are using.
art::PtrMaker< icarus::Hit > hitPtrMaker
Tool to create hit pointers,.
Additional Inherited Members
Static Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
static void declare_products (art::ProducesCollector &collector, std::string instance_name="", bool doWireAssns=true, bool doRawDigitAssns=true)
Declares the hit products we are going to fill.
Protected Types inherited from icarus::HitAndAssociationsWriterBase
using HitPtr_t = art::Ptr<icarus::Hit>
Type of art pointer to Hit.
Detailed Description
A class handling a collection of hits and its associations.
Use this object if you already have a collection of icarus::Hit and you simply want the hits associated to the wire and digit with the same channel.
Definition at line 650 of file HitCreator.h.
Constructor & Destructor Documentation
HitCollectionAssociator() [1/4]
icarus::HitCollectionAssociator::HitCollectionAssociator (art::Event & event, std::string instance_name, art::InputTag const & WireModuleLabel, art::InputTag const & RawDigitModuleLabel)
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
instance_name name of the instance for all data products
WireModuleLabel label of the module used to create wires
RawDigitModuleLabel label of the module used to create raw digits
All the data products (hit collection and associations) will have the specified product instance name.
If a label is empty, the corresponding association will not be produced.
Definition at line 341 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits.
HitCollectionAssociator() [2/4]
icarus::HitCollectionAssociator::HitCollectionAssociator (art::Event & event, art::InputTag const & WireModuleLabel, art::InputTag const & RawDigitModuleLabel) inline
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
WireModuleLabel label of the module used to create wires
RawDigitModuleLabel label of the module used to create raw digits
All the data products (hit collection and associations) will have a default, empty product instance name.
If a label is empty, the corresponding association will not be produced.
Definition at line 682 of file HitCreator.h.
HitCollectionAssociator() [3/4]
icarus::HitCollectionAssociator::HitCollectionAssociator (art::Event & event, std::string instance_name, art::InputTag const & WireModuleLabel, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
instance_name name of the instance for all data products
WireModuleLabel label of the module used to create wires
doRawDigitAssns whether to write associations with raw digits
All the data products (hit collection and associations) will have the specified product instance name.
The raw digit association is built out of their existing associations with wires, rather than by directly using the raw digits data product.
Definition at line 356 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits, icarus::HitAndAssociationsWriterBase::RawDigitAssns, and icarus::HitAndAssociationsWriterBase::WireAssns.
HitCollectionAssociator() [4/4]
icarus::HitCollectionAssociator::HitCollectionAssociator (art::Event & event, art::InputTag const & WireModuleLabel, bool doRawDigitAssns) inline
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
WireModuleLabel label of the module used to create wires
doRawDigitAssns whether to write associations with raw digits
All the data products (hit collection and associations) will have the default, empty product instance name.
The raw digit association is built out of their existing associations with wires, rather than by directly using the raw digits data product.
Definition at line 718 of file HitCreator.h.
Member Function Documentation
prepare_associations() [1/2]
void icarus::HitCollectionAssociator::prepare_associations () inline protected
Finds out the associations for the current hits.
Definition at line 769 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::hits, and prepare_associations().
Referenced by prepare_associations(), and put_into().
prepare_associations() [2/2]
void icarus::HitCollectionAssociator::prepare_associations (std::vector< icarus::Hit > const & srchits) protected
Finds out the associations for the specified hits.
Definition at line 387 of file HitCreator.cxx.
References recob::ChannelROI::Channel(), icarus::HitAndAssociationsWriterBase::CreatePtr(), digits_label, icarus::HitAndAssociationsWriterBase::event, icarus::HitAndAssociationsWriterBase::RawDigitAssns, icarus::HitAndAssociationsWriterBase::WireAssns, and wires_label.
put_into() [1/2]
void icarus::HitCollectionAssociator::put_into ()
Moves the data into the event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Definition at line 380 of file HitCreator.cxx.
References prepare_associations(), and icarus::HitAndAssociationsWriterBase::put_into().
put_into() [2/2]
void icarus::HitCollectionAssociator::put_into (art::Event &) inline
Moves the data into the event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Deprecated
Use the version with no arguments instead.
Definition at line 748 of file HitCreator.h.
References put_into().
Referenced by put_into().
use_hits()
void icarus::HitCollectionAssociator::use_hits (std::unique_ptr< std::vector< icarus::Hit > > && srchits)
Uses the specified collection as data product.
Parameters
srchits the collection to be used as data product
The very same collection is put into the event. This object will temporary own the collection until the hits are put into the event. If there were previous hits in the object, they are lost.
Definition at line 374 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits.
Member Data Documentation
digits_label
art::InputTag icarus::HitCollectionAssociator::digits_label protected
Label of raw digits collection to associate.
Definition at line 763 of file HitCreator.h.
Referenced by prepare_associations().
wires_label
art::InputTag icarus::HitCollectionAssociator::wires_label protected
Label of the collection of wires to associate.
Definition at line 761 of file HitCreator.h.
Referenced by prepare_associations().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/TPC/Utilities/HitCreator.h
icaruscode/icaruscode/TPC/Utilities/HitCreator.cxx