CAF format: lar_cluster3d::Cluster3DICARUS Class Reference
lar_cluster3d::Cluster3DICARUS Class Reference
Definition of the Cluster3D class.
Classes
class ArtOutputHandler
Public Member Functions
Cluster3DICARUS (fhicl::ParameterSet const &pset)
Private Types
using IdxToPCAMap = std::map<size_t, const reco::PrincipalComponents*>
Special routine to handle creating and saving space points & edges PCA points.
Private Member Functions
void beginJob () override
void produce (art::Event &evt) override
void PrepareEvent (const art::Event &evt)
Event Preparation.
void InitializeMonitoring ()
Initialize the internal monitoring.
void findTrackSeeds (art::Event &evt, reco::ClusterParameters &cluster, IHit3DBuilder::RecobHitToPtrMap &hitToPtrMap, std::vector< recob::Seed > &seedVec, art::Assns< recob::Seed, recob::Hit > &seedHitAssns) const
An interface to the seed finding algorithm.
void splitClustersWithMST (reco::ClusterParameters &clusterParameters, reco::ClusterParametersList &clusterParametersList) const
Attempt to split clusters by using a minimum spanning tree.
void splitClustersWithHough (reco::ClusterParameters &clusterParameters, reco::ClusterParametersList &clusterParametersList) const
Attempt to split clusters using the output of the Hough Filter.
void MakeAndSaveSpacePoints (ArtOutputHandler &output, std::vector< recob::SpacePoint > &spacePointVec, art::Assns< recob::Hit, recob::SpacePoint > &spHitAssns, reco::HitPairListPtr &clusHitPairVector, IHit3DBuilder::RecobHitToPtrMap &hitToPtrMap, Hit3DToSPPtrMap &hit3DToSPPtrMap, const std::string &path="") const
Special routine to handle creating and saving space points.
void MakeAndSaveKinkPoints (ArtOutputHandler &output, reco::ConvexHullKinkTupleList &clusHitPairVector) const
Special routine to handle creating and saving space points.
void MakeAndSaveVertexPoints (ArtOutputHandler &, dcel2d::VertexList &, dcel2d::HalfEdgeList &) const
Special routine to handle creating and saving space points & edges associated to voronoi diagrams.
void MakeAndSavePCAPoints (ArtOutputHandler &, const reco::PrincipalComponents &, IdxToPCAMap &) const
size_t FindAndStoreDaughters (util::GeometryUtilities const &gser, ArtOutputHandler &output, reco::ClusterParameters &clusterParameters, size_t pfParticleParent, IdxToPCAMap &idxToPCAMap, IHit3DBuilder::RecobHitToPtrMap &hitToPtrMap, Hit3DToSPPtrMap &hit3DToSPPtrMap, Hit3DToSPPtrMap &best3DToSPPtrMap) const
This will produce art output for daughters noting that it needs to be done recursively.
void ProduceArtClusters (util::GeometryUtilities const &gser, ArtOutputHandler &output, reco::HitPairList &hitPairList, reco::ClusterParametersList &clusterParametersList, IHit3DBuilder::RecobHitToPtrMap &hitToPtrMap) const
Top level output routine, allows checking cluster status.
size_t ConvertToArtOutput (util::GeometryUtilities const &gser, ArtOutputHandler &output, reco::ClusterParameters &clusterParameters, size_t pfParticleParent, IHit3DBuilder::RecobHitToPtrMap &hitToPtrMap, Hit3DToSPPtrMap &hit3DToSPPtrMap, Hit3DToSPPtrMap &best3DToSPPtrMap) const
Produces the art output from all the work done in this producer module.
bool aParallelHitsCluster (const reco::PrincipalComponents &pca) const
There are several places we will want to know if a candidate cluster is a "parallel hits" type of cluster so encapsulate that here.
size_t countUltimateDaughters (reco::ClusterParameters &clusterParameters) const
Count number of end of line daughters.
Private Attributes
bool m_onlyMakSpacePoints
If true we don't do the full cluster 3D processing.
bool m_enableMonitoring
Turn on monitoring of this algorithm.
float m_parallelHitsCosAng
Cut for PCA 3rd axis angle to X axis.
float m_parallelHitsTransWid
Cut on transverse width of cluster (PCA 2nd eigenvalue)
TTree * m_pRecoTree
int m_run
int m_event
int m_hits
Keeps track of the number of hits seen.
int m_hits3D
Keeps track of the number of 3D hits made.
float m_totalTime
Keeps track of total execution time.
float m_artHitsTime
Keeps track of time to recover hits.
float m_makeHitsTime
Keeps track of time to build 3D hits.
float m_buildNeighborhoodTime
Keeps track of time to build epsilon neighborhood.
float m_dbscanTime
Keeps track of time to run DBScan.
float m_clusterMergeTime
Keeps track of the time to merge clusters.
float m_pathFindingTime
Keeps track of the path finding time.
float m_finishTime
Keeps track of time to run output module.
std::string m_pathInstance
Special instance for path points.
std::string m_vertexInstance
Special instance name for vertex points.
std::string m_extremeInstance
Instance name for the extreme points.
std::unique_ptr< lar_cluster3d::IHit3DBuilder > m_hit3DBuilderAlg
Builds the 3D hits to operate on.
std::unique_ptr< lar_cluster3d::IClusterAlg > m_clusterAlg
Algorithm to do 3D space point clustering.
std::unique_ptr< lar_cluster3d::IClusterModAlg > m_clusterMergeAlg
Algorithm to do cluster merging.
std::unique_ptr< lar_cluster3d::IClusterModAlg > m_clusterPathAlg
Algorithm to do cluster path finding.
std::unique_ptr< lar_cluster3d::IClusterParametersBuilder > m_clusterBuilder
Common cluster builder tool.
PrincipalComponentsAlg m_pcaAlg
Principal Components algorithm.
SkeletonAlg m_skeletonAlg
Skeleton point finder.
HoughSeedFinderAlg m_seedFinderAlg
Seed finder.
PCASeedFinderAlg m_pcaSeedFinderAlg
Use PCA axis to find seeds.
ParallelHitsSeedFinderAlg m_parallelHitsAlg
Deal with parallel hits clusters.
Detailed Description
Definition of the Cluster3D class.
Definition at line 108 of file Cluster3DICARUS_module.cc.
Member Typedef Documentation
IdxToPCAMap
using lar_cluster3d::Cluster3DICARUS::IdxToPCAMap = std::map<size_t, const reco::PrincipalComponents*> private
Special routine to handle creating and saving space points & edges PCA points.
Parameters
output the object containting the art output
clusterParamsList List of clusters to get PCA's from
Definition at line 413 of file Cluster3DICARUS_module.cc.
Constructor & Destructor Documentation
Cluster3DICARUS()
lar_cluster3d::Cluster3DICARUS::Cluster3DICARUS (fhicl::ParameterSet const & pset) explicit
Definition at line 541 of file Cluster3DICARUS_module.cc.
Member Function Documentation
aParallelHitsCluster()
bool lar_cluster3d::Cluster3DICARUS::aParallelHitsCluster (const reco::PrincipalComponents & pca) const inline private
There are several places we will want to know if a candidate cluster is a "parallel hits" type of cluster so encapsulate that here.
Parameters
pca The Principal Components Analysis parameters for the cluster
Definition at line 473 of file Cluster3DICARUS_module.cc.
References m_parallelHitsCosAng, and m_parallelHitsTransWid.
Referenced by findTrackSeeds().
beginJob()
void lar_cluster3d::Cluster3DICARUS::beginJob () override private
beginJob will be tasked with initializing monitoring, in necessary, but also to init the geometry and detector services (and this probably needs to go in a "beginEvent" method?)
Definition at line 611 of file Cluster3DICARUS_module.cc.
References InitializeMonitoring(), and m_enableMonitoring.
ConvertToArtOutput()
size_t lar_cluster3d::Cluster3DICARUS::ConvertToArtOutput (util::GeometryUtilities const & gser, ArtOutputHandler & output, reco::ClusterParameters & clusterParameters, size_t pfParticleParent, IHit3DBuilder::RecobHitToPtrMap & hitToPtrMap, Hit3DToSPPtrMap & hit3DToSPPtrMap, Hit3DToSPPtrMap & best3DToSPPtrMap) const private
Produces the art output from all the work done in this producer module.
Parameters
output the object containting the art output
clusterParameters Cluster info to output (in internal format)
pfParticleParent The parent ID reference for the output PFParticle
hitToPtrMap This maps our Cluster2D hits back to art Ptr's to reco Hits
Definition at line 1462 of file Cluster3DICARUS_module.cc.
References m_pathInstance, and MakeAndSaveSpacePoints().
Referenced by FindAndStoreDaughters(), and ProduceArtClusters().
countUltimateDaughters()
size_t lar_cluster3d::Cluster3DICARUS::countUltimateDaughters (reco::ClusterParameters & clusterParameters) const private
Count number of end of line daughters.
Parameters
clusterParams input cluster parameters to look at
Definition at line 1409 of file Cluster3DICARUS_module.cc.
References countUltimateDaughters().
Referenced by countUltimateDaughters(), and ProduceArtClusters().
FindAndStoreDaughters()
size_t lar_cluster3d::Cluster3DICARUS::FindAndStoreDaughters (util::GeometryUtilities const & gser, ArtOutputHandler & output, reco::ClusterParameters & clusterParameters, size_t pfParticleParent, IdxToPCAMap & idxToPCAMap, IHit3DBuilder::RecobHitToPtrMap & hitToPtrMap, Hit3DToSPPtrMap & hit3DToSPPtrMap, Hit3DToSPPtrMap & best3DToSPPtrMap) const private
This will produce art output for daughters noting that it needs to be done recursively.
Parameters
output the object containting the art output
clusterParameters Cluster info to output (in internal format)
pfParticleParent The parent ID reference for the output PFParticle
daughterList List of PFParticle indices for stored daughters
hitToPtrMap This maps our Cluster2D hits back to art Ptr's to reco Hits
Definition at line 1424 of file Cluster3DICARUS_module.cc.
References ConvertToArtOutput(), and FindAndStoreDaughters().
Referenced by FindAndStoreDaughters(), and ProduceArtClusters().
findTrackSeeds()
void lar_cluster3d::Cluster3DICARUS::findTrackSeeds (art::Event & evt, reco::ClusterParameters & cluster, IHit3DBuilder::RecobHitToPtrMap & hitToPtrMap, std::vector< recob::Seed > & seedVec, art::Assns< recob::Seed, recob::Hit > & seedHitAssns) const private
An interface to the seed finding algorithm.
Parameters
evt the ART event
cluster structure of information representing a single cluster
hitToPtrMap This maps our Cluster2D hits back to art Ptr's to reco Hits
seedVec the output vector of candidate seeds
seedHitAssns the associations between the seeds and the 2D hits making them
This method provides an interface to various algorithms for finding candiate recob::Seed objects and, as well, their candidate related seed hits
Definition at line 759 of file Cluster3DICARUS_module.cc.
References aParallelHitsCluster(), m_parallelHitsAlg, m_pcaSeedFinderAlg, m_seedFinderAlg, and m_skeletonAlg.
InitializeMonitoring()
void lar_cluster3d::Cluster3DICARUS::InitializeMonitoring () private
Initialize the internal monitoring.
Definition at line 718 of file Cluster3DICARUS_module.cc.
References m_artHitsTime, m_buildNeighborhoodTime, m_clusterMergeTime, m_clusterPathAlg, m_dbscanTime, m_finishTime, m_hits, m_hits3D, m_makeHitsTime, m_pathFindingTime, m_pRecoTree, and m_totalTime.
Referenced by beginJob().
MakeAndSaveKinkPoints()
void lar_cluster3d::Cluster3DICARUS::MakeAndSaveKinkPoints (ArtOutputHandler & output, reco::ConvexHullKinkTupleList & clusHitPairVector) const private
Special routine to handle creating and saving space points.
Parameters
output the object containting the art output
clusHitPairVector List of 3D hits to output as "extreme" space points
Definition at line 1742 of file Cluster3DICARUS_module.cc.
Referenced by ProduceArtClusters().
MakeAndSavePCAPoints()
void lar_cluster3d::Cluster3DICARUS::MakeAndSavePCAPoints (ArtOutputHandler & output, const reco::PrincipalComponents & fullPCA, IdxToPCAMap & idxToPCAMap) const private
Definition at line 1835 of file Cluster3DICARUS_module.cc.
MakeAndSaveSpacePoints()
void lar_cluster3d::Cluster3DICARUS::MakeAndSaveSpacePoints (ArtOutputHandler & output, std::vector< recob::SpacePoint > & spacePointVec, art::Assns< recob::Hit, recob::SpacePoint > & spHitAssns, reco::HitPairListPtr & clusHitPairVector, IHit3DBuilder::RecobHitToPtrMap & hitToPtrMap, Hit3DToSPPtrMap & hit3DToSPPtrMap, const std::string & path = "") const private
Special routine to handle creating and saving space points.
Parameters
output the object containting the art output
clusterParameters Cluster info to output (in internal format)
pfParticleParent The parent ID reference for the output PFParticle
hitToPtrMap This maps our Cluster2D hits back to art Ptr's to reco Hits
Definition at line 1684 of file Cluster3DICARUS_module.cc.
Referenced by ConvertToArtOutput(), and ProduceArtClusters().
MakeAndSaveVertexPoints()
void lar_cluster3d::Cluster3DICARUS::MakeAndSaveVertexPoints (ArtOutputHandler & output, dcel2d::VertexList & vertexList, dcel2d::HalfEdgeList & halfEdgeList) const private
Special routine to handle creating and saving space points & edges associated to voronoi diagrams.
Parameters
output the object containting the art output
vertexList list of vertices in the diagram
HalfEdgeList list of half edges in the diagram
Definition at line 1769 of file Cluster3DICARUS_module.cc.
Referenced by ProduceArtClusters().
PrepareEvent()
void lar_cluster3d::Cluster3DICARUS::PrepareEvent (const art::Event & evt) private
Event Preparation.
Parameters
evt the ART event
Definition at line 741 of file Cluster3DICARUS_module.cc.
References m_artHitsTime, m_buildNeighborhoodTime, m_dbscanTime, m_finishTime, m_hits, m_hits3D, m_makeHitsTime, m_pathFindingTime, and m_totalTime.
produce()
void lar_cluster3d::Cluster3DICARUS::produce (art::Event & evt) override private
Definition at line 623 of file Cluster3DICARUS_module.cc.
ProduceArtClusters()
void lar_cluster3d::Cluster3DICARUS::ProduceArtClusters (util::GeometryUtilities const & gser, ArtOutputHandler & output, reco::HitPairList & hitPairList, reco::ClusterParametersList & clusterParametersList, IHit3DBuilder::RecobHitToPtrMap & hitToPtrMap) const private
Top level output routine, allows checking cluster status.
Parameters
hitPairList List of all 3D Hits in internal Cluster3D format
clusterParametersList Data structure containing the cluster information to output
hitToPtrMap This maps our Cluster2D hits back to art Ptr's to reco Hits
The workhorse to take the candidate 3D clusters and produce all of the necessary art output
Definition at line 1191 of file Cluster3DICARUS_module.cc.
References ConvertToArtOutput(), countUltimateDaughters(), FindAndStoreDaughters(), MakeAndSaveKinkPoints(), MakeAndSaveSpacePoints(), and MakeAndSaveVertexPoints().
splitClustersWithHough()
void lar_cluster3d::Cluster3DICARUS::splitClustersWithHough (reco::ClusterParameters & clusterParameters, reco::ClusterParametersList & clusterParametersList) const private
Attempt to split clusters using the output of the Hough Filter.
Parameters
clusterParameters The given cluster parameters object to try to split
clusterParametersList The list of clusters
Definition at line 1047 of file Cluster3DICARUS_module.cc.
References m_clusterBuilder, m_pcaAlg, m_seedFinderAlg, and m_skeletonAlg.
splitClustersWithMST()
void lar_cluster3d::Cluster3DICARUS::splitClustersWithMST (reco::ClusterParameters & clusterParameters, reco::ClusterParametersList & clusterParametersList) const private
Attempt to split clusters by using a minimum spanning tree.
Parameters
clusterParameters The given cluster parameters object to try to split
clusterParametersList The list of clusters
Definition at line 854 of file Cluster3DICARUS_module.cc.
References m_skeletonAlg.
Member Data Documentation
m_artHitsTime
float lar_cluster3d::Cluster3DICARUS::m_artHitsTime private
Keeps track of time to recover hits.
Definition at line 503 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_buildNeighborhoodTime
float lar_cluster3d::Cluster3DICARUS::m_buildNeighborhoodTime private
Keeps track of time to build epsilon neighborhood.
Definition at line 505 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_clusterAlg
std::unique_ptr<lar_cluster3d::IClusterAlg> lar_cluster3d::Cluster3DICARUS::m_clusterAlg private
Algorithm to do 3D space point clustering.
Definition at line 518 of file Cluster3DICARUS_module.cc.
m_clusterBuilder
std::unique_ptr<lar_cluster3d::IClusterParametersBuilder> lar_cluster3d::Cluster3DICARUS::m_clusterBuilder private
Common cluster builder tool.
Definition at line 524 of file Cluster3DICARUS_module.cc.
Referenced by splitClustersWithHough().
m_clusterMergeAlg
std::unique_ptr<lar_cluster3d::IClusterModAlg> lar_cluster3d::Cluster3DICARUS::m_clusterMergeAlg private
Algorithm to do cluster merging.
Definition at line 520 of file Cluster3DICARUS_module.cc.
m_clusterMergeTime
float lar_cluster3d::Cluster3DICARUS::m_clusterMergeTime private
Keeps track of the time to merge clusters.
Definition at line 507 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring().
m_clusterPathAlg
std::unique_ptr<lar_cluster3d::IClusterModAlg> lar_cluster3d::Cluster3DICARUS::m_clusterPathAlg private
Algorithm to do cluster path finding.
Definition at line 522 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring().
m_dbscanTime
float lar_cluster3d::Cluster3DICARUS::m_dbscanTime private
Keeps track of time to run DBScan.
Definition at line 506 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_enableMonitoring
bool lar_cluster3d::Cluster3DICARUS::m_enableMonitoring private
Turn on monitoring of this algorithm.
Definition at line 490 of file Cluster3DICARUS_module.cc.
Referenced by beginJob().
m_event
int lar_cluster3d::Cluster3DICARUS::m_event private
Definition at line 499 of file Cluster3DICARUS_module.cc.
m_extremeInstance
std::string lar_cluster3d::Cluster3DICARUS::m_extremeInstance private
Instance name for the extreme points.
Definition at line 512 of file Cluster3DICARUS_module.cc.
m_finishTime
float lar_cluster3d::Cluster3DICARUS::m_finishTime private
Keeps track of time to run output module.
Definition at line 509 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_hit3DBuilderAlg
std::unique_ptr<lar_cluster3d::IHit3DBuilder> lar_cluster3d::Cluster3DICARUS::m_hit3DBuilderAlg private
Builds the 3D hits to operate on.
Definition at line 516 of file Cluster3DICARUS_module.cc.
m_hits
int lar_cluster3d::Cluster3DICARUS::m_hits private
Keeps track of the number of hits seen.
Definition at line 500 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_hits3D
int lar_cluster3d::Cluster3DICARUS::m_hits3D private
Keeps track of the number of 3D hits made.
Definition at line 501 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_makeHitsTime
float lar_cluster3d::Cluster3DICARUS::m_makeHitsTime private
Keeps track of time to build 3D hits.
Definition at line 504 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_onlyMakSpacePoints
bool lar_cluster3d::Cluster3DICARUS::m_onlyMakSpacePoints private
If true we don't do the full cluster 3D processing.
Algorithm parameters
Definition at line 489 of file Cluster3DICARUS_module.cc.
m_parallelHitsAlg
ParallelHitsSeedFinderAlg lar_cluster3d::Cluster3DICARUS::m_parallelHitsAlg private
Deal with parallel hits clusters.
Definition at line 529 of file Cluster3DICARUS_module.cc.
Referenced by findTrackSeeds().
m_parallelHitsCosAng
float lar_cluster3d::Cluster3DICARUS::m_parallelHitsCosAng private
Cut for PCA 3rd axis angle to X axis.
Definition at line 491 of file Cluster3DICARUS_module.cc.
Referenced by aParallelHitsCluster().
m_parallelHitsTransWid
float lar_cluster3d::Cluster3DICARUS::m_parallelHitsTransWid private
Cut on transverse width of cluster (PCA 2nd eigenvalue)
Definition at line 492 of file Cluster3DICARUS_module.cc.
Referenced by aParallelHitsCluster().
m_pathFindingTime
float lar_cluster3d::Cluster3DICARUS::m_pathFindingTime private
Keeps track of the path finding time.
Definition at line 508 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_pathInstance
std::string lar_cluster3d::Cluster3DICARUS::m_pathInstance private
Special instance for path points.
Definition at line 510 of file Cluster3DICARUS_module.cc.
Referenced by ConvertToArtOutput().
m_pcaAlg
PrincipalComponentsAlg lar_cluster3d::Cluster3DICARUS::m_pcaAlg private
Principal Components algorithm.
Definition at line 525 of file Cluster3DICARUS_module.cc.
Referenced by splitClustersWithHough().
m_pcaSeedFinderAlg
PCASeedFinderAlg lar_cluster3d::Cluster3DICARUS::m_pcaSeedFinderAlg private
Use PCA axis to find seeds.
Definition at line 528 of file Cluster3DICARUS_module.cc.
Referenced by findTrackSeeds().
m_pRecoTree
TTree* lar_cluster3d::Cluster3DICARUS::m_pRecoTree private
Tree variables for output
Definition at line 497 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring().
m_run
int lar_cluster3d::Cluster3DICARUS::m_run private
Definition at line 498 of file Cluster3DICARUS_module.cc.
m_seedFinderAlg
HoughSeedFinderAlg lar_cluster3d::Cluster3DICARUS::m_seedFinderAlg private
Seed finder.
Definition at line 527 of file Cluster3DICARUS_module.cc.
Referenced by findTrackSeeds(), and splitClustersWithHough().
m_skeletonAlg
SkeletonAlg lar_cluster3d::Cluster3DICARUS::m_skeletonAlg private
Skeleton point finder.
Definition at line 526 of file Cluster3DICARUS_module.cc.
Referenced by findTrackSeeds(), splitClustersWithHough(), and splitClustersWithMST().
m_totalTime
float lar_cluster3d::Cluster3DICARUS::m_totalTime private
Keeps track of total execution time.
Definition at line 502 of file Cluster3DICARUS_module.cc.
Referenced by InitializeMonitoring(), and PrepareEvent().
m_vertexInstance
std::string lar_cluster3d::Cluster3DICARUS::m_vertexInstance private
Special instance name for vertex points.
Definition at line 511 of file Cluster3DICARUS_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/TPC/Tracking/cluster3D/Cluster3DICARUS_module.cc