CAF format: icarus::trigger::details::TriggerInfo_t Struct Reference
icarus::trigger::details::TriggerInfo_t Struct Reference
Helper data structure to store transient trigger result.
#include <TriggerInfo_t.h>
Classes
struct OpeningInfo_t
Public Types
using optical_tick = detinfo::timescales::optical_tick
Type alias.
using Opening_t = icarus::trigger::OpticalTriggerGateData_t::GateData_t::OpeningCount_t
Type of gate opening level.
using LocationID_t = std::size_t
Type for ID of trigger location.
Public Member Functions
TriggerInfo_t (OpeningInfo_t info)
Query whether the trigger fired.
bool fired () const
Returns whether the trigger fired.
operator bool () const
Returns whether there is trigger information.
bool operator! () const
Returns whether there is no trigger information.
Modify trigger information
void replace (OpeningInfo_t info)
Sets info as the new main() trigger.
bool addAndReplaceIfEarlier (TriggerInfo_t const &other)
If other has fired, and at an earlier tick, set a new main().
bool addAndReplaceIfEarlier (OpeningInfo_t const &info)
If info is earlier than main(), it is set as new main().
void add (OpeningInfo_t info)
void sortOpenings ()
Sorts all openings by time.
Access to trigger information
If the trigger did not fire, the result and behaviour of these methods are undefined.
OpeningInfo_t const & info () const
Returns the information of the main trigger (undefined if !fired()).
optical_tick atTick () const
Returns the time of the trigger (undefined if !fired()).
Opening_t level () const
Returns the opening level of the trigger (undefined if !fired()).
LocationID_t location () const
Returns the ID of the location of the trigger (undefined if !fired()).
bool hasLocation () const
Returns if the location of the trigger is set (undefined if !fired()).
OpeningInfo_t const & main () const
Returns the full data (undefined if !fired()).
std::vector< OpeningInfo_t > const & all () const
std::size_t nTriggers () const
Returns the number of registered triggers.
Private Attributes
OpeningInfo_t fMain
Main trigger (also found in fAll), if any.
std::vector< OpeningInfo_t > fAll
Detailed Description
Helper data structure to store transient trigger result.
This record maintains a list of all openings (add()), and has a special one (main()) which represents the "global" trigger.
Note that unless no opening is add()'ed, there is always a main() trigger.
Each trigger is described by the information in a OpeningInfo_t record. The records can be registered with add(); replace() changes the main() trigger information unconditionally, while addAndReplaceIfEarlier() replaces main() only if the argument proposes a trigger earlier than the current main().
Definition at line 50 of file TriggerInfo_t.h.
Member Typedef Documentation
LocationID_t
using icarus::trigger::details::TriggerInfo_t::LocationID_t = std::size_t
Type for ID of trigger location.
Definition at line 57 of file TriggerInfo_t.h.
Opening_t
using icarus::trigger::details::TriggerInfo_t::Opening_t = icarus::trigger::OpticalTriggerGateData_t::GateData_t::OpeningCount_t
Type of gate opening level.
Definition at line 55 of file TriggerInfo_t.h.
optical_tick
using icarus::trigger::details::TriggerInfo_t::optical_tick = detinfo::timescales::optical_tick
Type alias.
Definition at line 52 of file TriggerInfo_t.h.
Constructor & Destructor Documentation
TriggerInfo_t()
icarus::trigger::details::TriggerInfo_t::TriggerInfo_t (OpeningInfo_t info) inline
Definition at line 97 of file TriggerInfo_t.h.
Member Function Documentation
add()
void icarus::trigger::details::TriggerInfo_t::add (OpeningInfo_t info) inline
Adds an opening to all list (main is not affected). Not sorted. If no trigger is marked as main(), this becomes it.
Definition at line 152 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::MajorityTriggerSimulation::simulateCryostat().
addAndReplaceIfEarlier() [1/2]
bool icarus::trigger::details::TriggerInfo_t::addAndReplaceIfEarlier (OpeningInfo_t const & info) inline
If info is earlier than main(), it is set as new main().
Parameters
info the opening information candidate as new main()
Returns
whether main() was updated.
If info is earlier tick than main() (or if there is no main() yet, i.e. it has not fired()), info becomes the new main(). In all cases info is added (add()).
Definition at line 402 of file TriggerInfo_t.h.
addAndReplaceIfEarlier() [2/2]
bool icarus::trigger::details::TriggerInfo_t::addAndReplaceIfEarlier (TriggerInfo_t const & other) inline
If other has fired, and at an earlier tick, set a new main().
Parameters
other another set of triggers
Returns
whether the main() information from other was copied
If other has fired() earlier than this one (or if this one hasn't fired at all), the main trigger of other is adopted. In any case all openings from other are add()'ed to this one.
Definition at line 383 of file TriggerInfo_t.h.
References add(), all(), atTick(), fired(), fMain, info(), main(), and nTriggers().
Referenced by icarus::trigger::MajorityTriggerSimulation::simulate().
all()
std::vector< OpeningInfo_t > const & icarus::trigger::details::TriggerInfo_t::all () const inline
Returns all the registered opening in the current order (not resorted).
See also
sortOpenings()
Definition at line 191 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
atTick()
optical_tick icarus::trigger::details::TriggerInfo_t::atTick () const inline
Returns the time of the trigger (undefined if !fired()).
Definition at line 175 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), icarus::trigger::SlidingWindowTriggerEfficiencyPlots::plotResponse(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), icarus::trigger::MajorityTriggerSimulation::plotTriggerResponse(), icarus::trigger::SlidingWindowTriggerSimulation::plotTriggerResponse(), icarus::trigger::MajorityTriggerSimulation::produce(), icarus::trigger::SlidingWindowTriggerSimulation::produce(), icarus::trigger::TriggerSimulationOnGates::produceForThreshold(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
fired()
bool icarus::trigger::details::TriggerInfo_t::fired () const inline
Returns whether the trigger fired.
Definition at line 107 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::TriggerEfficiencyPlotsBase::fillAllEfficiencyPlots(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), icarus::trigger::SlidingWindowTriggerEfficiencyPlots::plotResponse(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), icarus::trigger::MajorityTriggerSimulation::plotTriggerResponse(), icarus::trigger::SlidingWindowTriggerSimulation::plotTriggerResponse(), icarus::trigger::MajorityTriggerSimulation::produceForThreshold(), and icarus::trigger::SlidingWindowTriggerSimulation::produceForThreshold().
hasLocation()
bool icarus::trigger::details::TriggerInfo_t::hasLocation () const inline
Returns if the location of the trigger is set (undefined if !fired()).
Definition at line 184 of file TriggerInfo_t.h.
Referenced by icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
info()
OpeningInfo_t const & icarus::trigger::details::TriggerInfo_t::info () const inline
Returns the information of the main trigger (undefined if !fired()).
Definition at line 172 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier().
level()
Opening_t icarus::trigger::details::TriggerInfo_t::level () const inline
Returns the opening level of the trigger (undefined if !fired()).
Definition at line 178 of file TriggerInfo_t.h.
Referenced by icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses().
location()
LocationID_t icarus::trigger::details::TriggerInfo_t::location () const inline
Returns the ID of the location of the trigger (undefined if !fired()).
Definition at line 181 of file TriggerInfo_t.h.
Referenced by icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
main()
OpeningInfo_t const & icarus::trigger::details::TriggerInfo_t::main () const inline
Returns the full data (undefined if !fired()).
Definition at line 187 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
nTriggers()
std::size_t icarus::trigger::details::TriggerInfo_t::nTriggers () const inline
Returns the number of registered triggers.
Definition at line 194 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::SlidingWindowPatternAlg::simulateResponse().
operator bool()
icarus::trigger::details::TriggerInfo_t::operator bool () const inline
Returns whether there is trigger information.
Definition at line 110 of file TriggerInfo_t.h.
operator!()
bool icarus::trigger::details::TriggerInfo_t::operator! () const inline
Returns whether there is no trigger information.
Definition at line 113 of file TriggerInfo_t.h.
replace()
void icarus::trigger::details::TriggerInfo_t::replace (OpeningInfo_t info) inline
Sets info as the new main() trigger.
Definition at line 124 of file TriggerInfo_t.h.
sortOpenings()
void icarus::trigger::details::TriggerInfo_t::sortOpenings () inline
Sorts all openings by time.
Definition at line 156 of file TriggerInfo_t.h.
Referenced by icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), and icarus::trigger::MajorityTriggerSimulation::simulate().
Member Data Documentation
fAll
std::vector<OpeningInfo_t> icarus::trigger::details::TriggerInfo_t::fAll private
Definition at line 205 of file TriggerInfo_t.h.
fMain
OpeningInfo_t icarus::trigger::details::TriggerInfo_t::fMain private
Main trigger (also found in fAll), if any.
Information about all global trigger candidates.
Definition at line 202 of file TriggerInfo_t.h.
Referenced by addAndReplaceIfEarlier().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/TriggerInfo_t.h