CAF format: icarus::trigger Namespace Reference
icarus::trigger Namespace Reference
Trigger simulation for ICARUS.
Namespaces
namespace details
namespace GateOps
Gate operations expressed as generic functions.
Classes
struct AdderBitID
struct AdderInfo_t
Description of a (logical) adder bit and additional information.
class ApplyBeamGateClass
Helper applying a beam gate to any gate.
class BeamGateInfoFromTracks
Writes a set collection of beam gates into each event.
class BeamGateMaker
Simple utility to generate gates around beam time.
struct BeamGateStruct
Object representing a time gate, with a start and and end.
class CryostatTriggerCombiner
Combines cryostat triggers via OR. Glorified Max().
class DiscriminatedAdderSignal
Produces discriminated optical waveforms for PMT adders.
class DiscriminatePMTwaveforms
Produces discriminated optical waveforms.
class DiscriminatePMTwaveformsByChannel
Produces discriminated optical waveforms.
struct dumpRecipe
class DumpTriggerGateData
Produces plots to inform trigger design.
class DynamicTriggerGateBuilder
Dynamic gate builder.
struct DynamicTriggerGateBuilderTool
Dynamic gate builder tool.
class ExtractEnergyDepositionSummary
Produces energy deposition summary data products.
class FixBeamGateInfo
Rewrites a set collection of beam gates into each event.
class FixedTriggerGateBuilder
Fixed-length gate builder.
struct FixedTriggerGateBuilderTool
Fixed gate builder tool.
class GeometryChannelSplitter
Combines cryostat triggers via OR. Glorified Max().
struct isReadoutTriggerGate
Type traits: Gate type derives from a ReadoutTriggerGate instance.
struct isTrackedTriggerGate
Trait returning whether T is some form of TrackedTriggerGate`.
class LVDSbitMaps
Utility to build and maintain ICARUS trigger LVDS bit maps.
class LVDSgates
Combines discriminated PMT outputs into V1730 LVDS gates.
struct LVDSHWbitID
struct LVDSinfo_t
Information about a PMT pair: source bit and connected channels.
class MajorityTriggerCombiner
Combines a group of trigger gates for majority trigger. Glorified Sum().
class MajorityTriggerEfficiencyPlots
Produces plots about trigger simulation and trigger efficiency.
class MajorityTriggerSimulation
Simulates a "majority" trigger.
class MakeTriggerSimulationTree
Make ROOT tree with information about event and trigger input.
class ManagedTriggerGateBuilder
Base interface for gate builders.
struct MoreThanOneChannelError
More than one channel associated to the readout gate.
class MultiChannelOpticalTriggerGate
Logical multi-level gate associated to one or more channels.
struct NoChannelError
No channel associated to the readout gate.
class OpDetWaveformMetaMaker
Extracts and saves the time coverage of optical detector waveforms.
class OpDetWaveformMetaMatcher
Object to facilitate the discovery of the raw::OpDetWaveform a sbn::OpDetWaveformMeta objects comes from.
class OpticalTriggerGate
Logical multi-level gate associated to one or more waveforms.
struct PMTpairBitID
class PMTverticalSlicingAlg
Algorithm clustering PMT according to their position.
class ReadoutTriggerGate
Logical multi-level gate associated to one or more readout channels.
struct ReadoutTriggerGateError
Base class for all exceptions from icarus::trigger::ReadoutTriggerGate.
struct ReadoutTriggerGateTag
All ReadoutTriggerGate template instances derive from this tag.
class ReassociatePMTbaselines
Associates baseline and RMS objects to pruned optical waveforms.
class SingleChannelOpticalTriggerGate
Logical multi-level gate associated to a optical detector channel.
class SlidingWindowCombinerAlg
class SlidingWindowDefinitionAlg
Groups optical detector channels into windows based on position.
class SlidingWindowPatternAlg
Applies sliding window patterns to discriminated waveforms.
class SlidingWindowTrigger
Combines trigger channels (V1730 LVDS gates) into sliding windows.
class SlidingWindowTriggerEfficiencyPlots
Produces plots about trigger simulation and trigger efficiency.
class SlidingWindowTriggerSimulation
Simulates a sliding window trigger.
class TrackedTriggerGate
A wrapper to trigger gate objects tracking the input of operations.
class TriggerEfficiencyPlots
Produces plots about trigger simulation and trigger efficiency.
class TriggerEfficiencyPlotsBase
Helper class to produce plots about trigger simulation and trigger efficiency.
class TriggerGateBuilder
Algorithm to produce trigger gates out of optical readout waveforms.
class TriggerGateData
Logical multi-level gate.
class TriggerGateIndex
Associates each optical detector channel to a gate.
class TriggerGateReader
Assembles and returns trigger gates from serialized data.
class TriggerSimulationOnGates
Simulates a sliding window trigger at specified gate times.
struct WaveformWithBaseline
Object to carry around waveform ant its baseline.
class WindowChannelMap
Information about composition and topology of trigger sliding windows.
struct WindowPattern
Specification of the requirement of sliding window firing pattern.
class WindowTopologyAlg
Algorithm to create trigger window topology information.
class WindowTopologyManager
Class to extract and verify a window topology from trigger gates.
class WindowTopologyVerification
Algorithm verifying the topology from trigger gates.
class WriteBeamGateInfo
Writes a set collection of beam gates into each event.
Typedefs
using ADCCounts_t = util::quantities::counts_as<raw::ADC_Count_t>
ADC counts for optical detector readout.
using WindowPatterns_t = std::vector<WindowPattern>
A list of window patterns.
template<typename TrackedType >
using TrackedOpticalTriggerGate
TrackedTriggerGate wrapper to trigger gate type commonly stored.
using OpDetWaveformDataProductMap_t = util::DataProductPointerMap_t<raw::OpDetWaveform>
Map util::DataProductPointerMap_t for raw::OpDetWaveform objects.
using OpDetWaveformMetaDataProductMap_t = util::DataProductPointerMap_t<sbn::OpDetWaveformMeta>
Map util::DataProductPointerMap_t for sbn::OpDetWaveformMeta objects.
using triggerLocation = sbn::triggerLocation
using triggerSource = sbn::triggerSource
using TriggerGateTick_t = util::quantities::tick::value_t
Tick point.
using TriggerGateTicks_t = util::quantities::tick::value_t
Tick interval.
using OpticalTriggerGateData_t
Type of trigger gate data serialized into art data products.
Functions
ApplyBeamGateClass makeApplyBeamGate (util::quantities::intervals::microseconds duration, util::quantities::intervals::microseconds delay, detinfo::DetectorClocksData const &clockData, std::string const &logCategory="ApplyBeamGateClass")
Returns a new ApplyBeamGateClass object with the specified gate.
ApplyBeamGateClass makeApplyBeamGate (util::quantities::intervals::microseconds duration, detinfo::DetectorClocksData const &clockData, std::string const &logCategory="ApplyBeamGateClass")
Returns a new ApplyBeamGateClass object with the specified gate.
std::ostream & operator<< (std::ostream &out, icarus::trigger::ApplyBeamGateClass const &gate)
BeamGateStruct makeBeamGateStruct (detinfo::DetectorTimings const &detTimings, util::quantities::intervals::microseconds duration, util::quantities::intervals::microseconds delay=util::quantities::intervals::microseconds{ 0.0 })
Creates a BeamGateStruct object of specified duration and start.
template<typename Time >
std::ostream & operator<< (std::ostream &out, icarus::trigger::BeamGateStruct::TimeRange< Time > const &range)
std::ostream & operator<< (std::ostream &out, PMTpairBitID const &bit)
std::ostream & operator<< (std::ostream &out, LVDSHWbitID const &bit)
std::ostream & operator<< (std::ostream &, WindowChannelMap const &)
std::string to_string (WindowPattern const &pattern)
DiscriminatePMTwaveformsByChannel::ChannelInfo_t convert (DiscriminatePMTwaveformsByChannel::ChannelConfig const &config)
std::ostream & operator<< (std::ostream &out, dumpRecipe const &dr)
FixBeamGateInfo::BeamChangeRecipe convert (FixBeamGateInfo::Config::ChangeGate const &config)
template<typename Gate , typename TrackedType >
std::ostream & operator<< (std::ostream &out, TrackedTriggerGate< Gate, TrackedType > const &gate)
template<typename Gates >
std::vector< icarus::trigger::OpticalTriggerGateData_t > transformIntoOpticalTriggerGate (Gates &&gates)
Returns the trigger gates in serializable format.
template<typename OpDetInfo = sbn::OpDetWaveformMeta>
std::tuple< std::vector< icarus::trigger::OpticalTriggerGateData_t >, art::Assns< icarus::trigger::OpticalTriggerGateData_t, OpDetInfo > > transformIntoOpticalTriggerGate (std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > &&gates, art::PtrMaker< icarus::trigger::OpticalTriggerGateData_t > const &makeGatePtr, util::DataProductPointerMap_t< OpDetInfo > const &opDetInfoPtrs)
Returns the trigger gates in serializable format.
template<typename OpDetInfo >
std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > FillTriggerGates (std::vector< icarus::trigger::OpticalTriggerGateData_t > const &gates, art::Assns< icarus::trigger::OpticalTriggerGateData_t, OpDetInfo > const &gateToWaveformInfo)
Creates gate objects out of trigger gate data products.
template<typename OpDetInfo = sbn::OpDetWaveformMeta, typename Event >
std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > ReadTriggerGates (Event const &event, art::InputTag const &dataTag)
Assembles and returns trigger gates from serialized data.
template<typename Tick , typename TickInterval , typename ChannelIDType >
auto compactdump (ReadoutTriggerGate< Tick, TickInterval, ChannelIDType > const &gate) -> details::CompactFormatter< ReadoutTriggerGate< Tick, TickInterval, ChannelIDType > >
Manipulator-like function for compact format of trigger gates.
sim::BeamGateInfo convert (WriteBeamGateInfo::Config::GateConfig const &config)
MultiChannelOpticalTriggerGate sumTriggerGates (std::vector< SingleChannelOpticalTriggerGate > const &gates)
std::ostream & operator<< (std::ostream &, OpticalTriggerGate const &)
template<typename Tick , typename TickInterval , typename ChannelIDType >
std::ostream & operator<< (std::ostream &, ReadoutTriggerGate< Tick, TickInterval, ChannelIDType > const &)
template<typename TK , typename TI >
std::ostream & operator<< (std::ostream &, TriggerGateData< TK, TI > const &)
template<typename TK , typename TI >
std::ostream & operator<< (std::ostream &, typename TriggerGateData< TK, TI >::Status const &)
<tt>icarus::trigger::TrackedTriggerGate</tt> simple helpers
template<typename Gate >
decltype(auto) gateDataIn (Gate &&gate)
Returns the trigger data (a TriggerGateData) from the specofied gate.
template<typename Gate >
decltype(auto) gateIn (Gate &&gate)
Returns the trigger gate (a ReadoutTriggerGate) from the specified gate.
template<typename TrackingGateColl >
auto gatesIn (TrackingGateColl &trackingGates)
Gate operations
Currently the following operations are supported:
discrimination against a threshold: discriminate();
sum of trigger gates: sumGates(), sumGatesSequence();
maximum of trigger gates: maxGates(), maxGatesSequence().
Operations on more than one gate can take a sequence (begin and end iterators), a collection or an arbitrary number of gates.
template<typename GateObj >
GateObj discriminate (GateObj const &gate, typename GateObj::OpeningCount_t threshold=1U, typename GateObj::OpeningCount_t pass=1U, typename GateObj::OpeningCount_t fail=0U)
Returns a discriminated version of gate.
template<typename BIter , typename EIter >
auto sumGatesSequence (BIter const begin, EIter const end)
Sums a sequence of gates.
template<typename GateColl >
auto sumGates (GateColl const &gates)
Sums all the gates in a collection.
template<typename AGate , typename BGate , typename... OTrigGates>
auto sumGates (AGate A, BGate const &B, OTrigGates const &... others)
Sums all the specified gates.
template<typename BIter , typename EIter >
auto mulGatesSequence (BIter const begin, EIter const end)
Multiplies a sequence of gates.
template<typename GateColl >
auto mulGates (GateColl const &gates)
Multiplies all the gates in a collection.
template<typename AGate , typename BGate , typename... OTrigGates>
auto mulGates (AGate A, BGate const &B, OTrigGates const &... others)
Multiplies all the specified gates.
template<typename BIter , typename EIter >
auto maxGatesSequence (BIter const begin, EIter const end)
Computes the gate with the maximum opening of a sequence of gates.
template<typename GateColl >
auto maxGates (GateColl const &gates)
Computes the gate with the maximum opening of gates from collection.
template<typename AGate , typename BGate , typename... OTrigGates>
auto maxGates (AGate A, BGate const &B, OTrigGates const &... others)
Computes the gate with the maximum opening of the specified gates.
template<typename BIter , typename EIter >
auto minGatesSequence (BIter const begin, EIter const end)
Computes the gate with the minimum opening of a sequence of gates.
template<typename GateColl >
auto minGates (GateColl const &gates)
Computes the gate with the minimum opening of gates from collection.
template<typename AGate , typename BGate , typename... OTrigGates>
auto minGates (AGate A, BGate const &B, OTrigGates const &... others)
Computes the gate with the minimum opening of the specified gates.
template<typename Op , typename AGate , typename BGate , typename... OGates>
AGate OpGates (Op op, AGate A, BGate const &B, OGates const &... others)
Applies an operation to two gates.
template<typename Op , typename GateColl >
auto OpGateColl (Op op, GateColl const &gates)
Computes the result of an operation on all gates from collection.
template<typename Op , typename BIter , typename EIter >
auto OpGatesSequence (Op op, BIter const begin, EIter const end)
Computes the result of an operation on all gates in the sequence.
Variables
template<typename T >
constexpr bool isTrackedTriggerGate_v = isTrackedTriggerGate<T>::value
Whether T is some form of TrackedTriggerGate`.
static constexpr std::size_t kEast = sbn::bits::value<triggerLocation>(triggerLocation::CryoEast)
static constexpr std::size_t kWest = sbn::bits::value<triggerLocation>(triggerLocation::CryoWest)
static constexpr std::size_t kNTriggerLocation = sbn::bits::value<triggerLocation>(triggerLocation::NBits)
static constexpr std::size_t kBNB = sbn::bits::value<triggerSource>(triggerSource::BNB)
static constexpr std::size_t kNuMI = sbn::bits::value<triggerSource>(triggerSource::NuMI)
static constexpr std::size_t kOffBeamBNB = sbn::bits::value<triggerSource>(triggerSource::OffbeamBNB)
static constexpr std::size_t kOffBeamNuMI = sbn::bits::value<triggerSource>(triggerSource::OffbeamNuMI)
static constexpr std::size_t kCalibration = sbn::bits::value<triggerSource>(triggerSource::Calib)
static constexpr std::size_t kNTriggerSource = sbn::bits::value<triggerSource>(triggerSource::NBits)
Exceptions associated to <tt>icarus::trigger::ReadoutTriggerGate</tt> class
template<typename Gate >
constexpr bool isReadoutTriggerGate_v = isReadoutTriggerGate<Gate>::value
Flag: true if Gate type derives from a ReadoutTriggerGate instance.
Optical detector windows
An optical detector window is just a group of optical detectors. For trigger, these windows comprise contiguous optical detectors, and may overlap for better coverage.
The algorithm SlidingWindowDefinitionAlg allows the creation of "sliding" windows. The information on a single window is encoded in a standard container (TriggerWindowChannels_t), with a unique channel number representing each detector in the window in no particular order.
Definitions ("aliases") are here provided for convenience, together with a couple of functions to print the content of a window or a set of windows.
using TriggerWindowChannels_t = std::vector<raw::Channel_t>
Type of optical detector channel list in a window.
using TriggerWindowDefs_t = std::vector<TriggerWindowChannels_t>
Definition of all windows.
void printTriggerWindowChannels (std::ostream &out, TriggerWindowChannels_t const &window)
Prints the composition of the optical detector window inline.
void printTriggerWindowDefs (std::ostream &out, TriggerWindowDefs_t const &windows)
Prints the composition of all windows in long format.
auto dumpTriggerWindowChannels (TriggerWindowChannels_t const &window) -> details::DumpTriggerWindowChannelWrapper
auto dumpTriggerWindowDefs (TriggerWindowDefs_t const &windows) -> details::DumpTriggerWindowDefWrapper
Detailed Description
Trigger simulation for ICARUS.
Typedef Documentation
ADCCounts_t
using icarus::trigger::ADCCounts_t = util::quantities::counts_as<raw::ADC_Count_t>
ADC counts for optical detector readout.
Definition at line 40 of file TriggerTypes.h.
OpDetWaveformDataProductMap_t
using icarus::trigger::OpDetWaveformDataProductMap_t = util::DataProductPointerMap_t<raw::OpDetWaveform>
Map util::DataProductPointerMap_t for raw::OpDetWaveform objects.
Definition at line 44 of file TriggerDataUtils.h.
OpDetWaveformMetaDataProductMap_t
using icarus::trigger::OpDetWaveformMetaDataProductMap_t = util::DataProductPointerMap_t<sbn::OpDetWaveformMeta>
Map util::DataProductPointerMap_t for sbn::OpDetWaveformMeta objects.
Definition at line 47 of file TriggerDataUtils.h.
OpticalTriggerGateData_t
using icarus::trigger::OpticalTriggerGateData_t
Initial value:
 icarus::trigger::ReadoutTriggerGate
    <TriggerGateTick_t, TriggerGateTicks_t, raw::Channel_t>
Type of trigger gate data serialized into art data products.
Definition at line 40 of file OpticalTriggerGate.h.
TrackedOpticalTriggerGate
template<typename TrackedType > using icarus::trigger::TrackedOpticalTriggerGate
Initial value:
 icarus::trigger::TrackedTriggerGate
    <icarus::trigger::OpticalTriggerGateData_t, TrackedType const*>
TrackedTriggerGate wrapper to trigger gate type commonly stored.
Template Parameters
TrackedType type of tracked objects
The data in the gate, of type icarus::trigger::OpticalTriggerGateData_t, is accessed via gate() and it is owned (i.e. if its source is a data product, this is a copy of that data and not a reference to it).
Tracking information stores pointers to existing TrackedType objects (typically raw::OpDetWaveform or sbn::OpDetWaveformMeta).
Definition at line 37 of file TrackedOpticalTriggerGate.h.
TriggerGateTick_t
using icarus::trigger::TriggerGateTick_t = util::quantities::tick::value_t
Tick point.
Definition at line 36 of file OpticalTriggerGate.h.
TriggerGateTicks_t
using icarus::trigger::TriggerGateTicks_t = util::quantities::tick::value_t
Tick interval.
Definition at line 37 of file OpticalTriggerGate.h.
triggerLocation
using icarus::trigger::triggerLocation = sbn::triggerLocation
Definition at line 400 of file BeamBits.h.
triggerSource
using icarus::trigger::triggerSource = sbn::triggerSource
Definition at line 401 of file BeamBits.h.
TriggerWindowChannels_t
using icarus::trigger::TriggerWindowChannels_t = std::vector<raw::Channel_t>
Type of optical detector channel list in a window.
Definition at line 44 of file SlidingWindowDefs.h.
TriggerWindowDefs_t
using icarus::trigger::TriggerWindowDefs_t = std::vector<TriggerWindowChannels_t>
Definition of all windows.
Definition at line 47 of file SlidingWindowDefs.h.
WindowPatterns_t
using icarus::trigger::WindowPatterns_t = std::vector<WindowPattern>
A list of window patterns.
Definition at line 25 of file WindowPattern.h.
Function Documentation
compactdump()
template<typename Tick , typename TickInterval , typename ChannelIDType > auto icarus::trigger::compactdump (ReadoutTriggerGate< Tick, TickInterval, ChannelIDType > const & gate) -> details::CompactFormatter<ReadoutTriggerGate<Tick, TickInterval, ChannelIDType>>
Manipulator-like function for compact format of trigger gates.
Template Parameters
Tick template type Tick for ReadoutTriggerGate
TickInterval template type TickInterval for ReadoutTriggerGate
ChannelIDType template type ChannelIDType for ReadoutTriggerGate
Parameters
gate the gate to be formatted
Returns
a wrapper with the parameters to format the gate
This helper function is always used in the context of the insertion of a trigger gate data object into an output stream:
#include "icaruscode/PMT/Trigger/Utilities/TriggerGateDataFormatting.h"
#include "sbnobj/ICARUS/PMT/Trigger/Data/OpticalTriggerGate.h"
#include "larcorealg/CoreUtils/enumerate.h"
#include <iostream>
// ...
std::vector<icarus::trigger::OpticalTriggerGate> LVDSgates;
// ...
for (auto const& [ iGate, gate ]: util::enumerate(LVDSgates))
  std::cout << "[" << iGate << "] " << compactdump(gate) << std::endl;
The loop will print all the LVDSgates in "compact" mode, one per line, prepended by their position in the collection.
Technical note: compactdump() in the example is found by the compiler via Koenig lookup.
Definition at line 78 of file TriggerGateDataFormatting.h.
Referenced by icarus::trigger::DumpTriggerGateData::analyze(), icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), and icarus::trigger::SlidingWindowTrigger::produceThreshold().
convert() [1/3]
DiscriminatePMTwaveformsByChannel::ChannelInfo_t icarus::trigger::convert (DiscriminatePMTwaveformsByChannel::ChannelConfig const & config)
Definition at line 455 of file DiscriminatePMTwaveformsByChannel_module.cc.
convert() [2/3]
FixBeamGateInfo::BeamChangeRecipe icarus::trigger::convert (FixBeamGateInfo::Config::ChangeGate const & config)
Definition at line 363 of file FixBeamGateInfo_module.cc.
convert() [3/3]
sim::BeamGateInfo icarus::trigger::convert (WriteBeamGateInfo::Config::GateConfig const & config)
Definition at line 187 of file WriteBeamGateInfo_module.cc.
discriminate()
template<typename GateObj > GateObj icarus::trigger::discriminate (GateObj const & gate, typename GateObj::OpeningCount_t threshold = 1U, typename GateObj::OpeningCount_t pass = 1U, typename GateObj::OpeningCount_t fail = 0U) nodiscard
Returns a discriminated version of gate.
Template Parameters
GateObj type of gate being discriminated (and returned)
Parameters
gate the gate to be discriminated
threshold (default: 1) the discrimination threshold
pass (default: 1) discriminated gate value on test pass
fail (default: 0) discriminated gate value on test fail
Returns
a gate resulting from the discrimination of gate.
See also
gateAbove(), gateBelow()
A new gate of the same type as the input gate is returned. This gate has two opening count values: either pass, in the time intervals where the gate is at or above threshold, or fail, in the time intervals where the gate is below threshold.
Examples:
auto const discrGate = discriminate(gate, 5U, 0U, 5U);
auto const discrGateNeg = discriminate(gate, 5U, 5U, 0U);
will have discrGate as a gate with value 0U wherever gate has opening count 4 or less, and 5U where gate has opening count 5 or more. The gatediscrGateNeg has the two opening values swapped and therefore results the complement of discrGate.
Definition at line 411 of file TriggerGateOperations.h.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern().
dumpTriggerWindowChannels()
auto icarus::trigger::dumpTriggerWindowChannels (TriggerWindowChannels_t const & window) -> details::DumpTriggerWindowChannelWrapper inline
Helper for printing a TriggerWindowChannels_t into a stream.
Example:
TriggerWindowChannels_t window; // ... filled with some channels
std::cout << "Window: " << icarus::trigger::dumpTriggerWindowChannels(window);
Definition at line 117 of file SlidingWindowDefs.h.
dumpTriggerWindowDefs()
auto icarus::trigger::dumpTriggerWindowDefs (TriggerWindowDefs_t const & windows) -> details::DumpTriggerWindowDefWrapper inline
Helper for printing a TriggerWindowDefs_t into a stream.
Example:
TriggerWindowDefs_t windows; // ... filled with some content
std::cout << "Windows: " << icarus::trigger::dumpTriggerWindowDefs(windows);
Definition at line 130 of file SlidingWindowDefs.h.
FillTriggerGates()
template<typename OpDetInfo > std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > icarus::trigger::FillTriggerGates (std::vector< icarus::trigger::OpticalTriggerGateData_t > const & gates, art::Assns< icarus::trigger::OpticalTriggerGateData_t, OpDetInfo > const & gateToWaveformInfo)
Creates gate objects out of trigger gate data products.
Template Parameters
OpDetInfo type of the associated waveforms
Parameters
gates collection of data from all the gates
gateToWaveformInfo association between each gate and its waveforms
Returns
a STL vector of TrackedOpticalTriggerGate with copy of data from gates
Objects like icarus::trigger::TrackedOpticalTriggerGate include the gate level information plus the connections to the source objects (waveforms). These objects are complicate enough that they are not saved directly into an art event. Rather, they are diced into pieces and the pieces are stored.
This function stitches the pieces and returns back an object like icarus::trigger::TrackedOpticalTriggerGate.
Example:
std::vector<icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>>
readTriggerGates(art::Event const& event, art::InputTag const& dataTag)
{
  auto const& gates
    = event.getProduct<std::vector<TriggerGateData_t>>(dataTag);
  auto const& gateToWaveforms
    = event.getProduct<art::Assns<TriggerGateData_t, sbn::OpDetWaveformMeta>>
      (dataTag);
  return icarus::trigger::FillTriggerGates<sbn::OpDetWaveformMeta>
    (gates, gateToWaveforms);
} // readTriggerGates()
will read the information from dateTag data products in an art event and return a collection of icarus::trigger::TrackedOpticalTriggerGate objects, each one with a copy of the data of the original data product and a pointer to each of the associated waveform metadata. Note that this specific functionality is now wrapped into icarus::trigger::ReadTriggerGates().
Return value
The returned collection contains one element for each OpticalTriggerGateData_t object in gates, in the same order. Each of these elements is of type icarus::trigger::TrackedOpticalTriggerGate<OpDetInfo>, contains a copy of the data of the corresponding gate, and a list of optical waveform information pointers (OpDetInfo objects) it is associated to.
Requirements
The requirements bind the gates to their association to waveforms:
each gate must be associated to at least one waveform
the associations must be grouped so that all the association pairs pertaining a gate are contiguous
within each of these groups, which is made of at least one waveform, the waveforms must be ordered by increasing timestamp
the groups must be in the same order as their associated gates This constitutes the requirement of one-to-many sequential association with the addition that each element in gates must have at least one associated waveform.
Definition at line 563 of file TriggerDataUtils.h.
Referenced by icarus::trigger::LVDSgates::ReadTriggerGates(), icarus::trigger::SlidingWindowTrigger::ReadTriggerGates(), icarus::trigger::SlidingWindowTriggerSimulation::readTriggerGates(), and icarus::trigger::TriggerEfficiencyPlotsBase::readTriggerGates().
gateDataIn()
template<typename Gate > decltype(auto) icarus::trigger::gateDataIn (Gate && gate)
Returns the trigger data (a TriggerGateData) from the specofied gate.
Definition at line 304 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate().
gateIn()
template<typename Gate > decltype(auto) icarus::trigger::gateIn (Gate && gate)
Returns the trigger gate (a ReadoutTriggerGate) from the specified gate.
Definition at line 296 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate().
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), gatesIn(), OpGates(), and icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses().
gatesIn()
template<typename TrackingGateColl > auto icarus::trigger::gatesIn (TrackingGateColl & trackingGates)
Returns a sequence of all the readout trigger gates contained in trackingGates.
Definition at line 312 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate(), and gateIn().
Referenced by icarus::trigger::LVDSgates::checkInput(), icarus::trigger::TriggerGateBuilder::TriggerGates::dump(), icarus::trigger::TriggerEfficiencyPlotsBase::extractActiveChannels(), icarus::trigger::MajorityTriggerEfficiencyPlots::plotResponses(), icarus::trigger::SlidingWindowTriggerEfficiencyPlots::simulateAndPlot(), transformIntoOpticalTriggerGate(), and transformIntoOpticalTriggerGate().
makeApplyBeamGate() [1/2]
ApplyBeamGateClass icarus::trigger::makeApplyBeamGate (util::quantities::intervals::microseconds duration, detinfo::DetectorClocksData const & clockData, std::string const & logCategory = "ApplyBeamGateClass")
Returns a new ApplyBeamGateClass object with the specified gate.
Parameters
duration the desired duration of the gate
clockData the current detector clocks service provider data
logCategory message category the returned object will use
Returns
a new ApplyBeamGateClass object with the specified parameters
The gate starts at the nominal beam gate time as reported by clockData.
makeApplyBeamGate() [2/2]
ApplyBeamGateClass icarus::trigger::makeApplyBeamGate (util::quantities::intervals::microseconds duration, util::quantities::intervals::microseconds delay, detinfo::DetectorClocksData const & clockData, std::string const & logCategory = "ApplyBeamGateClass")
Returns a new ApplyBeamGateClass object with the specified gate.
Parameters
duration the desired duration of the gate
delay the delay of gate start relative to the global beam gate time
clockData the current detector clocks service provider data
logCategory message category the returned object will use
Returns
a new ApplyBeamGateClass object with the specified parameters
Referenced by icarus::trigger::MajorityTriggerSimulation::makeMyBeamGate(), icarus::trigger::SlidingWindowTriggerSimulation::makeMyBeamGate(), and icarus::trigger::TriggerSimulationOnGates::produceForThreshold().
makeBeamGateStruct()
icarus::trigger::BeamGateStruct icarus::trigger::makeBeamGateStruct (detinfo::DetectorTimings const & detTimings, util::quantities::intervals::microseconds duration, util::quantities::intervals::microseconds delay = util::quantities::intervals::microseconds{ 0.0 })
Creates a BeamGateStruct object of specified duration and start.
Parameters
detTimings object used for time conversions
duration length of the gate [µs]
delay (default: 0_us) time the gate opens relative to beam gate opening [µs]
Returns
a BeamGateStruct
This is for when I will regret to have coupled BeamGateStruct interface to detinfo::DetectorTimings.
Definition at line 181 of file BeamGateStruct.h.
Referenced by icarus::trigger::MakeTriggerSimulationTree::analyze(), icarus::trigger::TriggerEfficiencyPlotsBase::initializePlots(), icarus::trigger::TriggerEfficiencyPlotsBase::makeGatePack(), and icarus::trigger::ExtractEnergyDepositionSummary::produce().
maxGates() [1/2]
template<typename AGate , typename BGate , typename... OTrigGates> auto icarus::trigger::maxGates (AGate A, BGate const & B, OTrigGates const &... others) nodiscard
Computes the gate with the maximum opening of the specified gates.
Template Parameters
AGate type of the first gate; it determines the return type
BGate type of the second gate
OGates type of other gates
Parameters
A first gate
B second gate
others other gates
Returns
a new gate maximum of all the argument gates, of same type as A
See also
maxGatesSequence()
For each tick, the maximum opening among all the specified gates is picked. The returned gate has the same type as the first gate.
Note
There must be at least two gates in the arguments.
maxGates() [2/2]
template<typename GateColl > auto icarus::trigger::maxGates (GateColl const & gates) nodiscard
Computes the gate with the maximum opening of gates from collection.
Template Parameters
GateColl type of collection of gates
Parameters
gates the collection of gates to sum
Returns
a new gate maximum of all the gates
See also
maxGatesSequence()
For each tick, the maximum opening among all the gates in the collection is picked. The returned gate has the same type as the gates in the collection.
Definition at line 571 of file TriggerGateOperations.h.
References maxGatesSequence().
Referenced by icarus::trigger::CryostatTriggerCombiner::combine().
maxGatesSequence()
template<typename BIter , typename EIter > auto icarus::trigger::maxGatesSequence (BIter const begin, EIter const end) nodiscard
Computes the gate with the maximum opening of a sequence of gates.
Template Parameters
BIter type of iterator to the gates to add
EIter type of iterator past-the-end of the sequence of gates to add
Parameters
begin iterator to the first gate to add
end iterator past-the-last gate to add
Returns
a new gate maximum of all the specified ones
See also
maxGates()
For each tick, the maximum opening among all the gates in the sequence is picked. The returned gate has the same type as the first gate.
Definition at line 565 of file TriggerGateOperations.h.
References OpGatesSequence().
Referenced by maxGates().
minGates() [1/2]
template<typename AGate , typename BGate , typename... OTrigGates> auto icarus::trigger::minGates (AGate A, BGate const & B, OTrigGates const &... others) nodiscard
Computes the gate with the minimum opening of the specified gates.
Template Parameters
AGate type of the first gate; it determines the return type
BGate type of the second gate
OGates type of other gates
Parameters
A first gate
B second gate
others other gates
Returns
a new gate minimum of all the argument gates, of same type as A
See also
minGatesSequence()
For each tick, the minimum opening among all the specified gates is picked. The returned gate has the same type as the first gate.
Note
There must be at least two gates in the arguments.
minGates() [2/2]
template<typename GateColl > auto icarus::trigger::minGates (GateColl const & gates) nodiscard
Computes the gate with the minimum opening of gates from collection.
Template Parameters
GateColl type of collection of gates
Parameters
gates the collection of gates to sum
Returns
a new gate minimum of all the gates
See also
minGatesSequence()
For each tick, the minimum opening among all the gates in the collection is picked. The returned gate has the same type as the gates in the collection.
Definition at line 591 of file TriggerGateOperations.h.
References minGatesSequence().
minGatesSequence()
template<typename BIter , typename EIter > auto icarus::trigger::minGatesSequence (BIter const begin, EIter const end) nodiscard
Computes the gate with the minimum opening of a sequence of gates.
Template Parameters
BIter type of iterator to the gates to add
EIter type of iterator past-the-end of the sequence of gates to add
Parameters
begin iterator to the first gate to add
end iterator past-the-last gate to add
Returns
a new gate minimum of all the specified ones
See also
minGates()
For each tick, the minimum opening among all the gates in the sequence is picked. The returned gate has the same type as the first gate.
Definition at line 585 of file TriggerGateOperations.h.
References OpGatesSequence().
Referenced by minGates().
mulGates() [1/2]
template<typename AGate , typename BGate , typename... OTrigGates> auto icarus::trigger::mulGates (AGate A, BGate const & B, OTrigGates const &... others) nodiscard
Multiplies all the specified gates.
Template Parameters
AGate type of the first gate to sum; it determines the return type
BGate type of the second gate to sum
OGates type of other gates to sum
Parameters
A first gate to be multiplied
B second gate to be multiplied
others other gates to be multiplied
Returns
a new gate product of all the argument gates, of the same type as A
See also
mulGatesSequence()
All arguments are combined in the product of the gates. The product of two gates is at each tick the product of the level of opening of the two gates at that tick. The returned gate has the same type as the first gate.
Note
There must be at least two gates in the arguments.
mulGates() [2/2]
template<typename GateColl > auto icarus::trigger::mulGates (GateColl const & gates) nodiscard
Multiplies all the gates in a collection.
Template Parameters
GateColl type of collection of gates
Parameters
gates the collection of gates to multiply
Returns
a new gate product of all the gates
See also
mulGatesSequence()
All gates from the first on are summed. The returned gate has the same type as the gates in the collection.
Definition at line 551 of file TriggerGateOperations.h.
References mulGatesSequence().
Referenced by icarus::trigger::ApplyBeamGateClass::apply().
mulGatesSequence()
template<typename BIter , typename EIter > auto icarus::trigger::mulGatesSequence (BIter const begin, EIter const end) nodiscard
Multiplies a sequence of gates.
Template Parameters
BIter type of iterator to the gates to add
EIter type of iterator past-the-end of the sequence of gates to add
Parameters
begin iterator to the first gate to add
end iterator past-the-last gate to add
Returns
a new gate product of all the specified ones
See also
mulGates()
All gates from the first on are multiplied. The returned gate has the same type as the first gate.
Definition at line 545 of file TriggerGateOperations.h.
References OpGatesSequence().
Referenced by mulGates().
operator<<() [1/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, OpticalTriggerGate const & gate)
Definition at line 237 of file OpticalTriggerGate.cxx.
operator<<() [2/11]
template<typename Tick , typename TickInterval , typename ChannelIDType > std::ostream & icarus::trigger::operator<< (std::ostream & out, ReadoutTriggerGate< Tick, TickInterval, ChannelIDType > const & gate)
Definition at line 325 of file ReadoutTriggerGate.tcc.
operator<<() [3/11]
template<typename TK , typename TI > std::ostream & icarus::trigger::operator<< (std::ostream & out, TriggerGateData< TK, TI > const & gate)
Definition at line 816 of file TriggerGateData.tcc.
operator<<() [4/11]
template<typename TK , typename TI > std::ostream & icarus::trigger::operator<< (std::ostream & out, typename TriggerGateData< TK, TI >::Status const & status)
Definition at line 853 of file TriggerGateData.tcc.
operator<<() [5/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, WindowChannelMap const & wi)
Definition at line 57 of file WindowChannelMap.cxx.
operator<<() [6/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, dumpRecipe const & dr)
Definition at line 614 of file FixBeamGateInfo_module.cc.
operator<<() [7/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, icarus::trigger::ApplyBeamGateClass const & gate)
Definition at line 183 of file ApplyBeamGate.h.
operator<<() [8/11]
template<typename Time > std::ostream & icarus::trigger::operator<< (std::ostream & out, icarus::trigger::BeamGateStruct::TimeRange< Time > const & range)
Definition at line 167 of file BeamGateStruct.h.
operator<<() [9/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, LVDSHWbitID const & bit)
Definition at line 43 of file LVDSbitMaps.cxx.
operator<<() [10/11]
std::ostream & icarus::trigger::operator<< (std::ostream & out, PMTpairBitID const & bit)
Definition at line 33 of file LVDSbitMaps.cxx.
operator<<() [11/11]
template<typename Gate , typename TrackedType > std::ostream & icarus::trigger::operator<< (std::ostream & out, TrackedTriggerGate< Gate, TrackedType > const & gate)
Definition at line 289 of file TrackedTriggerGate.h.
OpGateColl()
template<typename Op , typename GateColl > auto icarus::trigger::OpGateColl (Op op, GateColl const & gates) nodiscard
Computes the result of an operation on all gates from collection.
Template Parameters
Op type of binary operation AGate (Op)(AGate, BGate)
GateColl type of collection of gates
Parameters
op the binary operation to apply (copied)
gates the collection of gates to sum
Returns
a new gate result of op on all the gates
See also
OpGates(), OpGatesSequence()
This is the sequential application of op to all gates via OpGates(), according to their order in the collection. The returned gate has the same type as the gates in the collection.
Definition at line 491 of file TriggerGateOperations.h.
References OpGatesSequence().
OpGates()
template<typename Op , typename AGate , typename BGate , typename... OGates> AGate icarus::trigger::OpGates (Op op, AGate A, BGate const & B, OGates const &... others) nodiscard
Applies an operation to two gates.
Template Parameters
Op type of binary operation AGate (Op)(AGate, BGate)
AGate type of the first gate; it determines the return type
BGate type of the second gate
OGates type of other gates
Parameters
op the binary operation to apply (copied)
A first gate
B second gate
others other gates
Returns
a new gate of same type as A, result of the operation.
See also
OpGatesSequence(), OpGateColl()
For each tick, the operation op is performed between A, B and the others, and the result is stored into the return value. The order of operation is the same as in the arguments: ((A op B) op others...). The returned gate has the same type as the first gate (A).
Standard operations are provided in namespace GateOps.
A specific action is performed if the gates are "tracking" (i.e. instances of TrackedTriggerGate), in which case tracking will also be propagated so that the result includes all the tracked objects of all the operands.
Note
There must be at least two gates in the arguments.
Definition at line 467 of file TriggerGateOperations.h.
References gateIn(), and OpGates().
Referenced by OpGates(), and OpGatesSequence().
OpGatesSequence()
template<typename Op , typename BIter , typename EIter > auto icarus::trigger::OpGatesSequence (Op op, BIter const begin, EIter const end) nodiscard
Computes the result of an operation on all gates in the sequence.
Template Parameters
Op type of binary operation AGate (Op)(AGate, BGate)
BIter type of iterator to the gates to add
EIter type of iterator past-the-end of the sequence of gates to add
Parameters
op the binary operation to apply (copied)
begin iterator to the first gate to add
end iterator past-the-last gate to add
Returns
a new gate result of op on all the gates
See also
OpGates(), OpGateColl()
This is the sequential application of op to all gates from begin to end via OpGates(), following their order in the collection. The returned gate has the same type as the one pointed by the begin iterator (BIter::value_type for standard iterators).
Definition at line 497 of file TriggerGateOperations.h.
References OpGates().
Referenced by maxGatesSequence(), minGatesSequence(), mulGatesSequence(), OpGateColl(), and sumGatesSequence().
printTriggerWindowChannels()
void icarus::trigger::printTriggerWindowChannels (std::ostream & out, TriggerWindowChannels_t const & window)
Prints the composition of the optical detector window inline.
Definition at line 25 of file SlidingWindowDefs.cxx.
Referenced by printTriggerWindowDefs().
printTriggerWindowDefs()
void icarus::trigger::printTriggerWindowDefs (std::ostream & out, TriggerWindowDefs_t const & windows)
Prints the composition of all windows in long format.
Definition at line 48 of file SlidingWindowDefs.cxx.
References printTriggerWindowChannels().
ReadTriggerGates()
template<typename OpDetInfo = sbn::OpDetWaveformMeta, typename Event > std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > icarus::trigger::ReadTriggerGates (Event const & event, art::InputTag const & dataTag)
Assembles and returns trigger gates from serialized data.
Template Parameters
OpDetInfo type of object associated to the gates
Event type of object to read the needed information from
Parameters
event object to read all the needed information from
dataTag tag of the data to read from the event
Returns
a collection of "tracking" trigger gates
Exceptions
cet::exception wrapping any cet::exception thrown internally (typically a data product not found)
See also
icarus::trigger::TriggerGateReader, icarus::trigger::FillTriggerGates()
This function returns "tracking" trigger gates from data read from the data read from event. It is a one-shot replacement for TriggerGateReader to be used when data to be consumed needn't or can't be declared, or when that declaration is performed separately.
Definition at line 654 of file TriggerDataUtils.h.
References icarus::trigger::TriggerGateReader< OpDetInfo >::read().
Referenced by icarus::trigger::TriggerEfficiencyPlots::combineTriggerPrimitives(), icarus::trigger::MajorityTriggerSimulation::produceForThreshold(), icarus::trigger::TriggerSimulationOnGates::produceForThreshold(), icarus::trigger::LVDSgates::produceThreshold(), icarus::trigger::SlidingWindowTrigger::produceThreshold(), and icarus::trigger::TriggerEfficiencyPlots::ReadTriggerGates().
sumGates() [1/2]
template<typename AGate , typename BGate , typename... OTrigGates> auto icarus::trigger::sumGates (AGate A, BGate const & B, OTrigGates const &... others) nodiscard
Sums all the specified gates.
Template Parameters
AGate type of the first gate to sum; it determines the return type
BGate type of the second gate to sum
OGates type of other gates to sum
Parameters
A first gate to be summed
B second gate to be summed
others other gates to be summed
Returns
a new gate sum of all the argument gates, of the same type as A
See also
sumGatesSequence()
All arguments are combined in the sum of the gates. The returned gate has the same type as the first gate.
Note
There must be at least two gates in the arguments.
sumGates() [2/2]
template<typename GateColl > auto icarus::trigger::sumGates (GateColl const & gates) nodiscard
Sums all the gates in a collection.
Template Parameters
GateColl type of collection of gates
Parameters
gates the collection of gates to sum
Returns
a new gate sum of all the gates
See also
sumGatesSequence()
All gates from the first on are summed. The returned gate has the same type as the gates in the collection.
Definition at line 531 of file TriggerGateOperations.h.
References sumGatesSequence().
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::MajorityTriggerCombiner::combine(), icarus::trigger::MajorityTriggerEfficiencyPlots::combineTriggerPrimitives(), icarus::trigger::TriggerEfficiencyPlots::combineTriggerPrimitives(), and icarus::trigger::SlidingWindowCombinerAlg::mergeGateInto().
sumGatesSequence()
template<typename BIter , typename EIter > auto icarus::trigger::sumGatesSequence (BIter const begin, EIter const end) nodiscard
Sums a sequence of gates.
Template Parameters
BIter type of iterator to the gates to add
EIter type of iterator past-the-end of the sequence of gates to add
Parameters
begin iterator to the first gate to add
end iterator past-the-last gate to add
Returns
a new gate sum of all the specified ones
See also
sumGates()
All gates from the first on are summed. The returned gate has the same type as the first gate.
Definition at line 525 of file TriggerGateOperations.h.
References OpGatesSequence().
Referenced by sumGates().
sumTriggerGates()
icarus::trigger::MultiChannelOpticalTriggerGate icarus::trigger::sumTriggerGates (std::vector< SingleChannelOpticalTriggerGate > const & gates)
Definition at line 25 of file MultiChannelOpticalTriggerGate.cxx.
to_string()
std::string icarus::trigger::to_string (WindowPattern const & pattern) inline
Definition at line 115 of file WindowPattern.h.
transformIntoOpticalTriggerGate() [1/2]
template<typename Gates > std::vector< icarus::trigger::OpticalTriggerGateData_t > icarus::trigger::transformIntoOpticalTriggerGate (Gates && gates)
Returns the trigger gates in serializable format.
Template Parameters
Gates type of the source of trigger gate data
Parameters
gates the data to be reformatted (data will be stolen!)
Returns
gate data product
This function transfers the data from the original structured gates into a data collection suitable for serialization with art, but not including the association of each gate with all its contributing waveforms. It must be stressed that this causes information loss, because the trigger gates will not be associated any more to the contributing waveforms.
The return value is a collection of trigger gate data (icarus::trigger::OpticalTriggerGateData_t), with data stolen from gates.
The trigger gates are processed in the same order as they are in gates.
After the function returns, gates will have been depleted of all the gate data; any tracking information will be still associated to each gate, whose gate data will be in an invalid state anyway, only good for destruction.
The object gates is a iterable collection of gate objects: types derived from icarus::trigger::ReadoutTriggerGate and from TrackedOpticalTriggerGate are supported.
In the following example, we start with trigger gates already serialized in a art event. The serialization splits a trigger gate object in two components: the gate levels, and the associated waveforms. In the first part of the example we recover the information from the event and we assemble it into the standard trigger gate objects (of type icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>). After some unspecified and optional processing, gates are disassembled to be saved into the event: this is achieved by a call to transformIntoOpticalTriggerGate() which produces the trigger gate data and their associations to the waveforms. In the last part, these components are both stored into the event.
//
// somehow get/build a collection of trigger gates;
// here we use `FillTriggerGates()` to read existing data from the event
//
std::vector<icarus::trigger::TrackedOpticalTriggerGate<>> gates
  = icarus::trigger::ReadTriggerGates(event, "orig");
// ...
//
// use the created vector and associations (e.g. put them into art event)
//
event.put(std::make_unique<std::vector<icarus::trigger::OpticalTriggerGateData_t>>
  (icarus::trigger::transformIntoOpticalTriggerGate(std::move(gates))));
Also note that in the omitted processing part the trigger gates might have been combined into a different type of gates instead. To serialize that collection, the exact same procedure would be used. Note that in this example the association to the source waveform metadata is not serialised (and presumably lost). Another version of transformIntoOpticalTriggerGate() also provides support for the association to waveform sources.
Definition at line 496 of file TriggerDataUtils.h.
References gatesIn().
Referenced by icarus::trigger::DiscriminatePMTwaveforms::produce(), icarus::trigger::DiscriminatePMTwaveformsByChannel::produce(), icarus::trigger::LVDSgates::produceThreshold(), icarus::trigger::SlidingWindowTrigger::produceThreshold(), and transformIntoOpticalTriggerGate().
transformIntoOpticalTriggerGate() [2/2]
template<typename OpDetInfo = sbn::OpDetWaveformMeta> std::tuple< std::vector< icarus::trigger::OpticalTriggerGateData_t >, art::Assns< icarus::trigger::OpticalTriggerGateData_t, OpDetInfo > > icarus::trigger::transformIntoOpticalTriggerGate (std::vector< icarus::trigger::TrackedOpticalTriggerGate< OpDetInfo > > && gates, art::PtrMaker< icarus::trigger::OpticalTriggerGateData_t > const & makeGatePtr, util::DataProductPointerMap_t< OpDetInfo > const & opDetInfoPtrs)
Returns the trigger gates in serializable format.
Template Parameters
OpDetInfo type of the associated waveforms
Parameters
gates the data to be reformatted (data will be stolen!)
makeGatePtr art pointer maker for the gate data
opDetInfoPtrs map of art pointers to optical waveform information
Returns
a pair: gate data product and associations to OpDetInfo
This function transfers the data from the original structured gates into a data collection suitable for serialization with art, including the association of each gate with all its contributing waveforms.
The return value is a tuple of two elements:
0: collection of trigger gate data (icarus::trigger::OpticalTriggerGateData_t), with data stolen from gates;
1: association between trigger gate data and their optical waveform information, as reported by opDetInfoPtrs.
The trigger gates are processed in the same order as they are in gates, and the associations to the waveform information are set gate by gate, in the same order as they are reported by the tracking information of the input gate.
After the function returns, gates will have been depleted of all the data and left in an unspecified state only good for destruction.
The object gates is a sequence of icarus::trigger::TrackedOpticalTriggerGate objects, each of them containing a trigger gate object (icarus::trigger::OpticalTriggerGateData_t) and a list of tracked sources in the form of OpDetInfo objects.
In the following example, we start with trigger gates already serialized in a art event. The serialization splits a trigger gate object in two components: the gate levels, and the associated waveform information. In the first part of the example we recover the information from the event and we assemble it into the standard trigger gate objects (of type icarus::trigger::OpticalTriggerGateData_t). After some unspecified and optional processing, gates are disassembled to be saved into the event: this is achieved by a call to transformIntoOpticalTriggerGate() which produces the trigger gate data and their associations to the waveform information. In the last part, these components are both stored into the event.
using icarus::trigger::OpticalTriggerGateData_t; // for convenience
//
// somehow get/build a collection of trigger gates;
// here we use `FillTriggerGates()` to read existing data from the event
//
std::vector<icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>> gates
  = icarus::trigger::FillTriggerGates<sbn::OpDetWaveformMeta>
  (
  event.getProduct<std::vector<OpticalTriggerGateData_t>>("orig"),
  event.getProduct<art::Assns<OpticalTriggerGateData_t, sbn::OpDetWaveformMeta>>("orig")
  );
// ...
//
// optical waveform information to pointer map is required to create
// associations between the trigger gates and their waveforms
//
auto const& opDetInfoPtrs = util::mapDataProductPointers
  (event, event.getValidHandle<std::vector<raw::OpDetWaveformMeta>>("opdaq"));
// transform the data; after this line, `gates` is not usable any more
auto thresholdData = icarus::trigger::transformIntoOpticalTriggerGate
  (std::move(gates), makeGatePtr, opDetInfoPtrs);
//
// use the created vector and associations (e.g. put them into art event)
//
event.put(
  std::make_unique<std::vector<OpticalTriggerGateData_t>>
    (std::move(std::get<0U>(thresholdData)))
  );
event.put(
  std::make_unique<art::Assns<OpticalTriggerGateData_t, sbn::OpDetWaveformInfo>>
    (std::move(std::get<1U>(thresholdData)))
  );
In this example the most convenient waveform information is used, sbn::OpDetWaveformMeta; the same syntax would hold for using the more traditional, but encumbering, raw::OpDetWaveform.
Definition at line 518 of file TriggerDataUtils.h.
References gatesIn(), and transformIntoOpticalTriggerGate().
Variable Documentation
isReadoutTriggerGate_v
template<typename Gate > bool icarus::trigger::isReadoutTriggerGate_v = isReadoutTriggerGate<Gate>::value constexpr
Flag: true if Gate type derives from a ReadoutTriggerGate instance.
Definition at line 78 of file ReadoutTriggerGate.h.
isTrackedTriggerGate_v
template<typename T > bool icarus::trigger::isTrackedTriggerGate_v = isTrackedTriggerGate<T>::value constexpr
Whether T is some form of TrackedTriggerGate`.
Definition at line 37 of file TrackedTriggerGate.h.
kBNB
std::size_t icarus::trigger::kBNB = sbn::bits::value<triggerSource>(triggerSource::BNB) static constexpr
Definition at line 407 of file BeamBits.h.
kCalibration
std::size_t icarus::trigger::kCalibration = sbn::bits::value<triggerSource>(triggerSource::Calib) static constexpr
Definition at line 411 of file BeamBits.h.
kEast
std::size_t icarus::trigger::kEast = sbn::bits::value<triggerLocation>(triggerLocation::CryoEast) static constexpr
Definition at line 403 of file BeamBits.h.
kNTriggerLocation
std::size_t icarus::trigger::kNTriggerLocation = sbn::bits::value<triggerLocation>(triggerLocation::NBits) static constexpr
Definition at line 405 of file BeamBits.h.
kNTriggerSource
std::size_t icarus::trigger::kNTriggerSource = sbn::bits::value<triggerSource>(triggerSource::NBits) static constexpr
Definition at line 412 of file BeamBits.h.
kNuMI
std::size_t icarus::trigger::kNuMI = sbn::bits::value<triggerSource>(triggerSource::NuMI) static constexpr
Definition at line 408 of file BeamBits.h.
kOffBeamBNB
std::size_t icarus::trigger::kOffBeamBNB = sbn::bits::value<triggerSource>(triggerSource::OffbeamBNB) static constexpr
Definition at line 409 of file BeamBits.h.
kOffBeamNuMI
std::size_t icarus::trigger::kOffBeamNuMI = sbn::bits::value<triggerSource>(triggerSource::OffbeamNuMI) static constexpr
Definition at line 410 of file BeamBits.h.
kWest
std::size_t icarus::trigger::kWest = sbn::bits::value<triggerLocation>(triggerLocation::CryoWest) static constexpr
Definition at line 404 of file BeamBits.h.