CAF format: SaveConfigurationIntoTFile Class Reference
SaveConfigurationIntoTFile Class Reference
Writes the art configuration into the TFileService file.
Classes
struct Config
Public Types
using Parameters = art::EDAnalyzer::Table<Config>
Public Member Functions
SaveConfigurationIntoTFile (Parameters const &config)
Standard art analyzer moduel constructor.
virtual void beginJob () override
Writes the configuration information of the current process.
virtual void analyze (art::Event const &event) override
Writes the configuration information of the input processes.
Private Member Functions
void saveProcessConfiguration (std::string const &procName, fhicl::ParameterSet const &config)
Writes the specified configuration into a ROOT directory.
bool isProcessConfigurationSaved (std::string const &procName) const
Returns whether we have already saved configuration for procName.
Static Private Member Functions
static fhicl::ParameterSet processConfiguration (art::Event const &event, std::string const &procName)
Extracts the configuration of the specified process from event.
static void storeString (std::string const &key, std::string const &value)
Saves a string via TFileService (as TNamed).
static fhicl::ParameterSet currentProcessConfiguration (std::string const &procName)
Returns the configuration of the current art process.
static bool isProcessConfiguration (fhicl::ParameterSet const &pset)
Returns whether the specified one is a process configuration.
static bool isProcessConfiguration (fhicl::ParameterSet const &pset, std::string const &procName)
Returns whether pset is the configuration of procName process.
Private Attributes
bool fIncludePreviousProcesses = false
Whether to save the configuration of the input file.
std::set< std::string > fProcessedProcesses
Process names already saved.
Detailed Description
Writes the art configuration into the TFileService file.
A TStringObj object is written into the directory assigned by TFileService to this analyzer for every selected process configuration. The TObjString will have the same ROOT name as the process itself. In addition, the following are saved:
current_process (TNamed): the name of this process
The selection of processes is controlled by the module configuration. The current process is always selected.
This module takes a simplistic approach, and prints only the first occurrence of each process name. When saving configuration of processes from the input files, and they contain different configurations for the same process name, only one of them (the first one encountered) will be saved.
Todo
Currently the author does not know how to extract the configuration of the current process, which is therefore a dummy
Configuration parameters
includePreviousProcesses (boolean, default: false): saves also the configuration of all the processes the input file has seen; this has limitations when there are multiple input files (see above).
Definition at line 61 of file SaveConfigurationIntoTFile_module.cc.
Class Documentation
SaveConfigurationIntoTFile::Config
struct SaveConfigurationIntoTFile::Config
Definition at line 65 of file SaveConfigurationIntoTFile_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > includePreviousProcesses
Member Typedef Documentation
Parameters
using SaveConfigurationIntoTFile::Parameters = art::EDAnalyzer::Table<Config>
Definition at line 78 of file SaveConfigurationIntoTFile_module.cc.
Constructor & Destructor Documentation
SaveConfigurationIntoTFile()
SaveConfigurationIntoTFile::SaveConfigurationIntoTFile (Parameters const & config)
Standard art analyzer moduel constructor.
Definition at line 147 of file SaveConfigurationIntoTFile_module.cc.
Member Function Documentation
analyze()
void SaveConfigurationIntoTFile::analyze (art::Event const & event) override virtual
Writes the configuration information of the input processes.
Definition at line 178 of file SaveConfigurationIntoTFile_module.cc.
References fIncludePreviousProcesses, isProcessConfigurationSaved(), processConfiguration(), and saveProcessConfiguration().
beginJob()
void SaveConfigurationIntoTFile::beginJob () override virtual
Writes the configuration information of the current process.
Definition at line 154 of file SaveConfigurationIntoTFile_module.cc.
References currentProcessConfiguration(), saveProcessConfiguration(), and storeString().
currentProcessConfiguration()
fhicl::ParameterSet SaveConfigurationIntoTFile::currentProcessConfiguration (std::string const & procName) static private
Returns the configuration of the current art process.
Definition at line 245 of file SaveConfigurationIntoTFile_module.cc.
References isProcessConfiguration().
Referenced by beginJob().
isProcessConfiguration() [1/2]
bool SaveConfigurationIntoTFile::isProcessConfiguration (fhicl::ParameterSet const & pset) static private
Returns whether the specified one is a process configuration.
Definition at line 289 of file SaveConfigurationIntoTFile_module.cc.
Referenced by currentProcessConfiguration(), and isProcessConfiguration().
isProcessConfiguration() [2/2]
bool SaveConfigurationIntoTFile::isProcessConfiguration (fhicl::ParameterSet const & pset, std::string const & procName) static private
Returns whether pset is the configuration of procName process.
Definition at line 319 of file SaveConfigurationIntoTFile_module.cc.
References isProcessConfiguration().
isProcessConfigurationSaved()
bool SaveConfigurationIntoTFile::isProcessConfigurationSaved (std::string const & procName) const inline private
Returns whether we have already saved configuration for procName.
Definition at line 103 of file SaveConfigurationIntoTFile_module.cc.
References fProcessedProcesses.
Referenced by analyze().
processConfiguration()
fhicl::ParameterSet SaveConfigurationIntoTFile::processConfiguration (art::Event const & event, std::string const & procName) static private
Extracts the configuration of the specified process from event.
Definition at line 215 of file SaveConfigurationIntoTFile_module.cc.
Referenced by analyze().
saveProcessConfiguration()
void SaveConfigurationIntoTFile::saveProcessConfiguration (std::string const & procName, fhicl::ParameterSet const & config) private
Writes the specified configuration into a ROOT directory.
Definition at line 201 of file SaveConfigurationIntoTFile_module.cc.
References fProcessedProcesses, and storeString().
Referenced by analyze(), and beginJob().
storeString()
void SaveConfigurationIntoTFile::storeString (std::string const & key, std::string const & value) static private
Saves a string via TFileService (as TNamed).
Definition at line 223 of file SaveConfigurationIntoTFile_module.cc.
Referenced by beginJob(), and saveProcessConfiguration().
Member Data Documentation
fIncludePreviousProcesses
bool SaveConfigurationIntoTFile::fIncludePreviousProcesses = false private
Whether to save the configuration of the input file.
Definition at line 93 of file SaveConfigurationIntoTFile_module.cc.
Referenced by analyze().
fProcessedProcesses
std::set<std::string> SaveConfigurationIntoTFile::fProcessedProcesses private
Process names already saved.
Definition at line 96 of file SaveConfigurationIntoTFile_module.cc.
Referenced by isProcessConfigurationSaved(), and saveProcessConfiguration().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/SaveConfigurationIntoTFile_module.cc