CAF format: util::CacheGuard Class Reference
util::CacheGuard Class Reference
Tracks the status of a cache.
#include <CacheCounter.h>
Public Member Functions
CacheGuard (CacheCounter::CacheTag_t tag="")
Constructor: prepares monitoring of cache tag.
CacheGuard (CacheCounter const &cache, CacheCounter::CacheTag_t tag="")
Constructor: prepares monitoring of cache tag of the specified object.
void setCache (CacheCounter const &cache)
Changes the default cache.
void unsetCache ()
Removes the default cache.
CacheCounter::CacheID_t lastUpdateID () const
Returns the ID of the cache at the last update.
bool wasUpdated (CacheCounter::CacheID_t cacheID) const
bool wasUpdated (CacheCounter const &cache) const
Returns whether the cache was updated since the last update() call.
bool wasUpdated () const
bool update (CacheCounter::CacheID_t cacheID)
Returns if the cache was outdated, and at the same time updates its ID.
bool update (CacheCounter const &cache)
Returns if the cache was outdated, and at the same time updates its ID.
bool update ()
Private Member Functions
CacheCounter const & defaultCache () const
Returns the default cache object, throwing std::logic_error if not set.
void chooseCache (CacheCounter const *cache)
Changes the default cache.
Private Attributes
CacheCounter const * fDefaultCache = nullptr
Pointer to the cache to monitor by default.
CacheCounter::CacheTag_t fCacheTag
Tag of the cache to monitor.
CacheCounter::CacheID_t fLastCacheID = CacheCounter::NoCache
The ID of the cache at the last check.
Detailed Description
Tracks the status of a cache.
See also
util::CacheCounter
This class tracks the status of a cache, represented by an integer (ID). The cache is supposed to update (increment) that ID value each time it updates the cache content itself. This object tracks that ID and reports whether it has changed since the last time.
There are two elements of the interface:
update() unconditionally acquires the current ID of the cache; it also returns whether it's a new ID (like wasUpdated()).
wasUpdated() compares the current cache ID to the one acquired by the last update() call, and returns whether the current cache is newer.
While the cache ID can be any number, and the interface allows to directly provide the cache ID, nonetheless this class has a special relationship with util::CacheCounter: it can point to a specific tag name of any cache, or it can point to a specific cache and tag, with a simpler interface. If a CacheGuard object needs to track a specific cache or cache tag, that must be specified at construction time.
Note that the object always starts with no update.
Also note that a cache ID of util::CacheCounter::NoCache is specially treated and a cache with that ID will never be considered up to date.
Example
A database access class performs standard queries reading time-dependent data from a database. It caches the result of the query, and it updates the cache when a time is requested that is not the one present in the cache. This class also derives from util::CacheCounter to offer the cache updating track capability.
An analysis class uses the data from the database to produce results. It stores the small amount of data derived by the database that is needed for the computation, and it needs to refetch or recompute that data when its local cache is outdated. To do this it has a util::CacheGuard data member bound to the database access class above.
class DatabaseQuery: public util::CacheCounter {
  bool fetchData()
    {
      // ...
      return true;
    }
  void updateCache() { if (fetchData()) updateCacheID(); }
    public:
  using Data_t = ... ;
  Data_t query();
};
DatabaseQuery DBquery;
class DataUser {
  util::CacheGuard fDatabaseQueryCacheGuard;
  DatabaseQuery::Data_t fCachedQueryResult;
  DatabaseQuery::Data_t const& queryResults()
    {
      if (fDatabaseQueryCacheGuard.update())
        fCachedQueryResult = DBquery.query();
      return fCachedQueryResult;
    }
    public:
  DataUser(): fDatabaseQueryCache{ DBquery } {}
  void compute()
    {
      DatabaseQuery::Data_t const& data = queryResults();
      // ...
    }
}; // DataUser
Definition at line 196 of file CacheCounter.h.
Constructor & Destructor Documentation
CacheGuard() [1/2]
util::CacheGuard::CacheGuard (CacheCounter::CacheTag_t tag = "") inline
Constructor: prepares monitoring of cache tag.
Definition at line 222 of file CacheCounter.h.
CacheGuard() [2/2]
util::CacheGuard::CacheGuard (CacheCounter const & cache, CacheCounter::CacheTag_t tag = "") inline
Constructor: prepares monitoring of cache tag of the specified object.
Definition at line 225 of file CacheCounter.h.
Member Function Documentation
chooseCache()
void util::CacheGuard::chooseCache (CacheCounter const * cache) inline private
Changes the default cache.
Definition at line 216 of file CacheCounter.h.
References fDefaultCache, fLastCacheID, and util::CacheCounter::NoCache.
Referenced by setCache(), and unsetCache().
defaultCache()
CacheCounter const & util::CacheGuard::defaultCache () const inline private
Returns the default cache object, throwing std::logic_error if not set.
Definition at line 208 of file CacheCounter.h.
References fDefaultCache.
Referenced by update(), and wasUpdated().
lastUpdateID()
CacheCounter::CacheID_t util::CacheGuard::lastUpdateID () const inline
Returns the ID of the cache at the last update.
Definition at line 236 of file CacheCounter.h.
References fLastCacheID.
setCache()
void util::CacheGuard::setCache (CacheCounter const & cache) inline
Changes the default cache.
Definition at line 229 of file CacheCounter.h.
References chooseCache().
unsetCache()
void util::CacheGuard::unsetCache () inline
Removes the default cache.
Definition at line 232 of file CacheCounter.h.
References chooseCache().
update() [1/3]
bool util::CacheGuard::update () inline
Returns if the default cache was outdated, and at the same time updates its ID.
Definition at line 274 of file CacheCounter.h.
References defaultCache(), and update().
Referenced by update(), and update().
update() [2/3]
bool util::CacheGuard::update (CacheCounter const & cache) inline
Returns if the cache was outdated, and at the same time updates its ID.
Definition at line 269 of file CacheCounter.h.
References util::CacheCounter::cacheID(), fCacheTag, and update().
update() [3/3]
bool util::CacheGuard::update (CacheCounter::CacheID_t cacheID) inline
Returns if the cache was outdated, and at the same time updates its ID.
Definition at line 260 of file CacheCounter.h.
References fLastCacheID, and util::CacheCounter::NoCache.
Referenced by daq::TriggerDecoderV3::setupRun().
wasUpdated() [1/3]
bool util::CacheGuard::wasUpdated () const inline
Returns whether the default cache was updated since the last update() call.
Definition at line 252 of file CacheCounter.h.
References defaultCache(), and wasUpdated().
Referenced by wasUpdated(), and wasUpdated().
wasUpdated() [2/3]
bool util::CacheGuard::wasUpdated (CacheCounter const & cache) const inline
Returns whether the cache was updated since the last update() call.
Definition at line 247 of file CacheCounter.h.
References util::CacheCounter::cacheID(), fCacheTag, and wasUpdated().
wasUpdated() [3/3]
bool util::CacheGuard::wasUpdated (CacheCounter::CacheID_t cacheID) const inline
Returns whether the cache, which has cacheID ID, was updated since the last update() call.
Definition at line 243 of file CacheCounter.h.
References fLastCacheID, and util::CacheCounter::NoCache.
Member Data Documentation
fCacheTag
CacheCounter::CacheTag_t util::CacheGuard::fCacheTag private
Tag of the cache to monitor.
Definition at line 202 of file CacheCounter.h.
Referenced by update(), and wasUpdated().
fDefaultCache
CacheCounter const* util::CacheGuard::fDefaultCache = nullptr private
Pointer to the cache to monitor by default.
Definition at line 199 of file CacheCounter.h.
Referenced by chooseCache(), and defaultCache().
fLastCacheID
CacheCounter::CacheID_t util::CacheGuard::fLastCacheID = CacheCounter::NoCache private
The ID of the cache at the last check.
Definition at line 205 of file CacheCounter.h.
Referenced by chooseCache(), lastUpdateID(), update(), and wasUpdated().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/CacheCounter.h