CAF format: caldata::RawDigitFilterAlg Class Reference
caldata::RawDigitFilterAlg Class Reference
Public Member Functions
RawDigitFilterAlg (const fhicl::ParameterSet &pset)
~RawDigitFilterAlg ()
Destructor.
void configure (const fhicl::ParameterSet &pset) override
void initializeHistograms (art::TFileDirectory &) const override
size_t plane () const override
void FilterWaveform (RawDigitVector &, size_t, size_t, float=0.) const override
Public Member Functions inherited from caldata::IRawDigitFilter
Private Member Functions
void doAdaptiveFilter (RawDigitVector &) const
Private Attributes
float fTruncMeanFraction
Fraction for truncated mean.
size_t fStructuringElement
Structuring element to use with Top Hat filter.
bool fFillHistograms
if true then will fill diagnostic hists
size_t fPlane
RawDigitCharacterizationAlg fCharacterizationAlg
art::ServiceHandle< geo::Geometry > fGeometry
pointer to Geometry service
Detailed Description
Definition at line 26 of file RawDigitFilterAlg_tool.cc.
Constructor & Destructor Documentation
RawDigitFilterAlg()
caldata::RawDigitFilterAlg::RawDigitFilterAlg (const fhicl::ParameterSet & pset) explicit
Constructor.
Arguments:
pset - Fcl parameters.
Definition at line 66 of file RawDigitFilterAlg_tool.cc.
References configure().
~RawDigitFilterAlg()
caldata::RawDigitFilterAlg::~RawDigitFilterAlg ()
Destructor.
Definition at line 78 of file RawDigitFilterAlg_tool.cc.
Member Function Documentation
configure()
void caldata::RawDigitFilterAlg::configure (const fhicl::ParameterSet & pset) override virtual
Reconfigure method.
Arguments:
pset - Fcl parameter set.
Implements caldata::IRawDigitFilter.
Definition at line 88 of file RawDigitFilterAlg_tool.cc.
References fFillHistograms, fStructuringElement, fTruncMeanFraction, and caldata::RawDigitCharacterizationAlg::reconfigure().
Referenced by RawDigitFilterAlg().
FilterWaveform()
void caldata::RawDigitFilterAlg::FilterWaveform (RawDigitVector & dataVec, size_t channel, size_t cnt, float pedestal = 0.) const override virtual
Implements caldata::IRawDigitFilter.
Definition at line 103 of file RawDigitFilterAlg_tool.cc.
initializeHistograms()
void caldata::RawDigitFilterAlg::initializeHistograms (art::TFileDirectory & tfs) const override virtual
Implements caldata::IRawDigitFilter.
Definition at line 97 of file RawDigitFilterAlg_tool.cc.
plane()
size_t caldata::RawDigitFilterAlg::plane () const inline override virtual
Implements caldata::IRawDigitFilter.
Definition at line 37 of file RawDigitFilterAlg_tool.cc.
Member Data Documentation
fCharacterizationAlg
RawDigitCharacterizationAlg caldata::RawDigitFilterAlg::fCharacterizationAlg private
Definition at line 53 of file RawDigitFilterAlg_tool.cc.
fFillHistograms
bool caldata::RawDigitFilterAlg::fFillHistograms private
if true then will fill diagnostic hists
Definition at line 48 of file RawDigitFilterAlg_tool.cc.
Referenced by configure().
fGeometry
art::ServiceHandle<geo::Geometry> caldata::RawDigitFilterAlg::fGeometry private
pointer to Geometry service
Definition at line 56 of file RawDigitFilterAlg_tool.cc.
fPlane
size_t caldata::RawDigitFilterAlg::fPlane private
Definition at line 50 of file RawDigitFilterAlg_tool.cc.
fStructuringElement
size_t caldata::RawDigitFilterAlg::fStructuringElement private
Structuring element to use with Top Hat filter.
Definition at line 47 of file RawDigitFilterAlg_tool.cc.
Referenced by configure().
fTruncMeanFraction
float caldata::RawDigitFilterAlg::fTruncMeanFraction private
Fraction for truncated mean.
Definition at line 46 of file RawDigitFilterAlg_tool.cc.
Referenced by configure().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/TPC/SignalProcessing/RawDigitFilter/Algorithms/RawDigitFilterAlg_tool.cc