CAF format: icarus::opdet::SimPMTreadout::PrimitiveManager Class Reference
icarus::opdet::SimPMTreadout::PrimitiveManager Class Reference
Tracks the required primitives per optical detector channel.
Public Member Functions
PrimitiveManager (geo::GeometryCore const &geom)
std::vector< electronics_time > const & forChannel (raw::Channel_t channel) const
Returns all the readout windows for the specified channel.
void addPrimitiveForCryostat (electronics_time time, geo::CryostatID cryo)
Adds a primitive at the specified time for all channels in cryo.
void addPrimitiveToAllChannels (electronics_time time)
Adds a primitive at the specified time for all channels.
void prepare ()
Prepares for queries; not essential, but add deterministic flow.
Private Member Functions
void modify ()
void refreshCaches (bool force=false) const
Refreshes all caches. Note that this is a "const" method.
Static Private Member Functions
static std::vector< geo::CryostatID > makeChannelMap (geo::GeometryCore const &geom)
Creates a map of all PMT channels into cryostat ID.
Private Attributes
std::vector< geo::CryostatID > const fCryostatOf
Cryostat ID of each PMT channel.
std::vector< std::vector< electronics_time > > fPrimitives
Cached primitives per cryostat.
std::atomic_bool fModified { false }
Changes happened since last cache refresh.
std::mutex fRefreshMutex
Lock used while refreshing caches.
Detailed Description
Tracks the required primitives per optical detector channel.
Definition at line 419 of file SimPMTreadout_module.cc.
Constructor & Destructor Documentation
PrimitiveManager()
icarus::opdet::SimPMTreadout::PrimitiveManager::PrimitiveManager (geo::GeometryCore const & geom)
Definition at line 675 of file SimPMTreadout_module.cc.
Member Function Documentation
addPrimitiveForCryostat()
void icarus::opdet::SimPMTreadout::PrimitiveManager::addPrimitiveForCryostat (electronics_time time, geo::CryostatID cryo)
Adds a primitive at the specified time for all channels in cryo.
Definition at line 692 of file SimPMTreadout_module.cc.
Referenced by icarus::opdet::SimPMTreadout::addLocalPrimitives().
addPrimitiveToAllChannels()
void icarus::opdet::SimPMTreadout::PrimitiveManager::addPrimitiveToAllChannels (electronics_time time)
Adds a primitive at the specified time for all channels.
Definition at line 707 of file SimPMTreadout_module.cc.
Referenced by icarus::opdet::SimPMTreadout::addGlobalPrimitives().
forChannel()
auto icarus::opdet::SimPMTreadout::PrimitiveManager::forChannel (raw::Channel_t channel) const
Returns all the readout windows for the specified channel.
Definition at line 683 of file SimPMTreadout_module.cc.
makeChannelMap()
std::vector< geo::CryostatID > icarus::opdet::SimPMTreadout::PrimitiveManager::makeChannelMap (geo::GeometryCore const & geom) static private
Creates a map of all PMT channels into cryostat ID.
Definition at line 664 of file SimPMTreadout_module.cc.
modify()
void icarus::opdet::SimPMTreadout::PrimitiveManager::modify () inline private
Definition at line 432 of file SimPMTreadout_module.cc.
prepare()
void icarus::opdet::SimPMTreadout::PrimitiveManager::prepare () inline
Prepares for queries; not essential, but add deterministic flow.
Definition at line 456 of file SimPMTreadout_module.cc.
References refreshCaches().
refreshCaches()
void icarus::opdet::SimPMTreadout::PrimitiveManager::refreshCaches (bool force = false) const private
Refreshes all caches. Note that this is a "const" method.
Definition at line 638 of file SimPMTreadout_module.cc.
Referenced by prepare().
Member Data Documentation
fCryostatOf
std::vector<geo::CryostatID> const icarus::opdet::SimPMTreadout::PrimitiveManager::fCryostatOf private
Cryostat ID of each PMT channel.
Definition at line 422 of file SimPMTreadout_module.cc.
fModified
std::atomic_bool icarus::opdet::SimPMTreadout::PrimitiveManager::fModified { false } mutable private
Changes happened since last cache refresh.
Definition at line 428 of file SimPMTreadout_module.cc.
fPrimitives
std::vector<std::vector<electronics_time> > icarus::opdet::SimPMTreadout::PrimitiveManager::fPrimitives mutable private
Cached primitives per cryostat.
Definition at line 425 of file SimPMTreadout_module.cc.
fRefreshMutex
std::mutex icarus::opdet::SimPMTreadout::PrimitiveManager::fRefreshMutex mutable private
Lock used while refreshing caches.
Definition at line 430 of file SimPMTreadout_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/SimPMTreadout_module.cc