CAF format: icarus::opdet::PMTsimulationAlg Class Reference
icarus::opdet::PMTsimulationAlg Class Reference
Algorithm class for the full simulation of PMT channels.
#include <PMTsimulationAlg.h>
Classes
struct ConfigurationParameters_t
Type holding all configuration parameters for this algorithm.
class GainFluctuator
class TimeToTickAndSubtickConverter
Functor to convert tick point into a tick number and a subsample index.
Public Types
enum class DiscriminationAlgo { Unset , AboveThreshold , CrossingThreshold }
How to discriminate the waveform to determine the readout regions.
using microsecond = util::quantities::microsecond
using nanosecond = util::quantities::nanosecond
using hertz = util::quantities::hertz
using megahertz = util::quantities::megahertz
using picocoulomb = util::quantities::picocoulomb
using tick = util::quantities::tick
using ADCcount = DiscretePhotoelectronPulse::ADCcount
using time_interval = detinfo::timescales::time_interval
using optical_tick = detinfo::timescales::optical_tick
Public Member Functions
PMTsimulationAlg (ConfigurationParameters_t const &config)
Constructor.
std::tuple< std::vector< raw::OpDetWaveform >, std::optional< sim::SimPhotons > > simulate (sim::SimPhotons const &photons, sim::SimPhotonsLite const &lite_photons)
Returns the waveforms originating from simulated photons.
template<typename Stream >
void printConfiguration (Stream &&out, std::string indent="") const
Prints the configuration into the specified output stream.
Static Public Attributes
static util::MultipleChoiceSelection< DiscriminationAlgo > const DiscrimAlgoSelector
Manages the conversion between names and values of DiscriminationAlgo.
Private Types
using OpDetWaveformMaker_t = icarus::opdet::OpDetWaveformMakerClass<ADCcount>
using Waveform_t = OpDetWaveformMaker_t::WaveformData_t
Type internally used for storing waveforms.
using WaveformValue_t = util::value_t<ADCcount>
Numeric type in waveforms.
using PulseSampling_t = DiscretePhotoelectronPulse::Subsample_t
Type of sampled pulse shape: sequence of samples, one per tick.
using DiscriminationAlgoProc_t
Type of member function for zero-suppression discrimination.
Private Member Functions
auto makeGainFluctuator () const
Returns a configured gain fluctuator object.
Waveform_t CreateFullWaveform (sim::SimPhotons const &photons, sim::SimPhotonsLite const &lite_photons, std::optional< sim::SimPhotons > &photons_used) const
Creates raw::OpDetWaveform objects from simulated photoelectrons.
std::vector< raw::OpDetWaveform > CreateFixedSizeOpDetWaveforms (raw::Channel_t opChannel, Waveform_t const &waveform) const
Creates raw::OpDetWaveform objects from a waveform data.
template<typename Combine >
void AddPulseShape (PulseSampling_t const &pulse, Waveform_t &wave, tick const time_bin, Combine combination) const
Adds a pulse to a waveform, starting at a given tick.
void AddPhotoelectrons (PulseSampling_t const &pulse, Waveform_t &wave, tick const time_bin, WaveformValue_t const n) const
Adds a number of pulses to a waveform, starting at a given tick.
void AddPedestal (raw::Channel_t channel, std::uint64_t time, Waveform_t &wave) const
Add the pedestal, including electronics noise.
void AddDarkNoise (Waveform_t &wave) const
std::vector< optical_tick > FindTriggers (Waveform_t const &wvfm, ADCcount baseline) const
Returns time points in wvfm where the readout should happen.
std::vector< optical_tick > CreateTriggersCrossingThreshold (Waveform_t const &wvfm, ADCcount baseline) const
Ticks in the specified waveform where some signal activity starts.
std::vector< optical_tick > CreateTriggersAboveThreshold (Waveform_t const &wvfm, ADCcount baseline) const
Ticks in the specified waveform where some signal activity starts.
std::vector< optical_tick > CreateBeamGateTriggers () const
Generate periodic interest points regardless the actual activity.
bool KicksPhotoelectron () const
Returns a random response whether a photon generates a photoelectron.
std::pair< ADCcount, ADCcount > saturationRange (ADCcount baseline) const
Returns the ADC range allowed for photoelectron saturation.
void ApplySaturation (Waveform_t &waveform, ADCcount baseline, std::pair< ADCcount, ADCcount > const &range) const
void ApplySaturation (Waveform_t &waveform, ADCcount baseline) const
Applies the configured photoelectron saturation on the waveform.
std::uint64_t waveformStartTimestamp () const
Returns the timestamp matching the start of the full waveforms [UTC, ns].
Static Private Member Functions
static void ClipWaveform (Waveform_t &waveform, ADCcount min, ADCcount max)
Forces waveform ADC within the min to max range (max included).
static DiscriminationAlgoProc_t selectDiscriminationAlgo (DiscriminationAlgo algo)
Returns the method corresponding to the specified algorithm enumerator.
Private Attributes
ConfigurationParameters_t fParams
Complete algorithm configuration.
double fQE
PMT quantum efficiency.
megahertz fSampling
Wave sampling frequency [MHz].
std::size_t fNsamples
Samples per waveform.
DiscretePhotoelectronPulse wsp
PedestalGenerator_t * fPedestalGen = nullptr
Single photon pulse (sampled).
DiscriminationAlgoProc_t fDiscrAlgo = nullptr
Member function for the zero suppression discrimination algorithm.
Detailed Description
Algorithm class for the full simulation of PMT channels.
The algorithm creates simulated PMT waveforms as read out by ICARUS, including the generation of trigger primitives. Contributions to the waveforms include:
physical photons
dark noise
electronics noise
The algorithm processes an optical channel at a time, independently and uncorrelated from the other channels. For each channel, multiple waveforms may be generated according to the readout parameters.
Activity sources
Physical photons
Photons are read from sim::SimPhotons data objects, each one pertaining a single optical detector channel. Each photon on the channel is assumed to have successfully reached the external surface of the photocathode, with the wavelength shifter. Depending on the upstream simulation, and in particular on the photon visibility library settings, the photon might have also already passed the wavelength shifting and even triggered the conversion to a detectable photoelectron.
Quantum efficiency is simulated to determine if each photon converts into a photoelectron on the internal side of the photocathode. The target quantum efficiency is specified via the QE configuration parameter. It is assumed that some level of quantum efficiency has already been simulated upstream: more precisely, that the quantum efficiency already applied is in the amount returned by detinfo::LArProperties::ScintPreScale(). Therefore:
the quantum efficiency applied here is only the residual one to go from detinfo::LArProperties::ScintPreScale() to the value in QE
there is no implement here to increase quantum efficiency, i.e. QE must not exceed detinfo::LArProperties::ScintPreScale()
if the configuration specifies a target quantum efficiency QE larger than the one applied upstream (detinfo::LArProperties::ScintPreScale()), a warning message is printed, and no change to quantum efficiency is performed
Note that if the upstream code has not applied any quantum efficiency, the configuration should give a detinfo::LArProperties::ScintPreScale() of 1.0.
Note
If the photon visibility library already includes the probability of the photon converting to a photoelectron, the quantum efficiency check here should be skipped by setting the efficiency to 1.
For each converting photon, a photoelectron is added to the channel by placing a template waveform shape into the channel waveform.
The timestamp of each waveform is based on the same scale as the trigger time, as defined by detinfo::DetectorClocks::TriggerTime(). On that scale, the timestamp pins down the time of the first sample of the waveform. Note that this is typically earlier than when the actual signal starts. More precisely, the signal is defined to start at an interest point (see FindTriggers() for their definition), and the waveform starts (at tick #0) earlier than that by a fraction PreTrigFraction of the readout window size ReadoutWindowSize (both are configuration parameters of the algorithm), allowing for that amount of pre-trigger data.
The configuration parameter TriggerOffsetPMT describes how much earlier than the trigger time the optical readout has started. Note that if an interest point (see above) happens early after optical readout has started, there might be not enough data to fill the pre-trigger data. In such case, the interest point will just be located earlier than usual within the final waveform. This situation may be caused for example by asynchronous physics events like scintillation light from cosmic rays or radioactive decay of the detector materials, or from a fluctuation of the noise.
Photoelectrons
The response of the PMT to a single photoelectron is passed to the algorithm as a full blown function of type SinglePhotonResponseFunc_t. The function needs to be valid for the lifetime of the algorithm, since the algorithm refers to without owning it, and it is expected not to change during that time. See icarus::opdet::SimPMTIcarus
To account for gain fluctuations, that shape is considered to correspond to a nominal gain (PMTspecs.gain configuration parameter), which is then fluctuated to obtain the effective gain. This feature can be disabled by setting configuration parameter FluctuateGain to false. The approximation used here is that the fluctuation is entirely due to the first stage of multiplication. The gain on the first stage is described as a random variable with Poisson distribution around the mean gain. The gain on a single photoelectron at the first stage is, in fact, an integral number in each case. The time spread of the signal may be increased by the difference in time of the different branches of the multiplication avalanche. Therefore, increasing or decreasing the number of branches, as it is done by changing the gain of the first stage, the time evolution of the signal will also be likewise affected. At this time we do not take this aspect into account in the simulation. For the nominal settings of a Hamamatsu 5912 photomultiplier (gain 10 ^7^, high multiplication on the first stage) the gain at the first stage is around 20, causing a fluctuation of about 20%. If the multiplication were equally distributed across the stages, that fluctuation would be almost 45%.
The first stage gain is computed by icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::multiplicationStageGain().
Dark noise
Dark noise, i.e. the noise originating by "spontaneous" emission of a photoelectron in the photocathode without any external stimulation, is simulated by randomly extracting the time such emission happens. Each emission causes a photoelectron template waveform to be added at the extracted time. The rate of dark noise emission is set by configuration with DarkNoiseRate parameter.
Electronics noise
Electronics noise generation is delegated to an algorithm that also sets the waveform baseline and which can actually either add noise or transform the signal. Currently the "standard" noise model is Gaussian fluctuations of a given standard deviation, from tools PMTgausNoiseGeneratorTool or PMTfastGausNoiseGeneratorTool, with no noise correlation either in time or in space, while the standard pedestal model is a fixed value (PMTconstantPedestalGeneratorTool). Noise can be disabled by using the PMTnoNoiseGeneratorTool.
Configuration
PMT specifications
PMT specifications are used to evaluate the variance of the gain. The details of the calculation are documented in icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::PMTspecs_t::multiplicationStageGain().
The available parameters include:
gain (default: 1e7): the nominal gain of the PMT; this is just a reference value.
voltageDistribution is a sequence of values, one for each stage of the multiplication chain of the PMT. Each number represents the relative size of the resistance that determines the fall of the potential on that stage. Only the stages that contribute to the gain need to be included. The absolute value of each element is inconsequential. For example, a 10-stage PMT with the first stage having twice the resistance of all the other would be represented by the setting [ 2, 1, 1, 1, 1, 1, 1, 1, 1, 1 ].
dynodeK (default: 0.75) represents the dependence of the gain of a stage on the potential drop: \(\mu_{i} \propto (\Delta V_{i})^{k} \) (with \(\mu_{i} \) the gain for stage \(i \), \(\Delta V_{i} \) the drop of potential of that stage and \(k \) the parameter set by dynodeK.
DiscrimAlgo (choice, default: "CrossingThreshold"): selects one of the hard-coded discrimination algorithms used for zero suppression. The suppression algorithm identifies some interesting time points and issues a "trigger primitive" for each of them. A readout buffer is build around each trigger primitive (they are merged when overlapping). The algorithms currently supported are:
CrossingThreshold: a trigger primitive is issued whenever the signal passes from below threshold to above threshold. This algorithm suffers from a problem with large signals if the readout buffer is too short: the large signal may exceed the buffer while staying strictly above threshold and its tail will be lost until a fluctuation below and then back above threshold happens.
AboveThreshold: a trigger primitive is issued on each sample above threshold, regardless the neighbours. No sample below threshold will be suppressed, and if the readout buffer is longer than the single photoelectron response (as it should) the tail of the buffer will always contain just noise.
Random number generators
Three independent random engines are currently used in the simulation:
"main" random engine:
residual quantum efficiency;
gain fluctuations;
"dark noise" engine: dark current noise only;
"electronics noise" engine: electronics noise only.
Structure of the algorithm
This section needs completion.
The algorithm is serviceable immediately after construction. Construction relies on a custom parameter data structure.
An utility, PMTsimulationAlgMaker, splits the set up in two parts:
configuration, where the full set of parameters is learned;
set up, where service providers, random number engines and the external single photon response function are acquired.
This is supposed to make the creation of the filling of parameter structure and the creation of the algorithm easier. At that point, a single sim::SimPhotons can be processed (simulate()) at a time, or multiple at the same time (see the multithreading notes below).
The function used to describe the single particle response is customizable and it must in fact be specified by the caller, since there is no default form. The function must implement the PulseFunction_t interface.
Multithreading notes
The algorithm processes one channel at a time, and it does not depend on event-level information; therefore, the same algorithm object can be used to process many events in sequence. On the other hand, multithreading is impaired by the random number generation, in the sense that multithreading will break reproducibility if the random engine is not magically thread-resistant.
If the set up is event-dependent, then this object can't be used for multiple events at the same time. There is no global state, so at least different instances of the algorithm can be run at the same time. In fact, the creation of an algorithm is expected to take negligible time compared to its run time on a single event, and it is conceivable to create a new algorithm instance for each event.
Definition at line 371 of file PMTsimulationAlg.h.
Member Typedef Documentation
ADCcount
using icarus::opdet::PMTsimulationAlg::ADCcount = DiscretePhotoelectronPulse::ADCcount
Definition at line 380 of file PMTsimulationAlg.h.
DiscriminationAlgoProc_t
using icarus::opdet::PMTsimulationAlg::DiscriminationAlgoProc_t private
Initial value:
 std::vector<optical_tick> (PMTsimulationAlg::*)
      (Waveform_t const& wvfm, ADCcount baseline) const
Type of member function for zero-suppression discrimination.
Definition at line 579 of file PMTsimulationAlg.h.
hertz
using icarus::opdet::PMTsimulationAlg::hertz = util::quantities::hertz
Definition at line 376 of file PMTsimulationAlg.h.
megahertz
using icarus::opdet::PMTsimulationAlg::megahertz = util::quantities::megahertz
Definition at line 377 of file PMTsimulationAlg.h.
microsecond
using icarus::opdet::PMTsimulationAlg::microsecond = util::quantities::microsecond
Definition at line 374 of file PMTsimulationAlg.h.
nanosecond
using icarus::opdet::PMTsimulationAlg::nanosecond = util::quantities::nanosecond
Definition at line 375 of file PMTsimulationAlg.h.
OpDetWaveformMaker_t
using icarus::opdet::PMTsimulationAlg::OpDetWaveformMaker_t = icarus::opdet::OpDetWaveformMakerClass<ADCcount> private
Definition at line 568 of file PMTsimulationAlg.h.
optical_tick
using icarus::opdet::PMTsimulationAlg::optical_tick = detinfo::timescales::optical_tick
Definition at line 383 of file PMTsimulationAlg.h.
picocoulomb
using icarus::opdet::PMTsimulationAlg::picocoulomb = util::quantities::picocoulomb
Definition at line 378 of file PMTsimulationAlg.h.
PulseSampling_t
using icarus::opdet::PMTsimulationAlg::PulseSampling_t = DiscretePhotoelectronPulse::Subsample_t private
Type of sampled pulse shape: sequence of samples, one per tick.
Definition at line 576 of file PMTsimulationAlg.h.
tick
using icarus::opdet::PMTsimulationAlg::tick = util::quantities::tick
Definition at line 379 of file PMTsimulationAlg.h.
time_interval
using icarus::opdet::PMTsimulationAlg::time_interval = detinfo::timescales::time_interval
Definition at line 382 of file PMTsimulationAlg.h.
Waveform_t
using icarus::opdet::PMTsimulationAlg::Waveform_t = OpDetWaveformMaker_t::WaveformData_t private
Type internally used for storing waveforms.
Definition at line 571 of file PMTsimulationAlg.h.
WaveformValue_t
using icarus::opdet::PMTsimulationAlg::WaveformValue_t = util::value_t<ADCcount> private
Numeric type in waveforms.
Definition at line 573 of file PMTsimulationAlg.h.
Member Enumeration Documentation
DiscriminationAlgo
enum class icarus::opdet::PMTsimulationAlg::DiscriminationAlgo strong
How to discriminate the waveform to determine the readout regions.
Enumerator
Unset
Mode not set.
AboveThreshold
Readout triggered when signal is above threshold.
CrossingThreshold
Readout triggered when signal crosses threshold.
Definition at line 386 of file PMTsimulationAlg.h.
Constructor & Destructor Documentation
PMTsimulationAlg()
icarus::opdet::PMTsimulationAlg::PMTsimulationAlg (ConfigurationParameters_t const & config)
Constructor.
Definition at line 99 of file PMTsimulationAlg.cxx.
References icarus::opdet::DiscretePhotoelectronPulse::checkRange(), fDiscrAlgo, fParams, fQE, icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::larProp, and icarus::opdet::PMTsimulationAlg::ConfigurationParameters_t::QEbase.
Member Function Documentation
AddDarkNoise()
void icarus::opdet::PMTsimulationAlg::AddDarkNoise (Waveform_t & wave) const private
Definition at line 653 of file PMTsimulationAlg.cxx.
AddPedestal()
void icarus::opdet::PMTsimulationAlg::AddPedestal (raw::Channel_t channel, std::uint64_t time, Waveform_t & wave) const private
Add the pedestal, including electronics noise.
Definition at line 644 of file PMTsimulationAlg.cxx.
AddPhotoelectrons()
void icarus::opdet::PMTsimulationAlg::AddPhotoelectrons (PulseSampling_t const & pulse, Waveform_t & wave, tick const time_bin, WaveformValue_t const n) const private
Adds a number of pulses to a waveform, starting at a given tick.
Parameters
pulse the sampling to add, scaled, to the waveform
wave the waveform the pulses will be added to
time_bin the tick of the waveform where the pulses start being added
n the number of pulses added (it may be fractional)
All the samples of pulse are scaled by the factor n and then added to the sampling waveform wave, starting from the time_bin sample of this waveform.
The pulse samples are a sequence of ADC counts describing the single photoelectron pulse shape. The waveform is also a sequence of samples representing a optical detector channel digitized waveform, starting at tick #0.
Definition at line 603 of file PMTsimulationAlg.cxx.
AddPulseShape()
template<typename Combine > void icarus::opdet::PMTsimulationAlg::AddPulseShape (PulseSampling_t const & pulse, Waveform_t & wave, tick const time_bin, Combine combination) const private
Adds a pulse to a waveform, starting at a given tick.
Template Parameters
Combine binary operation combining two ADC counts into one
Parameters
pulse the sampling to add to the waveform
wave the waveform the pulse will be added to
time_bin the tick of the waveform where the pulse starts
combination how to combine the pulse and the waveform
This is the internal implementation of AddPhotoelectrons().
The combination functor behaves as a binary function taking the existing wave sample and the sample from the pulse at the same time and returning their combination as a new sample value.
Definition at line 624 of file PMTsimulationAlg.cxx.
ApplySaturation() [1/2]
void icarus::opdet::PMTsimulationAlg::ApplySaturation (Waveform_t & waveform, ADCcount baseline) const private
Applies the configured photoelectron saturation on the waveform.
Definition at line 725 of file PMTsimulationAlg.cxx.
ApplySaturation() [2/2]
void icarus::opdet::PMTsimulationAlg::ApplySaturation (Waveform_t & waveform, ADCcount baseline, std::pair< ADCcount, ADCcount > const & range) const private
Applies the configured photoelectron saturation on the waveform, only if the saturation is cutting into the digitisation range.
Definition at line 738 of file PMTsimulationAlg.cxx.
ClipWaveform()
void icarus::opdet::PMTsimulationAlg::ClipWaveform (Waveform_t & waveform, ADCcount min, ADCcount max) static private
Forces waveform ADC within the min to max range (max included).
Definition at line 758 of file PMTsimulationAlg.cxx.
CreateBeamGateTriggers()
auto icarus::opdet::PMTsimulationAlg::CreateBeamGateTriggers () const private
Generate periodic interest points regardless the actual activity.
Returns
a collection of ticks where we pretend interesting activity to be
See also
FindTriggers()
This methods emits a list of interest points according to the algorithm configuration. More precisely, if CreateBeamGateTriggers is configured true, BeamGateTriggerNReps interest points are generated at BeamGateTriggerRepPeriod intervals, starting from the beam gate time as defined by detinfo::DetectorClocks::BeamGateTime().
See FindTriggers() for the meaning of "interest point".
Note
It is assumed that tick 0 happens at a time defined by triggerOffsetPMT configuration parameter after the trigger (but since the value of that parameter is expected to be negative, tick 0 effectively happens before the trigger).
Definition at line 346 of file PMTsimulationAlg.cxx.
CreateFixedSizeOpDetWaveforms()
std::vector< raw::OpDetWaveform > icarus::opdet::PMTsimulationAlg::CreateFixedSizeOpDetWaveforms (raw::Channel_t opChannel, Waveform_t const & waveform) const private
Creates raw::OpDetWaveform objects from a waveform data.
Parameters
opChannel number of optical detector channel the data belongs to
waveform the waveform data
Returns
a collection of raw::OpDetWaveform
The waveform data is a sequence of samples on the optical detector channel, starting at the beginning of the optical time clock, that is set by the algorithm configuration as the global hardware trigger time (configured in detinfo::DetectorClocks) and an offset. It may be obtained from CreateFullWaveform().
Multiple waveforms may be returned for a single channel, since a form of zero suppression is applied by the simulated hardware. The waveforms are guaranteed to be non-overlapping, non-contiguous and sorted with increasing timestamp.
The procedure attempts to mimic the working mode of CAEN V1730B boards as described on page 32 of the manual "UM2792_V1730_V1725_rev2.pdf" in SBN DocDB 15024.
Algorithm details
In the board readout language, the "trigger" is the per-channel information that the signal on the channel has passed the threshold.
It is critical to understand the details of the generation of the triggers. At the time of writing, the algorithm in FindTriggers() emits a trigger every time the signal passes from under threshold to beyond threshold. Assuming that the threshold is at less than one photoelectron, this kind of behavior implies that every scintillation photons arriving on the tail of the first (large?) signal will add a new waveform in tail. It is not clear what happens if two more triggers happen while the window from the first trigger is still open.
The assumptions in the code include:
overlapped triggers are not discarded (p. 32);
board is set for self-trigger (p. 38);
each waveform has a fixed duration (except the ones overlapping the previous one);
when a trigger starts the recording window on a channel, only the last trigger happening during that window ("overlapping"), if any, is kept.
at decoding time, contiguous buffers are merged in a single waveform
The fixed duration of the waveform if the sum of pre- and post-trigger window length. If during this window another trigger is emitted, a new window will follow the current one and it will be long enough to contain all the post-trigger data.
Definition at line 493 of file PMTsimulationAlg.cxx.
CreateFullWaveform()
auto icarus::opdet::PMTsimulationAlg::CreateFullWaveform (sim::SimPhotons const & photons, sim::SimPhotonsLite const & lite_photons, std::optional< sim::SimPhotons > & photons_used) const private
Creates raw::OpDetWaveform objects from simulated photoelectrons.
Parameters
photons the simulated list of photoelectrons
photons_used (output) list of used photoelectrons
Returns
a collection of digitised raw::OpDetWaveform objects
This function performs the digitization of a optical detector channel which is collecting the photoelectrons in the photons list.
The photoelectrons are already screened for quantum efficiency: all of them are considered for use. It is still possible, if a reduction of the quantum efficiency is requested, that some of them are discarded.
The photons_used output argument is constructed and filled only if the configuration of the algorithm requires the creation of a list of used photons.
Definition at line 185 of file PMTsimulationAlg.cxx.
CreateTriggersAboveThreshold()
auto icarus::opdet::PMTsimulationAlg::CreateTriggersAboveThreshold (Waveform_t const & wvfm, ADCcount baseline) const private
Ticks in the specified waveform where some signal activity starts.
Parameters
wvfm the waveform to parse
ADCcount the value of the reference baseline
Returns
a collection of ticks with interesting activity, sorted
See also
FindTriggers(), CreateTriggersCrossingThreshold()
This is an implementation of the algorithm for FindTriggers().
An interest point is created whenever the signal is above a set threshold (configuration parameter ThresholdADC). Instead of issuing a trigger for every sample above the threshold, triggers are issued no more often than a readout post-trigger buffer as configured. This is just a computing optimization that should have no visible effect as long as each trigger is represented by a full readout window in the final waveform.
Compared to the CreateTriggersCrossingThreshold(), this algorithm does not suffer from the effect of truncating strong signals but it will produce potentially more waveforms. If the threshold is lower than a single photoelectron, though, the main effect will only be potentially longer waveforms.
Definition at line 430 of file PMTsimulationAlg.cxx.
Referenced by selectDiscriminationAlgo().
CreateTriggersCrossingThreshold()
auto icarus::opdet::PMTsimulationAlg::CreateTriggersCrossingThreshold (Waveform_t const & wvfm, ADCcount baseline) const private
Ticks in the specified waveform where some signal activity starts.
Parameters
wvfm the waveform to parse
ADCcount the value of the reference baseline
Returns
a collection of ticks with interesting activity, sorted
See also
FindTriggers(), CreateTriggersAboveThreshold()
This is an implementation of the algorithm for FindTriggers().
An interest point is created whenever the signal passes from below the set threshold (configuration parameter ThresholdADC) to above it. This is also similar to how the CAEN 1730B readout board discrimination works, although this algorithm is by no mean sufficient to correctly emulate the work of that readout board, and the thresholds are better be left low so that a second-step readout simulation can take place afterwards.
Note that this algorithm can artificially truncate a strong signal which stays above threshold long time after having crossed it: in that case, only a trigger at the crossing point is issued, and if the signal is longer than the set readout window, truncation will occur.
Definition at line 399 of file PMTsimulationAlg.cxx.
Referenced by selectDiscriminationAlgo().
FindTriggers()
auto icarus::opdet::PMTsimulationAlg::FindTriggers (Waveform_t const & wvfm, ADCcount baseline) const private
Returns time points in wvfm where the readout should happen.
Parameters
wvfm the waveform to parse
ADCcount the value of the reference baseline
Returns
a collection of ticks with interesting activity, sorted
See also
CreateBeamGateTriggers(), CreateTriggersCrossingThreshold(), CreateTriggersAboveThreshold()
This method is a portal to enable the actual functions performing the task.
We define an "interest point" a time when some activity in the waveform is considered interesting enough to be recorded. This method returns a list of interest points, in the form of the index they are located at in the waveform wvfm.
These interest points are local readout triggers that drive zero suppression on the optical readout channel and that are not necessarily causing any level of event trigger.
Currently only two algorithms are set for this task: CreateTriggersCrossingThreshold(), which has been the algorithm of choice since the beginning, and CreateTriggersAboveThreshold().
This method also adds the mandatory beam gate interest points as explained in CreateBeamGateTriggers() documentation. These are additional interest points that are added independently of whether there is actual interesting activity in there.
Definition at line 373 of file PMTsimulationAlg.cxx.
KicksPhotoelectron()
bool icarus::opdet::PMTsimulationAlg::KicksPhotoelectron () const private
Returns a random response whether a photon generates a photoelectron.
Definition at line 598 of file PMTsimulationAlg.cxx.
makeGainFluctuator()
auto icarus::opdet::PMTsimulationAlg::makeGainFluctuator () const private
Returns a configured gain fluctuator object.
Definition at line 170 of file PMTsimulationAlg.cxx.
printConfiguration()
template<typename Stream > void icarus::opdet::PMTsimulationAlg::printConfiguration (Stream && out, std::string indent = "") const
Prints the configuration into the specified output stream.
Definition at line 1182 of file PMTsimulationAlg.h.
saturationRange()
auto icarus::opdet::PMTsimulationAlg::saturationRange (ADCcount baseline) const private
Returns the ADC range allowed for photoelectron saturation.
Definition at line 711 of file PMTsimulationAlg.cxx.
selectDiscriminationAlgo()
auto icarus::opdet::PMTsimulationAlg::selectDiscriminationAlgo (DiscriminationAlgo algo) static private
Returns the method corresponding to the specified algorithm enumerator.
Definition at line 800 of file PMTsimulationAlg.cxx.
References CreateTriggersAboveThreshold(), and CreateTriggersCrossingThreshold().
simulate()
std::tuple< std::vector< raw::OpDetWaveform >, std::optional< sim::SimPhotons > > icarus::opdet::PMTsimulationAlg::simulate (sim::SimPhotons const & photons, sim::SimPhotonsLite const & lite_photons)
Returns the waveforms originating from simulated photons.
Parameters
photons all the photons simulated to land on the channel
Returns
a list of optical waveforms, response to those photons, and which photons were used (if requested)
Due to threshold readout, a single channel may result in multiple waveforms, which are all on the same channel but disjunct in time.
The second element of the return value is optional and filled only if the trackSelectedPhotons configuration parameter is set to true. In that case, the returned sim::SimPhotons contains a copy of each of the photons contributing to any of the waveforms.
Definition at line 154 of file PMTsimulationAlg.cxx.
waveformStartTimestamp()
std::uint64_t icarus::opdet::PMTsimulationAlg::waveformStartTimestamp () const private
Returns the timestamp matching the start of the full waveforms [UTC, ns].
Definition at line 780 of file PMTsimulationAlg.cxx.
Member Data Documentation
DiscrimAlgoSelector
util::MultipleChoiceSelection< icarus::opdet::PMTsimulationAlg::DiscriminationAlgo > const icarus::opdet::PMTsimulationAlg::DiscrimAlgoSelector static
Initial value:
{
    { DiscriminationAlgo::AboveThreshold,     "AboveThreshold"    }
  , { DiscriminationAlgo::CrossingThreshold,  "CrossingThreshold" }
}
Manages the conversion between names and values of DiscriminationAlgo.
Definition at line 61 of file PMTsimulationAlg.h.
Referenced by icarus::opdet::PMTsimulationAlgMaker::Config::getDiscriminationAlgo().
fDiscrAlgo
DiscriminationAlgoProc_t icarus::opdet::PMTsimulationAlg::fDiscrAlgo = nullptr private
Member function for the zero suppression discrimination algorithm.
Definition at line 640 of file PMTsimulationAlg.h.
Referenced by PMTsimulationAlg().
fNsamples
std::size_t icarus::opdet::PMTsimulationAlg::fNsamples private
Samples per waveform.
Definition at line 632 of file PMTsimulationAlg.h.
fParams
ConfigurationParameters_t icarus::opdet::PMTsimulationAlg::fParams private
Complete algorithm configuration.
Definition at line 628 of file PMTsimulationAlg.h.
Referenced by PMTsimulationAlg().
fPedestalGen
PedestalGenerator_t* icarus::opdet::PMTsimulationAlg::fPedestalGen = nullptr private
Single photon pulse (sampled).
Pedestal and electronics noise generator algorithm.
Definition at line 637 of file PMTsimulationAlg.h.
fQE
double icarus::opdet::PMTsimulationAlg::fQE private
PMT quantum efficiency.
Definition at line 630 of file PMTsimulationAlg.h.
Referenced by PMTsimulationAlg().
fSampling
megahertz icarus::opdet::PMTsimulationAlg::fSampling private
Wave sampling frequency [MHz].
Definition at line 631 of file PMTsimulationAlg.h.
wsp
DiscretePhotoelectronPulse icarus::opdet::PMTsimulationAlg::wsp private
Definition at line 634 of file PMTsimulationAlg.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Algorithms/PMTsimulationAlg.h
icaruscode/icaruscode/PMT/Algorithms/PMTsimulationAlg.cxx