CAF format: pmtana::FlashAlgoFactory Class Reference
pmtana::FlashAlgoFactory Class Reference
FlashAlgoFinder
Factory class for instantiating flash algorithm instance.
#include <FlashAlgoFactory.h>
Public Member Functions
~FlashAlgoFactory ()
Default dtor.
void add_factory (const std::string name, pmtana::FlashAlgoFactoryBase *factory)
Factory registration method (should be called by global factory instance in algorithm header)
FlashAlgoBase * create (const std::string name, const std::string instance_name)
Factory creation method (should be called by clients, possibly you!)
Static Public Member Functions
static FlashAlgoFactory & get ()
Static sharable instance getter.
Private Member Functions
FlashAlgoFactory ()
Default ctor, shouldn't be used.
Private Attributes
std::map< std::string, pmtana::FlashAlgoFactoryBase * > _factory_map
Static factory container.
Static Private Attributes
static FlashAlgoFactory * _me = nullptr
Static self.
Detailed Description
Factory class for instantiating flash algorithm instance.
Definition at line 40 of file FlashAlgoFactory.h.
Constructor & Destructor Documentation
FlashAlgoFactory()
pmtana::FlashAlgoFactory::FlashAlgoFactory () inline private
Default ctor, shouldn't be used.
Definition at line 43 of file FlashAlgoFactory.h.
Referenced by get().
~FlashAlgoFactory()
pmtana::FlashAlgoFactory::~FlashAlgoFactory () inline
Default dtor.
Definition at line 46 of file FlashAlgoFactory.h.
References _factory_map.
Member Function Documentation
add_factory()
void pmtana::FlashAlgoFactory::add_factory (const std::string name, pmtana::FlashAlgoFactoryBase * factory) inline
Factory registration method (should be called by global factory instance in algorithm header)
Definition at line 51 of file FlashAlgoFactory.h.
References _factory_map.
Referenced by pmtana::SimpleFlashAlgoFactory::SimpleFlashAlgoFactory().
create()
FlashAlgoBase * pmtana::FlashAlgoFactory::create (const std::string name, const std::string instance_name) inline
Factory creation method (should be called by clients, possibly you!)
Definition at line 54 of file FlashAlgoFactory.h.
References _factory_map.
get()
static FlashAlgoFactory & pmtana::FlashAlgoFactory::get () inline static
Static sharable instance getter.
Definition at line 48 of file FlashAlgoFactory.h.
References _me, and FlashAlgoFactory().
Referenced by pmtana::SimpleFlashAlgoFactory::SimpleFlashAlgoFactory().
Member Data Documentation
_factory_map
std::map<std::string,pmtana::FlashAlgoFactoryBase*> pmtana::FlashAlgoFactory::_factory_map private
Static factory container.
Definition at line 66 of file FlashAlgoFactory.h.
Referenced by add_factory(), create(), and ~FlashAlgoFactory().
_me
pmtana::FlashAlgoFactory * pmtana::FlashAlgoFactory::_me = nullptr static private
Static self.
Definition at line 68 of file FlashAlgoFactory.h.
Referenced by get().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/OpReco/FlashFinder/FlashAlgoFactory.h
icaruscode/icaruscode/PMT/OpReco/FlashFinder/FlashAlgoFactory.cxx