CAF format: icarus::trigger::TriggerGateBuilder Class Reference
icarus::trigger::TriggerGateBuilder Class Reference abstract
Algorithm to produce trigger gates out of optical readout waveforms.
#include <TriggerGateBuilder.h>
Classes
struct Config
class TriggerGates
Container of logical gates for all triggering channels for a threshold.
Public Types
using Channel_t = raw::Channel_t
Public Member Functions
TriggerGateBuilder (Config const &config)
Constructor: sets the configuration.
virtual ~TriggerGateBuilder ()=default
Virtual destructor. Nothing special about it, except that it's virtual.
virtual void setup (detinfo::DetectorTimings const &timings)
Algorithm setup.
virtual void reset ()
Algorithm reset. It will require a new setup before using it again.
virtual void resetup (detinfo::DetectorTimings const &timings)
Resets and sets up.
virtual void resetup (detinfo::DetectorTimings const &timings, std::vector< ADCCounts_t > const &thresholds)
Resets and sets up (including a new set of thresholds).
virtual std::vector< TriggerGates > build (std::vector< WaveformWithBaseline > const &waveforms) const =0
Returns a collection of TriggerGates objects sorted by threshold.
std::vector< ADCCounts_t > const & channelThresholds () const
Returns all the configured thresholds.
std::size_t nChannelThresholds () const
Returns the number of configured thresholds.
optical_tick timeToOpticalTick (microsecond time) const
Converts a time [µs] into optical ticks.
optical_tick timeStampToOpticalTick (raw::TimeStamp_t time) const
Converts a timestamp from raw::OpDetWaveform into optical ticks.
Static Public Member Functions
static constexpr bool isValidChannel (Channel_t channel)
Returns whether channel is valid.
Static Public Attributes
static constexpr Channel_t InvalidChannel = std::numeric_limits<Channel_t>::max()
Mnemonic for an invalid optical detector channel.
Protected Member Functions
detinfo::DetectorTimings const & detTimings () const
Returns a detector timings object.
std::vector< TriggerGates > prepareAllGates () const
virtual void doSetThresholds (std::vector< ADCCounts_t > const &thresholds)
Sets all thresholds anew.
Private Attributes
std::vector< ADCCounts_t > fChannelThresholds
All single channel thresholds, sorted in increasing order.
std::optional< detinfo::DetectorTimings > fDetTimings
LArSoft detector timing utility.
Detailed Description
Algorithm to produce trigger gates out of optical readout waveforms.
See also
icarus::trigger::DynamicTriggerGateBuilder, icarus::trigger::FixedTriggerGateBuilder
This is an abstract class. Derived algorithms need to provide a way to actually build() the gates.
Definition at line 102 of file TriggerGateBuilder.h.
Class Documentation
icarus::trigger::TriggerGateBuilder::Config
struct icarus::trigger::TriggerGateBuilder::Config
Definition at line 184 of file TriggerGateBuilder.h.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Sequence< value_t > ChannelThresholds
Member Typedef Documentation
Channel_t
using icarus::trigger::TriggerGateBuilder::Channel_t = raw::Channel_t
Definition at line 108 of file TriggerGateBuilder.h.
Constructor & Destructor Documentation
TriggerGateBuilder()
icarus::trigger::TriggerGateBuilder::TriggerGateBuilder (Config const & config)
Constructor: sets the configuration.
Definition at line 162 of file TriggerGateBuilder.cxx.
References fChannelThresholds.
~TriggerGateBuilder()
virtual icarus::trigger::TriggerGateBuilder::~TriggerGateBuilder () virtual default
Virtual destructor. Nothing special about it, except that it's virtual.
Member Function Documentation
build()
virtual std::vector< TriggerGates > icarus::trigger::TriggerGateBuilder::build (std::vector< WaveformWithBaseline > const & waveforms) const pure virtual
Returns a collection of TriggerGates objects sorted by threshold.
Implemented in icarus::trigger::DynamicTriggerGateBuilder, and icarus::trigger::FixedTriggerGateBuilder.
channelThresholds()
std::vector< ADCCounts_t > const & icarus::trigger::TriggerGateBuilder::channelThresholds () const inline
Returns all the configured thresholds.
Definition at line 229 of file TriggerGateBuilder.h.
References fChannelThresholds.
Referenced by icarus::trigger::ManagedTriggerGateBuilder::buildChannelGates(), and nChannelThresholds().
detTimings()
detinfo::DetectorTimings const & icarus::trigger::TriggerGateBuilder::detTimings () const inline protected
Returns a detector timings object.
Definition at line 250 of file TriggerGateBuilder.h.
References fDetTimings.
doSetThresholds()
virtual void icarus::trigger::TriggerGateBuilder::doSetThresholds (std::vector< ADCCounts_t > const & thresholds) inline protected virtual
Sets all thresholds anew.
Definition at line 257 of file TriggerGateBuilder.h.
References fChannelThresholds.
Referenced by resetup().
isValidChannel()
static constexpr bool icarus::trigger::TriggerGateBuilder::isValidChannel (Channel_t channel) inline static constexpr
Returns whether channel is valid.
Definition at line 244 of file TriggerGateBuilder.h.
References InvalidChannel.
nChannelThresholds()
std::size_t icarus::trigger::TriggerGateBuilder::nChannelThresholds () const inline
Returns the number of configured thresholds.
Definition at line 233 of file TriggerGateBuilder.h.
References channelThresholds().
prepareAllGates()
auto icarus::trigger::TriggerGateBuilder::prepareAllGates () const protected
Creates an empty TriggerGates object for each threshold; thresholds are kept relative.
Definition at line 205 of file TriggerGateBuilder.cxx.
reset()
virtual void icarus::trigger::TriggerGateBuilder::reset () inline virtual
Algorithm reset. It will require a new setup before using it again.
Definition at line 211 of file TriggerGateBuilder.h.
Referenced by resetup().
resetup() [1/2]
virtual void icarus::trigger::TriggerGateBuilder::resetup (detinfo::DetectorTimings const & timings) inline virtual
Resets and sets up.
Definition at line 214 of file TriggerGateBuilder.h.
References reset(), and setup().
Referenced by resetup().
resetup() [2/2]
virtual void icarus::trigger::TriggerGateBuilder::resetup (detinfo::DetectorTimings const & timings, std::vector< ADCCounts_t > const & thresholds) inline virtual
Resets and sets up (including a new set of thresholds).
Definition at line 218 of file TriggerGateBuilder.h.
References doSetThresholds(), and resetup().
setup()
void icarus::trigger::TriggerGateBuilder::setup (detinfo::DetectorTimings const & timings) virtual
Algorithm setup.
Reimplemented in icarus::trigger::FixedTriggerGateBuilder.
Definition at line 180 of file TriggerGateBuilder.cxx.
Referenced by resetup().
timeStampToOpticalTick()
auto icarus::trigger::TriggerGateBuilder::timeStampToOpticalTick (raw::TimeStamp_t time) const
Converts a timestamp from raw::OpDetWaveform into optical ticks.
Definition at line 197 of file TriggerGateBuilder.cxx.
Referenced by icarus::trigger::ManagedTriggerGateBuilder::buildChannelGates().
timeToOpticalTick()
auto icarus::trigger::TriggerGateBuilder::timeToOpticalTick (microsecond time) const
Converts a time [µs] into optical ticks.
Definition at line 188 of file TriggerGateBuilder.cxx.
Member Data Documentation
fChannelThresholds
std::vector<ADCCounts_t> icarus::trigger::TriggerGateBuilder::fChannelThresholds private
All single channel thresholds, sorted in increasing order.
Definition at line 265 of file TriggerGateBuilder.h.
Referenced by channelThresholds(), doSetThresholds(), and TriggerGateBuilder().
fDetTimings
std::optional<detinfo::DetectorTimings> icarus::trigger::TriggerGateBuilder::fDetTimings private
LArSoft detector timing utility.
Definition at line 273 of file TriggerGateBuilder.h.
Referenced by detTimings().
InvalidChannel
Channel_t icarus::trigger::TriggerGateBuilder::InvalidChannel = std::numeric_limits<Channel_t>::max() static constexpr
Mnemonic for an invalid optical detector channel.
Definition at line 111 of file TriggerGateBuilder.h.
Referenced by isValidChannel().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/TriggerGateBuilder.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/TriggerGateBuilder.cxx