CAF format: icarus::trigger::BeamGateMaker Class Reference
icarus::trigger::BeamGateMaker Class Reference
Simple utility to generate gates around beam time.
#include <BeamGateMaker.h>
Public Types
using time_interval = detinfo::timescales::time_interval
using optical_time = detinfo::timescales::optical_time
using optical_tick = detinfo::timescales::optical_tick
using optical_time_ticks = detinfo::timescales::optical_time_ticks
Public Member Functions
BeamGateMaker (detinfo::DetectorTimings const &detTimings)
Constructor: uses a copy of the specified detector timing provider.
BeamGateMaker (detinfo::DetectorClocksData const &clockData)
Constructor: uses the specified detector clocks service.
template<typename Gate = icarus::trigger::OpticalTriggerGate>
Gate make (time_interval length, time_interval delay=DefaultDelay) const
Returns a gate object of the specified duration.
template<typename Gate = icarus::trigger::OpticalTriggerGate>
Gate operator() (time_interval length, time_interval delay=DefaultDelay) const
Start and end time
optical_time startTime (time_interval const delay=DefaultDelay) const
optical_time endTime (time_interval const duration, time_interval const delay=DefaultDelay) const
Time of beam gate closure, in optical time scale.
optical_tick startTick (time_interval const delay=DefaultDelay) const
optical_tick endTick (time_interval const duration, time_interval const delay=DefaultDelay) const
Time of beam gate closure, in optical ticks.
Private Attributes
detinfo::DetectorTimings const fDetTimings
Detector timing provider.
Static Private Attributes
static constexpr util::quantities::microsecond DefaultDelay { 0.0 }
Value used for default delay.
Detailed Description
Simple utility to generate gates around beam time.
Example: to create an object describing a beam gate of 10 µs, run:
using namespace util::quantities::time_literals;
icarus::trigger::BeamGateMaker makeBeamGate
  (*lar::providerFrom<detinfo::DetectorClocks>());
auto const beamGate = makeBeamGate(10_us);
The time of the gate is in optical detector electronics ticks.
Definition at line 49 of file BeamGateMaker.h.
Member Typedef Documentation
optical_tick
using icarus::trigger::BeamGateMaker::optical_tick = detinfo::timescales::optical_tick
Definition at line 61 of file BeamGateMaker.h.
optical_time
using icarus::trigger::BeamGateMaker::optical_time = detinfo::timescales::optical_time
Definition at line 60 of file BeamGateMaker.h.
optical_time_ticks
using icarus::trigger::BeamGateMaker::optical_time_ticks = detinfo::timescales::optical_time_ticks
Definition at line 62 of file BeamGateMaker.h.
time_interval
using icarus::trigger::BeamGateMaker::time_interval = detinfo::timescales::time_interval
Definition at line 59 of file BeamGateMaker.h.
Constructor & Destructor Documentation
BeamGateMaker() [1/2]
icarus::trigger::BeamGateMaker::BeamGateMaker (detinfo::DetectorTimings const & detTimings) inline
Constructor: uses a copy of the specified detector timing provider.
Definition at line 66 of file BeamGateMaker.h.
BeamGateMaker() [2/2]
icarus::trigger::BeamGateMaker::BeamGateMaker (detinfo::DetectorClocksData const & clockData) inline
Constructor: uses the specified detector clocks service.
Definition at line 71 of file BeamGateMaker.h.
Member Function Documentation
endTick()
optical_tick icarus::trigger::BeamGateMaker::endTick (time_interval const duration, time_interval const delay = DefaultDelay) const inline
Time of beam gate closure, in optical ticks.
Definition at line 95 of file BeamGateMaker.h.
References endTime(), and fDetTimings.
endTime()
optical_time icarus::trigger::BeamGateMaker::endTime (time_interval const duration, time_interval const delay = DefaultDelay) const inline
Time of beam gate closure, in optical time scale.
Definition at line 84 of file BeamGateMaker.h.
References startTime().
Referenced by endTick().
make()
template<typename Gate = icarus::trigger::OpticalTriggerGate> Gate icarus::trigger::BeamGateMaker::make (time_interval length, time_interval delay = DefaultDelay) const inline
Returns a gate object of the specified duration.
Template Parameters
Gate type of gate object to be returned (default: icarus::trigger::OpticalTriggerGate)
Parameters
length duration of the gate to be open
delay time from beam gate time when this gate opens (default: 0)
Returns
a Gate object representing a gate opened at beam gate time
The returned object represents a gate opening at beam gate time (with an optional delay) for the specified duration. The time of the gate is in optical ticks.
Definition at line 120 of file BeamGateMaker.h.
References fDetTimings, icarus::trigger::OpticalTriggerGate::gateLevels(), icarus::trigger::TriggerGateData< Tick, TickInterval >::openFor(), and startTick().
Referenced by icarus::trigger::MakeTriggerSimulationTree::extractTriggerInfo().
operator()()
template<typename Gate = icarus::trigger::OpticalTriggerGate> Gate icarus::trigger::BeamGateMaker::operator() (time_interval length, time_interval delay = DefaultDelay) const inline
Definition at line 130 of file BeamGateMaker.h.
startTick()
optical_tick icarus::trigger::BeamGateMaker::startTick (time_interval const delay = DefaultDelay) const inline
Time of beam gate opening, in optical ticks.
Parameters
delay opening delay after the nominal beam gate time
Definition at line 91 of file BeamGateMaker.h.
References fDetTimings, and startTime().
Referenced by make().
startTime()
optical_time icarus::trigger::BeamGateMaker::startTime (time_interval const delay = DefaultDelay) const inline
Time of beam gate opening, in optical time scale.
Parameters
delay opening delay after the nominal beam gate time
Definition at line 80 of file BeamGateMaker.h.
References fDetTimings.
Referenced by endTime(), and startTick().
Member Data Documentation
DefaultDelay
util::quantities::microsecond icarus::trigger::BeamGateMaker::DefaultDelay { 0.0 } static constexpr private
Value used for default delay.
Definition at line 54 of file BeamGateMaker.h.
fDetTimings
detinfo::DetectorTimings const icarus::trigger::BeamGateMaker::fDetTimings private
Detector timing provider.
Definition at line 51 of file BeamGateMaker.h.
Referenced by endTick(), make(), startTick(), and startTime().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/BeamGateMaker.h