CAF format: icarus::trigger::TrackedTriggerGate< Gate, TrackedType > Class Template Reference
icarus::trigger::TrackedTriggerGate< Gate, TrackedType > Class Template Reference
A wrapper to trigger gate objects tracking the input of operations.
#include <TrackedTriggerGate.h>
Classes
class TrackingInfo
Tracked information. Interface is pretty minimal so far.
Public Types
using TriggerGate_t = Gate
Gate type being wrapped.
using Tracked_t = TrackedType
Type for tracking.
Public Member Functions
TrackedTriggerGate ()=default
Default constructor: default-constructed gate, no tracking.
TrackedTriggerGate (TriggerGate_t gate)
Constructor: copies the data of the specified gate (no tracking added).
TrackingInfo const & tracking () const
Returns the tracking information.
TrackingInfo & tracking ()
TriggerGate_t const & gate () const &
Returns the enclosed gate.
TriggerGate_t & gate () &
TriggerGate_t && gate () &&
decltype(auto) channels () const
Returns the list of channels of the enclosed gate.
Private Attributes
TriggerGate_t fGate
Local copy of the gate information.
TrackingInfo fTracking
Tracking information.
Detailed Description
template<typename Gate, typename TrackedType>
class icarus::trigger::TrackedTriggerGate< Gate, TrackedType >
A wrapper to trigger gate objects tracking the input of operations.
Template Parameters
Gate type of trigger gate object being wrapped
TrackedType type of the objects being tracked
This object includes its own Gate object, plus tracking().
Functions taking as argument a generic sequence of Gate objects can be passed the result of icarus::trigger::gatesIn() (sold separately), which behaves like a sequence of Gate.
Supporting functions can add specific tracking operations when operating of a TrackedTriggerGate object. The trait icarus::trigger::isTrackedTriggerGate_v will return whether that is the case.
Tracking is performed by accessing tracking() and add()'ing objects to be tracked. Tracking is currently just a collection of objects of a specific type (TrackedType). That type is expected to support strict comparison. A copy of each tracking object is used and owned: if the object is complex and externally owned, a pointer or handle should be stored as tracking object instead of the object itself. If an object is already present, it is not added again into the tracking.
The Gate type is expected to be a trigger gate type, like icarus::trigger::ReadoutTriggerGate.
Definition at line 100 of file TrackedTriggerGate.h.
Member Typedef Documentation
Tracked_t
template<typename Gate , typename TrackedType > using icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::Tracked_t = TrackedType
Type for tracking.
Definition at line 105 of file TrackedTriggerGate.h.
TriggerGate_t
template<typename Gate , typename TrackedType > using icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::TriggerGate_t = Gate
Gate type being wrapped.
Definition at line 104 of file TrackedTriggerGate.h.
Constructor & Destructor Documentation
TrackedTriggerGate() [1/2]
template<typename Gate , typename TrackedType > icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::TrackedTriggerGate () default
Default constructor: default-constructed gate, no tracking.
TrackedTriggerGate() [2/2]
template<typename Gate , typename TrackedType > icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::TrackedTriggerGate (TriggerGate_t gate) inline
Constructor: copies the data of the specified gate (no tracking added).
Definition at line 135 of file TrackedTriggerGate.h.
Member Function Documentation
channels()
template<typename Gate , typename TrackedType > decltype(auto) icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::channels () const inline
Returns the list of channels of the enclosed gate.
Definition at line 158 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate().
Referenced by icarus::trigger::SlidingWindowCombinerAlg::checkInput(), and icarus::trigger::WindowTopologyVerification::verifyGate().
gate() [1/3]
template<typename Gate , typename TrackedType > TriggerGate_t & icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate () & inline
Definition at line 151 of file TrackedTriggerGate.h.
gate() [2/3]
template<typename Gate , typename TrackedType > TriggerGate_t && icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate () && inline
Definition at line 152 of file TrackedTriggerGate.h.
gate() [3/3]
template<typename Gate , typename TrackedType > TriggerGate_t const & icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate () const & inline
Returns the enclosed gate.
Definition at line 150 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::fGate.
Referenced by icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::channels(), icarus::trigger::LVDSgates::discardChannels(), icarus::trigger::gateDataIn(), icarus::trigger::gateIn(), icarus::trigger::gatesIn(), icarus::trigger::SlidingWindowCombinerAlg::mergeGateInto(), and icarus::trigger::LVDSgates::selectChannel().
tracking() [1/2]
template<typename Gate , typename TrackedType > TrackingInfo & icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::tracking () inline
Definition at line 142 of file TrackedTriggerGate.h.
tracking() [2/2]
template<typename Gate , typename TrackedType > TrackingInfo const & icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::tracking () const inline
Returns the tracking information.
Definition at line 141 of file TrackedTriggerGate.h.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::fTracking.
Referenced by icarus::trigger::LVDSgates::discardChannels().
Member Data Documentation
fGate
template<typename Gate , typename TrackedType > TriggerGate_t icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::fGate private
Local copy of the gate information.
Definition at line 162 of file TrackedTriggerGate.h.
Referenced by icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate().
fTracking
template<typename Gate , typename TrackedType > TrackingInfo icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::fTracking private
Tracking information.
Definition at line 163 of file TrackedTriggerGate.h.
Referenced by icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::tracking().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Utilities/TrackedTriggerGate.h