CAF format: icarus::opdet::AsymGaussPulseFunction< T > Class Template Reference
icarus::opdet::AsymGaussPulseFunction< T > Class Template Reference
Describes the waveform from a single photoelectron.
#include <AsymGaussPulseFunction.h>
Public Types
using ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
using Time = typename Base_t::Time
Type of time being used.
Public Types inherited from icarus::opdet::PhotoelectronPulseFunction< T >
using ADCcount = util::quantities::counts_f
Type for ADC counts (floating point).
using Time = T
Type of time being used.
Public Member Functions
AsymGaussPulseFunction (ADCcount amplitude, Time peakTime, Time sigmaLeft, Time sigmaRight)
Constructor: assigns the parameters of the shape.
Parameter accessors.
Time leftSigma () const
Time rightSigma () const
ADCcount amplitude () const
Public Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
ADCcount evaluateAt (Time time) const
Evaluates the pulse at the given time.
ADCcount operator() (Time time) const
Alias of evaluateAt().
Time peakTime () const
Returns the time at which the first peak is found.
ADCcount peakAmplitude () const
Returns the amplitude of the first peak in ADC counts.
ADCcount baseline () const
Returns the baseline of the pulse in ADC counts.
int polarity () const
Returns the polarity of the pulse (+1: positive, or -1: negative).
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints on stream the parameters of this shape.
void dump (std::ostream &&out, std::string const &indent="") const
std::string toString (std::string const &indent, std::string const &firstIndent) const
Returns the parameters of this shape as a descriptive string.
std::string toString (std::string const &indent="") const
Static Public Member Functions
static ADCcount Gaussian (Time x, Time mean, Time sigma, ADCcount amplitude)
Returns the value of normal distribution at specified point.
Private Types
using Base_t = icarus::opdet::PhotoelectronPulseFunction<T>
Private Member Functions
Time myPeakTime () const
Returns the time of the center of the Gaussian.
ADCcount myAmplitude () const
Returns the amplitude of the pulse from the baseline, including its sign.
virtual ADCcount doEvaluateAt (Time time) const override
Evaluates the pulse at the given time.
virtual Time doPeakTime () const override
Returns the time at which the first peak is found.
virtual ADCcount doPeakAmplitude () const override
Returns the amplitude of the first peak in ADC counts.
virtual void doDump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const override
Prints on stream the parameters of this shape.
Static Private Member Functions
template<typename V >
static V sqr (V value)
template<typename V >
static V round (V value)
Private Attributes
ADCcount fAmplitude
Amplitude at peak (transition).
Time fTransitTime
Time of transition between the two forms of shape.
Time fSigmaL
RMS parameter of the shape before transition.
Time fSigmaR
RMS parameter of the shape after transition.
Additional Inherited Members
Protected Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
virtual ADCcount doBaseline () const
Returns the baseline of the pulse.
virtual int doPolarity () const
Returns the polarity of the pulse (+1 or -1).
Detailed Description
template<typename T>
class icarus::opdet::AsymGaussPulseFunction< T >
Describes the waveform from a single photoelectron.
Template Parameters
Time type of time unit to be used
This functor (class behaving like a function) describes the shape of the response to a single photoelectron as an asymmetric Gaussian shape.
Definition at line 41 of file AsymGaussPulseFunction.h.
Member Typedef Documentation
ADCcount
template<typename T > using icarus::opdet::AsymGaussPulseFunction< T >::ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
Definition at line 48 of file AsymGaussPulseFunction.h.
Base_t
template<typename T > using icarus::opdet::AsymGaussPulseFunction< T >::Base_t = icarus::opdet::PhotoelectronPulseFunction<T> private
Definition at line 44 of file AsymGaussPulseFunction.h.
Time
template<typename T > using icarus::opdet::AsymGaussPulseFunction< T >::Time = typename Base_t::Time
Type of time being used.
Definition at line 50 of file AsymGaussPulseFunction.h.
Constructor & Destructor Documentation
AsymGaussPulseFunction()
template<typename T > icarus::opdet::AsymGaussPulseFunction< T >::AsymGaussPulseFunction (ADCcount amplitude, Time peakTime, Time sigmaLeft, Time sigmaRight) inline
Constructor: assigns the parameters of the shape.
Parameters
amplitude the maximum amplitudes of the shape (at transition)
peakTime the time of the maximum amplitude of the shape
sigmaLeft the standard deviation of the shape before transition
sigmaRight the standard deviation of the shape after transition
The time parameters (peakTime, sigmaLeft and sigmaRight) must be measured in same unit. The peakTime defines the position of the shape with respect to time 0.
Definition at line 64 of file AsymGaussPulseFunction.h.
Member Function Documentation
amplitude()
template<typename T > ADCcount icarus::opdet::AsymGaussPulseFunction< T >::amplitude () const inline
Definition at line 82 of file AsymGaussPulseFunction.h.
doDump()
template<typename T > void icarus::opdet::AsymGaussPulseFunction< T >::doDump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const override private virtual
Prints on stream the parameters of this shape.
Parameters
out the stream to write into
indent indentation string, prepended to all lines except first
indentFirst indentation string prepended to the first line
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 164 of file AsymGaussPulseFunction.h.
doEvaluateAt()
template<typename T > auto icarus::opdet::AsymGaussPulseFunction< T >::doEvaluateAt (Time time) const override private virtual
Evaluates the pulse at the given time.
Parameters
time time to evaluate the shape at
The scale of the time is defined by the transition time passed at construction.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 150 of file AsymGaussPulseFunction.h.
doPeakAmplitude()
template<typename T > virtual ADCcount icarus::opdet::AsymGaussPulseFunction< T >::doPeakAmplitude () const inline override private virtual
Returns the amplitude of the first peak in ADC counts.
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 117 of file AsymGaussPulseFunction.h.
References icarus::opdet::AsymGaussPulseFunction< T >::myAmplitude().
doPeakTime()
template<typename T > virtual Time icarus::opdet::AsymGaussPulseFunction< T >::doPeakTime () const inline override private virtual
Returns the time at which the first peak is found.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 114 of file AsymGaussPulseFunction.h.
References icarus::opdet::AsymGaussPulseFunction< T >::myPeakTime().
Gaussian()
template<typename T > static ADCcount icarus::opdet::AsymGaussPulseFunction< T >::Gaussian (Time x, Time mean, Time sigma, ADCcount amplitude) inline static
Returns the value of normal distribution at specified point.
Definition at line 87 of file AsymGaussPulseFunction.h.
leftSigma()
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::leftSigma () const inline
Definition at line 80 of file AsymGaussPulseFunction.h.
myAmplitude()
template<typename T > ADCcount icarus::opdet::AsymGaussPulseFunction< T >::myAmplitude () const inline private
Returns the amplitude of the pulse from the baseline, including its sign.
Definition at line 100 of file AsymGaussPulseFunction.h.
References icarus::opdet::AsymGaussPulseFunction< T >::fAmplitude.
Referenced by icarus::opdet::AsymGaussPulseFunction< T >::doPeakAmplitude().
myPeakTime()
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::myPeakTime () const inline private
Returns the time of the center of the Gaussian.
Definition at line 97 of file AsymGaussPulseFunction.h.
References icarus::opdet::AsymGaussPulseFunction< T >::fTransitTime.
Referenced by icarus::opdet::AsymGaussPulseFunction< T >::doPeakTime().
rightSigma()
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::rightSigma () const inline
Definition at line 81 of file AsymGaussPulseFunction.h.
round()
template<typename T > template<typename V > static V icarus::opdet::AsymGaussPulseFunction< T >::round (V value) inline static private
Definition at line 136 of file AsymGaussPulseFunction.h.
sqr()
template<typename T > template<typename V > static V icarus::opdet::AsymGaussPulseFunction< T >::sqr (V value) inline static private
Definition at line 133 of file AsymGaussPulseFunction.h.
Member Data Documentation
fAmplitude
template<typename T > ADCcount icarus::opdet::AsymGaussPulseFunction< T >::fAmplitude private
Amplitude at peak (transition).
Definition at line 91 of file AsymGaussPulseFunction.h.
Referenced by icarus::opdet::AsymGaussPulseFunction< T >::myAmplitude().
fSigmaL
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::fSigmaL private
RMS parameter of the shape before transition.
Definition at line 93 of file AsymGaussPulseFunction.h.
fSigmaR
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::fSigmaR private
RMS parameter of the shape after transition.
Definition at line 94 of file AsymGaussPulseFunction.h.
fTransitTime
template<typename T > Time icarus::opdet::AsymGaussPulseFunction< T >::fTransitTime private
Time of transition between the two forms of shape.
Definition at line 92 of file AsymGaussPulseFunction.h.
Referenced by icarus::opdet::AsymGaussPulseFunction< T >::myPeakTime().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Algorithms/AsymGaussPulseFunction.h