CAF format: icarusDB::ICARUSChannelMapPostGres Class Reference
icarusDB::ICARUSChannelMapPostGres Class Reference
LArSoft service for ICARUS channel mapping (PostgreSQL DB backend).
Public Types
using provider_type = icarusDB::ICARUSChannelMapPostGresProvider
using Parameters = art::ServiceTable<provider_type::Config>
Public Types inherited from icarusDB::IICARUSChannelMap
using provider_type = icarusDB::IICARUSChannelMapProvider
Type of the service provider.
Public Types inherited from util::CacheCounter
using CacheID_t = unsigned long
Type of cache identifier.
using CacheTag_t = std::string
Type of cache name.
Public Types inherited from icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >
using ChannelMappingAlg_t
The helper used to extract data from the database.
using Parameters
Public Member Functions
ICARUSChannelMapPostGres (Parameters const &params, art::ActivityRegistry &reg)
Constructor: configures the provider and hooks to the framework.
provider_type const * provider () const
Returns the service provider (for use with lar::providerFrom()).
Public Member Functions inherited from icarusDB::IICARUSChannelMap
provider_type const * provider () const
Returns the service provider.
Public Member Functions inherited from icarusDB::IICARUSChannelMapProvider
Public Member Functions inherited from util::CacheCounter
CacheCounter ()
Constructor: prepares the ID of the default cache tag.
CacheCounter (std::initializer_list< CacheTag_t > tags)
Constructor: prepares the ID of the caches with the specified tags.
void addCacheTags (std::initializer_list< CacheTag_t > tags)
Adds tags. The ID of existing ones are not changed.
CacheID_t cacheID (CacheTag_t const &tag) const
Returns the current ID of the cache with the specified tag.
bool hasTag (CacheTag_t const &tag) const
Returns whether the specified tag is tracked.
bool wasCacheUpdatedSince (CacheTag_t const &tag, CacheID_t sinceID) const
Returns whether the cache tag was updated since it has sinceID ID.
bool wasCacheUpdatedSince (CacheID_t sinceID) const
Returns whether the default cache was updated since it has sinceID ID.
Public Member Functions inherited from icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >
ICARUSChannelMapProviderBase (Config const &config)
Constructor: configures the service provider via FHiCL configuration.
ICARUSChannelMapProviderBase (Parameters const &params)
Constructor: configures the service provider via FHiCL configuration.
virtual TPCReadoutBoardToChannelMap const & getReadoutBoardToChannelMap () const override
Returns the full TPC channel mapping.
virtual bool forRun (int run) override
Loads the mapping for run, returns whether a new mapping was loaded.
virtual bool forPeriod (icarusDB::RunPeriod period) override
Loads the mapping for period, returns whether a new mapping was loaded.
virtual bool hasFragmentID (unsigned int ID) const override
Returns whether the specified ID is a known TPC fragment ID.
virtual unsigned int nTPCfragmentIDs () const override
Returns the number of TPC fragment IDs known to the service.
virtual std::string const & getCrateName (unsigned int fragmentID) const override
Returns the name of the crate served by the specified fragmentID.
virtual ReadoutIDVec const & getReadoutBoardVec (unsigned int fragmentID) const override
Returns the list of board IDs included in the specified fragmentID.
virtual bool hasBoardID (unsigned int ID) const override
Returns whether there is a board with the specified ID.
virtual unsigned int nTPCboardIDs () const override
Returns the number of TPC board IDs known to the service.
virtual unsigned int getBoardSlot (unsigned int boardID) const override
Returns the number of slot the boardID is on.
virtual ChannelPlanePairVec const & getChannelPlanePair (unsigned int boardID) const override
virtual bool hasPMTDigitizerID (unsigned int ID) const override
Returns whether the specified fragment ID is known to the mapping.
virtual unsigned int nPMTfragmentIDs () const override
Returns the number of PMT fragment IDs known to the mapping.
virtual PMTdigitizerInfoVec const & getPMTchannelInfo (unsigned int ID) const override
Returns records on all the PMT channels covered by the fragment ID.
virtual unsigned int getSimMacAddress (unsigned int hwmacaddress) const override
virtual unsigned int gettopSimMacAddress (unsigned int) const override
virtual std::pair< double, double > getSideCRTCalibrationMap (int mac5, int chan) const override
Returns the Gain and Pedestal for Side CRT.
Private Member Functions
void preBeginRun (art::Run const &run)
Prepares the mapping for the specified run.
Additional Inherited Members
Static Public Member Functions inherited from icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >
static constexpr unsigned int PMTfragmentIDtoDBkey (unsigned int fragmentID)
Returns the channel mapping database key for the specified PMT fragment ID.
static constexpr unsigned int DBkeyToPMTfragmentID (unsigned int DBkey)
Static Public Attributes inherited from util::CacheCounter
static constexpr CacheID_t NoCache = 0
ID specifying that cache is not present yet.
Protected Member Functions inherited from util::CacheCounter
CacheID_t updateCacheID (CacheTag_t const &cacheTag="") const
Protected Member Functions inherited from icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >
void readFromDatabase ()
Has the channel mapping tool fill the mapping caches.
icarusDB::PMTdigitizerInfoVec const * findPMTfragmentEntry (unsigned int fragmentID) const
cet::exception myException () const
Returns an exception signed by this object.
Protected Attributes inherited from util::CacheCounter
std::map< CacheTag_t, std::atomic< CacheID_t > > fCacheID
ID of the current caches.
Protected Attributes inherited from icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >
bool const fDiagnosticOutput
std::string const fLogCategory
ChannelMappingAlg_t fChannelMappingAlg
The helper extracting information from the database.
icarusDB::TPCFragmentIDToReadoutIDMap fTPCFragmentToReadoutMap
icarusDB::TPCReadoutBoardToChannelMap fTPCReadoutBoardToChannelMap
icarusDB::PMTFragmentToDigitizerChannelMap fPMTFragmentToDigitizerMap
icarusDB::CRTChannelIDToHWtoSimMacAddressPairMap fCRTChannelIDToHWtoSimMacAddressPairMap
icarusDB::TopCRTHWtoSimMacAddressPairMap fTopCRTHWtoSimMacAddressPairMap
icarusDB::SideCRTChannelToCalibrationMap fSideCRTChannelToCalibrationMap
Detailed Description
LArSoft service for ICARUS channel mapping (PostgreSQL DB backend).
This service provides access to ICARUS channel mapping database, using the PostgreSQL database.
This service implements the generic channel mapping access service provider interface icarusDB::IICARUSChannelMapProvider. To use the channel mapping, include in your code the header of the service interface icarusDB::IICARUSChannelMap, and access the service provider via:
icarusDB::IICARUSChannelMapProvider const& channelMapping
  = *lar::providerFrom<icarusDB::IICARUSChannelMap>();
or similar (lar::providerFrom() is in larcore/CoreUtils/ServiceUtils.h) or directly the service via
icarusDB::IICARUSChannelMapProvider const& channelMapping
  = *art::ServiceHandle<icarusDB::IICARUSChannelMap>();
For details on the interface, see icarusDB::IICARUSChannelMapProvider. For details on the implementation, see icarusDB::ICARUSChannelMapPostGresProvider.
Note
For production and processes that need robustness, using the SQLite database and backend (icarusDB::ICARUSChannelMapSQLite) is suggested instead. That database is local to the process and not subject to network interruptions.
Definition at line 54 of file ICARUSChannelMapPostGres_service.cc.
Member Typedef Documentation
Parameters
using icarusDB::ICARUSChannelMapPostGres::Parameters = art::ServiceTable<provider_type::Config>
Definition at line 65 of file ICARUSChannelMapPostGres_service.cc.
provider_type
using icarusDB::ICARUSChannelMapPostGres::provider_type = icarusDB::ICARUSChannelMapPostGresProvider
Definition at line 63 of file ICARUSChannelMapPostGres_service.cc.
Constructor & Destructor Documentation
ICARUSChannelMapPostGres()
icarusDB::ICARUSChannelMapPostGres::ICARUSChannelMapPostGres (Parameters const & params, art::ActivityRegistry & reg)
Constructor: configures the provider and hooks to the framework.
Definition at line 79 of file ICARUSChannelMapPostGres_service.cc.
References icarusDB::IICARUSChannelMapProvider::forPeriod(), and preBeginRun().
Member Function Documentation
preBeginRun()
void icarusDB::ICARUSChannelMapPostGres::preBeginRun (art::Run const & run) private
Prepares the mapping for the specified run.
Definition at line 89 of file ICARUSChannelMapPostGres_service.cc.
Referenced by ICARUSChannelMapPostGres().
provider()
provider_type const * icarusDB::ICARUSChannelMapPostGres::provider () const inline
Returns the service provider (for use with lar::providerFrom()).
Definition at line 71 of file ICARUSChannelMapPostGres_service.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/ChannelMapping/ICARUSChannelMapPostGres_service.cc