CAF format: icarusDB::ChannelMapPostGres Class Reference
icarusDB::ChannelMapPostGres Class Reference
Helper to extract mapping information from ICARUS PostGres database.
#include <ChannelMapPostGres.h>
Classes
struct Config
Public Member Functions
ChannelMapPostGres (Config const &config)
Constructor: configuration via FHiCL.
virtual bool SelectPeriod (RunPeriod period) override
Prepares the object for queries pertaining the specified period.
virtual int BuildTPCFragmentIDToReadoutIDMap (TPCFragmentIDToReadoutIDMap &) const override
Define the returned data structures for a mapping between TPC Fragment IDs and the related crate and readout information. Then define the function interface to fill these data structures.
virtual int BuildTPCReadoutBoardToChannelMap (TPCReadoutBoardToChannelMap &) const override
Define the returned data structures for a mapping between TPC readout boards and the channel information Then define the function interface to fill these data structures.
virtual int BuildPMTFragmentToDigitizerChannelMap (PMTFragmentToDigitizerChannelMap &) const override
Define the returned data structures for a mapping between PMT Fragment IDs and the related crate and readout information. Then define the function interface to fill these data structures.
virtual int BuildCRTChannelIDToHWtoSimMacAddressPairMap (CRTChannelIDToHWtoSimMacAddressPairMap &) const override
Define the returned data structures for a mapping between CRT hardware mac_address to the simulated mac_address. Then define the function interface to fill these data structures.
virtual int BuildTopCRTHWtoSimMacAddressPairMap (TopCRTHWtoSimMacAddressPairMap &) const override
Fill mapping between top CRT channel ID and the simulated mac_address.
virtual int BuildSideCRTCalibrationMap (SideCRTChannelToCalibrationMap &) const override
Define the returned data structures for a mapping between Side CRT Channels and their calibration values. Then define the function interface to fill these data structures.
Public Member Functions inherited from icarusDB::IChannelMapping
virtual ~IChannelMapping () noexcept=default
Virtual Destructor.
Private Member Functions
details::WDADataset GetDataset (std::string const &name, std::string url, std::string const &dataType) const
Reads a full table from the specified database table.
details::WDADataset GetCRTCaldata (std::string const &name, std::string url) const
Reads a full table from the specified database table.
bool printDatasetError (details::WDADataset const &dataset) const
Static Private Member Functions
template<std::size_t BufferSize = 32>
static util::Expected< std::string > getStringFromTuple (details::WDATuple const &tuple, std::size_t column)
static cet::exception myException ()
Returns an exception object pre-approved with our signature.
Private Attributes
std::string const fDBURL
Complete URL for hardware database access.
std::string const fCRTcalibrationDBURL
Complete URL for CRT calibration database access.
unsigned int const fDatabaseAccessTimeout
In seconds.
std::string fCurrentPMTTimestamp = ""
The PMT timestamp being served. Chosen by SelectPeriod().
Static Private Attributes
static std::array< std::string, RunPeriods::NPeriods > const PMTTimestampSet
The list of available PMT timestamps.
Additional Inherited Members
Static Public Member Functions inherited from icarusDB::IChannelMapping
template<typename String >
static void makeLowerCase (String &s)
Turns and returns a string into lowercase.
static unsigned int TPCplaneIdentifierToPlane (std::string planeStr)
Returns the plane identified by planeStr: 0 to 2; 3 if invalid.
template<std::size_t N = 2, typename Integer = int>
static std::array< Integer, N > splitIntegers (std::string const &s, std::string const &sep)
Static Public Attributes inherited from icarusDB::IChannelMapping
static constexpr unsigned int ChannelsPerTPCreadoutBoard = 64
Detailed Description
Helper to extract mapping information from ICARUS PostGres database.
This helper fills "standard" data structures from a PostGres database. These data structures are then managed by a ICARUS service provider (icarusDB::IICARUSChannelMap).
Definition at line 44 of file ChannelMapPostGres.h.
Class Documentation
icarusDB::ChannelMapPostGres::Config
struct icarusDB::ChannelMapPostGres::Config
Definition at line 49 of file ChannelMapPostGres.h.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< string > CRTcalibrationDatabaseURL
Atom< unsigned int > DatabaseAccessTimeout
Atom< string > DatabaseURL
Atom< string > LogCategory
Constructor & Destructor Documentation
ChannelMapPostGres()
icarusDB::ChannelMapPostGres::ChannelMapPostGres (Config const & config) explicit
Constructor: configuration via FHiCL.
Definition at line 99 of file ChannelMapPostGres.cxx.
Member Function Documentation
BuildCRTChannelIDToHWtoSimMacAddressPairMap()
int icarusDB::ChannelMapPostGres::BuildCRTChannelIDToHWtoSimMacAddressPairMap (CRTChannelIDToHWtoSimMacAddressPairMap & crtChannelIDToHWtoSimMacAddressPairMap) const override virtual
Define the returned data structures for a mapping between CRT hardware mac_address to the simulated mac_address. Then define the function interface to fill these data structures.
Implements icarusDB::IChannelMapping.
Definition at line 530 of file ChannelMapPostGres.cxx.
BuildPMTFragmentToDigitizerChannelMap()
int icarusDB::ChannelMapPostGres::BuildPMTFragmentToDigitizerChannelMap (PMTFragmentToDigitizerChannelMap & fragmentToDigitizerChannelMap) const override virtual
Define the returned data structures for a mapping between PMT Fragment IDs and the related crate and readout information. Then define the function interface to fill these data structures.
Implements icarusDB::IChannelMapping.
Definition at line 388 of file ChannelMapPostGres.cxx.
References icarusDB::PMTChannelInfo_t::adderBit, icarusDB::PMTChannelInfo_t::adderConnector, icarusDB::PMTChannelInfo_t::channelID, icarusDB::PMTChannelInfo_t::digitizerChannelNo, icarusDB::PMTChannelInfo_t::digitizerLabel, util::Expected< T, E >::error(), icarusDB::PMTChannelInfo_t::laserChannelNo, icarusDB::PMTChannelInfo_t::LVDSbit, icarusDB::PMTChannelInfo_t::LVDSconnector, and util::Expected< T, E >::value().
BuildSideCRTCalibrationMap()
int icarusDB::ChannelMapPostGres::BuildSideCRTCalibrationMap (SideCRTChannelToCalibrationMap & sideCRTChannelToCalibrationMap) const override virtual
Define the returned data structures for a mapping between Side CRT Channels and their calibration values. Then define the function interface to fill these data structures.
Implements icarusDB::IChannelMapping.
Definition at line 671 of file ChannelMapPostGres.cxx.
BuildTopCRTHWtoSimMacAddressPairMap()
int icarusDB::ChannelMapPostGres::BuildTopCRTHWtoSimMacAddressPairMap (TopCRTHWtoSimMacAddressPairMap &) const override virtual
Fill mapping between top CRT channel ID and the simulated mac_address.
Implements icarusDB::IChannelMapping.
Definition at line 601 of file ChannelMapPostGres.cxx.
BuildTPCFragmentIDToReadoutIDMap()
int icarusDB::ChannelMapPostGres::BuildTPCFragmentIDToReadoutIDMap (TPCFragmentIDToReadoutIDMap & fragmentBoardMap) const override virtual
Define the returned data structures for a mapping between TPC Fragment IDs and the related crate and readout information. Then define the function interface to fill these data structures.
Implements icarusDB::IChannelMapping.
Definition at line 175 of file ChannelMapPostGres.cxx.
References util::Expected< T, E >::error(), and util::Expected< T, E >::value().
BuildTPCReadoutBoardToChannelMap()
int icarusDB::ChannelMapPostGres::BuildTPCReadoutBoardToChannelMap (TPCReadoutBoardToChannelMap & rbChanMap) const override virtual
Define the returned data structures for a mapping between TPC readout boards and the channel information Then define the function interface to fill these data structures.
Implements icarusDB::IChannelMapping.
Definition at line 292 of file ChannelMapPostGres.cxx.
References util::Expected< T, E >::error(), and util::Expected< T, E >::value().
GetCRTCaldata()
icarusDB::details::WDADataset icarusDB::ChannelMapPostGres::GetCRTCaldata (std::string const & name, std::string url) const private
Reads a full table from the specified database table.
Parameters
name name of the database table to read data from
url URL of the database to be accessed requested
[out] dataSet where the fetch data will be saved
Returns
a "smart" pointer to the data
Exceptions
cet::exception (category: "ChannelMapPostGres") on DB access error
See also
GetDataset()
Function used specifically for accessing CRT calibration data.
Note
[Tyler Boone] Adding this so I can control how this workflow goes Fetches CRT calibration data from the database.
Definition at line 163 of file ChannelMapPostGres.cxx.
GetDataset()
icarusDB::details::WDADataset icarusDB::ChannelMapPostGres::GetDataset (std::string const & name, std::string url, std::string const & dataType) const private
Reads a full table from the specified database table.
Parameters
name name of the database table to read data from
url URL of the database to be accessed requested
dataType type of data being requested
[out] dataSet where the fetch data will be saved
Returns
a "smart" pointer to the data
Exceptions
cet::exception (category: "ChannelMapPostGres") on DB access error
Database access is performed via Fermilab's libwda.
Definition at line 133 of file ChannelMapPostGres.cxx.
getStringFromTuple()
template<std::size_t BufferSize> util::Expected< std::string > icarusDB::ChannelMapPostGres::getStringFromTuple (details::WDATuple const & tuple, std::size_t column) static private
Returns the string on the specified column of the tuple.
Returns
the requested string, or an error code from libwda on error
Definition at line 748 of file ChannelMapPostGres.cxx.
myException()
static cet::exception icarusDB::ChannelMapPostGres::myException () inline static private
Returns an exception object pre-approved with our signature.
Definition at line 206 of file ChannelMapPostGres.h.
printDatasetError()
bool icarusDB::ChannelMapPostGres::printDatasetError (details::WDADataset const & dataset) const private
Emits an error message if libwda dataset contains one.
Returns
whether the dataset was in an error state
Definition at line 734 of file ChannelMapPostGres.cxx.
SelectPeriod()
bool icarusDB::ChannelMapPostGres::SelectPeriod (RunPeriod period) override virtual
Prepares the object for queries pertaining the specified period.
Parameters
period the period to be prepared for
Returns
whether values cached from the previous period are invalidated
Periods are defined in icarusDB::RunPeriods class.
If the return value is true, caller should follow by rebuilding all the maps they need to use. If the return value is false, all maps built after the previous call to SelectPeriod() are still current for period: building new ones is not necessary, but it's not harmful either (at most, wasteful).
Implements icarusDB::IChannelMapping.
Definition at line 108 of file ChannelMapPostGres.cxx.
Member Data Documentation
fCRTcalibrationDBURL
std::string const icarusDB::ChannelMapPostGres::fCRTcalibrationDBURL private
Complete URL for CRT calibration database access.
Definition at line 143 of file ChannelMapPostGres.h.
fCurrentPMTTimestamp
std::string icarusDB::ChannelMapPostGres::fCurrentPMTTimestamp = "" private
The PMT timestamp being served. Chosen by SelectPeriod().
Definition at line 153 of file ChannelMapPostGres.h.
fDatabaseAccessTimeout
unsigned int const icarusDB::ChannelMapPostGres::fDatabaseAccessTimeout private
In seconds.
Definition at line 145 of file ChannelMapPostGres.h.
fDBURL
std::string const icarusDB::ChannelMapPostGres::fDBURL private
Complete URL for hardware database access.
Definition at line 140 of file ChannelMapPostGres.h.
PMTTimestampSet
std::array< std::string, icarusDB::RunPeriods::NPeriods > const icarusDB::ChannelMapPostGres::PMTTimestampSet static private
Initial value:
{
   "start"
  ,"23aug2023"
  ,"29aug2023"
}
The list of available PMT timestamps.
Definition at line 91 of file ChannelMapPostGres.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/Decode/ChannelMapping/ChannelMapPostGres.h
icaruscode/icaruscode/Decode/ChannelMapping/ChannelMapPostGres.cxx