CAF format: util::ArtHandleTrackerManager< Event > Class Template Reference
util::ArtHandleTrackerManager< Event > Class Template Reference
Manages handle trackers for an easy call of removeCachedProduct().
#include <ArtHandleTrackerManager.h>
Classes
struct Config_t
Configuration record.
Public Types
using Event_t = Event
Type of data viewer object to operate with.
Public Member Functions
ArtHandleTrackerManager (Config_t config={})
Constructs a handle manager.
ArtHandleTrackerManager (Event_t const &event, Config_t config={})
Constructs a handle manager covering event.
template<typename Handle >
auto registerHandle (Handle &&handle) -> decltype(auto)
template<typename Handle >
Handle const * findHandle (Handle const &like) const
Queries
unsigned int nTrackedHandles () const
Returns the number of handles currently tracked.
bool hasEvent () const
Returns whether the object is associated to an event.
Registration of data products
template<typename T , typename... Args>
art::Handle< T > getHandle (Args &&... args)
Retrieves an handle from the event, and registers it.
template<typename T , typename... Args>
art::ValidHandle< T > getValidHandle (Args &&... args)
Retrieves a valid handle from the event, and registers it.
template<typename Handle >
decltype(auto) registerHandle (Handle &&handle)
Registers an existing handle.
Operations
void useEvent (Event_t const &event)
Changes the event being served.
unsigned int removeCachedProducts ()
Clears the cached data products for all tracked handles.
void forgetAllHandles ()
Stops tracking any handle, without removing their cache first.
unsigned int doneWithEvent (bool removeCache=true, art::Event const *event=nullptr)
Completes the work on the associated event.
Private Types
using TrackerPtr = std::unique_ptr<util::ArtHandleTrackerInterface<Event_t>>
Type of pointer to any handle tracker.
Private Member Functions
template<typename Handle >
Handle const * findHandle (Handle const &like) const
Returns the pointer to an handle equivalent to like.
void canOperate (const char *where) const
Static Private Member Functions
template<typename Handle >
static bool handleSameProduct (TrackerPtr tracker, Handle const &handle)
Returns whether tracker tracks the same product that handle handles.
Private Attributes
Event_t const * fEvent = nullptr
Event being manager. Must be present!
Config_t const fConfig
Configuration.
std::vector< TrackerPtr > fTrackers
List of managed handle trackers.
Detailed Description
template<typename Event>
class util::ArtHandleTrackerManager< Event >
Manages handle trackers for an easy call of removeCachedProduct().
Template Parameters
Event the type of data product source (the "principal") to serve
This handle manager is designed to simplify the usage of art::Event::removeCachedProduct() on multiple data products.
The envisioned usage model in a single-thread module is the following:
The manager is a data member of the module (in alternative, it should be passed down to the places where data products are read, and at a minimum it needs to register all the handles it is supposed to "manage").
The manager can ask the event to read a data product anew, and get an handle for it. It will register the handle, and return it.
The manager can also register an existing handle.
The manager can deliver a stored handle (but that's a slow process in the current implementation and it requires the input tag to resolve ambiguities).
Upon request, all handles are asked to remove their cached products. This request presumably happens at the end of the event-processing function (produce(), filter(), analyze()). Note that after an handle has its cached data removed, it's clear()'ed.
An handle manager can serve only one art event at a time. All handles come from that event (or are assumed to).
Example:
class MyModule: public art::EDAnalyzer {
  util::ArtHandleTrackerManager<art::Event> fDataCacheRemover;
  art::InputTag const fTag;
  // ...
  void analyze(art::Event const & event) override
    {
      fDataCacheRemover.useEvent(event);
      auto const& handle = fDataCacheRemover.getHandle<MyDataProduct>(fTag);
      auto results = processData(*handle); // ... or whatever
      fDataCacheRemover.removeCachedProducts(); // free caches after use
      results.Write(); // ... or another portion of whatever
    }
};
Or one can create the handle as preferred, and then register it:
class MyModule: public art::EDAnalyzer {
  util::ArtHandleTrackerManager<art::Event> fDataCacheRemover;
  art::InputTag const fTag;
  // ...
  void analyze(art::Event const & event) override
    {
      fDataCacheRemover.useEvent(event);
      auto const& handle = event.getValidHandle<MyDataProduct>(fTag);
      fDataCacheRemover.registerHandle(handle);
      auto results = processData(*handle); // ... or whatever
      fDataCacheRemover.removeCachedProducts(); // free caches after use
      results.Write(); // ... or another portion of whatever
    }
};
Technical notes
Support for different types of handles
Currently, both art::Handle and art::ValidHandle (and nothing else) can be created by ArtHandleTrackerManager. The code can be extended to support any object that can be passed to art::Event::removeCachedProduct() (e.g. art::ProductID, if it will ever happen).
The current implementation is expected to be able to recognize handles pointing to the same data product even if they are of different type (e.g. art::Handle<T> and art::ValidHandle<T>). The manager stores a copy of the first type of handle registered for a given data product; then, if another handle of any type to the same data product is requested or registered, registerHandle() will return the same handle in argument, and the getHandle() family of functions will get and return a new handle. In both cases, no new registration will happen.
Multithreading
The current implementation is inherently not safe for art multithreading. While the inner data structure don't need global state, and the interface can easily be extended to allow for no global state as well, the operations are still performed on all the registered handles at once (meaning, when one thread asks for removeCachedProduct() or forgetAllHandles(), data from all events is affected). This can be overcome by changing the internal storage (to be reentrant and possibly by event) and a bit of the interface.
The object as it is now can be implemented on top of such object, preserving the current event information and delivering it to the new manager under the hood, with minimal overhead.
If such feature is needed, ask the author (and be prepared to test it).
Definition at line 159 of file ArtHandleTrackerManager.h.
Class Documentation
util::ArtHandleTrackerManager::Config_t
struct util::ArtHandleTrackerManager::Config_t
template<typename Event>
struct util::ArtHandleTrackerManager< Event >::Config_t
Configuration record.
Definition at line 166 of file ArtHandleTrackerManager.h.
Class Members
string logCategory = "ArtHandleTrackerManager" Name of the output category for messages.
Member Typedef Documentation
Event_t
template<typename Event > using util::ArtHandleTrackerManager< Event >::Event_t = Event
Type of data viewer object to operate with.
Definition at line 163 of file ArtHandleTrackerManager.h.
TrackerPtr
template<typename Event > using util::ArtHandleTrackerManager< Event >::TrackerPtr = std::unique_ptr<util::ArtHandleTrackerInterface<Event_t>> private
Type of pointer to any handle tracker.
Definition at line 322 of file ArtHandleTrackerManager.h.
Constructor & Destructor Documentation
ArtHandleTrackerManager() [1/2]
template<typename Event > util::ArtHandleTrackerManager< Event >::ArtHandleTrackerManager (Config_t config = {})
Constructs a handle manager.
Parameters
config (optional) the configuration to be used
See also
useEvent()
An event must be later assigned to it (useEvent()) to make it functional.
Definition at line 782 of file ArtHandleTrackerManager.h.
ArtHandleTrackerManager() [2/2]
template<typename Event > util::ArtHandleTrackerManager< Event >::ArtHandleTrackerManager (Event_t const & event, Config_t config = {})
Constructs a handle manager covering event.
Parameters
event the first data viewer (event) object to operate on
Definition at line 790 of file ArtHandleTrackerManager.h.
Member Function Documentation
canOperate()
template<typename Event > void util::ArtHandleTrackerManager< Event >::canOperate (const char * where) const private
Checks that the object is in a state where it can perform operations.
Parameters
where identification of the calling function for error messages
Exceptions
art::Exception (code: art::errors::LogicError) on failure
Definition at line 994 of file ArtHandleTrackerManager.h.
doneWithEvent()
template<typename Event > unsigned int util::ArtHandleTrackerManager< Event >::doneWithEvent (bool removeCache = true, art::Event const * event = nullptr)
Completes the work on the associated event.
Parameters
removeCache (default: true) removes tracked data product caches
event if specified, only acts on cache from this event
Returns
the number of cleared data product caches
This is a shortcut for having optional release of cache in a single call, depending on the value of removeCache:
if true, removeCachedProducts() is called and its count is returned;
if false, forgetAllHandles() is called and 0 is returned.
In addition, the object is disassociated from the event, and a call to useEvent() will be needed before this object can be operative again.
If the event parameter is not null, a check is done that the event being currently used matches event, and if not no operation happens (0 is returned, but the object is not disassociated from its current event).
Definition at line 933 of file ArtHandleTrackerManager.h.
findHandle() [1/2]
template<typename Event > template<typename Handle > Handle const * util::ArtHandleTrackerManager< Event >::findHandle (Handle const & like) const private
Returns the pointer to an handle equivalent to like.
Template Parameters
Handle the type of the handle being queried
Returns
a pointer to the handle, or nullptr if not found
This is an half-assed method since it needs to know already the exact type of the handle being queried (it's not even agnostic to the difference between art::Handle and art::ValidHandle). For this reason, it's not really useful to the users, who would probably want to know if the data product is cached, via any mean.
Technical note
Delegating the matching to util::ArtHandleTrackerInterface is not possible (like is a template parameter and can't be passed via virtual interface) and even working around that and finding the match, the returned value needs to be of type Handle, which is not necessarily the type of handle stored in the tracker.
For the full functionality of knowing if a data product is tracked, a separate registry may be kept, still complicated by the fact that part of the registry entry is a C++ type (we may need to store a sanitized std::type_info for that).
findHandle() [2/2]
template<typename Event > template<typename Handle > Handle const * util::ArtHandleTrackerManager< Event >::findHandle (Handle const & like) const
Definition at line 951 of file ArtHandleTrackerManager.h.
forgetAllHandles()
template<typename Event > void util::ArtHandleTrackerManager< Event >::forgetAllHandles ()
Stops tracking any handle, without removing their cache first.
Definition at line 925 of file ArtHandleTrackerManager.h.
Referenced by util::LocalArtHandleTrackerManager< Event >::forgetAllHandles().
getHandle()
template<typename Event > template<typename T , typename... Args> art::Handle< T > util::ArtHandleTrackerManager< Event >::getHandle (Args &&... args)
Retrieves an handle from the event, and registers it.
Template Parameters
T type of data product to retrieve
Args types of the arguments needed by art::getHandle()
Parameters
args all the arguments that art::getHandle() requires
Returns
the handle just read and being managed
See also
getValidHandle(), registerHandle()
This function wraps art::Event::getHandle(), calling it to obtain the handle and then registering it (like with registerHandle()).
Definition at line 817 of file ArtHandleTrackerManager.h.
getValidHandle()
template<typename Event > template<typename T , typename... Args> art::ValidHandle< T > util::ArtHandleTrackerManager< Event >::getValidHandle (Args &&... args)
Retrieves a valid handle from the event, and registers it.
Template Parameters
T type of data product to retrieve
Args types of the arguments needed by art::getValidHandle()
Parameters
args all the arguments that art::getValidHandle() requires
Returns
the handle just read and being managed
See also
getHandle(), registerHandle()
This is the art::ValidHandle sibling of getHandle(). See that one for details.
Definition at line 829 of file ArtHandleTrackerManager.h.
handleSameProduct()
template<typename Event > template<typename Handle > bool util::ArtHandleTrackerManager< Event >::handleSameProduct (TrackerPtr tracker, Handle const & handle) static private
Returns whether tracker tracks the same product that handle handles.
Definition at line 977 of file ArtHandleTrackerManager.h.
hasEvent()
template<typename Event > bool util::ArtHandleTrackerManager< Event >::hasEvent () const
Returns whether the object is associated to an event.
Definition at line 903 of file ArtHandleTrackerManager.h.
Referenced by util::LocalArtHandleTrackerManager< Event >::doneWithEvent().
nTrackedHandles()
template<typename Event > unsigned int util::ArtHandleTrackerManager< Event >::nTrackedHandles () const
Returns the number of handles currently tracked.
Definition at line 897 of file ArtHandleTrackerManager.h.
Referenced by util::LocalArtHandleTrackerManager< Event >::nTrackedHandles().
registerHandle() [1/2]
template<typename Event > template<typename Handle > decltype(auto) util::ArtHandleTrackerManager< Event >::registerHandle (Handle && handle)
Registers an existing handle.
Template Parameters
Handle the type of handle to register
Parameters
handle the handle to be registered
Returns
handle (pass through)
This method registers a copy of handle into the manager.
Referenced by icarus::DaqDecoderICARUSPMT::readInputFragments().
registerHandle() [2/2]
template<typename Event > template<typename Handle > auto util::ArtHandleTrackerManager< Event >::registerHandle (Handle && handle) -> decltype(auto)
Definition at line 849 of file ArtHandleTrackerManager.h.
removeCachedProducts()
template<typename Event > unsigned int util::ArtHandleTrackerManager< Event >::removeCachedProducts ()
Clears the cached data products for all tracked handles.
Returns
the number of tracked handles which had their cache removed
This method calls Event_t::removeCachedProduct() for all tracked handles. This is the core functionality of the manager, which removes the cache of all tracked handles.
The art framework always makes the handles used to remove the cache invalid (Handle::clear()). After the removal, the object stops tracking the handles (like with a call to forgetAllHandles()).
Calling this method when there are no handles registered has no effect.
Definition at line 909 of file ArtHandleTrackerManager.h.
Referenced by icarus::DaqDecoderICARUSPMT::produce(), and util::LocalArtHandleTrackerManager< Event >::removeCachedProducts().
useEvent()
template<typename Event > void util::ArtHandleTrackerManager< Event >::useEvent (Event_t const & event)
Changes the event being served.
Parameters
event the new event being served
Exceptions
art::Exception (code: art::errors::LogicError) if there are still registered handles
The object starts tracking handles of a new event.
This method requires that any pending handle has been taken care of (even if the new event happens to be the same as the old one). Common options are removeCachedProductsAndForget() if cache removal is desired, or forgetAllHandles() if it's not.
Definition at line 798 of file ArtHandleTrackerManager.h.
Referenced by icarus::DaqDecoderICARUSPMT::produce().
Member Data Documentation
fConfig
template<typename Event > Config_t const util::ArtHandleTrackerManager< Event >::fConfig private
Configuration.
Definition at line 328 of file ArtHandleTrackerManager.h.
fEvent
template<typename Event > Event_t const* util::ArtHandleTrackerManager< Event >::fEvent = nullptr private
Event being manager. Must be present!
Definition at line 326 of file ArtHandleTrackerManager.h.
fTrackers
template<typename Event > std::vector<TrackerPtr> util::ArtHandleTrackerManager< Event >::fTrackers private
List of managed handle trackers.
Definition at line 331 of file ArtHandleTrackerManager.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h