CAF format: lar_cluster3d::SnippetHit3DBuilderICARUS Class Reference
lar_cluster3d::SnippetHit3DBuilderICARUS Class Reference
SnippetHit3DBuilderICARUS class definiton.
Public Member Functions
SnippetHit3DBuilderICARUS (fhicl::ParameterSet const &pset)
Constructor.
virtual void produces (art::ProducesCollector &) override
Each algorithm may have different objects it wants "produced" so use this to let the top level producer module "know" what it is outputting.
virtual void configure (const fhicl::ParameterSet &) override
virtual void Hit3DBuilder (art::Event &, reco::HitPairList &, RecobHitToPtrMap &) override
Given a set of recob hits, run DBscan to form 3D clusters.
virtual float getTimeToExecute (IHit3DBuilder::TimeValues index) const override
If monitoring, recover the time to execute a particular function.
Private Types
using HitMatchTriplet = std::tuple<const reco::ClusterHit2D*,const reco::ClusterHit2D*,const reco::ClusterHit3D>
This builds a list of candidate hit pairs from lists of hits on two planes.
using HitMatchTripletVec = std::vector<HitMatchTriplet>
using HitMatchTripletVecMap = std::map<geo::WireID,HitMatchTripletVec>
using ChannelStatusVec = std::vector<size_t>
define data structure for keeping track of channel status
using ChannelStatusByPlaneVec = std::vector<ChannelStatusVec>
using TickCorrectionArray = std::vector<std::vector<std::vector<float>>>
Data members to follow.
using PlaneToT0OffsetMap = std::map<geo::PlaneID,float>
Private Member Functions
void CollectArtHits (const art::Event &evt) const
Extract the ART hits and the ART hit-particle relationships.
void BuildHit3D (reco::HitPairList &hitPairList) const
Given the ClusterHit2D objects, build the HitPairMap.
void CreateNewRecobHitCollection (art::Event &, reco::HitPairList &, std::vector< recob::Hit > &, RecobHitToPtrMap &)
Create a new 2D hit collection from hits associated to 3D space points.
void makeWireAssns (const art::Event &, art::Assns< recob::Wire, recob::Hit > &, RecobHitToPtrMap &) const
Create recob::Wire to recob::Hit associations.
void makeRawDigitAssns (const art::Event &, art::Assns< raw::RawDigit, recob::Hit > &, RecobHitToPtrMap &) const
Create raw::RawDigit to recob::Hit associations.
size_t BuildHitPairMap (PlaneToSnippetHitMap &planeToHitVectorMap, reco::HitPairList &hitPairList) const
Given the ClusterHit2D objects, build the HitPairMap.
size_t BuildHitPairMapByTPC (PlaneSnippetHitMapItrPairVec &planeSnippetHitMapItrPairVec, reco::HitPairList &hitPairList) const
Given the ClusterHit2D objects, build the HitPairMap.
int findGoodHitPairs (SnippetHitMap::iterator &, SnippetHitMap::iterator &, SnippetHitMap::iterator &, HitMatchTripletVecMap &) const
void findGoodTriplets (HitMatchTripletVecMap &, HitMatchTripletVecMap &, reco::HitPairList &, bool=false) const
This algorithm takes lists of hit pairs and finds good triplets.
int saveOrphanPairs (HitMatchTripletVecMap &, reco::HitPairList &) const
This will look at storing pair "orphans" where the 2D hits are otherwise unused.
bool makeHitPair (reco::ClusterHit3D &pairOut, const reco::ClusterHit2D *hit1, const reco::ClusterHit2D *hit2, float hitWidthSclFctr=1., size_t hitPairCntr=0) const
Make a HitPair object by checking two hits.
bool makeHitTriplet (reco::ClusterHit3D &pairOut, const reco::ClusterHit3D &pairIn, const reco::ClusterHit2D *hit2) const
Make a 3D HitPair object by checking two hits.
bool makeDeadChannelPair (reco::ClusterHit3D &pairOut, const reco::ClusterHit3D &pair, size_t maxStatus=4, size_t minStatus=0, float minOverlap=0.2) const
Make a 3D HitPair object from a valid pair and a dead channel in the missing plane.
bool WireIDsIntersect (const geo::WireID &, const geo::WireID &, geo::WireIDIntersection &) const
function to detemine if two wires "intersect" (in the 2D sense)
float closestApproach (const Eigen::Vector3f &, const Eigen::Vector3f &, const Eigen::Vector3f &, const Eigen::Vector3f &, float &, float &) const
function to compute the distance of closest approach and the arc length to the points of closest approach
const reco::ClusterHit2D * FindBestMatchingHit (const Hit2DSet &hit2DSet, const reco::ClusterHit3D &pair, float pairDeltaTimeLimits) const
A utility routine for finding a 2D hit closest in time to the given pair.
int FindNumberInRange (const Hit2DSet &hit2DSet, const reco::ClusterHit3D &pair, float range) const
A utility routine for returning the number of 2D hits from the list in a given range.
geo::WireID NearestWireID (const Eigen::Vector3f &position, const geo::WireID &wireID) const
Jacket the calls to finding the nearest wire in order to intercept the exceptions if out of range.
float DistanceFromPointToHitWire (const Eigen::Vector3f &position, const geo::WireID &wireID) const
Jacket the calls to finding the nearest wire in order to intercept the exceptions if out of range.
float chargeIntegral (float, float, float, float, int, int) const
Perform charge integration between limits.
void clear ()
clear the tuple vectors before processing next event
Private Attributes
std::vector< art::InputTag > m_hitFinderTagVec
float m_hitWidthSclFctr
float m_deltaPeakTimeSig
float m_rangeNumSig
float m_LongHitStretchFctr
float m_pulseHeightFrac
float m_PHLowSelection
float m_minPHFor2HitPoints
Set a minimum pulse height for 2 hit space point candidates.
std::vector< int > m_invalidTPCVec
float m_wirePitchScaleFactor
Scaling factor to determine max distance allowed between candidate pairs.
float m_maxHit3DChiSquare
Provide ability to select hits based on "chi square".
bool m_allowBadChannels
Allow space points with bad channels.
bool m_saveMythicalPoints
Should we save valid 2 hit space points?
float m_maxMythicalChiSquare
Selection cut on mythical points.
bool m_useT0Offsets
If true then we will use the LArSoft interplane offsets.
bool m_outputHistograms
Take the time to create and fill some histograms for diagnostics.
bool m_makeAssociations
Do we make wire/rawdigit associations to space points?
bool m_enableMonitoring
float m_wirePitch [3]
std::vector< float > m_timeVector
float m_zPosOffset
PlaneToT0OffsetMap m_PlaneToT0OffsetMap
TTree * m_tupleTree
output analysis tree
std::vector< float > m_deltaPeakTimePlane0Vec
std::vector< float > m_deltaPeakSigmaPlane0Vec
std::vector< float > m_deltaPeakTimePlane1Vec
std::vector< float > m_deltaPeakSigmaPlane1Vec
std::vector< float > m_deltaPeakTimePlane2Vec
std::vector< float > m_deltaPeakSigmaPlane2Vec
std::vector< float > m_deltaTimeVec
std::vector< float > m_deltaTime0Vec
std::vector< float > m_deltaSigma0Vec
std::vector< float > m_deltaTime1Vec
std::vector< float > m_deltaSigma1Vec
std::vector< float > m_deltaTime2Vec
std::vector< float > m_deltaSigma2Vec
std::vector< float > m_chiSquare3DVec
std::vector< float > m_maxPullVec
std::vector< float > m_overlapFractionVec
std::vector< float > m_overlapRangeVec
std::vector< float > m_maxDeltaPeakVec
std::vector< float > m_maxSideVecVec
std::vector< float > m_pairWireDistVec
std::vector< float > m_smallChargeDiffVec
std::vector< int > m_smallIndexVec
std::vector< float > m_qualityMetricVec
std::vector< float > m_spacePointChargeVec
std::vector< float > m_hitAsymmetryVec
std::vector< float > m_2hit1stPHVec
std::vector< float > m_2hit2ndPHVec
std::vector< float > m_2hitDeltaPHVec
std::vector< float > m_2hitSumPHVec
Hit2DList m_clusterHit2DMasterList
PlaneToSnippetHitMap m_planeToSnippetHitMap
PlaneToWireToHitSetMap m_planeToWireToHitSetMap
bool m_weHaveAllBeenHereBefore = false
const geo::Geometry * m_geometry
const lariov::ChannelStatusProvider * m_channelFilter
Detailed Description
SnippetHit3DBuilderICARUS class definiton.
Definition at line 81 of file SnippetHit3DBuilderICARUS_tool.cc.
Member Typedef Documentation
ChannelStatusByPlaneVec
using lar_cluster3d::SnippetHit3DBuilderICARUS::ChannelStatusByPlaneVec = std::vector<ChannelStatusVec> private
Definition at line 232 of file SnippetHit3DBuilderICARUS_tool.cc.
ChannelStatusVec
using lar_cluster3d::SnippetHit3DBuilderICARUS::ChannelStatusVec = std::vector<size_t> private
define data structure for keeping track of channel status
Definition at line 231 of file SnippetHit3DBuilderICARUS_tool.cc.
HitMatchTriplet
using lar_cluster3d::SnippetHit3DBuilderICARUS::HitMatchTriplet = std::tuple<const reco::ClusterHit2D*,const reco::ClusterHit2D*,const reco::ClusterHit3D> private
This builds a list of candidate hit pairs from lists of hits on two planes.
Definition at line 154 of file SnippetHit3DBuilderICARUS_tool.cc.
HitMatchTripletVec
using lar_cluster3d::SnippetHit3DBuilderICARUS::HitMatchTripletVec = std::vector<HitMatchTriplet> private
Definition at line 155 of file SnippetHit3DBuilderICARUS_tool.cc.
HitMatchTripletVecMap
using lar_cluster3d::SnippetHit3DBuilderICARUS::HitMatchTripletVecMap = std::map<geo::WireID,HitMatchTripletVec> private
Definition at line 156 of file SnippetHit3DBuilderICARUS_tool.cc.
PlaneToT0OffsetMap
using lar_cluster3d::SnippetHit3DBuilderICARUS::PlaneToT0OffsetMap = std::map<geo::PlaneID,float> private
Definition at line 268 of file SnippetHit3DBuilderICARUS_tool.cc.
TickCorrectionArray
using lar_cluster3d::SnippetHit3DBuilderICARUS::TickCorrectionArray = std::vector<std::vector<std::vector<float>>> private
Data members to follow.
Definition at line 242 of file SnippetHit3DBuilderICARUS_tool.cc.
Constructor & Destructor Documentation
SnippetHit3DBuilderICARUS()
lar_cluster3d::SnippetHit3DBuilderICARUS::SnippetHit3DBuilderICARUS (fhicl::ParameterSet const & pset) explicit
Constructor.
Parameters
pset
Definition at line 317 of file SnippetHit3DBuilderICARUS_tool.cc.
Member Function Documentation
BuildHit3D()
void lar_cluster3d::SnippetHit3DBuilderICARUS::BuildHit3D (reco::HitPairList & hitPairList) const private
Given the ClusterHit2D objects, build the HitPairMap.
Driver for processing input 2D hits, transforming to 3D hits and building lists of associated 3D hits (candidate 3D clusters)
Definition at line 543 of file SnippetHit3DBuilderICARUS_tool.cc.
References BuildHitPairMap().
Referenced by Hit3DBuilder().
BuildHitPairMap()
size_t lar_cluster3d::SnippetHit3DBuilderICARUS::BuildHitPairMap (PlaneToSnippetHitMap & planeToHitVectorMap, reco::HitPairList & hitPairList) const private
Given the ClusterHit2D objects, build the HitPairMap.
Given input 2D hits, build out the lists of possible 3D hits
   The current strategy: ideally all 3D hits would be comprised of a triplet of 2D hits, one from each view
   However, we have concern that, in particular, the v-plane may have some inefficiency which we have to be
   be prepared to deal with. The idea, then, is to first make the association of hits in the U and W planes
   and then look for the match in the V plane. In the event we don't find the match in the V plane then we
   will evaluate the situation and in some instances keep the U-W pairs in order to keep efficiency high.
Definition at line 595 of file SnippetHit3DBuilderICARUS_tool.cc.
References BuildHitPairMapByTPC().
Referenced by BuildHit3D().
BuildHitPairMapByTPC()
size_t lar_cluster3d::SnippetHit3DBuilderICARUS::BuildHitPairMapByTPC (PlaneSnippetHitMapItrPairVec & planeSnippetHitMapItrPairVec, reco::HitPairList & hitPairList) const private
Given the ClusterHit2D objects, build the HitPairMap.
Given input 2D hits, build out the lists of possible 3D hits
   The current strategy: ideally all 3D hits would be comprised of a triplet of 2D hits, one from each view
   However, we have concern that, in particular, the v-plane may have some inefficiency which we have to be
   be prepared to deal with. The idea, then, is to first make the association of hits in the U and W planes
   and then look for the match in the V plane. In the event we don't find the match in the V plane then we
   will evaluate the situation and in some instances keep the U-W pairs in order to keep efficiency high.
Definition at line 653 of file SnippetHit3DBuilderICARUS_tool.cc.
References findGoodTriplets(), m_saveMythicalPoints, and saveOrphanPairs().
Referenced by BuildHitPairMap().
chargeIntegral()
float lar_cluster3d::SnippetHit3DBuilderICARUS::chargeIntegral (float peakMean, float peakAmp, float peakSigma, float areaNorm, int low, int hi) const private
Perform charge integration between limits.
Definition at line 1477 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by makeHitTriplet().
clear()
void lar_cluster3d::SnippetHit3DBuilderICARUS::clear () private
clear the tuple vectors before processing next event
Definition at line 412 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
closestApproach()
float lar_cluster3d::SnippetHit3DBuilderICARUS::closestApproach (const Eigen::Vector3f & P0, const Eigen::Vector3f & u0, const Eigen::Vector3f & P1, const Eigen::Vector3f & u1, float & arcLen0, float & arcLen1) const private
function to compute the distance of closest approach and the arc length to the points of closest approach
Definition at line 1452 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by WireIDsIntersect().
CollectArtHits()
void lar_cluster3d::SnippetHit3DBuilderICARUS::CollectArtHits (const art::Event & evt) const private
Extract the ART hits and the ART hit-particle relationships.
Parameters
evt - the ART event
Recover the 2D hits from art and fill out the local data structures for the 3D clustering
Definition at line 1730 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
configure()
void lar_cluster3d::SnippetHit3DBuilderICARUS::configure (const fhicl::ParameterSet & pset) override virtual
Definition at line 335 of file SnippetHit3DBuilderICARUS_tool.cc.
CreateNewRecobHitCollection()
void lar_cluster3d::SnippetHit3DBuilderICARUS::CreateNewRecobHitCollection (art::Event & event, reco::HitPairList & hitPairList, std::vector< recob::Hit > & hitPtrVec, RecobHitToPtrMap & recobHitToPtrMap) private
Create a new 2D hit collection from hits associated to 3D space points.
Definition at line 1871 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
DistanceFromPointToHitWire()
float lar_cluster3d::SnippetHit3DBuilderICARUS::DistanceFromPointToHitWire (const Eigen::Vector3f & position, const geo::WireID & wireID) const private
Jacket the calls to finding the nearest wire in order to intercept the exceptions if out of range.
Definition at line 1670 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by makeHitTriplet().
FindBestMatchingHit()
const reco::ClusterHit2D * lar_cluster3d::SnippetHit3DBuilderICARUS::FindBestMatchingHit (const Hit2DSet & hit2DSet, const reco::ClusterHit3D & pair, float pairDeltaTimeLimits) const private
A utility routine for finding a 2D hit closest in time to the given pair.
Definition at line 1589 of file SnippetHit3DBuilderICARUS_tool.cc.
findGoodHitPairs()
int lar_cluster3d::SnippetHit3DBuilderICARUS::findGoodHitPairs (SnippetHitMap::iterator & firstSnippetItr, SnippetHitMap::iterator & startItr, SnippetHitMap::iterator & endItr, HitMatchTripletVecMap & hitMatchMap) const private
Definition at line 745 of file SnippetHit3DBuilderICARUS_tool.cc.
findGoodTriplets()
void lar_cluster3d::SnippetHit3DBuilderICARUS::findGoodTriplets (HitMatchTripletVecMap & pair12Map, HitMatchTripletVecMap & pair13Map, reco::HitPairList & hitPairList, bool tagged = false) const private
This algorithm takes lists of hit pairs and finds good triplets.
Definition at line 799 of file SnippetHit3DBuilderICARUS_tool.cc.
References m_allowBadChannels, and makeHitTriplet().
Referenced by BuildHitPairMapByTPC().
FindNumberInRange()
int lar_cluster3d::SnippetHit3DBuilderICARUS::FindNumberInRange (const Hit2DSet & hit2DSet, const reco::ClusterHit3D & pair, float range) const private
A utility routine for returning the number of 2D hits from the list in a given range.
Definition at line 1616 of file SnippetHit3DBuilderICARUS_tool.cc.
getTimeToExecute()
virtual float lar_cluster3d::SnippetHit3DBuilderICARUS::getTimeToExecute (IHit3DBuilder::TimeValues index) const inline override virtual
If monitoring, recover the time to execute a particular function.
Definition at line 110 of file SnippetHit3DBuilderICARUS_tool.cc.
Hit3DBuilder()
void lar_cluster3d::SnippetHit3DBuilderICARUS::Hit3DBuilder (art::Event & evt, reco::HitPairList & hitPairList, RecobHitToPtrMap & clusterHitToArtPtrMap) override virtual
Given a set of recob hits, run DBscan to form 3D clusters.
Parameters
hitPairList The input list of 3D hits to run clustering on
clusterParametersList A list of cluster objects (parameters from associated hits)
Associations with wires.
Associations with raw digits.
Definition at line 466 of file SnippetHit3DBuilderICARUS_tool.cc.
References BuildHit3D(), clear(), CollectArtHits(), CreateNewRecobHitCollection(), m_makeAssociations, m_outputHistograms, m_tupleTree, m_useT0Offsets, makeRawDigitAssns(), and makeWireAssns().
makeDeadChannelPair()
bool lar_cluster3d::SnippetHit3DBuilderICARUS::makeDeadChannelPair (reco::ClusterHit3D & pairOut, const reco::ClusterHit3D & pair, size_t maxStatus = 4, size_t minStatus = 0, float minOverlap = 0.2) const private
Make a 3D HitPair object from a valid pair and a dead channel in the missing plane.
Definition at line 1495 of file SnippetHit3DBuilderICARUS_tool.cc.
References NearestWireID().
makeHitPair()
bool lar_cluster3d::SnippetHit3DBuilderICARUS::makeHitPair (reco::ClusterHit3D & pairOut, const reco::ClusterHit2D * hit1, const reco::ClusterHit2D * hit2, float hitWidthSclFctr = 1., size_t hitPairCntr = 0) const private
Make a HitPair object by checking two hits.
Definition at line 968 of file SnippetHit3DBuilderICARUS_tool.cc.
References m_outputHistograms, and WireIDsIntersect().
Referenced by makeHitTriplet().
makeHitTriplet()
bool lar_cluster3d::SnippetHit3DBuilderICARUS::makeHitTriplet (reco::ClusterHit3D & pairOut, const reco::ClusterHit3D & pairIn, const reco::ClusterHit2D * hit2) const private
Make a 3D HitPair object by checking two hits.
Definition at line 1119 of file SnippetHit3DBuilderICARUS_tool.cc.
References chargeIntegral(), DistanceFromPointToHitWire(), m_outputHistograms, m_wirePitchScaleFactor, and makeHitPair().
Referenced by findGoodTriplets().
makeRawDigitAssns()
void lar_cluster3d::SnippetHit3DBuilderICARUS::makeRawDigitAssns (const art::Event & evt, art::Assns< raw::RawDigit, recob::Hit > & rawDigitAssns, RecobHitToPtrMap & recobHitPtrMap) const private
Create raw::RawDigit to recob::Hit associations.
Definition at line 1985 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
makeWireAssns()
void lar_cluster3d::SnippetHit3DBuilderICARUS::makeWireAssns (const art::Event & evt, art::Assns< recob::Wire, recob::Hit > & wireAssns, RecobHitToPtrMap & recobHitPtrMap) const private
Create recob::Wire to recob::Hit associations.
Definition at line 1939 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
NearestWireID()
geo::WireID lar_cluster3d::SnippetHit3DBuilderICARUS::NearestWireID (const Eigen::Vector3f & position, const geo::WireID & wireID) const private
Jacket the calls to finding the nearest wire in order to intercept the exceptions if out of range.
Definition at line 1641 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by makeDeadChannelPair().
produces()
void lar_cluster3d::SnippetHit3DBuilderICARUS::produces (art::ProducesCollector & collector) override virtual
Each algorithm may have different objects it wants "produced" so use this to let the top level producer module "know" what it is outputting.
Definition at line 326 of file SnippetHit3DBuilderICARUS_tool.cc.
saveOrphanPairs()
int lar_cluster3d::SnippetHit3DBuilderICARUS::saveOrphanPairs (HitMatchTripletVecMap & pairMap, reco::HitPairList & hitPairList) const private
This will look at storing pair "orphans" where the 2D hits are otherwise unused.
Definition at line 915 of file SnippetHit3DBuilderICARUS_tool.cc.
References m_maxMythicalChiSquare, m_minPHFor2HitPoints, and m_outputHistograms.
Referenced by BuildHitPairMapByTPC().
WireIDsIntersect()
bool lar_cluster3d::SnippetHit3DBuilderICARUS::WireIDsIntersect (const geo::WireID & wireID0, const geo::WireID & wireID1, geo::WireIDIntersection & widIntersection) const private
function to detemine if two wires "intersect" (in the 2D sense)
Definition at line 1400 of file SnippetHit3DBuilderICARUS_tool.cc.
References closestApproach().
Referenced by makeHitPair().
Member Data Documentation
m_2hit1stPHVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_2hit1stPHVec mutable private
Definition at line 301 of file SnippetHit3DBuilderICARUS_tool.cc.
m_2hit2ndPHVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_2hit2ndPHVec mutable private
Definition at line 302 of file SnippetHit3DBuilderICARUS_tool.cc.
m_2hitDeltaPHVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_2hitDeltaPHVec mutable private
Definition at line 303 of file SnippetHit3DBuilderICARUS_tool.cc.
m_2hitSumPHVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_2hitSumPHVec mutable private
Definition at line 304 of file SnippetHit3DBuilderICARUS_tool.cc.
m_allowBadChannels
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_allowBadChannels private
Allow space points with bad channels.
Definition at line 255 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by findGoodTriplets().
m_channelFilter
const lariov::ChannelStatusProvider* lar_cluster3d::SnippetHit3DBuilderICARUS::m_channelFilter private
Definition at line 314 of file SnippetHit3DBuilderICARUS_tool.cc.
m_chiSquare3DVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_chiSquare3DVec mutable private
Definition at line 289 of file SnippetHit3DBuilderICARUS_tool.cc.
m_clusterHit2DMasterList
Hit2DList lar_cluster3d::SnippetHit3DBuilderICARUS::m_clusterHit2DMasterList mutable private
Definition at line 307 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakSigmaPlane0Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakSigmaPlane0Vec mutable private
Definition at line 276 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakSigmaPlane1Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakSigmaPlane1Vec mutable private
Definition at line 278 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakSigmaPlane2Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakSigmaPlane2Vec mutable private
Definition at line 280 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakTimePlane0Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakTimePlane0Vec mutable private
Definition at line 275 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakTimePlane1Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakTimePlane1Vec mutable private
Definition at line 277 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakTimePlane2Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakTimePlane2Vec mutable private
Definition at line 279 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaPeakTimeSig
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaPeakTimeSig private
Definition at line 246 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaSigma0Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaSigma0Vec mutable private
Definition at line 284 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaSigma1Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaSigma1Vec mutable private
Definition at line 286 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaSigma2Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaSigma2Vec mutable private
Definition at line 288 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaTime0Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaTime0Vec mutable private
Definition at line 283 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaTime1Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaTime1Vec mutable private
Definition at line 285 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaTime2Vec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaTime2Vec mutable private
Definition at line 287 of file SnippetHit3DBuilderICARUS_tool.cc.
m_deltaTimeVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_deltaTimeVec mutable private
Definition at line 282 of file SnippetHit3DBuilderICARUS_tool.cc.
m_enableMonitoring
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_enableMonitoring private
Definition at line 262 of file SnippetHit3DBuilderICARUS_tool.cc.
m_geometry
const geo::Geometry* lar_cluster3d::SnippetHit3DBuilderICARUS::m_geometry private
Definition at line 313 of file SnippetHit3DBuilderICARUS_tool.cc.
m_hitAsymmetryVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_hitAsymmetryVec mutable private
Definition at line 300 of file SnippetHit3DBuilderICARUS_tool.cc.
m_hitFinderTagVec
std::vector<art::InputTag> lar_cluster3d::SnippetHit3DBuilderICARUS::m_hitFinderTagVec private
Definition at line 244 of file SnippetHit3DBuilderICARUS_tool.cc.
m_hitWidthSclFctr
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_hitWidthSclFctr private
Definition at line 245 of file SnippetHit3DBuilderICARUS_tool.cc.
m_invalidTPCVec
std::vector<int> lar_cluster3d::SnippetHit3DBuilderICARUS::m_invalidTPCVec private
Definition at line 252 of file SnippetHit3DBuilderICARUS_tool.cc.
m_LongHitStretchFctr
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_LongHitStretchFctr private
Definition at line 248 of file SnippetHit3DBuilderICARUS_tool.cc.
m_makeAssociations
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_makeAssociations private
Do we make wire/rawdigit associations to space points?
Definition at line 260 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
m_maxDeltaPeakVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_maxDeltaPeakVec mutable private
Definition at line 293 of file SnippetHit3DBuilderICARUS_tool.cc.
m_maxHit3DChiSquare
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_maxHit3DChiSquare private
Provide ability to select hits based on "chi square".
Definition at line 254 of file SnippetHit3DBuilderICARUS_tool.cc.
m_maxMythicalChiSquare
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_maxMythicalChiSquare private
Selection cut on mythical points.
Definition at line 257 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by saveOrphanPairs().
m_maxPullVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_maxPullVec mutable private
Definition at line 290 of file SnippetHit3DBuilderICARUS_tool.cc.
m_maxSideVecVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_maxSideVecVec mutable private
Definition at line 294 of file SnippetHit3DBuilderICARUS_tool.cc.
m_minPHFor2HitPoints
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_minPHFor2HitPoints private
Set a minimum pulse height for 2 hit space point candidates.
Definition at line 251 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by saveOrphanPairs().
m_outputHistograms
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_outputHistograms private
Take the time to create and fill some histograms for diagnostics.
Definition at line 259 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder(), makeHitPair(), makeHitTriplet(), and saveOrphanPairs().
m_overlapFractionVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_overlapFractionVec mutable private
Definition at line 291 of file SnippetHit3DBuilderICARUS_tool.cc.
m_overlapRangeVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_overlapRangeVec mutable private
Definition at line 292 of file SnippetHit3DBuilderICARUS_tool.cc.
m_pairWireDistVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_pairWireDistVec mutable private
Definition at line 295 of file SnippetHit3DBuilderICARUS_tool.cc.
m_PHLowSelection
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_PHLowSelection private
Definition at line 250 of file SnippetHit3DBuilderICARUS_tool.cc.
m_planeToSnippetHitMap
PlaneToSnippetHitMap lar_cluster3d::SnippetHit3DBuilderICARUS::m_planeToSnippetHitMap mutable private
Definition at line 308 of file SnippetHit3DBuilderICARUS_tool.cc.
m_PlaneToT0OffsetMap
PlaneToT0OffsetMap lar_cluster3d::SnippetHit3DBuilderICARUS::m_PlaneToT0OffsetMap private
Definition at line 270 of file SnippetHit3DBuilderICARUS_tool.cc.
m_planeToWireToHitSetMap
PlaneToWireToHitSetMap lar_cluster3d::SnippetHit3DBuilderICARUS::m_planeToWireToHitSetMap mutable private
Definition at line 309 of file SnippetHit3DBuilderICARUS_tool.cc.
m_pulseHeightFrac
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_pulseHeightFrac private
Definition at line 249 of file SnippetHit3DBuilderICARUS_tool.cc.
m_qualityMetricVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_qualityMetricVec mutable private
Definition at line 298 of file SnippetHit3DBuilderICARUS_tool.cc.
m_rangeNumSig
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_rangeNumSig private
Definition at line 247 of file SnippetHit3DBuilderICARUS_tool.cc.
m_saveMythicalPoints
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_saveMythicalPoints private
Should we save valid 2 hit space points?
Definition at line 256 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by BuildHitPairMapByTPC().
m_smallChargeDiffVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_smallChargeDiffVec mutable private
Definition at line 296 of file SnippetHit3DBuilderICARUS_tool.cc.
m_smallIndexVec
std::vector<int> lar_cluster3d::SnippetHit3DBuilderICARUS::m_smallIndexVec mutable private
Definition at line 297 of file SnippetHit3DBuilderICARUS_tool.cc.
m_spacePointChargeVec
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_spacePointChargeVec mutable private
Definition at line 299 of file SnippetHit3DBuilderICARUS_tool.cc.
m_timeVector
std::vector<float> lar_cluster3d::SnippetHit3DBuilderICARUS::m_timeVector mutable private
Definition at line 264 of file SnippetHit3DBuilderICARUS_tool.cc.
m_tupleTree
TTree* lar_cluster3d::SnippetHit3DBuilderICARUS::m_tupleTree private
output analysis tree
Definition at line 273 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
m_useT0Offsets
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_useT0Offsets private
If true then we will use the LArSoft interplane offsets.
Definition at line 258 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by Hit3DBuilder().
m_weHaveAllBeenHereBefore
bool lar_cluster3d::SnippetHit3DBuilderICARUS::m_weHaveAllBeenHereBefore = false mutable private
Definition at line 311 of file SnippetHit3DBuilderICARUS_tool.cc.
m_wirePitch
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_wirePitch[3] private
Definition at line 263 of file SnippetHit3DBuilderICARUS_tool.cc.
m_wirePitchScaleFactor
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_wirePitchScaleFactor private
Scaling factor to determine max distance allowed between candidate pairs.
Definition at line 253 of file SnippetHit3DBuilderICARUS_tool.cc.
Referenced by makeHitTriplet().
m_zPosOffset
float lar_cluster3d::SnippetHit3DBuilderICARUS::m_zPosOffset private
Definition at line 266 of file SnippetHit3DBuilderICARUS_tool.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/TPC/Tracking/cluster3D/SnippetHit3DBuilderICARUS_tool.cc