CAF format: daq::details::BoardInfoLookup Class Reference
daq::details::BoardInfoLookup Class Reference
Utility class for fast lookup of board data by fragment ID.
#include <PMTDecoderUtils.h>
Classes
struct BoardInfo_t
Record of information about a readout board.
Public Types
using FragmentID_t = unsigned int
using Database_t = std::vector<BoardInfo_t>
Public Member Functions
BoardInfoLookup (Database_t &&database)
unsigned int nBoardInfo () const
Returns the number of registered boards.
auto const & allBoardInfo () const
Returns an object that can be iterated for all available information.
BoardInfo_t const * findBoardInfo (FragmentID_t fragmentID) const
Returns a pointer to the information for board with fragmentID.
BoardSetup_t const * findBoardSetup (FragmentID_t fragmentID) const
Returns a pointer to the setup information for board with fragmentID.
sbn::V1730Configuration const * findBoardConfig (FragmentID_t fragmentID) const
Returns a pointer to the configuration of board with fragmentID.
Static Private Member Functions
static Database_t sortDatabase (Database_t &&db)
Sorts the database structure in the argument and returns it.
Private Attributes
Database_t const fDatabase
Detailed Description
Utility class for fast lookup of board data by fragment ID.
Definition at line 144 of file PMTDecoderUtils.h.
Member Typedef Documentation
Database_t
using daq::details::BoardInfoLookup::Database_t = std::vector<BoardInfo_t>
Definition at line 160 of file PMTDecoderUtils.h.
FragmentID_t
using daq::details::BoardInfoLookup::FragmentID_t = unsigned int
Definition at line 147 of file PMTDecoderUtils.h.
Constructor & Destructor Documentation
BoardInfoLookup()
daq::details::BoardInfoLookup::BoardInfoLookup (Database_t && database) inline explicit
Definition at line 163 of file PMTDecoderUtils.h.
Member Function Documentation
allBoardInfo()
auto const & daq::details::BoardInfoLookup::allBoardInfo () const inline
Returns an object that can be iterated for all available information.
Definition at line 171 of file PMTDecoderUtils.h.
findBoardConfig()
sbn::V1730Configuration const * daq::details::BoardInfoLookup::findBoardConfig (FragmentID_t fragmentID) const inline
Returns a pointer to the configuration of board with fragmentID.
Definition at line 184 of file PMTDecoderUtils.h.
References findBoardInfo().
findBoardInfo()
auto daq::details::BoardInfoLookup::findBoardInfo (FragmentID_t fragmentID) const inline
Returns a pointer to the information for board with fragmentID.
Definition at line 206 of file PMTDecoderUtils.h.
Referenced by findBoardConfig(), and findBoardSetup().
findBoardSetup()
BoardSetup_t const * daq::details::BoardInfoLookup::findBoardSetup (FragmentID_t fragmentID) const inline
Returns a pointer to the setup information for board with fragmentID.
Definition at line 177 of file PMTDecoderUtils.h.
References findBoardInfo().
nBoardInfo()
unsigned int daq::details::BoardInfoLookup::nBoardInfo () const inline
Returns the number of registered boards.
Definition at line 168 of file PMTDecoderUtils.h.
sortDatabase()
static Database_t daq::details::BoardInfoLookup::sortDatabase (Database_t && db) inline static private
Sorts the database structure in the argument and returns it.
Definition at line 196 of file PMTDecoderUtils.h.
Member Data Documentation
fDatabase
Database_t const daq::details::BoardInfoLookup::fDatabase private
Definition at line 193 of file PMTDecoderUtils.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h