CAF format: icarus::trigger::SlidingWindowPatternAlg Class Reference
icarus::trigger::SlidingWindowPatternAlg Class Reference
Applies sliding window patterns to discriminated waveforms.
#include <SlidingWindowPatternAlg.h>
Classes
struct AllTriggerInfo_t
Complete information from this algorithm, standard + non-standard (extra).
struct MoreInfo_t
Additional information on the trigger.
struct WindowTriggerInfo_t
Data structure to communicate internally a trigger response.
Public Types
using TriggerInfo_t = icarus::trigger::details::TriggerInfo_t
Record of the trigger response.
using InputTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Type of trigger gate provided as input.
using TriggerGates_t = std::vector<InputTriggerGate_t>
A list of trigger gates from input.
using TriggerGateData_t = icarus::trigger::OpticalTriggerGateData_t
Type of gate data without channel information (gate levels only).
using WindowTopology_t = icarus::trigger::WindowChannelMap
Type holding information about composition and topology of all windows.
using WindowPattern_t = icarus::trigger::WindowPattern
Type representing the requirement pattern for a window.
Public Member Functions
SlidingWindowPatternAlg (WindowTopology_t windowTopology, WindowPattern_t windowPattern, icarus::trigger::ApplyBeamGateClass beamGate, std::string const &logCategory="SlidingWindowPatternAlg")
Constructor: configures window topology and times.
SlidingWindowPatternAlg (WindowTopology_t windowTopology, WindowPattern_t windowPattern, std::string const &logCategory="SlidingWindowPatternAlg")
Constructor: configures window topology and times.
AllTriggerInfo_t simulateResponse (TriggerGates_t const &gates) const
Returns the trigger response from the specified gates.
TriggerGates_t applyBeamGate (TriggerGates_t const &gates) const
Returns a new collection of gates, set each in coincidence with beam gate.
bool hasBeamGate () const
Returns whether a beam gate is being applied.
void setBeamGate (icarus::trigger::ApplyBeamGateClass beamGate)
Changes the beam gate to the specified value.
void clearBeamGate ()
Do not apply any beam gate.
TriggerInfo_t applyWindowPattern (WindowTopology_t::WindowInfo_t const &windowInfo, WindowPattern_t const &pattern, TriggerGates_t const &gates) const
Returns the trigger response for the specified window pattern.
Private Member Functions
TriggerInfo_t applyWindowPattern (WindowPattern_t const &pattern, std::size_t iWindow, TriggerGates_t const &gates) const
Returns the trigger response for the specified window pattern.
void verifyInputTopology (TriggerGates_t const &gates) const
Checks gates are compatible with the current window configuration.
Private Attributes
WindowTopology_t const fWindowTopology
Definition of the neighborhood of each window in terms of window indices.
WindowPattern_t const fWindowPattern
Requirement pattern to be applied to each window.
std::optional< icarus::trigger::ApplyBeamGateClass const > fBeamGate
Time interval when to evaluate the trigger.
Detailed Description
Applies sliding window patterns to discriminated waveforms.
This algorithm takes as input one trigger gate for each window. Each window is identified by an index, and the input gates are assigned one per window, in order.
The window mapping that defines the topology of the windows is passed to the algorithm.
If a beam gate is present, it is applied to all input before simulating the pattern. Otherwise, the full input is used.
For the definition of the windows, see icarus::trigger::WindowChannelMap.
Definition at line 51 of file SlidingWindowPatternAlg.h.
Class Documentation
icarus::trigger::SlidingWindowPatternAlg::MoreInfo_t
struct icarus::trigger::SlidingWindowPatternAlg::MoreInfo_t
Additional information on the trigger.
Definition at line 76 of file SlidingWindowPatternAlg.h.
Class Members
size_t windowIndex = std::numeric_limits<std::size_t>::max() Index of the window which led the trigger.
Member Typedef Documentation
InputTriggerGate_t
using icarus::trigger::SlidingWindowPatternAlg::InputTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Type of trigger gate provided as input.
Definition at line 61 of file SlidingWindowPatternAlg.h.
TriggerGateData_t
using icarus::trigger::SlidingWindowPatternAlg::TriggerGateData_t = icarus::trigger::OpticalTriggerGateData_t
Type of gate data without channel information (gate levels only).
Definition at line 67 of file SlidingWindowPatternAlg.h.
TriggerGates_t
using icarus::trigger::SlidingWindowPatternAlg::TriggerGates_t = std::vector<InputTriggerGate_t>
A list of trigger gates from input.
Definition at line 64 of file SlidingWindowPatternAlg.h.
TriggerInfo_t
using icarus::trigger::SlidingWindowPatternAlg::TriggerInfo_t = icarus::trigger::details::TriggerInfo_t
Record of the trigger response.
Definition at line 58 of file SlidingWindowPatternAlg.h.
WindowPattern_t
using icarus::trigger::SlidingWindowPatternAlg::WindowPattern_t = icarus::trigger::WindowPattern
Type representing the requirement pattern for a window.
Definition at line 73 of file SlidingWindowPatternAlg.h.
WindowTopology_t
using icarus::trigger::SlidingWindowPatternAlg::WindowTopology_t = icarus::trigger::WindowChannelMap
Type holding information about composition and topology of all windows.
Definition at line 70 of file SlidingWindowPatternAlg.h.
Constructor & Destructor Documentation
SlidingWindowPatternAlg() [1/2]
icarus::trigger::SlidingWindowPatternAlg::SlidingWindowPatternAlg (WindowTopology_t windowTopology, WindowPattern_t windowPattern, icarus::trigger::ApplyBeamGateClass beamGate, std::string const & logCategory = "SlidingWindowPatternAlg")
Constructor: configures window topology and times.
Parameters
windowTopology full composition and topology description of windows
windowPattern the pattern that this algorithm applies
beamGate object applying the beam gate to trigger gates
logCategory category tag for algorithm messages on screen
Window topology can be computed with icarus::trigger::WindowTopologyAlg starting from a (complete) set of trigger gates.
A beam gate application class can be constructed via icarus::trigger::makeApplyBeamGate() helper function.
Definition at line 34 of file SlidingWindowPatternAlg.cxx.
SlidingWindowPatternAlg() [2/2]
icarus::trigger::SlidingWindowPatternAlg::SlidingWindowPatternAlg (WindowTopology_t windowTopology, WindowPattern_t windowPattern, std::string const & logCategory = "SlidingWindowPatternAlg")
Constructor: configures window topology and times.
Parameters
windowTopology full composition and topology description of windows
windowPattern the pattern that this algorithm applies
logCategory category tag for algorithm messages on screen
Window topology can be computed with icarus::trigger::WindowTopologyAlg starting from a (complete) set of trigger gates.
The beam gate is set to be empty; it must be set before simulating the response (simulateResponse()) via setBeamGate().
Definition at line 48 of file SlidingWindowPatternAlg.cxx.
Member Function Documentation
applyBeamGate()
TriggerGates_t icarus::trigger::SlidingWindowPatternAlg::applyBeamGate (TriggerGates_t const & gates) const
Returns a new collection of gates, set each in coincidence with beam gate.
applyWindowPattern() [1/2]
auto icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern (WindowPattern_t const & pattern, std::size_t iWindow, TriggerGates_t const & gates) const private
Returns the trigger response for the specified window pattern.
Parameters
pattern the trigger requirement pattern
iWindow index of the window to be tested
gates trigger gates, one per window
Returns
a TriggerInfo_t record with the response of the pattern
See also
applyWindowPattern(WindowChannelMap::WindowInfo const&, WindowPattern_t const&, TriggerGates_t const&)
Applies the specified pattern to the window with index iWindow of the configured window topology.
See the static version of applyWindowPattern() for details.
Definition at line 342 of file SlidingWindowPatternAlg.cxx.
References icarus::trigger::WindowChannelMap::WindowTopology_t::index.
applyWindowPattern() [2/2]
auto icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern (WindowTopology_t::WindowInfo_t const & windowInfo, WindowPattern_t const & pattern, TriggerGates_t const & gates) const
Returns the trigger response for the specified window pattern.
Parameters
windowInfo the topology of the windows
pattern the trigger requirement pattern
gates trigger gates, one per window
Returns
a TriggerInfo_t record with the response of the pattern
The input gates represent all the trigger gates relevant to the trigger determination, in a list by window index: the first gate belongs to the window 0, the second one to the window 1 and so on. The topology windowInfo identifies a window and its topology, i.e. its neighbours, by window index. It is required and assumed that the values of the window indices match the ones in the gates list. This function applies the requirements in the specified pattern to the window identified by windowInfo, using the actual trigger gates from the gates list as needed.
The return value includes the first tick at which the requirements have been all met. Note that if a beam gate needs to be applied, it should be applies to all gates before calling this function (see e.g. applyBeamGate()).
Definition at line 207 of file SlidingWindowPatternAlg.cxx.
References icarus::trigger::details::TriggerInfo_t::add(), icarus::trigger::compactdump(), icarus::trigger::discriminate(), icarus::trigger::WindowChannelMap::WindowTopology_t::downstream, icarus::trigger::gateIn(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasDownstreamWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasOppositeWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasUpstreamWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::index, icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >::Mul(), icarus::trigger::WindowChannelMap::WindowTopology_t::opposite, icarus::trigger::sumGates(), and icarus::trigger::WindowChannelMap::WindowTopology_t::upstream.
clearBeamGate()
void icarus::trigger::SlidingWindowPatternAlg::clearBeamGate ()
Do not apply any beam gate.
Definition at line 133 of file SlidingWindowPatternAlg.cxx.
hasBeamGate()
bool icarus::trigger::SlidingWindowPatternAlg::hasBeamGate () const
Returns whether a beam gate is being applied.
Definition at line 122 of file SlidingWindowPatternAlg.cxx.
setBeamGate()
void icarus::trigger::SlidingWindowPatternAlg::setBeamGate (icarus::trigger::ApplyBeamGateClass beamGate)
Changes the beam gate to the specified value.
Definition at line 127 of file SlidingWindowPatternAlg.cxx.
simulateResponse()
auto icarus::trigger::SlidingWindowPatternAlg::simulateResponse (TriggerGates_t const & gates) const
Returns the trigger response from the specified gates.
Parameters
gates the trigger gates to be used as input, one per window
Returns
the response to the configured pattern
See also
applyWindowPattern(WindowChannelMap::WindowInfo const&, WindowPattern_t const&, TriggerGates_t const&)
The return value comprises a "standard" TriggerInfo_t object, which stores whether the pattern fired and when, and some extra information, including which window made the trigger fire first (in case of ties, the window with the smallest index is reported).
The list gates must contain a single trigger gate for each window, with the gate index in the list matching the window index in the configured window topology.
See the static version of applyWindowPattern() for more details.
Definition at line 60 of file SlidingWindowPatternAlg.cxx.
References icarus::trigger::details::TriggerInfo_t::all(), icarus::trigger::details::TriggerInfo_t::atTick(), icarus::trigger::details::TriggerInfo_t::hasLocation(), icarus::trigger::details::TriggerInfo_t::location(), icarus::trigger::details::TriggerInfo_t::main(), and icarus::trigger::details::TriggerInfo_t::nTriggers().
verifyInputTopology()
void icarus::trigger::SlidingWindowPatternAlg::verifyInputTopology (TriggerGates_t const & gates) const private
Checks gates are compatible with the current window configuration.
Parameters
gates the combined sliding window trigger gates, per cryostat
Exceptions
cet::exception (category: SlidingWindowTriggerEfficiencyPlots) or derived, if an incompatibility is found
The method verifies that the current channel mapping is compatible with the gates.
This currently means that the gates are in the expected order and have the expected channel content.
Definition at line 138 of file SlidingWindowPatternAlg.cxx.
References icarus::trigger::WindowChannelMap::WindowComposition_t::channels, and icarus::trigger::WindowChannelMap::WindowTopology_t::index.
Member Data Documentation
fBeamGate
std::optional<icarus::trigger::ApplyBeamGateClass const> icarus::trigger::SlidingWindowPatternAlg::fBeamGate private
Time interval when to evaluate the trigger.
Definition at line 223 of file SlidingWindowPatternAlg.h.
fWindowPattern
WindowPattern_t const icarus::trigger::SlidingWindowPatternAlg::fWindowPattern private
Requirement pattern to be applied to each window.
Definition at line 220 of file SlidingWindowPatternAlg.h.
fWindowTopology
WindowTopology_t const icarus::trigger::SlidingWindowPatternAlg::fWindowTopology private
Definition of the neighborhood of each window in terms of window indices.
Definition at line 217 of file SlidingWindowPatternAlg.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/SlidingWindowPatternAlg.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/SlidingWindowPatternAlg.cxx