CAF format: icarusDB::PMTTimingCorrectionsProvider Class Reference
icarusDB::PMTTimingCorrectionsProvider Class Reference
This module reads the PMT timing corrections from the database. Corrections are picked according to the run number being processed.
#include <PMTTimingCorrectionsProvider.h>
Public Member Functions
PMTTimingCorrectionsProvider (const fhicl::ParameterSet &pset)
void readTimeCorrectionDatabase (const art::Run &run)
Read timing corrections from the database.
double getTriggerCableDelay (unsigned int channelID) const override
Get time delay on the trigger line.
double getResetCableDelay (unsigned int channelID) const override
Get time delay on the PPS reset line.
double getLaserCorrections (unsigned int channelID) const override
Get timing corrections from laser data.
double getCosmicsCorrections (unsigned int channelID) const override
Get timing corrections from cosmics data.
Public Member Functions inherited from icarusDB::PMTTimingCorrections
Private Types
using PMTTimeCorrectionsDB = details::PMTTimeCorrectionsDB
Private Member Functions
PMTTimeCorrectionsDB const & getChannelCorrOrDefault (unsigned int channelID) const
Internal access to the channel correction record; returns defaults if not present.
uint64_t RunToDatabaseTimestamp (uint32_t run) const
Convert run number to internal database.
void ReadPMTCablesCorrections (uint32_t run)
Function to look up the calibration database at the table holding the pmt hardware cables corrections.
void ReadLaserCorrections (uint32_t run)
Function to look up the calibration database at the table holding the pmt timing corrections measured using the laser.
void ReadCosmicsCorrections (uint32_t run)
Function to look up the calibration database at the table holding the pmt timing corrections measured using cosmic muons.
Private Attributes
bool fVerbose = false
Whether to print the configuration we read.
std::string fLogCategory
Category tag for messages.
std::string fCablesTag
Tag for cable corrections database.
std::string fLaserTag
Tag for laser corrections database.
std::string fCosmicsTag
Tag for cosmics corrections database.
std::map< unsigned int, PMTTimeCorrectionsDB > fDatabaseTimingCorrections
Map of corrections by channel.
Static Private Attributes
static constexpr PMTTimeCorrectionsDB CorrectionDefaults {}
Default values.
Detailed Description
This module reads the PMT timing corrections from the database. Corrections are picked according to the run number being processed.
All time corrections are offsets (in microseconds) that need to be added to the uncorrected time.
Configuration parameters
CorrectionTags: tags to select the correction versions:
CablesTag (default: v1r0): correction for cable delay.
LaserTag (default: v1r0): first order PMT time correction, from laser data.
CosmicsTag (default: v1r0): second order PMT time correction, from cosmic rays.
Verbose (default: false): Print-out the corrections read from the database.
LogCategory (default: `PMTTimingCorrection")
Definition at line 61 of file PMTTimingCorrectionsProvider.h.
Member Typedef Documentation
PMTTimeCorrectionsDB
using icarusDB::PMTTimingCorrectionsProvider::PMTTimeCorrectionsDB = details::PMTTimeCorrectionsDB private
Definition at line 92 of file PMTTimingCorrectionsProvider.h.
Constructor & Destructor Documentation
PMTTimingCorrectionsProvider()
icarusDB::PMTTimingCorrectionsProvider::PMTTimingCorrectionsProvider (const fhicl::ParameterSet & pset)
Definition at line 27 of file PMTTimingCorrectionsProvider.cxx.
Member Function Documentation
getChannelCorrOrDefault()
PMTTimeCorrectionsDB const & icarusDB::PMTTimingCorrectionsProvider::getChannelCorrOrDefault (unsigned int channelID) const inline private
Internal access to the channel correction record; returns defaults if not present.
Definition at line 105 of file PMTTimingCorrectionsProvider.h.
References CorrectionDefaults, and fDatabaseTimingCorrections.
Referenced by getCosmicsCorrections(), getLaserCorrections(), getResetCableDelay(), and getTriggerCableDelay().
getCosmicsCorrections()
double icarusDB::PMTTimingCorrectionsProvider::getCosmicsCorrections (unsigned int channelID) const inline override virtual
Get timing corrections from cosmics data.
Implements icarusDB::PMTTimingCorrections.
Definition at line 86 of file PMTTimingCorrectionsProvider.h.
References icarusDB::details::PMTTimeCorrectionsDB::cosmicsCorrections, and getChannelCorrOrDefault().
getLaserCorrections()
double icarusDB::PMTTimingCorrectionsProvider::getLaserCorrections (unsigned int channelID) const inline override virtual
Get timing corrections from laser data.
Implements icarusDB::PMTTimingCorrections.
Definition at line 81 of file PMTTimingCorrectionsProvider.h.
References getChannelCorrOrDefault(), and icarusDB::details::PMTTimeCorrectionsDB::laserCableDelay.
getResetCableDelay()
double icarusDB::PMTTimingCorrectionsProvider::getResetCableDelay (unsigned int channelID) const inline override virtual
Get time delay on the PPS reset line.
Implements icarusDB::PMTTimingCorrections.
Definition at line 76 of file PMTTimingCorrectionsProvider.h.
References getChannelCorrOrDefault(), and icarusDB::details::PMTTimeCorrectionsDB::resetCableDelay.
getTriggerCableDelay()
double icarusDB::PMTTimingCorrectionsProvider::getTriggerCableDelay (unsigned int channelID) const inline override virtual
Get time delay on the trigger line.
Implements icarusDB::PMTTimingCorrections.
Definition at line 71 of file PMTTimingCorrectionsProvider.h.
References getChannelCorrOrDefault(), and icarusDB::details::PMTTimeCorrectionsDB::triggerCableDelay.
ReadCosmicsCorrections()
void icarusDB::PMTTimingCorrectionsProvider::ReadCosmicsCorrections (uint32_t run) private
Function to look up the calibration database at the table holding the pmt timing corrections measured using cosmic muons.
pmt_cosmics_residual: time residuals from downward going cosmics tracks correcting for point-like laser emission and pmts that do not see laser light corrections are saved in ns, but icaruscode wants us Corrections are additive!
Definition at line 167 of file PMTTimingCorrectionsProvider.cxx.
ReadLaserCorrections()
void icarusDB::PMTTimingCorrectionsProvider::ReadLaserCorrections (uint32_t run) private
Function to look up the calibration database at the table holding the pmt timing corrections measured using the laser.
pmt_laser_delay: delay from the Electron Transit time inside the PMT and the PMT signal cable corrections are saved in ns, but icaruscode wants us Corrections are additive!
Definition at line 127 of file PMTTimingCorrectionsProvider.cxx.
ReadPMTCablesCorrections()
void icarusDB::PMTTimingCorrectionsProvider::ReadPMTCablesCorrections (uint32_t run) private
Function to look up the calibration database at the table holding the pmt hardware cables corrections.
This is the delay due to the cables connecting the 'global' trigger crate FPGA to the spare channel of the first digitizer in each VME crates. The phase correction is an additional fudge factor holding local variation due to constant clock offsets (it can be up to 8 ns) It can be absorbed within other corrections if necessary Corrections are saved in ns, but icaruscode wants us Correction are saved with the sing correspoding to their time direction
This is the delay along the distribution line of the TTT reset The phase correction is an additional fudge factor holding local variation due to constant clock offsets (it can be up to 8 ns) It can be absorbed within other corrections if necessary Corrections are saved in ns, but icaruscode wants us Corrections are additive!
Definition at line 63 of file PMTTimingCorrectionsProvider.cxx.
readTimeCorrectionDatabase()
void icarusDB::PMTTimingCorrectionsProvider::readTimeCorrectionDatabase (const art::Run & run)
Read timing corrections from the database.
Read all the corrections from the database and save them inside a map, whose index is the PMT channel number
Definition at line 211 of file PMTTimingCorrectionsProvider.cxx.
RunToDatabaseTimestamp()
uint64_t icarusDB::PMTTimingCorrectionsProvider::RunToDatabaseTimestamp (uint32_t run) const private
Convert run number to internal database.
Definition at line 44 of file PMTTimingCorrectionsProvider.cxx.
References fLogCategory, and fVerbose.
Member Data Documentation
CorrectionDefaults
PMTTimeCorrectionsDB icarusDB::PMTTimingCorrectionsProvider::CorrectionDefaults {} static constexpr private
Default values.
Definition at line 93 of file PMTTimingCorrectionsProvider.h.
Referenced by getChannelCorrOrDefault().
fCablesTag
std::string icarusDB::PMTTimingCorrectionsProvider::fCablesTag private
Tag for cable corrections database.
Definition at line 97 of file PMTTimingCorrectionsProvider.h.
fCosmicsTag
std::string icarusDB::PMTTimingCorrectionsProvider::fCosmicsTag private
Tag for cosmics corrections database.
Definition at line 99 of file PMTTimingCorrectionsProvider.h.
fDatabaseTimingCorrections
std::map<unsigned int, PMTTimeCorrectionsDB> icarusDB::PMTTimingCorrectionsProvider::fDatabaseTimingCorrections private
Map of corrections by channel.
Definition at line 102 of file PMTTimingCorrectionsProvider.h.
Referenced by getChannelCorrOrDefault().
fLaserTag
std::string icarusDB::PMTTimingCorrectionsProvider::fLaserTag private
Tag for laser corrections database.
Definition at line 98 of file PMTTimingCorrectionsProvider.h.
fLogCategory
std::string icarusDB::PMTTimingCorrectionsProvider::fLogCategory private
Category tag for messages.
Definition at line 96 of file PMTTimingCorrectionsProvider.h.
Referenced by RunToDatabaseTimestamp().
fVerbose
bool icarusDB::PMTTimingCorrectionsProvider::fVerbose = false private
Whether to print the configuration we read.
Definition at line 95 of file PMTTimingCorrectionsProvider.h.
Referenced by RunToDatabaseTimestamp().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/Timing/PMTTimingCorrectionsProvider.h
icaruscode/icaruscode/Timing/PMTTimingCorrectionsProvider.cxx