CAF format: daq::TriggerDecoderV3 Class Reference
daq::TriggerDecoderV3 Class Reference
Tool decoding the trigger information from DAQ.
Classes
struct TriggerGateTypes
Codes of gate types from the trigger hardware.
Public Member Functions
TriggerDecoderV3 (fhicl::ParameterSet const &pset)
virtual void consumes (art::ConsumesCollector &collector) override
Declare to the framework what you expect to read.
virtual void produces (art::ProducesCollector &) override
The space point building should output the hit collection for those hits which combine to form space points - a nice noise filter!
virtual void configure (const fhicl::ParameterSet &) override
Interface for configuring the particular algorithm tool.
virtual void initializeDataProducts () override
Initialize any data products the tool will output.
virtual void setupRun (art::Run const &run) override
Preparation to process a new run.
virtual void process_fragment (const artdaq::Fragment &fragment) override
Given a set of recob hits, run DBscan to form 3D clusters.
virtual void outputDataProducts (art::Event &event) override
Output the data products to the event store.
Public Member Functions inherited from daq::IDecoder
virtual ~IDecoder () noexcept=default
Virtual Destructor.
virtual std::optional< art::InputTag > preferredInput () const
Returns the tag of the input fragment, if known (empty otherwise).
virtual void setupEvent (art::Event const &event)
Preparation to process a new event.
Private Types
using microseconds = util::quantities::microsecond
using nanoseconds = util::quantities::nanosecond
using TriggerCollection = std::vector<raw::ExternalTrigger>
using TriggerPtr = std::unique_ptr<TriggerCollection>
using RelativeTriggerCollection = std::vector<raw::Trigger>
using BeamGateInfoCollection = std::vector<sim::BeamGateInfo>
using BeamGateInfoPtr = std::unique_ptr<BeamGateInfoCollection>
using ExtraInfoPtr = std::unique_ptr<sbn::ExtraTriggerInfo>
Private Member Functions
icarus::ICARUSTriggerV3Fragment makeTriggerFragment (artdaq::Fragment const &fragment) const
Creates a ICARUSTriggerInfo from a generic fragment.
icarus::ICARUSTriggerInfo parseTriggerString (std::string_view data) const
Parses the trigger data packet with the "standard" parser.
icarus::KeyValuesData parseTriggerStringAsCSV (std::string const &data) const
Parses the trigger data packet with a CSV parser.
sbn::ExtraTriggerInfo::CryostatInfo unpackPrimitiveBits (std::size_t cryostat, bool firstEvent, unsigned long int counts, std::uint64_t connectors01, std::uint64_t connectors23, sbn::bits::triggerLogicMask triggerLogic) const
Fills one cryostat information of sbn::ExtraTriggerInfo.
std::array< std::uint64_t, sbn::ExtraTriggerInfo::MaxWalls > encodeLVDSbits (short int cryostat, std::uint64_t connector01word, std::uint64_t connector23word) const
Encodes all the LVDS bits for the specified cryostat.
std::array< std::uint16_t, sbn::ExtraTriggerInfo::MaxWalls > encodeSectorBits (short int cryostat, std::uint64_t connector01word, std::uint64_t connector23word) const
Encodes all the adder bits for the specified cryostat.
Static Private Member Functions
static std::string_view firstLine (std::string const &s, std::string const &endl="\0\n\r"s)
static std::uint64_t makeTimestamp (unsigned int s, unsigned int ns)
Combines second and nanosecond counts into a 64-bit timestamp.
static long long int timestampDiff (std::uint64_t a, std::uint64_t b)
Returns the difference a - b.
static std::uint64_t encodeLVDSbitsLegacy (short int cryostat, short int connector, std::uint64_t connectorWord)
static std::uint16_t encodeSectorBitsLegacy (short int cryostat, short int connector, std::uint64_t connectorWord)
template<unsigned int startBit, unsigned int nBits, typename T >
static constexpr T bits (T value)
Returns the nBits bits of value from startBit on.
static sim::BeamType_t simGateType (sbn::triggerSource source)
Returns the beam type corresponding to the specified trigger source.
static std::string sanitize (std::string const &s)
Returns s with non-printable characters replaced.
Private Attributes
TriggerPtr fTrigger
TriggerPtr fPrevTrigger
std::unique_ptr< RelativeTriggerCollection > fRelTrigger
ExtraInfoPtr fTriggerExtra
BeamGateInfoPtr fBeamGateInfo
art::InputTag fTriggerConfigTag
Data product with hardware trigger configuration.
bool fAllowDefaultLVDSmap
Allow LVDS mapping without mapping database.
bool fDiagnosticOutput
Produces large number of diagnostic messages, use with caution!
bool fDebug
Use this for debugging this tool.
long fLastEvent = 0
detinfo::DetectorTimings const fDetTimings
Detector clocks and timings.
icarusDB::IICARUSChannelMapProvider const * fChannelMap = nullptr
PMT channel mapping service provider.
util::CacheGuard fChannelMapCacheGuard
icarus::TriggerConfiguration const * fTriggerConfiguration = nullptr
Cached pointer to the trigger configuration of the current run, if any.
std::optional< icarus::trigger::LVDSbitMaps > fPMTpairMap
Map of LVDS bits.
Static Private Attributes
static std::string const CurrentTriggerInstanceName {}
Name of the data product instance for the current trigger.
static std::string const PreviousTriggerInstanceName { "previous" }
Name of the data product instance for the previous trigger.
static constexpr double UnknownBeamTime = std::numeric_limits<double>::max()
Detailed Description
Tool decoding the trigger information from DAQ.
Produces:
std::vector<raw::ExternalTrigger> containing the absolute trigger time stamp from the White Rabbit system, and a trigger count; it always includes a single entry (zero might be supported).
std::vector<raw::Trigger> containing:
TriggerTime(): the relative time of the trigger as reported in the White Rabbit timestamp, measured in the electronics time scale (for ICARUS it will always be detinfo::DetectorClocksData::TriggerTime()).
BeamGateTime(): relative time of the announced arrival of the beam, also in electronics time scale.
TriggerCount(): the trigger count from the beginning of the run.
TriggerBits(): includes the beam(s) with an open gate when the trigger happened (currently only one beam gate per trigger); definitions are in sbn::beamType namespace.
It always includes a single entry (zero might be supported).
std::vector<sim::BeamGateInfo> containing information on the "main" beam gate associated to each trigger (a way to say that if by any chance there are more than one bits set for the trigger, this gate will pick only one of them):
Start(): relative time of the announced arrival of the beam, in simulation time scale.
Width(): duration of the gate, in nanoseconds; read from trigger configuration if specified (TrigConfigLabel), set to 0 otherwise.
BeamType(): the type of the beam gate being described (BNB, NuMI).
sbn::ExtraTriggerInfo: the most complete collection of information, duplicating also some from the other data products. Note that differently from the usual, this is a single object, not a collection; also, this data product has no instance name. The information already available includes:
sourceType: the type of beam or trigger source, a value from sbn::triggerSource (equivalent to raw::Trigger::TriggerBits(), but in the form of an enumerator rather than a bit mask). Also called gate type.
triggerType: the type of trigger logic applied, a value from sbn::triggerType, e.g. minimum bias or majority.
triggerTimestamp: same as raw::ExternalTrigger::GetTrigTime() (nanoseconds from the Epoch, Coordinated Universal Time).
beamGateTimestamp: absolute time of the beam gate opening as reported by the trigger hardware, directly comparable with triggerTimestamp (same scale and unit).
enableGateTimestamp: absolute time of the enable gate opening as reported by the trigger hardware, directly comparable with triggerTimestamp (same scale and unit). This is the gate that enables the generation of trigger primitives and the off-spill readout of PMT. Its duration can be found in the trigger configuration data product (icarus::TriggerConfiguration).
triggerID: same as raw::ExternalTrigger::GetTrigID(). Should match the event number.
gateID: the count of gates since the beginning of the run, as reported by the trigger hardware.
gateCountFromPreviousTrigger: number of gates since the last trigger: specifically, if this is e.g. a majority trigger is from off-beam BNB gate, this is the number of off-beam BNB gates considered for majority triggers (i.e. excluding minimum bias) from the last off-beam BNB majority trigger (minimum number is 1, since that gate is included). The same logic applies for minimum bias triggers, which excludes from the count all minimum bias triggers (and therefore for minimum bias this count is always expected to be 1).
previousTriggerTimestamp: absolute timestamp of the previous trigger from this source. For example, if this is a majority trigger from an off-beam BNB gate, this represents the previous off-beam BNB majority trigger.
gateCount: total number of gates of this type (triggered or not) from the beginning of the run (minimum 1 since this one is included). For example, if this trigger is from an off-beam BNB gate, this is the number of off-beam BNB gates from the beginning of the run. Note that this count, differently from the source-specific trigger counts below, mixes the types of triggers (majority and minimum bias).
triggerCount: total number of triggers from gates of this type from the beginning of the run (minimum 1 since this one is included). For example, if this trigger is from an off-beam BNB majority trigger, this is the number of off-beam BNB majority triggers from the beginning of the run.
anyTriggerCountFromPreviousTrigger: number of triggers that occurred since the last trigger of this type (the one with timestamp previousTriggerTimestamp).
anyGateCountFromAnyPreviousTrigger: not available. It would hold how many gates have passed since the last trigger (reported by anyPreviousTriggerTimestamp), with minimum value 1.
anyPreviousTriggerTimestamp: absolute timestamp of the previous trigger (from any source). For example, if this trigger is from an off-beam BNB gate, and the previous was from a NuMI gate, this represents that previous (NuMI) trigger.
anyPreviousTriggerSourceType: the type of gate of the previous trigger (the one reported by anyPreviousTriggerTimestamp).
WRtimeToTriggerTime (nanoseconds): correction added to the GPS/White Rabbit time to obtain the trigger timestamp (normally it's the conversion from TAI to NTP timestamps).
triggerLocationBits: whether the trigger came from the east or west cryostat (currently the triggers combine the two opposite PMT walls, so there is no TPC-level granularity).
cryostats: information per cryostat (east first, then west). Note however that only the cryostats that are mentioned in triggerLocationBits have the information filled.
triggerCount: number of triggers in this cryostat fired during the trigger window; only the first one becomes the global trigger, but we still keep the count of how many happen. Its value is 0 when trigger happened from elsewhere.
triggerLogicBits: whether the trigger on this cryostat was from adder logic, trigger logic or both. The definition of "both" is taken by the hardware, based on an allowed overlapping time between the signals of the different logics, properly delayed.
LVDSstatus: information per PMT wall (i.e. TPC; east first, then west) of the LVDS signals of the discriminated PMT pairs at the time of the global trigger. All bits are 0 when trigger happened elsewhere. Otherwise, the encoding implements the prescription documented in sbn::ExtraTriggerInfo using information from the PMT channel mapping service (icarusDB::IICARUSChannelMap) if it was configured. Otherwise, the encoding is not guaranteed to be correct, and it is implemented in terms of hardware connector ports as follows:
east wall: 00<C0P2><C0P1><C0P0>00<C1P2><C1P1><C1P0>
west wall: 00<C2P2><C2P1><C2P0>00<C3P2><C3P1><C3P0>
For the expected matching with PMT, see the documentation of sbn::ExtraTriggerInfo::CryostatInfo::LVDSstatus.
sectorStatus: information for detector sector (one per TPC), reporting the discrimination status of the adder signals at the time of the global trigger. All bits are 0 when trigger happened elsewhere. Otherwise, the encoding implements the prescription documented in sbn::ExtraTriggerInfo using information from the PMT channel mapping service (icarusDB::IICARUSChannelMap) if it was configured. Otherwise, the encoding is not guaranteed to be correct, and it is implemented extracting bits from port 3 of the connectors:
east wall: 0000'0000'00ss'snnn with <C0P3> = 0000'0sss and <C1P3> = 0000'0nnn
west wall: 0000'0000'00ss'snnn with <C2P3> = 0000'0sss and <C3P3> = 0000'0nnn
Information may be missing. If a count is not available, its value is set to 0 (which is an invalid value because their valid range starts with 1 since they include the current event), and if a timestamp is not available it is set to sbn::ExtraTriggerInfo::NoTimestamp; these two conditions can be checked with static methods sbn::ExtraTriggerInfo::isValidTimestamp() and sbn::ExtraTriggerInfo::isValidCount() respectively.
Besides the main data product (empty instance name) an additional std::vector<raw::ExternalTrigger> data product with instance name "previous" is also produced, which relays the same kind of information but for the previous trigger. This information also comes from the trigger DAQ. If no previous trigger is available, this collection will be empty.
Timestamps and corrections
The reference trigger time is driven by the trigger fragment time, which is expected to have been derived from the actual trigger time from the White Rabbit system properly corrected to UTC by the board reader.
All absolute timestamps are corrected to be on that same scale. The absolute timestamps related to the White Rabbit time are added an offset to achieve this correction; this offset is stored in the data product (sbn::ExtraTriggerInfo::WRtimeToTriggerTime).
Configuration
TrigConfigLabel (input tag, mandatory): tag of the trigger configuration data product (see icarus::TriggerConfigurationExtractor module) to be used. Specifying its tag is mandatory, but if it is explicitly specified empty, the decoder will try to work around its absence.
AllowDefaultLVDSmap (flag, default: false): if set, when PMT channel mapping service is not available a legacy encoding pattern will be used for the LVDSstatus bits, and a warning will be printed. If unset and the PMT channel mapping database is not available, an exception will be thrown.
DiagnosticOutput (flag, default: false): prints on console trigger data diagnostics (including a full dump of the parsed content).
Debug (flag, default: false): prints on console decoding debug information, including a dump of the trigger data fragment.
Definition at line 248 of file TriggerDecoderV3_tool.cc.
Member Typedef Documentation
BeamGateInfoCollection
using daq::TriggerDecoderV3::BeamGateInfoCollection = std::vector<sim::BeamGateInfo> private
Definition at line 267 of file TriggerDecoderV3_tool.cc.
BeamGateInfoPtr
using daq::TriggerDecoderV3::BeamGateInfoPtr = std::unique_ptr<BeamGateInfoCollection> private
Definition at line 268 of file TriggerDecoderV3_tool.cc.
ExtraInfoPtr
using daq::TriggerDecoderV3::ExtraInfoPtr = std::unique_ptr<sbn::ExtraTriggerInfo> private
Definition at line 269 of file TriggerDecoderV3_tool.cc.
microseconds
using daq::TriggerDecoderV3::microseconds = util::quantities::microsecond private
Definition at line 250 of file TriggerDecoderV3_tool.cc.
nanoseconds
using daq::TriggerDecoderV3::nanoseconds = util::quantities::nanosecond private
Definition at line 251 of file TriggerDecoderV3_tool.cc.
RelativeTriggerCollection
using daq::TriggerDecoderV3::RelativeTriggerCollection = std::vector<raw::Trigger> private
Definition at line 266 of file TriggerDecoderV3_tool.cc.
TriggerCollection
using daq::TriggerDecoderV3::TriggerCollection = std::vector<raw::ExternalTrigger> private
Definition at line 264 of file TriggerDecoderV3_tool.cc.
TriggerPtr
using daq::TriggerDecoderV3::TriggerPtr = std::unique_ptr<TriggerCollection> private
Definition at line 265 of file TriggerDecoderV3_tool.cc.
Constructor & Destructor Documentation
TriggerDecoderV3()
daq::TriggerDecoderV3::TriggerDecoderV3 (fhicl::ParameterSet const & pset) explicit
Definition at line 378 of file TriggerDecoderV3_tool.cc.
Member Function Documentation
bits()
template<unsigned int startBit, unsigned int nBits, typename T > T daq::TriggerDecoderV3::bits (T value) static constexpr private
Returns the nBits bits of value from startBit on.
Definition at line 1132 of file TriggerDecoderV3_tool.cc.
configure()
void daq::TriggerDecoderV3::configure (const fhicl::ParameterSet &) override virtual
Interface for configuring the particular algorithm tool.
Parameters
ParameterSet The input set of parameters for configuration
Implements daq::IDecoder.
Definition at line 417 of file TriggerDecoderV3_tool.cc.
References fAllowDefaultLVDSmap, fDebug, fDiagnosticOutput, and fTriggerConfigTag.
consumes()
void daq::TriggerDecoderV3::consumes (art::ConsumesCollector &) override virtual
Declare to the framework what you expect to read.
Reimplemented from daq::IDecoder.
Definition at line 402 of file TriggerDecoderV3_tool.cc.
References fTriggerConfigTag.
encodeLVDSbits()
std::array< std::uint64_t, sbn::ExtraTriggerInfo::MaxWalls > daq::TriggerDecoderV3::encodeLVDSbits (short int cryostat, std::uint64_t connector01word, std::uint64_t connector23word) const private
Encodes all the LVDS bits for the specified cryostat.
Definition at line 959 of file TriggerDecoderV3_tool.cc.
References icarus::trigger::LVDSHWbitID::bit, icarus::trigger::LVDSHWbitID::connector, icarus::trigger::LVDSHWbitID::cryostat, sbn::ExtraTriggerInfo::EastPMTwall, encodeLVDSbitsLegacy(), fPMTpairMap, icarus::trigger::LVDSbitMaps::PMTpairs, and sbn::ExtraTriggerInfo::WestPMTwall.
Referenced by unpackPrimitiveBits().
encodeLVDSbitsLegacy()
std::uint64_t daq::TriggerDecoderV3::encodeLVDSbitsLegacy (short int cryostat, short int connector, std::uint64_t connectorWord) static private
Encodes the connectorWord LVDS bits from the specified cryostat and connector into the format required by sbn::ExtraTriggerInfo.
Definition at line 935 of file TriggerDecoderV3_tool.cc.
Referenced by encodeLVDSbits().
encodeSectorBits()
std::array< std::uint16_t, sbn::ExtraTriggerInfo::MaxWalls > daq::TriggerDecoderV3::encodeSectorBits (short int cryostat, std::uint64_t connector01word, std::uint64_t connector23word) const private
Encodes all the adder bits for the specified cryostat.
Definition at line 1046 of file TriggerDecoderV3_tool.cc.
References icarus::trigger::LVDSbitMaps::Adders, icarus::trigger::LVDSHWbitID::bit, icarus::trigger::LVDSHWbitID::connector, icarus::trigger::LVDSHWbitID::cryostat, sbn::ExtraTriggerInfo::EastPMTwall, fPMTpairMap, and sbn::ExtraTriggerInfo::WestPMTwall.
Referenced by unpackPrimitiveBits().
encodeSectorBitsLegacy()
std::uint16_t daq::TriggerDecoderV3::encodeSectorBitsLegacy (short int cryostat, short int connector, std::uint64_t connectorWord) static private
Definition at line 1138 of file TriggerDecoderV3_tool.cc.
firstLine()
std::string_view daq::TriggerDecoderV3::firstLine (std::string const & s, std::string const & endl = "\0\n\r"s) static private
Definition at line 906 of file TriggerDecoderV3_tool.cc.
initializeDataProducts()
void daq::TriggerDecoderV3::initializeDataProducts () override virtual
Initialize any data products the tool will output.
Implements daq::IDecoder.
Definition at line 437 of file TriggerDecoderV3_tool.cc.
makeTimestamp()
static std::uint64_t daq::TriggerDecoderV3::makeTimestamp (unsigned int s, unsigned int ns) inline static private
Combines second and nanosecond counts into a 64-bit timestamp.
Definition at line 328 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
makeTriggerFragment()
icarus::ICARUSTriggerV3Fragment daq::TriggerDecoderV3::makeTriggerFragment (artdaq::Fragment const & fragment) const private
Creates a ICARUSTriggerInfo from a generic fragment.
Definition at line 450 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
outputDataProducts()
void daq::TriggerDecoderV3::outputDataProducts (art::Event & event) override virtual
Output the data products to the event store.
Parameters
event The event store objects
Implements daq::IDecoder.
Definition at line 895 of file TriggerDecoderV3_tool.cc.
References CurrentTriggerInstanceName, and PreviousTriggerInstanceName.
parseTriggerString()
icarus::ICARUSTriggerInfo daq::TriggerDecoderV3::parseTriggerString (std::string_view data) const private
Parses the trigger data packet with the "standard" parser.
Definition at line 472 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
parseTriggerStringAsCSV()
icarus::KeyValuesData daq::TriggerDecoderV3::parseTriggerStringAsCSV (std::string const & data) const private
Parses the trigger data packet with a CSV parser.
Definition at line 494 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
process_fragment()
void daq::TriggerDecoderV3::process_fragment (const artdaq::Fragment & fragment) override virtual
Given a set of recob hits, run DBscan to form 3D clusters.
Parameters
fragment The artdaq fragment to process
Implements daq::IDecoder.
Definition at line 544 of file TriggerDecoderV3_tool.cc.
References sbn::ExtraTriggerInfo::anyGateCountFromAnyPreviousTrigger, sbn::ExtraTriggerInfo::anyPreviousTriggerSourceType, sbn::ExtraTriggerInfo::anyPreviousTriggerTimestamp, sbn::ExtraTriggerInfo::anyTriggerCountFromPreviousTrigger, sbn::ExtraTriggerInfo::beamGateTimestamp, sbn::bits::BNB, sbn::bits::Calib, sbn::bits::CryoEast, sbn::bits::CryoWest, sbn::ExtraTriggerInfo::EastCryostat, sbn::ExtraTriggerInfo::enableGateTimestamp, fDebug, fDetTimings, fDiagnosticOutput, fTriggerConfiguration, icarus::TriggerConfiguration::gateConfig, sbn::ExtraTriggerInfo::gateCount, sbn::ExtraTriggerInfo::gateCountFromPreviousTrigger, sbn::ExtraTriggerInfo::gateID, icarus::TriggerConfiguration::GateConfig::gateWidth, icarus::TriggerConfiguration::getGateWidth(), makeTimestamp(), makeTriggerFragment(), sbn::bits::NuMI, sbn::bits::OffbeamBNB, sbn::bits::OffbeamNuMI, parseTriggerString(), parseTriggerStringAsCSV(), sbn::bits::PMTAnalogSum, sbn::bits::PMTPairMajority, sbn::ExtraTriggerInfo::previousTriggerTimestamp, sanitize(), simGateType(), sbn::ExtraTriggerInfo::sourceType, timestampDiff(), sbn::ExtraTriggerInfo::triggerCount, sbn::ExtraTriggerInfo::triggerID, sbn::ExtraTriggerInfo::triggerLocationBits, sbn::ExtraTriggerInfo::triggerTimestamp, sbn::ExtraTriggerInfo::triggerType, sbn::bits::Unknown, unpackPrimitiveBits(), icarus::TriggerConfiguration::vetoDelay, sbn::ExtraTriggerInfo::WestCryostat, and sbn::ExtraTriggerInfo::WRtimeToTriggerTime.
produces()
void daq::TriggerDecoderV3::produces (art::ProducesCollector &) override virtual
The space point building should output the hit collection for those hits which combine to form space points - a nice noise filter!
Implements daq::IDecoder.
Definition at line 407 of file TriggerDecoderV3_tool.cc.
References CurrentTriggerInstanceName, and PreviousTriggerInstanceName.
sanitize()
std::string daq::TriggerDecoderV3::sanitize (std::string const & s) static private
Returns s with non-printable characters replaced.
Definition at line 1181 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
setupRun()
void daq::TriggerDecoderV3::setupRun (art::Run const & run) override virtual
Preparation to process a new run.
To be called on every art run transition.
Reimplemented from daq::IDecoder.
Definition at line 516 of file TriggerDecoderV3_tool.cc.
References icarus::trigger::LVDSbitMaps::Adders, fChannelMap, fPMTpairMap, fTriggerConfigTag, fTriggerConfiguration, icarus::trigger::LVDSbitMaps::PMTpairs, and util::CacheGuard::update().
simGateType()
sim::BeamType_t daq::TriggerDecoderV3::simGateType (sbn::triggerSource source) static private
Returns the beam type corresponding to the specified trigger source.
Definition at line 1163 of file TriggerDecoderV3_tool.cc.
References sbn::bits::BNB, sbn::bits::Calib, sbn::bits::NuMI, sbn::bits::OffbeamBNB, and sbn::bits::OffbeamNuMI.
Referenced by process_fragment().
timestampDiff()
static long long int daq::TriggerDecoderV3::timestampDiff (std::uint64_t a, std::uint64_t b) inline static private
Returns the difference a - b.
Definition at line 331 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
unpackPrimitiveBits()
sbn::ExtraTriggerInfo::CryostatInfo daq::TriggerDecoderV3::unpackPrimitiveBits (std::size_t cryostat, bool firstEvent, unsigned long int counts, std::uint64_t connectors01, std::uint64_t connectors23, sbn::bits::triggerLogicMask triggerLogic) const private
Fills one cryostat information of sbn::ExtraTriggerInfo.
Definition at line 913 of file TriggerDecoderV3_tool.cc.
References encodeLVDSbits(), encodeSectorBits(), sbn::ExtraTriggerInfo::CryostatInfo::LVDSstatus, sbn::ExtraTriggerInfo::CryostatInfo::sectorStatus, sbn::ExtraTriggerInfo::CryostatInfo::triggerCount, and sbn::ExtraTriggerInfo::CryostatInfo::triggerLogicBits.
Referenced by process_fragment().
Member Data Documentation
CurrentTriggerInstanceName
std::string const daq::TriggerDecoderV3::CurrentTriggerInstanceName {} static private
Name of the data product instance for the current trigger.
Definition at line 308 of file TriggerDecoderV3_tool.cc.
Referenced by outputDataProducts(), and produces().
fAllowDefaultLVDSmap
bool daq::TriggerDecoderV3::fAllowDefaultLVDSmap private
Allow LVDS mapping without mapping database.
Definition at line 276 of file TriggerDecoderV3_tool.cc.
Referenced by configure().
fBeamGateInfo
BeamGateInfoPtr daq::TriggerDecoderV3::fBeamGateInfo private
Definition at line 274 of file TriggerDecoderV3_tool.cc.
fChannelMap
icarusDB::IICARUSChannelMapProvider const* daq::TriggerDecoderV3::fChannelMap = nullptr private
PMT channel mapping service provider.
Tracks the cache of IICARUSChannelMapProvider.
Definition at line 285 of file TriggerDecoderV3_tool.cc.
Referenced by setupRun().
fChannelMapCacheGuard
util::CacheGuard daq::TriggerDecoderV3::fChannelMapCacheGuard private
Definition at line 288 of file TriggerDecoderV3_tool.cc.
fDebug
bool daq::TriggerDecoderV3::fDebug private
Use this for debugging this tool.
Definition at line 278 of file TriggerDecoderV3_tool.cc.
Referenced by configure(), and process_fragment().
fDetTimings
detinfo::DetectorTimings const daq::TriggerDecoderV3::fDetTimings private
Detector clocks and timings.
Definition at line 282 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment().
fDiagnosticOutput
bool daq::TriggerDecoderV3::fDiagnosticOutput private
Produces large number of diagnostic messages, use with caution!
Definition at line 277 of file TriggerDecoderV3_tool.cc.
Referenced by configure(), and process_fragment().
fLastEvent
long daq::TriggerDecoderV3::fLastEvent = 0 private
Definition at line 280 of file TriggerDecoderV3_tool.cc.
fPMTpairMap
std::optional<icarus::trigger::LVDSbitMaps> daq::TriggerDecoderV3::fPMTpairMap private
Map of LVDS bits.
Definition at line 294 of file TriggerDecoderV3_tool.cc.
Referenced by encodeLVDSbits(), encodeSectorBits(), and setupRun().
fPrevTrigger
TriggerPtr daq::TriggerDecoderV3::fPrevTrigger private
Definition at line 271 of file TriggerDecoderV3_tool.cc.
fRelTrigger
std::unique_ptr<RelativeTriggerCollection> daq::TriggerDecoderV3::fRelTrigger private
Definition at line 272 of file TriggerDecoderV3_tool.cc.
fTrigger
TriggerPtr daq::TriggerDecoderV3::fTrigger private
Definition at line 270 of file TriggerDecoderV3_tool.cc.
fTriggerConfigTag
art::InputTag daq::TriggerDecoderV3::fTriggerConfigTag private
Data product with hardware trigger configuration.
Definition at line 275 of file TriggerDecoderV3_tool.cc.
Referenced by configure(), consumes(), and setupRun().
fTriggerConfiguration
icarus::TriggerConfiguration const* daq::TriggerDecoderV3::fTriggerConfiguration = nullptr private
Cached pointer to the trigger configuration of the current run, if any.
Definition at line 291 of file TriggerDecoderV3_tool.cc.
Referenced by process_fragment(), and setupRun().
fTriggerExtra
ExtraInfoPtr daq::TriggerDecoderV3::fTriggerExtra private
Definition at line 273 of file TriggerDecoderV3_tool.cc.
PreviousTriggerInstanceName
std::string const daq::TriggerDecoderV3::PreviousTriggerInstanceName { "previous" } static private
Name of the data product instance for the previous trigger.
Definition at line 311 of file TriggerDecoderV3_tool.cc.
Referenced by outputDataProducts(), and produces().
UnknownBeamTime
double daq::TriggerDecoderV3::UnknownBeamTime = std::numeric_limits<double>::max() static constexpr private
Definition at line 313 of file TriggerDecoderV3_tool.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/TriggerDecoderV3_tool.cc