CAF format: util::CacheCounter Class Reference
util::CacheCounter Class Reference
Counter of cache versions.
#include <CacheCounter.h>
Public Types
using CacheID_t = unsigned long
Type of cache identifier.
using CacheTag_t = std::string
Type of cache name.
Public Member Functions
CacheCounter ()
Constructor: prepares the ID of the default cache tag.
CacheCounter (std::initializer_list< CacheTag_t > tags)
Constructor: prepares the ID of the caches with the specified tags.
void addCacheTags (std::initializer_list< CacheTag_t > tags)
Adds tags. The ID of existing ones are not changed.
CacheID_t cacheID (CacheTag_t const &tag) const
Returns the current ID of the cache with the specified tag.
bool hasTag (CacheTag_t const &tag) const
Returns whether the specified tag is tracked.
bool wasCacheUpdatedSince (CacheTag_t const &tag, CacheID_t sinceID) const
Returns whether the cache tag was updated since it has sinceID ID.
bool wasCacheUpdatedSince (CacheID_t sinceID) const
Returns whether the default cache was updated since it has sinceID ID.
Static Public Attributes
static constexpr CacheID_t NoCache = 0
ID specifying that cache is not present yet.
Protected Member Functions
CacheID_t updateCacheID (CacheTag_t const &cacheTag="") const
Protected Attributes
std::map< CacheTag_t, std::atomic< CacheID_t > > fCacheID
ID of the current caches.
Detailed Description
Counter of cache versions.
See also
util::CacheGuard
This simple class contains an index of cache IDs. A cache ID is a number that represents the status of a cache.
Multiple caches are supported by a single object instance. Each cache is represented by a "tag", or name. The cache with empty name is special in that it represent the whole set of caches: when updating it, all the other cache IDs are also updated.
Note that the special ID value NoCache represents the idea that the cache is never up to date and always needs to be refreshed (functionally equivalent to not having any cache).
See util::CacheGuard for a usage example.
Definition at line 46 of file CacheCounter.h.
Member Typedef Documentation
CacheID_t
using util::CacheCounter::CacheID_t = unsigned long
Type of cache identifier.
Definition at line 50 of file CacheCounter.h.
CacheTag_t
using util::CacheCounter::CacheTag_t = std::string
Type of cache name.
Definition at line 51 of file CacheCounter.h.
Constructor & Destructor Documentation
CacheCounter() [1/2]
util::CacheCounter::CacheCounter () inline
Constructor: prepares the ID of the default cache tag.
Definition at line 57 of file CacheCounter.h.
References fCacheID, and NoCache.
CacheCounter() [2/2]
util::CacheCounter::CacheCounter (std::initializer_list< CacheTag_t > tags) inline
Constructor: prepares the ID of the caches with the specified tags.
Definition at line 60 of file CacheCounter.h.
References addCacheTags().
Member Function Documentation
addCacheTags()
void util::CacheCounter::addCacheTags (std::initializer_list< CacheTag_t > tags) inline
Adds tags. The ID of existing ones are not changed.
Definition at line 65 of file CacheCounter.h.
References fCacheID, and NoCache.
Referenced by CacheCounter().
cacheID()
CacheID_t util::CacheCounter::cacheID (CacheTag_t const & tag) const inline
Returns the current ID of the cache with the specified tag.
Definition at line 69 of file CacheCounter.h.
References fCacheID.
Referenced by util::CacheGuard::update(), wasCacheUpdatedSince(), and util::CacheGuard::wasUpdated().
hasTag()
bool util::CacheCounter::hasTag (CacheTag_t const & tag) const inline
Returns whether the specified tag is tracked.
Definition at line 72 of file CacheCounter.h.
References fCacheID.
updateCacheID()
CacheID_t util::CacheCounter::updateCacheID (CacheTag_t const & cacheTag = "") const inline protected
Increments the counter of the specified cache tag. The default (empty) tag increments all.
Definition at line 90 of file CacheCounter.h.
References fCacheID.
wasCacheUpdatedSince() [1/2]
bool util::CacheCounter::wasCacheUpdatedSince (CacheID_t sinceID) const inline
Returns whether the default cache was updated since it has sinceID ID.
Definition at line 79 of file CacheCounter.h.
References wasCacheUpdatedSince().
wasCacheUpdatedSince() [2/2]
bool util::CacheCounter::wasCacheUpdatedSince (CacheTag_t const & tag, CacheID_t sinceID) const inline
Returns whether the cache tag was updated since it has sinceID ID.
Definition at line 75 of file CacheCounter.h.
References cacheID().
Referenced by wasCacheUpdatedSince().
Member Data Documentation
fCacheID
std::map<CacheTag_t, std::atomic<CacheID_t> > util::CacheCounter::fCacheID mutable protected
ID of the current caches.
Definition at line 86 of file CacheCounter.h.
Referenced by addCacheTags(), CacheCounter(), cacheID(), hasTag(), and updateCacheID().
NoCache
CacheID_t util::CacheCounter::NoCache = 0 static constexpr
ID specifying that cache is not present yet.
Definition at line 54 of file CacheCounter.h.
Referenced by addCacheTags(), CacheCounter(), util::CacheGuard::chooseCache(), util::CacheGuard::update(), and util::CacheGuard::wasUpdated().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/CacheCounter.h