CAF format: icarus::simfilter::FilterDirts Class Reference
icarus::simfilter::FilterDirts Class Reference
Classes
struct BoxCoordConfig
Configuration of box volume geometry.
struct Config
Configuration parameter structure.
Public Types
using Parameters = art::EDFilter::Table<Config>
Public Member Functions
FilterDirts (Parameters const &config)
Constructor: reads configuration and extracts information from geometry.
virtual bool filter (art::Event &event) override
Framework hook: applies the filter.
virtual void endJob () override
Framework hook: prints the summary of the passed events.
Private Member Functions
void addActiveVolumes ()
Adds all active volumes of detector into the qualifying volume list.
void addVolumeBoxes (fhicl::OptionalSequence< fhicl::Table< BoxCoordConfig > > const &boxConfig)
Adds the specified volumes into the qualifying volume list.
unsigned addVolumeByName (std::string const &volumeName)
Adds all volName from geometry into the qualifying volume list.
bool qualifying (simb::MCTruth const &truth) const
Returns whether the interaction described in truth qualifies.
bool qualifyingLocation (geo::Point_t const &location) const
Returns whether the location is among the accepted ones.
Static Private Member Functions
template<typename Coll >
static Coll sorted (Coll const &coll)
Returns a sorted copy of the specified collection.
Private Attributes
std::vector< geo::BoxBoundedGeo > fVolumes
Volumes for qualifying interactions.
art::InputTag const fTPCchannelTag
sim::SimChannel data product tag.
std::string const fLogCategory
Category name for the output stream.
std::atomic< unsigned int > fNObserved { 0U }
Number of observed events.
std::atomic< unsigned int > fNPassed { 0U }
Number of passed events.
Detailed Description
The filter selects "qualifying" events that:
have interaction vertex outside the active volume or outside specific volumes that can be indicated using the configuration parameters
deposit an energy > 0 (the filter can be improved introducing a threshold that can be set using a configuration parameter)
The event is kept if there is at least one qualifying interaction. In that case, the whole event is passed (including any other interaction). Please note: this class has been created starting from the FilterNeutrinoActive filter
Input
In the input file, there should be the truth MC information and the Geant4 propagation: so run both gen and g4 stages before this filter.
Configuration
Filtering
This is a filter module: its configuration must appear in the filters table and to be included in a path in trigger_path, and the output module must be told to include that path in SelectEvents configuration key; e.g.:
physics: {
  filters: {
    eventActive: @local::icarus_FilterDirts
    # ...
  } # filters
  # ...
  appliedFilters: [ eventActive ]
  trigger_paths: [ appliedFilters ]
} # physics
outputs: {
  rootoutput: {
    module_type:  RootOutput
    fileName:    "%ifb_%tc-%p.root"
    SelectEvents: [ appliedFilters ]
  }
}
Definition at line 113 of file FilterDirts_module.cc.
Class Documentation
icarus::simfilter::FilterDirts::BoxCoordConfig
struct icarus::simfilter::FilterDirts::BoxCoordConfig
Configuration of box volume geometry.
Definition at line 118 of file FilterDirts_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< double > Xmax
Atom< double > Xmin
Atom< double > Ymax
Atom< double > Ymin
Atom< double > Zmax
Atom< double > Zmin
icarus::simfilter::FilterDirts::Config
struct icarus::simfilter::FilterDirts::Config
Configuration parameter structure.
Definition at line 151 of file FilterDirts_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > inActive
Atom< string > logCategory
Atom< InputTag > TPCchannelTag
OptionalSequence< Table< BoxCoordConfig > > volumeBoxes
Sequence< string > volumeNames
Member Typedef Documentation
Parameters
using icarus::simfilter::FilterDirts::Parameters = art::EDFilter::Table<Config>
Definition at line 186 of file FilterDirts_module.cc.
Constructor & Destructor Documentation
FilterDirts()
icarus::simfilter::FilterDirts::FilterDirts (Parameters const & config) explicit
Constructor: reads configuration and extracts information from geometry.
Definition at line 247 of file FilterDirts_module.cc.
References addActiveVolumes(), addVolumeBoxes(), addVolumeByName(), fLogCategory, and fVolumes.
Member Function Documentation
addActiveVolumes()
void icarus::simfilter::FilterDirts::addActiveVolumes () private
Adds all active volumes of detector into the qualifying volume list.
Definition at line 378 of file FilterDirts_module.cc.
Referenced by FilterDirts().
addVolumeBoxes()
void icarus::simfilter::FilterDirts::addVolumeBoxes (fhicl::OptionalSequence< fhicl::Table< BoxCoordConfig > > const & boxConfig) private
Adds the specified volumes into the qualifying volume list.
Definition at line 398 of file FilterDirts_module.cc.
Referenced by FilterDirts().
addVolumeByName()
unsigned int icarus::simfilter::FilterDirts::addVolumeByName (std::string const & volumeName) private
Adds all volName from geometry into the qualifying volume list.
Definition at line 425 of file FilterDirts_module.cc.
Referenced by FilterDirts().
endJob()
void icarus::simfilter::FilterDirts::endJob () override virtual
Framework hook: prints the summary of the passed events.
Definition at line 365 of file FilterDirts_module.cc.
filter()
bool icarus::simfilter::FilterDirts::filter (art::Event & event) override virtual
Framework hook: applies the filter.
Definition at line 287 of file FilterDirts_module.cc.
qualifying()
bool icarus::simfilter::FilterDirts::qualifying (simb::MCTruth const & truth) const private
Returns whether the interaction described in truth qualifies.
Definition at line 509 of file FilterDirts_module.cc.
qualifyingLocation()
bool icarus::simfilter::FilterDirts::qualifyingLocation (geo::Point_t const & location) const private
Returns whether the location is among the accepted ones.
Definition at line 546 of file FilterDirts_module.cc.
sorted()
template<typename Coll > Coll icarus::simfilter::FilterDirts::sorted (Coll const & coll) static private
Returns a sorted copy of the specified collection.
Definition at line 570 of file FilterDirts_module.cc.
Member Data Documentation
fLogCategory
std::string const icarus::simfilter::FilterDirts::fLogCategory private
Category name for the output stream.
Definition at line 205 of file FilterDirts_module.cc.
Referenced by FilterDirts().
fNObserved
std::atomic<unsigned int> icarus::simfilter::FilterDirts::fNObserved { 0U } private
Number of observed events.
Definition at line 212 of file FilterDirts_module.cc.
fNPassed
std::atomic<unsigned int> icarus::simfilter::FilterDirts::fNPassed { 0U } private
Number of passed events.
Definition at line 213 of file FilterDirts_module.cc.
fTPCchannelTag
art::InputTag const icarus::simfilter::FilterDirts::fTPCchannelTag private
sim::SimChannel data product tag.
Definition at line 204 of file FilterDirts_module.cc.
fVolumes
std::vector<geo::BoxBoundedGeo> icarus::simfilter::FilterDirts::fVolumes private
Volumes for qualifying interactions.
Definition at line 203 of file FilterDirts_module.cc.
Referenced by FilterDirts().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Filters/FilterDirts_module.cc