CAF format: icarus::simfilter::FilterNeutrinosActiveVolume Class Reference
icarus::simfilter::FilterNeutrinosActiveVolume Class Reference
Accepts only neutrino-like events with vertices in a specified volume.
Classes
struct BoxCoordConfig
Configuration of box volume geometry.
struct Config
Configuration parameter structure.
Public Types
using Parameters = art::EDFilter::Table<Config>
Public Member Functions
FilterNeutrinosActiveVolume (Parameters const &config)
Constructor: reads configuration and extracts information from geometry.
virtual bool filter (art::Event &event) override
Framework hook: applies the filter.
virtual void endJob () override
Framework hook: prints the summary of the passed events.
Private Member Functions
void addActiveVolumes ()
Adds all active volumes of detector into the qualifying volume list.
void addVolumeBoxes (fhicl::OptionalSequence< fhicl::Table< BoxCoordConfig > > const &boxConfig)
Adds the specified volumes into the qualifying volume list.
unsigned addVolumeByName (std::string const &volumeName)
Adds all volName from geometry into the qualifying volume list.
bool qualifying (simb::MCTruth const &truth) const
Returns whether the interaction described in truth qualifies.
bool qualifyingInteractionType (int const interactionType) const
Returns whether the interaction type is qualifying.
bool qualifyingWeakCurrent (int const CCNC) const
Returns whether the weak current type is qualifying.
bool qualifyingLocation (geo::Point_t const &location) const
Returns whether the location is among the accepted ones.
Static Private Member Functions
template<typename Coll >
static Coll sorted (Coll const &coll)
Returns a sorted copy of the specified collection.
Private Attributes
std::vector< geo::BoxBoundedGeo > fVolumes
Volumes for qualifying interactions.
std::vector< int > const fInteractions
List of qualifying interaction types.
icarus::WeakCurrentType const fWeakCurrentType
Selected weak current.
std::string const fLogCategory
Category name for the output stream.
std::atomic< unsigned int > fNObserved { 0U }
Number of observed events.
std::atomic< unsigned int > fNPassed { 0U }
Number of passed events.
Detailed Description
Accepts only neutrino-like events with vertices in a specified volume.
The module identifies a list of volumes to filter on. The filter selects "qualifying" neutrino interactions that:
have interaction vertex in one of a selected list of volumes
optionally, has a specific interaction type (like in simb::MCNeutrino::InteractionType())
optionally, has a specific current type (see simb::MCNeutrino::CCNC())
The event is kept if there is at least one qualifying interaction. In that case, the whole event is passed (including any other interaction).
Input
Truth information from all data products in the form std::vector<simb::MCTruth> will be evaluated. It is an error for an event to have no such data product (but they can all be empty, in which case the event does not qualify).
Configuration
Parameters
The module can be operated in one of two ways: active volumes or generic. In the active volume mode, all TPC active volumes are used for filtering. In the generic mode, all the specified volumes are used for filtering.
inActive (flag, default: false): if set to true, the "active volume mode" is activated;
volumeBoxes (list of coordinate sets; default: empty): a list of selected volumes is specified as a collection of box coordinates, each one in the form of a table:
Xmin: lower x coordinate
Xmax: upper x coordinate
Ymin: lower y coordinate
Ymax: upper y coordinate
Zmin: lower z coordinate
Zmax: upper z coordinate each coordinate is in centimeters, and in the "world" reference frame
volumeNames (list of strings; default: empty): a list of selected volume patterns is specified as volume names; all volumes in the detector geometry with the specified names are included in the list (for example, specifying volCryostat all cryostats will be included); each pattern is a regular expression like parsed by std::regex with default flags;
interactionTypes (list of integers, optional): if specified, interactions only qualify if they belong to any of these interaction types; see simb::MCNeutrino::InteractionType(), and simb::int_type_ definition for the values and their meanings;
weakCurrent (CC or NC, optional): if specified, interactions qualify only if they are tagged as charged or neutral currents; see icarus::WeakCurrentTypes::parse();
logCategory (string, default: FilterNeutrinosActiveVolume): name of the category this module uses to send messages to the message facility.
It is required that at least one among inActive, volumeNames, volumeBoxes, weakCurrent and interactionTypes are specified.
Filtering
This is a filter module: its configuration must appear in the filters table and to be included in a path in trigger_path, and the output module must be told to include that path in SelectEvents configuration key; e.g.:
physics: {
  filters: {
    eventActive: @local::icarus_FilterNeutrinoActive
    # ...
  } # filters
  # ...
  appliedFilters: [ eventActive ]
  trigger_paths: [ appliedFilters ]
} # physics
outputs: {
  rootoutput: {
    module_type:  RootOutput
    fileName:    "%ifb_%tc-%p.root"
    SelectEvents: [ appliedFilters ]
  }
}
Definition at line 161 of file FilterNeutrinosActiveVolume_module.cc.
Class Documentation
icarus::simfilter::FilterNeutrinosActiveVolume::BoxCoordConfig
struct icarus::simfilter::FilterNeutrinosActiveVolume::BoxCoordConfig
Configuration of box volume geometry.
Definition at line 166 of file FilterNeutrinosActiveVolume_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< double > Xmax
Atom< double > Xmin
Atom< double > Ymax
Atom< double > Ymin
Atom< double > Zmax
Atom< double > Zmin
icarus::simfilter::FilterNeutrinosActiveVolume::Config
struct icarus::simfilter::FilterNeutrinosActiveVolume::Config
Configuration parameter structure.
Definition at line 199 of file FilterNeutrinosActiveVolume_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > inActive
Sequence< int > interactionTypes
Atom< string > logCategory
OptionalSequence< Table< BoxCoordConfig > > volumeBoxes
Sequence< string > volumeNames
Atom< string > weakCurrent
Member Typedef Documentation
Parameters
using icarus::simfilter::FilterNeutrinosActiveVolume::Parameters = art::EDFilter::Table<Config>
Definition at line 244 of file FilterNeutrinosActiveVolume_module.cc.
Constructor & Destructor Documentation
FilterNeutrinosActiveVolume()
icarus::simfilter::FilterNeutrinosActiveVolume::FilterNeutrinosActiveVolume (Parameters const & config) explicit
Constructor: reads configuration and extracts information from geometry.
Definition at line 316 of file FilterNeutrinosActiveVolume_module.cc.
References addActiveVolumes(), addVolumeBoxes(), addVolumeByName(), fInteractions, fLogCategory, fVolumes, and fWeakCurrentType.
Member Function Documentation
addActiveVolumes()
void icarus::simfilter::FilterNeutrinosActiveVolume::addActiveVolumes () private
Adds all active volumes of detector into the qualifying volume list.
Definition at line 445 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
addVolumeBoxes()
void icarus::simfilter::FilterNeutrinosActiveVolume::addVolumeBoxes (fhicl::OptionalSequence< fhicl::Table< BoxCoordConfig > > const & boxConfig) private
Adds the specified volumes into the qualifying volume list.
Definition at line 465 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
addVolumeByName()
unsigned int icarus::simfilter::FilterNeutrinosActiveVolume::addVolumeByName (std::string const & volumeName) private
Adds all volName from geometry into the qualifying volume list.
Definition at line 492 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
endJob()
void icarus::simfilter::FilterNeutrinosActiveVolume::endJob () override virtual
Framework hook: prints the summary of the passed events.
Definition at line 432 of file FilterNeutrinosActiveVolume_module.cc.
filter()
bool icarus::simfilter::FilterNeutrinosActiveVolume::filter (art::Event & event) override virtual
Framework hook: applies the filter.
Definition at line 370 of file FilterNeutrinosActiveVolume_module.cc.
qualifying()
bool icarus::simfilter::FilterNeutrinosActiveVolume::qualifying (simb::MCTruth const & truth) const private
Returns whether the interaction described in truth qualifies.
Definition at line 576 of file FilterNeutrinosActiveVolume_module.cc.
qualifyingInteractionType()
bool icarus::simfilter::FilterNeutrinosActiveVolume::qualifyingInteractionType (int const interactionType) const private
Returns whether the interaction type is qualifying.
Definition at line 624 of file FilterNeutrinosActiveVolume_module.cc.
qualifyingLocation()
bool icarus::simfilter::FilterNeutrinosActiveVolume::qualifyingLocation (geo::Point_t const & location) const private
Returns whether the location is among the accepted ones.
Definition at line 665 of file FilterNeutrinosActiveVolume_module.cc.
qualifyingWeakCurrent()
bool icarus::simfilter::FilterNeutrinosActiveVolume::qualifyingWeakCurrent (int const CCNC) const private
Returns whether the weak current type is qualifying.
Definition at line 642 of file FilterNeutrinosActiveVolume_module.cc.
sorted()
template<typename Coll > Coll icarus::simfilter::FilterNeutrinosActiveVolume::sorted (Coll const & coll) static private
Returns a sorted copy of the specified collection.
Definition at line 689 of file FilterNeutrinosActiveVolume_module.cc.
Member Data Documentation
fInteractions
std::vector<int> const icarus::simfilter::FilterNeutrinosActiveVolume::fInteractions private
List of qualifying interaction types.
Definition at line 264 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
fLogCategory
std::string const icarus::simfilter::FilterNeutrinosActiveVolume::fLogCategory private
Category name for the output stream.
Definition at line 268 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
fNObserved
std::atomic<unsigned int> icarus::simfilter::FilterNeutrinosActiveVolume::fNObserved { 0U } private
Number of observed events.
Definition at line 275 of file FilterNeutrinosActiveVolume_module.cc.
fNPassed
std::atomic<unsigned int> icarus::simfilter::FilterNeutrinosActiveVolume::fNPassed { 0U } private
Number of passed events.
Definition at line 276 of file FilterNeutrinosActiveVolume_module.cc.
fVolumes
std::vector<geo::BoxBoundedGeo> icarus::simfilter::FilterNeutrinosActiveVolume::fVolumes private
Volumes for qualifying interactions.
Definition at line 261 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
fWeakCurrentType
icarus::WeakCurrentType const icarus::simfilter::FilterNeutrinosActiveVolume::fWeakCurrentType private
Selected weak current.
Definition at line 266 of file FilterNeutrinosActiveVolume_module.cc.
Referenced by FilterNeutrinosActiveVolume().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Filters/FilterNeutrinosActiveVolume_module.cc