CAF format: daq::TPCDecoderFilter1D Class Reference
daq::TPCDecoderFilter1D Class Reference
TPCDecoderFilter1D class definiton.
Public Member Functions
TPCDecoderFilter1D (fhicl::ParameterSet const &pset)
Constructor.
~TPCDecoderFilter1D ()
Destructor.
virtual void configure (const fhicl::ParameterSet &) override
Interface for configuring the particular algorithm tool.
virtual void process_fragment (detinfo::DetectorClocksData const &, const artdaq::Fragment &) override
Given a set of recob hits, run DBscan to form 3D clusters.
const icarus_signal_processing::VectorInt getChannelIDs () const override
Recover the channels for the processed fragment.
const icarus_signal_processing::ArrayBool getSelectionVals () const override
Recover the selection values.
const icarus_signal_processing::ArrayBool getROIVals () const override
Recover the ROI values.
const icarus_signal_processing::ArrayFloat getRawWaveforms () const override
Recover the pedestal subtracted waveforms.
const icarus_signal_processing::ArrayFloat getPedCorWaveforms () const override
Recover the pedestal subtracted waveforms.
const icarus_signal_processing::ArrayFloat getIntrinsicRMS () const override
Recover the "intrinsic" RMS.
const icarus_signal_processing::ArrayFloat getCorrectedMedians () const override
Recover the correction median values.
const icarus_signal_processing::ArrayFloat getWaveLessCoherent () const override
Recover the waveforms less coherent noise.
const icarus_signal_processing::ArrayFloat getMorphedWaveforms () const override
Recover the morphological filter waveforms.
const icarus_signal_processing::VectorFloat getPedestalVals () const override
Recover the pedestals for each channel.
const icarus_signal_processing::VectorFloat getFullRMSVals () const override
Recover the full RMS before coherent noise.
const icarus_signal_processing::VectorFloat getTruncRMSVals () const override
Recover the truncated RMS noise.
const icarus_signal_processing::VectorInt getNumTruncBins () const override
Recover the number of bins after truncation.
Public Member Functions inherited from daq::IDecoderFilter
virtual ~IDecoderFilter () noexcept=default
Virtual Destructor.
Private Types
using FloatPairVec = std::vector<std::pair<float,float>>
using FragmentIDPair = std::pair<unsigned int, unsigned int>
using FragmentIDVec = std::vector<FragmentIDPair>
using FragmentIDMap = std::map<unsigned int, unsigned int>
Private Attributes
uint32_t fFragment_id_offset
float fSigmaForTruncation
size_t fCoherentNoiseGrouping
size_t fCoherentNoiseOffset
size_t fStructuringElement
size_t fMorphWindow
std::vector< float > fThreshold
bool fUseFFTFilter
bool fDiagnosticOutput
FloatPairVec fFFTSigmaValsVec
FloatPairVec fFFTCutoffValsVec
std::vector< std::string > fFilterModeVec
FragmentIDMap fFragmentIDMap
icarus_signal_processing::VectorInt fChannelIDVec
icarus_signal_processing::ArrayBool fSelectVals
icarus_signal_processing::ArrayBool fROIVals
icarus_signal_processing::ArrayFloat fRawWaveforms
icarus_signal_processing::ArrayFloat fPedCorWaveforms
icarus_signal_processing::ArrayFloat fIntrinsicRMS
icarus_signal_processing::ArrayFloat fCorrectedMedians
icarus_signal_processing::ArrayFloat fWaveLessCoherent
icarus_signal_processing::ArrayFloat fMorphedWaveforms
icarus_signal_processing::VectorFloat fPedestalVals
icarus_signal_processing::VectorFloat fFullRMSVals
icarus_signal_processing::VectorFloat fTruncRMSVals
icarus_signal_processing::VectorInt fNumTruncBins
icarus_signal_processing::VectorInt fRangeBins
icarus_signal_processing::VectorFloat fThresholdVec
icarus_signal_processing::FilterFunctionVec fFilterFunctionVec
const geo::Geometry * fGeometry
const icarusDB::IICARUSChannelMap * fChannelMap
icarus_signal_processing::FFTFilterFunctionVec fFFTFilterFunctionVec
Detailed Description
TPCDecoderFilter1D class definiton.
Definition at line 44 of file TPCDecoderFilter1D_tool.cc.
Member Typedef Documentation
FloatPairVec
using daq::TPCDecoderFilter1D::FloatPairVec = std::vector<std::pair<float,float>> private
Definition at line 141 of file TPCDecoderFilter1D_tool.cc.
FragmentIDMap
using daq::TPCDecoderFilter1D::FragmentIDMap = std::map<unsigned int, unsigned int> private
Definition at line 159 of file TPCDecoderFilter1D_tool.cc.
FragmentIDPair
using daq::TPCDecoderFilter1D::FragmentIDPair = std::pair<unsigned int, unsigned int> private
Definition at line 157 of file TPCDecoderFilter1D_tool.cc.
FragmentIDVec
using daq::TPCDecoderFilter1D::FragmentIDVec = std::vector<FragmentIDPair> private
Definition at line 158 of file TPCDecoderFilter1D_tool.cc.
Constructor & Destructor Documentation
TPCDecoderFilter1D()
daq::TPCDecoderFilter1D::TPCDecoderFilter1D (fhicl::ParameterSet const & pset) explicit
Constructor.
Parameters
pset
Definition at line 192 of file TPCDecoderFilter1D_tool.cc.
References configure().
~TPCDecoderFilter1D()
daq::TPCDecoderFilter1D::~TPCDecoderFilter1D ()
Destructor.
Definition at line 217 of file TPCDecoderFilter1D_tool.cc.
Member Function Documentation
configure()
void daq::TPCDecoderFilter1D::configure (const fhicl::ParameterSet & pset) override virtual
Interface for configuring the particular algorithm tool.
Parameters
ParameterSet The input set of parameters for configuration
Implements daq::IDecoderFilter.
Definition at line 222 of file TPCDecoderFilter1D_tool.cc.
Referenced by TPCDecoderFilter1D().
getChannelIDs()
const icarus_signal_processing::VectorInt daq::TPCDecoderFilter1D::getChannelIDs () const inline override virtual
Recover the channels for the processed fragment.
Implements daq::IDecoderFilter.
Definition at line 77 of file TPCDecoderFilter1D_tool.cc.
getCorrectedMedians()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getCorrectedMedians () const inline override virtual
Recover the correction median values.
Implements daq::IDecoderFilter.
Definition at line 107 of file TPCDecoderFilter1D_tool.cc.
getFullRMSVals()
const icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::getFullRMSVals () const inline override virtual
Recover the full RMS before coherent noise.
Implements daq::IDecoderFilter.
Definition at line 127 of file TPCDecoderFilter1D_tool.cc.
getIntrinsicRMS()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getIntrinsicRMS () const inline override virtual
Recover the "intrinsic" RMS.
Implements daq::IDecoderFilter.
Definition at line 102 of file TPCDecoderFilter1D_tool.cc.
getMorphedWaveforms()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getMorphedWaveforms () const inline override virtual
Recover the morphological filter waveforms.
Implements daq::IDecoderFilter.
Definition at line 117 of file TPCDecoderFilter1D_tool.cc.
getNumTruncBins()
const icarus_signal_processing::VectorInt daq::TPCDecoderFilter1D::getNumTruncBins () const inline override virtual
Recover the number of bins after truncation.
Implements daq::IDecoderFilter.
Definition at line 137 of file TPCDecoderFilter1D_tool.cc.
getPedCorWaveforms()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getPedCorWaveforms () const inline override virtual
Recover the pedestal subtracted waveforms.
Implements daq::IDecoderFilter.
Definition at line 97 of file TPCDecoderFilter1D_tool.cc.
getPedestalVals()
const icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::getPedestalVals () const inline override virtual
Recover the pedestals for each channel.
Implements daq::IDecoderFilter.
Definition at line 122 of file TPCDecoderFilter1D_tool.cc.
getRawWaveforms()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getRawWaveforms () const inline override virtual
Recover the pedestal subtracted waveforms.
Implements daq::IDecoderFilter.
Definition at line 92 of file TPCDecoderFilter1D_tool.cc.
getROIVals()
const icarus_signal_processing::ArrayBool daq::TPCDecoderFilter1D::getROIVals () const inline override virtual
Recover the ROI values.
Implements daq::IDecoderFilter.
Definition at line 87 of file TPCDecoderFilter1D_tool.cc.
getSelectionVals()
const icarus_signal_processing::ArrayBool daq::TPCDecoderFilter1D::getSelectionVals () const inline override virtual
Recover the selection values.
Implements daq::IDecoderFilter.
Definition at line 82 of file TPCDecoderFilter1D_tool.cc.
getTruncRMSVals()
const icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::getTruncRMSVals () const inline override virtual
Recover the truncated RMS noise.
Implements daq::IDecoderFilter.
Definition at line 132 of file TPCDecoderFilter1D_tool.cc.
getWaveLessCoherent()
const icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::getWaveLessCoherent () const inline override virtual
Recover the waveforms less coherent noise.
Implements daq::IDecoderFilter.
Definition at line 112 of file TPCDecoderFilter1D_tool.cc.
process_fragment()
void daq::TPCDecoderFilter1D::process_fragment (detinfo::DetectorClocksData const & , const artdaq::Fragment & fragment) override virtual
Given a set of recob hits, run DBscan to form 3D clusters.
Parameters
fragment The artdaq fragment to process
Implements daq::IDecoderFilter.
Definition at line 263 of file TPCDecoderFilter1D_tool.cc.
References icarusDB::IICARUSChannelMapProvider::getBoardSlot(), icarusDB::IICARUSChannelMapProvider::getChannelPlanePair(), icarusDB::IICARUSChannelMapProvider::getCrateName(), icarusDB::IICARUSChannelMapProvider::getReadoutBoardVec(), icarusDB::IICARUSChannelMapProvider::hasBoardID(), and icarusDB::IICARUSChannelMapProvider::hasFragmentID().
Member Data Documentation
fChannelIDVec
icarus_signal_processing::VectorInt daq::TPCDecoderFilter1D::fChannelIDVec private
Definition at line 164 of file TPCDecoderFilter1D_tool.cc.
fChannelMap
const icarusDB::IICARUSChannelMap* daq::TPCDecoderFilter1D::fChannelMap private
Definition at line 185 of file TPCDecoderFilter1D_tool.cc.
fCoherentNoiseGrouping
size_t daq::TPCDecoderFilter1D::fCoherentNoiseGrouping private
Definition at line 145 of file TPCDecoderFilter1D_tool.cc.
fCoherentNoiseOffset
size_t daq::TPCDecoderFilter1D::fCoherentNoiseOffset private
Definition at line 146 of file TPCDecoderFilter1D_tool.cc.
fCorrectedMedians
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fCorrectedMedians private
Definition at line 170 of file TPCDecoderFilter1D_tool.cc.
fDiagnosticOutput
bool daq::TPCDecoderFilter1D::fDiagnosticOutput private
Definition at line 151 of file TPCDecoderFilter1D_tool.cc.
fFFTCutoffValsVec
FloatPairVec daq::TPCDecoderFilter1D::fFFTCutoffValsVec private
Definition at line 153 of file TPCDecoderFilter1D_tool.cc.
fFFTFilterFunctionVec
icarus_signal_processing::FFTFilterFunctionVec daq::TPCDecoderFilter1D::fFFTFilterFunctionVec private
Definition at line 188 of file TPCDecoderFilter1D_tool.cc.
fFFTSigmaValsVec
FloatPairVec daq::TPCDecoderFilter1D::fFFTSigmaValsVec private
Definition at line 152 of file TPCDecoderFilter1D_tool.cc.
fFilterFunctionVec
icarus_signal_processing::FilterFunctionVec daq::TPCDecoderFilter1D::fFilterFunctionVec private
Definition at line 182 of file TPCDecoderFilter1D_tool.cc.
fFilterModeVec
std::vector<std::string> daq::TPCDecoderFilter1D::fFilterModeVec private
Definition at line 155 of file TPCDecoderFilter1D_tool.cc.
fFragment_id_offset
uint32_t daq::TPCDecoderFilter1D::fFragment_id_offset private
Definition at line 143 of file TPCDecoderFilter1D_tool.cc.
fFragmentIDMap
FragmentIDMap daq::TPCDecoderFilter1D::fFragmentIDMap private
Definition at line 161 of file TPCDecoderFilter1D_tool.cc.
fFullRMSVals
icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::fFullRMSVals private
Definition at line 175 of file TPCDecoderFilter1D_tool.cc.
fGeometry
const geo::Geometry* daq::TPCDecoderFilter1D::fGeometry private
Definition at line 184 of file TPCDecoderFilter1D_tool.cc.
fIntrinsicRMS
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fIntrinsicRMS private
Definition at line 169 of file TPCDecoderFilter1D_tool.cc.
fMorphedWaveforms
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fMorphedWaveforms private
Definition at line 172 of file TPCDecoderFilter1D_tool.cc.
fMorphWindow
size_t daq::TPCDecoderFilter1D::fMorphWindow private
Definition at line 148 of file TPCDecoderFilter1D_tool.cc.
fNumTruncBins
icarus_signal_processing::VectorInt daq::TPCDecoderFilter1D::fNumTruncBins private
Definition at line 177 of file TPCDecoderFilter1D_tool.cc.
fPedCorWaveforms
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fPedCorWaveforms private
Definition at line 168 of file TPCDecoderFilter1D_tool.cc.
fPedestalVals
icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::fPedestalVals private
Definition at line 174 of file TPCDecoderFilter1D_tool.cc.
fRangeBins
icarus_signal_processing::VectorInt daq::TPCDecoderFilter1D::fRangeBins private
Definition at line 178 of file TPCDecoderFilter1D_tool.cc.
fRawWaveforms
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fRawWaveforms private
Definition at line 167 of file TPCDecoderFilter1D_tool.cc.
fROIVals
icarus_signal_processing::ArrayBool daq::TPCDecoderFilter1D::fROIVals private
Definition at line 166 of file TPCDecoderFilter1D_tool.cc.
fSelectVals
icarus_signal_processing::ArrayBool daq::TPCDecoderFilter1D::fSelectVals private
Definition at line 165 of file TPCDecoderFilter1D_tool.cc.
fSigmaForTruncation
float daq::TPCDecoderFilter1D::fSigmaForTruncation private
Definition at line 144 of file TPCDecoderFilter1D_tool.cc.
fStructuringElement
size_t daq::TPCDecoderFilter1D::fStructuringElement private
Definition at line 147 of file TPCDecoderFilter1D_tool.cc.
fThreshold
std::vector<float> daq::TPCDecoderFilter1D::fThreshold private
Definition at line 149 of file TPCDecoderFilter1D_tool.cc.
fThresholdVec
icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::fThresholdVec private
Definition at line 180 of file TPCDecoderFilter1D_tool.cc.
fTruncRMSVals
icarus_signal_processing::VectorFloat daq::TPCDecoderFilter1D::fTruncRMSVals private
Definition at line 176 of file TPCDecoderFilter1D_tool.cc.
fUseFFTFilter
bool daq::TPCDecoderFilter1D::fUseFFTFilter private
Definition at line 150 of file TPCDecoderFilter1D_tool.cc.
fWaveLessCoherent
icarus_signal_processing::ArrayFloat daq::TPCDecoderFilter1D::fWaveLessCoherent private
Definition at line 171 of file TPCDecoderFilter1D_tool.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/TPCDecoderFilter1D_tool.cc