CAF format: icarus::opdet::SimPMTreadout Class Reference
icarus::opdet::SimPMTreadout Class Reference
Simulates the digitization of ICARUS PMT response including readout.
Classes
struct Config
Module configuration interface.
class PrimitiveManager
Tracks the required primitives per optical detector channel.
struct ReadoutParams_t
Configuration parameters for PMT readout.
class WaveformManager
Class to manage the input waveforms.
Public Types
using microseconds = util::quantities::intervals::microseconds
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
SimPMTreadout (Parameters const &config)
void produce (art::Event &event) override
Private Types
using electronics_time = detinfo::timescales::electronics_time
using TriggerBits_t = decltype(std::declval<raw::Trigger>().TriggerBits())
Type of trigger bits supported by raw::Trigger.
using nanoseconds = util::quantities::intervals::nanoseconds
using PedestalGenerator_t = icarus::opdet::PMTpedestalGeneratorTool::Generator_t
Type of the pedestal and electronics noise generator algorithm.
template<typename Data , typename... AssnsTo>
using DataAndAssns = std::tuple<std::vector<Data>, art::Assns<Data, AssnsTo>...>
Type of data product and its association(s).
using Window_t = PMTReadoutWindowMaker<electronics_time>::Window_t
Private Member Functions
void addLocalPrimitives (PrimitiveManager &manager, std::vector< raw::Trigger > const &primitives) const
Registers local primitives (affecting only part of the detector).
void addGlobalPrimitives (PrimitiveManager &manager, std::vector< raw::Trigger > const &primitives) const
Registers global primitives (affecting the whole detector).
std::vector< raw::OpDetWaveform > makeWaveforms (raw::Channel_t channel, std::uint64_t beamGateTimestamp, std::vector< raw::OpDetWaveform const * > const &source, std::vector< Window_t > const &readoutWindows) const
DataAndAssns< sbn::OpDetWaveformMeta, raw::OpDetWaveform > makeWaveformMetadata (std::vector< raw::OpDetWaveform > const &waveforms, detinfo::DetectorTimings const &detTimings, art::Event const &event) const
Creates waveform metadata and associations for all waveforms.
std::vector< geo::CryostatID > cryostatsOf (raw::Trigger const &trigger) const
Returns which cryostats the trigger belongs to (invalid if none/unknown).
Private Attributes
std::vector< art::InputTag > const fWaveformTags
Input tags for already digitized waveforms.
std::vector< art::InputTag > const fPrimitiveTags
Input tags for trigger primitives.
std::vector< art::InputTag > const fTriggerTags
Input tags for additional global triggers.
std::vector< microseconds > const fFixedTriggerTimes
Time of the added, artificial global triggers.
ReadoutParams_t const fReadoutParams
PMT readout parameters.
TriggerBits_t const fCryostatZeroMask
Bit mask for cryostat 0.
std::string const fLogCategory
Message facility category name.
geo::GeometryCore const & fGeom
Geometry service provider.
detinfo::DetectorTimings const fDetTimings
Timing conversion utility.
unsigned int const fNOpChannels
Number of optical detector channels.
unsigned int const fNCryostats
Number of cryostats in the detector.
nanoseconds const fOpticalTick
PMT digitization sampling time.
CLHEP::HepRandomEngine & fNoiseGeneratorEngine
Random engine for the electronics noise generation algorithm.
std::unique_ptr< PedestalGenerator_t > const fPedestalGenerator
Pedestal and electronics noise generation algorithm.
Static Private Attributes
static constexpr std::size_t NTriggerBits = sizeof(TriggerBits_t) * 8U
Number of bits supported by raw::Trigger.
Detailed Description
Simulates the digitization of ICARUS PMT response including readout.
This module operates on top of already digitised PMT waveforms, with the purpose of simulating the effect of the selective readout of ICARUS PMT system.
In the detector, PMT signals are first digitised and discriminated in real time, then combined to determine trigger primitives. When a trigger primitive is formed, it causes the PMT readout board to actually save the PMT information.
In the simulation, this is done in steps:
Digitization occurs first based on scintillation photons which converted at the PMT surface; this is the task of icarus::opdet::SimPMTIcarus module, which creates raw::OpDetWaveform with all scintillation signal (except that a low threshold is used), including noise.
Trigger primitives are determined based on the waveforms from the previous step. This task can be performed by the proper configuration of icarus::trigger::TriggerSimulationOnGates module.
Finally, the trigger primitives are used to determine the time intervals and the channels when and where the readout happens, and new waveforms are created combining the samples from the waveforms in the first step.
Readout details
The current implementation operates mimicking the ICARUS PMT and triger systems, although the delays are not simulated.
Trigger primitives are expected to be generated with a time, precise at the PMT sample (2 nanoseconds), and a location, precise at the cryostat (conceivably it could be precise at the TPC, but currently the trigger compbines the two TPC in a cryostat).
Optical detector waveforms used as input are expected to already contain all the signal.
Readout parameters are learned from the module configuration, as well as the noise parameters.
Artificial trigger primitives are added to reflect the ones sent by the hardware to ensure coverage of the beam gate time (see Readout during beam gate below).
For each trigger primitive, all PMT in the primitive cryostat are read out, with a time interval extending before the trigger primitive time by the amount of configured pre-trigger buffer, and with a fixed duration.
Contiguous buffers are merged in a single waveform.
Waveform content creation
The algorithm proceeds with the following steps:
Read all the trigger primitives from input.
Generate additional, artificial trigger primitives as requested in the configuration (see Readout during beam gate below)
Surround each trigger primitive with a readout buffer interval, and determine the final readout intervals for all channels and waveforms. A single channel will have multiple intervals, and each interval will generate a waveform.
For each interval, the source waveform data is copied into the new one. If there are times that are uncovered, the noise generator is tasked to full the gaps.
It is assumed that the noise will not contribute to further trigger primitives. This is a solid assumption, considering that the noise is added only on top of the baseline (no signal present), and that the noise is two orders of magnitude smaller than the discrimination threshold the trigger primitives utilize.
Readout during beam gate
The trigger hardware is configured to always send a sequence of artificial trigger primitives at around the time the beam gate is expected. For example, in ICARUS Run1 three trigger primitives were sent to all the PMT readout boards (i.e. triggering the readout of all 360 channels) at the times of -4, +3 and +12 microseconds from the beam gate (which is also the time the trigger hardware opens the gate to form a global trigger). This, combined with a readout buffer of 10 microseconds, 3 before the trigger primitive signal and 7 after it, would ensure the coverage by the PMT of 26 microseconds, from -7 to +19 with respect to the beam gate, and therefore a coverage of 7 microseconds before any beam interaction to more than 9 microseconds after the latest of NuMI neutrino possible interaction.
In addition, a trigger primitive is still sent at the time of the global trigger; with the aforementioned configuration, though, this does not add any time coverage to the PMT.
Noise generation and absolute event time
A noise generator is necessary to extend the waveforms to intervals where no original samples are available (as a reminder: the simulation fills a narrow region of waveform around any minor activity, while the detector readout acquires all PMT in a cryostat even when just a few of them show activity). Noise generation is delegated to an algorithm belonging to icarus::opdet::NoiseGeneratorAlg class. This class of generators may in principle generate noise specific to a channel and to a certain data acquisition time, and they require such information to be provided to them. We have two options to learn about the absolute time of the event: from a trigger object (sbn::ExtraTriggerInfo is produced by the trigger emulation) from the time of the event generation. In general, the status as of December 2022 in ICARUS is that no noise generator actually uses that information, we don't have automatically accessible records of different PMT noise conditions as function of time, and the Monte Carlo production is not set up to reflect any specific data taking condition. As a consequence, not only the choice here is largely irrelevant, but it's also not possible to make one that is "future-proof". The current implementation of this module utilizes the latter approach, of using the event time, because it's the simplest and least demanding; the former might be made optional too (for example, extracting the timestamp from the sbn::ExtraTriggerInfo data product matching the first of the TriggerTags tags).
Configuration
The configuration is also available with the usual lar --print-description SimPMTreadout.
WaveformTags (list of input tags, mandatory): list of data products with the waveform samples to be arranged in the new waveforms.
PrimitiveTags (list of input tags, mandatory): list of trigger primitive data products to seed the PMT readout with.
TriggerTags (list of input tags, default: empty): list of global triggers contributing additional trigger primitives to the whole detector.
FixedTriggerTimes (list of times, optional): adds a global trigger (in the same fashion as the ones from TriggerTags collections) to the times specified in this list. Times here are relative to the beam gate opening time.
Readout (table, mandatory): readout settings:
WindowSize (integer, mandatory): the size of a readout buffer in optical ticks.
PreTrigFraction (real, mandatory): the fraction of the readout buffer that is collected before the trigger primitive (e.g. a fraction 0.3 over a buffer of 5000 samples will have 1500 samples before the trigger primitive, and the remaining 3500 starting from the primitive time on).
Pedestal (tool configuration table): configuration of the tool used to generate pedestal and noise in the intervals where no source samples are available. The tool is one derived from icarus::opdet::PMTpedestalGeneratorTool. The recommendation is to use the same generator and parameters as used in the original simulation. even if no noise addition is desired.
NoiseGeneratorSeed (integer, optional): if specified, the value is used to seed the noise generation algorithm random engine; otherwise, the seed is assigned by NuRandomService.
CryostatFirstBit (positive integer, mandatory): the trigger bit which is set on input triggers from cryostat 0; as many bits are expected as there are cryostats in the detector (thus, 2 for ICARUS). The value 0 represents the least significant bit.
LogCategory (string, default: SimPMTreadout): message facility category to which the module messages are routed.
Input
std::vector<raw::Trigger> (PrimitiveTags): collection of trigger primitives. Each object must encode the location of the primitive in its trigger bits (see CryostatFirstBit configuration parameter).
std::vector<raw::Trigger> (optional, TriggerTags): collections of global triggers; each global trigger will count as a trigger primitive for each cryostat. All triggers in all data products are added.
std::vector<raw::OpDetWaveform> (WaveformTags): PMT waveforms already digitized, source of the data for the new ones.
Output
std::vector<raw::OpDetWaveform> with the rearranged readout samples. They are sorted by channel, then by time, like in the output of icarus::opdet::SimPMTIcarus module.
std::vector<sbn::OpDetWaveformMeta> and associations with the optical waveform data product, with "summary" informations about each waveform.
Requirements
This module currently requires LArSoft services:
Geometry for discovery of optical detector channels and their cryostat;
DetectorClocksService for timing conversions and settings;
NuRandomService for the noise generation (even if a non-stochastic generator is chosen).
Definition at line 267 of file SimPMTreadout_module.cc.
Class Documentation
icarus::opdet::SimPMTreadout::Config
struct icarus::opdet::SimPMTreadout::Config
Module configuration interface.
Definition at line 294 of file SimPMTreadout_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< unsigned int > CryostatFirstBit
Sequence< microseconds > FixedTriggerTimes
Atom< string > LogCategory
SeedAtom NoiseGeneratorSeed
DelegatedParameter Pedestal
Sequence< InputTag > PrimitiveTags
TableAs< ReadoutParams_t, ReadoutConfig > Readout
Sequence< InputTag > TriggerTags
Sequence< InputTag > WaveformTags
Member Typedef Documentation
DataAndAssns
template<typename Data , typename... AssnsTo> using icarus::opdet::SimPMTreadout::DataAndAssns = std::tuple<std::vector<Data>, art::Assns<Data, AssnsTo>...> private
Type of data product and its association(s).
Definition at line 386 of file SimPMTreadout_module.cc.
electronics_time
using icarus::opdet::SimPMTreadout::electronics_time = detinfo::timescales::electronics_time private
Definition at line 269 of file SimPMTreadout_module.cc.
microseconds
using icarus::opdet::SimPMTreadout::microseconds = util::quantities::intervals::microseconds
Definition at line 279 of file SimPMTreadout_module.cc.
nanoseconds
using icarus::opdet::SimPMTreadout::nanoseconds = util::quantities::intervals::nanoseconds private
Definition at line 379 of file SimPMTreadout_module.cc.
Parameters
using icarus::opdet::SimPMTreadout::Parameters = art::EDProducer::Table<Config>
Definition at line 369 of file SimPMTreadout_module.cc.
PedestalGenerator_t
using icarus::opdet::SimPMTreadout::PedestalGenerator_t = icarus::opdet::PMTpedestalGeneratorTool::Generator_t private
Type of the pedestal and electronics noise generator algorithm.
Definition at line 382 of file SimPMTreadout_module.cc.
TriggerBits_t
using icarus::opdet::SimPMTreadout::TriggerBits_t = decltype(std::declval<raw::Trigger>().TriggerBits()) private
Type of trigger bits supported by raw::Trigger.
Definition at line 272 of file SimPMTreadout_module.cc.
Window_t
using icarus::opdet::SimPMTreadout::Window_t = PMTReadoutWindowMaker<electronics_time>::Window_t private
Definition at line 460 of file SimPMTreadout_module.cc.
Constructor & Destructor Documentation
SimPMTreadout()
icarus::opdet::SimPMTreadout::SimPMTreadout (Parameters const & config) explicit
Definition at line 719 of file SimPMTreadout_module.cc.
Member Function Documentation
addGlobalPrimitives()
void icarus::opdet::SimPMTreadout::addGlobalPrimitives (PrimitiveManager & manager, std::vector< raw::Trigger > const & primitives) const private
Registers global primitives (affecting the whole detector).
Definition at line 957 of file SimPMTreadout_module.cc.
References icarus::opdet::SimPMTreadout::PrimitiveManager::addPrimitiveToAllChannels(), and fLogCategory.
addLocalPrimitives()
void icarus::opdet::SimPMTreadout::addLocalPrimitives (PrimitiveManager & manager, std::vector< raw::Trigger > const & primitives) const private
Registers local primitives (affecting only part of the detector).
Definition at line 932 of file SimPMTreadout_module.cc.
References icarus::opdet::SimPMTreadout::PrimitiveManager::addPrimitiveForCryostat(), cryostatsOf(), and fLogCategory.
cryostatsOf()
std::vector< geo::CryostatID > icarus::opdet::SimPMTreadout::cryostatsOf (raw::Trigger const & trigger) const private
Returns which cryostats the trigger belongs to (invalid if none/unknown).
Definition at line 913 of file SimPMTreadout_module.cc.
References fCryostatZeroMask, and fNCryostats.
Referenced by addLocalPrimitives().
makeWaveformMetadata()
auto icarus::opdet::SimPMTreadout::makeWaveformMetadata (std::vector< raw::OpDetWaveform > const & waveforms, detinfo::DetectorTimings const & detTimings, art::Event const & event) const private
Creates waveform metadata and associations for all waveforms.
Definition at line 1197 of file SimPMTreadout_module.cc.
makeWaveforms()
std::vector< raw::OpDetWaveform > icarus::opdet::SimPMTreadout::makeWaveforms (raw::Channel_t channel, std::uint64_t beamGateTimestamp, std::vector< raw::OpDetWaveform const * > const & source, std::vector< Window_t > const & readoutWindows) const private
Creates waveforms on a single channel, filling the specified readout windows, from the samples in source waveforms.
Definition at line 979 of file SimPMTreadout_module.cc.
References fDetTimings, fOpticalTick, and fPedestalGenerator.
produce()
void icarus::opdet::SimPMTreadout::produce (art::Event & event) override
Definition at line 832 of file SimPMTreadout_module.cc.
Member Data Documentation
fCryostatZeroMask
TriggerBits_t const icarus::opdet::SimPMTreadout::fCryostatZeroMask private
Bit mask for cryostat 0.
Definition at line 478 of file SimPMTreadout_module.cc.
Referenced by cryostatsOf().
fDetTimings
detinfo::DetectorTimings const icarus::opdet::SimPMTreadout::fDetTimings private
Timing conversion utility.
Definition at line 488 of file SimPMTreadout_module.cc.
Referenced by makeWaveforms().
fFixedTriggerTimes
std::vector<microseconds> const icarus::opdet::SimPMTreadout::fFixedTriggerTimes private
Time of the added, artificial global triggers.
Definition at line 474 of file SimPMTreadout_module.cc.
fGeom
geo::GeometryCore const& icarus::opdet::SimPMTreadout::fGeom private
Geometry service provider.
Definition at line 487 of file SimPMTreadout_module.cc.
fLogCategory
std::string const icarus::opdet::SimPMTreadout::fLogCategory private
Message facility category name.
Definition at line 480 of file SimPMTreadout_module.cc.
Referenced by addGlobalPrimitives(), and addLocalPrimitives().
fNCryostats
unsigned int const icarus::opdet::SimPMTreadout::fNCryostats private
Number of cryostats in the detector.
Definition at line 491 of file SimPMTreadout_module.cc.
Referenced by cryostatsOf().
fNoiseGeneratorEngine
CLHEP::HepRandomEngine& icarus::opdet::SimPMTreadout::fNoiseGeneratorEngine private
Random engine for the electronics noise generation algorithm.
Definition at line 496 of file SimPMTreadout_module.cc.
fNOpChannels
unsigned int const icarus::opdet::SimPMTreadout::fNOpChannels private
Number of optical detector channels.
Definition at line 490 of file SimPMTreadout_module.cc.
fOpticalTick
nanoseconds const icarus::opdet::SimPMTreadout::fOpticalTick private
PMT digitization sampling time.
Definition at line 493 of file SimPMTreadout_module.cc.
Referenced by makeWaveforms().
fPedestalGenerator
std::unique_ptr<PedestalGenerator_t> const icarus::opdet::SimPMTreadout::fPedestalGenerator private
Pedestal and electronics noise generation algorithm.
Definition at line 501 of file SimPMTreadout_module.cc.
Referenced by makeWaveforms().
fPrimitiveTags
std::vector<art::InputTag> const icarus::opdet::SimPMTreadout::fPrimitiveTags private
Input tags for trigger primitives.
Definition at line 468 of file SimPMTreadout_module.cc.
fReadoutParams
ReadoutParams_t const icarus::opdet::SimPMTreadout::fReadoutParams private
PMT readout parameters.
Definition at line 476 of file SimPMTreadout_module.cc.
fTriggerTags
std::vector<art::InputTag> const icarus::opdet::SimPMTreadout::fTriggerTags private
Input tags for additional global triggers.
Definition at line 471 of file SimPMTreadout_module.cc.
fWaveformTags
std::vector<art::InputTag> const icarus::opdet::SimPMTreadout::fWaveformTags private
Input tags for already digitized waveforms.
Definition at line 465 of file SimPMTreadout_module.cc.
NTriggerBits
std::size_t icarus::opdet::SimPMTreadout::NTriggerBits = sizeof(TriggerBits_t) * 8U static constexpr private
Number of bits supported by raw::Trigger.
Definition at line 275 of file SimPMTreadout_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/SimPMTreadout_module.cc