CAF format: icaruscode/icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.h File Reference
CRTPMTMatchingUtils.h File Reference
Common functions for CRT/PMT matching.
#include "sbnobj/Common/CRT/CRTPMTMatching.hh"
#include "larcoreobj/SimpleTypesAndConstants/geo_vectors.h"
#include "sbnobj/Common/CRT/CRTHit.hh"
#include "canvas/Persistency/Common/Ptr.h"
#include <vector>
Classes
struct icarus::crt::CRTPMT
struct icarus::crt::CRTMatches
Contains vectors of records with matched Time of Flight and matched CRTHit.
struct sbn::crt::FlashType
Namespaces
namespace recob
Reconstruction base classes.
namespace icarus
Cluster finding and building.
namespace sbn
Set of values to identify a beam.
Functions
bool icarus::crt::flashInTime (double flashTime, int gateType, double gateDiff, double gateWidth)
Returns whether a flash is in time with the specified gate.
double icarus::crt::CRTHitTime (sbn::crt::CRTHit const &hit, double globalT0Offset, bool isRealData)
Returns the relative time of a CRT hit [ns].
CRTMatches icarus::crt::CRTHitmatched (double flashTime, geo::Point_t const &flashpos, std::vector< art::Ptr< sbn::crt::CRTHit > > &crtHits, double interval, bool isRealData, double globalT0Offset, bool matchBottomCRT)
Returns all the CRT hits matching the specified flash time.
int icarus::crt::makeFlashID (recob::OpFlash const &flash, int version=std::numeric_limits< int >::max())
Returns an unique ID for the flash in ptr.
int icarus::crt::makeFlashID (recob::OpFlash const *flash, int version=std::numeric_limits< int >::max())
CRTPMTMatching sbn::crt::FillCRTPMT (FlashType const &flash)
Fills a CRTPMTMatching record out of the specified flash information.
Detailed Description
Common functions for CRT/PMT matching.
Author
Francesco Poppi (poppi@bo.infn.it) and Anna Heggestuen (aheggest@colostate.edu)
Date
April 26 2023.
See also
icaruscode/CRT/CRTUtils/CRTPMTMatchingUtils.cxx
Definition in file CRTPMTMatchingUtils.h.
Function Documentation
CRTHitmatched()
icarus::crt::CRTMatches icarus::crt::CRTHitmatched (double flashTime, geo::Point_t const & flashpos, std::vector< art::Ptr< sbn::crt::CRTHit > > & crtHits, double interval, bool isRealData, double globalT0Offset, bool matchBottomCRT)
Returns all the CRT hits matching the specified flash time.
Parameters
flashTime the time of the flash to be matched [us]
flashpos nominal position of the flash source [cm]
crtHits list of the CRT hits to consider
interval time difference for matching flash and hit [ns]
isRealData true for detector data, false for simulation
globalT0Offset CRT timing offset [ns]
Returns
a CRTMatches record with information about all the matched hits
Hits are separated between entering (before the flash) and exiting (after the flash). The match is tagged according to how many entering and exiting hits are found, and where.
Definition at line 50 of file CRTPMTMatchingUtils.cxx.
References icarus::crt::CRTHitmatched(), icarus::crt::CRTHitTime(), and icarus::distance().
Referenced by icarus::crt::CRTHitmatched().
CRTHitTime()
double icarus::crt::CRTHitTime (sbn::crt::CRTHit const & hit, double globalT0Offset, bool isRealData)
Returns the relative time of a CRT hit [ns].
Parameters
hit the CRT hit
globalT0Offset for simulation, the global T0 offset in nanoseconds
isRealData whether the hit is from data (as opposed to simulation)
Returns
the time of the hit [ns]
For data hits, the time is directly taken from the timestamp 1 (ts1_ns). For simulation, the time is taken from the "absolute" timestamp 0 (ts0()) after subtracting a known offset (globalT0Offset).
Definition at line 41 of file CRTPMTMatchingUtils.cxx.
References icarus::crt::CRTHitTime(), and sbn::crt::CRTHit::ts1_ns.
Referenced by icarus::crt::CRTHitmatched(), and icarus::crt::CRTHitTime().
FillCRTPMT()
sbn::crt::CRTPMTMatching sbn::crt::FillCRTPMT (FlashType const & flash)
Fills a CRTPMTMatching record out of the specified flash information.
Definition at line 123 of file CRTPMTMatchingUtils.cxx.
References sbn::crt::FillCRTPMT(), sbn::crt::CRTPMTMatching::flashPosition, and sbn::crt::CRTPMTMatching::matchedCRTHits.
Referenced by sbn::crt::FillCRTPMT().
flashInTime()
bool icarus::crt::flashInTime (double flashTime, int gateType, double gateDiff, double gateWidth)
Returns whether a flash is in time with the specified gate.
Parameters
flashTime time of the flash, in trigger time scale [us] " fill in for new vars "
gateType type of the gate [unused]
gateDiff time offset between PMT flashes and beam gate opening time [ns]
gateWidth the duration of the gate opening [us]
Returns
whether flashTime is included the gate of specified duration
The gateDiff offset represents the delay observed from the reconstructed time for a flash that happens exactly at the opening of the beam gate, and the opening time of the beam gate as reported by the trigger system. Due to delays on the trigger decision after the digitization of the PMT signals happened, this offset is typically larger than zero.
Note
With Monte Carlo conventions, gateDiff needs to be 0 since the flash time is already in beam gate time scale rather than trigger's.
Definition at line 24 of file CRTPMTMatchingUtils.cxx.
References icarus::crt::flashInTime().
Referenced by icarus::crt::flashInTime().
makeFlashID() [1/2]
int icarus::crt::makeFlashID (recob::OpFlash const & flash, int version = std::numeric_limits<int>::max())
Returns an unique ID for the flash in ptr.
Parameters
flash a flash or its pointer
version (default: latest) the ID creation algorithm version to use
Returns
an unique ID for the flash in ptr
An ID is made up out of the flash.
Supported versions:
10: ID is the flash time in picoseconds, rounded; icarus::crt::CRTPMTMatching::NoID if flash is invalid (e.g. null pointer)
Definition at line 151 of file CRTPMTMatchingUtils.cxx.
References icarus::crt::makeFlashID().
Referenced by icarus::crt::makeFlashID().
makeFlashID() [2/2]
int icarus::crt::makeFlashID (recob::OpFlash const * flash, int version = std::numeric_limits<int>::max())
Definition at line 158 of file CRTPMTMatchingUtils.cxx.