CAF format: icarus Namespace Reference
icarus Namespace Reference
Cluster finding and building.
Namespaces
namespace geo
Detector geometry algorithms for ICARUS.
namespace opdet
Optical detector simulation for ICARUS.
namespace trigger
Trigger simulation for ICARUS.
Classes
class AnalysisTree
Creates a simple ROOT tree with tracking and calorimetry information.
class AnalysisTreeDataStruct
struct CathodeCrossing_t
Information about the cathode crossing of a path.
struct CathodeDesc_t
Simple description for the cathode.
class CopyBeamTimePMTwaveforms
Creates a new list of PMT waveforms covering the specified time.
class CRTT0MatchAlg
class CRTT0Matching
class CRTT0MatchingAna
class CRTTPCMatchingAna
struct CRTTPCMatchingInfo
Additional information on the matching between CRT and TPC tracks.
class CRTTPCTruthEff
class CRTTzeroProducer
class DaqDecoderICARUSPMT
Produces raw::OpDetWaveform from V1730 artDAQ data fragments.
struct dumpChannel
class FlashResAna
class Hit
2D representation of charge deposited in the TDC/wire plane
class HitAndAssociationsWriterBase
Base class handling a collection of hits and its associations.
class HitAndAssociationsWriterManager
A helper to centralise creation of a hit collection data product.
class HitCollectionAssociator
A class handling a collection of hits and its associations.
class HitCollectionCreator
A class handling a collection of hits and its associations.
class HitCreator
Class managing the creation of a new icarus::Hit object.
class HitRefinerAssociator
A class handling a collection of hits and its associations.
class IcarusGeometryHelper
Implementation of geo::ExptGeoHelperInterface for ICARUS.
class ICARUSPurityDQM
class ICARUSsplitInductionChannelMapSetupTool
Interface for a tool creating the standard ICARUS channel mapper.
class KeyValuesData
Collection of items with key/values structure.
struct match_geometry
struct matchCand
class OpHitTimingCorrection
Creates a new collection of optical hits with corrected time.
struct ParsingToolkit
Utilities for text parsing.
class PhotBackground
class PMTconfigurationExtraction
Writes PMT configuration from FHiCL into a data product.
class PMTconfigurationExtractor
Class to extract PMT readout board configuration.
class PMTconfigurationExtractorBase
class PMTcoordinates
class PMTStartCalibTime
class PMTWaveformBaselines
Extracts the baseline of PMT waveforms.
class PMTWaveformBaselinesFromChannelData
Extracts a baseline from PMT waveforms.
class PMTWaveformBaselinesFromReadoutConfiguration
Extracts PMT baseline settings from PMT readout configuration.
struct SimEnergyDepositSummary
Data structure containing summary information about deposited energy.
struct TriggerConfiguration
class TriggerConfigurationExtraction
Writes trigger configuration from FHiCL into a data product.
class TriggerConfigurationExtractor
Class to extract PMT readout board configuration.
class TriggerConfigurationExtractorBase
class TrigInfo
struct WaveformBaseline
Class containing a waveform baseline value.
struct WaveformRMS
Class containing a waveform baseline RMS value.
Typedefs
using HitCollectionCreatorManager = HitAndAssociationsWriterManager<HitCollectionCreator>
A manager for icarus::HitCollectionCreator writer class.
Functions
CathodeDesc_t findTPCcathode (geo::Point_t const &point, geo::GeometryCore const &geom)
Returns cathode information for cryostat at the specified point.
double distance (geo::Point_t const &point, CathodeDesc_t const &cathode)
Returns the distance of a point from the cathode.
geo::Point_t findCathodeCenter (geo::CryostatGeo const &cryo)
Returns the center of the cathode in the specified cryostat.
template<typename Iter >
CathodeCrossing_t detectCrossing (Iter begin, Iter end, CathodeDesc_t const &cathode)
Returns the crossing point of a trajectory on the cathode.
void vmanip (std::vector< double > v, double *ave, double *rms)
void set_def (sbn::crt::CRTTzero tz)
daq::details::BoardSetup_t convert (DaqDecoderICARUSPMT::BoardSetupConfig const &config)
Special function fhicl::TableAs uses to convert BoardSetupConfig.
std::ostream & operator<< (std::ostream &out, dumpChannel const &d)
std::ostream & operator<< (std::ostream &out, DaqDecoderICARUSPMT::SplitTimestamp_t const &time)
std::ostream & operator<< (std::ostream &out, icarus::TriggerConfiguration const &config)
Prints the configuration into a stream with default verbosity.
std::ostream & operator<< (std::ostream &out, KeyValuesData const &data)
std::ostream & operator<< (std::ostream &out, KeyValuesData::Item const &data)
sbn::PMTconfiguration extractPMTreadoutConfiguration (std::string const &srcFileName, icarus::PMTconfigurationExtractor extractor)
sbn::PMTconfiguration extractPMTreadoutConfiguration (TFile &srcFile, icarus::PMTconfigurationExtractor extractor)
template<typename Principal >
sbn::PMTconfiguration extractPMTreadoutConfiguration (Principal const &data, icarus::PMTconfigurationExtractor extractor)
icarus::TriggerConfiguration extractTriggerReadoutConfiguration (std::string const &srcFileName, icarus::TriggerConfigurationExtractor extractor)
icarus::TriggerConfiguration extractTriggerReadoutConfiguration (TFile &srcFile, icarus::TriggerConfigurationExtractor extractor)
template<typename Principal >
icarus::TriggerConfiguration extractTriggerReadoutConfiguration (Principal const &data, icarus::TriggerConfigurationExtractor extractor)
std::ostream & operator<< (std::ostream &o, Hit const &hit)
bool operator< (const Hit &a, const Hit &b)
std::ostream & operator<< (std::ostream &out, icarus::WaveformRMS const &baseline)
Prints the value of the RMS into a stream.
opdet::SharedWaveformBaseline::Params_t convert (icarus::PMTWaveformBaselinesFromChannelData::Config::AlgoConfig const &config)
std::ostream & operator<< (std::ostream &out, icarus::WaveformBaseline const &baseline)
Prints the value of the baseline into a stream.
Detailed Description
Cluster finding and building.
Reconstruction base classes.
Class: CRTT0Matching Module Type: producer File: CRTT0Matching_module.cc
Author: Thomas Brooks E-mail address: tbrooks@fnal.gov
Modified from CRTT0Matching by Thomas Warburton.
Class: CRTTPCTruthEff Module Type: analyzer File: CRTTPCTruthEff_module.cc
Author: Tyler Boone E-mail address: tboone@FNAL.gov
Modified from CRTT0Matching_module by Tyler Boone
Class Documentation
icarus::CathodeDesc_t
struct icarus::CathodeDesc_t
Simple description for the cathode.
Definition at line 39 of file CathodeCrossingUtils.h.
Class Members
Point_t center
Vector_t normal
icarus::match_geometry
struct icarus::match_geometry
Definition at line 84 of file CRTT0MatchAlg.h.
Class Members
int best_DCA_pos = -1
TVector3 crt_hit_pos {DBL_MIN,DBL_MIN,DBL_MIN}
double crtTime = DBL_MIN
double dca = DBL_MIN
int driftDir = -2
int driftdir = -5
TVector3 endDir {DBL_MIN,DBL_MIN,DBL_MIN}
double extrapLen = DBL_MIN
int hit_id = INT_MIN
long meta_track_id = LONG_MIN
bool simple_cathodecrosser = false
double simpleDCA_endDir = DBL_MIN
double simpleDCA_startDir = DBL_MIN
TVector3 startDir {DBL_MIN,DBL_MIN,DBL_MIN}
double t0 = DBL_MIN
double t0max = DBL_MIN
double t0min = DBL_MIN
CRTHit thishit
TVector3 tpc_track_end {DBL_MIN,DBL_MIN,DBL_MIN}
TVector3 tpc_track_start {DBL_MIN,DBL_MIN,DBL_MIN}
long track_id = LONG_MIN
icarus::matchCand
struct icarus::matchCand
Definition at line 66 of file CRTT0MatchAlg.h.
Class Members
int best_DCA_pos = -1
double crtTime = DBL_MIN
double dca = DBL_MIN
int driftdir = -5
TVector3 endDir {DBL_MIN,DBL_MIN,DBL_MIN}
double extrapLen = DBL_MIN
bool simple_cathodecrosser = false
TVector3 startDir {DBL_MIN,DBL_MIN,DBL_MIN}
double t0 = DBL_MIN
double t0max = DBL_MIN
double t0min = DBL_MIN
CRTHit thishit
TVector3 tpc_track_end {DBL_MIN,DBL_MIN,DBL_MIN}
TVector3 tpc_track_start {DBL_MIN,DBL_MIN,DBL_MIN}
icarus::SimEnergyDepositSummary
struct icarus::SimEnergyDepositSummary
Data structure containing summary information about deposited energy.
Definition at line 15 of file SimEnergyDepositSummary.h.
Class Members
float Active { 0.0 }
Energy deposited in active volume [GeV]
float PreSpill { 0.0 } Energy deposited in pre-spill [GeV].
float PreSpillActive { 0.0 } Energy deposited in active volume in pre-spill window [GeV].
float Spill { 0.0 } Energy deposited in spill [GeV].
float SpillActive { 0.0 } Energy deposited in active volume in spill [GeV].
float Total { 0.0 } Total deposited energy [GeV].
Typedef Documentation
HitCollectionCreatorManager
using icarus::HitCollectionCreatorManager = HitAndAssociationsWriterManager<HitCollectionCreator>
A manager for icarus::HitCollectionCreator writer class.
Definition at line 991 of file HitCreator.h.
Function Documentation
convert() [1/2]
daq::details::BoardSetup_t icarus::convert (DaqDecoderICARUSPMT::BoardSetupConfig const & config)
Special function fhicl::TableAs uses to convert BoardSetupConfig.
Definition at line 1433 of file DaqDecoderICARUSPMT_module.cc.
References daq::details::BoardSetup_t::NoFragmentID.
convert() [2/2]
opdet::SharedWaveformBaseline::Params_t icarus::convert (icarus::PMTWaveformBaselinesFromChannelData::Config::AlgoConfig const & config)
Definition at line 406 of file PMTWaveformBaselinesFromChannelData_module.cc.
detectCrossing()
template<typename Iter > CathodeCrossing_t icarus::detectCrossing (Iter begin, Iter end, CathodeDesc_t const & cathode)
Returns the crossing point of a trajectory on the cathode.
Template Parameters
Iter type of iterator to a point in space
Parameters
begin iterator to the first point of the trajectory
end iterator past the last point of the trajectory
cathode description of the cathode plane
Returns
the crossing information
This algorithm intersects a path on a infinite plane in 3D space, and returns the intersection point.
The path is a sequence of segments. For simple trajectories, there is only one crossing, and then the returned point lies on both the path and the plane (it is, indeed, the path/cathode intersection point). For trajectories which cross the plane multiple times, the details of the part of the trajectory between the first and the last crossing are ignored and the two chunks of end paths that lie entirely on one side of the cathode are joint by a segment, shortcutting the details of the path in between.
The function also returns the length of the paths at the two sides of the cathode. Again, in case of multiple crossings, the details of the crossing are ignored and a single segment is used to connect the two sides, and the two lengths reflect that approximation. If no intersection point is found, the two partial lengths are both 0.
distance()
double icarus::distance (geo::Point_t const & point, CathodeDesc_t const & cathode)
Returns the distance of a point from the cathode.
Definition at line 35 of file CathodeCrossingUtils.cxx.
Referenced by icarus::crt::CRTHitmatched(), and icarus::ICARUSPurityDQM::produce().
extractPMTreadoutConfiguration() [1/3]
template<typename Principal > sbn::PMTconfiguration icarus::extractPMTreadoutConfiguration (Principal const & data, icarus::PMTconfigurationExtractor extractor)
Definition at line 492 of file PMTconfigurationExtractor.h.
extractPMTreadoutConfiguration() [2/3]
sbn::PMTconfiguration icarus::extractPMTreadoutConfiguration (std::string const & srcFileName, icarus::PMTconfigurationExtractor extractor)
Definition at line 220 of file PMTconfigurationExtractor.cxx.
extractPMTreadoutConfiguration() [3/3]
sbn::PMTconfiguration icarus::extractPMTreadoutConfiguration (TFile & srcFile, icarus::PMTconfigurationExtractor extractor)
Definition at line 236 of file PMTconfigurationExtractor.cxx.
extractTriggerReadoutConfiguration() [1/3]
template<typename Principal > icarus::TriggerConfiguration icarus::extractTriggerReadoutConfiguration (Principal const & data, icarus::TriggerConfigurationExtractor extractor)
Definition at line 470 of file TriggerConfigurationExtractor.h.
extractTriggerReadoutConfiguration() [2/3]
icarus::TriggerConfiguration icarus::extractTriggerReadoutConfiguration (std::string const & srcFileName, icarus::TriggerConfigurationExtractor extractor)
Definition at line 344 of file TriggerConfigurationExtractor.cxx.
extractTriggerReadoutConfiguration() [3/3]
icarus::TriggerConfiguration icarus::extractTriggerReadoutConfiguration (TFile & srcFile, icarus::TriggerConfigurationExtractor extractor)
Definition at line 360 of file TriggerConfigurationExtractor.cxx.
findCathodeCenter()
geo::Point_t icarus::findCathodeCenter (geo::CryostatGeo const & cryo)
Returns the center of the cathode in the specified cryostat.
Definition at line 40 of file CathodeCrossingUtils.cxx.
Referenced by findTPCcathode().
findTPCcathode()
icarus::CathodeDesc_t icarus::findTPCcathode (geo::Point_t const & point, geo::GeometryCore const & geom)
Returns cathode information for cryostat at the specified point.
The normal to the cathode is always the same as the normal of the first TPC in the cryostat containing point. This ensures consistency within the cryostat.
Definition at line 20 of file CathodeCrossingUtils.cxx.
References findCathodeCenter().
operator<()
bool icarus::operator< (const Hit & a, const Hit & b)
Definition at line 106 of file Hit.cxx.
operator<<() [1/8]
std::ostream & icarus::operator<< (std::ostream & o, Hit const & hit)
Definition at line 82 of file Hit.cxx.
operator<<() [2/8]
std::ostream & icarus::operator<< (std::ostream & out, DaqDecoderICARUSPMT::SplitTimestamp_t const & time)
Definition at line 1513 of file DaqDecoderICARUSPMT_module.cc.
operator<<() [3/8]
std::ostream & icarus::operator<< (std::ostream & out, dumpChannel const & d)
Definition at line 1481 of file DaqDecoderICARUSPMT_module.cc.
operator<<() [4/8]
std::ostream & icarus::operator<< (std::ostream & out, icarus::TriggerConfiguration const & config) inline
Prints the configuration into a stream with default verbosity.
Definition at line 345 of file TriggerConfiguration.h.
References icarus::TriggerConfiguration::dump().
operator<<() [5/8]
std::ostream & icarus::operator<< (std::ostream & out, icarus::WaveformBaseline const & baseline)
Prints the value of the baseline into a stream.
Definition at line 17 of file WaveformBaseline.cxx.
References icarus::WaveformBaseline::baseline().
operator<<() [6/8]
std::ostream & icarus::operator<< (std::ostream & out, icarus::WaveformRMS const & baseline)
Prints the value of the RMS into a stream.
Definition at line 17 of file WaveformRMS.cxx.
References icarus::WaveformRMS::RMS().
operator<<() [7/8]
std::ostream & icarus::operator<< (std::ostream & out, KeyValuesData const & data)
Definition at line 102 of file KeyValuesData.cxx.
operator<<() [8/8]
std::ostream & icarus::operator<< (std::ostream & out, KeyValuesData::Item const & data)
Definition at line 89 of file KeyValuesData.cxx.