CAF format: sbn::bits Namespace Reference
sbn::bits Namespace Reference
Simple utilities to deal with bit enumerators.
Classes
struct mask_t
Functions
Generic bit functions
template<typename EnumType >
mask_t< EnumType > makeMask (typename mask_t< EnumType >::maskbits_t bits) noexcept
Converts a integral type into a mask.
template<typename EnumType >
constexpr auto value (EnumType bit)
Returns the value of specified bit (conversion like enum to int).
template<typename EnumType , typename... OtherBits>
constexpr mask_t< EnumType > mask (EnumType bit, OtherBits... otherBits)
Returns a mask with all specified bits set.
template<typename EnumType >
constexpr bool hasBitSet (mask_t< EnumType > bitMask, EnumType bit)
Returns whether the specified bit is set in bitMask.
template<typename EnumType >
std::string name (EnumType bit)
Returns the name of the specified bit. Delegates to bitName().
template<typename EnumType >
std::vector< std::string > names (mask_t< EnumType > mask)
Beam bits
enum class triggerSource : unsigned int {
Unknown , BNB , NuMI , OffbeamBNB ,
OffbeamNuMI , Calib , NBits
}
Type of beam or beam gate or other trigger source.
enum class triggerLocation : unsigned int {
CryoEast , CryoWest , TPCEE , TPCEW ,
TPCWE , TPCWW , NBits
}
Location or locations generating a trigger.
enum class triggerLogic : unsigned int { PMTAnalogSum , PMTPairMajority , NBits }
Type(s) of trigger logic being satisfied.
enum class triggerType : unsigned int { Majority , MinimumBias , NBits }
Type representing the type(s) of this trigger.
enum class triggerWindowMode : unsigned int {
Separated , Overlapping , SeparatedPlusAdders , OverlappingPlusAdders ,
Adders , NBits
}
Trigger window mode.
enum class gateSelection : unsigned int {
GateBNB , DriftGateBNB , GateNuMI , DriftGateNuMI ,
GateOffbeamBNB , DriftGateOffbeamBNB , GateOffbeamNuMI , DriftGateOffbeamNuMI ,
GateCalibration , DriftGateCalibration , MinbiasGateBNB , MinbiasGateNuMI ,
MinbiasGateOffbeamBNB , MinbiasGateOffbeamNuMI , MinbiasGateCalibration , MinbiasDriftGateBNB ,
MinbiasDriftGateNuMI , MinbiasDriftGateOffbeamBNB , MinbiasDriftGateOffbeamNuMI , MinbiasDriftGateCalibration ,
NBits
}
Enabled gates in the trigger configuration. See register 0X00050008 in docdb SBN-doc-23778-v1.
using triggerSourceMask = mask_t<triggerSource>
Type of mask with triggerSource bits.
using triggerLocationMask = mask_t<triggerLocation>
Type of mask with triggerLocation bits.
using triggerLogicMask = mask_t<triggerLogic>
Type of mask with triggerLogic bits.
using triggerTypeMask = mask_t<triggerType>
Type of mask with triggerType bits.
using gateSelectionMask = mask_t<gateSelection>
Type of beam or beam gate or other trigger source.
std::string bitName (triggerSource bit)
Returns a mnemonic short name of the beam type.
std::string bitName (triggerLocation bit)
Returns a mnemonic short name of the trigger location.
std::string bitName (triggerLogic bit)
Returns a mnemonic short name of the trigger logic.
std::string bitName (triggerType bit)
Returns a mnemonic short name of the trigger type.
std::string bitName (triggerWindowMode bit)
Returns a mnemonic short name for the trigger window mode.
std::string bitName (gateSelection bit)
Returns a mnemonic short name for the gate type.
Detailed Description
Simple utilities to deal with bit enumerators.
A few simple concepts:
a bit is identified by its position (integral number: 0, 1, 2...)
representation of a bit is via a enumerator (enum class)
bits may be associated with a name (name())
to test bits, mask(), value() and hasBitSet() help with the conversions between enum class and the underlying integral type
Typedef Documentation
gateSelectionMask
using sbn::bits::gateSelectionMask = mask_t<gateSelection>
Type of beam or beam gate or other trigger source.
Definition at line 188 of file BeamBits.h.
triggerLocationMask
using sbn::bits::triggerLocationMask = mask_t<triggerLocation>
Type of mask with triggerLocation bits.
Definition at line 125 of file BeamBits.h.
triggerLogicMask
using sbn::bits::triggerLogicMask = mask_t<triggerLogic>
Type of mask with triggerLogic bits.
Definition at line 136 of file BeamBits.h.
triggerSourceMask
using sbn::bits::triggerSourceMask = mask_t<triggerSource>
Type of mask with triggerSource bits.
Definition at line 109 of file BeamBits.h.
triggerTypeMask
using sbn::bits::triggerTypeMask = mask_t<triggerType>
Type of mask with triggerType bits.
Definition at line 147 of file BeamBits.h.
Enumeration Type Documentation
gateSelection
enum class sbn::bits::gateSelection : unsigned int strong
Enabled gates in the trigger configuration. See register 0X00050008 in docdb SBN-doc-23778-v1.
Enumerator
GateBNB
Enable receiving BNB early warning signal (gatedBES) to open BNB gates.
DriftGateBNB
Enable BNB early-early warning signal ($1D) for light out-of-time in BNB gates.
GateNuMI
Enable NuMI early warning signal (MIBS$74) to open NuMI gates.
DriftGateNuMI
Enable receiving NuMI early-early warning signal ($AD) for light out-of-time in NuMI gates.
GateOffbeamBNB
Enable Offbeam gate for BNB.
DriftGateOffbeamBNB
Enable Offbeam drift gate BNB (for light out-of-time in offbeam gates)
GateOffbeamNuMI
Enable Offbeam gate for NuMI.
DriftGateOffbeamNuMI
Enable Offbeam drift gate NuMI (for light out-of-time in offbeam gates)
GateCalibration
Enable Calibration gate.
DriftGateCalibration
Enable Calibration drift gate (for light out-of-time in calibration gates)
MinbiasGateBNB
Enable MinBias triggers for the BNB stream.
MinbiasGateNuMI
Enable MinBias triggers for the NuMI stream.
MinbiasGateOffbeamBNB
Enabke MinBias triggers for the Offbeam BNB stream.
MinbiasGateOffbeamNuMI
Enable MinBias triggers for the Offbeam NuMI stream.
MinbiasGateCalibration
Enable MinBias triggers for the Calibration stream.
MinbiasDriftGateBNB
Enable light out-of-time for MinBias triggers in BNB stream.
MinbiasDriftGateNuMI
Enable light out-of-time for MinBias triggers in NuMI stream.
MinbiasDriftGateOffbeamBNB
Enable light out-of-time for MinBias triggers in Offbeam BNB stream.
MinbiasDriftGateOffbeamNuMI
Enable light out-of-time for MinBias triggers in Offbeam NuMI stream.
MinbiasDriftGateCalibration
Enable light out-of-time for MinBias triggers in Calibration stream.
Definition at line 163 of file BeamBits.h.
triggerLocation
enum class sbn::bits::triggerLocation : unsigned int strong
Location or locations generating a trigger.
Enumerator
CryoEast
A trigger happened in the east cryostat.
CryoWest
A trigger happened in the west cryostat.
TPCEE
A trigger happened in the east cryostat, east TPC.
TPCEW
A trigger happened in the east cryostat, west TPC.
TPCWE
A trigger happened in the west cryostat, east TPC.
TPCWW
A trigger happened in the west cryostat, west TPC.
NBits
Number of bits currently supported.
Definition at line 113 of file BeamBits.h.
triggerLogic
enum class sbn::bits::triggerLogic : unsigned int strong
Type(s) of trigger logic being satisfied.
Enumerator
PMTAnalogSum
Discriminated PMT signal sum above threshold.
PMTPairMajority
Minimum number of discriminated PMT above threshold.
NBits
Number of bits currently supported.
Definition at line 128 of file BeamBits.h.
triggerSource
enum class sbn::bits::triggerSource : unsigned int strong
Type of beam or beam gate or other trigger source.
Enumerator
Unknown
Type of beam unknown.
BNB
Type of beam: BNB.
NuMI
Type of beam: NuMI.
OffbeamBNB
Type of Offbeam: BNB.
OffbeamNuMI
Type of Offbeam: NuMI.
Calib
Type of source: calibration trigger.
NBits
Number of bits currently supported.
Definition at line 97 of file BeamBits.h.
triggerType
enum class sbn::bits::triggerType : unsigned int strong
Type representing the type(s) of this trigger.
Enumerator
Majority
A minimum number of close-by PMT pairs above threshold was reached.
MinimumBias
Data collected at gate opening with no further requirement imposed.
NBits
Number of bits currently supported.
Definition at line 139 of file BeamBits.h.
triggerWindowMode
enum class sbn::bits::triggerWindowMode : unsigned int strong
Trigger window mode.
Enumerator
Separated
Separated, non-overlapping contiguous window.
Overlapping
Overlapping windows.
SeparatedPlusAdders
OR of Separated and Adders.
OverlappingPlusAdders
OR of Overlapping and Adders.
Adders
Trigger from adders.
NBits
Number of Bits currently supported.
Definition at line 150 of file BeamBits.h.
Function Documentation
bitName() [1/6]
std::string sbn::bits::bitName (gateSelection bit) inline
Returns a mnemonic short name for the gate type.
Definition at line 366 of file BeamBits.h.
bitName() [2/6]
std::string sbn::bits::bitName (triggerLocation bit) inline
Returns a mnemonic short name of the trigger location.
Definition at line 303 of file BeamBits.h.
bitName() [3/6]
std::string sbn::bits::bitName (triggerLogic bit) inline
Returns a mnemonic short name of the trigger logic.
Definition at line 321 of file BeamBits.h.
bitName() [4/6]
std::string sbn::bits::bitName (triggerSource bit) inline
Returns a mnemonic short name of the beam type.
Todo
Move into an implementation file once this header in the final location.
Definition at line 285 of file BeamBits.h.
Referenced by name().
bitName() [5/6]
std::string sbn::bits::bitName (triggerType bit) inline
Returns a mnemonic short name of the trigger type.
Definition at line 335 of file BeamBits.h.
bitName() [6/6]
std::string sbn::bits::bitName (triggerWindowMode bit) inline
Returns a mnemonic short name for the trigger window mode.
Definition at line 349 of file BeamBits.h.
References Adders, NBits, Overlapping, OverlappingPlusAdders, Separated, and SeparatedPlusAdders.
hasBitSet()
template<typename EnumType > bool sbn::bits::hasBitSet (mask_t< EnumType > bitMask, EnumType bit) constexpr
Returns whether the specified bit is set in bitMask.
Definition at line 250 of file BeamBits.h.
References mask().
Referenced by icarus::TriggerConfigurationExtractor::extractTriggerConfiguration(), and names().
makeMask()
template<typename EnumType > mask_t< EnumType > sbn::bits::makeMask (typename mask_t< EnumType >::maskbits_t bits) noexcept
Converts a integral type into a mask.
Referenced by icarus::TriggerConfigurationExtractor::extractTriggerConfiguration().
mask()
template<typename EnumType , typename... OtherBits> mask_t< EnumType > sbn::bits::mask (EnumType bit, OtherBits... otherBits) constexpr
Returns a mask with all specified bits set.
Referenced by hasBitSet(), and names().
name()
template<typename EnumType > std::string sbn::bits::name (EnumType bit)
Returns the name of the specified bit. Delegates to bitName().
Definition at line 256 of file BeamBits.h.
References bitName().
Referenced by names().
names()
template<typename EnumType > std::vector< std::string > sbn::bits::names (mask_t< EnumType > mask)
Returns a list of the names of all the bits set in mask. Mask is interpreted as made of only bits of type EnumType.
Definition at line 262 of file BeamBits.h.
References hasBitSet(), mask(), name(), and names().
Referenced by names().
value()
template<typename EnumType > auto sbn::bits::value (EnumType bit) constexpr
Returns the value of specified bit (conversion like enum to int).
Definition at line 233 of file BeamBits.h.