CAF format: sbn Namespace Reference
sbn Namespace Reference
Set of values to identify a beam.
Namespaces
namespace bits
Simple utilities to deal with bit enumerators.
Classes
class BNBSpillInfo
class CRUMBSResult
class DumpArtDAQfragments
Dumps on console the content of artdaq::Fragment collections.
class DumpPMTconfiguration
Dumps on console the content of sbn::PMTconfiguration data product.
class DumpTrigger
Dumps on console the content of trigger data products.
class DumpTriggerConfiguration
Dumps on console the content of icarus::TriggerConfiguration data product.
class DuplicateEventTracker
Keeps track of duplicate events in the job.
class EventRegistry
Keeps a record of all registered events and their source.
class EXTCountInfo
struct ExtraTriggerInfo
Additional information on trigger.
struct FlashTriggerPrimitive
struct HitInfo
struct HitTruth
class MergedTrackInfo
struct MetaInfo
class MVAPID
class NuMISpillInfo
struct OpDetWaveformMeta
Derivative information from raw::OpDetWaveform data.
class OpDetWaveformMetaMaker
Converter from raw::OpDetWaveform into sbn::OpDetWaveformMeta.
class OpT0Finder
class PFPCNNScore
struct PMTconfiguration
Class containing configuration for PMT readout.
class RangeP
class ScatterClosestApproach
struct selBeamInfo
struct selCRTInfo
struct selCRTpoint
struct selHitInfo
struct selLightInfo
struct selSimTriggerInfo
struct selTrackInfo
struct selTriggerInfo
class ShowerDensityFit
class ShowerTrackFit
class SimpleFlashMatch
class StoppingChi2Fit
class Stub
class StubHit
class TimedTrackSelector
Selects tracks with time information.
class TimeTrackTreeStorage
Fills a ROOT tree with track-based triggering information.
class TPCPMTBarycenterMatch
Information on matching of a reconstructed TPC object with a optical flash via barycenter matching algorithm.
struct TrackHitInfo
struct TrackInfo
struct TrackTruth
class TriggerEmulationTree
Fills a ROOT tree with trigger emulation results.
struct TrueHit
struct TrueParticle
struct V1730channelConfiguration
Class containing configuration for a V1730 channel.
struct V1730Configuration
Class containing configuration for a V1730 board.
struct Vector3D
class VertexHit
struct WireInfo
Functions
TimeTrackTreeStorage::TriggerInputSpec_t convert (TimeTrackTreeStorage::Config::TriggerSpecConfig const &config)
std::ostream & operator<< (std::ostream &out, sbn::OpDetWaveformMeta const &meta)
TriggerEmulationTree::TriggerInputSpec_t convert (TriggerEmulationTree::Config::TriggerSpecConfig const &config)
std::ostream & operator<< (std::ostream &out, sbn::PMTconfiguration const &config)
Prints the configuration into a stream with default verbosity.
std::ostream & operator<< (std::ostream &out, sbn::V1730channelConfiguration const &config)
Prints the configuration into a stream with default verbosity.
std::ostream & operator<< (std::ostream &out, sbn::V1730Configuration const &config)
Prints the configuration into a stream with default verbosity.
std::ostream & operator<< (std::ostream &out, ExtraTriggerInfo const &info)
Creation of <tt>sbn::OpDetWaveformMeta</tt> from <tt>raw::OpDetWaveform</tt>
The creation of summary objects sbn::OpDetWaveformMeta from optical detector waveforms is possible with two options:
one shot: call to convert a single waveform (makeOpDetWaveformMeta());
bulk: converter object reused for multiple conversions (sbn::OpDetWaveformMetaMaker).
For usage examples, see their respective documentation.
OpDetWaveformMeta makeOpDetWaveformMeta (raw::OpDetWaveform const &waveform, detinfo::DetectorTimings const &detTimings)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
OpDetWaveformMeta makeOpDetWaveformMeta (raw::OpDetWaveform const &waveform, util::quantities::intervals::microseconds opDetTickPeriod)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
OpDetWaveformMeta makeOpDetWaveformMeta (raw::OpDetWaveform const &waveform, util::quantities::intervals::microseconds opDetTickPeriod, raw::Trigger const &trigger)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
Variables
constexpr float nan_float = std::numeric_limits<float>::signaling_NaN()
constexpr int default_int = std::numeric_limits<int>::max()
constexpr float default_float = std::numeric_limits<float>::signaling_NaN()
Detailed Description
Set of values to identify a beam.
The constants are used to identify the gate during which a trigger is acquired, in the raw::Trigger::TriggerBits() bit mask.
Class Documentation
sbn::EXTCountInfo
class sbn::EXTCountInfo
Definition at line 13 of file EXTCountInfo.h.
Class Members
float gates_since_last_trigger
sbn::FlashTriggerPrimitive
struct sbn::FlashTriggerPrimitive
Definition at line 22 of file FlashTriggerPrimitive.hh.
Class Members
unsigned channel
vector< Trig > triggers
sbn::HitTruth
struct sbn::HitTruth
Definition at line 39 of file TrackCaloSkimmerObj.h.
Class Members
float e
float nelec
sbn::MergedTrackInfo
class sbn::MergedTrackInfo
Definition at line 7 of file MergedTrackInfo.hh.
Class Members
int branch
float branch_overlap
float branch_start
TVector3 direction
int trunk
float trunk_start
TVector3 vertex
sbn::RangeP
class sbn::RangeP
Definition at line 5 of file RangeP.h.
Class Members
float range_p
int trackID
sbn::selTriggerInfo
struct sbn::selTriggerInfo
Definition at line 72 of file TrackTreeStoreObj.h.
Class Members
uint64_t beamGateTime = 0
unsigned int beamType = 0
unsigned int gateID = 0
unsigned int triggerID = 0
uint64_t triggerTime = 0
sbn::StubHit
class sbn::StubHit
Definition at line 9 of file Stub.h.
Class Members
float charge Calibrated and corrected for electron lifetime [#elec].
bool ontrack Whether the hit is also on a track.
short wire The wire this hit is on.
sbn::VertexHit
class sbn::VertexHit
Definition at line 9 of file VertexHit.h.
Class Members
float charge Calibrated and lifetime-corrected charge on the hit [#elec].
float dedx Recombination corrected dQ/dx [MeV/cm].
float dqdx charge/pitch [#elec/cm]
float pitch Computed pitch of a track traversing from the vertex to this hit. Space charge corrected. [cm].
float proj_dist_to_vertex Distnace from the hit to the vertex on the wireplane.
int spID ID of the SpacePoint associated with this hit.
Point_t spXYZ 3D location of the SpacePoint associated with this hit. Space charge corrected. [cm]
float vtxw Wire of the vertex associated with this hit. Not space charge corrected. [cm].
float vtxx X-Position of the vertex associated with this hit as seen by wire-planes. Not space charge corrected. [cm].
Point_t vtxXYZ 3D location of the Vertex associated with this hit. Space charge corrected. [cm]
WireID wire Wire that the hit is on.
Function Documentation
convert() [1/2]
TimeTrackTreeStorage::TriggerInputSpec_t sbn::convert (TimeTrackTreeStorage::Config::TriggerSpecConfig const & config)
Definition at line 353 of file TimeTrackTreeStorage_module.cc.
convert() [2/2]
TriggerEmulationTree::TriggerInputSpec_t sbn::convert (TriggerEmulationTree::Config::TriggerSpecConfig const & config)
Definition at line 230 of file TriggerEmulationTree_module.cc.
makeOpDetWaveformMeta() [1/3]
sbn::OpDetWaveformMeta sbn::makeOpDetWaveformMeta (raw::OpDetWaveform const & waveform, detinfo::DetectorTimings const & detTimings)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
Parameters
waveform the input waveform
detTimings timing service provider
Returns
a sbn::OpDetWaveformMeta object with the summary information
Returns a new summary object extracted from the waveform.
The timing information is used to determine whether the global trigger and beam times are included.
Example:
detinfo::DetectorTimings const detTimings = detinfo::makeDetectorTimings
  (art::ServiceHandle<detinfo::DetectorClocksService const>()->DataFor(event));
sbn::OpDetWaveformMeta info = sbn::makeOpDetWaveformMeta(waveform, detTimings);
Definition at line 112 of file OpDetWaveformMetaUtils.cxx.
References sbn::OpDetWaveformMetaMaker::make().
makeOpDetWaveformMeta() [2/3]
sbn::OpDetWaveformMeta sbn::makeOpDetWaveformMeta (raw::OpDetWaveform const & waveform, util::quantities::intervals::microseconds opDetTickPeriod)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
Parameters
waveform the input waveform
opDetTickPeriod period of the optical detector digitizer
Returns
a sbn::OpDetWaveformMeta object with the summary information
Returns a new summary object extracted from the waveform.
Information requiring timing is not saved.
Example:
util::quantities::intervals::nanoseconds const opDetPeriod { 2.0 };
sbn::OpDetWaveformMeta info
  = sbn::makeOpDetWaveformMeta(waveform, opDetPeriod);
Definition at line 120 of file OpDetWaveformMetaUtils.cxx.
References sbn::OpDetWaveformMetaMaker::make().
makeOpDetWaveformMeta() [3/3]
sbn::OpDetWaveformMeta sbn::makeOpDetWaveformMeta (raw::OpDetWaveform const & waveform, util::quantities::intervals::microseconds opDetTickPeriod, raw::Trigger const & trigger)
Creates a sbn::OpDetWaveformMeta out of a raw::OpDetWaveform.
Parameters
waveform the input waveform
opDetTickPeriod period of the optical detector digitizer
trigger relative trigger times information
Returns
a sbn::OpDetWaveformMeta object with the summary information
Returns a new summary object extracted from the waveform.
Example:
util::quantities::intervals::nanoseconds const opDetPeriod { 2.0 };
auto const& trigger
  = event.getProduct<std::vector<raw::Trigger>>(triggerTag).front();
sbn::OpDetWaveformMeta info
  = sbn::makeOpDetWaveformMeta(waveform, opDetPeriod, trigger);
Definition at line 128 of file OpDetWaveformMetaUtils.cxx.
References sbn::OpDetWaveformMetaMaker::make().
operator<<() [1/5]
std::ostream & sbn::operator<< (std::ostream & out, ExtraTriggerInfo const & info)
Definition at line 148 of file ExtraTriggerInfo.cxx.
operator<<() [2/5]
std::ostream & sbn::operator<< (std::ostream & out, sbn::OpDetWaveformMeta const & meta)
Definition at line 354 of file ReassociatePMTbaselines_module.cc.
operator<<() [3/5]
std::ostream & sbn::operator<< (std::ostream & out, sbn::PMTconfiguration const & config) inline
Prints the configuration into a stream with default verbosity.
Definition at line 149 of file PMTconfiguration.h.
operator<<() [4/5]
std::ostream & sbn::operator<< (std::ostream & out, sbn::V1730channelConfiguration const & config) inline
Prints the configuration into a stream with default verbosity.
Definition at line 191 of file V1730channelConfiguration.h.
operator<<() [5/5]
std::ostream & sbn::operator<< (std::ostream & out, sbn::V1730Configuration const & config) inline
Prints the configuration into a stream with default verbosity.
Definition at line 232 of file V1730Configuration.h.
Variable Documentation
default_float
float sbn::default_float = std::numeric_limits<float>::signaling_NaN() constexpr
Definition at line 10 of file CRUMBSResult.h.
default_int
int sbn::default_int = std::numeric_limits<int>::max() constexpr
Definition at line 9 of file CRUMBSResult.h.
nan_float
float sbn::nan_float = std::numeric_limits<float>::signaling_NaN() constexpr
Definition at line 8 of file CNNScore.h.