CAF format: icaruscode/icaruscode/PMT/OpReco/Algorithms/OpRecoFactoryStuff.h File Reference
OpRecoFactoryStuff.h File Reference
Utility and boilerplate for optical algorithms.
#include "fhiclcpp/ParameterSet.h"
#include "cetlib_except/exception.h"
#include <vector>
#include <iterator>
#include <memory>
#include <string>
#include <utility>
#include <type_traits>
Classes
struct opdet::factory::details::NoModule_t
struct opdet::factory::Decl< Algo >
Token to register an algorithm, used in AlgorithmFactory.
struct opdet::factory::FWInterfaceTraits< Event, Module >
Template type for the third parameter of FWInterfacedIF objects.
class opdet::factory::AlgorithmFactory< Base >
An algorithm factory class.
struct opdet::factory::AlgorithmFactory< Base >::Decl< Algo >
Derivative of opdet::factory::Decl with added type check.
class opdet::factory::FWInterfacedIF< Base, FWTraits >
class opdet::factory::FWInterfacedBase< Algo, Base, FWTraits >
Base class for specialization.
class opdet::factory::FWInterfaced< Algo, Base, FWTraits >
struct opdet::factory::AlgorithmFactory< Base >::AlgoMaker
struct opdet::factory::AlgorithmFactory< Base >::AlgoMakerFor< Algo >
Standard algorithm maker class.
Functions
template<typename S , typename Coll >
S opdet::factory::join (S const &sep, Coll const &s)
Returns a concatenation of strings in s separated by sep.
template<typename Coll >
std::string opdet::factory::join (const char *sep, Coll const &s)
Detailed Description
Utility and boilerplate for optical algorithms.
Date
May 7, 2022
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Some utility and boilerplate to make the use of optical reconstruction algorithms from larana more flexible.
This does not attempt to interface those algorithms with art tools, which is definitely possible but just not done here.
Definition in file OpRecoFactoryStuff.h.
Function Documentation
join() [1/2]
template<typename Coll > std::string opdet::factory::join (const char * sep, Coll const & s)
Definition at line 584 of file OpRecoFactoryStuff.h.
join() [2/2]
template<typename S , typename Coll > S opdet::factory::join (S const & sep, Coll const & s)
Returns a concatenation of strings in s separated by sep.
Template Parameters
S type of string
Coll type of collection of strings
Parameters
sep separator string
s list of strings
Returns
a string of type S with the concatenation of all elements of s
Example:
using std::string_literals;
std::array const s { "one"s, "2"s, "III"s, "d"s };
std::cout << "Options: '" << join("', '", s) << "'." << std::endl;
will print: ‘Options: 'one’, '2', 'III', 'd'.`.
Note that actually S can be any copyable type supporting in-place addition (that is concatenation for strings). Indeed, elements in Coll do not even need to be of type S as long as S::operator+=(Coll::value_type) is supported.
Definition at line 573 of file OpRecoFactoryStuff.h.
References opdet::factory::join().
Referenced by opdet::factory::join(), and opdet::factory::AlgorithmFactory< Base >::names().