CAF format: icaruscode/icaruscode/Decode/ChannelMapping/RunPeriods.h File Reference
RunPeriods.h File Reference
Utilities to define run periods.
#include <array>
Classes
struct icarusDB::RunPeriods
Definition of supported run periods.
Enumerations
enum class icarusDB::RunPeriod : unsigned int { Runs0to2 , Run2shutdownB1 , Runs3andOn , NPeriods }
List of run periods.
Functions
constexpr std::array< RunPeriod, static_cast< unsigned int >(RunPeriod::NPeriods)> icarusDB::allPeriods () noexcept
Returns an array with all run periods. Also in RunPeriods::All.
constexpr std::size_t icarusDB::NPeriods () noexcept
Returns the number of supported periods.
Detailed Description
Utilities to define run periods.
Date
August 8, 2023
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Definition in file RunPeriods.h.
Enumeration Type Documentation
RunPeriod
enum class icarusDB::RunPeriod : unsigned int strong
List of run periods.
Enumerator
Runs0to2
Runs from the very beginning to the first part of Summer 2023.
Run2shutdownB1
A few runs in Summer 2023, break point 1 (August 23-29).
Runs3andOn
Runs from last part of Summer 2023 on.
NPeriods
Number of run periods.
Definition at line 19 of file RunPeriods.h.
Function Documentation
allPeriods()
std::array< icarusDB::RunPeriod, icarusDB::NPeriods()> icarusDB::allPeriods () inline constexpr noexcept
Returns an array with all run periods. Also in RunPeriods::All.
Definition at line 43 of file RunPeriods.h.
References icarusDB::allPeriods(), and icarusDB::NPeriods().
Referenced by icarusDB::allPeriods().
NPeriods()
std::size_t icarusDB::NPeriods () constexpr noexcept
Returns the number of supported periods.
Definition at line 33 of file RunPeriods.h.
Referenced by icarusDB::allPeriods().