CAF format: icarus::WaveformRMS Struct Reference
icarus::WaveformRMS Struct Reference
Class containing a waveform baseline RMS value.
#include <WaveformRMS.h>
Public Types
using BaselineRMS_t = float
Type of baseline RMS value.
Public Member Functions
WaveformRMS ()=default
Constructor: default baseline RMS (0).
WaveformRMS (BaselineRMS_t RMS)
Constructor: sets the baseline RMS.
Access to the baseline RMS
In addition to the direct method (RMS()) a few candies are offered: a function-like operator for baseline RMS access.
BaselineRMS_t RMS () const
BaselineRMS_t operator() () const
Returns the current baseline RMS value.
Public Attributes
BaselineRMS_t fRMS {}
The current value of the baseline RMS.
Detailed Description
Class containing a waveform baseline RMS value.
See also
icarus::WaveformBaseline
The baseline RMS is stored as a floating point value.
This class is a data product wrapper for a simple value, with some usability candies attached.
Example of simple usage
icarus::WaveformRMS const RMS { 3.2f };
std::cout << "RMS: " << RMS << " ADC" << std::endl;
will print RMS: 3.2 ADC.
Definition at line 51 of file WaveformRMS.h.
Member Typedef Documentation
BaselineRMS_t
using icarus::WaveformRMS::BaselineRMS_t = float
Type of baseline RMS value.
Definition at line 53 of file WaveformRMS.h.
Constructor & Destructor Documentation
WaveformRMS() [1/2]
icarus::WaveformRMS::WaveformRMS () default
Constructor: default baseline RMS (0).
WaveformRMS() [2/2]
icarus::WaveformRMS::WaveformRMS (BaselineRMS_t RMS) inline
Constructor: sets the baseline RMS.
Definition at line 64 of file WaveformRMS.h.
Member Function Documentation
operator()()
BaselineRMS_t icarus::WaveformRMS::operator() () const inline
Returns the current baseline RMS value.
Definition at line 82 of file WaveformRMS.h.
References RMS().
RMS()
BaselineRMS_t icarus::WaveformRMS::RMS () const inline
Returns the current baseline RMS value.
Definition at line 79 of file WaveformRMS.h.
References fRMS.
Referenced by opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::doBeginEvent(), operator()(), and icarus::operator<<().
Member Data Documentation
fRMS
BaselineRMS_t icarus::WaveformRMS::fRMS {}
The current value of the baseline RMS.
Definition at line 55 of file WaveformRMS.h.
Referenced by RMS().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Data/WaveformRMS.h