CAF format: daq::details::BoardSetup_t::ChannelSetup_t Struct Reference
daq::details::BoardSetup_t::ChannelSetup_t Struct Reference
Special settings for one channel on the board.
#include <PMTDecoderUtils.h>
Public Member Functions
bool hasChannel () const
Returns if this channel is associated to a off-line channel number.
bool mustSkip () const
Whether this channel is requested to be skipped.
bool mustSave () const
Whether this channel is requested to be saved.
bool isDefault () const
Returns whether this is the default configuration.
Static Public Member Functions
static bool isChannel (raw::Channel_t channel)
Returns if channel is a valid channel ID.
Public Attributes
raw::Channel_t channelID = sbn::V1730channelConfiguration::NoChannelID
Associated off-line (LArSoft) channel ID.
std::optional< bool > forcedSkip
Whether the channel should be forcedly ignored or acquired.
bool onGlobalOnly = false
Save the channel only when including the global trigger time.
std::uint16_t minSpan = 0
Minimum acceptable waveform span.
std::string category
Category of this channel (will become instance name).
Detailed Description
Special settings for one channel on the board.
Definition at line 51 of file PMTDecoderUtils.h.
Member Function Documentation
hasChannel()
bool daq::details::BoardSetup_t::ChannelSetup_t::hasChannel () const inline
Returns if this channel is associated to a off-line channel number.
Definition at line 68 of file PMTDecoderUtils.h.
References channelID, and isChannel().
Referenced by icarus::DaqDecoderICARUSPMT::checkBoardSetup(), icarus::DaqDecoderICARUSPMT::createFragmentWaveforms(), and isDefault().
isChannel()
static bool daq::details::BoardSetup_t::ChannelSetup_t::isChannel (raw::Channel_t channel) inline static
Returns if channel is a valid channel ID.
Definition at line 86 of file PMTDecoderUtils.h.
References sbn::V1730channelConfiguration::NoChannelID.
Referenced by icarus::DaqDecoderICARUSPMT::createFragmentWaveforms(), and hasChannel().
isDefault()
bool daq::details::BoardSetup_t::ChannelSetup_t::isDefault () const inline
Returns whether this is the default configuration.
Definition at line 77 of file PMTDecoderUtils.h.
References category, forcedSkip, hasChannel(), and onGlobalOnly.
mustSave()
bool daq::details::BoardSetup_t::ChannelSetup_t::mustSave () const inline
Whether this channel is requested to be saved.
Definition at line 74 of file PMTDecoderUtils.h.
References forcedSkip.
Referenced by icarus::DaqDecoderICARUSPMT::createFragmentWaveforms().
mustSkip()
bool daq::details::BoardSetup_t::ChannelSetup_t::mustSkip () const inline
Whether this channel is requested to be skipped.
Definition at line 71 of file PMTDecoderUtils.h.
References forcedSkip.
Referenced by icarus::DaqDecoderICARUSPMT::checkBoardSetup(), icarus::DaqDecoderICARUSPMT::createFragmentWaveforms(), and icarus::DaqDecoderICARUSPMT::getAllInstanceNames().
Member Data Documentation
category
std::string daq::details::BoardSetup_t::ChannelSetup_t::category
Category of this channel (will become instance name).
Definition at line 65 of file PMTDecoderUtils.h.
Referenced by icarus::DaqDecoderICARUSPMT::checkBoardSetup(), icarus::DaqDecoderICARUSPMT::getAllInstanceNames(), isDefault(), and icarus::DaqDecoderICARUSPMT::mergeWaveformGroup().
channelID
raw::Channel_t daq::details::BoardSetup_t::ChannelSetup_t::channelID = sbn::V1730channelConfiguration::NoChannelID
Associated off-line (LArSoft) channel ID.
Definition at line 54 of file PMTDecoderUtils.h.
Referenced by icarus::DaqDecoderICARUSPMT::checkBoardSetup(), icarus::DaqDecoderICARUSPMT::createFragmentWaveforms(), and hasChannel().
forcedSkip
std::optional<bool> daq::details::BoardSetup_t::ChannelSetup_t::forcedSkip
Whether the channel should be forcedly ignored or acquired.
Definition at line 57 of file PMTDecoderUtils.h.
Referenced by isDefault(), mustSave(), and mustSkip().
minSpan
std::uint16_t daq::details::BoardSetup_t::ChannelSetup_t::minSpan = 0
Minimum acceptable waveform span.
Definition at line 62 of file PMTDecoderUtils.h.
onGlobalOnly
bool daq::details::BoardSetup_t::ChannelSetup_t::onGlobalOnly = false
Save the channel only when including the global trigger time.
Definition at line 60 of file PMTDecoderUtils.h.
Referenced by isDefault().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h