CAF format: icarus::WaveformBaseline Struct Reference
icarus::WaveformBaseline Struct Reference
Class containing a waveform baseline value.
#include <WaveformBaseline.h>
Public Types
using Baseline_t = float
Type of baseline value.
Public Member Functions
WaveformBaseline ()=default
Constructor: default baseline (0).
WaveformBaseline (Baseline_t baseline)
Constructor: sets the baseline.
Access to the baseline
In addition to the direct method (baseline()) a few candies are offered: a function-like operator for baseline access.
Baseline_t baseline () const
Baseline_t operator() () const
Returns the current baseline value.
Public Attributes
Baseline_t fBaseline {}
The current value of the baseline.
Detailed Description
Class containing a waveform baseline value.
The baseline is stored as a floating point value, not to lose precision.
This class is a data product wrapper for a simple value, with some usability candies attached.
Example of simple usage
icarus::WaveformBaseline const baseline { 1.2f };
std::cout << "Baseline: " << baseline << " ADC" << std::endl;
will print Baseline: 1.2 ADC.
Example of usage with quantity values
The following is a more complex example showing baseline subtraction. We assume we are using the type util::quantities::counts as ADC count type (defined in lardataalg/Utilities/quantities/electronics.h) for the waveform.
using ADCCount_t = util::quantities::counts;
std::vector<ADCCount_t> subtractBaseline
  (std::vector<ADCCount_t> const& data, icarus::WaveformBaseline const& baseline)
{
  icarus::waveform_operations::NegativePolarityOperations<float> const
    waveOps { baseline() };
  std::vector<ADCCount_t> subtracted;
  subtracted.reserve(data.size());
  for (auto sample: data) {
    subtracted.emplace_back
      (std::round(waveOps.subtractBaseline(sample.value())));
  }
  return subtracted;
} // subtractBaseline()
The subtracted waveform is positive and baseline-subtracted. We use ICARUS utilities to manage the polarity of the waveform (hard-coded negative). Note that the subtraction is less than trivial because of the integral type waveform on top of the floating point baseline. The samples are converted into floating point for the subtraction, then reconverted (rounded) back.
Definition at line 84 of file WaveformBaseline.h.
Member Typedef Documentation
Baseline_t
using icarus::WaveformBaseline::Baseline_t = float
Type of baseline value.
Definition at line 86 of file WaveformBaseline.h.
Constructor & Destructor Documentation
WaveformBaseline() [1/2]
icarus::WaveformBaseline::WaveformBaseline () default
Constructor: default baseline (0).
WaveformBaseline() [2/2]
icarus::WaveformBaseline::WaveformBaseline (Baseline_t baseline) inline
Constructor: sets the baseline.
Definition at line 97 of file WaveformBaseline.h.
Member Function Documentation
baseline()
Baseline_t icarus::WaveformBaseline::baseline () const inline
Returns the current baseline value.
Definition at line 112 of file WaveformBaseline.h.
References fBaseline.
Referenced by icarus::trigger::DiscriminatedAdderSignal::addWaveformsInInterval(), opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::doBeginEvent(), operator()(), icarus::operator<<(), sbn::V1730channelConfiguration::operator==(), icarus::PMTWaveformBaselines::produce(), icarus::PMTWaveformBaselinesFromChannelData::produce(), and icarus::opdet::DiscretePhotoelectronPulse::sampleShape().
operator()()
Baseline_t icarus::WaveformBaseline::operator() () const inline
Returns the current baseline value.
Definition at line 115 of file WaveformBaseline.h.
References baseline().
Member Data Documentation
fBaseline
Baseline_t icarus::WaveformBaseline::fBaseline {}
The current value of the baseline.
Definition at line 88 of file WaveformBaseline.h.
Referenced by baseline().
The documentation for this struct was generated from the following file:
sbnobj/sbnobj/ICARUS/PMT/Data/WaveformBaseline.h