CAF format: EventInfo_t Struct Reference
EventInfo_t Struct Reference
Information about the event.
Public Member Functions
EventInfo_t ()
Constructor. As if nobody noticed.
void dump (std::ostream &out) const
Prints the content of the object into a stream.
Query interface
unsigned int nWeakChargedCurrentInteractions () const
Returns the number of weak charged current interactions in the event.
unsigned int nWeakNeutralCurrentInteractions () const
Returns the number of weak neutral current interactions in the event.
unsigned int nWeakCurrentInteractions () const
Returns the number of weak current interactions in the event.
bool isWeakChargedCurrent () const
Returns whether the event is generated as a neutrino CC interaction.
bool isWeakNeutralCurrent () const
Returns whether the event is generated as a neutrino NC interaction.
bool isNeutrino () const
Returns whether the event is generated as a neutrino interaction.
bool isNu_mu () const
Returns which neutrino flavor is present in an event.
bool isNu_e () const
Returns the number of weak charged current interactions in the event.
int NeutrinoPDG () const
Returns the neutrino PDG code.
GeV DepositedEnergy () const
Returns the total energy deposited in the detector during the event [GeV].
GeV DepositedEnergyInSpill () const
Returns the total energy deposited in the detector during beam [GeV].
GeV DepositedEnergyInActiveVolume () const
Returns the energy deposited in the active volume during the event [GeV].
GeV DepositedEnergyInSpillInActiveVolume () const
Returns the energy deposited in the active volume during the beam [GeV].
GeV NeutrinoEnergy () const
Returns the number of weak charged current interactions in the event.
GeV LeptonEnergy () const
Returns the number of weak charged current interactions in the event.
int InteractionType () const
Returns the number of weak charged current interactions in the event.
bool hasVertex () const
Returns whether this type of event has a known vertex.
bool isInActiveVolume () const
Returns whether there is an interaction within the active volume.
Private Attributes
std::array< unsigned int, NInteractionTypes > fInteractions
GeV fEnergyDepTotal { 0.0 }
Total deposited energy.
GeV fEnergyDepSpill { 0.0 }
Energy deposited in spill.
GeV fEnergyDepActive { 0.0 }
GeV fEnergyDepSpillActive { 0.0 }
Energy deposited in active volume in spill.
int fNeutrinoPDG { 0 }
int fInteractionType { 0 }
GeV fNeutrinoEnergy { 0.0 }
GeV fLeptonEnergy { 0.0 }
bool nu_mu { false }
bool nu_e { false }
bool fInActiveVolume { false }
Whether the event has activity inside the active volume.
Static Private Attributes
static constexpr std::size_t itWCC { 0U }
Charged weak current.
static constexpr std::size_t itWNC { 1U }
Neutral weak current.
static constexpr std::size_t NInteractionTypes { 2U }
Set interface
std::vector< geo::Point_t > fVertices
Position of all vertices.
void AddWeakChargedCurrentInteractions (unsigned int n=1U)
Marks this event as including n more weak charged current interactions.
void AddWeakNeutralCurrentInteractions (unsigned int n=1U)
Marks this event as including n more weak neutral current interactions.
void SetNu_mu (bool numu)
Marks the neutrino flavor.
void SetNu_e (bool nue)
Position of all vertices.
void SetNeutrinoPDG (int NU)
Marks this event's neutrino type.
void SetDepositedEnergy (GeV e)
Sets the total deposited energy of the event [GeV].
void SetDepositedEnergyInSpill (GeV e)
Sets the energy of the event deposited during beam gate [GeV].
void SetDepositedEnergyInActiveVolume (GeV e)
Sets the total deposited energy of the event in active volume [GeV].
void SetDepositedEnergyInActiveVolumeInSpill (GeV e)
void SetNeutrinoEnergy (GeV eNu)
Position of all vertices.
void SetLeptonEnergy (GeV eL)
Position of all vertices.
void SetInteractionType (int type)
Position of all vertices.
void SetInActiveVolume (bool active=true)
Set whether the event has relevant activity in the active volume.
void AddVertex (geo::Point_t const &vertex)
Adds a point to the list of interaction vertices in the event.
Detailed Description
Information about the event.
Definition at line 97 of file TriggerEfficiencyPlots_module.cc.
Constructor & Destructor Documentation
EventInfo_t()
EventInfo_t::EventInfo_t () inline
Constructor. As if nobody noticed.
Definition at line 100 of file TriggerEfficiencyPlots_module.cc.
Member Function Documentation
AddVertex()
void EventInfo_t::AddVertex (geo::Point_t const & vertex) inline
Adds a point to the list of interaction vertices in the event.
Definition at line 218 of file TriggerEfficiencyPlots_module.cc.
References fVertices.
AddWeakChargedCurrentInteractions()
void EventInfo_t::AddWeakChargedCurrentInteractions (unsigned int n = 1U) inline
Marks this event as including n more weak charged current interactions.
Definition at line 177 of file TriggerEfficiencyPlots_module.cc.
References itWCC.
AddWeakNeutralCurrentInteractions()
void EventInfo_t::AddWeakNeutralCurrentInteractions (unsigned int n = 1U) inline
Marks this event as including n more weak neutral current interactions.
Definition at line 181 of file TriggerEfficiencyPlots_module.cc.
References itWNC.
DepositedEnergy()
GeV EventInfo_t::DepositedEnergy () const inline
Returns the total energy deposited in the detector during the event [GeV].
Definition at line 141 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepTotal.
Referenced by dump().
DepositedEnergyInActiveVolume()
GeV EventInfo_t::DepositedEnergyInActiveVolume () const inline
Returns the energy deposited in the active volume during the event [GeV].
Definition at line 147 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepActive.
Referenced by dump().
DepositedEnergyInSpill()
GeV EventInfo_t::DepositedEnergyInSpill () const inline
Returns the total energy deposited in the detector during beam [GeV].
Definition at line 144 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepSpill.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
DepositedEnergyInSpillInActiveVolume()
GeV EventInfo_t::DepositedEnergyInSpillInActiveVolume () const inline
Returns the energy deposited in the active volume during the beam [GeV].
Definition at line 150 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepSpillActive.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
dump()
void EventInfo_t::dump (std::ostream & out) const inline
Prints the content of the object into a stream.
Definition at line 226 of file TriggerEfficiencyPlots_module.cc.
References DepositedEnergy(), DepositedEnergyInActiveVolume(), DepositedEnergyInSpill(), DepositedEnergyInSpillInActiveVolume(), fVertices, InteractionType(), isInActiveVolume(), isNeutrino(), isNu_e(), isNu_mu(), LeptonEnergy(), NeutrinoEnergy(), nWeakChargedCurrentInteractions(), and nWeakNeutralCurrentInteractions().
hasVertex()
bool EventInfo_t::hasVertex () const inline
Returns whether this type of event has a known vertex.
Definition at line 163 of file TriggerEfficiencyPlots_module.cc.
References fVertices.
Referenced by icarus::trigger::TriggerEfficiencyPlots::shouldPlotEvent().
InteractionType()
int EventInfo_t::InteractionType () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 160 of file TriggerEfficiencyPlots_module.cc.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
isInActiveVolume()
bool EventInfo_t::isInActiveVolume () const inline
Returns whether there is an interaction within the active volume.
Definition at line 166 of file TriggerEfficiencyPlots_module.cc.
References fInActiveVolume.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::shouldPlotEvent().
isNeutrino()
bool EventInfo_t::isNeutrino () const inline
Returns whether the event is generated as a neutrino interaction.
Definition at line 130 of file TriggerEfficiencyPlots_module.cc.
References isWeakChargedCurrent(), and isWeakNeutralCurrent().
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
isNu_e()
bool EventInfo_t::isNu_e () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 135 of file TriggerEfficiencyPlots_module.cc.
Referenced by dump().
isNu_mu()
bool EventInfo_t::isNu_mu () const inline
Returns which neutrino flavor is present in an event.
Definition at line 134 of file TriggerEfficiencyPlots_module.cc.
Referenced by dump().
isWeakChargedCurrent()
bool EventInfo_t::isWeakChargedCurrent () const inline
Returns whether the event is generated as a neutrino CC interaction.
Definition at line 122 of file TriggerEfficiencyPlots_module.cc.
References nWeakChargedCurrentInteractions().
Referenced by isNeutrino().
isWeakNeutralCurrent()
bool EventInfo_t::isWeakNeutralCurrent () const inline
Returns whether the event is generated as a neutrino NC interaction.
Definition at line 126 of file TriggerEfficiencyPlots_module.cc.
References nWeakNeutralCurrentInteractions().
Referenced by isNeutrino().
LeptonEnergy()
GeV EventInfo_t::LeptonEnergy () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 157 of file TriggerEfficiencyPlots_module.cc.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
NeutrinoEnergy()
GeV EventInfo_t::NeutrinoEnergy () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 154 of file TriggerEfficiencyPlots_module.cc.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
NeutrinoPDG()
int EventInfo_t::NeutrinoPDG () const inline
Returns the neutrino PDG code.
Definition at line 138 of file TriggerEfficiencyPlots_module.cc.
nWeakChargedCurrentInteractions()
unsigned int EventInfo_t::nWeakChargedCurrentInteractions () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 107 of file TriggerEfficiencyPlots_module.cc.
References itWCC.
Referenced by dump(), isWeakChargedCurrent(), and nWeakCurrentInteractions().
nWeakCurrentInteractions()
unsigned int EventInfo_t::nWeakCurrentInteractions () const inline
Returns the number of weak current interactions in the event.
Definition at line 115 of file TriggerEfficiencyPlots_module.cc.
References nWeakChargedCurrentInteractions(), and nWeakNeutralCurrentInteractions().
nWeakNeutralCurrentInteractions()
unsigned int EventInfo_t::nWeakNeutralCurrentInteractions () const inline
Returns the number of weak neutral current interactions in the event.
Definition at line 111 of file TriggerEfficiencyPlots_module.cc.
References itWNC.
Referenced by dump(), isWeakNeutralCurrent(), and nWeakCurrentInteractions().
SetDepositedEnergy()
void EventInfo_t::SetDepositedEnergy (GeV e) inline
Sets the total deposited energy of the event [GeV].
Definition at line 192 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepTotal.
SetDepositedEnergyInActiveVolume()
void EventInfo_t::SetDepositedEnergyInActiveVolume (GeV e) inline
Sets the total deposited energy of the event in active volume [GeV].
Definition at line 198 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepActive.
SetDepositedEnergyInActiveVolumeInSpill()
void EventInfo_t::SetDepositedEnergyInActiveVolumeInSpill (GeV e) inline
Sets the energy of the event deposited during beam gate in active volume [GeV]
Definition at line 202 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepSpillActive.
SetDepositedEnergyInSpill()
void EventInfo_t::SetDepositedEnergyInSpill (GeV e) inline
Sets the energy of the event deposited during beam gate [GeV].
Definition at line 195 of file TriggerEfficiencyPlots_module.cc.
References fEnergyDepSpill.
SetInActiveVolume()
void EventInfo_t::SetInActiveVolume (bool active = true) inline
Set whether the event has relevant activity in the active volume.
Definition at line 215 of file TriggerEfficiencyPlots_module.cc.
References fInActiveVolume.
SetInteractionType()
void EventInfo_t::SetInteractionType (int type) inline
Position of all vertices.
Definition at line 212 of file TriggerEfficiencyPlots_module.cc.
SetLeptonEnergy()
void EventInfo_t::SetLeptonEnergy (GeV eL) inline
Position of all vertices.
Definition at line 209 of file TriggerEfficiencyPlots_module.cc.
SetNeutrinoEnergy()
void EventInfo_t::SetNeutrinoEnergy (GeV eNu) inline
Position of all vertices.
Definition at line 206 of file TriggerEfficiencyPlots_module.cc.
SetNeutrinoPDG()
void EventInfo_t::SetNeutrinoPDG (int NU) inline
Marks this event's neutrino type.
Definition at line 189 of file TriggerEfficiencyPlots_module.cc.
SetNu_e()
void EventInfo_t::SetNu_e (bool nue) inline
Position of all vertices.
Definition at line 186 of file TriggerEfficiencyPlots_module.cc.
SetNu_mu()
void EventInfo_t::SetNu_mu (bool numu) inline
Marks the neutrino flavor.
Definition at line 185 of file TriggerEfficiencyPlots_module.cc.
Member Data Documentation
fEnergyDepActive
GeV EventInfo_t::fEnergyDepActive { 0.0 } private
Energy deposited in active volume.
Definition at line 281 of file TriggerEfficiencyPlots_module.cc.
Referenced by DepositedEnergyInActiveVolume(), and SetDepositedEnergyInActiveVolume().
fEnergyDepSpill
GeV EventInfo_t::fEnergyDepSpill { 0.0 } private
Energy deposited in spill.
Definition at line 280 of file TriggerEfficiencyPlots_module.cc.
Referenced by DepositedEnergyInSpill(), and SetDepositedEnergyInSpill().
fEnergyDepSpillActive
GeV EventInfo_t::fEnergyDepSpillActive { 0.0 } private
Energy deposited in active volume in spill.
Definition at line 283 of file TriggerEfficiencyPlots_module.cc.
Referenced by DepositedEnergyInSpillInActiveVolume(), and SetDepositedEnergyInActiveVolumeInSpill().
fEnergyDepTotal
GeV EventInfo_t::fEnergyDepTotal { 0.0 } private
Total deposited energy.
Definition at line 279 of file TriggerEfficiencyPlots_module.cc.
Referenced by DepositedEnergy(), and SetDepositedEnergy().
fInActiveVolume
bool EventInfo_t::fInActiveVolume { false } private
Whether the event has activity inside the active volume.
Definition at line 296 of file TriggerEfficiencyPlots_module.cc.
Referenced by isInActiveVolume(), and SetInActiveVolume().
fInteractions
std::array<unsigned int, NInteractionTypes> EventInfo_t::fInteractions private
Definition at line 277 of file TriggerEfficiencyPlots_module.cc.
fInteractionType
int EventInfo_t::fInteractionType { 0 } private
Definition at line 286 of file TriggerEfficiencyPlots_module.cc.
fLeptonEnergy
GeV EventInfo_t::fLeptonEnergy { 0.0 } private
Definition at line 289 of file TriggerEfficiencyPlots_module.cc.
fNeutrinoEnergy
GeV EventInfo_t::fNeutrinoEnergy { 0.0 } private
Definition at line 288 of file TriggerEfficiencyPlots_module.cc.
fNeutrinoPDG
int EventInfo_t::fNeutrinoPDG { 0 } private
Definition at line 285 of file TriggerEfficiencyPlots_module.cc.
fVertices
std::vector<geo::Point_t> EventInfo_t::fVertices
Position of all vertices.
Definition at line 220 of file TriggerEfficiencyPlots_module.cc.
Referenced by AddVertex(), dump(), hasVertex(), and icarus::trigger::TriggerEfficiencyPlots::plotResponses().
itWCC
std::size_t EventInfo_t::itWCC { 0U } static constexpr private
Charged weak current.
Definition at line 271 of file TriggerEfficiencyPlots_module.cc.
Referenced by AddWeakChargedCurrentInteractions(), and nWeakChargedCurrentInteractions().
itWNC
std::size_t EventInfo_t::itWNC { 1U } static constexpr private
Neutral weak current.
Definition at line 272 of file TriggerEfficiencyPlots_module.cc.
Referenced by AddWeakNeutralCurrentInteractions(), and nWeakNeutralCurrentInteractions().
NInteractionTypes
std::size_t EventInfo_t::NInteractionTypes { 2U } static constexpr private
Definition at line 273 of file TriggerEfficiencyPlots_module.cc.
nu_e
bool EventInfo_t::nu_e { false } private
Definition at line 293 of file TriggerEfficiencyPlots_module.cc.
nu_mu
bool EventInfo_t::nu_mu { false } private
Definition at line 292 of file TriggerEfficiencyPlots_module.cc.
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/TriggerEfficiencyPlots_module.cc