CAF format: icarus::trigger::details::PMTwallBitID< MaxBits > Struct Template Reference
icarus::trigger::details::PMTwallBitID< MaxBits > Struct Template Reference
Public Types
using BitID_t = PMTwallBitID<MaxBits>
This ID type.
using StatusBit_t = unsigned short int
Type for bit in the status word.
using Index_t = unsigned short int
Type for bit ID index.
Public Member Functions
constexpr bool hasCryostat () const
Returns if the cryostat is set; ID is valid even if this is false.
constexpr bool hasPMTwall () const
Returns if the PMT wall is set; ID is valid even if this is false.
constexpr Index_t index () const
constexpr bool isValid () const
constexpr operator bool () const
Static Public Member Functions
static constexpr BitID_t fromIndex (Index_t index)
Rebuilds an ID object from its index.
static constexpr Index_t NIndices ()
Returns the number of possible indices (0 to NIndices() - 1).
Public Attributes
std::size_t cryostat = NoCryostat
The cryostat the bit comes from (sbn::ExtraTriggerInfo convention).
std::size_t PMTwall = NoPMTwall
The PMT wall the bit comes from (sbn::ExtraTriggerInfo convention).
StatusBit_t statusBit = NoStatusBit
The number of bit in the status word (0 is the least significant one).
Static Public Attributes
static constexpr std::size_t NCryostats = 2
How many cryostats in the detector.
static constexpr std::size_t NPMTwallsPerCryostat = 2
How many PMT walls per cryostat. Each has one status word.
static constexpr unsigned short int NStatusWordBits = MaxBits
How many bits in a status word.
static constexpr std::size_t NoCryostat = std::numeric_limits<std::size_t>::max()
Special value to identify the absence of cryostat information.
static constexpr std::size_t NoPMTwall = std::numeric_limits<std::size_t>::max()
Special value to identify the absence of PMT wall information.
static constexpr StatusBit_t NoStatusBit = std::numeric_limits<StatusBit_t>::max()
Special value to identify the absence of a status bit.
static constexpr Index_t InvalidIndex = std::numeric_limits<Index_t>::max()
Special value for an invalid bit index.
Detailed Description
template<std::size_t MaxBits>
struct icarus::trigger::details::PMTwallBitID< MaxBits >
Definition at line 56 of file LVDSbitMaps.h.
Member Typedef Documentation
BitID_t
template<std::size_t MaxBits> using icarus::trigger::details::PMTwallBitID< MaxBits >::BitID_t = PMTwallBitID<MaxBits>
This ID type.
Definition at line 58 of file LVDSbitMaps.h.
Index_t
template<std::size_t MaxBits> using icarus::trigger::details::PMTwallBitID< MaxBits >::Index_t = unsigned short int
Type for bit ID index.
Definition at line 60 of file LVDSbitMaps.h.
StatusBit_t
template<std::size_t MaxBits> using icarus::trigger::details::PMTwallBitID< MaxBits >::StatusBit_t = unsigned short int
Type for bit in the status word.
Definition at line 59 of file LVDSbitMaps.h.
Member Function Documentation
fromIndex()
template<std::size_t MaxBits> auto icarus::trigger::details::PMTwallBitID< MaxBits >::fromIndex (Index_t index) static constexpr
Rebuilds an ID object from its index.
Definition at line 602 of file LVDSbitMaps.h.
hasCryostat()
template<std::size_t MaxBits> bool icarus::trigger::details::PMTwallBitID< MaxBits >::hasCryostat () const inline constexpr
Returns if the cryostat is set; ID is valid even if this is false.
Definition at line 102 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::cryostat, and icarus::trigger::details::PMTwallBitID< MaxBits >::NoCryostat.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index().
hasPMTwall()
template<std::size_t MaxBits> bool icarus::trigger::details::PMTwallBitID< MaxBits >::hasPMTwall () const inline constexpr
Returns if the PMT wall is set; ID is valid even if this is false.
Definition at line 105 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::NoPMTwall, and icarus::trigger::details::PMTwallBitID< MaxBits >::PMTwall.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index().
index()
template<std::size_t MaxBits> Index_t icarus::trigger::details::PMTwallBitID< MaxBits >::index () const inline constexpr
Returns an "unique" index for this information. Supports the absence of PMT wall or cryostat (not of bit).
Definition at line 109 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::cryostat, icarus::trigger::details::PMTwallBitID< MaxBits >::hasCryostat(), icarus::trigger::details::PMTwallBitID< MaxBits >::hasPMTwall(), icarus::trigger::details::PMTwallBitID< MaxBits >::InvalidIndex, icarus::trigger::details::PMTwallBitID< MaxBits >::isValid(), icarus::trigger::details::PMTwallBitID< MaxBits >::NPMTwallsPerCryostat, icarus::trigger::details::PMTwallBitID< MaxBits >::NStatusWordBits, icarus::trigger::details::PMTwallBitID< MaxBits >::PMTwall, and icarus::trigger::details::PMTwallBitID< MaxBits >::statusBit.
Referenced by icarus::trigger::LVDSbitMaps::buildAdderSourceMap(), and icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap().
isValid()
template<std::size_t MaxBits> bool icarus::trigger::details::PMTwallBitID< MaxBits >::isValid () const inline constexpr
Returns whether this ID is valid (does not require hasCryostat() nor hasPMTwall()).
Definition at line 120 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::NoStatusBit, and icarus::trigger::details::PMTwallBitID< MaxBits >::statusBit.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index(), and icarus::trigger::details::PMTwallBitID< MaxBits >::operator bool().
NIndices()
template<std::size_t MaxBits> static constexpr Index_t icarus::trigger::details::PMTwallBitID< MaxBits >::NIndices () inline static constexpr
Returns the number of possible indices (0 to NIndices() - 1).
Definition at line 131 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::NCryostats, icarus::trigger::details::PMTwallBitID< MaxBits >::NPMTwallsPerCryostat, and icarus::trigger::details::PMTwallBitID< MaxBits >::NStatusWordBits.
operator bool()
template<std::size_t MaxBits> icarus::trigger::details::PMTwallBitID< MaxBits >::operator bool () const inline constexpr
Returns whether this ID is valid (does not require hasCryostat() nor hasPMTwall()).
Definition at line 124 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< MaxBits >::isValid().
Member Data Documentation
cryostat
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::cryostat = NoCryostat
The cryostat the bit comes from (sbn::ExtraTriggerInfo convention).
Definition at line 91 of file LVDSbitMaps.h.
Referenced by icarus::trigger::LVDSbitMaps::buildAdderSourceMap(), icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap(), icarus::trigger::details::PMTwallBitID< MaxBits >::hasCryostat(), and icarus::trigger::details::PMTwallBitID< MaxBits >::index().
InvalidIndex
template<std::size_t MaxBits> Index_t icarus::trigger::details::PMTwallBitID< MaxBits >::InvalidIndex = std::numeric_limits<Index_t>::max() static constexpr
Special value for an invalid bit index.
Definition at line 85 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index().
NCryostats
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::NCryostats = 2 static constexpr
How many cryostats in the detector.
Definition at line 63 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::NIndices().
NoCryostat
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::NoCryostat = std::numeric_limits<std::size_t>::max() static constexpr
Special value to identify the absence of cryostat information.
Definition at line 73 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::hasCryostat().
NoPMTwall
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::NoPMTwall = std::numeric_limits<std::size_t>::max() static constexpr
Special value to identify the absence of PMT wall information.
Definition at line 77 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::hasPMTwall().
NoStatusBit
template<std::size_t MaxBits> StatusBit_t icarus::trigger::details::PMTwallBitID< MaxBits >::NoStatusBit = std::numeric_limits<StatusBit_t>::max() static constexpr
Special value to identify the absence of a status bit.
Definition at line 81 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::isValid().
NPMTwallsPerCryostat
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::NPMTwallsPerCryostat = 2 static constexpr
How many PMT walls per cryostat. Each has one status word.
Definition at line 66 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index(), and icarus::trigger::details::PMTwallBitID< MaxBits >::NIndices().
NStatusWordBits
template<std::size_t MaxBits> unsigned short int icarus::trigger::details::PMTwallBitID< MaxBits >::NStatusWordBits = MaxBits static constexpr
How many bits in a status word.
Definition at line 69 of file LVDSbitMaps.h.
Referenced by icarus::trigger::details::PMTwallBitID< MaxBits >::index(), and icarus::trigger::details::PMTwallBitID< MaxBits >::NIndices().
PMTwall
template<std::size_t MaxBits> std::size_t icarus::trigger::details::PMTwallBitID< MaxBits >::PMTwall = NoPMTwall
The PMT wall the bit comes from (sbn::ExtraTriggerInfo convention).
Definition at line 94 of file LVDSbitMaps.h.
Referenced by icarus::trigger::LVDSbitMaps::buildAdderSourceMap(), icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap(), icarus::trigger::details::PMTwallBitID< MaxBits >::hasPMTwall(), and icarus::trigger::details::PMTwallBitID< MaxBits >::index().
statusBit
template<std::size_t MaxBits> StatusBit_t icarus::trigger::details::PMTwallBitID< MaxBits >::statusBit = NoStatusBit
The number of bit in the status word (0 is the least significant one).
Definition at line 97 of file LVDSbitMaps.h.
Referenced by icarus::trigger::LVDSbitMaps::buildAdderSourceMap(), icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap(), icarus::trigger::details::PMTwallBitID< MaxBits >::index(), and icarus::trigger::details::PMTwallBitID< MaxBits >::isValid().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h