CAF format: icarus::ParsingToolkit Struct Reference
icarus::ParsingToolkit Struct Reference
Utilities for text parsing.
#include <ParsingToolkit.h>
Classes
struct CCTypeAdapter
struct Error
struct Params_t
All parsing parameters.
struct SplitView_t
Record of a split token: pre-separator, separator and post-separator.
Public Types
using QuotSpec_t = std::pair<std::string, std::string>
Specification of quotation: opening and closing.
Public Member Functions
ParsingToolkit ()
Default parsing parameters.
ParsingToolkit (Params_t params)
Creates a parser with the specified parsing parameters.
Params_t const & params () const noexcept
Returns the current parameters of parsing.
template<typename Iter >
bool isCharacterEscaped (Iter begin, Iter itCh) const
Input
std::pair< std::string, unsigned int > readMultiline (std::istream &in) const
Returns a single line of text from the input stream.
Characters
bool isEscape (char ch) const
Returns whether ch is an escape character.
template<typename BIter >
bool isCharacterEscaped (BIter begin, BIter itCh) const
Returns whether the character pointed by itCh is escaped or not.
template<typename Sel >
std::string_view::const_iterator findNextCharacter (std::string_view s, Sel select) const
Finds the next character satisfying the specified criterion.
std::string_view::const_iterator findNextBlank (std::string_view s) const
Helper function for findNextCharacter(std::string_view, Sel).
template<typename CType >
std::string_view removeTrailingCharacters (std::string_view s, CType charType) const
Consumes the blank characters a the beginning of s.
std::string_view removeTrailingBlanks (std::string_view s) const
Consumes the blank characters a the beginning of s.
std::string removeWordEscapes (std::string &&w) const
Returns a copy of w with all escape characters removed.
std::string removeWordEscapes (std::string_view w) const
Returns whether ch is an escape character.
std::string removeWordEscapes (const char *w) const
Returns whether ch is an escape character.
template<typename Words >
std::vector< std::string > removeEscapes (Words const &words) const
Returns a copy of words with all escape characters removed.
std::string removeWordQuotations (std::string &&w) const
Returns a copy of w with no quotation starts and ends.
std::string removeWordQuotations (std::string_view w) const
Returns whether ch is an escape character.
std::string removeWordQuotations (const char *w) const
Returns whether ch is an escape character.
template<typename Words >
std::vector< std::string > removeQuotations (Words const &words) const
Returns a copy of words with no quotation starts and ends.
Static Public Member Functions
static std::string_view make_view (std::string const &s)
Creates a std::string_view from an entire string s.
template<typename BIter , typename EIter >
static std::string_view make_view (BIter b, EIter e)
Creates a std::string_view from two string iterators b and e.
Static Public Attributes
static constexpr CCTypeAdapter<&std::isblank > isBlank {}
Adapter for determining if a character is a blank (see std::isblank()).
static Params_t const DefaultParameters
Private Member Functions
void adoptParams (Params_t params)
Initializes the parameters and caches.
Private Attributes
Params_t fParams
Parsing parameters.
std::string fQuoteStarts
Start characters of all supported quotations.
Tokenization
template<typename Delim >
std::vector< std::string_view > splitWords (std::string const &s, Delim isDelimiter) const
Splits a string into words.
std::vector< std::string_view > splitWords (std::string const &s) const
Helper version of splitWords(std::string const&, Delim).
template<typename Iter >
Iter findCommentWord (Iter beginWord, Iter endWord) const
Finds the first word starting with a comment marker.
template<typename WordType >
void removeCommentLine (std::vector< WordType > &words) const
Removes all the words from the one starting with a comment marker.
std::pair< std::string_view, QuotSpec_t const * > findQuotationStart (std::string_view sv) const
Finds the start of the next quotation in sv.
std::string_view findQuotationEnd (std::string_view sv, std::string const &quotEnd) const
Finds the quotation end in sv.
bool isQuotationUnclosed (std::string_view sv) const
Returns if the sequence sv has unclosed quotation at its end.
template<typename BIter , typename EIter >
std::string_view findFirstUnescaped (std::string_view sv, BIter beginKey, EIter endKey) const
Finds the first of the specified keys in sv.
template<typename Keys >
std::string_view findFirstUnescaped (std::string_view sv, Keys const &keys) const
Finds the first of the specified keys in sv.
template<typename Key >
std::string_view findFirstUnescaped (std::string_view sv, std::initializer_list< Key > keys) const
Splits a string into words.
template<typename BIter , typename EIter >
std::string_view findFirstUnquoted (std::string_view sv, BIter beginKey, EIter endKey) const
Finds the first of the specified keys in the unquoted part of sv.
template<typename Keys >
std::string_view findFirstUnquoted (std::string_view sv, Keys const &keys) const
Finds the first of the specified keys in the unquoted part of sv.
template<typename Key >
std::string_view findFirstUnquoted (std::string_view sv, std::initializer_list< Key > keys) const
Splits a string into words.
static SplitView_t splitOn (std::string_view sv, std::string_view sep)
Splits the view sv in three: before sep, sep and after sep.
Detailed Description
Utilities for text parsing.
This "class" is a glorified namespace with some configuration inside.
Quotation
A quoted string is the content in between an opening quoting sequence and the matching closing sequence. Each sequence may be any string, including but not limited to a one-character long string. Escaping the first character of an opening or closing quotation string will turn it in common string data carrying no quotation meaning.
Escaping rules
Any single character following the escape character is "escaped". The escaped characters lose their standard function and are replaced by a substitute character. For example, escaping the first character of a opening quotation makes that a standard character. An escaped escape character is always replaced by the character itself, without its escape function.
Definition at line 54 of file ParsingToolkit.h.
Class Documentation
icarus::ParsingToolkit::Params_t
struct icarus::ParsingToolkit::Params_t
All parsing parameters.
Definition at line 66 of file ParsingToolkit.h.
Class Members
string comment { "#" } Word introducing a comment.
char EOL { '\n' }
char escape { '\\' } Escape character.
vector< QuotSpec_t > quotes List of matching start and end of quote.
icarus::ParsingToolkit::SplitView_t
struct icarus::ParsingToolkit::SplitView_t
Record of a split token: pre-separator, separator and post-separator.
Definition at line 60 of file ParsingToolkit.h.
Class Members
string_view post
string_view pre
string_view sep
Member Typedef Documentation
QuotSpec_t
using icarus::ParsingToolkit::QuotSpec_t = std::pair<std::string, std::string>
Specification of quotation: opening and closing.
Definition at line 63 of file ParsingToolkit.h.
Constructor & Destructor Documentation
ParsingToolkit() [1/2]
icarus::ParsingToolkit::ParsingToolkit () inline
Default parsing parameters.
Creates a parser with the default parsing parameters.
Definition at line 100 of file ParsingToolkit.h.
References adoptParams().
ParsingToolkit() [2/2]
icarus::ParsingToolkit::ParsingToolkit (Params_t params) inline
Creates a parser with the specified parsing parameters.
Definition at line 103 of file ParsingToolkit.h.
References adoptParams(), and params().
Member Function Documentation
adoptParams()
void icarus::ParsingToolkit::adoptParams (Params_t params) private
Initializes the parameters and caches.
Definition at line 220 of file ParsingToolkit.cxx.
Referenced by ParsingToolkit(), and ParsingToolkit().
findCommentWord()
template<typename Iter > Iter icarus::ParsingToolkit::findCommentWord (Iter beginWord, Iter endWord) const
Finds the first word starting with a comment marker.
Template Parameters
Iter type of iterator to the words
Parameters
beginWord iterator to the first word to consider
endWord iterator past the lasy word to consider
Returns
an iterator to the comment word, or endWord if not found
The original list is modified, the word starting with a comment marker and all the following ones are removed.
Definition at line 748 of file ParsingToolkit.h.
Referenced by removeCommentLine().
findFirstUnescaped() [1/3]
template<typename BIter , typename EIter > std::string_view icarus::ParsingToolkit::findFirstUnescaped (std::string_view sv, BIter beginKey, EIter endKey) const
Finds the first of the specified keys in sv.
Template Parameters
BIter type of iterator to the keys
EIter type of key end-iterator
Parameters
sv string to be parsed
beginKey iterator to the first key
endKey iterator past the last key
Returns
a view of the key found within sv, empty if none
The keys are required to be sorted, longest first, since they are tested in order and the first match is kept (e.g. if the first key is = and the second is ==, the second key is never matched since the first one matches first). The first character of the key must not be escaped. Escaped characters in the key are not supported.
If no key is found, the returned view is zero-length and pointing to the end of sv.
The quoting in sv is ignored.
Definition at line 633 of file ParsingToolkit.h.
findFirstUnescaped() [2/3]
template<typename Keys > std::string_view icarus::ParsingToolkit::findFirstUnescaped (std::string_view sv, Keys const & keys) const
Finds the first of the specified keys in sv.
Template Parameters
BIter type of iterator to the keys
EIter type of key end-iterator
Parameters
sv string to be parsed
beginKey iterator to the first key
endKey iterator past the last key
Returns
a view of the key found within sv, empty if none
The keys are required to be sorted, longest first, since they are tested in order and the first match is kept (e.g. if the first key is = and the second is ==, the second key is never matched since the first one matches first). The first character of the key must not be escaped. Escaped characters in the key are not supported.
If no key is found, the returned view is zero-length and pointing to the end of sv.
The quoting in sv is ignored.
Definition at line 666 of file ParsingToolkit.h.
findFirstUnescaped() [3/3]
template<typename Key > std::string_view icarus::ParsingToolkit::findFirstUnescaped (std::string_view sv, std::initializer_list< Key > keys) const
Splits a string into words.
Template Parameters
Delim type of delimiter functor
Parameters
s the string to be split
isDelimiter (default: isblank()) determines if a character is a word delimiter
Returns
a sequence of views, one per word
The splitter algorithm defines a word separator as a sequence of one or more unescaped, unquoted delimiter characters, where a delimiter is a character ch for which isDelimiter(ch) is true.
Note that this function does not change the content of the data, and in particular it does not remove escaping nor quoting (although it interprets both).
A character used as delimiter can appear in a word only if escaped or within quotation. Contiguous non-delimiter elements of a string, including quoted strings, belong to the same word (for example, a" and "b is a single word when delimitation is by blank characters). An empty word can be introduced only in quotations (e.g. "").
The Delim type is a functor so that isDelimiter(ch) returns something convertible to bool, true if the ch character should be considered a delimiter. Note that no context is provided for the answer, so the use of each character as delimiter is fixed, and modified only by the hard-coded quotation and escaping rules.
The first characters of quotation starts and the escape characters must not be classified as delimiters, or the algorithm will give wrong results.
Definition at line 676 of file ParsingToolkit.h.
findFirstUnquoted() [1/3]
template<typename BIter , typename EIter > std::string_view icarus::ParsingToolkit::findFirstUnquoted (std::string_view sv, BIter beginKey, EIter endKey) const
Finds the first of the specified keys in the unquoted part of sv.
Template Parameters
BIter type of iterator to the keys
EIter type of key end-iterator
Parameters
sv string to be parsed
beginKey iterator to the first key
endKey iterator past the last key
Returns
the view pointing to the key in sv, or empty to its end if none
The keys are required to be sorted, longest first, since they are tested in order and the first match is kept (e.g. if the first key is = and the second is ==, the second key is never matched since the first one matches first).
If no key is found, the returned view is zero-length and pointing to the end of sv.
Definition at line 683 of file ParsingToolkit.h.
findFirstUnquoted() [2/3]
template<typename Keys > std::string_view icarus::ParsingToolkit::findFirstUnquoted (std::string_view sv, Keys const & keys) const
Finds the first of the specified keys in the unquoted part of sv.
Template Parameters
BIter type of iterator to the keys
EIter type of key end-iterator
Parameters
sv string to be parsed
beginKey iterator to the first key
endKey iterator past the last key
Returns
the view pointing to the key in sv, or empty to its end if none
The keys are required to be sorted, longest first, since they are tested in order and the first match is kept (e.g. if the first key is = and the second is ==, the second key is never matched since the first one matches first).
If no key is found, the returned view is zero-length and pointing to the end of sv.
Definition at line 731 of file ParsingToolkit.h.
findFirstUnquoted() [3/3]
template<typename Key > std::string_view icarus::ParsingToolkit::findFirstUnquoted (std::string_view sv, std::initializer_list< Key > keys) const
Splits a string into words.
Template Parameters
Delim type of delimiter functor
Parameters
s the string to be split
isDelimiter (default: isblank()) determines if a character is a word delimiter
Returns
a sequence of views, one per word
The splitter algorithm defines a word separator as a sequence of one or more unescaped, unquoted delimiter characters, where a delimiter is a character ch for which isDelimiter(ch) is true.
Note that this function does not change the content of the data, and in particular it does not remove escaping nor quoting (although it interprets both).
A character used as delimiter can appear in a word only if escaped or within quotation. Contiguous non-delimiter elements of a string, including quoted strings, belong to the same word (for example, a" and "b is a single word when delimitation is by blank characters). An empty word can be introduced only in quotations (e.g. "").
The Delim type is a functor so that isDelimiter(ch) returns something convertible to bool, true if the ch character should be considered a delimiter. Note that no context is provided for the answer, so the use of each character as delimiter is fixed, and modified only by the hard-coded quotation and escaping rules.
The first characters of quotation starts and the escape characters must not be classified as delimiters, or the algorithm will give wrong results.
Definition at line 741 of file ParsingToolkit.h.
findNextBlank()
std::string_view::const_iterator icarus::ParsingToolkit::findNextBlank (std::string_view s) const inline
Helper function for findNextCharacter(std::string_view, Sel).
Definition at line 405 of file ParsingToolkit.h.
References findNextCharacter(), and isBlank.
findNextCharacter()
template<typename Sel > std::string_view::const_iterator icarus::ParsingToolkit::findNextCharacter (std::string_view s, Sel select) const
Finds the next character satisfying the specified criterion.
Template Parameters
Sel type of functor determining which character to consider blank
Parameters
s view of the string to be parsed
select functor determining which character(s) to look for
Returns
an iterator to the first character, s.end() if none
By default, the selected character is a blank character ch, which has std::isblank(ch) true.
Definition at line 777 of file ParsingToolkit.h.
Referenced by findNextBlank(), and splitWords().
findQuotationEnd()
std::string_view icarus::ParsingToolkit::findQuotationEnd (std::string_view sv, std::string const & quotEnd) const
Finds the quotation end in sv.
Parameters
sv the buffer to look the quotation end into
quotEnd the quotation end to be searched
Returns
a view of sv from the quotation end, included, empty if not found
Note that sv should not include the quotation start.
Definition at line 106 of file ParsingToolkit.cxx.
Referenced by splitWords().
findQuotationStart()
auto icarus::ParsingToolkit::findQuotationStart (std::string_view sv) const
Finds the start of the next quotation in sv.
Parameters
sv the buffer to look the quotation start into
Returns
a subview of sv starting from the quotation found, empty if none
Definition at line 66 of file ParsingToolkit.cxx.
Referenced by splitWords().
isCharacterEscaped() [1/2]
template<typename BIter > bool icarus::ParsingToolkit::isCharacterEscaped (BIter begin, BIter itCh) const
Returns whether the character pointed by itCh is escaped or not.
Template Parameters
BIter iterator type
Parameters
begin iterator to the beginning of the string
itCh iterator to the character to be investigated.
Returns
whether there is an unescaped escape character before itCh
Note that itCh may be a end iterator (for an empty string, the result is false).
Referenced by readMultiline().
isCharacterEscaped() [2/2]
template<typename Iter > bool icarus::ParsingToolkit::isCharacterEscaped (Iter begin, Iter itCh) const
Definition at line 760 of file ParsingToolkit.h.
isEscape()
bool icarus::ParsingToolkit::isEscape (char ch) const inline
Returns whether ch is an escape character.
Definition at line 375 of file ParsingToolkit.h.
References icarus::ParsingToolkit::Params_t::escape, and fParams.
isQuotationUnclosed()
bool icarus::ParsingToolkit::isQuotationUnclosed (std::string_view sv) const
Returns if the sequence sv has unclosed quotation at its end.
Definition at line 128 of file ParsingToolkit.cxx.
Referenced by readMultiline().
make_view() [1/2]
template<typename BIter , typename EIter > static std::string_view icarus::ParsingToolkit::make_view (BIter b, EIter e) inline static
Creates a std::string_view from two string iterators b and e.
Definition at line 515 of file ParsingToolkit.h.
make_view() [2/2]
static std::string_view icarus::ParsingToolkit::make_view (std::string const & s) inline static
Creates a std::string_view from an entire string s.
Definition at line 510 of file ParsingToolkit.h.
References make_view().
Referenced by make_view(), readMultiline(), and splitWords().
params()
Params_t const & icarus::ParsingToolkit::params () const inline noexcept
Returns the current parameters of parsing.
Definition at line 111 of file ParsingToolkit.h.
References fParams.
Referenced by ParsingToolkit().
readMultiline()
std::pair< std::string, unsigned int > icarus::ParsingToolkit::readMultiline (std::istream & in) const
Returns a single line of text from the input stream.
Parameters
in the input stream
Returns
the string read, and the number of lines read
Exceptions
Error on fatal parsing errors
This function reads entire lines from in, where a line is defined as in std::getline(). If the line ends with an unescaped escape character, another line is read and appended (the escape character is dropped). The return value is the merged string with no end-of-line characters, and the number of lines read. If there is no string to be read, it returns an empty string and 0U.
Special behaviour
If the line ends while a quotation is still open, the next line is also merged, and the line break is kept; to merge quoted lines without preserving the line break character, end the quote on the first line, immediately break the line escaping it, and then next line should immediately start with opening a quotation.
If the line ends while a quotation is still open, it is a parsing error to have the line break character escaped (an exception will be thrown) merged, and the line break is kept.
If the file ends while a quotation is still open, the line is preserved as such.
Definition at line 26 of file ParsingToolkit.cxx.
References fParams, isCharacterEscaped(), isQuotationUnclosed(), and make_view().
removeCommentLine()
template<typename WordType > void icarus::ParsingToolkit::removeCommentLine (std::vector< WordType > & words) const inline
Removes all the words from the one starting with a comment marker.
Parameters
words list of words
The original list is modified, the word starting with a comment marker and all the following ones are removed.
Definition at line 216 of file ParsingToolkit.h.
References findCommentWord().
removeEscapes()
template<typename Words > std::vector< std::string > icarus::ParsingToolkit::removeEscapes (Words const & words) const
Returns a copy of words with all escape characters removed.
Template Parameters
Words type of list of words
Parameters
words the list of words to change
Returns
the list of words without escaping
See also
removeEscapes(std::string)
The escaping is removed from each of the words in the list, which are treated as independent. See removeEscapes(std::string) for the details.
Definition at line 809 of file ParsingToolkit.h.
removeQuotations()
template<typename Words > std::vector< std::string > icarus::ParsingToolkit::removeQuotations (Words const & words) const
Returns a copy of words with no quotation starts and ends.
Template Parameters
Words type of list of words
Parameters
words the list of words to change
Returns
the list of words without quotations
See also
removeQuotations(std::string)
The substitution is applied on each of the words in the list, which are treated as independent. See removeQuotations(std::string) for the details.
Definition at line 822 of file ParsingToolkit.h.
removeTrailingBlanks()
std::string_view icarus::ParsingToolkit::removeTrailingBlanks (std::string_view s) const inline
Consumes the blank characters a the beginning of s.
See also
removeTrailingCharacters()
Definition at line 422 of file ParsingToolkit.h.
References isBlank, and removeTrailingCharacters().
removeTrailingCharacters()
template<typename CType > std::string_view icarus::ParsingToolkit::removeTrailingCharacters (std::string_view s, CType charType) const
Consumes the blank characters a the beginning of s.
Template Parameters
CType type of functor determining which type of character to remove
Parameters
s view of the string to be parsed
charType functor determining which characters to remove
Returns
a view of s starting after its trailing charType characters
See also
removeTrailingBlanks()
Definition at line 793 of file ParsingToolkit.h.
Referenced by removeTrailingBlanks(), and splitWords().
removeWordEscapes() [1/3]
std::string icarus::ParsingToolkit::removeWordEscapes (const char * w) const inline
Returns whether ch is an escape character.
Definition at line 449 of file ParsingToolkit.h.
References removeWordEscapes().
removeWordEscapes() [2/3]
std::string icarus::ParsingToolkit::removeWordEscapes (std::string && w) const
Returns a copy of w with all escape characters removed.
Parameters
w the string to change
Returns
a copy of w without escaping
See also
removeEscapes(Word const&)
The escaping scheme that is applied is just to remove the escape character (no replacement table supported here). An unescaped escape character at the end of the string will not be removed.
It is recommended that this be done as the last step of the parsing, since it changes the meaning of the parsing elements like quotations, comments etc.
Note that applying removeEscapes() more than once will keep removing characters that in the earlier passes were not considered escapes (for example, four escape characters become two in the first pass, one in the second and disappear in the following passes).
Definition at line 158 of file ParsingToolkit.cxx.
Referenced by removeWordEscapes(), and removeWordEscapes().
removeWordEscapes() [3/3]
std::string icarus::ParsingToolkit::removeWordEscapes (std::string_view w) const inline
Returns whether ch is an escape character.
Definition at line 447 of file ParsingToolkit.h.
References removeWordEscapes().
removeWordQuotations() [1/3]
std::string icarus::ParsingToolkit::removeWordQuotations (const char * w) const inline
Returns whether ch is an escape character.
Definition at line 487 of file ParsingToolkit.h.
References removeWordQuotations().
removeWordQuotations() [2/3]
std::string icarus::ParsingToolkit::removeWordQuotations (std::string && w) const
Returns a copy of w with no quotation starts and ends.
Parameters
w the string to change
Returns
the word without quotations
See also
removeQuotations(Words const&)
Escaping is still honored (if present).
Note that applying removeQuotations more than once will keep removing quotation markings that in the earlier passes were not considered such (for example, ‘a1 << "b1 << 'c1 << " or " << c2&rsquo; << b2" << a2will become first a1 << b1 << 'c1 << or << c2' << b2 << a2, and eventually a1 << b1 << c1 << or << c2 << b2 << a2`).
Definition at line 176 of file ParsingToolkit.cxx.
Referenced by removeWordQuotations(), and removeWordQuotations().
removeWordQuotations() [3/3]
std::string icarus::ParsingToolkit::removeWordQuotations (std::string_view w) const inline
Returns whether ch is an escape character.
Definition at line 485 of file ParsingToolkit.h.
References removeWordQuotations().
splitOn()
auto icarus::ParsingToolkit::splitOn (std::string_view sv, std::string_view sep) static
Splits the view sv in three: before sep, sep and after sep.
Parameters
sv view of the string to split
sep a subview of sv to split at
Returns
a SplitView_t object with the three parts split, empty if needed
The view sep is required to be a subview of sv: it's not enough for it to have as content a substring of sv. For example, splitOn("a:1", ":") will not work, because the string "a:1" does not share data in memory with ":".
Even if sep is empty, it's still required to point with both begin() and end() within sv, and sv will be split according to that point.
Definition at line 149 of file ParsingToolkit.cxx.
splitWords() [1/2]
std::vector< std::string_view > icarus::ParsingToolkit::splitWords (std::string const & s) const inline
Helper version of splitWords(std::string const&, Delim).
Definition at line 190 of file ParsingToolkit.h.
References isBlank, and splitWords().
splitWords() [2/2]
template<typename Delim > std::vector< std::string_view > icarus::ParsingToolkit::splitWords (std::string const & s, Delim isDelimiter) const
Splits a string into words.
Template Parameters
Delim type of delimiter functor
Parameters
s the string to be split
isDelimiter (default: isblank()) determines if a character is a word delimiter
Returns
a sequence of views, one per word
The splitter algorithm defines a word separator as a sequence of one or more unescaped, unquoted delimiter characters, where a delimiter is a character ch for which isDelimiter(ch) is true.
Note that this function does not change the content of the data, and in particular it does not remove escaping nor quoting (although it interprets both).
A character used as delimiter can appear in a word only if escaped or within quotation. Contiguous non-delimiter elements of a string, including quoted strings, belong to the same word (for example, a" and "b is a single word when delimitation is by blank characters). An empty word can be introduced only in quotations (e.g. "").
The Delim type is a functor so that isDelimiter(ch) returns something convertible to bool, true if the ch character should be considered a delimiter. Note that no context is provided for the answer, so the use of each character as delimiter is fixed, and modified only by the hard-coded quotation and escaping rules.
The first characters of quotation starts and the escape characters must not be classified as delimiters, or the algorithm will give wrong results.
Definition at line 544 of file ParsingToolkit.h.
References icarus::ParsingToolkit::Params_t::escape, findNextCharacter(), findQuotationEnd(), findQuotationStart(), fParams, fQuoteStarts, make_view(), and removeTrailingCharacters().
Referenced by splitWords().
Member Data Documentation
DefaultParameters
icarus::ParsingToolkit::Params_t const icarus::ParsingToolkit::DefaultParameters static
Definition at line 97 of file ParsingToolkit.h.
fParams
Params_t icarus::ParsingToolkit::fParams private
Parsing parameters.
Definition at line 519 of file ParsingToolkit.h.
Referenced by isEscape(), params(), readMultiline(), and splitWords().
fQuoteStarts
std::string icarus::ParsingToolkit::fQuoteStarts private
Start characters of all supported quotations.
Definition at line 524 of file ParsingToolkit.h.
Referenced by splitWords().
isBlank
CCTypeAdapter<&std::isblank> icarus::ParsingToolkit::isBlank {} static constexpr
Adapter for determining if a character is a blank (see std::isblank()).
Definition at line 92 of file ParsingToolkit.h.
Referenced by findNextBlank(), removeTrailingBlanks(), and splitWords().
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/PMT/Algorithms/ParsingToolkit.h
icaruscode/icaruscode/PMT/Algorithms/ParsingToolkit.cxx