CAF format: icarus::HitRefinerAssociator Class Reference
icarus::HitRefinerAssociator Class Reference
A class handling a collection of hits and its associations.
#include <HitCreator.h>
Public Member Functions
void use_hits (std::unique_ptr< std::vector< icarus::Hit > > &&srchits)
Uses the specified collection as data product.
void put_into (art::Event &)
Moves the data into the event.
void put_into ()
Moves the data into the event.
Constructors
HitRefinerAssociator (art::Event &event, art::InputTag const &HitModuleLabel, std::string instance_name="", bool doWireAssns=true, bool doRawDigitAssns=true)
Constructor: sets instance name and whether to build associations.
HitRefinerAssociator (art::Event &event, art::InputTag const &HitModuleLabel, bool doWireAssns, bool doRawDigitAssns=true)
Constructor: sets instance name and whether to build associations.
Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
size_t size () const
Returns the number of hits currently in the collection.
void put_into (art::Event &)
Moves the data into the event.
void put_into ()
Moves the data into the event.
std::vector< icarus::Hit > const & peek () const
Returns a read-only reference to the current list of hits.
Protected Member Functions
void prepare_associations (std::vector< icarus::Hit > const &srchits)
Finds out the associations for the specified hits.
void prepare_associations ()
Finds out the associations for the current hits.
Protected Member Functions inherited from icarus::HitAndAssociationsWriterBase
HitAndAssociationsWriterBase (art::Event &event, std::string instance_name, bool doWireAssns, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
HitPtr_t CreatePtr (size_t index) const
Creates an art pointer to the hit with the specified index.
Protected Attributes
art::InputTag hits_label
Label of the collection of hits.
Protected Attributes inherited from icarus::HitAndAssociationsWriterBase
std::string prod_instance
Tame of the instance for data products.
std::unique_ptr< std::vector< icarus::Hit > > hits
Collection of hits.
std::unique_ptr< art::Assns< recob::ChannelROI, icarus::Hit > > WireAssns
Associations with wires.
std::unique_ptr< art::Assns< raw::RawDigit, icarus::Hit > > RawDigitAssns
Associations with raw digits.
art::Event * event = nullptr
Pointer to the event we are using.
art::PtrMaker< icarus::Hit > hitPtrMaker
Tool to create hit pointers,.
Additional Inherited Members
Static Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
static void declare_products (art::ProducesCollector &collector, std::string instance_name="", bool doWireAssns=true, bool doRawDigitAssns=true)
Declares the hit products we are going to fill.
Protected Types inherited from icarus::HitAndAssociationsWriterBase
using HitPtr_t = art::Ptr<icarus::Hit>
Type of art pointer to Hit.
Detailed Description
A class handling a collection of hits and its associations.
Use this object if you already have a icarus::Hit data product and another collection that is going to become a data product, and you simply want the new hits associated to the wire and digit with the same channel. No hit-to-hit association is attempted (that would be, incidentally, not supported by art): the data product is used to get all the associated wires and digits, then they are associated to the new hits by channel ID. If a channel is not available, a warning is produced. If different hits on the same channel are associated to different wires or raw digits, an exception is thrown.
Definition at line 787 of file HitCreator.h.
Constructor & Destructor Documentation
HitRefinerAssociator() [1/2]
icarus::HitRefinerAssociator::HitRefinerAssociator (art::Event & event, art::InputTag const & HitModuleLabel, std::string instance_name = "", bool doWireAssns = true, bool doRawDigitAssns = true)
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
HitModuleLabel label of the module used to create hits
instance_name name of the instance for all data products
doWireAssns whether to enable associations to wires
doRawDigitAssns whether to enable associations to raw digits
All the data products (hit collection and associations) will have the specified product instance name.
Definition at line 493 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits.
HitRefinerAssociator() [2/2]
icarus::HitRefinerAssociator::HitRefinerAssociator (art::Event & event, art::InputTag const & HitModuleLabel, bool doWireAssns, bool doRawDigitAssns = true) inline
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
HitModuleLabel label of the module used to create hits
doWireAssns whether to enable associations to wires
doRawDigitAssns whether to enable associations to raw digits
All the data products (hit collection and associations) will have an empty product instance name.
Definition at line 818 of file HitCreator.h.
Member Function Documentation
prepare_associations() [1/2]
void icarus::HitRefinerAssociator::prepare_associations () inline protected
Finds out the associations for the current hits.
Definition at line 868 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::hits, and prepare_associations().
Referenced by prepare_associations(), and put_into().
prepare_associations() [2/2]
void icarus::HitRefinerAssociator::prepare_associations (std::vector< icarus::Hit > const & srchits) protected
Finds out the associations for the specified hits.
Definition at line 519 of file HitCreator.cxx.
References icarus::Hit::Channel(), icarus::HitAndAssociationsWriterBase::CreatePtr(), icarus::HitAndAssociationsWriterBase::event, hits_label, icarus::HitAndAssociationsWriterBase::RawDigitAssns, and icarus::HitAndAssociationsWriterBase::WireAssns.
put_into() [1/2]
void icarus::HitRefinerAssociator::put_into ()
Moves the data into the event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Definition at line 512 of file HitCreator.cxx.
References prepare_associations(), and icarus::HitAndAssociationsWriterBase::put_into().
put_into() [2/2]
void icarus::HitRefinerAssociator::put_into (art::Event &) inline
Moves the data into the event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Deprecated
Use the version with no arguments instead.
Definition at line 850 of file HitCreator.h.
References put_into().
Referenced by put_into().
use_hits()
void icarus::HitRefinerAssociator::use_hits (std::unique_ptr< std::vector< icarus::Hit > > && srchits)
Uses the specified collection as data product.
Parameters
srchits the collection to be used as data product
The very same collection is put into the event. This object will temporary own the collection until the hits are put into the event. If there were previous hits in the object, they are lost.
Definition at line 506 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits.
Member Data Documentation
hits_label
art::InputTag icarus::HitRefinerAssociator::hits_label protected
Label of the collection of hits.
Definition at line 862 of file HitCreator.h.
Referenced by prepare_associations().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/TPC/Utilities/HitCreator.h
icaruscode/icaruscode/TPC/Utilities/HitCreator.cxx