CAF format: icaruscode/icaruscode/Decode/ChannelMapping/ChannelMapDumper.cxx File Reference
ChannelMapDumper.cxx File Reference
Utility dumping the content of PMT channel mapping on screen.
#include "icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.h"
#include "icaruscode/Decode/ChannelMapping/ICARUSChannelMapSQLiteProvider.h"
#include "icaruscode/Decode/ChannelMapping/ICARUSChannelMapPostGresProvider.h"
#include "icaruscode/Decode/ChannelMapping/IICARUSChannelMapProvider.h"
#include "icaruscode/Decode/ChannelMapping/RunPeriods.h"
#include "larcorealg/CoreUtils/enumerate.h"
#include "larcorealg/CoreUtils/counter.h"
#include "larcorealg/TestUtils/unit_test_base.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include <iomanip>
#include <iostream>
#include <algorithm>
#include <memory>
#include <numeric>
#include <array>
Classes
class Pager
Helper to split text in rows.
Functions
void dumpTPCmapping (icarusDB::IICARUSChannelMapProvider const &mapping)
void dumpPMTmapping (icarusDB::IICARUSChannelMapProvider const &mapping)
void dumpCRTmapping (icarusDB::IICARUSChannelMapProvider const &mapping)
void dumpMapping (icarusDB::IICARUSChannelMapProvider const &channelMapping)
int main (int argc, char **argv)
Detailed Description
Utility dumping the content of PMT channel mapping on screen.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
This utility can be run with any configuration file including a configuration for IICARUSChannelMap service featuring a few hard-coded backends.
It may be using art facilities for tool loading, but it does not run in art environment. So it may break without warning and without solution.
Definition in file ChannelMapDumper.cxx.
Function Documentation
dumpCRTmapping()
void dumpCRTmapping (icarusDB::IICARUSChannelMapProvider const & mapping)
Definition at line 195 of file ChannelMapDumper.cxx.
dumpMapping()
void dumpMapping (icarusDB::IICARUSChannelMapProvider const & channelMapping)
Definition at line 221 of file ChannelMapDumper.cxx.
dumpPMTmapping()
void dumpPMTmapping (icarusDB::IICARUSChannelMapProvider const & mapping)
Definition at line 138 of file ChannelMapDumper.cxx.
dumpTPCmapping()
void dumpTPCmapping (icarusDB::IICARUSChannelMapProvider const & mapping)
Returns the number of TPC board IDs known to the service.
Definition at line 60 of file ChannelMapDumper.cxx.
References icarusDB::IICARUSChannelMapProvider::getBoardSlot(), icarusDB::IICARUSChannelMapProvider::getChannelPlanePair(), icarusDB::IICARUSChannelMapProvider::getCrateName(), icarusDB::IICARUSChannelMapProvider::getReadoutBoardToChannelMap(), icarusDB::IICARUSChannelMapProvider::getReadoutBoardVec(), icarusDB::IICARUSChannelMapProvider::hasBoardID(), icarusDB::IICARUSChannelMapProvider::hasFragmentID(), icarusDB::IICARUSChannelMapProvider::nTPCboardIDs(), and icarusDB::IICARUSChannelMapProvider::nTPCfragmentIDs().
main()
int main (int argc, char ** argv)
Definition at line 237 of file ChannelMapDumper.cxx.