CAF format: icarus::trigger::details::EventInfoExtractorMaker Class Reference
icarus::trigger::details::EventInfoExtractorMaker Class Reference
A helper class creating a EventInfoExtractor with a specific setup.
#include <EventInfoUtils.h>
Public Types
using TimeSpan_t = EventInfoExtractor::TimeSpan_t
using EDepTags_t = EventInfoExtractor::EDepTags_t
Public Member Functions
EventInfoExtractorMaker (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, geo::GeometryCore const &geom, detinfo::DetectorPropertiesData const *detProps, detinfo::DetectorTimings const *detTimings, std::string logCategory)
Constructor: stores parameters for construction of EventInfoExtractor.
template<typename ConsumesColl >
EventInfoExtractorMaker (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, geo::GeometryCore const &geom, detinfo::DetectorPropertiesData const *detProps, detinfo::DetectorTimings const *detTimings, std::string logCategory, ConsumesColl &consumesCollector)
EventInfoExtractor make (TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes) const
Creates and returns a new EventInfoExtractor object.
EventInfoExtractor operator() (TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes) const
bool hasGenerated () const
Returns whether we are extracting any generator information.
bool hasEDep () const
Returns whether we are extracting any energy deposition information.
Private Attributes
std::vector< art::InputTag > const fGeneratorTags
EDepTags_t fEnergyDepositTags
std::string const fLogCategory
geo::GeometryCore const & fGeom
detinfo::DetectorPropertiesData const * fDetProps = nullptr
detinfo::DetectorTimings const * fDetTimings = nullptr
Detailed Description
A helper class creating a EventInfoExtractor with a specific setup.
Definition at line 367 of file EventInfoUtils.h.
Member Typedef Documentation
EDepTags_t
using icarus::trigger::details::EventInfoExtractorMaker::EDepTags_t = EventInfoExtractor::EDepTags_t
Definition at line 372 of file EventInfoUtils.h.
TimeSpan_t
using icarus::trigger::details::EventInfoExtractorMaker::TimeSpan_t = EventInfoExtractor::TimeSpan_t
Definition at line 371 of file EventInfoUtils.h.
Constructor & Destructor Documentation
EventInfoExtractorMaker() [1/2]
icarus::trigger::details::EventInfoExtractorMaker::EventInfoExtractorMaker (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, geo::GeometryCore const & geom, detinfo::DetectorPropertiesData const * detProps, detinfo::DetectorTimings const * detTimings, std::string logCategory)
Constructor: stores parameters for construction of EventInfoExtractor.
Definition at line 356 of file EventInfoUtils.cxx.
EventInfoExtractorMaker() [2/2]
template<typename ConsumesColl > icarus::trigger::details::EventInfoExtractorMaker::EventInfoExtractorMaker (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, geo::GeometryCore const & geom, detinfo::DetectorPropertiesData const * detProps, detinfo::DetectorTimings const * detTimings, std::string logCategory, ConsumesColl & consumesCollector)
Constructor: stores parameters for construction of EventInfoExtractor and declares consumables.
Definition at line 607 of file EventInfoUtils.h.
References icarus::trigger::details::EventInfoExtractor::declareConsumables().
Member Function Documentation
hasEDep()
bool icarus::trigger::details::EventInfoExtractorMaker::hasEDep () const inline
Returns whether we are extracting any energy deposition information.
Definition at line 413 of file EventInfoUtils.h.
References icarus::trigger::details::EventInfoExtractor::isEDepSpecified().
Referenced by icarus::trigger::TriggerEfficiencyPlotsBase::useEDep().
hasGenerated()
bool icarus::trigger::details::EventInfoExtractorMaker::hasGenerated () const inline
Returns whether we are extracting any generator information.
Definition at line 410 of file EventInfoUtils.h.
Referenced by icarus::trigger::TriggerEfficiencyPlotsBase::useGen().
make()
icarus::trigger::details::EventInfoExtractor icarus::trigger::details::EventInfoExtractorMaker::make (TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes) const
Creates and returns a new EventInfoExtractor object.
Definition at line 375 of file EventInfoUtils.cxx.
operator()()
EventInfoExtractor icarus::trigger::details::EventInfoExtractorMaker::operator() (TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes) const inline
Definition at line 403 of file EventInfoUtils.h.
Member Data Documentation
fDetProps
detinfo::DetectorPropertiesData const* icarus::trigger::details::EventInfoExtractorMaker::fDetProps = nullptr private
Definition at line 423 of file EventInfoUtils.h.
fDetTimings
detinfo::DetectorTimings const* icarus::trigger::details::EventInfoExtractorMaker::fDetTimings = nullptr private
Definition at line 424 of file EventInfoUtils.h.
fEnergyDepositTags
EDepTags_t icarus::trigger::details::EventInfoExtractorMaker::fEnergyDepositTags private
Definition at line 420 of file EventInfoUtils.h.
fGeneratorTags
std::vector<art::InputTag> const icarus::trigger::details::EventInfoExtractorMaker::fGeneratorTags private
Definition at line 419 of file EventInfoUtils.h.
fGeom
geo::GeometryCore const& icarus::trigger::details::EventInfoExtractorMaker::fGeom private
Definition at line 422 of file EventInfoUtils.h.
fLogCategory
std::string const icarus::trigger::details::EventInfoExtractorMaker::fLogCategory private
Definition at line 421 of file EventInfoUtils.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.cxx