CAF format: icarus::opdet::AsymExpPulseFunction< T > Class Template Reference
icarus::opdet::AsymExpPulseFunction< T > Class Template Reference
Describes the waveform from a single photoelectron.
#include <AsymExpPulseFunction.h>
Public Types
using ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
using Time = typename Base_t::Time
Type of time being used.
Public Types inherited from icarus::opdet::PhotoelectronPulseFunction< T >
using ADCcount = util::quantities::counts_f
Type for ADC counts (floating point).
using Time = T
Type of time being used.
Public Member Functions
AsymExpPulseFunction (ADCcount amplitude, Time peakTime, Time raiseTau, Time fallTau)
Constructor: assigns the parameters of the shape.
Parameter accessors.
Time raiseTau () const
Time fallTau () const
ADCcount amplitude () const
Public Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
ADCcount evaluateAt (Time time) const
Evaluates the pulse at the given time.
ADCcount operator() (Time time) const
Alias of evaluateAt().
Time peakTime () const
Returns the time at which the first peak is found.
ADCcount peakAmplitude () const
Returns the amplitude of the first peak in ADC counts.
ADCcount baseline () const
Returns the baseline of the pulse in ADC counts.
int polarity () const
Returns the polarity of the pulse (+1: positive, or -1: negative).
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints on stream the parameters of this shape.
void dump (std::ostream &&out, std::string const &indent="") const
std::string toString (std::string const &indent, std::string const &firstIndent) const
Returns the parameters of this shape as a descriptive string.
std::string toString (std::string const &indent="") const
Static Public Member Functions
static double Exponential (Time t, Time tau)
Returns the value of an exponential: exp(-t/tau).
static double ExponentialDiff (Time t, Time raise, Time fall)
Returns the value of an exponential: exp(-t/tau).
Private Types
using Base_t = icarus::opdet::PhotoelectronPulseFunction<T>
Private Member Functions
Time myPeakTime () const
Returns the time of the peak.
ADCcount myAmplitude () const
Returns the amplitude of the pulse from the baseline, including its sign.
virtual ADCcount doEvaluateAt (Time time) const override
Evaluates the pulse at the given time.
virtual Time doPeakTime () const override
Returns the time at which the first peak is found.
virtual ADCcount doPeakAmplitude () const override
Returns the amplitude of the first peak in ADC counts.
virtual void doDump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const override
Prints on stream the parameters of this shape.
Static Private Member Functions
static Time expDiffPeak (Time raiseTau, Time fallTau)
Returns the time value at which ExponentialDiff() is maximum.
template<typename V >
static V round (V value)
Private Attributes
ADCcount const fAmplitude
Amplitude at peak (transition).
Time const fPeakTime
Time of maximum signal.
Time const fRaiseTau
Time constant of signal rise.
Time const fFallTau
Time constant of signal fall.
Time const fRaiseTime
Time when the signal starts rising above baseline.
ADCcount const fA
Normalization factor in the functional form.
Additional Inherited Members
Protected Member Functions inherited from icarus::opdet::PhotoelectronPulseFunction< T >
virtual ADCcount doBaseline () const
Returns the baseline of the pulse.
virtual int doPolarity () const
Returns the polarity of the pulse (+1 or -1).
Detailed Description
template<typename T>
class icarus::opdet::AsymExpPulseFunction< T >
Describes the waveform from a single photoelectron.
Template Parameters
Time type of time unit to be used
This functor (class behaving like a function) describes the shape of the response to a single photoelectron as an exponentially raising and then exponentially falling shape:
\[ A \left[ exp(-(t - t_{0})/\tau_{s}) - exp(-(t - t_{0})/\tau) \right] \]
with \(\tau_{s} \) the rise time and \(\tau \) the fall time; \(t_{0} \) is the start of the signal formation, i.e. the time at which the signal starts raising.
Note that \(t_{0} \) is not the peak time, and \(A \) is not the peak amplitude of the signal.
Definition at line 50 of file AsymExpPulseFunction.h.
Member Typedef Documentation
ADCcount
template<typename T > using icarus::opdet::AsymExpPulseFunction< T >::ADCcount = typename Base_t::ADCcount
Type for ADC counts (floating point).
Definition at line 57 of file AsymExpPulseFunction.h.
Base_t
template<typename T > using icarus::opdet::AsymExpPulseFunction< T >::Base_t = icarus::opdet::PhotoelectronPulseFunction<T> private
Definition at line 53 of file AsymExpPulseFunction.h.
Time
template<typename T > using icarus::opdet::AsymExpPulseFunction< T >::Time = typename Base_t::Time
Type of time being used.
Definition at line 59 of file AsymExpPulseFunction.h.
Constructor & Destructor Documentation
AsymExpPulseFunction()
template<typename T > icarus::opdet::AsymExpPulseFunction< T >::AsymExpPulseFunction (ADCcount amplitude, Time peakTime, Time raiseTau, Time fallTau)
Constructor: assigns the parameters of the shape.
Parameters
amplitude the maximum amplitudes of the shape (at transition)
peakTime the time of the maximum amplitude of the shape
raiseTau the raise time (exponential parameter) of the shape
fallTau the decay time (exponential parameter) of the shape
The time parameters (peakTime, raiseTau and fallTau) must be measured in same unit. The peakTime defines the position of the shape with respect to time 0.
Note
The construction parameters are not the ones described by the functional form documented in the class, \(A \left[ exp(-(t - t_{0})/\tau_{s}) - exp(-(t - t_{0})/\tau) \right] \): the amplitude parameter is the actual maximum of the signal response, and peakTime is the actual time at which the signal peaks. These parameters are more easily read from a measured waveform.
Definition at line 165 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::fA.
Member Function Documentation
amplitude()
template<typename T > ADCcount icarus::opdet::AsymExpPulseFunction< T >::amplitude () const inline
Definition at line 94 of file AsymExpPulseFunction.h.
doDump()
template<typename T > void icarus::opdet::AsymExpPulseFunction< T >::doDump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const override private virtual
Prints on stream the parameters of this shape.
Parameters
out the stream to write into
indent indentation string, prepended to all lines except first
indentFirst indentation string prepended to the first line
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 196 of file AsymExpPulseFunction.h.
doEvaluateAt()
template<typename T > auto icarus::opdet::AsymExpPulseFunction< T >::doEvaluateAt (Time time) const override private virtual
Evaluates the pulse at the given time.
Parameters
time time to evaluate the shape at
The scale of the time is defined by the transition time passed at construction.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 185 of file AsymExpPulseFunction.h.
doPeakAmplitude()
template<typename T > virtual ADCcount icarus::opdet::AsymExpPulseFunction< T >::doPeakAmplitude () const inline override private virtual
Returns the amplitude of the first peak in ADC counts.
Reimplemented from icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 135 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::myAmplitude().
doPeakTime()
template<typename T > virtual Time icarus::opdet::AsymExpPulseFunction< T >::doPeakTime () const inline override private virtual
Returns the time at which the first peak is found.
Implements icarus::opdet::PhotoelectronPulseFunction< T >.
Definition at line 132 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::myPeakTime().
expDiffPeak()
template<typename T > auto icarus::opdet::AsymExpPulseFunction< T >::expDiffPeak (Time raiseTau, Time fallTau) static private
Returns the time value at which ExponentialDiff() is maximum.
Definition at line 213 of file AsymExpPulseFunction.h.
Exponential()
template<typename T > static double icarus::opdet::AsymExpPulseFunction< T >::Exponential (Time t, Time tau) inline static
Returns the value of an exponential: exp(-t/tau).
Definition at line 99 of file AsymExpPulseFunction.h.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::ExponentialDiff().
ExponentialDiff()
template<typename T > static double icarus::opdet::AsymExpPulseFunction< T >::ExponentialDiff (Time t, Time raise, Time fall) inline static
Returns the value of an exponential: exp(-t/tau).
Definition at line 102 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::Exponential().
fallTau()
template<typename T > Time icarus::opdet::AsymExpPulseFunction< T >::fallTau () const inline
Definition at line 93 of file AsymExpPulseFunction.h.
myAmplitude()
template<typename T > ADCcount icarus::opdet::AsymExpPulseFunction< T >::myAmplitude () const inline private
Returns the amplitude of the pulse from the baseline, including its sign.
Definition at line 118 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::fAmplitude.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::doPeakAmplitude().
myPeakTime()
template<typename T > Time icarus::opdet::AsymExpPulseFunction< T >::myPeakTime () const inline private
Returns the time of the peak.
Definition at line 115 of file AsymExpPulseFunction.h.
References icarus::opdet::AsymExpPulseFunction< T >::fPeakTime.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::doPeakTime().
raiseTau()
template<typename T > Time icarus::opdet::AsymExpPulseFunction< T >::raiseTau () const inline
Definition at line 92 of file AsymExpPulseFunction.h.
round()
template<typename T > template<typename V > static V icarus::opdet::AsymExpPulseFunction< T >::round (V value) inline static private
Definition at line 155 of file AsymExpPulseFunction.h.
Member Data Documentation
fA
template<typename T > ADCcount const icarus::opdet::AsymExpPulseFunction< T >::fA private
Normalization factor in the functional form.
Definition at line 112 of file AsymExpPulseFunction.h.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::AsymExpPulseFunction().
fAmplitude
template<typename T > ADCcount const icarus::opdet::AsymExpPulseFunction< T >::fAmplitude private
Amplitude at peak (transition).
Definition at line 106 of file AsymExpPulseFunction.h.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::myAmplitude().
fFallTau
template<typename T > Time const icarus::opdet::AsymExpPulseFunction< T >::fFallTau private
Time constant of signal fall.
Definition at line 109 of file AsymExpPulseFunction.h.
fPeakTime
template<typename T > Time const icarus::opdet::AsymExpPulseFunction< T >::fPeakTime private
Time of maximum signal.
Definition at line 107 of file AsymExpPulseFunction.h.
Referenced by icarus::opdet::AsymExpPulseFunction< T >::myPeakTime().
fRaiseTau
template<typename T > Time const icarus::opdet::AsymExpPulseFunction< T >::fRaiseTau private
Time constant of signal rise.
Definition at line 108 of file AsymExpPulseFunction.h.
fRaiseTime
template<typename T > Time const icarus::opdet::AsymExpPulseFunction< T >::fRaiseTime private
Time when the signal starts rising above baseline.
Definition at line 111 of file AsymExpPulseFunction.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Algorithms/AsymExpPulseFunction.h