CAF format: sbn::OpDetWaveformMetaMaker Class Reference
sbn::OpDetWaveformMetaMaker Class Reference
Converter from raw::OpDetWaveform into sbn::OpDetWaveformMeta.
#include <OpDetWaveformMetaUtils.h>
Public Types
using microseconds = util::quantities::intervals::microseconds
using electronics_time = detinfo::timescales::electronics_time
Public Member Functions
OpDetWaveformMetaMaker (detinfo::DetectorTimings const &detTimings)
OpDetWaveformMetaMaker (microseconds opDetTickPeriod, raw::Trigger const &trigger)
OpDetWaveformMetaMaker (microseconds opDetTickPeriod)
OpDetWaveformMetaMaker (microseconds opDetTickPeriod, electronics_time triggerTime, electronics_time beamTime)
sbn::OpDetWaveformMeta make (raw::OpDetWaveform const &waveform) const
Creates a sbn::OpDetWaveformMeta out of the specified waveform.
sbn::OpDetWaveformMeta operator() (raw::OpDetWaveform const &waveform) const
Private Attributes
microseconds fOpDetTickPeriod
The duration of a optical detector tick.
std::optional< electronics_time > fTriggerTime
Cached trigger time.
std::optional< electronics_time > fBeamGateTime
Cached beam gate time.
Detailed Description
Converter from raw::OpDetWaveform into sbn::OpDetWaveformMeta.
An object of this class is initialized once with some timings (e.g. once per event), and then used to make() multiple sbn::OpDetWaveformMeta:
detinfo::DetectorTimings const detTimings = detinfo::makeDetectorTimings
  (art::ServiceHandle<detinfo::DetectorClocksService const>()->DataFor(event));
std::vector<sbn::OpDetWaveformMeta> PMTinfo;
sbn::OpDetWaveformMetaMaker const makeMetadata{ detTimings };
for (raw::OpDetWaveform const& waveform: waveforms)
  PMTinfo.push_back(makeMetadata(waveform));
It supports a scenario where times (trigger and beam gate) are not available or not relevant, in which case only the duration in time of a optical detector waveform tick is needed.
Definition at line 151 of file OpDetWaveformMetaUtils.h.
Member Typedef Documentation
electronics_time
using sbn::OpDetWaveformMetaMaker::electronics_time = detinfo::timescales::electronics_time
Definition at line 157 of file OpDetWaveformMetaUtils.h.
microseconds
using sbn::OpDetWaveformMetaMaker::microseconds = util::quantities::intervals::microseconds
Definition at line 155 of file OpDetWaveformMetaUtils.h.
Constructor & Destructor Documentation
OpDetWaveformMetaMaker() [1/4]
sbn::OpDetWaveformMetaMaker::OpDetWaveformMetaMaker (detinfo::DetectorTimings const & detTimings)
Constructor: allows creation of sbn::OpDetWaveformMeta with full information.
Definition at line 25 of file OpDetWaveformMetaUtils.cxx.
OpDetWaveformMetaMaker() [2/4]
sbn::OpDetWaveformMetaMaker::OpDetWaveformMetaMaker (microseconds opDetTickPeriod, raw::Trigger const & trigger)
Constructor: allows creation of sbn::OpDetWaveformMeta with no detector clocks service.
Definition at line 43 of file OpDetWaveformMetaUtils.cxx.
OpDetWaveformMetaMaker() [3/4]
sbn::OpDetWaveformMetaMaker::OpDetWaveformMetaMaker (microseconds opDetTickPeriod)
Constructor: allows creation of sbn::OpDetWaveformMeta with no trigger/beam time information.
Definition at line 36 of file OpDetWaveformMetaUtils.cxx.
OpDetWaveformMetaMaker() [4/4]
sbn::OpDetWaveformMetaMaker::OpDetWaveformMetaMaker (microseconds opDetTickPeriod, electronics_time triggerTime, electronics_time beamTime)
Constructor: allows creation of sbn::OpDetWaveformMeta with explicit trigger/beam time information.
Definition at line 54 of file OpDetWaveformMetaUtils.cxx.
Member Function Documentation
make()
sbn::OpDetWaveformMeta sbn::OpDetWaveformMetaMaker::make (raw::OpDetWaveform const & waveform) const
Creates a sbn::OpDetWaveformMeta out of the specified waveform.
Definition at line 65 of file OpDetWaveformMetaUtils.cxx.
References sbn::OpDetWaveformMeta::ChannelNumber(), sbn::OpDetWaveformMeta::bits::WithBeamGate, and sbn::OpDetWaveformMeta::bits::WithTrigger.
Referenced by sbn::makeOpDetWaveformMeta(), sbn::makeOpDetWaveformMeta(), and sbn::makeOpDetWaveformMeta().
operator()()
sbn::OpDetWaveformMeta sbn::OpDetWaveformMetaMaker::operator() (raw::OpDetWaveform const & waveform) const inline
Definition at line 182 of file OpDetWaveformMetaUtils.h.
Member Data Documentation
fBeamGateTime
std::optional<electronics_time> sbn::OpDetWaveformMetaMaker::fBeamGateTime private
Cached beam gate time.
Definition at line 191 of file OpDetWaveformMetaUtils.h.
fOpDetTickPeriod
microseconds sbn::OpDetWaveformMetaMaker::fOpDetTickPeriod private
The duration of a optical detector tick.
Definition at line 188 of file OpDetWaveformMetaUtils.h.
fTriggerTime
std::optional<electronics_time> sbn::OpDetWaveformMetaMaker::fTriggerTime private
Cached trigger time.
Definition at line 190 of file OpDetWaveformMetaUtils.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Algorithms/OpDetWaveformMetaUtils.h
icaruscode/icaruscode/PMT/Algorithms/OpDetWaveformMetaUtils.cxx