CAF format: icarus::trigger::WaveformWithBaseline Struct Reference
icarus::trigger::WaveformWithBaseline Struct Reference
Object to carry around waveform ant its baseline.
#include <TriggerGateBuilder.h>
Public Types
using Waveform_t = raw::OpDetWaveform
using Baseline_t = icarus::WaveformBaseline
using Base_t = std::tuple<Waveform_t const*, Baseline_t const*>
Public Member Functions
Waveform_t const & waveform () const
Returns a reference to the waveform.
Baseline_t const & baseline () const
Returns a reference to the waveform baseline.
Waveform_t const * waveformPtr () const
Returns a pointer to the waveform.
Baseline_t const * baselinePtr () const
Returns a pointer to the waveform baseline.
bool hasBaseline () const
Returns whether the baseline is available for this waveform.
operator Waveform_t const & () const
operator Waveform_t const * () const
operator Baseline_t const & () const
operator Baseline_t const * () const
Detailed Description
Object to carry around waveform ant its baseline.
Definition at line 56 of file TriggerGateBuilder.h.
Member Typedef Documentation
Base_t
using icarus::trigger::WaveformWithBaseline::Base_t = std::tuple<Waveform_t const*, Baseline_t const*>
Definition at line 62 of file TriggerGateBuilder.h.
Baseline_t
using icarus::trigger::WaveformWithBaseline::Baseline_t = icarus::WaveformBaseline
Definition at line 61 of file TriggerGateBuilder.h.
Waveform_t
using icarus::trigger::WaveformWithBaseline::Waveform_t = raw::OpDetWaveform
Definition at line 60 of file TriggerGateBuilder.h.
Member Function Documentation
baseline()
Baseline_t const & icarus::trigger::WaveformWithBaseline::baseline () const inline
Returns a reference to the waveform baseline.
Definition at line 70 of file TriggerGateBuilder.h.
References baselinePtr().
baselinePtr()
Baseline_t const * icarus::trigger::WaveformWithBaseline::baselinePtr () const inline
Returns a pointer to the waveform baseline.
Definition at line 77 of file TriggerGateBuilder.h.
Referenced by baseline(), and hasBaseline().
hasBaseline()
bool icarus::trigger::WaveformWithBaseline::hasBaseline () const inline
Returns whether the baseline is available for this waveform.
Definition at line 81 of file TriggerGateBuilder.h.
References baselinePtr().
operator Baseline_t const &()
icarus::trigger::WaveformWithBaseline::operator Baseline_t const & () const inline
Definition at line 87 of file TriggerGateBuilder.h.
operator Baseline_t const *()
icarus::trigger::WaveformWithBaseline::operator Baseline_t const * () const inline
Definition at line 88 of file TriggerGateBuilder.h.
operator Waveform_t const &()
icarus::trigger::WaveformWithBaseline::operator Waveform_t const & () const inline
Definition at line 85 of file TriggerGateBuilder.h.
operator Waveform_t const *()
icarus::trigger::WaveformWithBaseline::operator Waveform_t const * () const inline
Definition at line 86 of file TriggerGateBuilder.h.
waveform()
Waveform_t const & icarus::trigger::WaveformWithBaseline::waveform () const inline
Returns a reference to the waveform.
Definition at line 67 of file TriggerGateBuilder.h.
References waveformPtr().
waveformPtr()
Waveform_t const * icarus::trigger::WaveformWithBaseline::waveformPtr () const inline
Returns a pointer to the waveform.
Definition at line 73 of file TriggerGateBuilder.h.
Referenced by waveform().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/TriggerGateBuilder.h