CAF format: icarus::trigger::details::EventInfoExtractor Class Reference
icarus::trigger::details::EventInfoExtractor Class Reference
Extracts from event the relevant information on the physics event.
#include <EventInfoUtils.h>
Classes
struct CategorizedInputTag
Utility tag to identify a parameter as a specific type of tag.
Public Types
enum class InputType { EnergyDeposits , EnergyDepositSummary , SimChannels , Unknown }
Enumerator of possible inputs.
using simulation_time = detinfo::timescales::simulation_time
using TimeSpan_t = std::pair<simulation_time, simulation_time>
using SimEnergyDepositSummaryInputTag = CategorizedInputTag<InputType::EnergyDepositSummary>
Utility tag to identify a parameter as for SimEnergyDepositSummary tag.
using SimChannelsInputTag = CategorizedInputTag<InputType::SimChannels>
Utility tag to identify a parameter as for sim::SimChannel tag.
using EDepTags_t
Type to specify the source of energy deposition information, if any.
Public Member Functions
template<typename Event >
EventInfo_t extractInfo (Event const &event) const
Returns an EventInfo_t object with information from event.
template<typename Event >
EventInfo_t operator() (Event const &event) const
bool hasGenerated () const
Returns whether we are extracting any generator information.
bool hasEDep () const
Returns whether we are extracting any energy deposition information.
template<typename Event >
auto extractInfo (Event const &event) const -> EventInfo_t
Constructors
Constructors are available to take advantage of specific art features, and for the generic art/_gallery_ compatible interfaces.
EventInfoExtractor (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes, geo::GeometryCore const &geom, detinfo::DetectorPropertiesData const *detProps, detinfo::DetectorTimings const *detTimings, std::string logCategory="EventInfoExtractor")
Constructor: configures the object.
template<typename ConsumesColl >
EventInfoExtractor (std::vector< art::InputTag > truthTags, std::vector< art::InputTag > edepTags, TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes, geo::GeometryCore const &geom, detinfo::DetectorPropertiesData const *detProps, detinfo::DetectorTimings const *detTimings, std::string logCategory, ConsumesColl &consumesCollector)
Constructor: configures, and declares consuming data product.
Static Public Member Functions
static bool isEDepSummaryTag (EDepTags_t const &edepTag)
Returns whether edepTags contains a energy deposition summary tag.
static bool isEDepListTag (EDepTags_t const &edepTag)
Returns whether edepTags contains energy deposition list tags.
static bool isEDepSpecified (EDepTags_t const &edepTag)
Returns whether edepTags contains any energy deposition tag.
Static Public Attributes
static EDepTags_t const NoEDepTags {}
Represents the absence of any energy deposition information.
Private Member Functions
bool useEnergyDepositSummary () const
Returns whether we use energy summary instead of full energy deposits.
void fillGeneratorInfo (EventInfo_t &info, simb::MCTruth const &truth) const
Fills info record with generation information from truth.
void fillGeneratorNeutrinoInfo (EventInfo_t &info, simb::MCTruth const &truth) const
Fills info record with generated neutrino information from truth.
void setMainGeneratorNeutrinoInfo (EventInfo_t &info, simb::MCTruth const &truth) const
void addGeneratorNeutrinoInfo (EventInfo_t &info, simb::MCTruth const &truth) const
void addEnergyDepositionInfo (EventInfo_t &info, std::vector< sim::SimEnergyDeposit > const &energyDeposits) const
Adds the energy depositions from energyDeposits into info record.
void addEnergyDepositionInfo (EventInfo_t &info, std::vector< sim::SimChannel > const &channels) const
Adds the energy depositions from channels into info record.
geo::TPCGeo const * pointInTPC (geo::Point_t const &point) const
Returns in which TPC volume point falls in (nullptr if none).
geo::TPCGeo const * pointInActiveTPC (geo::Point_t const &point) const
Returns in which active TPC volume point falls in (nullptr if none).
simulation_time getInteractionTime (simb::MCTruth const &truth) const
Static Private Member Functions
template<typename ConsumesColl >
static void declareConsumables (ConsumesColl &consumesCollector, std::vector< art::InputTag > const &truthTags, EDepTags_t const &edepTags)
Declares all the consumables to the collector.
Private Attributes
friend EventInfoExtractorMaker
std::vector< art::InputTag > const fGeneratorTags
List of truth data product tags (std::vector<simb::MCTruth>).
EDepTags_t const fEnergyDepositTags
std::string const fLogCategory
Stream name for message facility.
geo::GeometryCore const & fGeom
Geometry service provider.
detinfo::DetectorPropertiesData const * fDetProps = nullptr
Detector timing conversion utility.
detinfo::DetectorTimings const * fDetTimings = nullptr
TimeSpan_t const fInSpillTimes
Start and stop time for "in spill" label.
TimeSpan_t const fInPreSpillTimes
Start and stop time for "pre-spill" label.
Detailed Description
Extracts from event the relevant information on the physics event.
This returns a EventInfo_t object filled as completely as possible.
The EventInfo_t is managed so that it contains all the information about the "main" neutrino interaction. All other neutrino interactions are acknowledged but their information is not stored, with minor exceptions. Currently:
the main interaction is the interaction happening the earliest;
the other interactions have only their location (Vertices()) stored in the list; the order of the vertices in the list stays the same as the order they are filled, with the exception of the main interaction that is always moved in front() of the list. This means that interaction vertices are not ordered by time unless that is how they were fed to this object.
This class can read any data product in the event, and is completely configured at construction time via constructor arguments. If information is needed from a data product that is not read yet, the following actions are needed:
decide the input tag of the data product(s) to be read; this is usually delegated to the user via a configuration parameter;
the required input tags need to be stored into data members;
art needs to be informed of the intention of reading the data products via consumes() or equivalent calls; this class can take care of that, if a art::ConsumesCollector object is provided;
the data product can be read with the usual means.
Energy deposition
The energy deposition information is event-wide and does not select depositions from any specific interaction.
The energy depositions are grouped according to whether they are within the time interval of the beam spill window, a pre-spill window, or at any time; and whether they are in the active volume or anywhere. The depositions can be collected from a sim::SimEnergyDeposit list of data products or (not recommended) from a single sim::SimChannel data product. In the latter case, the depositions are extracted from the channels on the first interaction plane (always plane 0 according to LArSoft definitions), which is usually the largest of the planes.
Definition at line 99 of file EventInfoUtils.h.
Member Typedef Documentation
EDepTags_t
using icarus::trigger::details::EventInfoExtractor::EDepTags_t
Initial value:
 std::variant<
    std::vector<art::InputTag>,
    SimEnergyDepositSummaryInputTag,
    SimChannelsInputTag
    >
Type to specify the source of energy deposition information, if any.
Definition at line 144 of file EventInfoUtils.h.
SimChannelsInputTag
using icarus::trigger::details::EventInfoExtractor::SimChannelsInputTag = CategorizedInputTag<InputType::SimChannels>
Utility tag to identify a parameter as for sim::SimChannel tag.
Definition at line 140 of file EventInfoUtils.h.
SimEnergyDepositSummaryInputTag
using icarus::trigger::details::EventInfoExtractor::SimEnergyDepositSummaryInputTag = CategorizedInputTag<InputType::EnergyDepositSummary>
Utility tag to identify a parameter as for SimEnergyDepositSummary tag.
Definition at line 137 of file EventInfoUtils.h.
simulation_time
using icarus::trigger::details::EventInfoExtractor::simulation_time = detinfo::timescales::simulation_time
Definition at line 103 of file EventInfoUtils.h.
TimeSpan_t
using icarus::trigger::details::EventInfoExtractor::TimeSpan_t = std::pair<simulation_time, simulation_time>
Definition at line 104 of file EventInfoUtils.h.
Member Enumeration Documentation
InputType
enum class icarus::trigger::details::EventInfoExtractor::InputType strong
Enumerator of possible inputs.
Definition at line 107 of file EventInfoUtils.h.
Constructor & Destructor Documentation
EventInfoExtractor() [1/2]
icarus::trigger::details::EventInfoExtractor::EventInfoExtractor (std::vector< art::InputTag > truthTags, EDepTags_t edepTags, TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes, geo::GeometryCore const & geom, detinfo::DetectorPropertiesData const * detProps, detinfo::DetectorTimings const * detTimings, std::string logCategory = "EventInfoExtractor")
Constructor: configures the object.
Parameters
truthTags list of truth information data products to be read
edepTags list of energy deposition data products to be read
inSpillTimes start and end of spill, in simulation time
inPreSpillTimes start and end of pre-spill, in simulation time
geom LArSoft geometry service provider
detTimingsPtr pointer to LArSoft detector timings utility
logCategory name of message facility stream to sent messages to
See also
EventInfoExtractor(std::vector<art::InputTag> const&, ConsumesColl&)
In art framework context, prefer the EventInfoExtractor(std::vector<art::InputTag> const&, ConsumesColl&) constructor.
Two formats of energy depositions are supported:
standard LArSoft (std::vector<sim::SimEnergyDeposit>): specify a vector of input tags in edepTags argument;
ICARUS deposited energy summary: specify an input tag converted into a SimEnergyDepositSummaryInputTag parameter in edepTags argument.
Definition at line 97 of file EventInfoUtils.cxx.
EventInfoExtractor() [2/2]
template<typename ConsumesColl > icarus::trigger::details::EventInfoExtractor::EventInfoExtractor (std::vector< art::InputTag > truthTags, std::vector< art::InputTag > edepTags, TimeSpan_t inSpillTimes, TimeSpan_t inPreSpillTimes, geo::GeometryCore const & geom, detinfo::DetectorPropertiesData const * detProps, detinfo::DetectorTimings const * detTimings, std::string logCategory, ConsumesColl & consumesCollector)
Constructor: configures, and declares consuming data product.
Template Parameters
ConsumesColl type with art::ConsumesCollector interface
Parameters
truthTags list of truth information data products to be read
edepTags list of energy deposition data products to be read
inSpillTimes start and end of spill, in simulation time
inPreSpillTimes start and end of pre-spill, in simulation time
geom LArSoft geometry service provider
detTimings LArSoft detector timings utility
logCategory name of message facility stream to sent messages to
consumesCollector object to declare the consumed products to
Typical usage is within a art module constructor:
icarus::trigger::details::EventInfoExtractor const eventInfoFrom {
  { art:InputTag{ "generator" } },
  consumesCollector()
  };
Definition at line 458 of file EventInfoUtils.h.
References declareConsumables(), fEnergyDepositTags, and fGeneratorTags.
Member Function Documentation
addEnergyDepositionInfo() [1/2]
void icarus::trigger::details::EventInfoExtractor::addEnergyDepositionInfo (EventInfo_t & info, std::vector< sim::SimChannel > const & channels) const private
Adds the energy depositions from channels into info record.
Definition at line 264 of file EventInfoUtils.cxx.
addEnergyDepositionInfo() [2/2]
void icarus::trigger::details::EventInfoExtractor::addEnergyDepositionInfo (EventInfo_t & info, std::vector< sim::SimEnergyDeposit > const & energyDeposits) const private
Adds the energy depositions from energyDeposits into info record.
Definition at line 228 of file EventInfoUtils.cxx.
addGeneratorNeutrinoInfo()
void icarus::trigger::details::EventInfoExtractor::addGeneratorNeutrinoInfo (EventInfo_t & info, simb::MCTruth const & truth) const private
Adds selected information from the interaction in truth to info record.
Definition at line 205 of file EventInfoUtils.cxx.
declareConsumables()
template<typename ConsumesColl > void icarus::trigger::details::EventInfoExtractor::declareConsumables (ConsumesColl & consumesCollector, std::vector< art::InputTag > const & truthTags, EDepTags_t const & edepTags) static private
Declares all the consumables to the collector.
Definition at line 571 of file EventInfoUtils.h.
Referenced by EventInfoExtractor(), and icarus::trigger::details::EventInfoExtractorMaker::EventInfoExtractorMaker().
extractInfo() [1/2]
template<typename Event > EventInfo_t icarus::trigger::details::EventInfoExtractor::extractInfo (Event const & event) const
Returns an EventInfo_t object with information from event.
Template Parameters
Event type of event to read data from (art or gallery event)
Parameters
event event record to read the information from
Returns
a EventInfo_t with information extracted from event
extractInfo() [2/2]
template<typename Event > auto icarus::trigger::details::EventInfoExtractor::extractInfo (Event const & event) const -> EventInfo_t
Definition at line 481 of file EventInfoUtils.h.
fillGeneratorInfo()
void icarus::trigger::details::EventInfoExtractor::fillGeneratorInfo (EventInfo_t & info, simb::MCTruth const & truth) const private
Fills info record with generation information from truth.
Definition at line 120 of file EventInfoUtils.cxx.
fillGeneratorNeutrinoInfo()
void icarus::trigger::details::EventInfoExtractor::fillGeneratorNeutrinoInfo (EventInfo_t & info, simb::MCTruth const & truth) const private
Fills info record with generated neutrino information from truth.
If info record already contains an interaction (the "main" interaction), the interaction in truth becomes the new main interaction of info only if it is earlier than the old main interaction. Otherwise the record is updated to take note that there was yet another interaction in the event, with little-to-no information about it stored.
Definition at line 130 of file EventInfoUtils.cxx.
getInteractionTime()
auto icarus::trigger::details::EventInfoExtractor::getInteractionTime (simb::MCTruth const & truth) const private
Returns the time of the neutrino interaction in truth.
Undefined behaviour if the truth information does not describe a neutrino interaction.
Definition at line 344 of file EventInfoUtils.cxx.
hasEDep()
bool icarus::trigger::details::EventInfoExtractor::hasEDep () const inline
Returns whether we are extracting any energy deposition information.
Definition at line 248 of file EventInfoUtils.h.
hasGenerated()
bool icarus::trigger::details::EventInfoExtractor::hasGenerated () const inline
Returns whether we are extracting any generator information.
Definition at line 245 of file EventInfoUtils.h.
isEDepListTag()
bool icarus::trigger::details::EventInfoExtractor::isEDepListTag (EDepTags_t const & edepTag) static
Returns whether edepTags contains energy deposition list tags.
Definition at line 439 of file EventInfoUtils.h.
isEDepSpecified()
static bool icarus::trigger::details::EventInfoExtractor::isEDepSpecified (EDepTags_t const & edepTag) inline static
Returns whether edepTags contains any energy deposition tag.
Definition at line 262 of file EventInfoUtils.h.
Referenced by icarus::trigger::details::EventInfoExtractorMaker::hasEDep().
isEDepSummaryTag()
bool icarus::trigger::details::EventInfoExtractor::isEDepSummaryTag (EDepTags_t const & edepTag) static
Returns whether edepTags contains a energy deposition summary tag.
Definition at line 433 of file EventInfoUtils.h.
operator()()
template<typename Event > EventInfo_t icarus::trigger::details::EventInfoExtractor::operator() (Event const & event) const inline
Definition at line 239 of file EventInfoUtils.h.
pointInActiveTPC()
geo::TPCGeo const * icarus::trigger::details::EventInfoExtractor::pointInActiveTPC (geo::Point_t const & point) const private
Returns in which active TPC volume point falls in (nullptr if none).
Definition at line 336 of file EventInfoUtils.cxx.
pointInTPC()
geo::TPCGeo const * icarus::trigger::details::EventInfoExtractor::pointInTPC (geo::Point_t const & point) const private
Returns in which TPC volume point falls in (nullptr if none).
Definition at line 327 of file EventInfoUtils.cxx.
setMainGeneratorNeutrinoInfo()
void icarus::trigger::details::EventInfoExtractor::setMainGeneratorNeutrinoInfo (EventInfo_t & info, simb::MCTruth const & truth) const private
Extracts information from truth and sets it as the "main" interaction information. Previous information is typically overwritten.
Definition at line 146 of file EventInfoUtils.cxx.
useEnergyDepositSummary()
bool icarus::trigger::details::EventInfoExtractor::useEnergyDepositSummary () const inline private
Returns whether we use energy summary instead of full energy deposits.
Definition at line 302 of file EventInfoUtils.h.
Member Data Documentation
EventInfoExtractorMaker
friend icarus::trigger::details::EventInfoExtractor::EventInfoExtractorMaker private
Definition at line 268 of file EventInfoUtils.h.
fDetProps
detinfo::DetectorPropertiesData const* icarus::trigger::details::EventInfoExtractor::fDetProps = nullptr private
Detector timing conversion utility.
Definition at line 289 of file EventInfoUtils.h.
fDetTimings
detinfo::DetectorTimings const* icarus::trigger::details::EventInfoExtractor::fDetTimings = nullptr private
Definition at line 292 of file EventInfoUtils.h.
fEnergyDepositTags
EDepTags_t const icarus::trigger::details::EventInfoExtractor::fEnergyDepositTags private
List of energy deposition product tags (std::vector<sim::SimEnergyDeposit>) or their summary.
Definition at line 277 of file EventInfoUtils.h.
Referenced by EventInfoExtractor().
fGeneratorTags
std::vector<art::InputTag> const icarus::trigger::details::EventInfoExtractor::fGeneratorTags private
List of truth data product tags (std::vector<simb::MCTruth>).
Definition at line 273 of file EventInfoUtils.h.
Referenced by EventInfoExtractor().
fGeom
geo::GeometryCore const& icarus::trigger::details::EventInfoExtractor::fGeom private
Geometry service provider.
Detector properties information.
Definition at line 286 of file EventInfoUtils.h.
fInPreSpillTimes
TimeSpan_t const icarus::trigger::details::EventInfoExtractor::fInPreSpillTimes private
Start and stop time for "pre-spill" label.
Definition at line 297 of file EventInfoUtils.h.
fInSpillTimes
TimeSpan_t const icarus::trigger::details::EventInfoExtractor::fInSpillTimes private
Start and stop time for "in spill" label.
Definition at line 294 of file EventInfoUtils.h.
fLogCategory
std::string const icarus::trigger::details::EventInfoExtractor::fLogCategory private
Stream name for message facility.
Definition at line 279 of file EventInfoUtils.h.
NoEDepTags
icarus::trigger::details::EventInfoExtractor::EDepTags_t const icarus::trigger::details::EventInfoExtractor::NoEDepTags {} inline static
Represents the absence of any energy deposition information.
Definition at line 453 of file EventInfoUtils.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfoUtils.cxx