CAF format: sbn::V1730channelConfiguration Struct Reference
sbn::V1730channelConfiguration Struct Reference
Class containing configuration for a V1730 channel.
#include <V1730channelConfiguration.h>
Public Member Functions
bool hasChannelID () const
Returns whether the channel ID is set.
short signed int relativeThreshold () const
Threshold relative to the baseline (ticks).
bool operator== (V1730channelConfiguration const &other) const
Comparison: all fields need to have the same values.
bool operator!= (V1730channelConfiguration const &other) const
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent, unsigned int verbosity=MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, std::string const &indent="") const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, unsigned int verbosity, std::string const &indent="") const
Dumps the content of the configuration into out stream.
Public Attributes
short unsigned int channelNo = std::numeric_limits<short unsigned int>::max()
Number of the channel on the board (0-15).
raw::Channel_t channelID = NoChannelID
Offline channel ID.
short signed int baseline = 0
Baseline (BaselineCh<N+1>).
short signed int threshold = 0
Threshold (triggerThreshold<N>).
bool enabled = false
Channel is enabled (enable).
Static Public Attributes
static constexpr auto NoChannelID = std::numeric_limits<raw::Channel_t>::max()
Special value for unassigned channel ID.
static constexpr unsigned int MaxDumpVerbosity = 1U
Maximum supported verbosity level supported by dump().
static constexpr unsigned int DefaultDumpVerbosity = MaxDumpVerbosity
Default verbosity level for dump().
Detailed Description
Class containing configuration for a V1730 channel.
This is an informative class containing configuration of a V1730 channel extracted from some other source (typically, DAQ) made readily available to the users.
This class does not include any configuration extraction code.
The class is default-constructible only, and its content needs to be added element by element.
Definition at line 46 of file V1730channelConfiguration.h.
Member Function Documentation
dump() [1/3]
void sbn::V1730channelConfiguration::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent, unsigned int verbosity = MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation string
firstIndent special indentation string for the first line
verbosity (default: DefaultDumpVerbosity) level of verbosity
The indentation string is prepended to each new line of the dump. The first line indentation string is prepended before the first line of the dump. The dump ends on a new empty line.
The amount of information printed depends on the verbosity level:
0: channel number and whether it is enabled or not (also off-line channel ID if available)
1: also baseline and threshold
Definition at line 21 of file V1730channelConfiguration.cxx.
References baseline, channelID, channelNo, enabled, hasChannelID(), MaxDumpVerbosity, relativeThreshold(), and threshold.
Referenced by dump(), dump(), and sbn::V1730Configuration::dump().
dump() [2/3]
void sbn::V1730channelConfiguration::dump (std::ostream & out, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation level
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with same first indentation level as the rest, and default verbosity.
Definition at line 139 of file V1730channelConfiguration.h.
References dump().
dump() [3/3]
void sbn::V1730channelConfiguration::dump (std::ostream & out, unsigned int verbosity, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent (default: none) indentation string
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with the specified verbosity level and same first indentation level as the rest.
Definition at line 151 of file V1730channelConfiguration.h.
References dump().
hasChannelID()
bool sbn::V1730channelConfiguration::hasChannelID () const inline
Returns whether the channel ID is set.
Definition at line 166 of file V1730channelConfiguration.h.
References channelID, and NoChannelID.
Referenced by dump(), and icarus::trigger::DiscriminatePMTwaveformsByChannel::refreshCurrentThresholds().
operator!=()
bool sbn::V1730channelConfiguration::operator!= (V1730channelConfiguration const & other) const inline
Definition at line 89 of file V1730channelConfiguration.h.
operator==()
bool sbn::V1730channelConfiguration::operator== (sbn::V1730channelConfiguration const & other) const inline
Comparison: all fields need to have the same values.
Definition at line 177 of file V1730channelConfiguration.h.
References icarus::WaveformBaseline::baseline().
relativeThreshold()
short signed int sbn::V1730channelConfiguration::relativeThreshold () const inline
Threshold relative to the baseline (ticks).
Definition at line 171 of file V1730channelConfiguration.h.
Referenced by dump(), and icarus::trigger::DiscriminatePMTwaveformsByChannel::refreshCurrentThresholds().
Member Data Documentation
baseline
short signed int sbn::V1730channelConfiguration::baseline = 0
Baseline (BaselineCh<N+1>).
Definition at line 63 of file V1730channelConfiguration.h.
Referenced by dump(), icarus::PMTWaveformBaselinesFromReadoutConfiguration::extractBaselinesFromConfiguration(), and icarus::PMTconfigurationExtractor::extractChannelConfiguration().
channelID
raw::Channel_t sbn::V1730channelConfiguration::channelID = NoChannelID
Offline channel ID.
Definition at line 60 of file V1730channelConfiguration.h.
Referenced by dump(), icarus::PMTWaveformBaselinesFromReadoutConfiguration::extractBaselinesFromConfiguration(), hasChannelID(), and icarus::trigger::DiscriminatePMTwaveformsByChannel::refreshCurrentThresholds().
channelNo
short unsigned int sbn::V1730channelConfiguration::channelNo = std::numeric_limits<short unsigned int>::max()
Number of the channel on the board (0-15).
Definition at line 57 of file V1730channelConfiguration.h.
Referenced by dump(), and icarus::PMTconfigurationExtractor::extractChannelConfiguration().
DefaultDumpVerbosity
unsigned int sbn::V1730channelConfiguration::DefaultDumpVerbosity = MaxDumpVerbosity static constexpr
Default verbosity level for dump().
Definition at line 104 of file V1730channelConfiguration.h.
enabled
bool sbn::V1730channelConfiguration::enabled = false
Channel is enabled (enable).
Definition at line 69 of file V1730channelConfiguration.h.
Referenced by dump(), and icarus::PMTconfigurationExtractor::extractChannelConfiguration().
MaxDumpVerbosity
unsigned int sbn::V1730channelConfiguration::MaxDumpVerbosity = 1U static constexpr
Maximum supported verbosity level supported by dump().
Definition at line 101 of file V1730channelConfiguration.h.
Referenced by dump().
NoChannelID
auto sbn::V1730channelConfiguration::NoChannelID = std::numeric_limits<raw::Channel_t>::max() static constexpr
Special value for unassigned channel ID.
Definition at line 49 of file V1730channelConfiguration.h.
Referenced by icarus::DaqDecoderICARUSPMT::createFragmentWaveforms(), icarus::PMTWaveformBaselinesFromReadoutConfiguration::extractBaselinesFromConfiguration(), icarus::PMTconfigurationExtractor::finalize(), hasChannelID(), and daq::details::BoardSetup_t::ChannelSetup_t::isChannel().
threshold
short signed int sbn::V1730channelConfiguration::threshold = 0
Threshold (triggerThreshold<N>).
Definition at line 66 of file V1730channelConfiguration.h.
Referenced by dump(), and icarus::PMTconfigurationExtractor::extractChannelConfiguration().
The documentation for this struct was generated from the following files:
sbnobj/sbnobj/Common/PMT/Data/V1730channelConfiguration.h
sbnobj/sbnobj/Common/PMT/Data/V1730channelConfiguration.cxx