CAF format: icarus::trigger::WindowChannelMap::WindowInfo_t Struct Reference
icarus::trigger::WindowChannelMap::WindowInfo_t Struct Reference
Information of a single window.
#include <WindowChannelMap.h>
Public Member Functions
void dump (std::ostream &out, std::string const &indent="") const
Prints the information content (single line).
Public Attributes
WindowComposition_t composition
WindowTopology_t topology
Detailed Description
Information of a single window.
Definition at line 104 of file WindowChannelMap.h.
Member Function Documentation
dump()
void icarus::trigger::WindowChannelMap::WindowInfo_t::dump (std::ostream & out, std::string const & indent = "") const
Prints the information content (single line).
Definition at line 22 of file WindowChannelMap.cxx.
References icarus::trigger::WindowChannelMap::WindowComposition_t::center, icarus::trigger::WindowChannelMap::WindowComposition_t::channels, icarus::trigger::WindowChannelMap::WindowComposition_t::cryoid, icarus::trigger::WindowChannelMap::WindowTopology_t::downstream, icarus::trigger::WindowChannelMap::WindowComposition_t::hasCryostat(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasDownstreamWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasOppositeWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasUpstreamWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::index, icarus::trigger::WindowChannelMap::WindowTopology_t::opposite, and icarus::trigger::WindowChannelMap::WindowTopology_t::upstream.
Referenced by icarus::trigger::WindowChannelMap::dump().
Member Data Documentation
composition
WindowComposition_t icarus::trigger::WindowChannelMap::WindowInfo_t::composition
Definition at line 106 of file WindowChannelMap.h.
topology
WindowTopology_t icarus::trigger::WindowChannelMap::WindowInfo_t::topology
Definition at line 108 of file WindowChannelMap.h.
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.cxx