CAF format: RequireOnBeamWaveforms Class Reference
RequireOnBeamWaveforms Class Reference
Requires the presence of one waveform per PMT covering beam gate time.
Classes
struct Config
Public Types
using Parameters = art::SharedFilter::Table<Config>
Public Member Functions
RequireOnBeamWaveforms (Parameters const &params, art::ProcessingFrame const &)
virtual bool filter (art::Event &event, art::ProcessingFrame const &) override
Evaluate the filtering logic.
virtual void endJob (art::ProcessingFrame const &) override
Prints a summary.
Private Types
using microsecond = util::quantities::points::microsecond
using nanoseconds = util::quantities::intervals::nanoseconds
Private Member Functions
microsecond beamGateTimeFromService (art::Event const &event) const
Reads the beam gate opening time from DetectorClocksService.
microsecond beamGateTimeFromData (art::Event const &event) const
Reads the beam gate opening time from the configured trigger data product.
std::vector< bool > missingFromMetadata (microsecond beamGateTime, std::vector< sbn::OpDetWaveformMeta > const &metadata, art::FindOneP< raw::OpDetWaveform > const *toWaveforms=nullptr) const
Returns a mask with positions of the missing channels set to true.
std::vector< bool > missingFromWaveforms (microsecond beamGateTime, std::vector< raw::OpDetWaveform > const &waveforms, nanoseconds clockTick) const
Returns a mask with positions of the missing channels set to true.
Static Private Member Functions
static std::vector< bool > buildRequiredChannelList (std::vector< raw::Channel_t > const &skipChannels={})
Composes and returns the list of channels to require.
Private Attributes
art::InputTag const fWaveformTag
Input waveform data product.
art::InputTag const fWaveformMetaTag
Input waveform metadata product.
art::InputTag const fTriggerTag
Data product for beam gate.
art::InputTag const fWaveformMetaAssnsTag
Input waveform/metadata assns.
bool const fForceWaveformPresence
Whether to always read waveforms.
std::string const fThrowOnFailure
Category of the exception to throw on failure (empty: does not throw).
std::string const fLogCategory
Name of message facility stream.
std::vector< bool > const fRequiredChannelMask
Bits of required channels (index is channel number).
std::ptrdiff_t const fNRequired
Number of channels needed on beam.
icarus::ns::util::AtomicPassCounter fPassed
Count of passed and seen events.
Detailed Description
Requires the presence of one waveform per PMT covering beam gate time.
This module passes only the events with one optical detector waveform per channel covering the beam gate opening time.
It attempts to read optical detector metadata and, failing that, falls back to the waveforms themselves.
Optionally, the availability of the waveforms is also verified (ForceWaveformPresence). With this option, if a waveform is not available it is considered like it were missing completely.
Note that the timestamp in the waveforms is assumed to be on the same scale as the beam gate opening time, and, where it matters, expressed in microseconds.
Configuration parameters
WaveformTag (input tag, optional): tag of the optical detector waveforms; if not specified, optical detector waveforms are not read at all (unless ForceWaveformPresence is set).
WaveformMetaTag (input tag, optional): tag of the optical detector waveform metadata; if empty, metadata is not used, and if not specified, the value of WaveformTag is used instead; in both special cases, WaveformTag must be specified.
TriggerTag (input tag, optional): data product to use to learn when the beam gate was opened; if omitted, DetectorClocksService is used instead.
WaveformMetaAssnsTag (input tag, default: like WaveformMetaTag): tag of the association between waveforms and their metadata. Normally, this is the same as the tag of the metadata itself, but in some old data that was not the case (ReassociatePMTbaselines would reassociate the existing one).
ForceWaveformPresence (flag, default: false): if set, waveforms from WaveformTag are always read even when the check is performed with metadata; this detects the case where optical detector waveforms were present but have since been dropped.
ThrowOnFailure (string, default: empty): if non-empty, instead of just returning false, when an event does not qualify, an exception is thrown with the category specified here, which can then be handled by art's scheduler "service".
MissingChannels (sequence of numbers, default: empty): the channels in this list are allowed not to be present.
LogCategory (string, default: RequireOnBeamWaveforms): message facility stream name where to write console messages to.
Service dependencies
Geometry: to learn how many channels we are looking for.
DetectorClocksService: depending on configuration, to get the beam opening time and for optical tick duration.
Input data products
std::vector<raw::OpDetWaveform> (WaveformTag, if specified): the waveforms which must have been present (and, if required, available).
std::vector<sbn::OpDetWaveformMeta> (WaveformTagMeta, if specified): the metadata of the waveforms which must be present.
std::vector<raw::Trigger> (TriggerTag, if specified) to read the beam gate opening time.
art::Assns<sbn::OpDetWaveformMeta, raw::OpDetWaveform> (WaveformTagMeta if ForceWaveformPresence is set and metadata is used) to verify the availability of waveforms.
Output data products
None.
Definition at line 123 of file RequireOnBeamWaveforms_module.cc.
Class Documentation
RequireOnBeamWaveforms::Config
struct RequireOnBeamWaveforms::Config
Definition at line 127 of file RequireOnBeamWaveforms_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > ForceWaveformPresence
Atom< string > LogCategory
Sequence< Channel_t > MissingChannels
Atom< string > ThrowOnFailure
Atom< InputTag > TriggerTag
OptionalAtom< InputTag > WaveformMetaAssnsTag
OptionalAtom< InputTag > WaveformMetaTag
OptionalAtom< InputTag > WaveformTag
Member Typedef Documentation
microsecond
using RequireOnBeamWaveforms::microsecond = util::quantities::points::microsecond private
Definition at line 192 of file RequireOnBeamWaveforms_module.cc.
nanoseconds
using RequireOnBeamWaveforms::nanoseconds = util::quantities::intervals::nanoseconds private
Definition at line 193 of file RequireOnBeamWaveforms_module.cc.
Parameters
using RequireOnBeamWaveforms::Parameters = art::SharedFilter::Table<Config>
Definition at line 178 of file RequireOnBeamWaveforms_module.cc.
Constructor & Destructor Documentation
RequireOnBeamWaveforms()
RequireOnBeamWaveforms::RequireOnBeamWaveforms (Parameters const & params, art::ProcessingFrame const &)
Definition at line 257 of file RequireOnBeamWaveforms_module.cc.
Member Function Documentation
beamGateTimeFromData()
auto RequireOnBeamWaveforms::beamGateTimeFromData (art::Event const & event) const private
Reads the beam gate opening time from the configured trigger data product.
Definition at line 467 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
beamGateTimeFromService()
auto RequireOnBeamWaveforms::beamGateTimeFromService (art::Event const & event) const private
Reads the beam gate opening time from DetectorClocksService.
Definition at line 456 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
buildRequiredChannelList()
std::vector< bool > RequireOnBeamWaveforms::buildRequiredChannelList (std::vector< raw::Channel_t > const & skipChannels = {}) static private
Composes and returns the list of channels to require.
Definition at line 347 of file RequireOnBeamWaveforms_module.cc.
endJob()
void RequireOnBeamWaveforms::endJob (art::ProcessingFrame const &) override virtual
Prints a summary.
Definition at line 444 of file RequireOnBeamWaveforms_module.cc.
References fLogCategory, and fPassed.
filter()
bool RequireOnBeamWaveforms::filter (art::Event & event, art::ProcessingFrame const &) override virtual
Evaluate the filtering logic.
Definition at line 361 of file RequireOnBeamWaveforms_module.cc.
References beamGateTimeFromData(), beamGateTimeFromService(), fForceWaveformPresence, fLogCategory, fNRequired, fPassed, fThrowOnFailure, fTriggerTag, fWaveformMetaAssnsTag, fWaveformMetaTag, fWaveformTag, missingFromMetadata(), and missingFromWaveforms().
missingFromMetadata()
std::vector< bool > RequireOnBeamWaveforms::missingFromMetadata (microsecond beamGateTime, std::vector< sbn::OpDetWaveformMeta > const & metadata, art::FindOneP< raw::OpDetWaveform > const * toWaveforms = nullptr) const private
Returns a mask with positions of the missing channels set to true.
Definition at line 482 of file RequireOnBeamWaveforms_module.cc.
References fForceWaveformPresence, and fRequiredChannelMask.
Referenced by filter().
missingFromWaveforms()
std::vector< bool > RequireOnBeamWaveforms::missingFromWaveforms (microsecond beamGateTime, std::vector< raw::OpDetWaveform > const & waveforms, nanoseconds clockTick) const private
Returns a mask with positions of the missing channels set to true.
Definition at line 522 of file RequireOnBeamWaveforms_module.cc.
References fRequiredChannelMask.
Referenced by filter().
Member Data Documentation
fForceWaveformPresence
bool const RequireOnBeamWaveforms::fForceWaveformPresence private
Whether to always read waveforms.
Definition at line 205 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter(), and missingFromMetadata().
fLogCategory
std::string const RequireOnBeamWaveforms::fLogCategory private
Name of message facility stream.
Definition at line 210 of file RequireOnBeamWaveforms_module.cc.
Referenced by endJob(), and filter().
fNRequired
std::ptrdiff_t const RequireOnBeamWaveforms::fNRequired private
Number of channels needed on beam.
Definition at line 219 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
fPassed
icarus::ns::util::AtomicPassCounter RequireOnBeamWaveforms::fPassed private
Count of passed and seen events.
Definition at line 224 of file RequireOnBeamWaveforms_module.cc.
Referenced by endJob(), and filter().
fRequiredChannelMask
std::vector<bool> const RequireOnBeamWaveforms::fRequiredChannelMask private
Bits of required channels (index is channel number).
Definition at line 217 of file RequireOnBeamWaveforms_module.cc.
Referenced by missingFromMetadata(), and missingFromWaveforms().
fThrowOnFailure
std::string const RequireOnBeamWaveforms::fThrowOnFailure private
Category of the exception to throw on failure (empty: does not throw).
Definition at line 208 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
fTriggerTag
art::InputTag const RequireOnBeamWaveforms::fTriggerTag private
Data product for beam gate.
Definition at line 201 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
fWaveformMetaAssnsTag
art::InputTag const RequireOnBeamWaveforms::fWaveformMetaAssnsTag private
Input waveform/metadata assns.
Definition at line 203 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
fWaveformMetaTag
art::InputTag const RequireOnBeamWaveforms::fWaveformMetaTag private
Input waveform metadata product.
Definition at line 199 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
fWaveformTag
art::InputTag const RequireOnBeamWaveforms::fWaveformTag private
Input waveform data product.
Definition at line 197 of file RequireOnBeamWaveforms_module.cc.
Referenced by filter().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/RequireOnBeamWaveforms_module.cc