CAF format: icarus::trigger::MajorityTriggerSimulation Class Reference
icarus::trigger::MajorityTriggerSimulation Class Reference
Simulates a "majority" trigger.
Classes
struct Config
Public Types
using microseconds = util::quantities::intervals::microseconds
using nanoseconds = util::quantities::intervals::nanoseconds
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
MajorityTriggerSimulation (Parameters const &config)
virtual void beginJob () override
Initializes the plots.
virtual void produce (art::Event &event) override
Runs the simulation and saves the results into the art event.
virtual void endJob () override
Prints end-of-job summaries.
Private Types
using TriggerInfo_t = details::TriggerInfo_t
Type alias.
using InputTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Type of trigger gate extracted from the input event.
using TriggerGates_t = std::vector<InputTriggerGate_t>
A list of trigger gates from input.
Private Member Functions
void initializePlots ()
Initializes the full set of plots (all ADC thresholds).
TriggerInfo_t produceForThreshold (art::Event &event, detinfo::DetectorTimings const &detTimings, ApplyBeamGateClass const &beamGate, std::size_t const iThr, icarus::trigger::ADCCounts_t const thr)
Performs the simulation for the specified ADC threshold.
TriggerInfo_t simulate (ApplyBeamGateClass const &clockData, TriggerGates_t const &gates) const
Performs the simulation of the configured trigger on gates input.
TriggerInfo_t simulateCryostat (ApplyBeamGateClass const &beamGate, std::size_t iCryo, TriggerGates_t const &gates) const
Simulates the trigger response within a single cryostat.
raw::Trigger triggerInfoToTriggerData (detinfo::DetectorTimings const &detTimings, unsigned int triggerNumber, TriggerInfo_t const &info) const
Converts the trigger information into a raw::Trigger object.
void plotTriggerResponse (std::size_t iThr, TriggerInfo_t const &triggerInfo) const
Fills the plots for threshold index iThr with trigger information.
void printSummary () const
Prints the summary of fired triggers on screen.
icarus::trigger::ApplyBeamGateClass makeMyBeamGate (art::Event const *event=nullptr) const
Shortcut to create an ApplyBeamGate with the current configuration.
icarus::trigger::ApplyBeamGateClass makeMyBeamGate (art::Event const &event) const
Private Attributes
std::map< icarus::trigger::ADCCounts_t, art::InputTag > fADCthresholds
ADC thresholds to read, and the input tag connected to their data.
unsigned int const fMinimumPrimitives
Minimum number of trigger primitives for a trigger to happen.
microseconds fBeamGateDuration
Duration of the gate during with global optical triggers are accepted.
nanoseconds fTriggerTimeResolution
Trigger resolution in time.
std::uint32_t fBeamBits
Bits for the beam gate being simulated.
std::string const fLogCategory
Message facility stream category for output.
geo::GeometryCore const & fGeom
art::TFileDirectory fOutputDir
ROOT directory where all the plots are written.
MajorityTriggerCombiner const fCombiner
Algorithm to combine primitives.
GeometryChannelSplitter fChannelSplitter
Algorithm to sort trigger gates by cryostat or TPC.
icarus::ns::util::PlotSandbox< art::TFileDirectory > fPlots
All plots in one practical sandbox.
std::vector< std::atomic< unsigned int > > fTriggerCount
std::atomic< unsigned int > fTotalEvents { 0U }
Count of fired triggers.
icarus::ns::util::ThreadSafeChangeMonitor< icarus::trigger::ApplyBeamGateClass > fGateChangeCheck
Functor returning whether a gate has changed.
Detailed Description
Simulates a "majority" trigger.
A trigger primitive is a two-level function of time which describes when that primitive is on and when it is off. Trigger primitives are given as input to this module and their origin may vary, but the standard source in ICARUS is single trigger request.
This module simulates a trigger requesting a minimum number of single trigger requests in the event, and saves the result as raw::Trigger data products. While only one trigger definition is used, inputs with different thresholds may be specified to have the different responses.
Configuration
TriggerGatesTag (string, mandatory): name of the module instance which produced the trigger primitives to be used as input; it must not include any instance name, as the instance names will be automatically added from Thresholds parameter. The typical trigger primitives used as input may be LVDS discriminated output (e.g. from icarus::trigger::LVDSgates module) or combinations of them (e.g. from icarus::trigger::SlidingWindowTrigger module).
Thresholds (list of integers, mandatory): list of the discrimination thresholds to consider, in ADC counts. A data product containing a digital signal is read for each one of the thresholds, and the tag of the data product is expected to be the module label TriggerGatesTag with as instance name the value of the threshold (e.g. for a threshold of 60 ADC counts the data product tag might be LVDSgates:60).
MinimumPrimitives (integer, mandatory): the required number of single trigger requests in order for the trigger to fire;
BeamGateDuration (time, mandatory): the duration of the beam gate; the time requires the unit to be explicitly specified: use "1.6 us" for BNB, 9.5 us for NuMI (also available as BNB_settings.spill_duration and NuMI_settings.spill_duration in trigger_icarus.fcl);
TriggerTimeResolution (time, default: 8 ns): time resolution for the trigger primitives;
LogCategory (string, default TriggerEfficiencyPlots): name of category used to stream messages from this module into message facility.
An example job configuration is provided as simulatemajoritytriggers_icarus.fcl.
Output data products
std::vector<raw::Trigger> (one instance per ADC threshold): list of triggers fired according to the configured trigger definition; there is one collection (and data product) per ADC threshold, and the data product has the same instance name as the input data one (see TriggerGatesTag and Thresholds configuration parameters); currently only at most one trigger is emitted, with time stamp matching the first time the trigger criteria are satisfied.
Trigger logic algorithm
This section describes the trigger logic algorithm used in icarus::trigger::MajorityTriggerSimulation and its assumptions.
The algorithm keeps the trigger primitives from the different cryostats separate for the most time. Within each cryostat, all trigger primitives are treated equally, whether they originate from one or from two channels (or 10 or 30), and wherever their channels are in the cryostat. The trigger primitives in each cryostat are combined in a multi-level gate by adding them, so that the level of the resulting gate matches at any time how many trigger primitives are on at that time. Finally, the maximum number of trigger primitives open in any of the cryostats at each time is the level to be compared to the trigger requirements.
This multi-level gate is set in coincidence with the beam gate by multiplying the multi-level and the beam gates. The beam gate opens at a time configured in DetectorClocks service provider (detinfo::DetectorClocks::BeamGateTime()) and has a duration configured in this module (BeamGateDuration).
At this point, the trigger gate is a multi-level gate suppressed everywhere except than during the beam gate. The trigger requirement is simply how many trigger primitives must be open at the same time in a single cryostat for the trigger to fire. The requirement is set in the configuration (MinimumPrimitives). To determine whether a trigger with the given minimum number of primitives open at the same time has fired, the gate combined as described above is scanned to find the first tick where the level of the gate reaches or passes this minimum required number. If such tick exists, the trigger is considered to have fired, and at that time.
While there is a parameter describing the time resolution of the trigger (TriggerTimeResolution), this is currently only used for aesthetic purposes to choose the binning of some plots: the resolution is not superimposed to the gates (yet).
Output plots
Plots are directly stored in the producer folder of the TFileService ROOT output file.
Summary plots are generated:
NTriggers: total number of triggers, per threshold
Eff: fraction of events with at least one trigger, per threshold
TriggerTick: trigger time distribution (optical tick), per threshold
The plots marked "per threshold" have a "threshold" axis where each bin corresponds to the threshold specified in the Thresholds configuration parameter. Note that the numerical value of the axis on that bin does not match the threshold value.
Definition at line 342 of file MajorityTriggerSimulation_module.cc.
Class Documentation
icarus::trigger::MajorityTriggerSimulation::Config
struct icarus::trigger::MajorityTriggerSimulation::Config
Definition at line 354 of file MajorityTriggerSimulation_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< uint32_t > BeamBits
Atom< microseconds > BeamGateDuration
Atom< string > LogCategory
Atom< unsigned int > MinimumPrimitives
Sequence< ADC_Count_t > Thresholds
Atom< string > TriggerGatesTag
Atom< nanoseconds > TriggerTimeResolution
Member Typedef Documentation
InputTriggerGate_t
using icarus::trigger::MajorityTriggerSimulation::InputTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta> private
Type of trigger gate extracted from the input event.
Definition at line 433 of file MajorityTriggerSimulation_module.cc.
microseconds
using icarus::trigger::MajorityTriggerSimulation::microseconds = util::quantities::intervals::microseconds
Definition at line 349 of file MajorityTriggerSimulation_module.cc.
nanoseconds
using icarus::trigger::MajorityTriggerSimulation::nanoseconds = util::quantities::intervals::nanoseconds
Definition at line 350 of file MajorityTriggerSimulation_module.cc.
Parameters
using icarus::trigger::MajorityTriggerSimulation::Parameters = art::EDProducer::Table<Config>
Definition at line 398 of file MajorityTriggerSimulation_module.cc.
TriggerGates_t
using icarus::trigger::MajorityTriggerSimulation::TriggerGates_t = std::vector<InputTriggerGate_t> private
A list of trigger gates from input.
Definition at line 436 of file MajorityTriggerSimulation_module.cc.
TriggerInfo_t
using icarus::trigger::MajorityTriggerSimulation::TriggerInfo_t = details::TriggerInfo_t private
Type alias.
Definition at line 430 of file MajorityTriggerSimulation_module.cc.
Constructor & Destructor Documentation
MajorityTriggerSimulation()
icarus::trigger::MajorityTriggerSimulation::MajorityTriggerSimulation (Parameters const & config) explicit
Definition at line 604 of file MajorityTriggerSimulation_module.cc.
Member Function Documentation
beginJob()
void icarus::trigger::MajorityTriggerSimulation::beginJob () override virtual
Initializes the plots.
Definition at line 665 of file MajorityTriggerSimulation_module.cc.
endJob()
void icarus::trigger::MajorityTriggerSimulation::endJob () override virtual
Prints end-of-job summaries.
Definition at line 707 of file MajorityTriggerSimulation_module.cc.
initializePlots()
void icarus::trigger::MajorityTriggerSimulation::initializePlots () private
Initializes the full set of plots (all ADC thresholds).
Definition at line 715 of file MajorityTriggerSimulation_module.cc.
makeMyBeamGate() [1/2]
icarus::trigger::ApplyBeamGateClass icarus::trigger::MajorityTriggerSimulation::makeMyBeamGate (art::Event const & event) const inline private
Definition at line 591 of file MajorityTriggerSimulation_module.cc.
makeMyBeamGate() [2/2]
icarus::trigger::ApplyBeamGateClass icarus::trigger::MajorityTriggerSimulation::makeMyBeamGate (art::Event const * event = nullptr) const inline private
Shortcut to create an ApplyBeamGate with the current configuration.
Definition at line 582 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::makeApplyBeamGate().
plotTriggerResponse()
void icarus::trigger::MajorityTriggerSimulation::plotTriggerResponse (std::size_t iThr, TriggerInfo_t const & triggerInfo) const private
Fills the plots for threshold index iThr with trigger information.
Definition at line 886 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::atTick(), and icarus::trigger::details::TriggerInfo_t::fired().
printSummary()
void icarus::trigger::MajorityTriggerSimulation::printSummary () const private
Prints the summary of fired triggers on screen.
Definition at line 901 of file MajorityTriggerSimulation_module.cc.
produce()
void icarus::trigger::MajorityTriggerSimulation::produce (art::Event & event) override virtual
Runs the simulation and saves the results into the art event.
Definition at line 673 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::atTick().
produceForThreshold()
auto icarus::trigger::MajorityTriggerSimulation::produceForThreshold (art::Event & event, detinfo::DetectorTimings const & detTimings, ApplyBeamGateClass const & beamGate, std::size_t const iThr, icarus::trigger::ADCCounts_t const thr) private
Performs the simulation for the specified ADC threshold.
Parameters
event art event to read data from and put results into
iThr index of the threshold in the configuration
thr value of the threshold (ADC counts)
Returns
a simple copy of the trigger response information
For the given threshold, the simulation of the configured trigger is performed. The input data is read from the event (the source tag is from the module configuration), simulation is performed, auxiliary plots are drawn and a raw::Trigger collection is stored into the event.
The stored collection contains either one or zero raw::Trigger elements.
The simulation itself is performed by the simulate() method.
Definition at line 785 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::fired(), and icarus::trigger::ReadTriggerGates().
simulate()
auto icarus::trigger::MajorityTriggerSimulation::simulate (ApplyBeamGateClass const & clockData, TriggerGates_t const & gates) const private
Performs the simulation of the configured trigger on gates input.
Parameters
gates the input to the trigger simulation
Returns
the outcome and details of the trigger simulation
The simulation is performed using the input single trigger requests (or trigger primitives) from the gates collection.
The gates are split by cryostat, and the simulation is performed independently on each cryostat (simulateCryostat()). Finally, the cryostat triggers are combined (OR) into the final trigger decision, bearing as time the earliest one.
Definition at line 825 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::addAndReplaceIfEarlier(), and icarus::trigger::details::TriggerInfo_t::sortOpenings().
simulateCryostat()
auto icarus::trigger::MajorityTriggerSimulation::simulateCryostat (ApplyBeamGateClass const & beamGate, std::size_t iCryo, TriggerGates_t const & gates) const private
Simulates the trigger response within a single cryostat.
Parameters
beamGate the beam gate to be applied
iCryo index of the cryostat being processed
gates the trigger primitives to be considered
Returns
the outcome and details of the trigger simulation
The simulation computes the count of trigger gates open at any time, sets it in coincidence with the beam gate, and fires a trigger if within that gate the count of open gates is equal or larger than the threshold configured (MinimumPrimitives). The time is the earliest one when that requirement is met.
Definition at line 855 of file MajorityTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::add().
triggerInfoToTriggerData()
raw::Trigger icarus::trigger::MajorityTriggerSimulation::triggerInfoToTriggerData (detinfo::DetectorTimings const & detTimings, unsigned int triggerNumber, TriggerInfo_t const & info) const private
Converts the trigger information into a raw::Trigger object.
Parameters
triggerNumber the unique number to assign to this trigger
info the information about the fired trigger
Returns
a raw::Trigger object with all the information encoded
The trigger described by info is encoded into a raw::Trigger object. The trigger must have fired.
Definition at line 925 of file MajorityTriggerSimulation_module.cc.
Member Data Documentation
fADCthresholds
std::map<icarus::trigger::ADCCounts_t, art::InputTag> icarus::trigger::MajorityTriggerSimulation::fADCthresholds private
ADC thresholds to read, and the input tag connected to their data.
Definition at line 442 of file MajorityTriggerSimulation_module.cc.
fBeamBits
std::uint32_t icarus::trigger::MajorityTriggerSimulation::fBeamBits private
Bits for the beam gate being simulated.
Definition at line 452 of file MajorityTriggerSimulation_module.cc.
fBeamGateDuration
microseconds icarus::trigger::MajorityTriggerSimulation::fBeamGateDuration private
Duration of the gate during with global optical triggers are accepted.
Definition at line 448 of file MajorityTriggerSimulation_module.cc.
fChannelSplitter
GeometryChannelSplitter icarus::trigger::MajorityTriggerSimulation::fChannelSplitter private
Algorithm to sort trigger gates by cryostat or TPC.
Definition at line 474 of file MajorityTriggerSimulation_module.cc.
fCombiner
MajorityTriggerCombiner const icarus::trigger::MajorityTriggerSimulation::fCombiner private
Algorithm to combine primitives.
Definition at line 471 of file MajorityTriggerSimulation_module.cc.
fGateChangeCheck
icarus::ns::util::ThreadSafeChangeMonitor<icarus::trigger::ApplyBeamGateClass> icarus::trigger::MajorityTriggerSimulation::fGateChangeCheck private
Functor returning whether a gate has changed.
Definition at line 487 of file MajorityTriggerSimulation_module.cc.
fGeom
geo::GeometryCore const& icarus::trigger::MajorityTriggerSimulation::fGeom private
Definition at line 461 of file MajorityTriggerSimulation_module.cc.
fLogCategory
std::string const icarus::trigger::MajorityTriggerSimulation::fLogCategory private
Message facility stream category for output.
Definition at line 455 of file MajorityTriggerSimulation_module.cc.
fMinimumPrimitives
unsigned int const icarus::trigger::MajorityTriggerSimulation::fMinimumPrimitives private
Minimum number of trigger primitives for a trigger to happen.
Definition at line 445 of file MajorityTriggerSimulation_module.cc.
fOutputDir
art::TFileDirectory icarus::trigger::MajorityTriggerSimulation::fOutputDir private
ROOT directory where all the plots are written.
Definition at line 464 of file MajorityTriggerSimulation_module.cc.
fPlots
icarus::ns::util::PlotSandbox<art::TFileDirectory> icarus::trigger::MajorityTriggerSimulation::fPlots private
All plots in one practical sandbox.
Count of fired triggers, per threshold.
Definition at line 477 of file MajorityTriggerSimulation_module.cc.
fTotalEvents
std::atomic<unsigned int> icarus::trigger::MajorityTriggerSimulation::fTotalEvents { 0U } private
Count of fired triggers.
Definition at line 481 of file MajorityTriggerSimulation_module.cc.
fTriggerCount
std::vector<std::atomic<unsigned int> > icarus::trigger::MajorityTriggerSimulation::fTriggerCount private
Definition at line 480 of file MajorityTriggerSimulation_module.cc.
fTriggerTimeResolution
nanoseconds icarus::trigger::MajorityTriggerSimulation::fTriggerTimeResolution private
Trigger resolution in time.
Definition at line 450 of file MajorityTriggerSimulation_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/MajorityTriggerSimulation_module.cc