CAF format: icarus::TriggerConfiguration Struct Reference
icarus::TriggerConfiguration Struct Reference
Classes
struct CryoConfig
struct GateConfig
Public Member Functions
float getGateWidth (std::size_t source) const
returns the effective gate width corrected for the veto delay in us
float getDriftGateWidth (std::size_t source) const
returns the width of the drift gate used for out-of-time light activity in us
unsigned int getOffBeamRate (std::size_t source) const
returns the prescale value used to open the offbeam gates with respect to the total number of beam gates seen
unsigned int getMinBiasPrescale (std::size_t source) const
returns the prescale value used to collect MinBias triggers with respect to the total number of gates seen of a particula type
bool operator== (TriggerConfiguration const &other) const noexcept
Comparison: all fields need to have the same values.
bool operator!= (TriggerConfiguration const &other) const noexcept
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent, unsigned int verbosity=MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, std::string const &indent="") const
Dumps the content of the configuration into out stream.
void dumpGateConfig (std::ostream &out, icarus::TriggerConfiguration::GateConfig const &gateConfig, std::string const &indent) const
Dumps the content of the gate configuration into out stream.
void dump (std::ostream &out, unsigned int verbosity, std::string const &indent="") const
Public Attributes
bool useWrTime = false
Use the WR time reference.
unsigned int wrTimeOffset = 1'000'000'000
Add an offset between the npt and tai time as used in the wr reference (normally it is 1 or 2 leap seconds) in ns.
unsigned int vetoDelay = 0
Veto (this delay has to be subtracted to the gate width). Value is in ns.
std::array< CryoConfig, icarus::trigger::kNTriggerLocation > cryoConfig
Cryostat configuration.
std::string majorityTriggerType
Majority trigger type (consider triggers from one cryostats, either cryostats, or both cryostats)
std::string runType
Force the run to be fully a MinBias, if runType=="MinBias". If runType=="Majority" does a majority run with some prescaled minbias triggers depending on the gate selection in use.
unsigned int tpcTriggerDelay = 0
TPCTriggerDelay: distance between the Global trigger time and the output for the TPC. NB: It is in units of 400 ns.
std::array< GateConfig, icarus::trigger::kNTriggerSource > gateConfig
Gate Configuration.
std::string generator = UnknwonGenerator
Name of the trigger fragment DAQ generator.
Static Public Attributes
static std::string const UnknwonGenerator { "<unknown>" }
Label used for unknown DAQ generator.
static constexpr unsigned int MaxDumpVerbosity = 2U
Maximum supported verbosity level supported by dump().
static constexpr unsigned int DefaultDumpVerbosity = MaxDumpVerbosity
Default verbosity level for dump().
Detailed Description
Definition at line 31 of file TriggerConfiguration.h.
Member Function Documentation
dump() [1/3]
void icarus::TriggerConfiguration::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent, unsigned int verbosity = MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation string
firstIndent special indentation string for the first line
verbosity (default: DefaultDumpVerbosity) level of verbosity
The indentation string is prepended to each new line of the dump. The first line indentation string is prepended before the first line of the dump. The dump ends on a new empty line.
The amount of information printed depends on the verbosity level:
0: Boardreader configuration
1: FPGA configuration
2: SPEXI configuration
Definition at line 71 of file TriggerConfiguration.cxx.
Referenced by sbn::DumpTriggerConfiguration::beginRun(), dump(), and icarus::operator<<().
dump() [2/3]
void icarus::TriggerConfiguration::dump (std::ostream & out, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation level
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with same first indentation level as the rest, and default verbosity.
Definition at line 260 of file TriggerConfiguration.h.
References dump().
dump() [3/3]
void icarus::TriggerConfiguration::dump (std::ostream & out, unsigned int verbosity, std::string const & indent = "") const inline
Definition at line 278 of file TriggerConfiguration.h.
dumpGateConfig()
void icarus::TriggerConfiguration::dumpGateConfig (std::ostream & out, icarus::TriggerConfiguration::GateConfig const & gateConfig, std::string const & indent) const
Dumps the content of the gate configuration into out stream.
Parameters
out stream to dump the information into
gateConfig the gate to be dumped
indent (default: none) indentation string
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with the specified verbosity level and same first indentation level as the rest.
Definition at line 24 of file TriggerConfiguration.cxx.
References gateConfig, and vetoDelay.
getDriftGateWidth()
float icarus::TriggerConfiguration::getDriftGateWidth (std::size_t source) const inline
returns the width of the drift gate used for out-of-time light activity in us
Parameters
source is the value of the sbn::bits::triggerSource enum type corresponding to the type of gate
Definition at line 170 of file TriggerConfiguration.h.
References gateConfig.
getGateWidth()
float icarus::TriggerConfiguration::getGateWidth (std::size_t source) const inline
returns the effective gate width corrected for the veto delay in us
Parameters
source is the value of the sbn::bits::triggerSource enum type corresponding to the type of gate
Definition at line 154 of file TriggerConfiguration.h.
References gateConfig, and vetoDelay.
Referenced by daq::TriggerDecoderV2::process_fragment(), and daq::TriggerDecoderV3::process_fragment().
getMinBiasPrescale()
unsigned int icarus::TriggerConfiguration::getMinBiasPrescale (std::size_t source) const inline
returns the prescale value used to collect MinBias triggers with respect to the total number of gates seen of a particula type
Parameters
source is the value of the sbn::bits::triggerSource enum type corresponding to the type of gate
Definition at line 195 of file TriggerConfiguration.h.
References gateConfig.
getOffBeamRate()
unsigned int icarus::TriggerConfiguration::getOffBeamRate (std::size_t source) const inline
returns the prescale value used to open the offbeam gates with respect to the total number of beam gates seen
Parameters
source is the value of the sbn::bits::triggerSource enum type corresponding to the type of gate
Definition at line 183 of file TriggerConfiguration.h.
References gateConfig.
operator!=()
bool icarus::TriggerConfiguration::operator!= (TriggerConfiguration const & other) const inline noexcept
Definition at line 208 of file TriggerConfiguration.h.
operator==()
bool icarus::TriggerConfiguration::operator== (icarus::TriggerConfiguration const & other) const inline noexcept
Comparison: all fields need to have the same values.
Definition at line 294 of file TriggerConfiguration.h.
Member Data Documentation
cryoConfig
std::array<CryoConfig, icarus::trigger::kNTriggerLocation> icarus::TriggerConfiguration::cryoConfig
Cryostat configuration.
Definition at line 128 of file TriggerConfiguration.h.
DefaultDumpVerbosity
unsigned int icarus::TriggerConfiguration::DefaultDumpVerbosity = MaxDumpVerbosity static constexpr
Default verbosity level for dump().
Definition at line 224 of file TriggerConfiguration.h.
gateConfig
std::array<GateConfig, icarus::trigger::kNTriggerSource> icarus::TriggerConfiguration::gateConfig
Gate Configuration.
Definition at line 140 of file TriggerConfiguration.h.
Referenced by dumpGateConfig(), getDriftGateWidth(), getGateWidth(), getMinBiasPrescale(), getOffBeamRate(), daq::TriggerDecoderV2::process_fragment(), and daq::TriggerDecoderV3::process_fragment().
generator
std::string icarus::TriggerConfiguration::generator = UnknwonGenerator
Name of the trigger fragment DAQ generator.
Definition at line 143 of file TriggerConfiguration.h.
majorityTriggerType
std::string icarus::TriggerConfiguration::majorityTriggerType
Majority trigger type (consider triggers from one cryostats, either cryostats, or both cryostats)
Definition at line 131 of file TriggerConfiguration.h.
MaxDumpVerbosity
unsigned int icarus::TriggerConfiguration::MaxDumpVerbosity = 2U static constexpr
Maximum supported verbosity level supported by dump().
Definition at line 221 of file TriggerConfiguration.h.
runType
std::string icarus::TriggerConfiguration::runType
Force the run to be fully a MinBias, if runType=="MinBias". If runType=="Majority" does a majority run with some prescaled minbias triggers depending on the gate selection in use.
Definition at line 134 of file TriggerConfiguration.h.
tpcTriggerDelay
unsigned int icarus::TriggerConfiguration::tpcTriggerDelay = 0
TPCTriggerDelay: distance between the Global trigger time and the output for the TPC. NB: It is in units of 400 ns.
Definition at line 137 of file TriggerConfiguration.h.
UnknwonGenerator
std::string const icarus::TriggerConfiguration::UnknwonGenerator { "<unknown>" } static
Label used for unknown DAQ generator.
Definition at line 21 of file TriggerConfiguration.h.
useWrTime
bool icarus::TriggerConfiguration::useWrTime = false
Use the WR time reference.
Definition at line 119 of file TriggerConfiguration.h.
Referenced by icarus::TriggerConfigurationExtractor::extractTriggerConfiguration().
vetoDelay
unsigned int icarus::TriggerConfiguration::vetoDelay = 0
Veto (this delay has to be subtracted to the gate width). Value is in ns.
Definition at line 125 of file TriggerConfiguration.h.
Referenced by dumpGateConfig(), getGateWidth(), daq::TriggerDecoderV2::process_fragment(), and daq::TriggerDecoderV3::process_fragment().
wrTimeOffset
unsigned int icarus::TriggerConfiguration::wrTimeOffset = 1'000'000'000
Add an offset between the npt and tai time as used in the wr reference (normally it is 1 or 2 leap seconds) in ns.
Definition at line 122 of file TriggerConfiguration.h.
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/Decode/DataProducts/TriggerConfiguration.h
icaruscode/icaruscode/Decode/DataProducts/TriggerConfiguration.cxx