CAF format: util::Expected< T, E > Class Template Reference
util::Expected< T, E > Class Template Reference
Class holding a value or an error.
#include <Expected.h>
Public Member Functions
constexpr Expected (E e=E{})
Constructor: starts with a default-constructed error value.
constexpr Expected (T t)
Constructor: starts with a copy of the value t.
Expected< T, E > & operator= (E e)
Expected< T, E > & operator= (T t)
template<typename... Args>
T & emplace (Args &&... args)
Constructs the expected value in place.
bool has_value () const
Returns whether a value is stored (as opposed to an error).
E error () const
Returns the error (undefined behaviour when storing a value).
T const & value () const
Returns the value (undefined behaviour when storing an error).
T const * valuePtr () const
Returns a pointer to the value (nullptr when storing an error).
T const & operator* () const
Implicit conversion to value (undefined behaviour if storing an error).
T const * operator-> () const
Implicit conversion to value (undefined behaviour if storing an error).
operator bool () const
Returns whether a value is stored (as opposed to an error).
Private Attributes
std::variant< T, E > fValue
The stored value or error.
Detailed Description
template<typename T, typename E>
class util::Expected< T, E >
Class holding a value or an error.
Template Parameters
T type of the value
E (default: int) type of the error
This class is loosely based on C++-23 std::expected. When C++23 is available, this class should be removed. The main difference is the default value of the error type E, which is not present at all in the standard (so the upgrade path would be to define
namespace util {
  template <typename T, typename E = int>
  using Expected = std::expected<T, E>;
}
Definition at line 38 of file Expected.h.
Constructor & Destructor Documentation
Expected() [1/2]
template<typename T , typename E > util::Expected< T, E >::Expected (E e = E{}) inline constexpr
Constructor: starts with a default-constructed error value.
Definition at line 45 of file Expected.h.
Expected() [2/2]
template<typename T , typename E > util::Expected< T, E >::Expected (T t) inline constexpr
Constructor: starts with a copy of the value t.
Definition at line 48 of file Expected.h.
Member Function Documentation
emplace()
template<typename T , typename E > template<typename... Args> T & util::Expected< T, E >::emplace (Args &&... args) inline
Constructs the expected value in place.
Definition at line 55 of file Expected.h.
References util::Expected< T, E >::fValue.
error()
template<typename T , typename E > E util::Expected< T, E >::error () const inline
Returns the error (undefined behaviour when storing a value).
Definition at line 62 of file Expected.h.
References util::Expected< T, E >::fValue.
Referenced by icarusDB::ChannelMapPostGres::BuildPMTFragmentToDigitizerChannelMap(), icarusDB::ChannelMapPostGres::BuildTPCFragmentIDToReadoutIDMap(), and icarusDB::ChannelMapPostGres::BuildTPCReadoutBoardToChannelMap().
has_value()
template<typename T , typename E > bool util::Expected< T, E >::has_value () const inline
Returns whether a value is stored (as opposed to an error).
Definition at line 59 of file Expected.h.
References util::Expected< T, E >::fValue.
Referenced by util::Expected< T, E >::operator bool(), and util::Expected< T, E >::valuePtr().
operator bool()
template<typename T , typename E > util::Expected< T, E >::operator bool () const inline explicit
Returns whether a value is stored (as opposed to an error).
Definition at line 77 of file Expected.h.
References util::Expected< T, E >::has_value().
operator*()
template<typename T , typename E > T const & util::Expected< T, E >::operator* () const inline
Implicit conversion to value (undefined behaviour if storing an error).
Definition at line 71 of file Expected.h.
References util::Expected< T, E >::value().
operator->()
template<typename T , typename E > T const * util::Expected< T, E >::operator-> () const inline
Implicit conversion to value (undefined behaviour if storing an error).
Definition at line 74 of file Expected.h.
References util::Expected< T, E >::valuePtr().
operator=() [1/2]
template<typename T , typename E > Expected< T, E > & util::Expected< T, E >::operator= (E e) inline
Definition at line 50 of file Expected.h.
operator=() [2/2]
template<typename T , typename E > Expected< T, E > & util::Expected< T, E >::operator= (T t) inline
Definition at line 51 of file Expected.h.
value()
template<typename T , typename E > T const & util::Expected< T, E >::value () const inline
Returns the value (undefined behaviour when storing an error).
Definition at line 65 of file Expected.h.
References util::Expected< T, E >::fValue.
Referenced by icarusDB::ChannelMapPostGres::BuildPMTFragmentToDigitizerChannelMap(), icarusDB::ChannelMapPostGres::BuildTPCFragmentIDToReadoutIDMap(), icarusDB::ChannelMapPostGres::BuildTPCReadoutBoardToChannelMap(), util::Expected< T, E >::operator*(), and util::Expected< T, E >::valuePtr().
valuePtr()
template<typename T , typename E > T const * util::Expected< T, E >::valuePtr () const inline
Returns a pointer to the value (nullptr when storing an error).
Definition at line 68 of file Expected.h.
References util::Expected< T, E >::has_value(), and util::Expected< T, E >::value().
Referenced by util::Expected< T, E >::operator->().
Member Data Documentation
fValue
template<typename T , typename E > std::variant<T, E> util::Expected< T, E >::fValue private
The stored value or error.
Definition at line 40 of file Expected.h.
Referenced by util::Expected< T, E >::emplace(), util::Expected< T, E >::error(), util::Expected< T, E >::has_value(), and util::Expected< T, E >::value().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/Expected.h