CAF format: icarus::trigger::details::EventInfo_t Struct Reference
icarus::trigger::details::EventInfo_t Struct Reference
Selected information about the event.
#include <EventInfo_t.h>
Public Types
Local type aliases
using GeV = util::quantities::gigaelectronvolt
using simulation_time = detinfo::timescales::simulation_time
Public Member Functions
EventInfo_t ()
Constructor. As if nobody noticed.
void dump (std::ostream &out) const
Prints the content of the object into a stream.
Generation information
The information is available only if hasGenerated() returns true. Otherwise, the return value of all the members in this group is undefined.
bool hasGenerated () const
Returns whether generator information is available.
unsigned int nWeakChargedCurrentInteractions () const
Returns the number of weak charged current interactions in the event.
unsigned int nWeakNeutralCurrentInteractions () const
Returns the number of weak neutral current interactions in the event.
unsigned int nWeakCurrentInteractions () const
Returns the number of weak current interactions in the event.
bool isWeakChargedCurrent () const
Returns whether the event is generated as a neutrino CC interaction.
bool isWeakNeutralCurrent () const
Returns whether the event is generated as a neutrino NC interaction.
bool isNeutrino () const
Returns whether the event is generated as a neutrino interaction.
bool isNu_mu () const
Returns which neutrino flavor is present in an event.
bool isNu_e () const
Returns whether generator information is available.
int NeutrinoPDG () const
Returns the neutrino PDG code.
GeV NeutrinoEnergy () const
Returns the neutrino energy [GeV].
GeV LeptonEnergy () const
Returns the lepton energy [GeV].
int InteractionType () const
Returns the interaction type.
simulation_time InteractionTime () const
Returns the time of the first interaction, in simulation time scale [ns].
bool hasVertex () const
Returns whether this type of event has a known vertex.
unsigned int nVertices () const
Returns the number of known interaction vertices.
std::vector< geo::Point_t > const & Vertices () const
Returns the list of a known interaction vertex.
bool isInActiveVolume () const
Returns whether there is an interaction within the active volume.
Deposited energy information
The information is available only if hasDepEnergy() returns true. Otherwise, the return value of all the members in this group is undefined.
bool hasDepEnergy () const
Returns whether generator information is available.
GeV DepositedEnergy () const
Returns the total energy deposited in the detector during the event [GeV].
GeV DepositedEnergyInSpill () const
Returns the total energy deposited in the detector during beam [GeV].
GeV DepositedEnergyInPreSpill () const
GeV DepositedEnergyInActiveVolume () const
Returns the energy deposited in the active volume during the event [GeV].
GeV DepositedEnergyInSpillInActiveVolume () const
Returns the energy deposited in the active volume during the beam [GeV].
GeV DepositedEnergyInPreSpillInActiveVolume () const
Set interface
void AddWeakChargedCurrentInteractions (unsigned int n=1U)
Marks this event as including n more weak charged current interactions.
void AddWeakNeutralCurrentInteractions (unsigned int n=1U)
Marks this event as including n more weak neutral current interactions.
void SetNu_mu (bool numu)
Marks the flavor of the neutrino in the first interaction.
void SetNu_e (bool nue)
Marks this event as including n more weak charged current interactions.
void SetNeutrinoPDG (int NU)
Marks the neutrino type of the first interaction in the event.
void SetNeutrinoEnergy (GeV eNu)
Sets the neutrino energy.
void SetLeptonEnergy (GeV eL)
Sets the lepton energy.
void SetInteractionType (int type)
Sets the interaction type.
void SetInteractionTime (simulation_time time)
Sets the time of the first interaction.
void SetInActiveVolume (bool active=true)
Set whether the event has relevant activity in the active volume.
void AddVertex (geo::Point_t const &vertex)
Adds a point to the list of interaction vertices in the event.
void InsertVertex (geo::Point_t const &vertex, std::size_t beforeIndex)
void SetDepositedEnergy (GeV e)
Sets the total deposited energy of the event [GeV].
void SetDepositedEnergyInSpill (GeV e)
Sets the energy of the event deposited during beam gate [GeV].
void SetDepositedEnergyInPreSpill (GeV e)
Sets the energy of the event deposited during pre-spill window [GeV].
void SetDepositedEnergyInActiveVolume (GeV e)
Sets the total deposited energy of the event in active volume [GeV].
void SetDepositedEnergyInSpillInActiveVolume (GeV e)
void SetDepositedEnergyInPreSpillInActiveVolume (GeV e)
Private Member Functions
void setGen ()
Declares that this object has generator information.
void setDep ()
Declares that this object has deposited energy information.
Private Attributes
bool fHasGenerated = false
Whether generation information is available.
std::array< unsigned int, NInteractionTypes > fInteractions
int fNeutrinoPDG { 0 }
int fInteractionType { 0 }
simulation_time fInteractionTime
Time of the first interaction [ns].
GeV fNeutrinoEnergy { 0.0 }
GeV fLeptonEnergy { 0.0 }
bool nu_mu { false }
bool nu_e { false }
bool fInActiveVolume { false }
Whether the event has activity inside the active volume.
std::vector< geo::Point_t > fVertices
Position of all vertices.
bool fHasDepEnergy = false
Whether deposited energy info is available.
GeV fEnergyDepTotal { 0.0 }
Total deposited energy.
GeV fEnergyDepSpill { 0.0 }
Energy deposited in spill.
GeV fEnergyDepPreSpill { 0.0 }
Energy deposited in pre-spill.
GeV fEnergyDepActive { 0.0 }
GeV fEnergyDepSpillActive { 0.0 }
Energy deposited in active volume in spill.
GeV fEnergyDepPreSpillActive { 0.0 }
Energy deposited in active volume in pre-spill window.
Static Private Attributes
static constexpr std::size_t itWCC { 0U }
Charged weak current.
static constexpr std::size_t itWNC { 1U }
Neutral weak current.
static constexpr std::size_t NInteractionTypes { 2U }
Detailed Description
Selected information about the event.
This is intended as a record for transferring relevant event information between object.
The exact definition of the quantities is deferred to the user (e.g. when and how long the beam and pre-spill windows are, the definition of active volume, etc.).
Definition at line 45 of file EventInfo_t.h.
Member Typedef Documentation
GeV
using icarus::trigger::details::EventInfo_t::GeV = util::quantities::gigaelectronvolt
Definition at line 49 of file EventInfo_t.h.
simulation_time
using icarus::trigger::details::EventInfo_t::simulation_time = detinfo::timescales::simulation_time
Definition at line 50 of file EventInfo_t.h.
Constructor & Destructor Documentation
EventInfo_t()
icarus::trigger::details::EventInfo_t::EventInfo_t () inline
Constructor. As if nobody noticed.
Definition at line 54 of file EventInfo_t.h.
Member Function Documentation
AddVertex()
void icarus::trigger::details::EventInfo_t::AddVertex (geo::Point_t const & vertex) inline
Adds a point to the list of interaction vertices in the event.
Definition at line 205 of file EventInfo_t.h.
References fVertices, and setGen().
AddWeakChargedCurrentInteractions()
void icarus::trigger::details::EventInfo_t::AddWeakChargedCurrentInteractions (unsigned int n = 1U) inline
Marks this event as including n more weak charged current interactions.
Definition at line 173 of file EventInfo_t.h.
References itWCC, and setGen().
AddWeakNeutralCurrentInteractions()
void icarus::trigger::details::EventInfo_t::AddWeakNeutralCurrentInteractions (unsigned int n = 1U) inline
Marks this event as including n more weak neutral current interactions.
Definition at line 177 of file EventInfo_t.h.
References itWNC, and setGen().
DepositedEnergy()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergy () const inline
Returns the total energy deposited in the detector during the event [GeV].
Definition at line 143 of file EventInfo_t.h.
References fEnergyDepTotal.
Referenced by dump().
DepositedEnergyInActiveVolume()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergyInActiveVolume () const inline
Returns the energy deposited in the active volume during the event [GeV].
Definition at line 153 of file EventInfo_t.h.
References fEnergyDepActive.
Referenced by dump().
DepositedEnergyInPreSpill()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergyInPreSpill () const inline
Returns the total energy deposited in the detector in the pre-spill window [GeV]
Definition at line 150 of file EventInfo_t.h.
References fEnergyDepPreSpill.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
DepositedEnergyInPreSpillInActiveVolume()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergyInPreSpillInActiveVolume () const inline
Returns the energy deposited in the active volume during the pre-spill window [GeV]
Definition at line 161 of file EventInfo_t.h.
References fEnergyDepPreSpillActive.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
DepositedEnergyInSpill()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergyInSpill () const inline
Returns the total energy deposited in the detector during beam [GeV].
Definition at line 146 of file EventInfo_t.h.
References fEnergyDepSpill.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
DepositedEnergyInSpillInActiveVolume()
GeV icarus::trigger::details::EventInfo_t::DepositedEnergyInSpillInActiveVolume () const inline
Returns the energy deposited in the active volume during the beam [GeV].
Definition at line 156 of file EventInfo_t.h.
References fEnergyDepSpillActive.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
dump()
void EventInfo_t::dump (std::ostream & out) const
Prints the content of the object into a stream.
Definition at line 21 of file EventInfo_t.cxx.
References DepositedEnergy(), DepositedEnergyInActiveVolume(), DepositedEnergyInPreSpill(), DepositedEnergyInPreSpillInActiveVolume(), DepositedEnergyInSpill(), DepositedEnergyInSpillInActiveVolume(), fVertices, hasDepEnergy(), hasGenerated(), InteractionTime(), InteractionType(), isInActiveVolume(), isNeutrino(), isNu_e(), isNu_mu(), LeptonEnergy(), NeutrinoEnergy(), nWeakChargedCurrentInteractions(), and nWeakNeutralCurrentInteractions().
hasDepEnergy()
bool icarus::trigger::details::EventInfo_t::hasDepEnergy () const inline
Returns whether generator information is available.
Definition at line 140 of file EventInfo_t.h.
References fHasDepEnergy.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
hasGenerated()
bool icarus::trigger::details::EventInfo_t::hasGenerated () const inline
Returns whether generator information is available.
Definition at line 66 of file EventInfo_t.h.
References fHasGenerated.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
hasVertex()
bool icarus::trigger::details::EventInfo_t::hasVertex () const inline
Returns whether this type of event has a known vertex.
Definition at line 115 of file EventInfo_t.h.
References fVertices.
Referenced by icarus::trigger::TriggerEfficiencyPlotsBase::shouldPlotEvent().
InsertVertex()
void icarus::trigger::details::EventInfo_t::InsertVertex (geo::Point_t const & vertex, std::size_t beforeIndex) inline
Inserts a point in the specified position of the list of interaction vertices in the event.
Definition at line 210 of file EventInfo_t.h.
References fVertices, and setGen().
InteractionTime()
simulation_time icarus::trigger::details::EventInfo_t::InteractionTime () const inline
Returns the time of the first interaction, in simulation time scale [ns].
Definition at line 112 of file EventInfo_t.h.
References fInteractionTime.
Referenced by dump().
InteractionType()
int icarus::trigger::details::EventInfo_t::InteractionType () const inline
Returns the interaction type.
Definition at line 109 of file EventInfo_t.h.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
isInActiveVolume()
bool icarus::trigger::details::EventInfo_t::isInActiveVolume () const inline
Returns whether there is an interaction within the active volume.
Definition at line 124 of file EventInfo_t.h.
References fInActiveVolume.
Referenced by dump(), and icarus::trigger::TriggerEfficiencyPlotsBase::shouldPlotEvent().
isNeutrino()
bool icarus::trigger::details::EventInfo_t::isNeutrino () const inline
Returns whether the event is generated as a neutrino interaction.
Definition at line 92 of file EventInfo_t.h.
References isWeakChargedCurrent(), and isWeakNeutralCurrent().
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
isNu_e()
bool icarus::trigger::details::EventInfo_t::isNu_e () const inline
Returns whether generator information is available.
Definition at line 97 of file EventInfo_t.h.
Referenced by dump().
isNu_mu()
bool icarus::trigger::details::EventInfo_t::isNu_mu () const inline
Returns which neutrino flavor is present in an event.
Definition at line 96 of file EventInfo_t.h.
Referenced by dump().
isWeakChargedCurrent()
bool icarus::trigger::details::EventInfo_t::isWeakChargedCurrent () const inline
Returns whether the event is generated as a neutrino CC interaction.
Definition at line 84 of file EventInfo_t.h.
References nWeakChargedCurrentInteractions().
Referenced by isNeutrino().
isWeakNeutralCurrent()
bool icarus::trigger::details::EventInfo_t::isWeakNeutralCurrent () const inline
Returns whether the event is generated as a neutrino NC interaction.
Definition at line 88 of file EventInfo_t.h.
References nWeakNeutralCurrentInteractions().
Referenced by isNeutrino().
LeptonEnergy()
GeV icarus::trigger::details::EventInfo_t::LeptonEnergy () const inline
Returns the lepton energy [GeV].
Definition at line 106 of file EventInfo_t.h.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
NeutrinoEnergy()
GeV icarus::trigger::details::EventInfo_t::NeutrinoEnergy () const inline
Returns the neutrino energy [GeV].
Definition at line 103 of file EventInfo_t.h.
Referenced by dump(), icarus::trigger::TriggerEfficiencyPlotsBase::fillEfficiencyPlots(), and icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
NeutrinoPDG()
int icarus::trigger::details::EventInfo_t::NeutrinoPDG () const inline
Returns the neutrino PDG code.
Definition at line 100 of file EventInfo_t.h.
nVertices()
unsigned int icarus::trigger::details::EventInfo_t::nVertices () const inline
Returns the number of known interaction vertices.
Definition at line 118 of file EventInfo_t.h.
References fVertices.
nWeakChargedCurrentInteractions()
unsigned int icarus::trigger::details::EventInfo_t::nWeakChargedCurrentInteractions () const inline
Returns the number of weak charged current interactions in the event.
Definition at line 69 of file EventInfo_t.h.
References itWCC.
Referenced by dump(), isWeakChargedCurrent(), and nWeakCurrentInteractions().
nWeakCurrentInteractions()
unsigned int icarus::trigger::details::EventInfo_t::nWeakCurrentInteractions () const inline
Returns the number of weak current interactions in the event.
Definition at line 77 of file EventInfo_t.h.
References nWeakChargedCurrentInteractions(), and nWeakNeutralCurrentInteractions().
nWeakNeutralCurrentInteractions()
unsigned int icarus::trigger::details::EventInfo_t::nWeakNeutralCurrentInteractions () const inline
Returns the number of weak neutral current interactions in the event.
Definition at line 73 of file EventInfo_t.h.
References itWNC.
Referenced by dump(), isWeakNeutralCurrent(), and nWeakCurrentInteractions().
setDep()
void icarus::trigger::details::EventInfo_t::setDep () inline private
Declares that this object has deposited energy information.
Definition at line 297 of file EventInfo_t.h.
References fHasDepEnergy.
Referenced by SetDepositedEnergy(), SetDepositedEnergyInActiveVolume(), SetDepositedEnergyInPreSpill(), SetDepositedEnergyInPreSpillInActiveVolume(), SetDepositedEnergyInSpill(), and SetDepositedEnergyInSpillInActiveVolume().
SetDepositedEnergy()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergy (GeV e) inline
Sets the total deposited energy of the event [GeV].
Definition at line 214 of file EventInfo_t.h.
References fEnergyDepTotal, and setDep().
SetDepositedEnergyInActiveVolume()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergyInActiveVolume (GeV e) inline
Sets the total deposited energy of the event in active volume [GeV].
Definition at line 223 of file EventInfo_t.h.
References fEnergyDepActive, and setDep().
SetDepositedEnergyInPreSpill()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergyInPreSpill (GeV e) inline
Sets the energy of the event deposited during pre-spill window [GeV].
Definition at line 220 of file EventInfo_t.h.
References fEnergyDepPreSpill, and setDep().
SetDepositedEnergyInPreSpillInActiveVolume()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergyInPreSpillInActiveVolume (GeV e) inline
Sets the energy of the event deposited during pre-spill window in active volume [GeV]
Definition at line 233 of file EventInfo_t.h.
References fEnergyDepPreSpillActive, and setDep().
SetDepositedEnergyInSpill()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergyInSpill (GeV e) inline
Sets the energy of the event deposited during beam gate [GeV].
Definition at line 217 of file EventInfo_t.h.
References fEnergyDepSpill, and setDep().
SetDepositedEnergyInSpillInActiveVolume()
void icarus::trigger::details::EventInfo_t::SetDepositedEnergyInSpillInActiveVolume (GeV e) inline
Sets the energy of the event deposited during beam gate in active volume [GeV]
Definition at line 228 of file EventInfo_t.h.
References fEnergyDepSpillActive, and setDep().
setGen()
void icarus::trigger::details::EventInfo_t::setGen () inline private
Declares that this object has generator information.
Definition at line 294 of file EventInfo_t.h.
References fHasGenerated.
Referenced by AddVertex(), AddWeakChargedCurrentInteractions(), AddWeakNeutralCurrentInteractions(), InsertVertex(), SetInActiveVolume(), SetInteractionTime(), SetInteractionType(), SetLeptonEnergy(), SetNeutrinoEnergy(), SetNeutrinoPDG(), SetNu_e(), and SetNu_mu().
SetInActiveVolume()
void icarus::trigger::details::EventInfo_t::SetInActiveVolume (bool active = true) inline
Set whether the event has relevant activity in the active volume.
Definition at line 201 of file EventInfo_t.h.
References fInActiveVolume, and setGen().
SetInteractionTime()
void icarus::trigger::details::EventInfo_t::SetInteractionTime (simulation_time time) inline
Sets the time of the first interaction.
Definition at line 197 of file EventInfo_t.h.
References fInteractionTime, and setGen().
SetInteractionType()
void icarus::trigger::details::EventInfo_t::SetInteractionType (int type) inline
Sets the interaction type.
Definition at line 194 of file EventInfo_t.h.
References setGen().
SetLeptonEnergy()
void icarus::trigger::details::EventInfo_t::SetLeptonEnergy (GeV eL) inline
Sets the lepton energy.
Definition at line 191 of file EventInfo_t.h.
References setGen().
SetNeutrinoEnergy()
void icarus::trigger::details::EventInfo_t::SetNeutrinoEnergy (GeV eNu) inline
Sets the neutrino energy.
Definition at line 188 of file EventInfo_t.h.
References setGen().
SetNeutrinoPDG()
void icarus::trigger::details::EventInfo_t::SetNeutrinoPDG (int NU) inline
Marks the neutrino type of the first interaction in the event.
Definition at line 185 of file EventInfo_t.h.
References setGen().
SetNu_e()
void icarus::trigger::details::EventInfo_t::SetNu_e (bool nue) inline
Marks this event as including n more weak charged current interactions.
Definition at line 182 of file EventInfo_t.h.
References setGen().
SetNu_mu()
void icarus::trigger::details::EventInfo_t::SetNu_mu (bool numu) inline
Marks the flavor of the neutrino in the first interaction.
Definition at line 181 of file EventInfo_t.h.
References setGen().
Vertices()
std::vector< geo::Point_t > const & icarus::trigger::details::EventInfo_t::Vertices () const inline
Returns the list of a known interaction vertex.
Definition at line 121 of file EventInfo_t.h.
References fVertices.
Referenced by icarus::trigger::TriggerEfficiencyPlotsBase::fillEventPlots().
Member Data Documentation
fEnergyDepActive
GeV icarus::trigger::details::EventInfo_t::fEnergyDepActive { 0.0 } private
Energy deposited in active volume.
Definition at line 284 of file EventInfo_t.h.
Referenced by DepositedEnergyInActiveVolume(), and SetDepositedEnergyInActiveVolume().
fEnergyDepPreSpill
GeV icarus::trigger::details::EventInfo_t::fEnergyDepPreSpill { 0.0 } private
Energy deposited in pre-spill.
Definition at line 283 of file EventInfo_t.h.
Referenced by DepositedEnergyInPreSpill(), and SetDepositedEnergyInPreSpill().
fEnergyDepPreSpillActive
GeV icarus::trigger::details::EventInfo_t::fEnergyDepPreSpillActive { 0.0 } private
Energy deposited in active volume in pre-spill window.
Definition at line 288 of file EventInfo_t.h.
Referenced by DepositedEnergyInPreSpillInActiveVolume(), and SetDepositedEnergyInPreSpillInActiveVolume().
fEnergyDepSpill
GeV icarus::trigger::details::EventInfo_t::fEnergyDepSpill { 0.0 } private
Energy deposited in spill.
Definition at line 282 of file EventInfo_t.h.
Referenced by DepositedEnergyInSpill(), and SetDepositedEnergyInSpill().
fEnergyDepSpillActive
GeV icarus::trigger::details::EventInfo_t::fEnergyDepSpillActive { 0.0 } private
Energy deposited in active volume in spill.
Definition at line 286 of file EventInfo_t.h.
Referenced by DepositedEnergyInSpillInActiveVolume(), and SetDepositedEnergyInSpillInActiveVolume().
fEnergyDepTotal
GeV icarus::trigger::details::EventInfo_t::fEnergyDepTotal { 0.0 } private
Total deposited energy.
Definition at line 281 of file EventInfo_t.h.
Referenced by DepositedEnergy(), and SetDepositedEnergy().
fHasDepEnergy
bool icarus::trigger::details::EventInfo_t::fHasDepEnergy = false private
Whether deposited energy info is available.
Definition at line 279 of file EventInfo_t.h.
Referenced by hasDepEnergy(), and setDep().
fHasGenerated
bool icarus::trigger::details::EventInfo_t::fHasGenerated = false private
Whether generation information is available.
Definition at line 254 of file EventInfo_t.h.
Referenced by hasGenerated(), and setGen().
fInActiveVolume
bool icarus::trigger::details::EventInfo_t::fInActiveVolume { false } private
Whether the event has activity inside the active volume.
Definition at line 271 of file EventInfo_t.h.
Referenced by isInActiveVolume(), and SetInActiveVolume().
fInteractions
std::array<unsigned int, NInteractionTypes> icarus::trigger::details::EventInfo_t::fInteractions private
Definition at line 256 of file EventInfo_t.h.
fInteractionTime
simulation_time icarus::trigger::details::EventInfo_t::fInteractionTime private
Time of the first interaction [ns].
Definition at line 261 of file EventInfo_t.h.
Referenced by InteractionTime(), and SetInteractionTime().
fInteractionType
int icarus::trigger::details::EventInfo_t::fInteractionType { 0 } private
Definition at line 259 of file EventInfo_t.h.
fLeptonEnergy
GeV icarus::trigger::details::EventInfo_t::fLeptonEnergy { 0.0 } private
Definition at line 264 of file EventInfo_t.h.
fNeutrinoEnergy
GeV icarus::trigger::details::EventInfo_t::fNeutrinoEnergy { 0.0 } private
Definition at line 263 of file EventInfo_t.h.
fNeutrinoPDG
int icarus::trigger::details::EventInfo_t::fNeutrinoPDG { 0 } private
Definition at line 258 of file EventInfo_t.h.
fVertices
std::vector<geo::Point_t> icarus::trigger::details::EventInfo_t::fVertices private
Position of all vertices.
Definition at line 273 of file EventInfo_t.h.
Referenced by AddVertex(), dump(), hasVertex(), InsertVertex(), nVertices(), and Vertices().
itWCC
std::size_t icarus::trigger::details::EventInfo_t::itWCC { 0U } static constexpr private
Charged weak current.
Definition at line 246 of file EventInfo_t.h.
Referenced by AddWeakChargedCurrentInteractions(), and nWeakChargedCurrentInteractions().
itWNC
std::size_t icarus::trigger::details::EventInfo_t::itWNC { 1U } static constexpr private
Neutral weak current.
Definition at line 247 of file EventInfo_t.h.
Referenced by AddWeakNeutralCurrentInteractions(), and nWeakNeutralCurrentInteractions().
NInteractionTypes
std::size_t icarus::trigger::details::EventInfo_t::NInteractionTypes { 2U } static constexpr private
Definition at line 248 of file EventInfo_t.h.
nu_e
bool icarus::trigger::details::EventInfo_t::nu_e { false } private
Definition at line 268 of file EventInfo_t.h.
nu_mu
bool icarus::trigger::details::EventInfo_t::nu_mu { false } private
Definition at line 267 of file EventInfo_t.h.
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfo_t.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/details/EventInfo_t.cxx