CAF format: sbn::DuplicateEventTracker Class Reference
sbn::DuplicateEventTracker Class Reference
Keeps track of duplicate events in the job.
#include <DuplicateEventTracker.h>
Classes
struct Config
Service configuration.
Public Types
using Parameters = art::ServiceTable<Config>
Public Member Functions
DuplicateEventTracker (Parameters const &config, art::ActivityRegistry &reg)
Constructor: reads the configuration.
void printSummary () const
Prints a summary of the current duplicates.
Protected Member Functions
Callback functions
void postEventReading (art::Event const &event, art::ScheduleContext)
Records the event and throws an exception depending on the configuration.
void postOpenFile (std::string const &fileName)
Records the current file name.
void postEndJob ()
Prints the summary and throws an exception depending on the configuration.
Protected Attributes
bool const fWarningOnly
Only warning, no exception.
bool const fSkipSummary
Do not print the summary of duplicate events.
bool const fExceptionAtEnd
Throw exception as late as possible.
std::string const fLogCategory
Message service category tag.
sbn::EventRegistry::FileID_t fCurrentInputFileID = sbn::EventRegistry::NoFileID
ID in the event registry of the current input file.
sbn::EventRegistry fEventRegistry
Record of all events and their source.
std::atomic< unsigned int > fNDuplicateEvents { 0U }
Duplicate event count.
Detailed Description
Keeps track of duplicate events in the job.
This art service maintains a record of all the processed events, and it takes action when one is processed more than once. The main purpose of the service is to detect the duplication as soon as possible and in such case to interrupt the job with an error, so that the input can be amended.
The default action is to immediately throw an exception. Alternatively, a warning message can be emitted each time an event is reprocessed, and a summary of all duplication can be emitted at the end of the job.
The service also offers an interface, to receive the current list of events that have been processed so far.
See sbn::EventRegistry for a description of the (large) memory usage of this service.
Configuration parameters
WarningOnly (flag, default: false): this flag has effect on warning messages and on exception throwing:
warning messages: if this flag is set to true, the service will emit a warning on each duplicate event encountered, otherwise it will not emit any warning (summary will still describe the duplicates if not skipped);
exception in case of duplicate events: if set to false, an exception will be thrown at the first duplicate event, unless ExceptionAtEnd is set, in which case the exception will be thrown at the end; if the flag is set to true, an exception is thrown at the end if ExceptionAtEnd is set, otherwise no exception is thrown at all
SkipSummary (flag, default: false): when set to true, it disables the printout of the duplicate events at the end of the job; unless WarningOnly is also set, this summary is going to be one-entry only
ExceptionAtEnd (flag, default: false): if duplicate events are detected, an exception is thrown at the end of the job instead of at the first duplicate event; this allows to assess all the duplicate events at once; if set, it is recommended that SkipSummary be disabled; note that with this option enabled, if duplicate events are detected an exception is always thrown (at the end of the job), regardless the setting of WarningOnly end of the job)
LogCategory (text, default: "DuplicateEventTracker"): tag of the output category used by this service to the message facility
Multi-threading notes
This service is designed to work with the concurrent processing of events from the same file. Reading multiple files is not supported (but art 3 doesn't do that anyway).
Definition at line 99 of file DuplicateEventTracker.h.
Class Documentation
sbn::DuplicateEventTracker::Config
struct sbn::DuplicateEventTracker::Config
Service configuration.
Definition at line 104 of file DuplicateEventTracker.h.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > ExceptionAtEnd
Atom< string > LogCategory
Atom< bool > SkipSummary
Atom< bool > WarningOnly
Member Typedef Documentation
Parameters
using sbn::DuplicateEventTracker::Parameters = art::ServiceTable<Config>
Definition at line 139 of file DuplicateEventTracker.h.
Constructor & Destructor Documentation
DuplicateEventTracker()
sbn::DuplicateEventTracker::DuplicateEventTracker (Parameters const & config, art::ActivityRegistry & reg)
Constructor: reads the configuration.
Definition at line 26 of file DuplicateEventTracker_service.cc.
References postEndJob(), postEventReading(), and postOpenFile().
Member Function Documentation
postEndJob()
void sbn::DuplicateEventTracker::postEndJob () protected
Prints the summary and throws an exception depending on the configuration.
Definition at line 140 of file DuplicateEventTracker_service.cc.
Referenced by DuplicateEventTracker().
postEventReading()
void sbn::DuplicateEventTracker::postEventReading (art::Event const & event, art::ScheduleContext) protected
Records the event and throws an exception depending on the configuration.
Definition at line 100 of file DuplicateEventTracker_service.cc.
References sbn::EventRegistry::EventRecord_t::sourceFiles.
Referenced by DuplicateEventTracker().
postOpenFile()
void sbn::DuplicateEventTracker::postOpenFile (std::string const & fileName) protected
Records the current file name.
Definition at line 90 of file DuplicateEventTracker_service.cc.
Referenced by DuplicateEventTracker().
printSummary()
void sbn::DuplicateEventTracker::printSummary () const
Prints a summary of the current duplicates.
Definition at line 45 of file DuplicateEventTracker_service.cc.
Member Data Documentation
fCurrentInputFileID
sbn::EventRegistry::FileID_t sbn::DuplicateEventTracker::fCurrentInputFileID = sbn::EventRegistry::NoFileID protected
ID in the event registry of the current input file.
Definition at line 162 of file DuplicateEventTracker.h.
fEventRegistry
sbn::EventRegistry sbn::DuplicateEventTracker::fEventRegistry protected
Record of all events and their source.
Definition at line 165 of file DuplicateEventTracker.h.
fExceptionAtEnd
bool const sbn::DuplicateEventTracker::fExceptionAtEnd protected
Throw exception as late as possible.
Definition at line 155 of file DuplicateEventTracker.h.
fLogCategory
std::string const sbn::DuplicateEventTracker::fLogCategory protected
Message service category tag.
Definition at line 157 of file DuplicateEventTracker.h.
fNDuplicateEvents
std::atomic<unsigned int> sbn::DuplicateEventTracker::fNDuplicateEvents { 0U } protected
Duplicate event count.
Definition at line 167 of file DuplicateEventTracker.h.
fSkipSummary
bool const sbn::DuplicateEventTracker::fSkipSummary protected
Do not print the summary of duplicate events.
Definition at line 154 of file DuplicateEventTracker.h.
fWarningOnly
bool const sbn::DuplicateEventTracker::fWarningOnly protected
Only warning, no exception.
Definition at line 153 of file DuplicateEventTracker.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/Utilities/DuplicateEventTracker.h
icaruscode/icaruscode/Utilities/DuplicateEventTracker_service.cc