CAF format: icaruscode/icaruscode/Utilities/ReadArtConfiguration.h File Reference
ReadArtConfiguration.h File Reference
Utilities to extract art FHiCL configuration from different sources.
#include "canvas/Persistency/Provenance/ProcessConfiguration.h"
#include "canvas/Persistency/Provenance/ProcessHistory.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "fhiclcpp/ParameterSet.h"
#include "fhiclcpp/ParameterSetID.h"
#include "fhiclcpp/ParameterSetRegistry.h"
#include "cetlib_except/exception.h"
#include "TFile.h"
#include <map>
Functions
std::map< fhicl::ParameterSetID, fhicl::ParameterSet > util::readConfigurationFromArtFile (TFile &file)
Reads and returns the art configuration stored in sourceDir.
template<typename Principal >
std::map< std::string, fhicl::ParameterSet > util::readConfigurationFromArtPrincipal (Principal const &principal)
Reads and returns the complete art configuration in the principal.
Detailed Description
Utilities to extract art FHiCL configuration from different sources.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Date
February 18, 2021
See also
icaruscode/Utilities/ReadArtConfiguration.cxx
Definition in file ReadArtConfiguration.h.
Function Documentation
readConfigurationFromArtFile()
std::map< fhicl::ParameterSetID, fhicl::ParameterSet > util::readConfigurationFromArtFile (TFile & file)
Reads and returns the art configuration stored in sourceDir.
Parameters
file ROOT file where the configuration is stored
Returns
the full configuration
Exceptions
cet::exception (category: "readConfigurationFromArtFile") on error
See also
readConfigurationFromArtPrincipal()
The configuration is expected to be stored by art in the way it does for art ROOT files.
The configuration is returned as a map of parameter set ID to parameter set.
Definition at line 21 of file ReadArtConfiguration.cxx.
References util::readConfigurationFromArtFile().
Referenced by util::readConfigurationFromArtFile().
readConfigurationFromArtPrincipal()
template<typename Principal > std::map< std::string, fhicl::ParameterSet > util::readConfigurationFromArtPrincipal (Principal const & principal)
Reads and returns the complete art configuration in the principal.
Template Parameters
Principal type of framework principal class (e.g. art::Event)
Parameters
principal the "principal" art object to read the information from
Returns
the full configuration, as map: process name -> FHiCL parameter set
Exceptions
cet::exception (category: "readConfigurationFromArtPrincipal") on error
See also
readConfigurationFromArtFile()
Compared to readConfigurationFromArtFile(), this function relays the same information after it has been conveniently extracted by the framework. A "principal" is framework jargon for art::Event, art::SubRun or art::Run (all derived from art::DataViewImpl). Therefore, this function can be called e.g. in beginRun() hook of a module using its art::Run argument, or in a analyze() hook using its art::Event argument.
This function is supposed to be more solid than readConfigurationFromArtFile() because it relies less on internals of how the framework works. Also, this function should also be compatible with gallery::Event too (which is the reason why it is implemented as template instead of taking a art::DataViewImpl, which is art-specific), making the name of this function a misnomer.
The configuration is returned as a map of process names to parameter sets (note that the key is different from the one returned by readConfigurationFromArtFile()).
The function extracts the configuration of all the known processes in the process history. As a workaround to fhiclcpp issue #14, if the configuration is not present, it's not included at all in the returned container of configurations (used to throw an exception).
Definition at line 103 of file ReadArtConfiguration.h.
References util::readConfigurationFromArtPrincipal().
Referenced by util::readConfigurationFromArtPrincipal().