CAF format: icarus::trigger::LVDSgates Class Reference
icarus::trigger::LVDSgates Class Reference
Combines discriminated PMT outputs into V1730 LVDS gates.
Classes
struct Config
struct SourceInfo_t
Information for each source.
Public Types
enum class ComboMode {
disable , Input1 , Input2 , AND ,
OR
}
Available operations for the combination of channels.
using TriggerGateData_t = icarus::trigger::OpticalTriggerGate::GateData_t
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
LVDSgates (Parameters const &config)
LVDSgates (LVDSgates const &)=delete
LVDSgates (LVDSgates &&)=delete
LVDSgates & operator= (LVDSgates const &)=delete
LVDSgates & operator= (LVDSgates &&)=delete
virtual void produce (art::Event &event) override
Fills the plots. Also extracts the information to fill them with.
template<typename Op >
auto binaryCombineChannel (std::vector< TrackedTriggerGate_t > const &gates, std::vector< raw::Channel_t > const &pairing, Op combine) const -> TrackedTriggerGate_t
Private Types
using BinaryCombinationFunc_t = OpticalTriggerGate& (OpticalTriggerGate::*)(OpticalTriggerGate const&)
Type of member function to combine the current gate with another one.
using TrackedTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Reconstituted trigger gate type internally used.
Private Member Functions
void produceThreshold (art::Event &event, icarus::trigger::OpDetWaveformMetaDataProductMap_t &waveformMap, std::string const &thresholdStr, SourceInfo_t const &srcInfo) const
Completely processes the data for the specified threshold.
std::vector< std::vector< raw::Channel_t > > removeChannels (std::vector< std::vector< raw::Channel_t > > channelPairing, std::vector< raw::Channel_t > const &ignoreChannels) const
Removes all the channel in ignoreChannels from channelPairing.
TrackedTriggerGate_t discardChannels (std::vector< TrackedTriggerGate_t > const &, std::vector< raw::Channel_t > const &pairing) const
Combination function for the disable mode.
TrackedTriggerGate_t selectChannel (std::vector< TrackedTriggerGate_t > const &, std::vector< raw::Channel_t > const &pairing, std::size_t chosenIndex) const
Combination function for the input1 and input2 modes.
template<typename Op >
TrackedTriggerGate_t binaryCombineChannel (std::vector< TrackedTriggerGate_t > const &gates, std::vector< raw::Channel_t > const &pairing, Op combine) const
Combination function for the AND and OR modes; op is from GateOps.
TrackedTriggerGate_t combineChannels (std::vector< TrackedTriggerGate_t > const &gates, std::vector< raw::Channel_t > const &pairing, ComboMode comboMode) const
Performs the combination of a group of channels.
unsigned int checkPairings () const
void checkInput (std::vector< TrackedTriggerGate_t > const &gates) const
Input requirement check. Throws if requirements fail.
Static Private Member Functions
static void UpdateWaveformMap (icarus::trigger::OpDetWaveformMetaDataProductMap_t &map, art::Assns< TriggerGateData_t, sbn::OpDetWaveformMeta > const &assns)
Adds the associated waveforms into the map.
static std::vector< TrackedTriggerGate_t > ReadTriggerGates (art::Event const &event, art::InputTag const &dataTag, icarus::trigger::OpDetWaveformMetaDataProductMap_t &waveformMap)
Assembles trigger gates from dataTag data products in event.
static art::InputTag makeTag (std::string const &thresholdStr, std::string const &defModule)
Converts a threshold string into an input tag.
static std::string makeOutputInstanceName (art::InputTag const &inputTag, std::string const &defModule)
Converts an input tag into an instance name for the corresponding output.
Private Attributes
std::map< std::string, SourceInfo_t > fADCthresholds
ADC thresholds to read, and the input tag connected to their data.
std::vector< std::vector< raw::Channel_t > > fChannelPairing
Pairing of optical detector channels.
ComboMode fComboMode
The operation used to combinate channels.
std::vector< raw::Channel_t > fIgnoreChannels
bool fProduceWaveformAssns
Whether to produce gate/waveform associations.
std::string fLogCategory
Message facility stream category for output.
Detailed Description
Combines discriminated PMT outputs into V1730 LVDS gates.
This module simulates the combination of discriminated PMT outputs by the V1730 board LVDS output.
Input data products
std::vector<icarus::trigger::OpticalTriggerGateData_t> (labels out of TriggerGatesTag and Thresholds): full sets of discriminated waveforms, each waveform possibly covering multiple optical channels, and their associations to optical waveform metadata. One set per threshold.
Requirements
The algorithms require that the list of discriminated waveforms has in each position the waveform from the optical detector channel number matching the position (e.g. entry 0 will be the discriminated waveform from channel 0, and so forth). No gaps are allowed: if no signal is present above threshold for a certain channel, a discriminated waveform should appear for that channel, with a gate always closed.
Output data products
std::vector<icarus::trigger::OpticalTriggerGateData_t> (instance name: concatenation of input module label and instance name of the input gates; the former is omitted if it is TriggerGatesTag): sets of gates combined according to the configuration; one set per input threshold.
art::Assns<icarus::trigger::OpticalTriggerGateData_t, sbn::OpDetWaveformMeta> (instance name: same as above): associations between each produced gate and the metadata of the optical waveforms providing the original data.
art::Assns<icarus::trigger::OpticalTriggerGateData_t, raw::OpDetWaveform> (instance name: same as above; optional): associations between each produced gate and the optical waveforms providing the original data. It is produced only if ProduceWaveformAssns configuration parameter is true, and it relies on the assumption that there is an association available between each sbn::OpDetWaveformMeta and its raw::OpDetWaveform, produced by the same module (i.e. with the same input tag) as the one of the original sbn::OpDetWaveformMeta data product itself.
Configuration parameters
A terse description of the parameters is printed by running lar --print-description LVDSgates.
TriggerGatesTag (string, mandatory): name of the module instance which produced the discriminated waveforms; it must not include any instance name, as the instance names will be automatically added from Thresholds parameter. This value is used as module name for all thresholds which do not specify one.
Thresholds (list of tags, mandatory): list of the discrimination thresholds to consider. A data product containing a digital signal is read for each one of the thresholds; each threshold entry is expected to be a input tag in the form "ModuleLabel:InstanceName"; both ModuleName and InstanceName may be omitted, in which case the colon : may also be omitted. In case the colon is omitted, the parameter will be considered an instance name if it represents an integer, and a module name otherwise. When the parameter is considered an instance name, the module is taken from the TriggerGatesTag parameter; when the instance name is omitted, it is considered empty. In this way, thresholds can be specified simply by a number, e.g. [ 200, 400, 600 ], which will be translated into e.g. "pmtfixedthr:200", "pmtfixedthr:400" and "pmtfixedthr:600", while a full specification can be also used: [ 200, "pmtthr:config" ], which will turn into "pmtfixedthr:200" and "pmtthr:config"; or a label-only one: [ 200, "pmtthr" ], which will turn into "pmtfixedthr:200" and "pmtthr".
ChannelPairing (list of integral number lists): channels to combine; each element of this list is itself a list of optical detector channel numbers. The channels within each group are combined according to CombinationMode, resulting in a single combined gate associated to all the channels in the group. All optical detector channels must appear in the configuration, and each channel can be combined only in one group. Groups must not be empty.
IgnoreChannels (list of integral numbers, optional): ID of the optical detector channels to skip.
CombinationMode (either: "disable", "input1", "input2", "AND" or "OR"): for each group of channels defined in ChannelPairing, the selected operation is used to combine all the channels in the group:
disable: all channels are discarded, and the resulting gates are all closed all the way;
input1: the first channel in the pairing is kept, and the others are discarded;
input2: the second channel in the pairing is kept, and the others are discarded;
AND: all channels are combined in a AND, resulting in a gate open only at the time when all the channel gates in the group are open; if there is a single channel in the group, the combined gate is a copy of it;
OR: all channels are combined in a OR, resulting in a gate open at every time when any of the channel gates in the group is open; if there is a single channel in the group, the combined gate is a copy of it. All pairings undergo the same operation (it is not possible, for example, disabling only one group of channels and combining the other groups with a AND).
ProduceWaveformAssns (flag, default: true): produce also associations between each gate and the raw::OpDetWaveform which contributed to it.
LogCategory (string): name of the output stream category for console messages (managed by MessageFacility library).
Definition at line 170 of file LVDSgates_module.cc.
Class Documentation
icarus::trigger::LVDSgates::SourceInfo_t
struct icarus::trigger::LVDSgates::SourceInfo_t
Information for each source.
Definition at line 289 of file LVDSgates_module.cc.
Class Members
InputTag inputTag
string outputInstanceName
Member Typedef Documentation
BinaryCombinationFunc_t
using icarus::trigger::LVDSgates::BinaryCombinationFunc_t = OpticalTriggerGate& (OpticalTriggerGate::*)(OpticalTriggerGate const&) private
Type of member function to combine the current gate with another one.
Definition at line 280 of file LVDSgates_module.cc.
Parameters
using icarus::trigger::LVDSgates::Parameters = art::EDProducer::Table<Config>
Definition at line 252 of file LVDSgates_module.cc.
TrackedTriggerGate_t
using icarus::trigger::LVDSgates::TrackedTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta> private
Reconstituted trigger gate type internally used.
Definition at line 283 of file LVDSgates_module.cc.
TriggerGateData_t
using icarus::trigger::LVDSgates::TriggerGateData_t = icarus::trigger::OpticalTriggerGate::GateData_t
Definition at line 174 of file LVDSgates_module.cc.
Member Enumeration Documentation
ComboMode
enum class icarus::trigger::LVDSgates::ComboMode strong
Available operations for the combination of channels.
Definition at line 177 of file LVDSgates_module.cc.
Constructor & Destructor Documentation
LVDSgates()
icarus::trigger::LVDSgates::LVDSgates (Parameters const & config) explicit
Definition at line 402 of file LVDSgates_module.cc.
Member Function Documentation
binaryCombineChannel() [1/2]
template<typename Op > TrackedTriggerGate_t icarus::trigger::LVDSgates::binaryCombineChannel (std::vector< TrackedTriggerGate_t > const & gates, std::vector< raw::Channel_t > const & pairing, Op combine) const private
Combination function for the AND and OR modes; op is from GateOps.
binaryCombineChannel() [2/2]
template<typename Op > auto icarus::trigger::LVDSgates::binaryCombineChannel (std::vector< TrackedTriggerGate_t > const & gates, std::vector< raw::Channel_t > const & pairing, Op combine) const -> TrackedTriggerGate_t
Definition at line 649 of file LVDSgates_module.cc.
checkInput()
void icarus::trigger::LVDSgates::checkInput (std::vector< TrackedTriggerGate_t > const & gates) const private
Input requirement check. Throws if requirements fail.
Definition at line 784 of file LVDSgates_module.cc.
References icarus::trigger::gatesIn().
checkPairings()
unsigned int icarus::trigger::LVDSgates::checkPairings () const private
Checks the pairing configuration, throws on error. Returns the number of configured channels.
Definition at line 695 of file LVDSgates_module.cc.
combineChannels()
auto icarus::trigger::LVDSgates::combineChannels (std::vector< TrackedTriggerGate_t > const & gates, std::vector< raw::Channel_t > const & pairing, ComboMode comboMode) const private
Performs the combination of a group of channels.
Definition at line 569 of file LVDSgates_module.cc.
discardChannels()
auto icarus::trigger::LVDSgates::discardChannels (std::vector< TrackedTriggerGate_t > const & gates, std::vector< raw::Channel_t > const & pairing) const private
Combination function for the disable mode.
Definition at line 618 of file LVDSgates_module.cc.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::TrackingInfo::add(), icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate(), and icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::tracking().
makeOutputInstanceName()
std::string icarus::trigger::LVDSgates::makeOutputInstanceName (art::InputTag const & inputTag, std::string const & defModule) static private
Converts an input tag into an instance name for the corresponding output.
Definition at line 885 of file LVDSgates_module.cc.
makeTag()
art::InputTag icarus::trigger::LVDSgates::makeTag (std::string const & thresholdStr, std::string const & defModule) static private
Converts a threshold string into an input tag.
Definition at line 865 of file LVDSgates_module.cc.
produce()
void icarus::trigger::LVDSgates::produce (art::Event & event) override virtual
Fills the plots. Also extracts the information to fill them with.
Definition at line 473 of file LVDSgates_module.cc.
produceThreshold()
void icarus::trigger::LVDSgates::produceThreshold (art::Event & event, icarus::trigger::OpDetWaveformMetaDataProductMap_t & waveformMap, std::string const & thresholdStr, SourceInfo_t const & srcInfo) const private
Completely processes the data for the specified threshold.
Definition at line 489 of file LVDSgates_module.cc.
References icarus::trigger::ReadTriggerGates(), and icarus::trigger::transformIntoOpticalTriggerGate().
ReadTriggerGates()
auto icarus::trigger::LVDSgates::ReadTriggerGates (art::Event const & event, art::InputTag const & dataTag, icarus::trigger::OpDetWaveformMetaDataProductMap_t & waveformMap) static private
Assembles trigger gates from dataTag data products in event.
Definition at line 845 of file LVDSgates_module.cc.
References icarus::trigger::FillTriggerGates().
removeChannels()
std::vector< std::vector< raw::Channel_t > > icarus::trigger::LVDSgates::removeChannels (std::vector< std::vector< raw::Channel_t > > channelPairing, std::vector< raw::Channel_t > const & ignoreChannels) const private
Removes all the channel in ignoreChannels from channelPairing.
Returns
a copy of channelPairing with no element from ignoreChannels
Channel lists in the returned list may become empty.
Definition at line 597 of file LVDSgates_module.cc.
selectChannel()
auto icarus::trigger::LVDSgates::selectChannel (std::vector< TrackedTriggerGate_t > const & gates, std::vector< raw::Channel_t > const & pairing, std::size_t chosenIndex) const private
Combination function for the input1 and input2 modes.
Definition at line 630 of file LVDSgates_module.cc.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate().
UpdateWaveformMap()
void icarus::trigger::LVDSgates::UpdateWaveformMap (icarus::trigger::OpDetWaveformMetaDataProductMap_t & map, art::Assns< TriggerGateData_t, sbn::OpDetWaveformMeta > const & assns) static private
Adds the associated waveforms into the map.
Definition at line 833 of file LVDSgates_module.cc.
Member Data Documentation
fADCthresholds
std::map<std::string, SourceInfo_t> icarus::trigger::LVDSgates::fADCthresholds private
ADC thresholds to read, and the input tag connected to their data.
Definition at line 295 of file LVDSgates_module.cc.
fChannelPairing
std::vector<std::vector<raw::Channel_t> > icarus::trigger::LVDSgates::fChannelPairing private
Pairing of optical detector channels.
Definition at line 298 of file LVDSgates_module.cc.
fComboMode
ComboMode icarus::trigger::LVDSgates::fComboMode private
The operation used to combinate channels.
Definition at line 299 of file LVDSgates_module.cc.
fIgnoreChannels
std::vector<raw::Channel_t> icarus::trigger::LVDSgates::fIgnoreChannels private
Definition at line 301 of file LVDSgates_module.cc.
fLogCategory
std::string icarus::trigger::LVDSgates::fLogCategory private
Message facility stream category for output.
Definition at line 306 of file LVDSgates_module.cc.
fProduceWaveformAssns
bool icarus::trigger::LVDSgates::fProduceWaveformAssns private
Whether to produce gate/waveform associations.
Definition at line 304 of file LVDSgates_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/LVDSgates_module.cc