CAF format: icarus::HitCollectionCreator Class Reference
icarus::HitCollectionCreator Class Reference
A class handling a collection of hits and its associations.
#include <HitCreator.h>
Public Member Functions
size_t size () const
Returns the number of hits currently in the collection.
void reserve (size_t new_size)
Prepares the collection to host at least new_size hits.
void put_into (art::Event &)
Moves the data into an event.
void put_into ()
Moves the data into the event.
std::vector< icarus::Hit > const & peek () const
Returns a read-only reference to the current list of hits.
Constructors
HitCollectionCreator (art::Event &event, std::string instance_name="", bool doWireAssns=true, bool doRawDigitAssns=true)
Constructor: sets instance name and whether to build associations.
HitCollectionCreator (art::Event &event, bool doWireAssns, bool doRawDigitAssns)
Constructor: no product instance name.
Addition of hits
void emplace_back (icarus::Hit &&hit, art::Ptr< recob::ChannelROI > const &wire=art::Ptr< recob::ChannelROI >(), art::Ptr< raw::RawDigit > const &digits=art::Ptr< raw::RawDigit >())
Adds the specified hit to the data collection.
void emplace_back (icarus::Hit const &hit, art::Ptr< recob::ChannelROI > const &wire=art::Ptr< recob::ChannelROI >(), art::Ptr< raw::RawDigit > const &digits=art::Ptr< raw::RawDigit >())
Adds the specified hit to the data collection.
void emplace_back (HitCreator &&hit, art::Ptr< recob::ChannelROI > const &wire=art::Ptr< recob::ChannelROI >(), art::Ptr< raw::RawDigit > const &digits=art::Ptr< raw::RawDigit >())
Adds the specified hit to the data collection.
void emplace_back (icarus::Hit &&hit, art::Ptr< raw::RawDigit > const &digits)
Adds the specified hit to the data collection.
void emplace_back (HitCreator &&hit, art::Ptr< raw::RawDigit > const &digits)
Adds the specified hit to the data collection.
void emplace_back (HitCreator const &hit, art::Ptr< raw::RawDigit > const &digits)
Adds the specified hit to the data collection.
Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
size_t size () const
Returns the number of hits currently in the collection.
void put_into (art::Event &)
Moves the data into the event.
void put_into ()
Moves the data into the event.
std::vector< icarus::Hit > const & peek () const
Returns a read-only reference to the current list of hits.
Protected Types
using HitPtr_t = HitAndAssociationsWriterBase::HitPtr_t
Protected Types inherited from icarus::HitAndAssociationsWriterBase
using HitPtr_t = art::Ptr<icarus::Hit>
Type of art pointer to Hit.
Protected Member Functions
HitPtr_t CreatePtrToLastHit () const
Creates an art pointer to the hit with the last index.
void CreateAssociationsToLastHit (art::Ptr< recob::ChannelROI > const &wire, art::Ptr< raw::RawDigit > const &digits)
Creates associations between the last hit and the specified pointers.
Protected Member Functions inherited from icarus::HitAndAssociationsWriterBase
HitAndAssociationsWriterBase (art::Event &event, std::string instance_name, bool doWireAssns, bool doRawDigitAssns)
Constructor: sets instance name and whether to build associations.
HitPtr_t CreatePtr (size_t index) const
Creates an art pointer to the hit with the specified index.
Additional Inherited Members
Static Public Member Functions inherited from icarus::HitAndAssociationsWriterBase
static void declare_products (art::ProducesCollector &collector, std::string instance_name="", bool doWireAssns=true, bool doRawDigitAssns=true)
Declares the hit products we are going to fill.
Protected Attributes inherited from icarus::HitAndAssociationsWriterBase
std::string prod_instance
Tame of the instance for data products.
std::unique_ptr< std::vector< icarus::Hit > > hits
Collection of hits.
std::unique_ptr< art::Assns< recob::ChannelROI, icarus::Hit > > WireAssns
Associations with wires.
std::unique_ptr< art::Assns< raw::RawDigit, icarus::Hit > > RawDigitAssns
Associations with raw digits.
art::Event * event = nullptr
Pointer to the event we are using.
art::PtrMaker< icarus::Hit > hitPtrMaker
Tool to create hit pointers,.
Detailed Description
A class handling a collection of hits and its associations.
Instead of creating a collection of hits, one for its association with wires and one for its association with raw digits, one can push hits into this object, and then move it into the event.
Definition at line 481 of file HitCreator.h.
Member Typedef Documentation
HitPtr_t
using icarus::HitCollectionCreator::HitPtr_t = HitAndAssociationsWriterBase::HitPtr_t protected
Definition at line 629 of file HitCreator.h.
Constructor & Destructor Documentation
HitCollectionCreator() [1/2]
icarus::HitCollectionCreator::HitCollectionCreator (art::Event & event, std::string instance_name = "", bool doWireAssns = true, bool doRawDigitAssns = true)
Constructor: sets instance name and whether to build associations.
Parameters
event the event the products are going to be put into
instance_name name of the instance for all data products
doWireAssns whether to enable associations to wires
doRawDigitAssns whether to enable associations to raw digits
All the data products (hit collection and associations) will have the specified product instance name.
Definition at line 273 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits.
HitCollectionCreator() [2/2]
icarus::HitCollectionCreator::HitCollectionCreator (art::Event & event, bool doWireAssns, bool doRawDigitAssns) inline
Constructor: no product instance name.
Parameters
event the event the products are going to be put into
doWireAssns whether to enable associations to wires
doRawDigitAssns whether to enable associations to raw digits
Definition at line 506 of file HitCreator.h.
Member Function Documentation
CreateAssociationsToLastHit()
void icarus::HitCollectionCreator::CreateAssociationsToLastHit (art::Ptr< recob::ChannelROI > const & wire, art::Ptr< raw::RawDigit > const & digits) protected
Creates associations between the last hit and the specified pointers.
Definition at line 319 of file HitCreator.cxx.
References CreatePtrToLastHit(), icarus::HitAndAssociationsWriterBase::RawDigitAssns, and icarus::HitAndAssociationsWriterBase::WireAssns.
Referenced by emplace_back(), and emplace_back().
CreatePtrToLastHit()
HitPtr_t icarus::HitCollectionCreator::CreatePtrToLastHit () const inline protected
Creates an art pointer to the hit with the last index.
Definition at line 632 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::CreatePtr(), and icarus::HitAndAssociationsWriterBase::hits.
Referenced by CreateAssociationsToLastHit().
emplace_back() [1/6]
void icarus::HitCollectionCreator::emplace_back (HitCreator && hit, art::Ptr< raw::RawDigit > const & digits) inline
Adds the specified hit to the data collection.
Parameters
hit the HitCreator object containing the hit
digits art pointer to the raw digits to be associated to this hit
After this call, the hit creator will be empty. If the digit pointer is not valid, its association will not be stored.
Definition at line 578 of file HitCreator.h.
References emplace_back().
emplace_back() [2/6]
void icarus::HitCollectionCreator::emplace_back (HitCreator && hit, art::Ptr< recob::ChannelROI > const & wire = art::Ptr<recob::ChannelROI>(), art::Ptr< raw::RawDigit > const & digits = art::Ptr<raw::RawDigit>()) inline
Adds the specified hit to the data collection.
Parameters
hit the HitCreator object containing the hit
wire art pointer to the wire to be associated to this hit
digits art pointer to the raw digits to be associated to this hit
After this call, the hit creator will be empty. If a art pointer is not valid, that association will not be stored.
Definition at line 550 of file HitCreator.h.
References emplace_back().
emplace_back() [3/6]
void icarus::HitCollectionCreator::emplace_back (HitCreator const & hit, art::Ptr< raw::RawDigit > const & digits) inline
Adds the specified hit to the data collection.
Parameters
hit the HitCreator object containing the hit
digits art pointer to the raw digits to be associated to this hit
If the digit pointer is not valid, its association will not be stored.
Definition at line 590 of file HitCreator.h.
References icarus::HitCreator::copy(), and emplace_back().
emplace_back() [4/6]
void icarus::HitCollectionCreator::emplace_back (icarus::Hit && hit, art::Ptr< raw::RawDigit > const & digits) inline
Adds the specified hit to the data collection.
Parameters
hit the hit that will be moved into the collection
digits art pointer to the raw digits to be associated to this hit
After this call, hit will be invalid. If the digit pointer is not valid, its association will not be stored.
Definition at line 565 of file HitCreator.h.
References emplace_back().
emplace_back() [5/6]
void icarus::HitCollectionCreator::emplace_back (icarus::Hit && hit, art::Ptr< recob::ChannelROI > const & wire = art::Ptr<recob::ChannelROI>(), art::Ptr< raw::RawDigit > const & digits = art::Ptr<raw::RawDigit>())
Adds the specified hit to the data collection.
Parameters
hit the hit that will be moved into the collection
wire art pointer to the wire to be associated to this hit
digits art pointer to the raw digits to be associated to this hit
After this call, hit will be invalid. If a art pointer is not valid, that association will not be stored.
Definition at line 284 of file HitCreator.cxx.
References CreateAssociationsToLastHit(), and icarus::HitAndAssociationsWriterBase::hits.
Referenced by emplace_back(), emplace_back(), emplace_back(), and emplace_back().
emplace_back() [6/6]
void icarus::HitCollectionCreator::emplace_back (icarus::Hit const & hit, art::Ptr< recob::ChannelROI > const & wire = art::Ptr<recob::ChannelROI>(), art::Ptr< raw::RawDigit > const & digits = art::Ptr<raw::RawDigit>())
Adds the specified hit to the data collection.
Parameters
hit the hit that will be copied into the collection
wire art pointer to the wire to be associated to this hit
digits art pointer to the raw digits to be associated to this hit
If a art pointer is not valid, that association will not be stored.
Definition at line 296 of file HitCreator.cxx.
References CreateAssociationsToLastHit(), and icarus::HitAndAssociationsWriterBase::hits.
peek()
std::vector< icarus::Hit > const & icarus::HitCollectionCreator::peek () const inline
Returns a read-only reference to the current list of hits.
Definition at line 626 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::hits.
put_into() [1/2]
void icarus::HitCollectionCreator::put_into ()
Moves the data into the event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Definition at line 308 of file HitCreator.cxx.
References icarus::HitAndAssociationsWriterBase::hits, and icarus::HitAndAssociationsWriterBase::put_into().
put_into() [2/2]
void icarus::HitCollectionCreator::put_into (art::Event &) inline
Moves the data into an event.
The calling module must have already declared the production of these products with the proper instance name. After the move, the collections in this object are empty.
Deprecated
Use the version with no arguments instead.
Definition at line 614 of file HitCreator.h.
References put_into().
Referenced by put_into().
reserve()
void icarus::HitCollectionCreator::reserve (size_t new_size) inline
Prepares the collection to host at least new_size hits.
Definition at line 600 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::hits.
size()
size_t icarus::HitCollectionCreator::size () const inline
Returns the number of hits currently in the collection.
Definition at line 597 of file HitCreator.h.
References icarus::HitAndAssociationsWriterBase::hits.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/TPC/Utilities/HitCreator.h
icaruscode/icaruscode/TPC/Utilities/HitCreator.cxx