CAF format: icarus::AnalysisTreeDataStruct::BoxedArray< Array_t > Class Template Reference
icarus::AnalysisTreeDataStruct::BoxedArray< Array_t > Class Template Reference
A wrapper to a C array (needed to embed an array into a vector)
Public Types
using This_t = BoxedArray<Array_t>
typedef std::remove_all_extents< Array_t >::type Data_t
Public Member Functions
BoxedArray (const This_t &from)
Array_t & data ()
const Array_t & data () const
Data_t * begin ()
const Data_t * begin () const
Data_t * end ()
const Data_t * end () const
auto operator[] (size_t index) -> decltype(*array)
Array interface.
auto operator[] (size_t index) const -> decltype(*array)
auto operator+ (ptrdiff_t index) -> decltype(&*array)
auto operator+ (ptrdiff_t index) const -> decltype(&*array)
auto operator- (ptrdiff_t index) -> decltype(&*array)
auto operator- (ptrdiff_t index) const -> decltype(&*array)
auto operator* () -> decltype(*array)
auto operator* () const -> decltype(*array)
operator decltype(&[0]) array ()
operator decltype(&[0]) array () const
Static Public Member Functions
static constexpr size_t size ()
begin/end interface
Protected Attributes
Array_t array
Detailed Description
template<typename Array_t>
class icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >
A wrapper to a C array (needed to embed an array into a vector)
Definition at line 166 of file AnalysisTree_module.cc.
Member Typedef Documentation
Data_t
template<typename Array_t > std::remove_all_extents<Array_t>::type icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::Data_t
Definition at line 172 of file AnalysisTree_module.cc.
This_t
template<typename Array_t > using icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::This_t = BoxedArray<Array_t>
Definition at line 171 of file AnalysisTree_module.cc.
Constructor & Destructor Documentation
BoxedArray() [1/2]
template<typename Array_t > icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::BoxedArray () inline
Definition at line 174 of file AnalysisTree_module.cc.
BoxedArray() [2/2]
template<typename Array_t > icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::BoxedArray (const This_t & from) inline
Definition at line 175 of file AnalysisTree_module.cc.
Member Function Documentation
array() [1/2]
template<typename Array_t > operator decltype(&[0]) icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::array () inline
Definition at line 201 of file AnalysisTree_module.cc.
array() [2/2]
template<typename Array_t > operator decltype(&[0]) icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::array () const inline
Definition at line 202 of file AnalysisTree_module.cc.
begin() [1/2]
template<typename Array_t > Data_t * icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::begin () inline
Definition at line 184 of file AnalysisTree_module.cc.
begin() [2/2]
template<typename Array_t > const Data_t * icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::begin () const inline
Definition at line 185 of file AnalysisTree_module.cc.
data() [1/2]
template<typename Array_t > Array_t & icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::data () inline
Definition at line 178 of file AnalysisTree_module.cc.
Referenced by DataLoader3.DataLoader::__init__(), DataLoader3.DataLoader::addRow(), DataLoader3.DataLoader::clearRows(), and DataLoader3.DataLoader::send().
data() [2/2]
template<typename Array_t > const Array_t & icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::data () const inline
Definition at line 179 of file AnalysisTree_module.cc.
Referenced by DataLoader3.DataLoader::__init__(), DataLoader3.DataLoader::addRow(), DataLoader3.DataLoader::clearRows(), and DataLoader3.DataLoader::send().
end() [1/2]
template<typename Array_t > Data_t * icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::end () inline
Definition at line 186 of file AnalysisTree_module.cc.
end() [2/2]
template<typename Array_t > const Data_t * icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::end () const inline
Definition at line 187 of file AnalysisTree_module.cc.
operator*() [1/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator* () -> decltype(*array) inline
Definition at line 198 of file AnalysisTree_module.cc.
operator*() [2/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator* () const -> decltype(*array) inline
Definition at line 199 of file AnalysisTree_module.cc.
operator+() [1/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator+ (ptrdiff_t index) -> decltype(&*array) inline
Definition at line 194 of file AnalysisTree_module.cc.
operator+() [2/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator+ (ptrdiff_t index) const -> decltype(&*array) inline
Definition at line 195 of file AnalysisTree_module.cc.
operator-() [1/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator- (ptrdiff_t index) -> decltype(&*array) inline
Definition at line 196 of file AnalysisTree_module.cc.
operator-() [2/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator- (ptrdiff_t index) const -> decltype(&*array) inline
Definition at line 197 of file AnalysisTree_module.cc.
operator[]() [1/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator[] (size_t index) -> decltype(*array) inline
Array interface.
Definition at line 192 of file AnalysisTree_module.cc.
operator[]() [2/2]
template<typename Array_t > auto icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::operator[] (size_t index) const -> decltype(*array) inline
Definition at line 193 of file AnalysisTree_module.cc.
size()
template<typename Array_t > static constexpr size_t icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::size () inline static constexpr
begin/end interface
Definition at line 183 of file AnalysisTree_module.cc.
Member Data Documentation
array
template<typename Array_t > Array_t icarus::AnalysisTreeDataStruct::BoxedArray< Array_t >::array protected
Definition at line 168 of file AnalysisTree_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Analysis/AnalysisTree_module.cc