CAF format: icarusDB::ICARUSChannelMapProvider Class Reference
icarusDB::ICARUSChannelMapProvider Class Reference
Interface to the channel mapping databases of TPC, CRT and PMT subdetectors.
#include <ICARUSChannelMapProvider.h>
Public Member Functions
ICARUSChannelMapProvider (const fhicl::ParameterSet &pset)
bool hasFragmentID (const unsigned int) const override
Returns whether the specified ID is a known TPC fragment ID.
unsigned int nTPCfragmentIDs () const override
Returns the number of TPC fragment IDs known to the service.
const std::string & getCrateName (const unsigned int) const override
Returns the name of the crate served by the specified fragmentID.
const ReadoutIDVec & getReadoutBoardVec (const unsigned int) const override
Returns the list of board IDs included in the specified fragmentID.
const TPCReadoutBoardToChannelMap & getReadoutBoardToChannelMap () const override
Returns the full TPC channel mapping.
bool hasBoardID (const unsigned int) const override
Returns whether there is a board with the specified ID.
unsigned int nTPCboardIDs () const override
Returns the number of TPC board IDs known to the service.
unsigned int getBoardSlot (const unsigned int) const override
Returns the number of slot the boardID is on.
const ChannelPlanePairVec & getChannelPlanePair (const unsigned int) const override
bool hasPMTDigitizerID (const unsigned int) const override
Returns whether the specified fragment ID is known to the mapping.
unsigned int nPMTfragmentIDs () const override
Returns the number of PMT fragment IDs known to the service.
const PMTdigitizerInfoVec & getPMTchannelInfo (unsigned int) const override
Returns records on all the PMT channels covered by the fragment ID.
unsigned int getSimMacAddress (const unsigned int) const override
unsigned int gettopSimMacAddress (const unsigned int) const override
std::pair< double, double > getSideCRTCalibrationMap (int mac5, int chan) const override
Returns the Gain and Pedestal for Side CRT.
bool forRun (int run) override
Loads the mapping for run, returns whether a new mapping was loaded.
bool forPeriod (icarusDB::RunPeriod period) override
Loads the mapping for period, returns whether a new mapping was loaded.
Public Member Functions inherited from icarusDB::IICARUSChannelMap
provider_type const * provider () const
Returns the service provider.
Public Member Functions inherited from icarusDB::IICARUSChannelMapProvider
Public Member Functions inherited from util::CacheCounter
CacheCounter ()
Constructor: prepares the ID of the default cache tag.
CacheCounter (std::initializer_list< CacheTag_t > tags)
Constructor: prepares the ID of the caches with the specified tags.
void addCacheTags (std::initializer_list< CacheTag_t > tags)
Adds tags. The ID of existing ones are not changed.
CacheID_t cacheID (CacheTag_t const &tag) const
Returns the current ID of the cache with the specified tag.
bool hasTag (CacheTag_t const &tag) const
Returns whether the specified tag is tracked.
bool wasCacheUpdatedSince (CacheTag_t const &tag, CacheID_t sinceID) const
Returns whether the cache tag was updated since it has sinceID ID.
bool wasCacheUpdatedSince (CacheID_t sinceID) const
Returns whether the default cache was updated since it has sinceID ID.
Static Public Member Functions
static constexpr unsigned int PMTfragmentIDtoDBkey (unsigned int fragmentID)
Returns the channel mapping database key for the specified PMT fragment ID.
static constexpr unsigned int DBkeyToPMTfragmentID (unsigned int DBkey)
Returns the PMT fragment ID for the specified channel mapping database key.
Private Member Functions
void readFromDatabase ()
Has the channel mapping tool fill the mapping caches.
PMTdigitizerInfoVec const * findPMTfragmentEntry (unsigned int fragmentID) const
Private Attributes
bool fDiagnosticOutput
TPCFragmentIDToReadoutIDMap fFragmentToReadoutMap
TPCReadoutBoardToChannelMap fReadoutBoardToChannelMap
PMTFragmentToDigitizerChannelMap fFragmentToDigitizerMap
CRTChannelIDToHWtoSimMacAddressPairMap fCRTChannelIDToHWtoSimMacAddressPairMap
TopCRTHWtoSimMacAddressPairMap fTopCRTHWtoSimMacAddressPairMap
SideCRTChannelToCalibrationMap fSideCRTChannelToCalibrationMap
std::unique_ptr< IChannelMapping > fChannelMappingTool
Additional Inherited Members
Public Types inherited from icarusDB::IICARUSChannelMap
using provider_type = icarusDB::IICARUSChannelMapProvider
Type of the service provider.
Public Types inherited from util::CacheCounter
using CacheID_t = unsigned long
Type of cache identifier.
using CacheTag_t = std::string
Type of cache name.
Static Public Attributes inherited from util::CacheCounter
static constexpr CacheID_t NoCache = 0
ID specifying that cache is not present yet.
Protected Member Functions inherited from util::CacheCounter
CacheID_t updateCacheID (CacheTag_t const &cacheTag="") const
Protected Attributes inherited from util::CacheCounter
std::map< CacheTag_t, std::atomic< CacheID_t > > fCacheID
ID of the current caches.
Detailed Description
Interface to the channel mapping databases of TPC, CRT and PMT subdetectors.
Before retrieving the information, a run period (forPeriod()) or a run (forRun()) must be selected.
Definition at line 31 of file ICARUSChannelMapProvider.h.
Constructor & Destructor Documentation
ICARUSChannelMapProvider()
icarusDB::ICARUSChannelMapProvider::ICARUSChannelMapProvider (const fhicl::ParameterSet & pset)
Definition at line 31 of file ICARUSChannelMapProvider.cxx.
Member Function Documentation
DBkeyToPMTfragmentID()
unsigned int icarusDB::ICARUSChannelMapProvider::DBkeyToPMTfragmentID (unsigned int DBkey) static constexpr
Returns the PMT fragment ID for the specified channel mapping database key.
Definition at line 337 of file ICARUSChannelMapProvider.cxx.
findPMTfragmentEntry()
auto icarusDB::ICARUSChannelMapProvider::findPMTfragmentEntry (unsigned int fragmentID) const private
Returns the list of records of all channels in the PMT readout board with the specified fragment.
Returns
a pointer to the mapping list, or nullptr if invalid fragment
Definition at line 312 of file ICARUSChannelMapProvider.cxx.
Referenced by getPMTchannelInfo(), and hasPMTDigitizerID().
forPeriod()
bool icarusDB::ICARUSChannelMapProvider::forPeriod (icarusDB::RunPeriod period) override virtual
Loads the mapping for period, returns whether a new mapping was loaded.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 66 of file ICARUSChannelMapProvider.cxx.
References readFromDatabase().
Referenced by forRun().
forRun()
bool icarusDB::ICARUSChannelMapProvider::forRun (int run) override virtual
Loads the mapping for run, returns whether a new mapping was loaded.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 43 of file ICARUSChannelMapProvider.cxx.
References forPeriod(), and icarusDB::RunPeriods::withRun().
getBoardSlot()
unsigned int icarusDB::ICARUSChannelMapProvider::getBoardSlot (const unsigned int boardID) const override virtual
Returns the number of slot the boardID is on.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 232 of file ICARUSChannelMapProvider.cxx.
getChannelPlanePair()
const ChannelPlanePairVec & icarusDB::ICARUSChannelMapProvider::getChannelPlanePair (const unsigned int boardID) const override virtual
Returns a list of channels served by the boardID and for each the plane it is on (0 to 2).
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 242 of file ICARUSChannelMapProvider.cxx.
getCrateName()
const std::string & icarusDB::ICARUSChannelMapProvider::getCrateName (const unsigned int fragmentID) const override virtual
Returns the name of the crate served by the specified fragmentID.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 194 of file ICARUSChannelMapProvider.cxx.
getPMTchannelInfo()
const PMTdigitizerInfoVec & icarusDB::ICARUSChannelMapProvider::getPMTchannelInfo (unsigned int fragmentID) const override virtual
Returns records on all the PMT channels covered by the fragment ID.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 265 of file ICARUSChannelMapProvider.cxx.
References findPMTfragmentEntry().
getReadoutBoardToChannelMap()
const TPCReadoutBoardToChannelMap & icarusDB::ICARUSChannelMapProvider::getReadoutBoardToChannelMap () const override virtual
Returns the full TPC channel mapping.
— END - - - TPC fragment information - - - - - - - - - - - - - - - - - -
The returned mapping is an associative container, associating each board ID (boardID) to the following information (in a std::tuple):
[0] slot number the board is on (like getBoardSlot(boardID))
[1] list of channels served by the board, and their plane (like getChannelPlanePair(boardID))
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 215 of file ICARUSChannelMapProvider.cxx.
getReadoutBoardVec()
const ReadoutIDVec & icarusDB::ICARUSChannelMapProvider::getReadoutBoardVec (const unsigned int fragmentID) const override virtual
Returns the list of board IDs included in the specified fragmentID.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 204 of file ICARUSChannelMapProvider.cxx.
getSideCRTCalibrationMap()
std::pair< double, double > icarusDB::ICARUSChannelMapProvider::getSideCRTCalibrationMap (int mac5, int chan) const override virtual
Returns the Gain and Pedestal for Side CRT.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 305 of file ICARUSChannelMapProvider.cxx.
getSimMacAddress()
unsigned int icarusDB::ICARUSChannelMapProvider::getSimMacAddress (const unsigned int hwmacaddress) const override virtual
Returns the Sim Mac address corresponding to the specified side CRT hardware address.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 276 of file ICARUSChannelMapProvider.cxx.
gettopSimMacAddress()
unsigned int icarusDB::ICARUSChannelMapProvider::gettopSimMacAddress (const unsigned int) const override virtual
Returns the sim Mac address corresponding to the specified top CRT hardware address.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 288 of file ICARUSChannelMapProvider.cxx.
hasBoardID()
bool icarusDB::ICARUSChannelMapProvider::hasBoardID (const unsigned int ID) const override virtual
Returns whether there is a board with the specified ID.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 221 of file ICARUSChannelMapProvider.cxx.
hasFragmentID()
bool icarusDB::ICARUSChannelMapProvider::hasFragmentID (const unsigned int ID) const override virtual
Returns whether the specified ID is a known TPC fragment ID.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 183 of file ICARUSChannelMapProvider.cxx.
hasPMTDigitizerID()
bool icarusDB::ICARUSChannelMapProvider::hasPMTDigitizerID (const unsigned int ID) const override virtual
Returns whether the specified fragment ID is known to the mapping.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 253 of file ICARUSChannelMapProvider.cxx.
References findPMTfragmentEntry().
nPMTfragmentIDs()
unsigned int icarusDB::ICARUSChannelMapProvider::nPMTfragmentIDs () const override virtual
Returns the number of PMT fragment IDs known to the service.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 259 of file ICARUSChannelMapProvider.cxx.
nTPCboardIDs()
unsigned int icarusDB::ICARUSChannelMapProvider::nTPCboardIDs () const override virtual
Returns the number of TPC board IDs known to the service.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 227 of file ICARUSChannelMapProvider.cxx.
nTPCfragmentIDs()
unsigned int icarusDB::ICARUSChannelMapProvider::nTPCfragmentIDs () const override virtual
Returns the number of TPC fragment IDs known to the service.
Implements icarusDB::IICARUSChannelMapProvider.
Definition at line 189 of file ICARUSChannelMapProvider.cxx.
PMTfragmentIDtoDBkey()
unsigned int icarusDB::ICARUSChannelMapProvider::PMTfragmentIDtoDBkey (unsigned int fragmentID) static constexpr
Returns the channel mapping database key for the specified PMT fragment ID.
Definition at line 320 of file ICARUSChannelMapProvider.cxx.
readFromDatabase()
void icarusDB::ICARUSChannelMapProvider::readFromDatabase () private
Has the channel mapping tool fill the mapping caches.
Definition at line 76 of file ICARUSChannelMapProvider.cxx.
Referenced by forPeriod().
Member Data Documentation
fChannelMappingTool
std::unique_ptr<IChannelMapping> icarusDB::ICARUSChannelMapProvider::fChannelMappingTool private
Definition at line 98 of file ICARUSChannelMapProvider.h.
fCRTChannelIDToHWtoSimMacAddressPairMap
CRTChannelIDToHWtoSimMacAddressPairMap icarusDB::ICARUSChannelMapProvider::fCRTChannelIDToHWtoSimMacAddressPairMap private
Definition at line 92 of file ICARUSChannelMapProvider.h.
fDiagnosticOutput
bool icarusDB::ICARUSChannelMapProvider::fDiagnosticOutput private
Definition at line 84 of file ICARUSChannelMapProvider.h.
fFragmentToDigitizerMap
PMTFragmentToDigitizerChannelMap icarusDB::ICARUSChannelMapProvider::fFragmentToDigitizerMap private
Definition at line 90 of file ICARUSChannelMapProvider.h.
fFragmentToReadoutMap
TPCFragmentIDToReadoutIDMap icarusDB::ICARUSChannelMapProvider::fFragmentToReadoutMap private
Definition at line 86 of file ICARUSChannelMapProvider.h.
fReadoutBoardToChannelMap
TPCReadoutBoardToChannelMap icarusDB::ICARUSChannelMapProvider::fReadoutBoardToChannelMap private
Definition at line 88 of file ICARUSChannelMapProvider.h.
fSideCRTChannelToCalibrationMap
SideCRTChannelToCalibrationMap icarusDB::ICARUSChannelMapProvider::fSideCRTChannelToCalibrationMap private
Definition at line 96 of file ICARUSChannelMapProvider.h.
fTopCRTHWtoSimMacAddressPairMap
TopCRTHWtoSimMacAddressPairMap icarusDB::ICARUSChannelMapProvider::fTopCRTHWtoSimMacAddressPairMap private
Definition at line 94 of file ICARUSChannelMapProvider.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.h
icaruscode/icaruscode/Decode/ChannelMapping/Legacy/ICARUSChannelMapProvider.cxx