CAF format: icarus::trigger::WindowChannelMap::WindowTopology_t Struct Reference
icarus::trigger::WindowChannelMap::WindowTopology_t Struct Reference
Information of the identity and neighbourhood of a window.
#include <WindowChannelMap.h>
Public Member Functions
bool hasUpstreamWindow () const
Returns whether the main window has another upstream of it.
bool hasDownstreamWindow () const
Returns whether the main window has another downstream of it.
bool hasOppositeWindow () const
Returns whether the main window has another downstream of it.
Public Attributes
WindowIndex_t index
Index of the window this information is about.
WindowIndex_t opposite { InvalidWindowIndex }
Index of the window opposite to this one.
WindowIndex_t upstream { InvalidWindowIndex }
Index of the window upstream of this one.
WindowIndex_t downstream { InvalidWindowIndex }
Index of the window downstream of this one.
Detailed Description
Information of the identity and neighbourhood of a window.
Definition at line 79 of file WindowChannelMap.h.
Member Function Documentation
hasDownstreamWindow()
bool icarus::trigger::WindowChannelMap::WindowTopology_t::hasDownstreamWindow () const inline
Returns whether the main window has another downstream of it.
Definition at line 96 of file WindowChannelMap.h.
References downstream, and icarus::trigger::WindowChannelMap::isValidWindow().
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), and icarus::trigger::WindowChannelMap::WindowInfo_t::dump().
hasOppositeWindow()
bool icarus::trigger::WindowChannelMap::WindowTopology_t::hasOppositeWindow () const inline
Returns whether the main window has another downstream of it.
Definition at line 99 of file WindowChannelMap.h.
References icarus::trigger::WindowChannelMap::isValidWindow(), and opposite.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), and icarus::trigger::WindowChannelMap::WindowInfo_t::dump().
hasUpstreamWindow()
bool icarus::trigger::WindowChannelMap::WindowTopology_t::hasUpstreamWindow () const inline
Returns whether the main window has another upstream of it.
Definition at line 93 of file WindowChannelMap.h.
References icarus::trigger::WindowChannelMap::isValidWindow(), and upstream.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), and icarus::trigger::WindowChannelMap::WindowInfo_t::dump().
Member Data Documentation
downstream
WindowIndex_t icarus::trigger::WindowChannelMap::WindowTopology_t::downstream { InvalidWindowIndex }
Index of the window downstream of this one.
Definition at line 90 of file WindowChannelMap.h.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::WindowChannelMap::WindowInfo_t::dump(), and hasDownstreamWindow().
index
WindowIndex_t icarus::trigger::WindowChannelMap::WindowTopology_t::index
Index of the window this information is about.
Definition at line 81 of file WindowChannelMap.h.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::WindowTopologyAlg::createWindowsFromCryostat(), icarus::trigger::WindowChannelMap::WindowInfo_t::dump(), icarus::trigger::WindowTopologyVerification::verifyGate(), and icarus::trigger::SlidingWindowPatternAlg::verifyInputTopology().
opposite
WindowIndex_t icarus::trigger::WindowChannelMap::WindowTopology_t::opposite { InvalidWindowIndex }
Index of the window opposite to this one.
Definition at line 84 of file WindowChannelMap.h.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::WindowChannelMap::WindowInfo_t::dump(), and hasOppositeWindow().
upstream
WindowIndex_t icarus::trigger::WindowChannelMap::WindowTopology_t::upstream { InvalidWindowIndex }
Index of the window upstream of this one.
Definition at line 87 of file WindowChannelMap.h.
Referenced by icarus::trigger::SlidingWindowPatternAlg::applyWindowPattern(), icarus::trigger::WindowChannelMap::WindowInfo_t::dump(), and hasUpstreamWindow().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.h