CAF format: icarus::trigger::SlidingWindowCombinerAlg Class Reference
icarus::trigger::SlidingWindowCombinerAlg Class Reference
Public Types
using WindowChannels_t = icarus::trigger::TriggerWindowChannels_t
Type of optical detector channel list in a window.
using Windows_t = icarus::trigger::TriggerWindowDefs_t
Type of content of all windows.
using TrackedTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Trigger gate data type (tracks sources via sbn::OpDetWaveformMeta).
Public Member Functions
SlidingWindowCombinerAlg (Windows_t const &windows, std::vector< raw::Channel_t > missingChannels={}, bool requireFullCoverage=true, std::string logCategory="SlidingWindowCombinerAlg")
Constructor: learns about the window pattern (keeps a reference).
std::vector< TrackedTriggerGate_t > combine (std::vector< TrackedTriggerGate_t > const &gates) const
Combines the gates according to the configured grouping.
bool isMissingChannel (raw::Channel_t channel) const
Returns if channel is configured to be missing.
Private Types
using TriggerGateIndex_t = icarus::trigger::TriggerGateIndex<TrackedTriggerGate_t>
Private Member Functions
void checkInput (TriggerGateIndex_t const &gates) const
Throws an exception if the gates are not suitable for input.
TrackedTriggerGate_t combineChannels (TriggerGateIndex_t const &gates, WindowChannels_t const &channels) const
Returns the combination of the channels selected from the gates.
WindowChannels_t::const_iterator firstChannelPresent (WindowChannels_t const &channels) const
Returns an iterator to the first of the channels which is not missing.
Static Private Member Functions
static bool mergeGateInto (TrackedTriggerGate_t &dest, TrackedTriggerGate_t const &input)
static Windows_t sortedWindowChannels (Windows_t const &windows)
Returns windows with numerically sorted channel numbers.
static std::vector< raw::Channel_t > sortChannels (std::vector< raw::Channel_t > channels)
Returns a sorted copy of channels.
template<typename Cont , typename T >
static bool inList (Cont const &c, T const &value)
Returns whether the container c has value.
Private Attributes
Windows_t const fWindowChannels
Content of channels of each window.
std::vector< raw::Channel_t > fMissingChannels
Channels known (and required) to be missing (sorted).
bool const fRequireFullCoverage
Whether to require all channels to be used.
std::string fLogCategory
Category for messages to MessageFacility.
Detailed Description
Definition at line 43 of file SlidingWindowCombinerAlg.h.
Member Typedef Documentation
TrackedTriggerGate_t
using icarus::trigger::SlidingWindowCombinerAlg::TrackedTriggerGate_t = icarus::trigger::TrackedOpticalTriggerGate<sbn::OpDetWaveformMeta>
Trigger gate data type (tracks sources via sbn::OpDetWaveformMeta).
Definition at line 53 of file SlidingWindowCombinerAlg.h.
TriggerGateIndex_t
using icarus::trigger::SlidingWindowCombinerAlg::TriggerGateIndex_t = icarus::trigger::TriggerGateIndex<TrackedTriggerGate_t> private
Definition at line 73 of file SlidingWindowCombinerAlg.h.
WindowChannels_t
using icarus::trigger::SlidingWindowCombinerAlg::WindowChannels_t = icarus::trigger::TriggerWindowChannels_t
Type of optical detector channel list in a window.
Definition at line 47 of file SlidingWindowCombinerAlg.h.
Windows_t
using icarus::trigger::SlidingWindowCombinerAlg::Windows_t = icarus::trigger::TriggerWindowDefs_t
Type of content of all windows.
Definition at line 50 of file SlidingWindowCombinerAlg.h.
Constructor & Destructor Documentation
SlidingWindowCombinerAlg()
icarus::trigger::SlidingWindowCombinerAlg::SlidingWindowCombinerAlg (Windows_t const & windows, std::vector< raw::Channel_t > missingChannels = {}, bool requireFullCoverage = true, std::string logCategory = "SlidingWindowCombinerAlg")
Constructor: learns about the window pattern (keeps a reference).
Definition at line 19 of file SlidingWindowCombinerAlg.cxx.
Member Function Documentation
checkInput()
void icarus::trigger::SlidingWindowCombinerAlg::checkInput (TriggerGateIndex_t const & gates) const private
Throws an exception if the gates are not suitable for input.
Definition at line 55 of file SlidingWindowCombinerAlg.cxx.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::channels(), icarus::trigger::TriggerGateIndex< GateObject >::find(), and icarus::trigger::TriggerGateIndex< GateObject >::nChannels().
combine()
auto icarus::trigger::SlidingWindowCombinerAlg::combine (std::vector< TrackedTriggerGate_t > const & gates) const
Combines the gates according to the configured grouping.
Definition at line 33 of file SlidingWindowCombinerAlg.cxx.
combineChannels()
auto icarus::trigger::SlidingWindowCombinerAlg::combineChannels (TriggerGateIndex_t const & gates, WindowChannels_t const & channels) const private
Returns the combination of the channels selected from the gates.
Definition at line 164 of file SlidingWindowCombinerAlg.cxx.
firstChannelPresent()
auto icarus::trigger::SlidingWindowCombinerAlg::firstChannelPresent (WindowChannels_t const & channels) const private
Returns an iterator to the first of the channels which is not missing.
Definition at line 197 of file SlidingWindowCombinerAlg.cxx.
inList()
template<typename Cont , typename T > static bool icarus::trigger::SlidingWindowCombinerAlg::inList (Cont const & c, T const & value) inline static private
Returns whether the container c has value.
Definition at line 112 of file SlidingWindowCombinerAlg.h.
isMissingChannel()
bool icarus::trigger::SlidingWindowCombinerAlg::isMissingChannel (raw::Channel_t channel) const inline
Returns if channel is configured to be missing.
Definition at line 124 of file SlidingWindowCombinerAlg.h.
References fMissingChannels.
mergeGateInto()
bool icarus::trigger::SlidingWindowCombinerAlg::mergeGateInto (TrackedTriggerGate_t & dest, TrackedTriggerGate_t const & input) static private
Adds the gate data of input to dest, unless it's already included.
Returns
whether the addition happened
Definition at line 208 of file SlidingWindowCombinerAlg.cxx.
References icarus::trigger::TrackedTriggerGate< Gate, TrackedType >::gate(), and icarus::trigger::sumGates().
sortChannels()
auto icarus::trigger::SlidingWindowCombinerAlg::sortChannels (std::vector< raw::Channel_t > channels) static private
Returns a sorted copy of channels.
Definition at line 234 of file SlidingWindowCombinerAlg.cxx.
sortedWindowChannels()
auto icarus::trigger::SlidingWindowCombinerAlg::sortedWindowChannels (Windows_t const & windows) static private
Returns windows with numerically sorted channel numbers.
Definition at line 224 of file SlidingWindowCombinerAlg.cxx.
Member Data Documentation
fLogCategory
std::string icarus::trigger::SlidingWindowCombinerAlg::fLogCategory private
Category for messages to MessageFacility.
Definition at line 84 of file SlidingWindowCombinerAlg.h.
fMissingChannels
std::vector<raw::Channel_t> icarus::trigger::SlidingWindowCombinerAlg::fMissingChannels private
Channels known (and required) to be missing (sorted).
Definition at line 79 of file SlidingWindowCombinerAlg.h.
Referenced by isMissingChannel().
fRequireFullCoverage
bool const icarus::trigger::SlidingWindowCombinerAlg::fRequireFullCoverage private
Whether to require all channels to be used.
Definition at line 82 of file SlidingWindowCombinerAlg.h.
fWindowChannels
Windows_t const icarus::trigger::SlidingWindowCombinerAlg::fWindowChannels private
Content of channels of each window.
Definition at line 76 of file SlidingWindowCombinerAlg.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/SlidingWindowCombinerAlg.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/SlidingWindowCombinerAlg.cxx