CAF format: util::LocalArtHandleTrackerManager< Event > Class Template Reference
util::LocalArtHandleTrackerManager< Event > Class Template Reference
Variant of util::ArtHandleTrackerManager in local scope.
#include <ArtHandleTrackerManager.h>
Public Types
using Event_t = typename ArtHandleTrackerManager<Event>::Event_t
Type of the art event.
Public Member Functions
LocalArtHandleTrackerManager (Event const &event, bool removeCache=true)
Constructor: operates on the specified event.
~LocalArtHandleTrackerManager ()
Destructor; will implement the RAII pattern (i.e. call doneWithEvent()).
template<typename Handle >
auto registerHandle (Handle &&handle) -> decltype(auto)
Queries
unsigned int nTrackedHandles () const
Returns the number of handles currently tracked.
bool willRemoveCachedProducts () const
Registration of data products
template<typename T , typename... Args>
art::Handle< T > getHandle (Args &&... args)
Retrieves an handle from the event, and registers it.
template<typename T , typename... Args>
art::ValidHandle< T > getValidHandle (Args &&... args)
Retrieves a valid handle from the event, and registers it.
template<typename Handle >
decltype(auto) registerHandle (Handle &&handle)
Registers an existing handle.
Operations
void setRemoveCachedProducts (bool removeCache)
Sets whether to remove tracked data caches on destruction or not.
unsigned int removeCachedProducts ()
Clears the cached data products for all tracked handles.
void forgetAllHandles ()
Stops tracking any handle, without removing their cache first.
unsigned int doneWithEvent (bool removeCache)
Completes the work on the associated event.
unsigned int doneWithEvent ()
Completes the work on the associated event.
Private Attributes
ArtHandleTrackerManager< Event > fManager
The actual manager doing the work.
bool fRemoveCache
Whether to remove cache on destructor.
Detailed Description
template<typename Event>
class util::LocalArtHandleTrackerManager< Event >
Variant of util::ArtHandleTrackerManager in local scope.
Template Parameters
Event the type of data product source (the "principal") to serve
This class allows the removal of data products cached in an event. The general functionality is described in util::ArtHandleTrackerManager.
This class in particular offers a tuned interface for the case where the object is local (which is convenient for multithreading and if all the reading and usage happens in the same scope):
the object supports being associated to only one event in its lifetime, and the association must be established on construction;
removal is automatically performed on destruction at the exit of the scope of the object (this is "Resource Acquisition Is Initialization" idiom)
Whether the object will actually remove the caches can be decided on construction (by default it does), and then changed with setRemoveCachedProducts(). The removal can also be anticipated by explicitly calling doneWithEvent() (no event parameter is supported), after which the destruction will not do anything.
Example:
void MyModule::analyze(art::Event const & event) override {
  util::LocalArtHandleTrackerManager dataCacheRemover{ event };
  auto const& handle = dataCacheRemover.getHandle<MyDataProduct>(fTag);
  auto results = processData(*handle); // ... or whatever
  results.Write(); // ... or another portion of whatever
}
Definition at line 419 of file ArtHandleTrackerManager.h.
Member Typedef Documentation
Event_t
template<typename Event > using util::LocalArtHandleTrackerManager< Event >::Event_t = typename ArtHandleTrackerManager<Event>::Event_t
Type of the art event.
Definition at line 429 of file ArtHandleTrackerManager.h.
Constructor & Destructor Documentation
LocalArtHandleTrackerManager()
template<typename Event > util::LocalArtHandleTrackerManager< Event >::LocalArtHandleTrackerManager (Event const & event, bool removeCache = true)
Constructor: operates on the specified event.
Parameters
event the event this object will operate on
removeCache (default: true) remove tracked data caches when done
The parameter removeCache controls whether the data caches are removed on destruction. It may be changed along the way with setRemoveCachedProducts().
Definition at line 1009 of file ArtHandleTrackerManager.h.
~LocalArtHandleTrackerManager()
template<typename Event > util::LocalArtHandleTrackerManager< Event >::~LocalArtHandleTrackerManager< Event > ()
Destructor; will implement the RAII pattern (i.e. call doneWithEvent()).
Definition at line 1009 of file ArtHandleTrackerManager.h.
Member Function Documentation
doneWithEvent() [1/2]
template<typename Event > unsigned int util::LocalArtHandleTrackerManager< Event >::doneWithEvent ()
Completes the work on the associated event.
Returns
the number of cleared data product caches
See also
doneWithEvent(bool), setRemoveCachedProducts()
This is a shortcut for having optional release of cache in a single call, depending on the value of willRemoveCachedProducts():
if true, removeCachedProducts() is called and its count is returned;
if false, forgetAllHandles() is called and 0 is returned.
In addition, the object is disassociated from the event, and the object will not be available for use any more.
Definition at line 1094 of file ArtHandleTrackerManager.h.
doneWithEvent() [2/2]
template<typename Event > unsigned int util::LocalArtHandleTrackerManager< Event >::doneWithEvent (bool removeCache)
Completes the work on the associated event.
Parameters
removeCache (default: true) removes tracked data product caches
Returns
the number of cleared data product caches
See also
doneWithEvent()
This is a shortcut for having optional release of cache in a single call, depending on the value of removeCache:
if true, removeCachedProducts() is called and its count is returned;
if false, forgetAllHandles() is called and 0 is returned.
Differently from util::ArtHandleTrackerManager, the object is not disassociated from the event: new handles can be registered and the clearing settings are preserved as they are. To be really done with the event, setRemoveCachedProducts() needs to be set to false, and users should refrain from calling `removeCachedProducts().
This method ignores and overrides the value set by setRemoveCachedProducts() and the one at construction.
Definition at line 1080 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerManager< Event >::hasEvent().
forgetAllHandles()
template<typename Event > void util::LocalArtHandleTrackerManager< Event >::forgetAllHandles ()
Stops tracking any handle, without removing their cache first.
Definition at line 1074 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerManager< Event >::forgetAllHandles().
getHandle()
template<typename Event > template<typename T , typename... Args> art::Handle< T > util::LocalArtHandleTrackerManager< Event >::getHandle (Args &&... args)
Retrieves an handle from the event, and registers it.
Template Parameters
T type of data product to retrieve
Args types of the arguments needed by art::getHandle()
Parameters
args all the arguments that art::getHandle() requires
Returns
the handle just read and being managed
See also
getValidHandle(), registerHandle()
This function wraps art::Event::getHandle(), calling it to obtain the handle and then registering it (like with registerHandle()).
Definition at line 1036 of file ArtHandleTrackerManager.h.
Referenced by daq::DaqDecoderICARUSTPCwROI::produce().
getValidHandle()
template<typename Event > template<typename T , typename... Args> art::ValidHandle< T > util::LocalArtHandleTrackerManager< Event >::getValidHandle (Args &&... args)
Retrieves a valid handle from the event, and registers it.
Template Parameters
T type of data product to retrieve
Args types of the arguments needed by art::getValidHandle()
Parameters
args all the arguments that art::getValidHandle() requires
Returns
the handle just read and being managed
See also
getHandle(), registerHandle()
This is the art::ValidHandle sibling of getHandle(). See that one for details.
Definition at line 1044 of file ArtHandleTrackerManager.h.
nTrackedHandles()
template<typename Event > unsigned int util::LocalArtHandleTrackerManager< Event >::nTrackedHandles () const
Returns the number of handles currently tracked.
Definition at line 1023 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerManager< Event >::nTrackedHandles().
registerHandle() [1/2]
template<typename Event > template<typename Handle > decltype(auto) util::LocalArtHandleTrackerManager< Event >::registerHandle (Handle && handle)
Registers an existing handle.
Template Parameters
Handle the type of handle to register
Parameters
handle the handle to be registered
Returns
the same handle is passed through
This method registers a copy of handle into the manager.
registerHandle() [2/2]
template<typename Event > template<typename Handle > auto util::LocalArtHandleTrackerManager< Event >::registerHandle (Handle && handle) -> decltype(auto)
Definition at line 1052 of file ArtHandleTrackerManager.h.
removeCachedProducts()
template<typename Event > unsigned int util::LocalArtHandleTrackerManager< Event >::removeCachedProducts ()
Clears the cached data products for all tracked handles.
Returns
the number of tracked handles which had their cache removed
This method calls Event_t::removeCachedProduct() for all tracked handles. This is the core functionality of the manager, which removes the cache of all tracked handles.
The art framework always makes the handles used to remove the cache invalid (Handle::clear()). After the removal, the object stops tracking the handles (like with a call to forgetAllHandles()).
Calling this method when there are no handles registered has no effect.
Definition at line 1068 of file ArtHandleTrackerManager.h.
References util::ArtHandleTrackerManager< Event >::removeCachedProducts().
setRemoveCachedProducts()
template<typename Event > void util::LocalArtHandleTrackerManager< Event >::setRemoveCachedProducts (bool removeCache)
Sets whether to remove tracked data caches on destruction or not.
Parameters
removeCache if true, data caches will be removed on destruction
Definition at line 1061 of file ArtHandleTrackerManager.h.
willRemoveCachedProducts()
template<typename Event > bool util::LocalArtHandleTrackerManager< Event >::willRemoveCachedProducts () const
Returns whether caches will be removed on destruction.
See also
setRemoveCachedProducts()
Definition at line 1029 of file ArtHandleTrackerManager.h.
Member Data Documentation
fManager
template<typename Event > ArtHandleTrackerManager<Event> util::LocalArtHandleTrackerManager< Event >::fManager private
The actual manager doing the work.
Definition at line 422 of file ArtHandleTrackerManager.h.
fRemoveCache
template<typename Event > bool util::LocalArtHandleTrackerManager< Event >::fRemoveCache private
Whether to remove cache on destructor.
Definition at line 424 of file ArtHandleTrackerManager.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h