CAF format: sbnobj/sbnobj/ICARUS/PMT/Trigger/Data/SingleChannelOpticalTriggerGate.h File Reference
SingleChannelOpticalTriggerGate.h File Reference
Logical multi-level gate associated to a optical detector channel.
#include "sbnobj/ICARUS/PMT/Trigger/Data/OpticalTriggerGate.h"
#include "lardataobj/RawData/OpDetWaveform.h"
#include <iosfwd>
Classes
class icarus::trigger::SingleChannelOpticalTriggerGate
Logical multi-level gate associated to a optical detector channel.
Namespaces
namespace icarus
Cluster finding and building.
namespace icarus::trigger
Trigger simulation for ICARUS.
Functions
constexpr bool raw::isValidChannel (Channel_t channel)
Returns whether the specified one is a valid channel number.
Variables
constexpr Channel_t raw::InvalidChannel = std::numeric_limits<Channel_t>::max()
Mnemonics for an invalid channel number.
Detailed Description
Logical multi-level gate associated to a optical detector channel.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Date
April 1, 2019
See also
sbnobj/ICARUS/PMT/Trigger/Data/SingleChannelOpticalTriggerGate.cxx
Definition in file SingleChannelOpticalTriggerGate.h.
Function Documentation
isValidChannel()
bool raw::isValidChannel (Channel_t channel) constexpr
Returns whether the specified one is a valid channel number.
Definition at line 32 of file SingleChannelOpticalTriggerGate.h.
References raw::InvalidChannel, and raw::isValidChannel().
Referenced by raw::isValidChannel().
Variable Documentation
InvalidChannel
Channel_t raw::InvalidChannel = std::numeric_limits<Channel_t>::max() constexpr
Mnemonics for an invalid channel number.
Definition at line 29 of file SingleChannelOpticalTriggerGate.h.
Referenced by raw::isValidChannel().