CAF format: icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h File Reference
ArtHandleTrackerManager.h File Reference
Tracks handles for cache deletion.
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Provenance.h"
#include "canvas/Utilities/InputTag.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include <algorithm>
#include <vector>
#include <memory>
#include <any>
#include <utility>
#include <typeinfo>
Classes
class util::ArtHandleTrackerManager< Event >
Manages handle trackers for an easy call of removeCachedProduct().
struct util::ArtHandleTrackerManager< Event >::Config_t
Configuration record.
class util::LocalArtHandleTrackerManager< Event >
Variant of util::ArtHandleTrackerManager in local scope.
struct util::ArtHandleTrackerInterface< Event >
Interface to facilitate the use of util::ArtHandleTracker specializations.
class util::details::ProvenanceGetter< Handle, typename >
class util::details::ArtHandleTracker< Event, Handle >
Tracks art handle objects.
Functions
template<typename Handle >
std::string util::details::productClassOf (Handle const &handle)
use candy
template<typename Handle >
std::type_info const * util::details::productTypeOf (Handle const &handle)
template<typename Handle >
art::InputTag util::details::inputTagOf (Handle const &handle)
Detailed Description
Tracks handles for cache deletion.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Date
July 31, 2022
This is a header-only library.
Definition in file ArtHandleTrackerManager.h.
Class Documentation
util::ArtHandleTrackerManager::Config_t
struct util::ArtHandleTrackerManager::Config_t
template<typename Event>
struct util::ArtHandleTrackerManager< Event >::Config_t
Configuration record.
Definition at line 166 of file ArtHandleTrackerManager.h.
Class Members
string logCategory = "ArtHandleTrackerManager" Name of the output category for messages.
Function Documentation
inputTagOf()
template<typename Handle > art::InputTag util::details::inputTagOf (Handle const & handle)
Definition at line 708 of file ArtHandleTrackerManager.h.
productClassOf()
template<typename Handle > std::string util::details::productClassOf (Handle const & handle)
use candy
Definition at line 700 of file ArtHandleTrackerManager.h.
References util::details::productClassOf().
Referenced by util::details::ArtHandleTracker< Event, Handle >::doProductClass(), and util::details::productClassOf().