CAF format: icarus::trigger::SlidingWindowTriggerSimulation Class Reference
icarus::trigger::SlidingWindowTriggerSimulation Class Reference
Simulates a sliding window trigger.
Classes
struct Config
struct ThresholdPlotInfo_t
All information needed to generate plots for a specific threshold.
Public Types
using microseconds = util::quantities::intervals::microseconds
using nanoseconds = util::quantities::intervals::nanoseconds
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
SlidingWindowTriggerSimulation (Parameters const &config)
virtual void beginJob () override
Initializes the plots.
virtual void produce (art::Event &event) override
Runs the simulation and saves the results into the art event.
virtual void endJob () override
Prints end-of-job summaries.
Private Types
using TriggerInfo_t = details::TriggerInfo_t
Type alias.
using InputTriggerGate_t = icarus::trigger::SlidingWindowPatternAlg::InputTriggerGate_t
Type of trigger gate extracted from the input event.
using TriggerGates_t = icarus::trigger::SlidingWindowPatternAlg::TriggerGates_t
List of trigger gates.
using WindowTriggerInfo_t = icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t
Data structure to communicate internally a trigger response.
using BinnedContent_t = icarus::ns::util::FixedBins<double>
Content for future histograms, binned.
using PlotSandbox_t = icarus::ns::util::PlotSandbox<art::TFileDirectory>
Import type.
Private Member Functions
void initializePlots ()
Initializes the full set of plots (all ADC thresholds).
void finalizePlots ()
Creates summary plots from proto-histogram data.
void makeThresholdPlots (std::string const &threshold, PlotSandbox_t &plots, ThresholdPlotInfo_t const &plotInfo)
void makeEventPlots ()
Creates in the main sandbox all event-wide plots.
void plotEvent (art::Event const &event, detinfo::DetectorTimings const &detTimings)
Fills event-wide plots.
void plotTriggerResponse (std::size_t iThr, std::string const &thrTag, WindowTriggerInfo_t const &triggerInfo, detinfo::DetectorTimings const &detTimings)
Fills the plots for threshold index iThr with trigger information.
WindowTriggerInfo_t produceForThreshold (art::Event &event, detinfo::DetectorTimings const &detTimings, ApplyBeamGateClass const &beamGate, std::size_t const iThr, std::string const &thrTag)
Performs the simulation for the specified ADC threshold.
raw::Trigger triggerInfoToTriggerData (detinfo::DetectorTimings const &detTimings, unsigned int triggerNumber, WindowTriggerInfo_t const &info) const
Converts the trigger information into a raw::Trigger object.
void printSummary () const
Prints the summary of fired triggers on screen.
TH1 * makeHistogramFromBinnedContent (PlotSandbox_t &plots, std::string const &name, std::string const &title, BinnedContent_t const &binnedContent) const
Creates and returns a 1D histogram filled with binnedContent.
icarus::trigger::ApplyBeamGateClass makeMyBeamGate (detinfo::DetectorClocksData data) const
Shortcut to create an ApplyBeamGate with the current configuration.
icarus::trigger::ApplyBeamGateClass makeMyBeamGate (art::Event const *event=nullptr) const
icarus::trigger::ApplyBeamGateClass makeMyBeamGate (art::Event const &event) const
Static Private Member Functions
static TriggerGates_t readTriggerGates (art::Event const &event, art::InputTag const &dataTag)
static double eventTimestampInSeconds (art::Timestamp const &time)
Returns the time of the event in seconds from The Epoch.
static double eventTimestampInSeconds (art::Event const &event)
Private Attributes
std::map< std::string, art::InputTag > fADCthresholds
Name of ADC thresholds to read, and the input tag connected to their data.
WindowPattern const fPattern
Configured sliding window requirement pattern.
microseconds fBeamGateDuration
Duration of the gate during with global optical triggers are accepted.
microseconds fBeamGateStart
Start of the beam gate with respect to BeamGate().
std::uint32_t fBeamBits
Bits for the beam gate being simulated.
nanoseconds fTriggerTimeResolution
Trigger resolution in time.
double fEventTimeBinning
Trigger time plot binning [s].
std::string const fLogCategory
Message facility stream category for output.
art::TFileDirectory fOutputDir
ROOT directory where all the plots are written.
std::vector< std::string > fOutputInstances
Output data product instance names (same order as fADCthresholds).
icarus::trigger::WindowTopologyManager fWindowMapMan
Mapping of each sliding window with location and topological information.
std::optional< icarus::trigger::SlidingWindowPatternAlg > fPatternAlg
Pattern algorithm.
PlotSandbox_t fPlots
All plots in one practical sandbox.
ThresholdPlotInfo_t fEventPlotInfo
Proto-histogram information in a convenient packet; event-wide.
std::vector< ThresholdPlotInfo_t > fThresholdPlots
Proto-histogram information in a not-so-practical array; per threshold.
std::vector< std::atomic< unsigned int > > fTriggerCount
std::atomic< unsigned int > fTotalEvents { 0U }
Count of opened gates.
icarus::ns::util::ThreadSafeChangeMonitor< icarus::trigger::ApplyBeamGateClass > fGateChangeCheck
Functor returning whether a gate has changed.
Detailed Description
Simulates a sliding window trigger.
This module produces raw::Trigger objects each representing the outcome of some trigger logic applied to a discriminated input ("trigger primitives").
A trigger primitive is a two-level function of time which describes when that primitive is on and when it is off. Trigger primitives are given as input to this module and their origin may vary, but the standard source in ICARUS is single trigger request (LVDS).
This module applies a sliding window pattern to the input: the pattern consists of a requirement on the main window and optional additional requirements on the neighbouring windows. This module rebases the configured pattern on each of the available windows, evaluates the requirement of the pattern in that configuration, and decides whether those requirements are met. The general trigger is considered passed if any of the rebased patterns satisfies the requirement at any time, and no special treatment is performed in case multiple windows fulfil them, except that the trigger time is driven by the earliest of the satisfied patterns.
A single trigger pattern is configured for each instance of the module, while multiple input sets (e.g. with different discrimination thresholds) can be processed on the same pattern by the same module instance. Conversely, testing a different pattern requires the instantiation of a new module.
Configuration
TriggerGatesTag (string, mandatory): name of the module instance which produced the trigger primitives to be used as input; it must not include any instance name, as the instance names will be automatically added from Thresholds parameter. The typical trigger primitives used as input are LVDS discriminated output combined into trigger windows (e.g. from icarus::trigger::SlidingWindowTrigger module).
Thresholds (list of names, mandatory): list of the discrimination thresholds to consider. A data product containing a digital signal is read for each one of the thresholds, and the tag of the data product is expected to be the instance name in this configuration parameter for the module label set in TriggerGatesTag (e.g. for a threshold of "60", supposedly 60 ADC counts, and with TriggerGatesTag set to "TrigSlidingWindows", the data product tag would be TrigSlidingWindows:60).
KeepThresholdName (flag, optional): by default, output data products have each an instance name according to their threshold (from the Threshold parameter), unless there is only one threshold specified. If this parameter is specified as true, the output data product always includes the threshold instance name, even when there is only one threshold specified. If this parameter is specified as false, if there is only one threshold the default behaviour (of not adding an instance name) is confirmed; otherwise, it is a configuration error to have this parameter set to false.
Pattern (configuration table, mandatory): describes the sliding window pattern; the configuration format for a pattern is described under icarus::trigger::ns::fhicl::WindowPatternConfig.
BeamGateDuration (time, mandatory): the duration of the beam gate; the time requires the unit to be explicitly specified: use "1.6 us" for BNB, 9.5 us for NuMI (also available as BNB_settings.spill_duration and NuMI_settings.spill_duration in trigger_icarus.fcl);
BeamGateStart (time, default: 0_us): how long after the
nominal beam gate opening time the actual beam gate opens at;
BeamBits (bitmask as 32-bit integral number): bits to be set in the produced raw::Trigger objects (see also daq::TriggerDecoder tool).
LogCategory (string, default SlidingWindowTriggerSimulation): name of category used to stream messages from this module into message facility.
An example job configuration is provided as simulate_sliding_window_trigger_icarus.fcl.
Output data products
std::vector<raw::Trigger> (one instance per ADC threshold): list of triggers fired according to the configured trigger definition; there is one collection (and data product) per ADC threshold, and the data product has the same instance name as the input data one, unless there is only one threshold (see TriggerGatesTag, Thresholds and KeepThresholdName configuration parameters); currently only at most one trigger is emitted, with time stamp matching the first time the trigger criteria are satisfied. All triggers feature the bits specified in BeamBits configuration parameter.
Trigger logic algorithm
This section describes the trigger logic algorithm used in icarus::trigger::SlidingWindowTriggerSimulation and its assumptions. Nevertheless, more up-to-date information can be found in SlidingWindowTrigger module (for the combination of the LVDS signals into window-wide gates) and in icarus::trigger::SlidingWindowPatternAlg, which applies the configured pattern logic to the input.
The module receives as input a multi-level trigger gate for each of the windows to be considered. On the first input (i.e. the first event), that input is parsed to learn the windows and their relative position from the input trigger gates. This topology will be used to apply the configured patterns. On the following events, their input is checked to confirm the compatibility of the composition of its windows with the one from that first event (both aspects are handled by an icarus::trigger::WindowTopologyManager object).
All multi-level gates are set in coincidence with the beam gate by multiplying the multi-level and the beam gates. Because of this, trigger gates are suppressed everywhere except than during the beam gate. The beam gate opens at a time configured in DetectorClocks service provider (detinfo::DetectorClocks::BeamGateTime()), optionally offset (BeamGateStart), and has a duration configured in this module (BeamGateDuration).
The algorithm handles independently multiple trigger patterns. On each input, each configured pattern is applied based on the window topology. Each pattern describes a minimum level of the trigger gate in the window, that usually means the number of LVDS signals in coincidence at any given time ("majority"). A pattern may have requirements on the neighbouring windows in addition to the main one. The pattern is satisfied if all involved windows pass their specific requirements at the same time (coincidence between windows). Each pattern is applied in turn to each of the windows (which is the "main" window). The neighborhood described in the pattern is applied with respect to that main window. The trigger fires if one or more of the windows satisfy the pattern, and the trigger time is the one of the earliest satisfied pattern (more precisely, the earliest tick when the coincidence required by that pattern is satisfied).* All windows in the detector are considered independently, but the supported patterns may only include components in the same cryostat. Therefore, triggers are effectively on a single cryostat. An object of class icarus::trigger::SlidingWindowPatternAlg applies this logic: see its documentation for the most up-to-date details.
Eventually, for each event there are as many different trigger responses as how many different patterns are configured (Patterns configuration parameter), times how many ADC thresholds are provided in input, configured in Thresholds.
Technical aspects of the module
This module does not build the trigger gates of the sliding windows, but rather it takes them as input (see e.g. SlidingWindowTrigger module). Window topology (size of the windows and their relations) is stored in icarus::trigger::WindowChannelMap objects, and its construction is delegated to icarus::trigger::WindowTopologyAlg (under the hood of the WindowTopologyManager class) which learns it from the actual trigger gate input rather than on explicit configuration. Pattern definitions and configuration are defined in icarus::trigger::WindowPattern and icarus::trigger::ns::fhicl::WindowPatternConfig respectively. Trigger simulation is delegated to icarus::trigger::SlidingWindowPatternAlg.
Discontinuation note
Note
This module is not being developed any more. New features are currently being added to icarus::trigger::TriggerSimulationOnGates module only. The main things that are lost with the deprecation of this module are some plots and more in general the design oriented to a single beam gate. This allowed for assumptions that in turn could result into a rational choice of plots and (a bit more) rational treatment of non-triggering events. Nevertheless, adding features to both modules is becoming vexing, so the author has opted to stick to the most versatile among the two.
Definition at line 270 of file SlidingWindowTriggerSimulation_module.cc.
Class Documentation
icarus::trigger::SlidingWindowTriggerSimulation::Config
struct icarus::trigger::SlidingWindowTriggerSimulation::Config
Definition at line 282 of file SlidingWindowTriggerSimulation_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< uint32_t > BeamBits
Atom< microseconds > BeamGateDuration
Atom< microseconds > BeamGateStart
Atom< double > EventTimeBinning
OptionalAtom< bool > KeepThresholdName
Atom< string > LogCategory
WindowPatternTable Pattern
Sequence< string > Thresholds
Atom< string > TriggerGatesTag
Atom< nanoseconds > TriggerTimeResolution
icarus::trigger::SlidingWindowTriggerSimulation::ThresholdPlotInfo_t
struct icarus::trigger::SlidingWindowTriggerSimulation::ThresholdPlotInfo_t
All information needed to generate plots for a specific threshold.
Definition at line 385 of file SlidingWindowTriggerSimulation_module.cc.
Class Members
BinnedContent_t eventTimes
BinnedContent_t HWtrigTimeVsBeam
BinnedContent_t triggerTimesVsBeam
BinnedContent_t triggerTimesVsHWtrig
Member Typedef Documentation
BinnedContent_t
using icarus::trigger::SlidingWindowTriggerSimulation::BinnedContent_t = icarus::ns::util::FixedBins<double> private
Content for future histograms, binned.
Definition at line 382 of file SlidingWindowTriggerSimulation_module.cc.
InputTriggerGate_t
using icarus::trigger::SlidingWindowTriggerSimulation::InputTriggerGate_t = icarus::trigger::SlidingWindowPatternAlg::InputTriggerGate_t private
Type of trigger gate extracted from the input event.
Definition at line 373 of file SlidingWindowTriggerSimulation_module.cc.
microseconds
using icarus::trigger::SlidingWindowTriggerSimulation::microseconds = util::quantities::intervals::microseconds
Definition at line 277 of file SlidingWindowTriggerSimulation_module.cc.
nanoseconds
using icarus::trigger::SlidingWindowTriggerSimulation::nanoseconds = util::quantities::intervals::nanoseconds
Definition at line 278 of file SlidingWindowTriggerSimulation_module.cc.
Parameters
using icarus::trigger::SlidingWindowTriggerSimulation::Parameters = art::EDProducer::Table<Config>
Definition at line 344 of file SlidingWindowTriggerSimulation_module.cc.
PlotSandbox_t
using icarus::trigger::SlidingWindowTriggerSimulation::PlotSandbox_t = icarus::ns::util::PlotSandbox<art::TFileDirectory> private
Import type.
Definition at line 393 of file SlidingWindowTriggerSimulation_module.cc.
TriggerGates_t
using icarus::trigger::SlidingWindowTriggerSimulation::TriggerGates_t = icarus::trigger::SlidingWindowPatternAlg::TriggerGates_t private
List of trigger gates.
Definition at line 376 of file SlidingWindowTriggerSimulation_module.cc.
TriggerInfo_t
using icarus::trigger::SlidingWindowTriggerSimulation::TriggerInfo_t = details::TriggerInfo_t private
Type alias.
Definition at line 370 of file SlidingWindowTriggerSimulation_module.cc.
WindowTriggerInfo_t
using icarus::trigger::SlidingWindowTriggerSimulation::WindowTriggerInfo_t = icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t private
Data structure to communicate internally a trigger response.
Definition at line 379 of file SlidingWindowTriggerSimulation_module.cc.
Constructor & Destructor Documentation
SlidingWindowTriggerSimulation()
icarus::trigger::SlidingWindowTriggerSimulation::SlidingWindowTriggerSimulation (Parameters const & config) explicit
Definition at line 583 of file SlidingWindowTriggerSimulation_module.cc.
Member Function Documentation
beginJob()
void icarus::trigger::SlidingWindowTriggerSimulation::beginJob () override virtual
Initializes the plots.
Definition at line 676 of file SlidingWindowTriggerSimulation_module.cc.
endJob()
void icarus::trigger::SlidingWindowTriggerSimulation::endJob () override virtual
Prints end-of-job summaries.
Definition at line 722 of file SlidingWindowTriggerSimulation_module.cc.
eventTimestampInSeconds() [1/2]
double icarus::trigger::SlidingWindowTriggerSimulation::eventTimestampInSeconds (art::Event const & event) static private
Definition at line 1199 of file SlidingWindowTriggerSimulation_module.cc.
eventTimestampInSeconds() [2/2]
double icarus::trigger::SlidingWindowTriggerSimulation::eventTimestampInSeconds (art::Timestamp const & time) static private
Returns the time of the event in seconds from The Epoch.
Definition at line 1188 of file SlidingWindowTriggerSimulation_module.cc.
finalizePlots()
void icarus::trigger::SlidingWindowTriggerSimulation::finalizePlots () private
Creates summary plots from proto-histogram data.
Definition at line 875 of file SlidingWindowTriggerSimulation_module.cc.
initializePlots()
void icarus::trigger::SlidingWindowTriggerSimulation::initializePlots () private
Initializes the full set of plots (all ADC thresholds).
Definition at line 732 of file SlidingWindowTriggerSimulation_module.cc.
makeEventPlots()
void icarus::trigger::SlidingWindowTriggerSimulation::makeEventPlots () private
Creates in the main sandbox all event-wide plots.
Definition at line 944 of file SlidingWindowTriggerSimulation_module.cc.
makeHistogramFromBinnedContent()
TH1 * icarus::trigger::SlidingWindowTriggerSimulation::makeHistogramFromBinnedContent (PlotSandbox_t & plots, std::string const & name, std::string const & title, BinnedContent_t const & binnedContent) const private
Creates and returns a 1D histogram filled with binnedContent.
Definition at line 1163 of file SlidingWindowTriggerSimulation_module.cc.
makeMyBeamGate() [1/3]
icarus::trigger::ApplyBeamGateClass icarus::trigger::SlidingWindowTriggerSimulation::makeMyBeamGate (art::Event const & event) const inline private
Definition at line 557 of file SlidingWindowTriggerSimulation_module.cc.
makeMyBeamGate() [2/3]
icarus::trigger::ApplyBeamGateClass icarus::trigger::SlidingWindowTriggerSimulation::makeMyBeamGate (art::Event const * event = nullptr) const inline private
Definition at line 554 of file SlidingWindowTriggerSimulation_module.cc.
makeMyBeamGate() [3/3]
icarus::trigger::ApplyBeamGateClass icarus::trigger::SlidingWindowTriggerSimulation::makeMyBeamGate (detinfo::DetectorClocksData data) const inline private
Shortcut to create an ApplyBeamGate with the current configuration.
Definition at line 545 of file SlidingWindowTriggerSimulation_module.cc.
References fBeamGateDuration, fBeamGateStart, fLogCategory, and icarus::trigger::makeApplyBeamGate().
makeThresholdPlots()
void icarus::trigger::SlidingWindowTriggerSimulation::makeThresholdPlots (std::string const & threshold, PlotSandbox_t & plots, ThresholdPlotInfo_t const & plotInfo) private
Creates in plots sandbox all plots for threshold threshold from data in plotInfo.
Definition at line 891 of file SlidingWindowTriggerSimulation_module.cc.
plotEvent()
void icarus::trigger::SlidingWindowTriggerSimulation::plotEvent (art::Event const & event, detinfo::DetectorTimings const & detTimings) private
Fills event-wide plots.
Definition at line 1024 of file SlidingWindowTriggerSimulation_module.cc.
plotTriggerResponse()
void icarus::trigger::SlidingWindowTriggerSimulation::plotTriggerResponse (std::size_t iThr, std::string const & thrTag, WindowTriggerInfo_t const & triggerInfo, detinfo::DetectorTimings const & detTimings) private
Fills the plots for threshold index iThr with trigger information.
Definition at line 1038 of file SlidingWindowTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::atTick(), icarus::trigger::details::TriggerInfo_t::fired(), icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t::info, and icarus::trigger::WindowPattern::tag().
printSummary()
void icarus::trigger::SlidingWindowTriggerSimulation::printSummary () const private
Prints the summary of fired triggers on screen.
Definition at line 1092 of file SlidingWindowTriggerSimulation_module.cc.
References icarus::trigger::WindowPattern::description().
produce()
void icarus::trigger::SlidingWindowTriggerSimulation::produce (art::Event & event) override virtual
Runs the simulation and saves the results into the art event.
Definition at line 684 of file SlidingWindowTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::atTick(), and icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t::info.
produceForThreshold()
auto icarus::trigger::SlidingWindowTriggerSimulation::produceForThreshold (art::Event & event, detinfo::DetectorTimings const & detTimings, ApplyBeamGateClass const & beamGate, std::size_t const iThr, std::string const & thrTag) private
Performs the simulation for the specified ADC threshold.
Parameters
event art event to read data from and put results into
iThr index of the threshold in the configuration
thr value of the threshold (ADC counts)
Returns
the trigger response information
For the given threshold, the simulation of the configured trigger is performed. The input data is read from the event (the source tag is from the module configuration), simulation is performed, auxiliary plots are drawn and a raw::Trigger collection is stored into the event.
The stored collection contains either one or zero raw::Trigger elements.
The simulation itself is performed by the simulate() method.
Definition at line 972 of file SlidingWindowTriggerSimulation_module.cc.
References icarus::trigger::details::TriggerInfo_t::fired(), and icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t::info.
readTriggerGates()
auto icarus::trigger::SlidingWindowTriggerSimulation::readTriggerGates (art::Event const & event, art::InputTag const & dataTag) static private
Reads a set of input gates from the event
Returns
trigger gates, converted into InputTriggerGate_t
Definition at line 1136 of file SlidingWindowTriggerSimulation_module.cc.
References icarus::trigger::FillTriggerGates().
triggerInfoToTriggerData()
raw::Trigger icarus::trigger::SlidingWindowTriggerSimulation::triggerInfoToTriggerData (detinfo::DetectorTimings const & detTimings, unsigned int triggerNumber, WindowTriggerInfo_t const & info) const private
Converts the trigger information into a raw::Trigger object.
Parameters
triggerNumber the unique number to assign to this trigger
info the information about the fired trigger
Returns
a raw::Trigger object with all the information encoded
The trigger described by info is encoded into a raw::Trigger object. The trigger must have fired.
Definition at line 1119 of file SlidingWindowTriggerSimulation_module.cc.
Member Data Documentation
fADCthresholds
std::map<std::string, art::InputTag> icarus::trigger::SlidingWindowTriggerSimulation::fADCthresholds private
Name of ADC thresholds to read, and the input tag connected to their data.
Definition at line 398 of file SlidingWindowTriggerSimulation_module.cc.
fBeamBits
std::uint32_t icarus::trigger::SlidingWindowTriggerSimulation::fBeamBits private
Bits for the beam gate being simulated.
Definition at line 409 of file SlidingWindowTriggerSimulation_module.cc.
fBeamGateDuration
microseconds icarus::trigger::SlidingWindowTriggerSimulation::fBeamGateDuration private
Duration of the gate during with global optical triggers are accepted.
Definition at line 404 of file SlidingWindowTriggerSimulation_module.cc.
Referenced by makeMyBeamGate().
fBeamGateStart
microseconds icarus::trigger::SlidingWindowTriggerSimulation::fBeamGateStart private
Start of the beam gate with respect to BeamGate().
Definition at line 407 of file SlidingWindowTriggerSimulation_module.cc.
Referenced by makeMyBeamGate().
fEventPlotInfo
ThresholdPlotInfo_t icarus::trigger::SlidingWindowTriggerSimulation::fEventPlotInfo private
Proto-histogram information in a convenient packet; event-wide.
Definition at line 445 of file SlidingWindowTriggerSimulation_module.cc.
fEventTimeBinning
double icarus::trigger::SlidingWindowTriggerSimulation::fEventTimeBinning private
Trigger time plot binning [s].
Definition at line 413 of file SlidingWindowTriggerSimulation_module.cc.
fGateChangeCheck
icarus::ns::util::ThreadSafeChangeMonitor<icarus::trigger::ApplyBeamGateClass> icarus::trigger::SlidingWindowTriggerSimulation::fGateChangeCheck private
Functor returning whether a gate has changed.
Definition at line 457 of file SlidingWindowTriggerSimulation_module.cc.
fLogCategory
std::string const icarus::trigger::SlidingWindowTriggerSimulation::fLogCategory private
Message facility stream category for output.
Definition at line 416 of file SlidingWindowTriggerSimulation_module.cc.
Referenced by makeMyBeamGate().
fOutputDir
art::TFileDirectory icarus::trigger::SlidingWindowTriggerSimulation::fOutputDir private
ROOT directory where all the plots are written.
Definition at line 424 of file SlidingWindowTriggerSimulation_module.cc.
fOutputInstances
std::vector<std::string> icarus::trigger::SlidingWindowTriggerSimulation::fOutputInstances private
Output data product instance names (same order as fADCthresholds).
Definition at line 432 of file SlidingWindowTriggerSimulation_module.cc.
fPattern
WindowPattern const icarus::trigger::SlidingWindowTriggerSimulation::fPattern private
Configured sliding window requirement pattern.
Definition at line 401 of file SlidingWindowTriggerSimulation_module.cc.
fPatternAlg
std::optional<icarus::trigger::SlidingWindowPatternAlg> icarus::trigger::SlidingWindowTriggerSimulation::fPatternAlg private
Pattern algorithm.
Definition at line 439 of file SlidingWindowTriggerSimulation_module.cc.
fPlots
PlotSandbox_t icarus::trigger::SlidingWindowTriggerSimulation::fPlots private
All plots in one practical sandbox.
Definition at line 442 of file SlidingWindowTriggerSimulation_module.cc.
fThresholdPlots
std::vector<ThresholdPlotInfo_t> icarus::trigger::SlidingWindowTriggerSimulation::fThresholdPlots private
Proto-histogram information in a not-so-practical array; per threshold.
Count of fired triggers, per threshold.
Definition at line 448 of file SlidingWindowTriggerSimulation_module.cc.
fTotalEvents
std::atomic<unsigned int> icarus::trigger::SlidingWindowTriggerSimulation::fTotalEvents { 0U } private
Count of opened gates.
Definition at line 452 of file SlidingWindowTriggerSimulation_module.cc.
fTriggerCount
std::vector<std::atomic<unsigned int> > icarus::trigger::SlidingWindowTriggerSimulation::fTriggerCount private
Definition at line 451 of file SlidingWindowTriggerSimulation_module.cc.
fTriggerTimeResolution
nanoseconds icarus::trigger::SlidingWindowTriggerSimulation::fTriggerTimeResolution private
Trigger resolution in time.
Definition at line 411 of file SlidingWindowTriggerSimulation_module.cc.
fWindowMapMan
icarus::trigger::WindowTopologyManager icarus::trigger::SlidingWindowTriggerSimulation::fWindowMapMan mutable private
Mapping of each sliding window with location and topological information.
Definition at line 436 of file SlidingWindowTriggerSimulation_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/SlidingWindowTriggerSimulation_module.cc