CAF format: icarus::trigger::TriggerSimulationOnGates Class Reference
icarus::trigger::TriggerSimulationOnGates Class Reference
Simulates a sliding window trigger at specified gate times.
Classes
struct ApplyBeamGateClassWithBits
Utility to carry beam bits along with the beam gates.
struct Config
struct EventAux_t
Event-level information.
struct ThresholdPlotInfo_t
All information needed to generate plots for a specific threshold.
Public Types
using microseconds = util::quantities::intervals::microseconds
using nanoseconds = util::quantities::intervals::nanoseconds
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
TriggerSimulationOnGates (Parameters const &config)
virtual void beginJob () override
Initializes the plots.
virtual void produce (art::Event &event) override
Runs the simulation and saves the results into the art event.
virtual void endJob () override
Prints end-of-job summaries.
Private Types
using TriggerBits_t = decltype(std::declval<raw::Trigger>().TriggerBits())
Type of trigger bits supported by raw::Trigger.
using TriggerInfo_t = details::TriggerInfo_t
Type alias.
using WindowTriggerInfo_t = icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t
Data structure to communicate internally a trigger response.
using BinnedContent_t = icarus::ns::util::FixedBins<double>
Content for future histograms, binned.
using BeamGates_t = std::vector<sim::BeamGateInfo>
Type of list of gates to simulate trigger into.
using PlotSandbox_t = icarus::ns::util::PlotSandbox<art::TFileDirectory>
Private Member Functions
void initializePlots ()
Initializes the full set of plots (all ADC thresholds).
void finalizePlots ()
Creates summary plots from proto-histogram data.
void makeThresholdPlots (std::string const &threshold, PlotSandbox_t &plots, ThresholdPlotInfo_t const &plotInfo)
void makeEventPlots ()
Creates in the main sandbox all event-wide plots.
void plotEvent (art::Event const &event, detinfo::DetectorTimings const &detTimings, std::vector< sim::BeamGateInfo > const &gates)
Fills event-wide plots.
void plotTriggerResponse (std::size_t iThr, std::string const &thrTag, std::vector< WindowTriggerInfo_t > const &triggerInfos, detinfo::DetectorTimings const &detTimings)
Fills the plots for threshold index iThr with trigger information.
std::vector< std::vector< WindowTriggerInfo_t > > produceForThreshold (art::Event &event, detinfo::DetectorTimings const &detTimings, std::vector< sim::BeamGateInfo > const &beamGates, std::size_t const iThr, std::string const &thrTag, unsigned int firstTriggerNumber)
Performs the simulation for the specified ADC threshold.
std::pair< std::vector< raw::Trigger >, sbn::ExtraTriggerInfo > triggerInfoToTriggerData (detinfo::DetectorTimings const &detTimings, sim::BeamGateInfo const &beamGate, EventAux_t const &eventInfo, unsigned int triggerNumber, std::vector< WindowTriggerInfo_t > const &info) const
Converts the trigger information into trigger objects.
void printSummary () const
Prints the summary of fired triggers on screen.
nanoseconds toBeamGateTime (util::quantities::nanosecond time, detinfo::DetectorTimings const &detTimings) const
Converts a time into beam gate time.
TH1 * makeHistogramFromBinnedContent (PlotSandbox_t &plots, std::string const &name, std::string const &title, BinnedContent_t const &binnedContent) const
Creates and returns a 1D histogram filled with binnedContent.
Static Private Member Functions
static sbn::triggerSourceMask makeTriggerBits (sim::BeamGateInfo const &beamInfo)
Converts trigger bits from beamInfo into a sbn::triggerSourceMask.
static sbn::triggerSource beamTypeToTriggerSource (sim::BeamType_t beamType)
Converts a sim::BeamType_t value into a sbn::bits::triggerSource one.
static sbn::bits::triggerLocationMask cryoIDtoTriggerLocation (geo::CryostatID const &cid)
Converts a cryostat ID into a bitmask pointing to that cryostat.
static double eventTimestampInSeconds (art::Timestamp const &time)
Returns the time of the event in seconds from The Epoch.
static double eventTimestampInSeconds (art::Event const &event)
static EventAux_t extractEventInfo (art::Event const &event)
Fills an EventAux_t from the information found in the argument.
static std::uint64_t TimestampToUTC (art::Timestamp const &ts)
Converts a standard art timestamp into an UTC time [ns].
static geo::CryostatID WindowCryostat (icarus::trigger::WindowChannelMap::WindowInfo_t const &winfo)
Returns the ID of the cryostat the specified window belongs to.
Private Attributes
std::map< std::string, art::InputTag > fADCthresholds
Name of ADC thresholds to read, and the input tag connected to their data.
WindowPattern const fPattern
Configured sliding window requirement pattern.
art::InputTag const fBeamGateTag
Data product of beam gates to simulate.
util::TimeScale const fBeamGateReference
Reference time of beam gates.
std::optional< std::uint32_t > fBeamBits
Bits for the beam gate being simulated.
bool const fEmitEmpty
Whether to produce trigger objects for gates without triggers.
bool const fExtraInfo
Whether to produce a sbn::ExtraTriggerInfo.
nanoseconds const fDeadTime
Veto time after a trigger in a gate.
TriggerBits_t const fRetriggeringMask
Bit mask set for triggers after the first one in a gate.
TriggerBits_t const fCryostatZeroMask
Bit mask for cryostat 0.
nanoseconds const fTriggerTimeResolution
Trigger resolution in time.
double const fEventTimeBinning
Trigger time plot binning [s].
std::string const fLogCategory
Message facility stream category for output.
art::TFileDirectory fOutputDir
ROOT directory where all the plots are written.
std::vector< std::string > fOutputInstances
Output data product instance names (same order as fADCthresholds).
icarus::trigger::WindowTopologyManager fWindowMapMan
Mapping of each sliding window with location and topological information.
std::optional< icarus::trigger::SlidingWindowPatternAlg > fPatternAlg
Pattern algorithm.
PlotSandbox_t fPlots
All plots in one practical sandbox.
ThresholdPlotInfo_t fEventPlotInfo
Proto-histogram information in a convenient packet; event-wide.
std::vector< ThresholdPlotInfo_t > fThresholdPlots
Proto-histogram information in a not-so-practical array; per threshold.
std::vector< std::atomic< unsigned int > > fTriggerCount
std::atomic< unsigned int > fTotalGates { 0U }
Count of opened gates.
Static Private Attributes
static constexpr std::size_t NTriggerBits = sizeof(TriggerBits_t) * 8U
Number of bits supported by raw::Trigger.
Detailed Description
Simulates a sliding window trigger at specified gate times.
This module produces raw::Trigger objects each representing the outcome of some trigger logic applied to discriminated optical detector input ("trigger primitives"). The logic is applied to each event at multiple times, according to a list of time intervals read from each event. In addition, the module finds all the possible triggers within each gate (honouring a configurable dead time).
The main purpose of this module is to simulate the trigger logic at times of special interest, typically the times some track is believed to have crossed the detector.
This module applies the configured window pattern to the input: the pattern consists of a requirement on the main window and optional additional requirements on the neighbouring windows. This module rebases the configured pattern on each of the available windows, evaluates the requirement of the pattern in that configuration, and decides whether those requirements are met. The general trigger is considered passed if any of the rebased patterns satisfies the requirement at any time, and no special treatment is performed in case multiple windows fulfil them, except that the trigger time is driven by the earliest of the satisfied patterns.
A single trigger pattern is configured for each instance of the module, while multiple input sets (e.g. with different discrimination thresholds) can be processed on the same pattern by the same module instance. Conversely, testing a different pattern requires the instantiation of a new module.
Configuration
Run lar --print-description TriggerSimulationOnGates for a configuration example and terse explanations (it will also include the full list of available options for multiple choice parameters like BeamGateReference).
TriggerGatesTag (string, mandatory): name of the module instance which produced the trigger primitives to be used as input; it must not include any instance name, as the instance names will be automatically added from Thresholds parameter. The typical trigger primitives used as input are LVDS discriminated output combined into trigger windows (e.g. from icarus::trigger::SlidingWindowTrigger module).
Thresholds (list of names, mandatory): list of the discrimination thresholds to consider. A data product containing a digital signal is read for each one of the thresholds, and the tag of the data product is expected to be the instance name in this configuration parameter for the module label set in TriggerGatesTag (e.g. for a threshold of "60", supposedly 60 ADC counts, and with TriggerGatesTag set to "TrigSlidingWindows", the data product tag would be TrigSlidingWindows:60).
KeepThresholdName (flag, optional): by default, output data products have each an instance name according to their threshold (from the Threshold parameter), unless there is only one threshold specified. If this parameter is specified as true, the output data product always includes the threshold instance name, even when there is only one threshold specified. If this parameter is specified as false, if there is only one threshold the default behaviour (of not adding an instance name) is confirmed; otherwise, it is a configuration error to have this parameter set to false.
Pattern (configuration table, mandatory): describes the sliding window pattern; the configuration format for a pattern is described under icarus::trigger::ns::fhicl::WindowPatternConfig.
BeamGates (input tag, mandatory): the data product with the beam gates to run the simulation in;
BeamBits (bitmask as 32-bit integral number, optional): bits to be set in the produced raw::Trigger objects. If omitted, bits are created from a sbn::bits::triggerSource mask reflecting the content of the input beam gate bits, which basically can distinguish only between BNB, NuMI and others, "unknown" (see also daq::TriggerDecoder tool).
BeamGateReference (text, default: BeamGate): time reference of the input gates in the data product defined by BeamGates. By LArSoft standard, that is simulation time in Monte Carlo, which is mirrored in data by the hardware beam gate time (although the latter allows a margin around the beam spill opening a bit before neutrinos are expected).
DeadTime (time, default: forever): when looking for sequences of triggers, ignore this much time after every trigger found. This applies only within each requested gate: a trigger at the very end of a gate will not suppress one at the beginning of the next one even if that is within the set dead time. If set to a very large value (as the default), only one trigger will be found per input gate.
EmitEmpty (flag, default: true): if set, each gate gets at least a trigger object, and if there is no trigger during a gate its trigger object will be marked by having no bit set. If unset, when there is no trigger in the gate, no trigger object will be produced, but the counts will still proceed.
ExtraInfo (flag, default: false): also produces a data product sbn::ExtraTriggerInfo with reduced information from the first of the triggers from the first of the gates. If the first gate did not trigger the object will have fields marked invalid.
RetriggeringBit (positive integer, default: 17): the bit to set for all the triggers found after the first one within each gate. The value 0 represents the least significant bit; the default value is 17, bit mask 0x20000. Using a value larger than the size of the trigger bit field will disable this mark.
CryostatFirstBit (positive integer, default: disabled): the bit to set for triggers from windows in cryostat 0; as many bits will be used as there are cryostats in the detector (thus, 2 for ICARUS). The value 0 represents the least significant bit. Using a value larger than the size of the trigger bit field (which is the default) will disable this mark.
LogCategory (string, default TriggerSimulationOnGates): name of category used to stream messages from this module into message facility.
An example job configuration is provided as simulate_sliding_window_trigger_icarus.fcl.
Input data products
TriggerGatesTag + Thresholds: input gate collections.
BeamGates (std::vector<sim::BeamGateInfo>): the beam gate intervals to run the simulation on; one trigger result is produced and saved for each of the gates in this data product. The gates are interpreted following LArSoft convention for the simulation, with the times in nanoseconds and in simulation time reference.
Output data products
For each ADC threshold there will be an instance of the following:
std::vector<raw::Trigger>: list of triggers fired according to the configured trigger definition; there is one collection (and data product) per ADC threshold, and the data product has the same instance name as the input data one, unless there is only one threshold (see TriggerGatesTag, Thresholds and KeepThresholdName configuration parameters); at least one trigger object is produced for each of the beam gates found in the input data product specified by the BeamGates parameter. Each trigger object has the time stamp matching the time the trigger criteria are satisfied. All triggers feature the bits specified in BeamBits configuration parameter, with the following exceptions: if there was no trigger found, the bits will all be cleared; and if there was more than one trigger found in the same gate, all triggers except the first one (which all share the same ID) will have the RetriggeringBit set.
sbn::ExtraTriggerInfo (if ExtraInfo configuration parameter is set): always present, and reflecting the triggers on the first beam gate: if a trigger fired in that beam gate, a reduced version of sbn::ExtraTriggerInfo is provided; currently it is guaranteed to have:
triggerTimestamp: based on the art event timestamp, or invalid timestamp if the trigger did not fire.
beamGateTimestamp: set accordingly to the relative time of the trigger vs. simulated beam gate opening, if the trigger happened. Otherwise, it will be set at the event time.
sourceType: interpreted according to the trigger bits of the input beam gate object, it may be sbn::triggerSource::BNB, sbn::bits::triggerSource::NuMI or sbn::bits::triggerSource::Unknown (note that in any case it's not left to its default value sbn::bits::triggerSource::NBits).
triggerType: majority type is always set.
triggerLocationBits: set to either cryostat east or west depending on where trigger was (bit mask for sbn::bits::triggerLocation::CryoEast or sbn::bits::triggerLocation::CryoWest).
triggerID and triggerCount match the trigger number in raw::Trigger::TriggerNumber(), except in case no trigger fired, in which case triggerID is sbn::ExtraTriggerInfo::NoID and triggerCount is 0, both in their default values.
gateID and gateCount match the event number.
If the first gate did not emit a trigger, the object will be left default-constructed, noticeably with an invalid trigger timestamp (sbn::ExtraTriggerInfo::NoTimestamp). Note that there may be exceptions to this rule (for example, triggerSource, beamGateTimestamp and the gate counts described above). Also note that sbn::ExtraTriggerInfo::isValid(), bound to the source of the trigger, will return true even when there was no trigger firing.
Trigger bits
The trigger bits may be overridden by the BeamBits configuration parameter. If they are not, the bits from an input "beam" gate will be used verbatim for all the triggers within that gate.
On top of this base set of bits, this module may add a few additional bits.
The module can be configured so that multiple trigger objects are created for a single input gate. In that case, the triggers after the first one may be marked as "retriggering" by setting a bit whose position is determined by RetriggeringBit configuration parameter.
In addition, the module can mark a trigger according to which cryostat it originated from. The position of the bit for cryostat 0 is set by the CryostatFirstBit, and the next cryostat(s) will follow in their order with more significant bits.
For the options where a bit position can be specified, specifying a position beyond the number of available bits effectively disables that option.
Trigger logic algorithm
This section describes the trigger logic algorithm used in icarus::trigger::TriggerSimulationOnGates and its assumptions. Nevertheless, more up-to-date information can be found in SlidingWindowTrigger module (for the combination of the LVDS signals into window-wide gates) and in icarus::trigger::SlidingWindowPatternAlg, which applies the configured pattern logic to the input.
The module receives as input a multi-level trigger gate for each of the windows to be considered. On the first input (i.e. the first event), that input is parsed to learn the windows and their relative position from the input trigger gates. This topology will be used to apply the configured patterns. On the following events, their input is checked to confirm the compatibility of the composition of its windows with the one from that first event (both aspects are handled by an icarus::trigger::WindowTopologyManager object).
All multi-level gates are set in coincidence with the beam gate by multiplying the multi-level and the beam gates. Because of this, trigger gates are suppressed everywhere except than during the beam gate (see below). The reference time for the beam gates is the time configured in DetectorClocks service provider (detinfo::DetectorClocks::BeamGateTime()).
The algorithm handles independently multiple trigger patterns. On each input, each configured pattern is applied based on the window topology. Each pattern describes a minimum level of the trigger gate in the window, that usually means the number of LVDS signals in coincidence at any given time ("majority"). A pattern may have requirements on the neighbouring windows in addition to the main one. The pattern is satisfied if all involved windows pass their specific requirements at the same time (coincidence between windows). Each pattern is applied in turn to each of the windows (which is the "main" window). The neighborhood described in the pattern is applied with respect to that main window. The trigger fires if one or more of the windows satisfy the pattern, and the trigger time is the one of the earliest satisfied pattern (more precisely, the earliest tick when the coincidence required by that pattern is satisfied).* All windows in the detector are considered independently, but the supported patterns may only include components in the same cryostat. Therefore, triggers are effectively on a single cryostat. An object of class icarus::trigger::SlidingWindowPatternAlg applies this logic: see its documentation for the most up-to-date details.
Eventually, for each event there are as many different trigger responses as how many different patterns are configured (Patterns configuration parameter), times how many ADC thresholds are provided in input, configured in Thresholds.
Beam gates
A single instance of this module can perform the simulation on several beam gates. The values of these beam gates are picked from the data product specified in BeamGates, event by event. The specified beam gate times are on beam gate time scale, i.e. their reference time 0 is the time of the beam gate as known by detinfo::DetectorClocks::BeamGateTime(). In case the same beam gate is desired for all events, such data product can be produced by icarus::trigger::WriteBeamGateInfo module. The trigger data product collection produced by this module has the same number of entries as the beam gates in the data product, and they match one-to-one.
Technical aspects of the module
This module does not build the trigger gates of the sliding windows, but rather it takes them as input (see e.g. SlidingWindowTrigger module). Window topology (size of the windows and their relations) is stored in icarus::trigger::WindowChannelMap objects, and its construction is delegated to icarus::trigger::WindowTopologyAlg (under the hood of the WindowTopologyManager class) which learns it from the actual trigger gate input rather than on explicit configuration. Pattern definitions and configuration are defined in icarus::trigger::WindowPattern and icarus::trigger::ns::fhicl::WindowPatternConfig respectively. Trigger simulation is delegated to icarus::trigger::SlidingWindowPatternAlg.
Todo
Plots need to be thought and implemented.
Definition at line 385 of file TriggerSimulationOnGates_module.cc.
Class Documentation
icarus::trigger::TriggerSimulationOnGates::Config
struct icarus::trigger::TriggerSimulationOnGates::Config
Definition at line 403 of file TriggerSimulationOnGates_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
OptionalAtom< uint32_t > BeamBits
Atom< TimeScale > BeamGateReference
Atom< InputTag > BeamGates
Atom< unsigned int > CryostatFirstBit
Atom< nanoseconds > DeadTime
Atom< bool > EmitEmpty
Atom< double > EventTimeBinning
Atom< bool > ExtraInfo
OptionalAtom< bool > KeepThresholdName
Atom< string > LogCategory
WindowPatternTable Pattern
Atom< unsigned int > RetriggeringBit
Sequence< string > Thresholds
Atom< string > TriggerGatesTag
Atom< nanoseconds > TriggerTimeResolution
icarus::trigger::TriggerSimulationOnGates::EventAux_t
struct icarus::trigger::TriggerSimulationOnGates::EventAux_t
Event-level information.
Definition at line 531 of file TriggerSimulationOnGates_module.cc.
Class Members
unsigned int event Event number.
uint64_t time Event timestamp [ns].
icarus::trigger::TriggerSimulationOnGates::ThresholdPlotInfo_t
struct icarus::trigger::TriggerSimulationOnGates::ThresholdPlotInfo_t
All information needed to generate plots for a specific threshold.
Definition at line 540 of file TriggerSimulationOnGates_module.cc.
Class Members
BinnedContent_t eventTimes
BinnedContent_t HWtrigTimeVsBeam
BinnedContent_t triggerTimesVsBeam
BinnedContent_t triggerTimesVsHWtrig
Member Typedef Documentation
BeamGates_t
using icarus::trigger::TriggerSimulationOnGates::BeamGates_t = std::vector<sim::BeamGateInfo> private
Type of list of gates to simulate trigger into.
Definition at line 548 of file TriggerSimulationOnGates_module.cc.
BinnedContent_t
using icarus::trigger::TriggerSimulationOnGates::BinnedContent_t = icarus::ns::util::FixedBins<double> private
Content for future histograms, binned.
Definition at line 537 of file TriggerSimulationOnGates_module.cc.
microseconds
using icarus::trigger::TriggerSimulationOnGates::microseconds = util::quantities::intervals::microseconds
Definition at line 398 of file TriggerSimulationOnGates_module.cc.
nanoseconds
using icarus::trigger::TriggerSimulationOnGates::nanoseconds = util::quantities::intervals::nanoseconds
Definition at line 399 of file TriggerSimulationOnGates_module.cc.
Parameters
using icarus::trigger::TriggerSimulationOnGates::Parameters = art::EDProducer::Table<Config>
Definition at line 499 of file TriggerSimulationOnGates_module.cc.
PlotSandbox_t
using icarus::trigger::TriggerSimulationOnGates::PlotSandbox_t = icarus::ns::util::PlotSandbox<art::TFileDirectory> private
Definition at line 557 of file TriggerSimulationOnGates_module.cc.
TriggerBits_t
using icarus::trigger::TriggerSimulationOnGates::TriggerBits_t = decltype(std::declval<raw::Trigger>().TriggerBits()) private
Type of trigger bits supported by raw::Trigger.
Definition at line 391 of file TriggerSimulationOnGates_module.cc.
TriggerInfo_t
using icarus::trigger::TriggerSimulationOnGates::TriggerInfo_t = details::TriggerInfo_t private
Type alias.
Definition at line 525 of file TriggerSimulationOnGates_module.cc.
WindowTriggerInfo_t
using icarus::trigger::TriggerSimulationOnGates::WindowTriggerInfo_t = icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t private
Data structure to communicate internally a trigger response.
Definition at line 528 of file TriggerSimulationOnGates_module.cc.
Constructor & Destructor Documentation
TriggerSimulationOnGates()
icarus::trigger::TriggerSimulationOnGates::TriggerSimulationOnGates (Parameters const & config) explicit
Definition at line 834 of file TriggerSimulationOnGates_module.cc.
Member Function Documentation
beamTypeToTriggerSource()
sbn::triggerSource icarus::trigger::TriggerSimulationOnGates::beamTypeToTriggerSource (sim::BeamType_t beamType) static private
Converts a sim::BeamType_t value into a sbn::bits::triggerSource one.
Definition at line 1701 of file TriggerSimulationOnGates_module.cc.
References sbn::bits::BNB, sbn::bits::NuMI, and sbn::bits::Unknown.
beginJob()
void icarus::trigger::TriggerSimulationOnGates::beginJob () override virtual
Initializes the plots.
Definition at line 979 of file TriggerSimulationOnGates_module.cc.
References initializePlots().
cryoIDtoTriggerLocation()
sbn::bits::triggerLocationMask icarus::trigger::TriggerSimulationOnGates::cryoIDtoTriggerLocation (geo::CryostatID const & cid) static private
Converts a cryostat ID into a bitmask pointing to that cryostat.
Definition at line 1718 of file TriggerSimulationOnGates_module.cc.
References sbn::bits::CryoEast, sbn::bits::CryoWest, and sbn::bits::NBits.
endJob()
void icarus::trigger::TriggerSimulationOnGates::endJob () override virtual
Prints end-of-job summaries.
Definition at line 1053 of file TriggerSimulationOnGates_module.cc.
eventTimestampInSeconds() [1/2]
double icarus::trigger::TriggerSimulationOnGates::eventTimestampInSeconds (art::Event const & event) static private
Definition at line 1770 of file TriggerSimulationOnGates_module.cc.
eventTimestampInSeconds() [2/2]
double icarus::trigger::TriggerSimulationOnGates::eventTimestampInSeconds (art::Timestamp const & time) static private
Returns the time of the event in seconds from The Epoch.
Definition at line 1759 of file TriggerSimulationOnGates_module.cc.
extractEventInfo()
auto icarus::trigger::TriggerSimulationOnGates::extractEventInfo (art::Event const & event) static private
Fills an EventAux_t from the information found in the argument.
Definition at line 1581 of file TriggerSimulationOnGates_module.cc.
finalizePlots()
void icarus::trigger::TriggerSimulationOnGates::finalizePlots () private
Creates summary plots from proto-histogram data.
Definition at line 1209 of file TriggerSimulationOnGates_module.cc.
initializePlots()
void icarus::trigger::TriggerSimulationOnGates::initializePlots () private
Initializes the full set of plots (all ADC thresholds).
Definition at line 1063 of file TriggerSimulationOnGates_module.cc.
Referenced by beginJob().
makeEventPlots()
void icarus::trigger::TriggerSimulationOnGates::makeEventPlots () private
Creates in the main sandbox all event-wide plots.
Definition at line 1286 of file TriggerSimulationOnGates_module.cc.
makeHistogramFromBinnedContent()
TH1 * icarus::trigger::TriggerSimulationOnGates::makeHistogramFromBinnedContent (PlotSandbox_t & plots, std::string const & name, std::string const & title, BinnedContent_t const & binnedContent) const private
Creates and returns a 1D histogram filled with binnedContent.
Definition at line 1734 of file TriggerSimulationOnGates_module.cc.
makeThresholdPlots()
void icarus::trigger::TriggerSimulationOnGates::makeThresholdPlots (std::string const & threshold, PlotSandbox_t & plots, ThresholdPlotInfo_t const & plotInfo) private
Creates in plots sandbox all plots for threshold threshold from data in plotInfo.
Definition at line 1229 of file TriggerSimulationOnGates_module.cc.
makeTriggerBits()
sbn::triggerSourceMask icarus::trigger::TriggerSimulationOnGates::makeTriggerBits (sim::BeamGateInfo const & beamInfo) static private
Converts trigger bits from beamInfo into a sbn::triggerSourceMask.
Definition at line 1694 of file TriggerSimulationOnGates_module.cc.
plotEvent()
void icarus::trigger::TriggerSimulationOnGates::plotEvent (art::Event const & event, detinfo::DetectorTimings const & detTimings, std::vector< sim::BeamGateInfo > const & gates) private
Fills event-wide plots.
Definition at line 1427 of file TriggerSimulationOnGates_module.cc.
plotTriggerResponse()
void icarus::trigger::TriggerSimulationOnGates::plotTriggerResponse (std::size_t iThr, std::string const & thrTag, std::vector< WindowTriggerInfo_t > const & triggerInfos, detinfo::DetectorTimings const & detTimings) private
Fills the plots for threshold index iThr with trigger information.
Definition at line 1449 of file TriggerSimulationOnGates_module.cc.
printSummary()
void icarus::trigger::TriggerSimulationOnGates::printSummary () const private
Prints the summary of fired triggers on screen.
Definition at line 1507 of file TriggerSimulationOnGates_module.cc.
produce()
void icarus::trigger::TriggerSimulationOnGates::produce (art::Event & event) override virtual
Runs the simulation and saves the results into the art event.
Definition at line 987 of file TriggerSimulationOnGates_module.cc.
produceForThreshold()
auto icarus::trigger::TriggerSimulationOnGates::produceForThreshold (art::Event & event, detinfo::DetectorTimings const & detTimings, std::vector< sim::BeamGateInfo > const & beamGates, std::size_t const iThr, std::string const & thrTag, unsigned int firstTriggerNumber) private
Performs the simulation for the specified ADC threshold.
Parameters
event art event to read data from and put results into
detTimings detector clocks service provider proxy
beamGates list of all beam gates to evaluate
iThr index of the threshold in the configuration
thr value of the threshold (ADC counts)
firstTriggerNumber the next unassigned trigger number
Returns
the trigger response information
For the given threshold, the simulation of the configured trigger is performed. The input data is read from the event (the source tag is from the module configuration), simulation is performed, auxiliary plots are drawn and a raw::Trigger collection is stored into the event.
The return value contains one trigger list per gate. Depending on the configuration (and especially fDeadTime), one gate may be any number of triggers, including none.
The simulation itself is performed by the fPatternAlg algorithm.
Definition at line 1318 of file TriggerSimulationOnGates_module.cc.
References icarus::trigger::ApplyBeamGateClass::applyToAll(), icarus::trigger::details::TriggerInfo_t::atTick(), icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t::extra, icarus::trigger::SlidingWindowPatternAlg::AllTriggerInfo_t::info, icarus::trigger::makeApplyBeamGate(), icarus::trigger::ReadTriggerGates(), and icarus::trigger::SlidingWindowPatternAlg::MoreInfo_t::windowIndex.
TimestampToUTC()
std::uint64_t icarus::trigger::TriggerSimulationOnGates::TimestampToUTC (art::Timestamp const & ts) static private
Converts a standard art timestamp into an UTC time [ns].
Definition at line 1592 of file TriggerSimulationOnGates_module.cc.
toBeamGateTime()
auto icarus::trigger::TriggerSimulationOnGates::toBeamGateTime (util::quantities::nanosecond time, detinfo::DetectorTimings const & detTimings) const private
Converts a time into beam gate time.
Parameters
time the time to be converted
detTimings detector timings helper
Returns
delay from the start of beam gate opening time to time
The time value is assumed to be in the reference as fBeamGateReference and converted into the beam gate time scale.
Definition at line 1533 of file TriggerSimulationOnGates_module.cc.
triggerInfoToTriggerData()
std::pair< std::vector< raw::Trigger >, sbn::ExtraTriggerInfo > icarus::trigger::TriggerSimulationOnGates::triggerInfoToTriggerData (detinfo::DetectorTimings const & detTimings, sim::BeamGateInfo const & beamGate, EventAux_t const & eventInfo, unsigned int triggerNumber, std::vector< WindowTriggerInfo_t > const & info) const private
Converts the trigger information into trigger objects.
Parameters
detTimings detector clocks service provider proxy
beamGates list of all beam gates to evaluate
eventInfo event-wide information to be transferred to trigger data
triggerNumber the "unique" number to assign to this trigger
info the information about the fired triggers
Returns
objects with all the trigger information encoded
The triggers described by info are encoded into raw::Trigger objects. If no trigger is present, one object may be made up depending of the value configured in fEmitEmpty. A sbn::ExtraTriggerInfo object is also returned representing the first trigger in the beam gate (see the Output section of module documentation for details).
Definition at line 1602 of file TriggerSimulationOnGates_module.cc.
References sbn::ExtraTriggerInfo::beamGateTimestamp, icarus::trigger::TriggerSimulationOnGates::EventAux_t::event, sbn::ExtraTriggerInfo::gateCount, sbn::ExtraTriggerInfo::gateID, sbn::bits::Majority, sbn::ExtraTriggerInfo::NoID, sbn::ExtraTriggerInfo::NoTimestamp, sbn::ExtraTriggerInfo::sourceType, icarus::trigger::TriggerSimulationOnGates::EventAux_t::time, sbn::ExtraTriggerInfo::triggerCount, sbn::ExtraTriggerInfo::triggerID, sbn::ExtraTriggerInfo::triggerLocationBits, sbn::ExtraTriggerInfo::triggerTimestamp, and sbn::ExtraTriggerInfo::triggerType.
WindowCryostat()
static geo::CryostatID icarus::trigger::TriggerSimulationOnGates::WindowCryostat (icarus::trigger::WindowChannelMap::WindowInfo_t const & winfo) inline static private
Returns the ID of the cryostat the specified window belongs to.
Definition at line 773 of file TriggerSimulationOnGates_module.cc.
Member Data Documentation
fADCthresholds
std::map<std::string, art::InputTag> icarus::trigger::TriggerSimulationOnGates::fADCthresholds private
Name of ADC thresholds to read, and the input tag connected to their data.
Definition at line 563 of file TriggerSimulationOnGates_module.cc.
fBeamBits
std::optional<std::uint32_t> icarus::trigger::TriggerSimulationOnGates::fBeamBits private
Bits for the beam gate being simulated.
Definition at line 573 of file TriggerSimulationOnGates_module.cc.
fBeamGateReference
util::TimeScale const icarus::trigger::TriggerSimulationOnGates::fBeamGateReference private
Reference time of beam gates.
Definition at line 570 of file TriggerSimulationOnGates_module.cc.
fBeamGateTag
art::InputTag const icarus::trigger::TriggerSimulationOnGates::fBeamGateTag private
Data product of beam gates to simulate.
Definition at line 568 of file TriggerSimulationOnGates_module.cc.
fCryostatZeroMask
TriggerBits_t const icarus::trigger::TriggerSimulationOnGates::fCryostatZeroMask private
Bit mask for cryostat 0.
Definition at line 585 of file TriggerSimulationOnGates_module.cc.
fDeadTime
nanoseconds const icarus::trigger::TriggerSimulationOnGates::fDeadTime private
Veto time after a trigger in a gate.
Definition at line 580 of file TriggerSimulationOnGates_module.cc.
fEmitEmpty
bool const icarus::trigger::TriggerSimulationOnGates::fEmitEmpty private
Whether to produce trigger objects for gates without triggers.
Definition at line 576 of file TriggerSimulationOnGates_module.cc.
fEventPlotInfo
ThresholdPlotInfo_t icarus::trigger::TriggerSimulationOnGates::fEventPlotInfo private
Proto-histogram information in a convenient packet; event-wide.
Definition at line 621 of file TriggerSimulationOnGates_module.cc.
fEventTimeBinning
double const icarus::trigger::TriggerSimulationOnGates::fEventTimeBinning private
Trigger time plot binning [s].
Definition at line 589 of file TriggerSimulationOnGates_module.cc.
fExtraInfo
bool const icarus::trigger::TriggerSimulationOnGates::fExtraInfo private
Whether to produce a sbn::ExtraTriggerInfo.
Definition at line 578 of file TriggerSimulationOnGates_module.cc.
fLogCategory
std::string const icarus::trigger::TriggerSimulationOnGates::fLogCategory private
Message facility stream category for output.
Definition at line 592 of file TriggerSimulationOnGates_module.cc.
fOutputDir
art::TFileDirectory icarus::trigger::TriggerSimulationOnGates::fOutputDir private
ROOT directory where all the plots are written.
Definition at line 600 of file TriggerSimulationOnGates_module.cc.
fOutputInstances
std::vector<std::string> icarus::trigger::TriggerSimulationOnGates::fOutputInstances private
Output data product instance names (same order as fADCthresholds).
Definition at line 608 of file TriggerSimulationOnGates_module.cc.
fPattern
WindowPattern const icarus::trigger::TriggerSimulationOnGates::fPattern private
Configured sliding window requirement pattern.
Definition at line 566 of file TriggerSimulationOnGates_module.cc.
fPatternAlg
std::optional<icarus::trigger::SlidingWindowPatternAlg> icarus::trigger::TriggerSimulationOnGates::fPatternAlg private
Pattern algorithm.
Definition at line 615 of file TriggerSimulationOnGates_module.cc.
fPlots
PlotSandbox_t icarus::trigger::TriggerSimulationOnGates::fPlots private
All plots in one practical sandbox.
Definition at line 618 of file TriggerSimulationOnGates_module.cc.
fRetriggeringMask
TriggerBits_t const icarus::trigger::TriggerSimulationOnGates::fRetriggeringMask private
Bit mask set for triggers after the first one in a gate.
Definition at line 583 of file TriggerSimulationOnGates_module.cc.
fThresholdPlots
std::vector<ThresholdPlotInfo_t> icarus::trigger::TriggerSimulationOnGates::fThresholdPlots private
Proto-histogram information in a not-so-practical array; per threshold.
Count of fired triggers, per threshold.
Definition at line 624 of file TriggerSimulationOnGates_module.cc.
fTotalGates
std::atomic<unsigned int> icarus::trigger::TriggerSimulationOnGates::fTotalGates { 0U } private
Count of opened gates.
Definition at line 628 of file TriggerSimulationOnGates_module.cc.
fTriggerCount
std::vector<std::atomic<unsigned int> > icarus::trigger::TriggerSimulationOnGates::fTriggerCount private
Definition at line 627 of file TriggerSimulationOnGates_module.cc.
fTriggerTimeResolution
nanoseconds const icarus::trigger::TriggerSimulationOnGates::fTriggerTimeResolution private
Trigger resolution in time.
Definition at line 587 of file TriggerSimulationOnGates_module.cc.
fWindowMapMan
icarus::trigger::WindowTopologyManager icarus::trigger::TriggerSimulationOnGates::fWindowMapMan mutable private
Mapping of each sliding window with location and topological information.
Definition at line 612 of file TriggerSimulationOnGates_module.cc.
NTriggerBits
std::size_t icarus::trigger::TriggerSimulationOnGates::NTriggerBits = sizeof(TriggerBits_t) * 8U static constexpr private
Number of bits supported by raw::Trigger.
Definition at line 394 of file TriggerSimulationOnGates_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/TriggerSimulationOnGates_module.cc