CAF format: icarus::trigger::LVDSbitMaps Class Reference
icarus::trigger::LVDSbitMaps Class Reference
Utility to build and maintain ICARUS trigger LVDS bit maps.
#include <LVDSbitMaps.h>
Classes
struct LVDSchannel_t
Public Types
enum class Errors {
NoError , Error , NoDatabase , NoPMTfragment ,
NoPairBitInformation , NoAdderBitInformation , Unknown
}
Error codes from this object. See errorMessage() code for descriptions.
enum class Map { PMTpairs , Adders }
Supported maps.
using Exception = cet::coded_exception<Errors, &errorMessage>
Type of exception thrown by this object.
Public Member Functions
LVDSbitMaps ()=default
Default constructor: maps empty until rebuild() is called.
LVDSbitMaps (icarusDB::IICARUSChannelMapProvider const &channelMap)
Constructor: builds all the maps based on the specified PMT channel map.
LVDSbitMaps (icarusDB::IICARUSChannelMapProvider const &channelMap, std::initializer_list< Map > maps)
void rebuild (icarusDB::IICARUSChannelMapProvider const &channelMap)
Rebuilds all the LVDS maps based on the specified channel map status.
Query interface.
bool hasMap (Map map) const
Returns whether the specified map is present.
LVDSinfo_t bitSource (PMTpairBitID const &bit) const
Returns the source bit for the specified encoded PMT pair bit.
AdderInfo_t bitSource (AdderBitID const &bit) const
Returns the source bit for the specified encoded adder bit.
std::vector< std::vector< raw::Channel_t > > channelPairs () const
Returns a list of channels paired in a single LVDS.
Static Public Member Functions
static std::string errorMessage (Errors code)
Returns a predefined message describing the specified error code.
Static Public Attributes
Good old hard-coded ICARUS geometry.
static constexpr unsigned int NChannels = 360
Total number of PMT channels in the detector.
static constexpr unsigned int NChannelsPerCryostat = 180
Number of PMT channels in each cryostat.
static constexpr std::size_t NCryostats = NChannels / NChannelsPerCryostat
Number of cryostats in the detector.
Private Member Functions
void buildAllMaps (icarusDB::IICARUSChannelMapProvider const &channelMap)
Builds all the maps.
void buildMaps (icarusDB::IICARUSChannelMapProvider const &channelMap, std::initializer_list< Map > maps)
Builds the specified maps. If any error occurs, an Exception is thrown.
std::vector< LVDSchannel_t > buildChannelInfo (icarusDB::IICARUSChannelMapProvider const &channelMap) const
Fills a list of PMT channels and their relevant information.
std::vector< LVDSinfo_t > buildPMTpairSourceMap (icarusDB::IICARUSChannelMapProvider const &channelMap) const
Builds the LVDS map connecting each bit to its hardware source.
std::vector< AdderInfo_t > buildAdderSourceMap (icarusDB::IICARUSChannelMapProvider const &channelMap) const
Builds the adder map connecting each bit to its hardware source.
Private Attributes
std::vector< LVDSchannel_t > fPMTchannelInfo
Cached information of each PMT (sorted by PMT channel).
std::vector< LVDSinfo_t > fLVDSinfoMap
For each PMT pair bit index, the HW LVDS ID and information are stored.
std::vector< AdderInfo_t > fAdderInfoMap
For each adder bit ID, adder information is stored.
Detailed Description
Utility to build and maintain ICARUS trigger LVDS bit maps.
This object caches the relations between the LVDS bits. The maps include:
from logic LVDS bit ID to hardware LVDS bit ID (see below).
Upon request, the following mappings may be added:
from PMT channel to LVDS bit ID (logic), and vice versa.
Maps are build based on the information from the PMT hardware channel mapping.
Mapping conventions
The logic mapping is described in sbn::ExtraTriggerInfo::LVDSstatus. Compared with that mapping, the PMT pair bit ID are assigned so that
the index of the ID, modulo 64 bits, matches the LVDSstatus words;
cryostats and PMT walls of the IDs are honoured, so that they can be used to directly address LVDSstatus.
Likewise, the adder bit ID are assigned so that
the index of the ID, modulo 6 bits, matches the sectorStatus words;
cryostats and PMT walls of the IDs are honoured, so that they can be used to directly address sectorStatus.
This results in the following mapping, "first bit" meaning the most significant.
PMT pairs:
east cryostat, east wall: 0x00aAbBcC'00dDeEfF, channel 0 the most significant bit in a (bit #55) and channel 45 the one in d (bit 23);
east cryostat, west wall: 0x00aAbBcC'00dDeEfF, channel 90 the most significant bit in a (bit #55) and channel 135 the one in d (bit 23);
west cryostat, east wall: 0x00aAbBcC'00dDeEfF, channel 180 the most significant bit in a (bit #55) and channel 225 the one in d (bit 23);
west cryostat, west wall: 0x00aAbBcC'00dDeEfF, channel 270 the most significant bit in a (bit #55) and channel 315 the one in d (bit 23).
Adders:
east cryostat, east wall: 0b00000000'00abcdef, with a to f covering adders starting with channel 0, 15, 30,45, 60 and 75;
east cryostat, west wall: 0b00000000'00abcdef, with a to f covering adders starting with channel 90, 105, 120,135, 150 and 165;
west cryostat, east wall: 0b00000000'00abcdef, with a to f covering adders starting with channel 180, 195, 210,225, 240 and 255;
west cryostat, west wall: 0b00000000'00abcdef, with a to f covering adders starting with channel 270, 285, 300,315, 330 and 345.
Naming conventions
Each PMT has a channel ID associated with a location; the relation between the channel number value and the position of the PMT is fixed by a convention (from LArSoft). This is a "logical" channel number. On the other side, each PMT has a unique identifier that was assigned by the ICARUS PMT Working Group and is used as key in an hardware database. This is the PMT hardware channel number. These two channel numbers may be (and in fact, are) different. A similar distinction is made of the LVDS signals.
Eight LVDS signals with discriminated PMT pair information are emitted by each CAEN V1730B PMT readout board. These bits are collected into four 64-bit words, one for each of the four PMT walls. The word values are stored in sbn::ExtraTriggerInfo, which also defines the convention relating each of the bits in the 64-bit words with the physical location of the PMT feeding the bit. This is equivalent to the logical PMT channel number described above, and here we call it a "logical LVDS bit ID". Analyzers will typically deal with this logical ID only. It is described by icarus::trigger::PMTpairBitID data type.
The assembly of the bits in hardware includes the combination of 8-bit information from groups of three PMT readout boards, physically using LVDS format and for that often just dubbed "the LVDS signals", via custom LVDS boxes into 32-bit cables and connectors, with the excess 8 bits in each of them partly used for other information. Like in the case of single PMT, we define a "hardware LVDS bit ID" representing the position of a bit in the 32-bit word in the connector, and identifying the connector. The relation of these bits with the actual PMT channels is encoded in the hardware database; analyzers typically don't have to deal with them, because the trigger decoding software will translate them into the sbn::ExtraTriggerInfo convention (using, in fact, this LVDSbitMaps object for the mapping). The data type devoted to this concept is LVDSHWbitID. Note that the NIM FPGA boards combine two 32-bit connector words into 64-bit words for transportation. These 64-bit words are stored in the trigger DAQ fragment. At first look, these 64-bit words are similar to the ones described in the previous bullet, but their bits are in a different relation with the actual readout boards and PMT. Also note that the decoding of these 64-bit words from the FPGA require, on top oft he information from this mapping, the information of where each connector is located within the word (hint: connectors 0 and 2 are stored as the most significant 32-bit word, 1 and 3 as the least significant one).
Definition at line 376 of file LVDSbitMaps.h.
Member Typedef Documentation
Exception
using icarus::trigger::LVDSbitMaps::Exception = cet::coded_exception<Errors, &errorMessage>
Type of exception thrown by this object.
Definition at line 417 of file LVDSbitMaps.h.
Member Enumeration Documentation
Errors
enum class icarus::trigger::LVDSbitMaps::Errors strong
Error codes from this object. See errorMessage() code for descriptions.
Enumerator
NoError
No error condition.
Error
An unspecified error condition.
NoDatabase
No channel mapping database access.
NoPMTfragment
Missing a required PMT fragment information.
NoPairBitInformation
No PMT pair bit information in the database.
NoAdderBitInformation
No adder bit information in the database.
Unknown
Unknown error.
Definition at line 397 of file LVDSbitMaps.h.
Map
enum class icarus::trigger::LVDSbitMaps::Map strong
Supported maps.
Enumerator
PMTpairs
Map of PMT pairs ("LVDS").
Adders
Map of adder signals.
Definition at line 408 of file LVDSbitMaps.h.
Constructor & Destructor Documentation
LVDSbitMaps() [1/3]
icarus::trigger::LVDSbitMaps::LVDSbitMaps () default
Default constructor: maps empty until rebuild() is called.
LVDSbitMaps() [2/3]
icarus::trigger::LVDSbitMaps::LVDSbitMaps (icarusDB::IICARUSChannelMapProvider const & channelMap) inline
Constructor: builds all the maps based on the specified PMT channel map.
Definition at line 423 of file LVDSbitMaps.h.
References buildAllMaps().
LVDSbitMaps() [3/3]
icarus::trigger::LVDSbitMaps::LVDSbitMaps (icarusDB::IICARUSChannelMapProvider const & channelMap, std::initializer_list< Map > maps) inline
Constructor: builds the specified maps based on the specified PMT channel map.
Definition at line 428 of file LVDSbitMaps.h.
References buildMaps().
Member Function Documentation
bitSource() [1/2]
auto icarus::trigger::LVDSbitMaps::bitSource (AdderBitID const & bit) const
Returns the source bit for the specified encoded adder bit.
Parameters
bit ID of the logical adder bit to get the source information of
Returns
the number of hardware connector and bit where to find the value
Exceptions
std::out_of_range if the specified bit is not in the map
The output connector/bit bits are sorted according to the prescription of sbn::ExtraTriggerInfo, which requires the least significant bit to have the most upstream adder signal (i.e. the lowest channels).
The returned information includes:
the cryostat the bit comes from (the same as the one in bit);
the hardware connector number the bit comes from;
the hardware bit (wire) in the connector which carries the bit value;
the PMT channels covered by the bit.
See buildAdderSourceMap() for details of the mapping definitions.
Definition at line 90 of file LVDSbitMaps.cxx.
bitSource() [2/2]
auto icarus::trigger::LVDSbitMaps::bitSource (PMTpairBitID const & bit) const
Returns the source bit for the specified encoded PMT pair bit.
Parameters
bit ID of the logical PMT pair bit to get the source information of
Returns
the number of hardware connector and bit where to find the value
Exceptions
std::out_of_range if the specified bit is not in the map
The output connector/bit bits are sorted according to the prescription of sbn::ExtraTriggerInfo, which requires the least significant bit to have the most upstream PMT pair (i.e. the lowest channels).
The returned information includes:
the cryostat the bit comes from (the same as the one in bit);
the hardware connector number the bit comes from;
the hardware bit (wire) in the connector which carries the bit value;
the PMT channels covered by the bit.
See buildPMTpairSourceMap() for details of the mapping definitions.
Definition at line 82 of file LVDSbitMaps.cxx.
buildAdderSourceMap()
auto icarus::trigger::LVDSbitMaps::buildAdderSourceMap (icarusDB::IICARUSChannelMapProvider const & channelMap) const private
Builds the adder map connecting each bit to its hardware source.
Parameters
channelMap service provider to associate each PMT channel to LVDS
Returns
a map
The map is associating the unique adder bit ID (AdderBitID::index()) and the information of the hardware LVDS ID matching that ID. The information includes the source in the hardware connector of the bit and the involved channels (see AdderInfo_t for more).
Definition at line 295 of file LVDSbitMaps.cxx.
References icarus::trigger::AdderInfo_t::channels, icarus::trigger::details::PMTwallBitID< MaxBits >::cryostat, icarus::trigger::AdderBitID::fromIndex(), icarus::trigger::AdderInfo_t::ID, icarus::trigger::details::PMTwallBitID< MaxBits >::index(), icarus::trigger::details::PMTwallBitID< 16 >::NCryostats, icarus::trigger::details::PMTwallBitID< 16 >::NIndices(), icarus::trigger::LVDSHWbitID::NIndices(), icarus::trigger::details::PMTwallBitID< 16 >::NPMTwallsPerCryostat, icarus::trigger::details::PMTwallBitID< MaxBits >::PMTwall, icarus::trigger::AdderInfo_t::source, and icarus::trigger::details::PMTwallBitID< MaxBits >::statusBit.
buildAllMaps()
void icarus::trigger::LVDSbitMaps::buildAllMaps (icarusDB::IICARUSChannelMapProvider const & channelMap) private
Builds all the maps.
Definition at line 111 of file LVDSbitMaps.cxx.
Referenced by LVDSbitMaps(), and rebuild().
buildChannelInfo()
auto icarus::trigger::LVDSbitMaps::buildChannelInfo (icarusDB::IICARUSChannelMapProvider const & channelMap) const private
Fills a list of PMT channels and their relevant information.
Parameters
channelMap service provider to associate each PMT channel to LVDS
Returns
the list, sorted by PMT channel ID
Definition at line 141 of file LVDSbitMaps.cxx.
buildMaps()
void icarus::trigger::LVDSbitMaps::buildMaps (icarusDB::IICARUSChannelMapProvider const & channelMap, std::initializer_list< Map > maps) private
Builds the specified maps. If any error occurs, an Exception is thrown.
Definition at line 119 of file LVDSbitMaps.cxx.
Referenced by LVDSbitMaps().
buildPMTpairSourceMap()
auto icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap (icarusDB::IICARUSChannelMapProvider const & channelMap) const private
Builds the LVDS map connecting each bit to its hardware source.
Parameters
channelMap service provider to associate each PMT channel to LVDS
Returns
a map
The map is associating the unique PMT pair bit ID (PMTpairBitID::index()) and the information of the LVDS ID matching that ID. The information includes the source in the hardware connector of the bit and the involved channels (see LVDSinfo_t for more).
Definition at line 192 of file LVDSbitMaps.cxx.
References icarus::trigger::LVDSinfo_t::channels, icarus::trigger::details::PMTwallBitID< MaxBits >::cryostat, icarus::trigger::PMTpairBitID::fromIndex(), icarus::trigger::LVDSinfo_t::ID, icarus::trigger::details::PMTwallBitID< MaxBits >::index(), icarus::trigger::details::PMTwallBitID< 64 >::NCryostats, icarus::trigger::details::PMTwallBitID< 64 >::NIndices(), icarus::trigger::LVDSHWbitID::NIndices(), icarus::trigger::details::PMTwallBitID< 64 >::NPMTwallsPerCryostat, icarus::trigger::details::PMTwallBitID< MaxBits >::PMTwall, icarus::trigger::LVDSinfo_t::source, and icarus::trigger::details::PMTwallBitID< MaxBits >::statusBit.
channelPairs()
std::vector< std::vector< raw::Channel_t > > icarus::trigger::LVDSbitMaps::channelPairs () const
Returns a list of channels paired in a single LVDS.
Returns
a list of vectors of one or two PMT channel ID
This method recreates the pairing of PMT channels into LVDS bits. The order of the "pairs" follows the order of the logic bits. These "pairs" can actually contain either two or one ID; empty pairs (from invalid bits) are not included.
Definition at line 99 of file LVDSbitMaps.cxx.
errorMessage()
std::string icarus::trigger::LVDSbitMaps::errorMessage (Errors code) static
Returns a predefined message describing the specified error code.
Definition at line 396 of file LVDSbitMaps.cxx.
hasMap()
bool icarus::trigger::LVDSbitMaps::hasMap (Map map) const
Returns whether the specified map is present.
Definition at line 69 of file LVDSbitMaps.cxx.
References Adders, Error, fAdderInfoMap, fLVDSinfoMap, and PMTpairs.
rebuild()
void icarus::trigger::LVDSbitMaps::rebuild (icarusDB::IICARUSChannelMapProvider const & channelMap) inline
Rebuilds all the LVDS maps based on the specified channel map status.
Definition at line 502 of file LVDSbitMaps.h.
References buildAllMaps().
Member Data Documentation
fAdderInfoMap
std::vector<AdderInfo_t> icarus::trigger::LVDSbitMaps::fAdderInfoMap private
For each adder bit ID, adder information is stored.
Definition at line 545 of file LVDSbitMaps.h.
Referenced by hasMap().
fLVDSinfoMap
std::vector<LVDSinfo_t> icarus::trigger::LVDSbitMaps::fLVDSinfoMap private
For each PMT pair bit index, the HW LVDS ID and information are stored.
Definition at line 542 of file LVDSbitMaps.h.
Referenced by hasMap().
fPMTchannelInfo
std::vector<LVDSchannel_t> icarus::trigger::LVDSbitMaps::fPMTchannelInfo private
Cached information of each PMT (sorted by PMT channel).
Definition at line 539 of file LVDSbitMaps.h.
NChannels
unsigned int icarus::trigger::LVDSbitMaps::NChannels = 360 static constexpr
Total number of PMT channels in the detector.
Definition at line 385 of file LVDSbitMaps.h.
NChannelsPerCryostat
unsigned int icarus::trigger::LVDSbitMaps::NChannelsPerCryostat = 180 static constexpr
Number of PMT channels in each cryostat.
Definition at line 388 of file LVDSbitMaps.h.
NCryostats
std::size_t icarus::trigger::LVDSbitMaps::NCryostats = NChannels / NChannelsPerCryostat static constexpr
Number of cryostats in the detector.
Definition at line 391 of file LVDSbitMaps.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.cxx