CAF format: icarusDB::IICARUSChannelMapProvider Class Reference
icarusDB::IICARUSChannelMapProvider Class Reference abstract
Interface of ICARUS channel mapping service provider.
#include <IICARUSChannelMapProvider.h>
Public Member Functions
virtual TPCReadoutBoardToChannelMap const & getReadoutBoardToChannelMap () const =0
Returns the full TPC channel mapping.
Data period selection
— BEGIN — Data period selection -----------------------------------—
virtual bool forRun (int run)=0
Loads the mapping for run, returns whether a new mapping was loaded.
virtual bool forPeriod (icarusDB::RunPeriod period)=0
Loads the mapping for period, returns whether a new mapping was loaded.
TPC fragment information
— BEGIN - - TPC fragment information - - - - - - - - - - - - - - - - - -
virtual bool hasFragmentID (unsigned int ID) const =0
Returns whether the specified ID is a known TPC fragment ID.
virtual unsigned int nTPCfragmentIDs () const =0
Returns the number of TPC fragment IDs known to the service.
virtual std::string const & getCrateName (unsigned int fragmentID) const =0
Returns the name of the crate served by the specified fragmentID.
virtual ReadoutIDVec const & getReadoutBoardVec (unsigned int fragmentID) const =0
Returns the list of board IDs included in the specified fragmentID.
TPC board information
— BEGIN - - TPC board information - - - - - - - - - - - - - - - - - - -
virtual bool hasBoardID (unsigned int ID) const =0
Returns whether there is a board with the specified ID.
virtual unsigned int nTPCboardIDs () const =0
Returns the number of TPC board IDs known to the service.
virtual unsigned int getBoardSlot (unsigned int boardID) const =0
Returns the number of slot the boardID is on.
virtual ChannelPlanePairVec const & getChannelPlanePair (unsigned int boardID) const =0
PMT information
— END - - - TPC board information - - - - - - - - - - - - - - - - - - - — BEGIN — PMT information -----------------------------------------—
virtual bool hasPMTDigitizerID (unsigned int ID) const =0
Returns whether the specified fragment ID is known to the mapping.
virtual unsigned int nPMTfragmentIDs () const =0
Returns the number of PMT fragment IDs known to the mapping.
virtual PMTdigitizerInfoVec const & getPMTchannelInfo (unsigned int ID) const =0
Returns records on all the PMT channels covered by the fragment ID.
CRT information
— END --— PMT information -----------------------------------------— — BEGIN — CRT information -----------------------------------------—
virtual unsigned int getSimMacAddress (unsigned int hwmacaddress) const =0
virtual unsigned int gettopSimMacAddress (unsigned int) const =0
virtual std::pair< double, double > getSideCRTCalibrationMap (int mac5, int chan) const =0
Returns the gain and pedestal for Side CRT.
Public Member Functions inherited from util::CacheCounter
CacheCounter ()
Constructor: prepares the ID of the default cache tag.
CacheCounter (std::initializer_list< CacheTag_t > tags)
Constructor: prepares the ID of the caches with the specified tags.
void addCacheTags (std::initializer_list< CacheTag_t > tags)
Adds tags. The ID of existing ones are not changed.
CacheID_t cacheID (CacheTag_t const &tag) const
Returns the current ID of the cache with the specified tag.
bool hasTag (CacheTag_t const &tag) const
Returns whether the specified tag is tracked.
bool wasCacheUpdatedSince (CacheTag_t const &tag, CacheID_t sinceID) const
Returns whether the cache tag was updated since it has sinceID ID.
bool wasCacheUpdatedSince (CacheID_t sinceID) const
Returns whether the default cache was updated since it has sinceID ID.
Additional Inherited Members
Public Types inherited from util::CacheCounter
using CacheID_t = unsigned long
Type of cache identifier.
using CacheTag_t = std::string
Type of cache name.
Static Public Attributes inherited from util::CacheCounter
static constexpr CacheID_t NoCache = 0
ID specifying that cache is not present yet.
Protected Member Functions inherited from util::CacheCounter
CacheID_t updateCacheID (CacheTag_t const &cacheTag="") const
Protected Attributes inherited from util::CacheCounter
std::map< CacheTag_t, std::atomic< CacheID_t > > fCacheID
ID of the current caches.
Detailed Description
Interface of ICARUS channel mapping service provider.
The service providers implementing this interface provide access to ICARUS channel mapping.
The mapping organization reflects what was needed at the time of inception.
The service provider is expected to have status and to be compatible with multithreading only within the same run period. In fact, a current run (forRun()) or run period (forPeriod()) must be selected and all the provided information will pertain the selected run period.
Also, given that the interface yields complex structures by reference, it is expected that implementations cache results in their final form and provide direct access to that cache.
The interface includes cache tracking support via util::CacheCounter. Implementations are expected to maintain the tracking of the cache with the default (empty) name; by default the cache will be always considered outdated.
Definition at line 48 of file IICARUSChannelMapProvider.h.
Member Function Documentation
forPeriod()
virtual bool icarusDB::IICARUSChannelMapProvider::forPeriod (icarusDB::RunPeriod period) pure virtual
Loads the mapping for period, returns whether a new mapping was loaded.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by icarusDB::ICARUSChannelMapPostGres::ICARUSChannelMapPostGres(), and icarusDB::ICARUSChannelMapSQLite::ICARUSChannelMapSQLite().
forRun()
virtual bool icarusDB::IICARUSChannelMapProvider::forRun (int run) pure virtual
Loads the mapping for run, returns whether a new mapping was loaded.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
getBoardSlot()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::getBoardSlot (unsigned int boardID) const pure virtual
Returns the number of slot the boardID is on.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
getChannelPlanePair()
virtual ChannelPlanePairVec const & icarusDB::IICARUSChannelMapProvider::getChannelPlanePair (unsigned int boardID) const pure virtual
Returns a list of channels served by the boardID and for each the plane it is on (0 to 2).
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
getCrateName()
virtual std::string const & icarusDB::IICARUSChannelMapProvider::getCrateName (unsigned int fragmentID) const pure virtual
Returns the name of the crate served by the specified fragmentID.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
getPMTchannelInfo()
virtual PMTdigitizerInfoVec const & icarusDB::IICARUSChannelMapProvider::getPMTchannelInfo (unsigned int ID) const pure virtual
Returns records on all the PMT channels covered by the fragment ID.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by icarus::DaqDecoderICARUSPMT::createFragmentWaveforms().
getReadoutBoardToChannelMap()
virtual TPCReadoutBoardToChannelMap const & icarusDB::IICARUSChannelMapProvider::getReadoutBoardToChannelMap () const pure virtual
Returns the full TPC channel mapping.
— END - - - TPC fragment information - - - - - - - - - - - - - - - - - -
The returned mapping is an associative container, associating each board ID (boardID) to the following information (in a std::tuple):
[0] slot number the board is on (like getBoardSlot(boardID))
[1] list of channels served by the board, and their plane (like getChannelPlanePair(boardID))
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping().
getReadoutBoardVec()
virtual ReadoutIDVec const & icarusDB::IICARUSChannelMapProvider::getReadoutBoardVec (unsigned int fragmentID) const pure virtual
Returns the list of board IDs included in the specified fragmentID.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
getSideCRTCalibrationMap()
virtual std::pair< double, double > icarusDB::IICARUSChannelMapProvider::getSideCRTCalibrationMap (int mac5, int chan) const pure virtual
Returns the gain and pedestal for Side CRT.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by icarus::crt::CRTDataAnalysis::analyze(), icarus::crt::CRTHitRecoAlg::MakeSideHit(), and icarus::crt::CRTHitRecoAlg::PreselectCRTData().
getSimMacAddress()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::getSimMacAddress (unsigned int hwmacaddress) const pure virtual
Returns the Sim Mac address corresponding to the specified side CRT hardware address.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
gettopSimMacAddress()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::gettopSimMacAddress (unsigned int) const pure virtual
Returns the sim Mac address corresponding to the specified top CRT hardware address.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
hasBoardID()
virtual bool icarusDB::IICARUSChannelMapProvider::hasBoardID (unsigned int ID) const pure virtual
Returns whether there is a board with the specified ID.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
hasFragmentID()
virtual bool icarusDB::IICARUSChannelMapProvider::hasFragmentID (unsigned int ID) const pure virtual
Returns whether the specified ID is a known TPC fragment ID.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping(), daq::TPCDecoderFilter1D::process_fragment(), and daq::TPCDecoderFilter2D::process_fragment().
hasPMTDigitizerID()
virtual bool icarusDB::IICARUSChannelMapProvider::hasPMTDigitizerID (unsigned int ID) const pure virtual
Returns whether the specified fragment ID is known to the mapping.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by icarus::DaqDecoderICARUSPMT::fragmentWaveformTimestamp().
nPMTfragmentIDs()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::nPMTfragmentIDs () const pure virtual
Returns the number of PMT fragment IDs known to the mapping.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
nTPCboardIDs()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::nTPCboardIDs () const pure virtual
Returns the number of TPC board IDs known to the service.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping().
nTPCfragmentIDs()
virtual unsigned int icarusDB::IICARUSChannelMapProvider::nTPCfragmentIDs () const pure virtual
Returns the number of TPC fragment IDs known to the service.
Implemented in icarusDB::ICARUSChannelMapProvider, icarusDB::ICARUSChannelMapProviderBase< ChMapAlg >, icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapPostGres >, and icarusDB::ICARUSChannelMapProviderBase< icarusDB::ChannelMapSQLite >.
Referenced by dumpTPCmapping().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/ChannelMapping/IICARUSChannelMapProvider.h