CAF format: icarus::trigger::ManagedTriggerGateBuilder Class Reference
icarus::trigger::ManagedTriggerGateBuilder Class Reference
Base interface for gate builders.
#include <ManagedTriggerGateBuilder.h>
Classes
struct GateManager
Public Member Functions
template<typename GateMgr >
auto unifiedBuild (GateMgr &&gateManager, std::vector< WaveformWithBaseline > const &waveforms) const -> std::vector< TriggerGates >
Public Member Functions inherited from icarus::trigger::TriggerGateBuilder
TriggerGateBuilder (Config const &config)
Constructor: sets the configuration.
virtual ~TriggerGateBuilder ()=default
Virtual destructor. Nothing special about it, except that it's virtual.
virtual void setup (detinfo::DetectorTimings const &timings)
Algorithm setup.
virtual void reset ()
Algorithm reset. It will require a new setup before using it again.
virtual void resetup (detinfo::DetectorTimings const &timings)
Resets and sets up.
virtual void resetup (detinfo::DetectorTimings const &timings, std::vector< ADCCounts_t > const &thresholds)
Resets and sets up (including a new set of thresholds).
virtual std::vector< TriggerGates > build (std::vector< WaveformWithBaseline > const &waveforms) const =0
Returns a collection of TriggerGates objects sorted by threshold.
std::vector< ADCCounts_t > const & channelThresholds () const
Returns all the configured thresholds.
std::size_t nChannelThresholds () const
Returns the number of configured thresholds.
optical_tick timeToOpticalTick (microsecond time) const
Converts a time [µs] into optical ticks.
optical_tick timeStampToOpticalTick (raw::TimeStamp_t time) const
Converts a timestamp from raw::OpDetWaveform into optical ticks.
Protected Member Functions
template<typename GateMgr >
std::vector< TriggerGates > unifiedBuild (GateMgr &&gateManager, std::vector< WaveformWithBaseline > const &waveforms) const
Returns a collection of TriggerGates objects sorted by threshold.
template<typename GateInfo , typename Waveforms >
void buildChannelGates (std::vector< GateInfo > &channelGates, Waveforms const &channelWaveforms) const
Computes the gates for all the waveforms in one optical channel.
Protected Member Functions inherited from icarus::trigger::TriggerGateBuilder
detinfo::DetectorTimings const & detTimings () const
Returns a detector timings object.
std::vector< TriggerGates > prepareAllGates () const
virtual void doSetThresholds (std::vector< ADCCounts_t > const &thresholds)
Sets all thresholds anew.
Private Types
using Base_t = icarus::trigger::TriggerGateBuilder
Additional Inherited Members
Public Types inherited from icarus::trigger::TriggerGateBuilder
using Channel_t = raw::Channel_t
Static Public Member Functions inherited from icarus::trigger::TriggerGateBuilder
static constexpr bool isValidChannel (Channel_t channel)
Returns whether channel is valid.
Static Public Attributes inherited from icarus::trigger::TriggerGateBuilder
static constexpr Channel_t InvalidChannel = std::numeric_limits<Channel_t>::max()
Mnemonic for an invalid optical detector channel.
Detailed Description
Base interface for gate builders.
See also
icarus::trigger::DynamicTriggerGateBuilder, icarus::trigger::FixedTriggerGateBuilder
This base class provides a skeleton building algorithm that can be customised by templates. The allowed customization includes what to do when a threshold is crossed in a gate.
Note that actions are performed only when the sample crosses a threshold. The algorithm keeps track at each time of which are the thresholds enclosing the signal level, and if the level crosses one of them, the gates associated to those thresholds, and only them, are offered a chance to react.
Definition at line 54 of file ManagedTriggerGateBuilder.h.
Member Typedef Documentation
Base_t
using icarus::trigger::ManagedTriggerGateBuilder::Base_t = icarus::trigger::TriggerGateBuilder private
Definition at line 57 of file ManagedTriggerGateBuilder.h.
Member Function Documentation
buildChannelGates()
template<typename GateInfo , typename Waveforms > void icarus::trigger::ManagedTriggerGateBuilder::buildChannelGates (std::vector< GateInfo > & channelGates, Waveforms const & channelWaveforms) const protected
Computes the gates for all the waveforms in one optical channel.
Definition at line 108 of file ManagedTriggerGateBuilder.tcc.
References icarus::trigger::TriggerGateBuilder::channelThresholds(), and icarus::trigger::TriggerGateBuilder::timeStampToOpticalTick().
unifiedBuild() [1/2]
template<typename GateMgr > std::vector< TriggerGates > icarus::trigger::ManagedTriggerGateBuilder::unifiedBuild (GateMgr && gateManager, std::vector< WaveformWithBaseline > const & waveforms) const protected
Returns a collection of TriggerGates objects sorted by threshold.
Referenced by icarus::trigger::DynamicTriggerGateBuilder::build(), and icarus::trigger::FixedTriggerGateBuilder::build().
unifiedBuild() [2/2]
template<typename GateMgr > auto icarus::trigger::ManagedTriggerGateBuilder::unifiedBuild (GateMgr && gateManager, std::vector< WaveformWithBaseline > const & waveforms) const -> std::vector<TriggerGates>
Definition at line 46 of file ManagedTriggerGateBuilder.tcc.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/ManagedTriggerGateBuilder.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/ManagedTriggerGateBuilder.tcc