CAF format: icarus::trigger::PMTpairBitID Struct Reference
icarus::trigger::PMTpairBitID Struct Reference
#include <LVDSbitMaps.h>
Public Types
using BaseID_t = details::PMTwallBitID<64>
Public Types inherited from icarus::trigger::details::PMTwallBitID< 64 >
using BitID_t
This ID type.
using StatusBit_t
Type for bit in the status word.
using Index_t
Type for bit ID index.
Static Public Member Functions
static PMTpairBitID fromIndex (Index_t index)
Rebuilds an ID object from its index.
Static Public Member Functions inherited from icarus::trigger::details::PMTwallBitID< 64 >
static constexpr BitID_t fromIndex (Index_t index)
Rebuilds an ID object from its index.
static constexpr Index_t NIndices ()
Returns the number of possible indices (0 to NIndices() - 1).
Additional Inherited Members
Public Member Functions inherited from icarus::trigger::details::PMTwallBitID< 64 >
constexpr bool hasCryostat () const
Returns if the cryostat is set; ID is valid even if this is false.
constexpr bool hasPMTwall () const
Returns if the PMT wall is set; ID is valid even if this is false.
constexpr Index_t index () const
constexpr bool isValid () const
constexpr operator bool () const
Public Attributes inherited from icarus::trigger::details::PMTwallBitID< 64 >
std::size_t cryostat
The cryostat the bit comes from (sbn::ExtraTriggerInfo convention).
std::size_t PMTwall
The PMT wall the bit comes from (sbn::ExtraTriggerInfo convention).
StatusBit_t statusBit
The number of bit in the status word (0 is the least significant one).
Static Public Attributes inherited from icarus::trigger::details::PMTwallBitID< 64 >
static constexpr std::size_t NCryostats
How many cryostats in the detector.
static constexpr std::size_t NPMTwallsPerCryostat
How many PMT walls per cryostat. Each has one status word.
static constexpr unsigned short int NStatusWordBits
How many bits in a status word.
static constexpr std::size_t NoCryostat
Special value to identify the absence of cryostat information.
static constexpr std::size_t NoPMTwall
Special value to identify the absence of PMT wall information.
static constexpr StatusBit_t NoStatusBit
Special value to identify the absence of a status bit.
static constexpr Index_t InvalidIndex
Special value for an invalid bit index.
Detailed Description
Identifier of a "logical" LVDS bit for PMT pairs following sbn::ExtraTriggerInfo convention.
Definition at line 140 of file LVDSbitMaps.h.
Member Typedef Documentation
BaseID_t
using icarus::trigger::PMTpairBitID::BaseID_t = details::PMTwallBitID<64>
Definition at line 142 of file LVDSbitMaps.h.
Member Function Documentation
fromIndex()
static PMTpairBitID icarus::trigger::PMTpairBitID::fromIndex (Index_t index) inline static
Rebuilds an ID object from its index.
Definition at line 145 of file LVDSbitMaps.h.
References icarus::trigger::details::PMTwallBitID< 64 >::fromIndex(), and icarus::trigger::details::PMTwallBitID< 64 >::index().
Referenced by icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap().
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h