CAF format: icarus::trigger::WindowChannelMap Class Reference
icarus::trigger::WindowChannelMap Class Reference
Information about composition and topology of trigger sliding windows.
#include <WindowChannelMap.h>
Classes
struct WindowComposition_t
Geometric location and composition of the window.
struct WindowInfo_t
Information of a single window.
struct WindowTopology_t
Information of the identity and neighbourhood of a window.
Public Types
using WindowIndex_t = std::size_t
Type of window index.
Public Member Functions
WindowChannelMap (std::vector< WindowInfo_t > &&windows)
Construction: moves the windows information into the map.
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints the content of the full mapping.
void dump (std::ostream &out, std::string const &indent="") const
Access to window information.
std::size_t nWindows () const
Number of sliding windows.
bool hasWindow (WindowIndex_t index) const
Returns whether a window with the specified index is present.
WindowInfo_t const & info (WindowIndex_t index) const
Returns the information for the window with specified index (unchecked).
Static Public Member Functions
static bool isValidWindow (WindowIndex_t index)
Returns whether the specified index is not the invalid window index.
Static Public Attributes
static const WindowIndex_t InvalidWindowIndex = std::numeric_limits<WindowIndex_t>::max()
Special index denoting an invalid window.
Private Attributes
std::vector< WindowInfo_t > fWindows
Iterable standard interface
using value_type = WindowInfo_t
using reference_type = WindowInfo_t const&
using pointer_type = WindowInfo_t const*
std::size_t size () const
bool empty () const
auto begin () const
auto end () const
auto cbegin () const
auto cend () const
Detailed Description
Information about composition and topology of trigger sliding windows.
This class collects optical detector windows defined as a collection of channels, supposedly contiguous in space. A rudimentary topology is described with each window having upstream, downstream windows (with respect to the nominal beam direction) and a single opposite window.
The class exposes a minimal collection interface and is therefore iterable. Windows are identified by an index that matches their position in the collection.
This is just a data structure, and algorithms building the composition and topology of the windows are not part of it.
Definition at line 53 of file WindowChannelMap.h.
Member Typedef Documentation
pointer_type
using icarus::trigger::WindowChannelMap::pointer_type = WindowInfo_t const*
Definition at line 151 of file WindowChannelMap.h.
reference_type
using icarus::trigger::WindowChannelMap::reference_type = WindowInfo_t const&
Definition at line 150 of file WindowChannelMap.h.
value_type
using icarus::trigger::WindowChannelMap::value_type = WindowInfo_t
Definition at line 149 of file WindowChannelMap.h.
WindowIndex_t
using icarus::trigger::WindowChannelMap::WindowIndex_t = std::size_t
Type of window index.
Definition at line 57 of file WindowChannelMap.h.
Constructor & Destructor Documentation
WindowChannelMap()
icarus::trigger::WindowChannelMap::WindowChannelMap (std::vector< WindowInfo_t > && windows) inline explicit
Construction: moves the windows information into the map.
Definition at line 117 of file WindowChannelMap.h.
Member Function Documentation
begin()
auto icarus::trigger::WindowChannelMap::begin () const inline
Definition at line 155 of file WindowChannelMap.h.
cbegin()
auto icarus::trigger::WindowChannelMap::cbegin () const inline
Definition at line 157 of file WindowChannelMap.h.
cend()
auto icarus::trigger::WindowChannelMap::cend () const inline
Definition at line 158 of file WindowChannelMap.h.
dump() [1/2]
void icarus::trigger::WindowChannelMap::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const
Prints the content of the full mapping.
Definition at line 43 of file WindowChannelMap.cxx.
References icarus::trigger::WindowChannelMap::WindowInfo_t::dump(), info(), and nWindows().
dump() [2/2]
void icarus::trigger::WindowChannelMap::dump (std::ostream & out, std::string const & indent = "") const inline
Definition at line 141 of file WindowChannelMap.h.
empty()
bool icarus::trigger::WindowChannelMap::empty () const inline
Definition at line 154 of file WindowChannelMap.h.
end()
auto icarus::trigger::WindowChannelMap::end () const inline
Definition at line 156 of file WindowChannelMap.h.
hasWindow()
bool icarus::trigger::WindowChannelMap::hasWindow (WindowIndex_t index) const inline
Returns whether a window with the specified index is present.
Definition at line 128 of file WindowChannelMap.h.
References nWindows().
info()
WindowInfo_t const & icarus::trigger::WindowChannelMap::info (WindowIndex_t index) const inline
Returns the information for the window with specified index (unchecked).
Definition at line 131 of file WindowChannelMap.h.
Referenced by dump().
isValidWindow()
static bool icarus::trigger::WindowChannelMap::isValidWindow (WindowIndex_t index) inline static
Returns whether the specified index is not the invalid window index.
Definition at line 163 of file WindowChannelMap.h.
References InvalidWindowIndex.
Referenced by icarus::trigger::WindowChannelMap::WindowTopology_t::hasDownstreamWindow(), icarus::trigger::WindowChannelMap::WindowTopology_t::hasOppositeWindow(), and icarus::trigger::WindowChannelMap::WindowTopology_t::hasUpstreamWindow().
nWindows()
std::size_t icarus::trigger::WindowChannelMap::nWindows () const inline
Number of sliding windows.
Definition at line 125 of file WindowChannelMap.h.
Referenced by dump(), and hasWindow().
size()
std::size_t icarus::trigger::WindowChannelMap::size () const inline
Definition at line 153 of file WindowChannelMap.h.
Member Data Documentation
fWindows
std::vector<WindowInfo_t> icarus::trigger::WindowChannelMap::fWindows private
Definition at line 168 of file WindowChannelMap.h.
InvalidWindowIndex
const WindowIndex_t icarus::trigger::WindowChannelMap::InvalidWindowIndex = std::numeric_limits<WindowIndex_t>::max() static
Special index denoting an invalid window.
Definition at line 60 of file WindowChannelMap.h.
Referenced by isValidWindow().
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/WindowChannelMap.cxx