CAF format: icarus::AnalysisTree Class Reference
icarus::AnalysisTree Class Reference
Creates a simple ROOT tree with tracking and calorimetry information.
Public Member Functions
AnalysisTree (fhicl::ParameterSet const &pset)
void analyze (const art::Event &evt)
read access to event
void beginSubRun (const art::SubRun &sr)
Private Member Functions
void HitsPurity (detinfo::DetectorClocksData const &clockData, std::vector< art::Ptr< recob::Hit > > const &hits, Int_t &trackid, Float_t &purity, double &maxe)
double length (const recob::Track &track)
double length (const simb::MCParticle &part, TVector3 &start, TVector3 &end)
double bdist (const recob::tracking::Point_t &pos)
size_t GetNTrackers () const
Returns the number of trackers configured.
void CreateData (bool bClearData=false)
Creates the structure for the tree data; optionally initializes it.
void SetAddresses ()
Sets the addresses of all the tree branches, creating the missing ones.
void SetTrackerAddresses (size_t iTracker)
void CreateTree (bool bClearData=false)
Create the output tree and the data structures, if needed.
void DestroyData ()
Destroy the local buffers (existing branches will point to invalid address!)
void CheckData (std::string caller) const
Helper function: throws if no data structure is available.
void CheckTree (std::string caller) const
Helper function: throws if no tree is available.
Private Attributes
TTree * fTree
AnalysisTreeDataStruct * fData
AnalysisTreeDataStruct::SubRunData_t SubRunData
std::string fDigitModuleLabel
std::string fHitsModuleLabel
std::string fLArG4ModuleLabel
std::string fCalDataModuleLabel
std::string fGenieGenModuleLabel
std::string fCryGenModuleLabel
std::string fG4ModuleLabel
std::string fVertexModuleLabel
std::vector< std::string > fTrackModuleLabel
std::vector< std::string > fCalorimetryModuleLabel
std::vector< std::string > fParticleIDModuleLabel
std::string fPOTModuleLabel
bool fUseBuffer
whether to use a permanent buffer (faster, huge memory)
bool fSaveAuxDetInfo
whether to extract and save auxiliary detector data
bool fSaveCryInfo
bool fSaveGenieInfo
whether to extract and save CRY particle data
bool fSaveGeantInfo
whether to extract and save Genie information
bool fSaveHitInfo
whether to extract and save Geant information
bool fSaveTrackInfo
whether to extract and save Hit information
bool fSaveVertexInfo
whether to extract and save Track information
std::vector< std::string > fCosmicTaggerAssocLabel
whether to extract and save Vertex information
std::vector< std::string > fFlashMatchAssocLabel
bool isCosmics
if it contains cosmics
bool fSaveCaloCosmics
save calorimetry information for cosmics
float fG4minE
Detailed Description
Creates a simple ROOT tree with tracking and calorimetry information.
Configuration parameters
UseBuffers (default: false): if enabled, memory is allocated for tree data for all the run; otherwise, it's allocated on each event, used and freed; use "true" for speed, "false" to save memory
SaveAuxDetInfo (default: false): if enabled, auxiliary detector data will be extracted and included in the tree
Definition at line 670 of file AnalysisTree_module.cc.
Constructor & Destructor Documentation
AnalysisTree()
icarus::AnalysisTree::AnalysisTree (fhicl::ParameterSet const & pset) explicit
Definition at line 1661 of file AnalysisTree_module.cc.
~AnalysisTree()
icarus::AnalysisTree::~AnalysisTree () virtual
Definition at line 1713 of file AnalysisTree_module.cc.
Member Function Documentation
analyze()
void icarus::AnalysisTree::analyze (const art::Event & evt)
read access to event
transfer the run and subrun data to the tree data object
Definition at line 1741 of file AnalysisTree_module.cc.
bdist()
double icarus::AnalysisTree::bdist (const recob::tracking::Point_t & pos) private
Definition at line 2770 of file AnalysisTree_module.cc.
beginSubRun()
void icarus::AnalysisTree::beginSubRun (const art::SubRun & sr)
Definition at line 1728 of file AnalysisTree_module.cc.
CheckData()
void icarus::AnalysisTree::CheckData (std::string caller) const inline private
Helper function: throws if no data structure is available.
Definition at line 775 of file AnalysisTree_module.cc.
Referenced by SetAddresses(), and SetTrackerAddresses().
CheckTree()
void icarus::AnalysisTree::CheckTree (std::string caller) const inline private
Helper function: throws if no tree is available.
Definition at line 782 of file AnalysisTree_module.cc.
Referenced by SetAddresses(), and SetTrackerAddresses().
CreateData()
void icarus::AnalysisTree::CreateData (bool bClearData = false) inline private
Creates the structure for the tree data; optionally initializes it.
Definition at line 729 of file AnalysisTree_module.cc.
References icarus::AnalysisTreeDataStruct::Clear(), fSaveAuxDetInfo, fSaveGeantInfo, fSaveGenieInfo, fSaveHitInfo, fSaveTrackInfo, fSaveVertexInfo, GetNTrackers(), icarus::AnalysisTreeDataStruct::SetBits(), and icarus::AnalysisTreeDataStruct::SetTrackers().
CreateTree()
void icarus::AnalysisTree::CreateTree (bool bClearData = false) private
Create the output tree and the data structures, if needed.
Definition at line 1718 of file AnalysisTree_module.cc.
DestroyData()
void icarus::AnalysisTree::DestroyData () inline private
Destroy the local buffers (existing branches will point to invalid address!)
Definition at line 772 of file AnalysisTree_module.cc.
GetNTrackers()
size_t icarus::AnalysisTree::GetNTrackers () const inline private
Returns the number of trackers configured.
Definition at line 726 of file AnalysisTree_module.cc.
Referenced by CreateData().
HitsPurity()
void icarus::AnalysisTree::HitsPurity (detinfo::DetectorClocksData const & clockData, std::vector< art::Ptr< recob::Hit > > const & hits, Int_t & trackid, Float_t & purity, double & maxe) private
Definition at line 2729 of file AnalysisTree_module.cc.
length() [1/2]
double icarus::AnalysisTree::length (const recob::Track & track) private
Definition at line 2829 of file AnalysisTree_module.cc.
length() [2/2]
double icarus::AnalysisTree::length (const simb::MCParticle & part, TVector3 & start, TVector3 & end) private
Definition at line 2835 of file AnalysisTree_module.cc.
SetAddresses()
void icarus::AnalysisTree::SetAddresses () inline private
Sets the addresses of all the tree branches, creating the missing ones.
Definition at line 748 of file AnalysisTree_module.cc.
References CheckData(), CheckTree(), isCosmics, and icarus::AnalysisTreeDataStruct::SetAddresses().
SetTrackerAddresses()
void icarus::AnalysisTree::SetTrackerAddresses (size_t iTracker) inline private
Sets the addresses of all the tree branches of the specified tracking algo, creating the missing ones
Definition at line 756 of file AnalysisTree_module.cc.
References CheckData(), CheckTree(), icarus::AnalysisTreeDataStruct::GetNTrackers(), and isCosmics.
Member Data Documentation
fCalDataModuleLabel
std::string icarus::AnalysisTree::fCalDataModuleLabel private
Definition at line 701 of file AnalysisTree_module.cc.
fCalorimetryModuleLabel
std::vector<std::string> icarus::AnalysisTree::fCalorimetryModuleLabel private
Definition at line 707 of file AnalysisTree_module.cc.
fCosmicTaggerAssocLabel
std::vector<std::string> icarus::AnalysisTree::fCosmicTaggerAssocLabel private
whether to extract and save Vertex information
Definition at line 719 of file AnalysisTree_module.cc.
fCryGenModuleLabel
std::string icarus::AnalysisTree::fCryGenModuleLabel private
Definition at line 703 of file AnalysisTree_module.cc.
fData
AnalysisTreeDataStruct* icarus::AnalysisTree::fData private
Definition at line 694 of file AnalysisTree_module.cc.
fDigitModuleLabel
std::string icarus::AnalysisTree::fDigitModuleLabel private
Definition at line 698 of file AnalysisTree_module.cc.
fFlashMatchAssocLabel
std::vector<std::string> icarus::AnalysisTree::fFlashMatchAssocLabel private
Definition at line 720 of file AnalysisTree_module.cc.
fG4minE
float icarus::AnalysisTree::fG4minE private
Energy threshold to save g4 particle info
Definition at line 724 of file AnalysisTree_module.cc.
fG4ModuleLabel
std::string icarus::AnalysisTree::fG4ModuleLabel private
Definition at line 704 of file AnalysisTree_module.cc.
fGenieGenModuleLabel
std::string icarus::AnalysisTree::fGenieGenModuleLabel private
Definition at line 702 of file AnalysisTree_module.cc.
fHitsModuleLabel
std::string icarus::AnalysisTree::fHitsModuleLabel private
Definition at line 699 of file AnalysisTree_module.cc.
fLArG4ModuleLabel
std::string icarus::AnalysisTree::fLArG4ModuleLabel private
Definition at line 700 of file AnalysisTree_module.cc.
fParticleIDModuleLabel
std::vector<std::string> icarus::AnalysisTree::fParticleIDModuleLabel private
Definition at line 708 of file AnalysisTree_module.cc.
fPOTModuleLabel
std::string icarus::AnalysisTree::fPOTModuleLabel private
Definition at line 709 of file AnalysisTree_module.cc.
fSaveAuxDetInfo
bool icarus::AnalysisTree::fSaveAuxDetInfo private
whether to extract and save auxiliary detector data
Definition at line 711 of file AnalysisTree_module.cc.
Referenced by CreateData().
fSaveCaloCosmics
bool icarus::AnalysisTree::fSaveCaloCosmics private
save calorimetry information for cosmics
Definition at line 723 of file AnalysisTree_module.cc.
fSaveCryInfo
bool icarus::AnalysisTree::fSaveCryInfo private
Definition at line 712 of file AnalysisTree_module.cc.
fSaveGeantInfo
bool icarus::AnalysisTree::fSaveGeantInfo private
whether to extract and save Genie information
Definition at line 714 of file AnalysisTree_module.cc.
Referenced by CreateData().
fSaveGenieInfo
bool icarus::AnalysisTree::fSaveGenieInfo private
whether to extract and save CRY particle data
Definition at line 713 of file AnalysisTree_module.cc.
Referenced by CreateData().
fSaveHitInfo
bool icarus::AnalysisTree::fSaveHitInfo private
whether to extract and save Geant information
Definition at line 715 of file AnalysisTree_module.cc.
Referenced by CreateData().
fSaveTrackInfo
bool icarus::AnalysisTree::fSaveTrackInfo private
whether to extract and save Hit information
Definition at line 716 of file AnalysisTree_module.cc.
Referenced by CreateData().
fSaveVertexInfo
bool icarus::AnalysisTree::fSaveVertexInfo private
whether to extract and save Track information
Definition at line 717 of file AnalysisTree_module.cc.
Referenced by CreateData().
fTrackModuleLabel
std::vector<std::string> icarus::AnalysisTree::fTrackModuleLabel private
Definition at line 706 of file AnalysisTree_module.cc.
fTree
TTree* icarus::AnalysisTree::fTree private
Definition at line 689 of file AnalysisTree_module.cc.
fUseBuffer
bool icarus::AnalysisTree::fUseBuffer private
whether to use a permanent buffer (faster, huge memory)
Definition at line 710 of file AnalysisTree_module.cc.
fVertexModuleLabel
std::string icarus::AnalysisTree::fVertexModuleLabel private
Definition at line 705 of file AnalysisTree_module.cc.
isCosmics
bool icarus::AnalysisTree::isCosmics private
if it contains cosmics
Definition at line 722 of file AnalysisTree_module.cc.
Referenced by SetAddresses(), and SetTrackerAddresses().
SubRunData
AnalysisTreeDataStruct::SubRunData_t icarus::AnalysisTree::SubRunData private
Definition at line 696 of file AnalysisTree_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Analysis/AnalysisTree_module.cc