CAF format: sbn::V1730Configuration Struct Reference
sbn::V1730Configuration Struct Reference
Class containing configuration for a V1730 board.
#include <V1730Configuration.h>
Public Member Functions
unsigned int preTriggerTicks () const
Ticks in the waveform before the trigger.
unsigned int postTriggerTicks () const
Ticks in the waveform after the trigger.
float bufferTime () const
Duration of the waveform [us].
float preTriggerTime () const
Time in the waveform before the trigger [us].
float postTriggerTime () const
Time in the waveform after the trigger [us].
bool operator== (V1730Configuration const &other) const
Comparison: all fields need to have the same values.
bool operator!= (V1730Configuration const &other) const
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent, unsigned int verbosity=MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, std::string const &indent="") const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, unsigned int verbosity, std::string const &indent="") const
Dumps the content of the configuration into out stream.
Static Public Member Functions
static float ticks2us (int ticks)
Convert a number of ticks into a time interval in microseconds.
Public Attributes
std::string boardName
Name (mnemonic) of the board.
unsigned int boardID = std::numeric_limits<unsigned int>::max()
Numeric ID of the board (board_id).
unsigned int fragmentID = std::numeric_limits<unsigned int>::max()
DAQ fragment ID.
unsigned int bufferLength = 0U
Ticks in each buffer (recordLength).
float postTriggerFrac = 0.0f
Fraction of the waveform after the trigger signal (postPercent).
unsigned int nChannels = 0U
Number of channels (nChannels).
bool useTimeTagForTimeStamp = false
Whether fragment timestamp is synchronised with server NTP and with TTT.
std::vector< sbn::V1730channelConfiguration > channels
Configuration of each channel.
Static Public Attributes
static constexpr unsigned int MaxDumpVerbosity = V1730channelConfiguration::MaxDumpVerbosity + 1U
Maximum supported verbosity level supported by dump().
static constexpr unsigned int DefaultDumpVerbosity = MaxDumpVerbosity
Default verbosity level for dump().
Detailed Description
Class containing configuration for a V1730 board.
This is an informative class containing configuration of a V1730 board extracted from some other source (typically, DAQ) made readily available to the users.
This class does not include any configuration extraction code.
The class is default-constructible only, and its content needs to be added element by element.
Definition at line 45 of file V1730Configuration.h.
Member Function Documentation
bufferTime()
float sbn::V1730Configuration::bufferTime () const inline
Duration of the waveform [us].
Definition at line 199 of file V1730Configuration.h.
Referenced by dump().
dump() [1/3]
void sbn::V1730Configuration::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent, unsigned int verbosity = MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation string
firstIndent special indentation string for the first line
verbosity (default: DefaultDumpVerbosity) level of verbosity
The indentation string is prepended to each new line of the dump. The first line indentation string is prepended before the first line of the dump. The dump ends on a new empty line.
The amount of information printed depends on the verbosity level:
0: name of the board, board and fragment ID, number of channels
1: waveform length and post-trigger fraction; also: information on each channel, one per line, as with V1730channelConfiguration::dump() with verbosity one level smaller than the value ofverbosityargument *2`: also setting of fragment timestamp
Definition at line 21 of file V1730Configuration.cxx.
References boardID, boardName, bufferLength, bufferTime(), channels, sbn::V1730channelConfiguration::dump(), fragmentID, MaxDumpVerbosity, nChannels, postTriggerFrac, postTriggerTime(), preTriggerTime(), and useTimeTagForTimeStamp.
Referenced by sbn::PMTconfiguration::dump(), dump(), and dump().
dump() [2/3]
void sbn::V1730Configuration::dump (std::ostream & out, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation level
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with same first indentation level as the rest, and default verbosity.
Definition at line 158 of file V1730Configuration.h.
References dump().
dump() [3/3]
void sbn::V1730Configuration::dump (std::ostream & out, unsigned int verbosity, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent (default: none) indentation string
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with the specified verbosity level and same first indentation level as the rest.
Definition at line 170 of file V1730Configuration.h.
References dump().
operator!=()
bool sbn::V1730Configuration::operator!= (V1730Configuration const & other) const inline
Definition at line 104 of file V1730Configuration.h.
operator==()
bool sbn::V1730Configuration::operator== (sbn::V1730Configuration const & other) const inline
Comparison: all fields need to have the same values.
Definition at line 214 of file V1730Configuration.h.
postTriggerTicks()
unsigned int sbn::V1730Configuration::postTriggerTicks () const inline
Ticks in the waveform after the trigger.
Definition at line 194 of file V1730Configuration.h.
postTriggerTime()
float sbn::V1730Configuration::postTriggerTime () const inline
Time in the waveform after the trigger [us].
Definition at line 209 of file V1730Configuration.h.
Referenced by dump().
preTriggerTicks()
unsigned int sbn::V1730Configuration::preTriggerTicks () const inline
Ticks in the waveform before the trigger.
Definition at line 189 of file V1730Configuration.h.
References bufferLength, and postTriggerFrac.
Referenced by icarus::PMTWaveformBaselinesFromChannelData::getPretriggerBuffer().
preTriggerTime()
float sbn::V1730Configuration::preTriggerTime () const inline
Time in the waveform before the trigger [us].
Definition at line 204 of file V1730Configuration.h.
Referenced by dump().
ticks2us()
static float sbn::V1730Configuration::ticks2us (int ticks) inline static
Convert a number of ticks into a time interval in microseconds.
Definition at line 180 of file V1730Configuration.h.
Member Data Documentation
boardID
unsigned int sbn::V1730Configuration::boardID = std::numeric_limits<unsigned int>::max()
Numeric ID of the board (board_id).
Definition at line 55 of file V1730Configuration.h.
Referenced by dump().
boardName
std::string sbn::V1730Configuration::boardName
Name (mnemonic) of the board.
Definition at line 52 of file V1730Configuration.h.
Referenced by dump(), icarus::PMTconfigurationExtractor::extractV1730configuration(), icarus::PMTconfigurationExtractor::finalize(), and icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup().
bufferLength
unsigned int sbn::V1730Configuration::bufferLength = 0U
Ticks in each buffer (recordLength).
Definition at line 61 of file V1730Configuration.h.
Referenced by dump(), icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup(), and preTriggerTicks().
channels
std::vector<sbn::V1730channelConfiguration> sbn::V1730Configuration::channels
Configuration of each channel.
Definition at line 73 of file V1730Configuration.h.
Referenced by dump(), icarus::PMTWaveformBaselinesFromReadoutConfiguration::extractBaselinesFromConfiguration(), icarus::PMTconfigurationExtractor::finalize(), and icarus::trigger::DiscriminatePMTwaveformsByChannel::refreshCurrentThresholds().
DefaultDumpVerbosity
unsigned int sbn::V1730Configuration::DefaultDumpVerbosity = MaxDumpVerbosity static constexpr
Default verbosity level for dump().
Definition at line 120 of file V1730Configuration.h.
fragmentID
unsigned int sbn::V1730Configuration::fragmentID = std::numeric_limits<unsigned int>::max()
DAQ fragment ID.
Definition at line 58 of file V1730Configuration.h.
Referenced by dump(), icarus::PMTconfigurationExtractor::finalize(), icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup(), and icarus::PMTconfigurationExtractor::readoutBoardDBfragmentID().
MaxDumpVerbosity
unsigned int sbn::V1730Configuration::MaxDumpVerbosity = V1730channelConfiguration::MaxDumpVerbosity + 1U static constexpr
Maximum supported verbosity level supported by dump().
Definition at line 116 of file V1730Configuration.h.
Referenced by dump().
nChannels
unsigned int sbn::V1730Configuration::nChannels = 0U
Number of channels (nChannels).
Definition at line 67 of file V1730Configuration.h.
Referenced by dump().
postTriggerFrac
float sbn::V1730Configuration::postTriggerFrac = 0.0f
Fraction of the waveform after the trigger signal (postPercent).
Definition at line 64 of file V1730Configuration.h.
Referenced by dump(), icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup(), and preTriggerTicks().
useTimeTagForTimeStamp
bool sbn::V1730Configuration::useTimeTagForTimeStamp = false
Whether fragment timestamp is synchronised with server NTP and with TTT.
Definition at line 70 of file V1730Configuration.h.
Referenced by dump().
The documentation for this struct was generated from the following files:
sbnobj/sbnobj/Common/PMT/Data/V1730Configuration.h
sbnobj/sbnobj/Common/PMT/Data/V1730Configuration.cxx