CAF format: icarus::DaqDecoderICARUSPMT Class Reference
icarus::DaqDecoderICARUSPMT Class Reference
Produces raw::OpDetWaveform from V1730 artDAQ data fragments.
Classes
struct BoardSetupConfig
Configuration of the V1730 readout board setup.
struct Config
Main module configuration.
struct FragmentInfo_t
Collection of useful information from fragment data.
struct NeededBoardInfo_t
Information used in decoding from a board.
struct ProtoWaveform_t
All the information collected about a waveform (with the waveform itself).
struct SplitTimestamp_t
Data structure for trigger time.
struct TreeData_EventID_t
Data structure for basic event information in simple ROOT trees.
struct TreeFragment_t
Structure collecting all data for a fragment ROOT tree.
struct TriggerInfo_t
Collection of information about the global trigger.
Public Types
using nanoseconds = util::quantities::intervals::nanoseconds
Alias.
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
DaqDecoderICARUSPMT (Parameters const &params)
Constructor.
void beginRun (art::Run &run) override
On a new run: cache PMT configuration information.
void produce (art::Event &event) override
Processes the event.
void endJob () override
Prints a end-of-job message.
Static Public Attributes
static constexpr electronics_time NoTimestamp = std::numeric_limits<electronics_time>::min()
Private Types
enum class DataTrees : std::size_t { Fragments , N }
Enumerate the supported data trees.
using TreeNameList_t = std::array<std::string, static_cast<std::size_t>(DataTrees::N)>
using AllChannelSetup_t = daq::details::BoardSetup_t::AllChannelSetup_t
Type of setup of all channels in a readout board.
using WaveformsByCategory_t = std::map<std::string, std::vector<raw::OpDetWaveform>>
Type of map: category to collection of waveforms under that category.
using BoardID_t = short int
Type used internally to represent board ID.
Private Member Functions
bool hasPMTconfiguration () const
Returns whether PMT configuration information is expected to be available.
bool UpdatePMTConfiguration (sbn::PMTconfiguration const *PMTconfig)
Updates the PMT configuration cache. How? Dunno. Placeholder.
daq::details::BoardInfoLookup matchBoardConfigurationAndSetup (sbn::PMTconfiguration const *PMTconfig) const
Returns a lookup object with board setup and configuration info.
NeededBoardInfo_t fetchNeededBoardInfo (daq::details::BoardInfoLookup::BoardInfo_t const *boardInfo, unsigned int fragmentID) const
Puts together all the needed information for a board.
TriggerInfo_t fetchTriggerTimestamp (art::Event const &event) const
Retrieves the global trigger time stamp from the event.
electronics_time fragmentWaveformTimestamp (FragmentInfo_t const &fragInfo, NeededBoardInfo_t const &boardInfo, SplitTimestamp_t triggerTime) const
Returns the timestamp for the waveforms in the specified fragment.
electronics_time fragmentWaveformTimestampOnTrigger (FragmentInfo_t const &fragInfo, NeededBoardInfo_t const &boardInfo, SplitTimestamp_t triggerTime) const
Returns the timestamp for the waveforms in the specified fragment.
electronics_time fragmentWaveformTimestampFromTTT (FragmentInfo_t const &fragInfo, NeededBoardInfo_t const &boardInfo, SplitTimestamp_t triggerTime) const
Returns the timestamp for the waveforms in the specified fragment.
artdaq::Fragments const & readInputFragments (art::Event const &event) const
Reads the fragments to be processed.
void checkFragmentType (artdaq::Fragment const &artdaqFragment) const
Throws an exception if artdaqFragment is not of type CAEN1730.
artdaq::FragmentPtrs makeFragmentCollection (artdaq::Fragment const &sourceFragment) const
artdaq::FragmentPtrs makeFragmentCollectionFromFragment (artdaq::Fragment const &sourceFragment) const
Converts a plain fragment into a fragment collection.
artdaq::FragmentPtrs makeFragmentCollectionFromContainerFragment (artdaq::Fragment const &sourceFragment) const
Converts a container fragment into a fragment collection.
std::vector< ProtoWaveform_t > processBoardFragments (artdaq::FragmentPtrs const &artdaqFragment, TriggerInfo_t const &triggerInfo)
Extracts waveforms from the specified fragments from a board.
unsigned int mergeWaveforms (std::vector< ProtoWaveform_t > &waveforms) const
void sortWaveforms (std::vector< ProtoWaveform_t > &waveforms) const
Sorts in place the specified waveforms in channel order, then in time.
std::vector< ProtoWaveform_t const * > findWaveformsWithNominalTrigger (std::vector< ProtoWaveform_t > const &waveforms) const
Returns pointers to all waveforms including the nominal trigger time.
bool containsGlobalTrigger (raw::OpDetWaveform const &waveform) const
Returns whether waveform includes the tick of the nominal trigger time.
bool containsGlobalTrigger (electronics_time time, std::size_t nTicks) const
Returns whether nominal trigger time is within nTicks from time.
ProtoWaveform_t mergeWaveformGroup (std::vector< ProtoWaveform_t > &allWaveforms, std::vector< std::size_t > const &indices) const
std::vector< sbn::OpDetWaveformMeta > createWaveformMetadata (std::vector< raw::OpDetWaveform > const &waveforms, TriggerInfo_t const &triggerInfo) const
Creates and returns waveform metadata.
art::Assns< raw::OpDetWaveform, sbn::OpDetWaveformMeta > createWaveformMetadataAssociations (std::vector< raw::OpDetWaveform > const &waveforms, art::Event const &event, std::string const &instanceName="") const
Creates and returns waveform metadata associations.
electronics_time waveformStartTime (raw::OpDetWaveform const &wf) const
electronics_time waveformStartTime (ProtoWaveform_t const &wf) const
electronics_time waveformEndTime (raw::OpDetWaveform const &wf) const
electronics_time waveformEndTime (ProtoWaveform_t const &wf) const
WaveformsByCategory_t prepareOutputWaveforms (std::vector< ProtoWaveform_t > &&protoWaveforms, std::vector< icarus::timing::PMTWaveformTimeCorrection > const *timeCorrections) const
Converts the proto-waveforms into the final waveforms to be saved.
std::pair< std::vector< sbn::OpDetWaveformMeta >, art::Assns< raw::OpDetWaveform, sbn::OpDetWaveformMeta > > createRegularWaveformMetadata (WaveformsByCategory_t const &waveformProducts, art::Event const &event, TriggerInfo_t const &triggerInfo) const
Creates metadata and associations (if needed) for the regular waveforms.
double extractTimeCorrection (raw::OpDetWaveform const &waveform, std::vector< icarus::timing::PMTWaveformTimeCorrection > const *corrections) const
Returns time correction appropriate for waveform.
std::vector< ProtoWaveform_t > processFragment (artdaq::Fragment const &artdaqFragment, NeededBoardInfo_t const &boardInfo, TriggerInfo_t const &triggerInfo)
Create waveforms and fills trees for the specified artDAQ fragment.
std::vector< ProtoWaveform_t > createFragmentWaveforms (FragmentInfo_t const &fragInfo, AllChannelSetup_t const &channelSetup, electronics_time const timeStamp) const
Creates raw::OpDetWaveform objects from the fragment data.
FragmentInfo_t extractFragmentInfo (artdaq::Fragment const &artdaqFragment) const
Extracts useful information from fragment data.
NeededBoardInfo_t neededBoardInfo (artdaq::Fragment::fragment_id_t fragment_id) const
Returns the board information for this fragment.
std::vector< std::string > getAllInstanceNames () const
Returns all the instance names we will produce.
void checkBoardSetup (std::vector< daq::details::BoardSetup_t > const &allBoardSetup) const
Throws an exception if the configuration of boards shows errors.
void usesEventInfo ()
Declares the use of event information.
void initTrees (std::vector< std::string > const &treeNames)
Initializes all requested data trees.
void initEventIDtree (TTree &tree, TreeData_EventID_t &data)
Initializes the event ID part of a tree.
void initFragmentsTree ()
Initializes the fragment data tree (fTreeFragment).
void fillTreeEventID (art::Event const &event, TreeData_EventID_t &treeData) const
Fills the base information of a tree data entry from an art event.
void assignEventInfo (TreeData_EventID_t &treeData) const
Assigns the cached event information to the specified tree data.
void fillPMTfragmentTree (FragmentInfo_t const &fragInfo, TriggerInfo_t const &triggerInfo, electronics_time waveformTimestamp)
Static Private Member Functions
static std::string listTreeNames (std::string const &sep="\n")
Returns a string with all supported tree names.
static unsigned int extractTriggerTimeTag (artdaq::Fragment const &fragment)
Extracts the Trigger Time Tag (31+1 bits) value from the fragment.
template<std::size_t NBits, typename T >
static constexpr std::pair< std::array< std::size_t, NBits >, std::size_t > setBitIndices (T value) noexcept
Returns the count of set bits for each set bit.
static long long int timestampDiff (std::uint64_t a, std::uint64_t b)
Returns the timestamp difference a - b.
static constexpr std::size_t effectivePMTboardFragmentID (artdaq::Fragment::fragment_id_t id)
Returns the fragment ID to be used with databases.
static BoardID_t extractFragmentBoardID (artdaq::Fragment const &fragment)
Extracts the fragment ID (i.e. board ID) from the specified fragment.
static std::string const & treeName (DataTrees treeID)
Returns the name of the specified tree.
static TreeNameList_t initTreeNames ()
Static initialization.
Private Attributes
std::vector< art::InputTag > const fInputTags
< List of candidate data products with artDAQ data fragments.
bool const fSurviveExceptions
Whether to "ignore" errors.
bool const fDiagnosticOutput
If true will spew endless messages to output.
bool const fPacketDump
Dump V1730 data.
bool const fRequireKnownBoards
Whether info on all input boards is required.
bool const fRequireBoardConfig
Whether setup info on all boards is required.
std::string const fCorrectionInstance
String of the instance to use for the time corrections.
bool const fApplyCableDelayCorrection
Whether to apply cable delay corrections.
std::optional< art::InputTag > const fPMTconfigTag
Input tag of the PMT configuration.
std::optional< art::InputTag > const fTriggerTag
Input tag of the global trigger.
bool const fTTTresetEverySecond
Whether V1730 TTT is reset every second.
std::vector< daq::details::BoardSetup_t > const fBoardSetup
All board setup settings.
std::vector< std::string > fSaveWaveformsFrom
List of waveform categories to save.
std::vector< std::string > fSaveCorrectionsFrom
List of correction categories to save.
bool const fDropRawDataAfterUse
Clear fragment data product cache after use.
std::string const fLogCategory
Message facility category.
detinfo::DetectorTimings const fDetTimings
Interface to LArSoft configuration for detector timing.
icarusDB::IICARUSChannelMap const & fChannelMap
Fragment/channel mapping database.
icarusDB::PMTTimingCorrections const *const fPMTTimingCorrectionsService
The online PMT corrections service provider.
icarus::timing::PMTWaveformTimeCorrectionExtractor const fPMTWaveformTimeCorrectionManager
nanoseconds const fOpticalTick
Duration of the optical detector readout sampling tick (i.e. 2 ns; hush!).
electronics_time const fNominalTriggerTime
Trigger time as reported by detinfo::DetectorClocks service.
bool const fSaveRegularWaveforms
Whether regular waveforms are saved.
std::optional< daq::details::BoardInfoLookup > fBoardInfoLookup
Find the information on a readout boards by fragment ID.
unsigned int fNFailures = 0U
Number of event failures encountered.
std::unique_ptr< TreeData_EventID_t > fEventInfo
Event ID for trees.
std::unique_ptr< TreeFragment_t > fTreeFragment
util::ArtHandleTrackerManager< art::Event > fDataCacheRemover
Tracks art data products and removes their cached data on demand.
Static Private Attributes
static TreeNameList_t const TreeNames = icarus::DaqDecoderICARUSPMT::initTreeNames()
static std::string const RegularWaveformCategory { "" }
Instance name associated to the regular PMT waveforms.
Friends
struct dumpChannel
std::ostream & operator<< (std::ostream &, ProtoWaveform_t const &)
Detailed Description
Produces raw::OpDetWaveform from V1730 artDAQ data fragments.
The module can read fragments from CAEN V1730 readout boards delivered by artDAQ. It produces optical detector waveforms in LArSoft standards.
This decoder must support both a off-line mode (for storage and downstream processing) and a on-line mode (for monitoring). In particular, the on-line workflow is such that it may not be possible to access the FHiCL configuration of the job and therefore the PMT configuration data (see icarus::PMTconfigurationExtraction module).
Configuration
The set of supported parameters can be seen on command line by running lar --print-description DaqDecoderICARUSPMT.
Description of the configuration parameters:
FragmentsLabels (list of input tags): a list of possible input data products. A valid input data product contain a list of fragments from V1730. All input tags are tried. If only one is available, its content is used for decoding; otherwise, an exception is thrown.
DiagnosticOutput (flag, default: false): enables additional console output, including dumping of the fragments (that is huge output).
PMTconfigTag (data product tag, optional): if specified, the pre-trigger buffer duration is read from there; although optional, it is strongly recommended that this information be provided, since it is essential for the correct timing of the PMT waveforms (see the discussion on time stamps below).
BoardSetup (list of board setup information): each entry specifies some information about a specific readout board; the boards are identified by their name; if a board is found in input that has no setup information, some time corrections are not applied (see the discussion on time stamps below). Each entry is in the form of a table:
Name (string, mandatory): the name of the board (e.g. "icaruspmtwwtop01"); this is use to match the setup information to a fragment ID in the PMT configuration.
FragmentID (integral, optional): if specified, allows the corrections using setup information to be applied even when no PMT configuration is provided (if neither PMT configuration nor setup information including FragmentID is available, no time correction is applied).
TriggerDelay (nanoseconds, default: 0 ns): measured delay from the primitive trigger time to the execution of the PMT trigger; specify the unit! (e.g. "43 ns").
SpecialChannels (list of configurations): each entry described special features and settings of a specific channel, identified by its V1730B board channel number (0 to 15). The supported keys are:
ChannelIndex (integer, mandatory) the index of the channel in the board, from 0 to 15; note that for this module to decode this channel index, the channel itself must be enabled on the readout board.
Skip (flag, optional): if specified, tells whether to always skip this channel or whether always store it. If not specified, a channel will be always stored unless it is not associated to any channel number (see Channel below). Note that if the channel is not enabled in the readout board, this option has no effect.
OnlyOnGlobalTrigger (flag, default: false): if set, waveforms are saved from this channel only when it includes the global trigger time; if no trigger time is available, such channels will never be saved.
MinSpan (integer, default: 0): waveforms which have a span (highest sample minus lowest sample) smaller than this limit are not saved (unless Skip is set to false).
Channel (integral, optional): if specified, it overrides the channel number used for the waveforms on this channel; if not specified, the channel number is obtained from the channel mapping database. Note that insisting to save a waveform without an assigned channel number (from database or from this configuration) will trigger an exception.
InstanceName (string, default: empty): the waveform will be stored in a collection of raw::OpDetWaveform with the specified instance name; the default is an empty name, which is the standard data product where all the normal waveforms are saved.
RequireKnownBoards (flag, default: true): if set, the readout boards in input must each have a setup configuration (BoardSetup) and must be present in the PMT DAQ configuration, or an exception is thrown; if not set, readout boards in input will be processed even when their setup or DAQ configuration is not known, at the cost of fewer corrections on the timestamps (which should then be considered unreliable).
RequireBoardConfig (flag, default: true): if set, the readout boards which have a setup (BoardSetup) are required to be included in the DAQ configuration of the input file, or an exception is thrown; if not set, missing readout boards are unnoticed.
TriggerTag (data product tag): tag for the information (sbn::ExtraTriggerInfo, produced by trigger decoding); if not specified, the art event timestamp will be used as trigger time (not recommended).
TTTresetEverySecond (optional): if set, the decoder will take advantage of the assumption that the Trigger Time Tag of all PMT readout boards is synchronised with the global trigger time and reset at every change of second of the timescale of the latter; this is currently the only implementation supporting multiple PMT readout windows on the same board; if this option is set to false, all PMT readout boards are assumed to have been triggered at the time of the global trigger. By default, this option is set to true unless TriggerTag is specified empty.
CorrectionInstance (string, default: empty): the category name of the waveforms to use for timing correction. Categories are defined in the BoardSetup configuration (each instance name, InstanceName, defines also a category). If empty, no waveform-based timing correction is used.
ApplyCableDelayCorrection (flag, default: true): if set, applies the cable delay corrections from a database.
DataTrees (list of strings, default: none): list of data trees to be produced; if none (default), then TFileService is not required.
SkipWaveforms (flag, default: false) if set, waveforms won't be produced; this is intended as a debugging option for jobs where only the DataTrees are desired.
SaveWaveformsFrom (list of categories, default: all): which categories of waveforms to save. The "regular" waveforms have an empty category name, while the "special" waveforms have the category name defined by the InstanceName parameter in the BoardSetup configuration above. If not specified, all waveforms from all categories are saved. If an empty list is specified, no waveform is saved at all.
SaveCorrectionsFrom (list of categories, default: only the used one): time corrections may be extracted from the "special" waveforms (see Further time corrections below); this parameter determines which of them are saved as stand-alone data products (only one at most is applied to waveforms though: see CorrectionInstance configuration parameter).
DropRawDataAfterUse (flag, default: true): at the end of processing, the framework will be asked to remove the PMT data fragment from memory. Set this to false in the unlikely case where raw PMT fragments are still needed after decoding.
LogCategory (string, default: DaqDecoderICARUSPMT): name of the message facility category where the output is sent.
Requirements
Services required include:
IICARUSChannelMap for the association of fragments to LArSoft channel ID;
DetectorClocksService for the correct decoding of the time stamps (always required, even when dumbed-down timestamp decoding is requested);
IPMTTimingCorrectionService for the cable delay timing corrections (if ApplyCableDelayCorrection is set);
TFileService only if the production of trees or plots is requested.
Output data products
std::vector<raw::OpDetWaveform> (empty instance name): decoded waveforms from the "regular" PMT channels. Produced only if SkipWaveforms is false.
std::vector<raw::OpDetWaveform> (non-empty instance name): decoded waveforms from the special PMT channels as configured in BoardSetup. Produced only if SkipWaveforms is false.
std::vector<sbn::OpDetWaveformMeta>: for regular waveforms, metadata of each produced waveform (in the same order).
art::Assns<raw::OpDetWaveform, sbn::OpDetWaveformMeta>: for regular waveforms, association with its metadata object (also in same order). Produced only if SkipWaveforms is false.
std::vector<icarus::timing::PMTWaveformTimeCorrection> (one instance name per correction source): list of time corrections from the specific source, one per (regular) PMT channel. If SaveCorrectionsFrom is specified it defines which corrections are saved; if it's not specified, only the correction from CorrectionInstance is saved, if any (otherwise, this data product is not saved at all).
Waveform time stamp
All waveforms on the same readout board fragment share the same timestamp. The same readout board can produce different fragments at different times within an event in which case each fragment will be independently assigned a timestamp .
The time stamp of the waveform is defined as the time when the first sample of the waveform started (that is, if the sample represent the value of the signal in an interval of 2 ns, the time stamp is pointing at the beginning of those 2 ns). Whether we can honour that definition, though, is a different matter. The representation of the time stamp is in the electronics time scale.
Waveforms all originate from a trigger primitive signal being sent to the readout boards by NI7820 FPGA to start the acquisition of the waveform. One of these primitives matches the global event trigger, but the corresponding fragment is not treated in any special way. Every delay between when that signal is emitted and when the PMT trigger is executed shifts the timestamp of the waveform backward.
We assign the the time stamp of the waveforms as follow:
the base time is the global trigger time; the global trigger time is read from the trigger data, where it is stored as an absolute time in TAI scale; the global trigger time itself effectively defines the electronics time scale used within a art event, so its representation is a fixed number that is configured in LArSoft and can be accessed with DetectorClocksData::TriggerTime();
each V1730 data fragment comes with a time tag ("TTT") describing the time of the end of the readout buffer (unknown whether the start or the end of the tick of the last sample). This tag is a counter internal to the V1730 board, incremented every 8 ns. The counter is reset at the beginning of every "new" TAI second, and it can thus be easily transformed into a time in the same TAI scale as the global trigger; the difference between TTT and the global trigger pins down the end of the readout buffer in the electronics time scale;
a delay is subtracted to the timestamp, which encompasses all fixed delays occurring in the trigger signal transportation; the most prominent is the delay occurring between the start of the "new" TAI second and when the TTT reset signal reaches and is honoured by the readout board. This value must be independently measured and provided to this decoder via configuration as setup information (TTTresetDelay); if not present in the setup, this delay is not added;
finally, the time of the beginning of the waveform, that is the target for raw::OpDetWaveform timestamp, is obtained from the time of its end by simply subtracting the readout buffer length.
A special decoding mode, hoped to be just historical by now, does not rely on the global trigger time. This mode can be safely used only when the (only) data fragment was triggered by the global trigger (e.g. in the simplest minimum/zero bias trigger). It has the advantage that it does not use the TTT information. It can be enabled explicitly by setting the option TTTresetEverySecond to true, or by removing the specification of the trigger time data product tag (TriggerTag).
The trigger primitive time is assumed to be the global trigger time too, so that the trigger primitive time in electronics time also matches the global trigger time.
upon receiving the trigger primitive signal, the readout board will keep some of the samples already digitized, in what we call pre-trigger buffer; the size of this buffer is a fixed number of samples which is specified in DAQ as a fraction of the complete buffer that is post-trigger; this amount, converted in time, is subtracted to the trigger time to point back to the beginning of the waveform instead that to the trigger primitive time. The necessary information is read from the PMT configuration (PMTconfigTag); if no configuration is available, this offset is not subtracted; note that this is a major shift (typically, a few microseconds) that should be always included. This step is equivalent to the step (4) of the regular mode, where here the adjustment starts from the trigger primitive time instead than from the end-of-buffer time.
a delay is subtracted to the timestamp, which encompasses all fixed delays occurring in the trigger signal transportation; one component of it is the relative delay in the propagation of the trigger primitive signal from a board to the next (in fact, every three boards have the trigger signal in daisy chain). This value must be independently measured and provided to this decoder via configuration as setup information (TriggerDelay); if not present in the setup, this delay is not added. Note that the particular contribution of the daisy chain to the delay does not need to be explicitly taken into account in the main mode, because the TTT reset is independent and not daisy-chained, so that the TTT times are all synchronized and when the primitive trigger arrives (via daisy chain) the TTT value at that instant is already including the delay.
Further time corrections
Time corrections are also applied for cable delays unless ApplyCableDelayCorrection is unset. These corrections are learned via IPMTTimingCorrectionService service.
Also, a timing correction can be applied to the waveforms based on a special waveform digitizing a trigger signal. The correction is the same for all the channels sharing the trigger signal, and more precisely, for all the channels in the same readout crate (which have the trigger signal propagate in chain from one to the next). The algorithm used to extract the correction from the special waveforms is icarus::timing::PMTWaveformTimeCorrectionExtractor. The decoder allows the extraction and saving of corrections from different types ("categories", as defined in the BoardSetup configuration) of special waveforms (see SaveCorrectionsFrom), but only the correction from a single category, chosen by CorrectionInstance, are applied to all the "standard" waveforms. Special waveforms have their time not corrected.
Data trees
The module supports the following ROOT trees production on demand:
PMTfragments: data pertaining a single fragment; each entry is about a single fragment, and it includes full event ID, event time stamp (from art, i.e. the one assigned to the event by artDAQ), the ID of the fragment the entry is describing, and then the rest of the data, including:
TTT (64-bit integer): (Extended) Trigger Time Tag value, in readout board ticks (each worth 8 ns) from the last board reset; currently the value includes the 31-bit counter and in addition the overflow bit as MSB; the overflow bit is set by the readout board the first time the counter passes its limit (2^31) and wraps, and never cleared until the next board reset. While the tree has room for the 48-bit version (ETTT), the rest of the decoder does not yet support it.
trigger (64-bit signed integer): global trigger time (from the trigger decoder), in nanoseconds from The Epoch.
triggerSec, triggerNS (32-bit integer each): same time as trigger branch, split into second and nanosecond components.
relBeamGateNS, (32-bit integer): beam gate time opening relative to the trigger time, in nanoseconds.
relEnableGateNS, (32-bit integer): enable gate time opening relative to the beam gate time, in nanoseconds. If larger than 2.1 seconds (\(\pm 2^{31}\) ns), it is capped. branch, split into second and nanosecond components.
fragTime (64-bit signed integer), fragTimeSec (32-bit signed integer): the timestamp of the PMT fragment, assigned by the board reader constructing the fragment.
fragCount (unsigned integer): the counter of the fragment within a readout board (its "event counter").
waveformTime (double): time assigned to the waveforms from this fragment (electronics time scale).
waveformSize (unsigned integer): number of ticks for the waveforms from this fragment.
triggerBits (unsigned integer): bits from the raw::Trigger.
triggerSource (unsigned integer): value of the trigger source bit (from sbn::ExtraTriggerInfo::triggerSource; see sbn::bits::triggerSource).
triggerLocation (unsigned integer): value of the trigger location bit (from sbn::ExtraTriggerInfo::triggerLocationBits; see sbn::bits::triggerLocation).
triggerLogicE, triggerLogicW (unsigned integer): value of the trigger logic bits (from sbn::ExtraTriggerInfo::triggerLogicBits; see sbn::bits::triggerLogic) for the two cryostats; 0 if there was no trigger in the respective cryostat.
gateID (unsigned integer): number of this gate from run start (note: this used to be gateCount until around v09_80_00).
triggerCount (unsigned integer): number of triggers from this source since run start, including this one; from sbn::ExtraTriggerInfo::triggerCount.
gateCount (unsigned integer): number of gates from this trigger source since run start, including this one (note: this used to be the number of all gates regardless the source until around v09_80_00).
gateCountFromPreviousTrigger (unsigned integer): number of gates from this trigger source since the previous trigger also from this trigger source (from sbn::ExtraTriggerInfo::gateCountFromPreviousTrigger).
onGlobalTrigger (boolean): whether the waveform covers the nominal trigger time (which should be equivalent to whether the fragment was triggered by the global trigger).
minimumBias (boolean): whether the event was triggered via minimum bias selection.
Technical notes
In order to correctly reconstruct the time stamp, this module needs several pieces of information. These include the size of the pre-trigger buffer, which is set by the readout board configuration, and the delay either between the start of the "new" second and the execution of the TTT reset, or between the global trigger and the time that trigger is received and acted upon in the readout board, depending of the time stamping mode; in both cases, the delays need to be measured. The first category of information, from readout board configuration, are read from the input file (sbn::PMTconfiguration), while the second category needs to be specified in the module FHiCL configuration.
PMT configuration is optional, in the sense that it can be omitted; in that case, some standard values will be used for it. This kind of setup may be good for monitoring, but it does not meet the requirements for physics analyses. For a board to be served, an entry of that board must be present in the module configuration (BoardSetup). It is an error for a fragment in input not to have an entry for the corresponding board setup.
The module extracts the needed information and matches it into a sort-of-database keyed by fragment ID, so that it can be quickly applied when decoding a fragment. The matching is performed by board name.
Proto-waveforms
The module has grown complex enough that some decisions need to be taken much later after a waveform is created, but using information available only during the creation. For example, a waveform can be ultimately routed to a different data product depending on which readout board it comes from, but that information is lost by the time the waveform needs to be written. Rather than attempting to recreate that information, it is saved when still available and travels together with the waveform itself in a data structure called "proto-waveform". The extra-information is eventually discarded when putting the actual waveform into the art event.
Processing pipeline
Processing happens according to the following structure (in produce()):
pre-processing: currently nothing
processing of each board data independently: at this level, all the buffers from the 16 channels of a single board are processed together (processBoardFragments())
the configuration and parameters specific to this board are fetched
each data fragment is processed independently: at this level, data from all 16 channels at a given time are processed together, producing up to 16 proto-waveforms
merging of contiguous waveforms is performed
post-processing of proto-waveforms:
sorting by time (as opposed as roughly by channel, as they come)
conversion to data products and output
Glossary
setup, [PMT] configuration: this is jargon specific to this module. Information about a readout board can come from two sources: the "setup" is information included in the BoardSetup configuration list of this module; the "PMT configuration" is information included in the DAQ configuration that is delivered via PMTconfigTag.
TAI (International Atomic Time): a time standard defining a universal time with a precision higher than it will ever matter for ICARUS.
TTT: trigger time tag, from the V1730 event record (31 bits); may be:
ETTT: extended trigger time tag, from the V1730 event record (48 bits).
trigger delay: time point when a V1730 board processes a (PMT) trigger signal (and increments the TTT register) with respect to the time of the time stamp of the (SPEXi) global trigger that acquired the event.
Definition at line 505 of file DaqDecoderICARUSPMT_module.cc.
Class Documentation
icarus::DaqDecoderICARUSPMT::BoardSetupConfig
struct icarus::DaqDecoderICARUSPMT::BoardSetupConfig
Configuration of the V1730 readout board setup.
Definition at line 553 of file DaqDecoderICARUSPMT_module.cc.
Class Members
OptionalAtom< unsigned int > FragmentID
Atom< string > Name
OptionalSequence< Table< ChannelSetupConfig > > SpecialChannels
Atom< nanoseconds > TriggerDelay
Atom< nanoseconds > TTTresetDelay
icarus::DaqDecoderICARUSPMT::Config
struct icarus::DaqDecoderICARUSPMT::Config
Main module configuration.
Definition at line 636 of file DaqDecoderICARUSPMT_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< bool > ApplyCableDelayCorrection
Sequence< TableAs< BoardSetup_t, BoardSetupConfig > > BoardSetup
Atom< string > CorrectionInstance
Sequence< string > DataTrees
Atom< bool > DiagnosticOutput
Atom< bool > DropRawDataAfterUse
Sequence< InputTag > FragmentsLabels
Atom< string > LogCategory
Atom< bool > PacketDump
OptionalAtom< InputTag > PMTconfigTag
Atom< bool > RequireBoardConfig
Atom< bool > RequireKnownBoards
OptionalSequence< string > SaveCorrectionsFrom
OptionalSequence< string > SaveWaveformsFrom
Atom< bool > SurviveExceptions
OptionalAtom< InputTag > TriggerTag
OptionalAtom< bool > TTTresetEverySecond
icarus::DaqDecoderICARUSPMT::FragmentInfo_t
struct icarus::DaqDecoderICARUSPMT::FragmentInfo_t
Collection of useful information from fragment data.
Definition at line 778 of file DaqDecoderICARUSPMT_module.cc.
Class Members
uint16_t const * data = nullptr
uint16_t enabledChannels = 0U
unsigned int eventCounter = 0U
fragment_id_t fragmentID = std::numeric_limits<artdaq::Fragment::fragment_id_t>::max()
timestamp_t fragmentTimestamp
size_t nSamplesPerChannel = 0U
uint32_t TTT = 0U
icarus::DaqDecoderICARUSPMT::TreeFragment_t
struct icarus::DaqDecoderICARUSPMT::TreeFragment_t
Structure collecting all data for a fragment ROOT tree.
Definition at line 1027 of file DaqDecoderICARUSPMT_module.cc.
Class Members
Data_t data
TTree * tree = nullptr
icarus::DaqDecoderICARUSPMT::TriggerInfo_t
struct icarus::DaqDecoderICARUSPMT::TriggerInfo_t
Collection of information about the global trigger.
Definition at line 806 of file DaqDecoderICARUSPMT_module.cc.
Class Members
long int beamToEnable Enable gate time relative to beam gate [ns].
triggerSourceMask bits Trigger bits.
unsigned int gateCount = 0U Gate number for this source.
unsigned int gateCountFromPreviousTrigger = 0U Gates from last trig.
unsigned int gateID = 0U Gate number from the beginning of run.
electronics_time relBeamGateTime Beam gate time.
electronics_time relTriggerTime Trigger time.
triggerSource sourceType Trigger source bit.
SplitTimestamp_t time Time of the trigger (absolute).
unsigned int triggerCount = 0U Trigger number for this source.
triggerLocationMask triggerLocation Where the trigger came from.
triggerLogicMask triggerLogicE Logic of east cryostat trigger.
triggerLogicMask triggerLogicW Logic of west cryostat trigger.
triggerType triggerType Type of trigger (minimum bias, majority).
long int trigToBeam Time of beam gate relative to trigger [ns].
Member Typedef Documentation
AllChannelSetup_t
using icarus::DaqDecoderICARUSPMT::AllChannelSetup_t = daq::details::BoardSetup_t::AllChannelSetup_t private
Type of setup of all channels in a readout board.
Definition at line 775 of file DaqDecoderICARUSPMT_module.cc.
BoardID_t
using icarus::DaqDecoderICARUSPMT::BoardID_t = short int private
Type used internally to represent board ID.
Definition at line 1283 of file DaqDecoderICARUSPMT_module.cc.
nanoseconds
using icarus::DaqDecoderICARUSPMT::nanoseconds = util::quantities::intervals::nanoseconds
Alias.
Definition at line 526 of file DaqDecoderICARUSPMT_module.cc.
Parameters
using icarus::DaqDecoderICARUSPMT::Parameters = art::EDProducer::Table<Config>
Definition at line 749 of file DaqDecoderICARUSPMT_module.cc.
TreeNameList_t
using icarus::DaqDecoderICARUSPMT::TreeNameList_t = std::array<std::string, static_cast<std::size_t>(DataTrees::N)> private
Definition at line 514 of file DaqDecoderICARUSPMT_module.cc.
WaveformsByCategory_t
using icarus::DaqDecoderICARUSPMT::WaveformsByCategory_t = std::map<std::string, std::vector<raw::OpDetWaveform>> private
Type of map: category to collection of waveforms under that category.
Definition at line 851 of file DaqDecoderICARUSPMT_module.cc.
Member Enumeration Documentation
DataTrees
enum class icarus::DaqDecoderICARUSPMT::DataTrees : std::size_t strong private
Enumerate the supported data trees.
Enumerator
Fragments
Information about fragments.
N
Counter.
Definition at line 510 of file DaqDecoderICARUSPMT_module.cc.
Constructor & Destructor Documentation
DaqDecoderICARUSPMT()
icarus::DaqDecoderICARUSPMT::DaqDecoderICARUSPMT (Parameters const & params) explicit
Constructor.
Definition at line 1588 of file DaqDecoderICARUSPMT_module.cc.
References fTriggerTag.
Member Function Documentation
assignEventInfo()
void icarus::DaqDecoderICARUSPMT::assignEventInfo (TreeData_EventID_t & treeData) const private
Assigns the cached event information to the specified tree data.
Definition at line 3408 of file DaqDecoderICARUSPMT_module.cc.
beginRun()
void icarus::DaqDecoderICARUSPMT::beginRun (art::Run & run) override
On a new run: cache PMT configuration information.
Definition at line 1759 of file DaqDecoderICARUSPMT_module.cc.
checkBoardSetup()
void icarus::DaqDecoderICARUSPMT::checkBoardSetup (std::vector< daq::details::BoardSetup_t > const & allBoardSetup) const private
Throws an exception if the configuration of boards shows errors.
Definition at line 3253 of file DaqDecoderICARUSPMT_module.cc.
References daq::details::BoardSetup_t::ChannelSetup_t::category, daq::details::BoardSetup_t::ChannelSetup_t::channelID, daq::details::BoardSetup_t::ChannelSetup_t::hasChannel(), and daq::details::BoardSetup_t::ChannelSetup_t::mustSkip().
checkFragmentType()
void icarus::DaqDecoderICARUSPMT::checkFragmentType (artdaq::Fragment const & artdaqFragment) const private
Throws an exception if artdaqFragment is not of type CAEN1730.
Definition at line 2399 of file DaqDecoderICARUSPMT_module.cc.
containsGlobalTrigger() [1/2]
bool icarus::DaqDecoderICARUSPMT::containsGlobalTrigger (electronics_time time, std::size_t nTicks) const private
Returns whether nominal trigger time is within nTicks from time.
Definition at line 2071 of file DaqDecoderICARUSPMT_module.cc.
containsGlobalTrigger() [2/2]
bool icarus::DaqDecoderICARUSPMT::containsGlobalTrigger (raw::OpDetWaveform const & waveform) const private
Returns whether waveform includes the tick of the nominal trigger time.
Definition at line 2080 of file DaqDecoderICARUSPMT_module.cc.
createFragmentWaveforms()
auto icarus::DaqDecoderICARUSPMT::createFragmentWaveforms (FragmentInfo_t const & fragInfo, AllChannelSetup_t const & channelSetup, electronics_time const timeStamp) const private
Creates raw::OpDetWaveform objects from the fragment data.
Parameters
fragInfo information extracted from the fragment
channelSetup settings channel by channel
timeStamp timestamp of the waveforms in the fragment
Returns
collection of newly created raw::OpDetWaveform
All fragment information needed is enclosed in fragInfo (extractFragmentInfo()). The timestamp can be obtained with a call to fragmentWaveformTimestamp().
Definition at line 2477 of file DaqDecoderICARUSPMT_module.cc.
References daq::details::BoardSetup_t::ChannelSetup_t::channelID, icarusDB::IICARUSChannelMapProvider::getPMTchannelInfo(), daq::details::BoardSetup_t::ChannelSetup_t::hasChannel(), daq::details::BoardSetup_t::ChannelSetup_t::isChannel(), daq::details::BoardSetup_t::ChannelSetup_t::mustSave(), daq::details::BoardSetup_t::ChannelSetup_t::mustSkip(), and sbn::V1730channelConfiguration::NoChannelID.
createRegularWaveformMetadata()
std::pair< std::vector< sbn::OpDetWaveformMeta >, art::Assns< raw::OpDetWaveform, sbn::OpDetWaveformMeta > > icarus::DaqDecoderICARUSPMT::createRegularWaveformMetadata (WaveformsByCategory_t const & waveformProducts, art::Event const & event, TriggerInfo_t const & triggerInfo) const private
Creates metadata and associations (if needed) for the regular waveforms.
Definition at line 2808 of file DaqDecoderICARUSPMT_module.cc.
createWaveformMetadata()
std::vector< sbn::OpDetWaveformMeta > icarus::DaqDecoderICARUSPMT::createWaveformMetadata (std::vector< raw::OpDetWaveform > const & waveforms, TriggerInfo_t const & triggerInfo) const private
Creates and returns waveform metadata.
Definition at line 2854 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::TriggerInfo_t::relBeamGateTime, and icarus::DaqDecoderICARUSPMT::TriggerInfo_t::relTriggerTime.
createWaveformMetadataAssociations()
art::Assns< raw::OpDetWaveform, sbn::OpDetWaveformMeta > icarus::DaqDecoderICARUSPMT::createWaveformMetadataAssociations (std::vector< raw::OpDetWaveform > const & waveforms, art::Event const & event, std::string const & instanceName = "") const private
Creates and returns waveform metadata associations.
Definition at line 2872 of file DaqDecoderICARUSPMT_module.cc.
effectivePMTboardFragmentID()
static constexpr std::size_t icarus::DaqDecoderICARUSPMT::effectivePMTboardFragmentID (artdaq::Fragment::fragment_id_t id) inline static constexpr private
Returns the fragment ID to be used with databases.
Definition at line 1138 of file DaqDecoderICARUSPMT_module.cc.
endJob()
void icarus::DaqDecoderICARUSPMT::endJob () override
Prints a end-of-job message.
Definition at line 2005 of file DaqDecoderICARUSPMT_module.cc.
extractFragmentBoardID()
auto icarus::DaqDecoderICARUSPMT::extractFragmentBoardID (artdaq::Fragment const & fragment) static private
Extracts the fragment ID (i.e. board ID) from the specified fragment.
Definition at line 2930 of file DaqDecoderICARUSPMT_module.cc.
extractFragmentInfo()
auto icarus::DaqDecoderICARUSPMT::extractFragmentInfo (artdaq::Fragment const & artdaqFragment) const private
Extracts useful information from fragment data.
Definition at line 2938 of file DaqDecoderICARUSPMT_module.cc.
extractTimeCorrection()
double icarus::DaqDecoderICARUSPMT::extractTimeCorrection (raw::OpDetWaveform const & waveform, std::vector< icarus::timing::PMTWaveformTimeCorrection > const * corrections) const private
Returns time correction appropriate for waveform.
Parameters
waveform the waveform whose time needs to be corrected
corrections the set of available corrections by channel
Returns
the time correction [us]
Corrections are preferably extracted from corrections if non-null. If no corrections are specified, cable delay corrections are applied according to the value of the configuration (fApplyCableDelayCorrection).
Definition at line 2831 of file DaqDecoderICARUSPMT_module.cc.
References icarus::timing::PMTWaveformTimeCorrection::startTime.
extractTriggerTimeTag()
unsigned int icarus::DaqDecoderICARUSPMT::extractTriggerTimeTag (artdaq::Fragment const & fragment) static private
Extracts the Trigger Time Tag (31+1 bits) value from the fragment.
Definition at line 3286 of file DaqDecoderICARUSPMT_module.cc.
fetchNeededBoardInfo()
auto icarus::DaqDecoderICARUSPMT::fetchNeededBoardInfo (daq::details::BoardInfoLookup::BoardInfo_t const * boardInfo, unsigned int fragmentID) const private
Puts together all the needed information for a board.
Definition at line 2231 of file DaqDecoderICARUSPMT_module.cc.
fetchTriggerTimestamp()
auto icarus::DaqDecoderICARUSPMT::fetchTriggerTimestamp (art::Event const & event) const private
Retrieves the global trigger time stamp from the event.
Definition at line 2262 of file DaqDecoderICARUSPMT_module.cc.
References sbn::ExtraTriggerInfo::EastCryostat, sbn::bits::NBits, and sbn::ExtraTriggerInfo::WestCryostat.
fillPMTfragmentTree()
void icarus::DaqDecoderICARUSPMT::fillPMTfragmentTree (FragmentInfo_t const & fragInfo, TriggerInfo_t const & triggerInfo, electronics_time waveformTimestamp) private
Fills the PMT fragment tree with the specified information (additional information needs to have been set already).
Definition at line 2891 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::TriggerInfo_t::beamToEnable, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::bits, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::gateCount, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::gateCountFromPreviousTrigger, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::gateID, sbn::bits::MinimumBias, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::sourceType, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::time, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerCount, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerLocation, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerLogicE, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerLogicW, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerType, and icarus::DaqDecoderICARUSPMT::TriggerInfo_t::trigToBeam.
fillTreeEventID()
void icarus::DaqDecoderICARUSPMT::fillTreeEventID (art::Event const & event, TreeData_EventID_t & treeData) const private
Fills the base information of a tree data entry from an art event.
Definition at line 3419 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::event, icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::run, icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::subrun, and icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::timestamp.
findWaveformsWithNominalTrigger()
auto icarus::DaqDecoderICARUSPMT::findWaveformsWithNominalTrigger (std::vector< ProtoWaveform_t > const & waveforms) const private
Returns pointers to all waveforms including the nominal trigger time.
Definition at line 2058 of file DaqDecoderICARUSPMT_module.cc.
fragmentWaveformTimestamp()
electronics_time icarus::DaqDecoderICARUSPMT::fragmentWaveformTimestamp (FragmentInfo_t const & fragInfo, NeededBoardInfo_t const & boardInfo, SplitTimestamp_t triggerTime) const private
Returns the timestamp for the waveforms in the specified fragment.
Definition at line 3018 of file DaqDecoderICARUSPMT_module.cc.
References icarusDB::IICARUSChannelMapProvider::hasPMTDigitizerID().
fragmentWaveformTimestampFromTTT()
auto icarus::DaqDecoderICARUSPMT::fragmentWaveformTimestampFromTTT (FragmentInfo_t const & fragInfo, NeededBoardInfo_t const & boardInfo, SplitTimestamp_t triggerTime) const private
Returns the timestamp for the waveforms in the specified fragment.
This method assumes that the Trigger Time Tag counters are synchronised with the global trigger and their value is reset on each new second of the global trigger timescale (International Atomic Time).
This assumptions enables timestamping of waveforms from the same readout boards at different times ("multi-window PMT readout").
See TTTresetEverySecond configuration option.
Definition at line 3066 of file DaqDecoderICARUSPMT_module.cc.
fragmentWaveformTimestampOnTrigger()
auto icarus::DaqDecoderICARUSPMT::fragmentWaveformTimestampOnTrigger (FragmentInfo_t const & fragInfo, NeededBoardInfo_t const & boardInfo, SplitTimestamp_t triggerTime) const private
Returns the timestamp for the waveforms in the specified fragment.
This method assumes that all PMT readout board triggers happened at the same time as the global trigger. Unsurprisingly, this does not work well with multiple PMT windows.
Definition at line 3045 of file DaqDecoderICARUSPMT_module.cc.
getAllInstanceNames()
std::vector< std::string > icarus::DaqDecoderICARUSPMT::getAllInstanceNames () const private
Returns all the instance names we will produce.
Definition at line 3232 of file DaqDecoderICARUSPMT_module.cc.
References daq::details::BoardSetup_t::ChannelSetup_t::category, and daq::details::BoardSetup_t::ChannelSetup_t::mustSkip().
hasPMTconfiguration()
bool icarus::DaqDecoderICARUSPMT::hasPMTconfiguration () const inline private
Returns whether PMT configuration information is expected to be available.
Definition at line 953 of file DaqDecoderICARUSPMT_module.cc.
References fPMTconfigTag.
initEventIDtree()
void icarus::DaqDecoderICARUSPMT::initEventIDtree (TTree & tree, TreeData_EventID_t & data) private
Initializes the event ID part of a tree.
Definition at line 3343 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::event, icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::run, icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::subrun, icarus::DaqDecoderICARUSPMT::SplitTimestamp_t::time, and icarus::DaqDecoderICARUSPMT::TreeData_EventID_t::timestamp.
initFragmentsTree()
void icarus::DaqDecoderICARUSPMT::initFragmentsTree () private
Initializes the fragment data tree (fTreeFragment).
Definition at line 3358 of file DaqDecoderICARUSPMT_module.cc.
initTreeNames()
auto icarus::DaqDecoderICARUSPMT::initTreeNames () static private
Static initialization.
Definition at line 1558 of file DaqDecoderICARUSPMT_module.cc.
initTrees()
void icarus::DaqDecoderICARUSPMT::initTrees (std::vector< std::string > const & treeNames) private
Initializes all requested data trees.
Definition at line 3316 of file DaqDecoderICARUSPMT_module.cc.
listTreeNames()
std::string icarus::DaqDecoderICARUSPMT::listTreeNames (std::string const & sep = "\n") static private
Returns a string with all supported tree names.
Definition at line 1571 of file DaqDecoderICARUSPMT_module.cc.
makeFragmentCollection()
artdaq::FragmentPtrs icarus::DaqDecoderICARUSPMT::makeFragmentCollection (artdaq::Fragment const & sourceFragment) const private
Converts a fragment into a fragment collection (dispatcher based on fragment type).
Definition at line 2349 of file DaqDecoderICARUSPMT_module.cc.
makeFragmentCollectionFromContainerFragment()
artdaq::FragmentPtrs icarus::DaqDecoderICARUSPMT::makeFragmentCollectionFromContainerFragment (artdaq::Fragment const & sourceFragment) const private
Converts a container fragment into a fragment collection.
Definition at line 2382 of file DaqDecoderICARUSPMT_module.cc.
makeFragmentCollectionFromFragment()
artdaq::FragmentPtrs icarus::DaqDecoderICARUSPMT::makeFragmentCollectionFromFragment (artdaq::Fragment const & sourceFragment) const private
Converts a plain fragment into a fragment collection.
Definition at line 2370 of file DaqDecoderICARUSPMT_module.cc.
matchBoardConfigurationAndSetup()
auto icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup (sbn::PMTconfiguration const * PMTconfig) const private
Returns a lookup object with board setup and configuration info.
Parameters
PMTconfig the PMT configuration, if available
Returns
an object working like lookup table for all fragment information
This method merges the setup information from the module configuration with the PMT configuration specified in the argument, and returns an object that can look up all the information as a single record, with the fragment ID as key. In addition, a few intermediate quantities ("facts", see BoardFacts_t) are computed and stored in this object.
If a fragment ID is missing, it means that no PMT configuration was provided and that the setup information did not include a fragment ID. If some information (configuration or setup) is missing, the "facts" depending on the missing information will have default values.
Definition at line 2101 of file DaqDecoderICARUSPMT_module.cc.
References sbn::V1730Configuration::boardName, sbn::V1730Configuration::bufferLength, sbn::V1730Configuration::fragmentID, daq::details::BoardSetup_t::NoFragmentID, and sbn::V1730Configuration::postTriggerFrac.
mergeWaveformGroup()
auto icarus::DaqDecoderICARUSPMT::mergeWaveformGroup (std::vector< ProtoWaveform_t > & allWaveforms, std::vector< std::size_t > const & indices) const private
Returns a waveform merging of the indices ones from allWaveforms. The merged waveforms are emptied of their content.
Definition at line 2665 of file DaqDecoderICARUSPMT_module.cc.
References daq::details::BoardSetup_t::ChannelSetup_t::category, icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::channelSetup, icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::maxSample, icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::minSample, icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::onGlobal, and icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::waveform.
mergeWaveforms()
unsigned int icarus::DaqDecoderICARUSPMT::mergeWaveforms (std::vector< ProtoWaveform_t > & waveforms) const private
Merges "in place" waveforms based on timestamp.
Returns
the number of original waveforms merged into another
Definition at line 2620 of file DaqDecoderICARUSPMT_module.cc.
neededBoardInfo()
auto icarus::DaqDecoderICARUSPMT::neededBoardInfo (artdaq::Fragment::fragment_id_t fragment_id) const private
Returns the board information for this fragment.
Definition at line 3198 of file DaqDecoderICARUSPMT_module.cc.
prepareOutputWaveforms()
auto icarus::DaqDecoderICARUSPMT::prepareOutputWaveforms (std::vector< ProtoWaveform_t > && protoWaveforms, std::vector< icarus::timing::PMTWaveformTimeCorrection > const * timeCorrections) const private
Converts the proto-waveforms into the final waveforms to be saved.
Parameters
protoWaveforms the waveforms to be converted
timeCorrections the set of time corrections to apply (may be null)
Returns
a map: instance name to its collection of waveforms to save
The protowaveforms are sorted by category (i.e. instance name), filtered as proper and corrections are applied to their timestamp according to the configuration of the module.
Filtering is based on the parameters in the module configuration, and includes the selection of categories to save and constraints e.g. on whether they include the global trigger. The timeCorrections can be omitted (nullptr), in which case cable delay corrections are applied unless fApplyCableDelayCorrection is disabled.
Note that protoWaveforms is depleted in the process.
Definition at line 2752 of file DaqDecoderICARUSPMT_module.cc.
processBoardFragments()
auto icarus::DaqDecoderICARUSPMT::processBoardFragments (artdaq::FragmentPtrs const & artdaqFragment, TriggerInfo_t const & triggerInfo) private
Extracts waveforms from the specified fragments from a board.
Definition at line 2414 of file DaqDecoderICARUSPMT_module.cc.
processFragment()
auto icarus::DaqDecoderICARUSPMT::processFragment (artdaq::Fragment const & artdaqFragment, NeededBoardInfo_t const & boardInfo, TriggerInfo_t const & triggerInfo) private
Create waveforms and fills trees for the specified artDAQ fragment.
Parameters
artdaqFragment the fragment to process
boardInfo board information needed, from configuration/setup
triggerTime absolute time of the trigger
Returns
collection of PMT waveforms from the fragment
This method fills the information for the PMT fragment tree (fillPMTfragmentTree()) and creates PMT waveforms from the fragment data (createFragmentWaveforms()).
Definition at line 2445 of file DaqDecoderICARUSPMT_module.cc.
produce()
void icarus::DaqDecoderICARUSPMT::produce (art::Event & event) override
Processes the event.
Definition at line 1772 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::TriggerInfo_t::bits, icarus::timing::PMTWaveformTimeCorrectionExtractor::findWaveformTimeCorrections(), icarus::DaqDecoderICARUSPMT::TriggerInfo_t::gateCount, util::ArtHandleTrackerManager< Event >::removeCachedProducts(), icarus::DaqDecoderICARUSPMT::TriggerInfo_t::time, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerCount, icarus::DaqDecoderICARUSPMT::TriggerInfo_t::triggerType, and util::ArtHandleTrackerManager< Event >::useEvent().
readInputFragments()
artdaq::Fragments const & icarus::DaqDecoderICARUSPMT::readInputFragments (art::Event const & event) const private
Reads the fragments to be processed.
Definition at line 2016 of file DaqDecoderICARUSPMT_module.cc.
References util::ArtHandleTrackerManager< Event >::registerHandle().
setBitIndices()
template<std::size_t NBits, typename T > std::pair< std::array< std::size_t, NBits >, std::size_t > icarus::DaqDecoderICARUSPMT::setBitIndices (T value) static constexpr private noexcept
Returns the count of set bits for each set bit.
Template Parameters
NBits the number of bits to test
Parameters
value the bit mask to be analyzed
Returns
a pair: first an array with the NBits values, second the number of bits set
Much better to go with an example. Let's process setBitIndices<16U>(0x6701): value is 0110 0111 0000 0001, and we request the 16 least significant bits (NBits). There are six bit that are set, in position 0, 8, 9, 10, 13 and 14. The returned value includes the number of set bits (6) as the second element of the pair, an as first an array of 16 indices, one for each bit position. Its values are 0 at [0], 1 at [8], 2 at [9], 3 at [10], 4 at [13] and 5 at [14]. That is, each value represents the number of that bit in the list of set bits. All the other indices, associated to the bits which are not set, are assigned a value that is equal or larger than the number of bits set (i.e. 6 or larger).
Definition at line 1531 of file DaqDecoderICARUSPMT_module.cc.
sortWaveforms()
void icarus::DaqDecoderICARUSPMT::sortWaveforms (std::vector< ProtoWaveform_t > & waveforms) const private
Sorts in place the specified waveforms in channel order, then in time.
Definition at line 3299 of file DaqDecoderICARUSPMT_module.cc.
References icarus::DaqDecoderICARUSPMT::ProtoWaveform_t::waveform.
timestampDiff()
static long long int icarus::DaqDecoderICARUSPMT::timestampDiff (std::uint64_t a, std::uint64_t b) inline static private
Returns the timestamp difference a - b.
Definition at line 1133 of file DaqDecoderICARUSPMT_module.cc.
treeName()
std::string const & icarus::DaqDecoderICARUSPMT::treeName (DataTrees treeID) static private
Returns the name of the specified tree.
Definition at line 1566 of file DaqDecoderICARUSPMT_module.cc.
UpdatePMTConfiguration()
bool icarus::DaqDecoderICARUSPMT::UpdatePMTConfiguration (sbn::PMTconfiguration const * PMTconfig) private
Updates the PMT configuration cache. How? Dunno. Placeholder.
Definition at line 2089 of file DaqDecoderICARUSPMT_module.cc.
usesEventInfo()
void icarus::DaqDecoderICARUSPMT::usesEventInfo () private
Declares the use of event information.
Definition at line 3400 of file DaqDecoderICARUSPMT_module.cc.
waveformEndTime() [1/2]
electronics_time icarus::DaqDecoderICARUSPMT::waveformEndTime (ProtoWaveform_t const & wf) const inline private
Definition at line 1228 of file DaqDecoderICARUSPMT_module.cc.
waveformEndTime() [2/2]
electronics_time icarus::DaqDecoderICARUSPMT::waveformEndTime (raw::OpDetWaveform const & wf) const inline private
Definition at line 1225 of file DaqDecoderICARUSPMT_module.cc.
waveformStartTime() [1/2]
electronics_time icarus::DaqDecoderICARUSPMT::waveformStartTime (ProtoWaveform_t const & wf) const inline private
Definition at line 1222 of file DaqDecoderICARUSPMT_module.cc.
waveformStartTime() [2/2]
electronics_time icarus::DaqDecoderICARUSPMT::waveformStartTime (raw::OpDetWaveform const & wf) const inline private
Definition at line 1219 of file DaqDecoderICARUSPMT_module.cc.
Friends And Related Symbol Documentation
dumpChannel
friend struct dumpChannel friend
Definition at line 1378 of file DaqDecoderICARUSPMT_module.cc.
Member Data Documentation
fApplyCableDelayCorrection
bool const icarus::DaqDecoderICARUSPMT::fApplyCableDelayCorrection private
Whether to apply cable delay corrections.
Definition at line 875 of file DaqDecoderICARUSPMT_module.cc.
fBoardInfoLookup
std::optional<daq::details::BoardInfoLookup> icarus::DaqDecoderICARUSPMT::fBoardInfoLookup private
Find the information on a readout boards by fragment ID.
Definition at line 939 of file DaqDecoderICARUSPMT_module.cc.
fBoardSetup
std::vector<daq::details::BoardSetup_t> const icarus::DaqDecoderICARUSPMT::fBoardSetup private
All board setup settings.
Definition at line 886 of file DaqDecoderICARUSPMT_module.cc.
fChannelMap
icarusDB::IICARUSChannelMap const& icarus::DaqDecoderICARUSPMT::fChannelMap private
Fragment/channel mapping database.
Definition at line 908 of file DaqDecoderICARUSPMT_module.cc.
fCorrectionInstance
std::string const icarus::DaqDecoderICARUSPMT::fCorrectionInstance private
String of the instance to use for the time corrections.
Definition at line 872 of file DaqDecoderICARUSPMT_module.cc.
fDataCacheRemover
util::ArtHandleTrackerManager<art::Event> icarus::DaqDecoderICARUSPMT::fDataCacheRemover mutable private
Tracks art data products and removes their cached data on demand.
Definition at line 1149 of file DaqDecoderICARUSPMT_module.cc.
fDetTimings
detinfo::DetectorTimings const icarus::DaqDecoderICARUSPMT::fDetTimings private
Interface to LArSoft configuration for detector timing.
Definition at line 905 of file DaqDecoderICARUSPMT_module.cc.
fDiagnosticOutput
bool const icarus::DaqDecoderICARUSPMT::fDiagnosticOutput private
If true will spew endless messages to output.
Definition at line 861 of file DaqDecoderICARUSPMT_module.cc.
fDropRawDataAfterUse
bool const icarus::DaqDecoderICARUSPMT::fDropRawDataAfterUse private
Clear fragment data product cache after use.
Definition at line 895 of file DaqDecoderICARUSPMT_module.cc.
fEventInfo
std::unique_ptr<TreeData_EventID_t> icarus::DaqDecoderICARUSPMT::fEventInfo private
Event ID for trees.
Tree with fragment information.
Definition at line 1080 of file DaqDecoderICARUSPMT_module.cc.
fInputTags
std::vector<art::InputTag> const icarus::DaqDecoderICARUSPMT::fInputTags private
< List of candidate data products with artDAQ data fragments.
Definition at line 856 of file DaqDecoderICARUSPMT_module.cc.
fLogCategory
std::string const icarus::DaqDecoderICARUSPMT::fLogCategory private
Message facility category.
Definition at line 897 of file DaqDecoderICARUSPMT_module.cc.
fNFailures
unsigned int icarus::DaqDecoderICARUSPMT::fNFailures = 0U private
Number of event failures encountered.
Definition at line 944 of file DaqDecoderICARUSPMT_module.cc.
fNominalTriggerTime
electronics_time const icarus::DaqDecoderICARUSPMT::fNominalTriggerTime private
Trigger time as reported by detinfo::DetectorClocks service.
Definition at line 929 of file DaqDecoderICARUSPMT_module.cc.
fOpticalTick
nanoseconds const icarus::DaqDecoderICARUSPMT::fOpticalTick private
Duration of the optical detector readout sampling tick (i.e. 2 ns; hush!).
Definition at line 926 of file DaqDecoderICARUSPMT_module.cc.
fPacketDump
bool const icarus::DaqDecoderICARUSPMT::fPacketDump private
Dump V1730 data.
Definition at line 863 of file DaqDecoderICARUSPMT_module.cc.
fPMTconfigTag
std::optional<art::InputTag> const icarus::DaqDecoderICARUSPMT::fPMTconfigTag private
Input tag of the PMT configuration.
Definition at line 878 of file DaqDecoderICARUSPMT_module.cc.
Referenced by hasPMTconfiguration().
fPMTTimingCorrectionsService
icarusDB::PMTTimingCorrections const* const icarus::DaqDecoderICARUSPMT::fPMTTimingCorrectionsService private
The online PMT corrections service provider.
Definition at line 911 of file DaqDecoderICARUSPMT_module.cc.
fPMTWaveformTimeCorrectionManager
icarus::timing::PMTWaveformTimeCorrectionExtractor const icarus::DaqDecoderICARUSPMT::fPMTWaveformTimeCorrectionManager private
Definition at line 918 of file DaqDecoderICARUSPMT_module.cc.
fRequireBoardConfig
bool const icarus::DaqDecoderICARUSPMT::fRequireBoardConfig private
Whether setup info on all boards is required.
Definition at line 869 of file DaqDecoderICARUSPMT_module.cc.
fRequireKnownBoards
bool const icarus::DaqDecoderICARUSPMT::fRequireKnownBoards private
Whether info on all input boards is required.
Definition at line 866 of file DaqDecoderICARUSPMT_module.cc.
fSaveCorrectionsFrom
std::vector<std::string> icarus::DaqDecoderICARUSPMT::fSaveCorrectionsFrom private
List of correction categories to save.
Definition at line 892 of file DaqDecoderICARUSPMT_module.cc.
fSaveRegularWaveforms
bool const icarus::DaqDecoderICARUSPMT::fSaveRegularWaveforms private
Whether regular waveforms are saved.
Definition at line 931 of file DaqDecoderICARUSPMT_module.cc.
fSaveWaveformsFrom
std::vector<std::string> icarus::DaqDecoderICARUSPMT::fSaveWaveformsFrom private
List of waveform categories to save.
Definition at line 889 of file DaqDecoderICARUSPMT_module.cc.
fSurviveExceptions
bool const icarus::DaqDecoderICARUSPMT::fSurviveExceptions private
Whether to "ignore" errors.
Definition at line 858 of file DaqDecoderICARUSPMT_module.cc.
fTreeFragment
std::unique_ptr<TreeFragment_t> icarus::DaqDecoderICARUSPMT::fTreeFragment private
Definition at line 1083 of file DaqDecoderICARUSPMT_module.cc.
fTriggerTag
std::optional<art::InputTag> const icarus::DaqDecoderICARUSPMT::fTriggerTag private
Input tag of the global trigger.
Definition at line 881 of file DaqDecoderICARUSPMT_module.cc.
Referenced by DaqDecoderICARUSPMT().
fTTTresetEverySecond
bool const icarus::DaqDecoderICARUSPMT::fTTTresetEverySecond private
Whether V1730 TTT is reset every second.
Definition at line 883 of file DaqDecoderICARUSPMT_module.cc.
NoTimestamp
electronics_time icarus::DaqDecoderICARUSPMT::NoTimestamp = std::numeric_limits<electronics_time>::min() static constexpr
Definition at line 752 of file DaqDecoderICARUSPMT_module.cc.
RegularWaveformCategory
std::string const icarus::DaqDecoderICARUSPMT::RegularWaveformCategory { "" } static private
Instance name associated to the regular PMT waveforms.
Definition at line 1550 of file DaqDecoderICARUSPMT_module.cc.
TreeNames
icarus::DaqDecoderICARUSPMT::TreeNameList_t const icarus::DaqDecoderICARUSPMT::TreeNames = icarus::DaqDecoderICARUSPMT::initTreeNames() static private
Definition at line 515 of file DaqDecoderICARUSPMT_module.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/DaqDecoderICARUSPMT_module.cc