CAF format: icarus::opdet::PhotoelectronPulseFunction< T > Class Template Reference
icarus::opdet::PhotoelectronPulseFunction< T > Class Template Reference abstract
Interface for a function describing a pulse from a photoelectron.
#include <PhotoelectronPulseFunction.h>
Public Types
using ADCcount = util::quantities::counts_f
Type for ADC counts (floating point).
using Time = T
Type of time being used.
Public Member Functions
ADCcount evaluateAt (Time time) const
Evaluates the pulse at the given time.
ADCcount operator() (Time time) const
Alias of evaluateAt().
Time peakTime () const
Returns the time at which the first peak is found.
ADCcount peakAmplitude () const
Returns the amplitude of the first peak in ADC counts.
ADCcount baseline () const
Returns the baseline of the pulse in ADC counts.
int polarity () const
Returns the polarity of the pulse (+1: positive, or -1: negative).
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints on stream the parameters of this shape.
void dump (std::ostream &&out, std::string const &indent="") const
std::string toString (std::string const &indent, std::string const &firstIndent) const
Returns the parameters of this shape as a descriptive string.
std::string toString (std::string const &indent="") const
Protected Member Functions
Mandatory customization
virtual ADCcount doEvaluateAt (Time time) const =0
Implementation of the function evaluation at time.
virtual Time doPeakTime () const =0
Returns the time at which the first peak is found.
Optional customization
virtual ADCcount doPeakAmplitude () const
Returns the amplitude of the first peak in ADC counts.
virtual ADCcount doBaseline () const
Returns the baseline of the pulse.
virtual int doPolarity () const
Returns the polarity of the pulse (+1 or -1).
virtual void doDump (std::ostream &out, std::string const &indent, std::string const &firstIndent) const
Prints into the stream the parameters of this shape.
Detailed Description
template<typename T>
class icarus::opdet::PhotoelectronPulseFunction< T >
Interface for a function describing a pulse from a photoelectron.
Template Parameters
T type used to represent time
A function implementing this interface expresses a sampled value in ADC counts (ADCcount type) as function of time (Time type).
The time types in LArSoft quantities library can be used as Time (T): e.g., PhotoelectronPulseFunction<util::quantities::nanosecond>.
Definition at line 45 of file PhotoelectronPulseFunction.h.
Member Typedef Documentation
ADCcount
template<typename T > using icarus::opdet::PhotoelectronPulseFunction< T >::ADCcount = util::quantities::counts_f
Type for ADC counts (floating point).
Definition at line 49 of file PhotoelectronPulseFunction.h.
Time
template<typename T > using icarus::opdet::PhotoelectronPulseFunction< T >::Time = T
Type of time being used.
Definition at line 51 of file PhotoelectronPulseFunction.h.
Member Function Documentation
baseline()
template<typename T > ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::baseline () const inline
Returns the baseline of the pulse in ADC counts.
Definition at line 73 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doBaseline().
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::doPolarity().
doBaseline()
template<typename T > virtual ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::doBaseline () const inline protected virtual
Returns the baseline of the pulse.
Definition at line 134 of file PhotoelectronPulseFunction.h.
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::baseline().
doDump()
template<typename T > virtual void icarus::opdet::PhotoelectronPulseFunction< T >::doDump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const inline protected virtual
Prints into the stream the parameters of this shape.
Parameters
out the C++ output stream to write into
indent indentation string, prepended to all lines except first
firstIndent indentation string prepended to the first line
Reimplemented in icarus::opdet::AsymExpPulseFunction< T >, icarus::opdet::AsymGaussPulseFunction< T >, icarus::opdet::CustomPulseFunction< T >, and icarus::opdet::SampledWaveformFunction< T >.
Definition at line 147 of file PhotoelectronPulseFunction.h.
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::dump().
doEvaluateAt()
template<typename T > virtual ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::doEvaluateAt (Time time) const protected pure virtual
Implementation of the function evaluation at time.
Implemented in icarus::opdet::AsymExpPulseFunction< T >, icarus::opdet::AsymGaussPulseFunction< T >, icarus::opdet::CustomPulseFunction< T >, and icarus::opdet::SampledWaveformFunction< T >.
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::evaluateAt().
doPeakAmplitude()
template<typename T > virtual ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::doPeakAmplitude () const inline protected virtual
Returns the amplitude of the first peak in ADC counts.
Reimplemented in icarus::opdet::AsymExpPulseFunction< T >, icarus::opdet::AsymGaussPulseFunction< T >, icarus::opdet::CustomPulseFunction< T >, and icarus::opdet::SampledWaveformFunction< T >.
Definition at line 131 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::evaluateAt(), and icarus::opdet::PhotoelectronPulseFunction< T >::peakTime().
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::peakAmplitude().
doPeakTime()
template<typename T > virtual Time icarus::opdet::PhotoelectronPulseFunction< T >::doPeakTime () const protected pure virtual
Returns the time at which the first peak is found.
Implemented in icarus::opdet::AsymExpPulseFunction< T >, icarus::opdet::AsymGaussPulseFunction< T >, icarus::opdet::CustomPulseFunction< T >, and icarus::opdet::SampledWaveformFunction< T >.
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::peakTime().
doPolarity()
template<typename T > virtual int icarus::opdet::PhotoelectronPulseFunction< T >::doPolarity () const inline protected virtual
Returns the polarity of the pulse (+1 or -1).
Definition at line 137 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::baseline(), and icarus::opdet::PhotoelectronPulseFunction< T >::peakAmplitude().
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::polarity().
dump() [1/2]
template<typename T > void icarus::opdet::PhotoelectronPulseFunction< T >::dump (std::ostream && out, std::string const & indent = "") const inline
Definition at line 91 of file PhotoelectronPulseFunction.h.
dump() [2/2]
template<typename T > void icarus::opdet::PhotoelectronPulseFunction< T >::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent) const inline
Prints on stream the parameters of this shape.
Parameters
out the stream to write into
indent indentation string, prepended to all lines except first
firstIndent indentation string prepended to the first line
Definition at line 86 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doDump().
evaluateAt()
template<typename T > ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::evaluateAt (Time time) const inline
Evaluates the pulse at the given time.
Parameters
time time to evaluate the shape at
Returns
value of the pulse at the specified time
Definition at line 61 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doEvaluateAt().
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::doPeakAmplitude(), and icarus::opdet::PhotoelectronPulseFunction< T >::operator()().
operator()()
template<typename T > ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::operator() (Time time) const inline
Alias of evaluateAt().
Definition at line 64 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::evaluateAt().
peakAmplitude()
template<typename T > ADCcount icarus::opdet::PhotoelectronPulseFunction< T >::peakAmplitude () const inline
Returns the amplitude of the first peak in ADC counts.
Definition at line 70 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doPeakAmplitude().
Referenced by icarus::opdet::PhotoelectronPulseFunction< T >::doPolarity(), and icarus::opdet::DiscretePhotoelectronPulse::peakAmplitude().
peakTime()
template<typename T > Time icarus::opdet::PhotoelectronPulseFunction< T >::peakTime () const inline
Returns the time at which the first peak is found.
Definition at line 67 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doPeakTime().
Referenced by icarus::opdet::CustomPulseFunction< T >::CustomPulseFunction(), icarus::opdet::PhotoelectronPulseFunction< T >::doPeakAmplitude(), and icarus::opdet::DiscretePhotoelectronPulse::peakTime().
polarity()
template<typename T > int icarus::opdet::PhotoelectronPulseFunction< T >::polarity () const inline
Returns the polarity of the pulse (+1: positive, or -1: negative).
Definition at line 76 of file PhotoelectronPulseFunction.h.
References icarus::opdet::PhotoelectronPulseFunction< T >::doPolarity().
toString() [1/2]
template<typename T > std::string icarus::opdet::PhotoelectronPulseFunction< T >::toString (std::string const & indent, std::string const & firstIndent) const
Returns the parameters of this shape as a descriptive string.
Parameters
indent indentation string, prepended to all lines except first
firstIndent indentation string prepended to the first line
Returns
a string with the parameters of this shape
Definition at line 163 of file PhotoelectronPulseFunction.h.
Referenced by icarus::opdet::DiscretePhotoelectronPulse::checkRange().
toString() [2/2]
template<typename T > std::string icarus::opdet::PhotoelectronPulseFunction< T >::toString (std::string const & indent = "") const inline
Definition at line 105 of file PhotoelectronPulseFunction.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/Algorithms/PhotoelectronPulseFunction.h