CAF format: manageDataRunDefinitions.SampleInfo Class Reference
manageDataRunDefinitions.SampleInfo Class Reference
Public Member Functions
__init__ (self, run=None, stage=None, stream=None, projectVersion=None, "MiB" minSize=None)
"returns if run is collapsed to a value" isRunDefined (self)
"returns if stage is collapsed to a value" isStageComplete (self)
"returns if stream is collapsed to a value" isStreamComplete (self)
"returns if project version is collapsed to a value" isProjectVersionComplete (self)
"returns if there are no ambiguities left in the info" isComplete (self)
defName (self)
copy (self, **kwargs)
__str__ (self)
Static Public Member Functions
makeOptionList (value)
hasOptions (value)
Public Attributes
run = SampleInfo._copyList(run)
s+ stage = SampleInfo._copyList(stage)
s+ stream = SampleInfo._copyList(stream)
s+ projectVersion = SampleInfo._copyList(projectVersion)
int minSize = minSize if minSize else 0
Static Protected Member Functions
_isIterable (value)
_copyList (value)
Detailed Description
Definition at line 59 of file manageDataRunDefinitions.py.
Constructor & Destructor Documentation
__init__()
manageDataRunDefinitions.SampleInfo.__init__ (self, run = None, stage = None, stream = None, projectVersion = None, "MiB" minSize = None)
Definition at line 60 of file manageDataRunDefinitions.py.
Member Function Documentation
__str__()
manageDataRunDefinitions.SampleInfo.__str__ (self)
Definition at line 112 of file manageDataRunDefinitions.py.
_copyList()
manageDataRunDefinitions.SampleInfo._copyList (value) static protected
Definition at line 132 of file manageDataRunDefinitions.py.
_isIterable()
manageDataRunDefinitions.SampleInfo._isIterable (value) static protected
Definition at line 129 of file manageDataRunDefinitions.py.
copy()
manageDataRunDefinitions.SampleInfo.copy (self, ** kwargs)
Definition at line 103 of file manageDataRunDefinitions.py.
defName()
manageDataRunDefinitions.SampleInfo.defName (self)
Definition at line 90 of file manageDataRunDefinitions.py.
hasOptions()
manageDataRunDefinitions.SampleInfo.hasOptions (value) static
Definition at line 125 of file manageDataRunDefinitions.py.
isComplete()
"returns if there are no ambiguities left in the info" manageDataRunDefinitions.SampleInfo.isComplete (self)
Definition at line 85 of file manageDataRunDefinitions.py.
isProjectVersionComplete()
"returns if project version is collapsed to a value" manageDataRunDefinitions.SampleInfo.isProjectVersionComplete (self)
Definition at line 82 of file manageDataRunDefinitions.py.
isRunDefined()
"returns if run is collapsed to a value" manageDataRunDefinitions.SampleInfo.isRunDefined (self)
Definition at line 71 of file manageDataRunDefinitions.py.
isStageComplete()
"returns if stage is collapsed to a value" manageDataRunDefinitions.SampleInfo.isStageComplete (self)
Definition at line 76 of file manageDataRunDefinitions.py.
isStreamComplete()
"returns if stream is collapsed to a value" manageDataRunDefinitions.SampleInfo.isStreamComplete (self)
Definition at line 79 of file manageDataRunDefinitions.py.
makeOptionList()
manageDataRunDefinitions.SampleInfo.makeOptionList (value) static
Definition at line 121 of file manageDataRunDefinitions.py.
Member Data Documentation
minSize
manageDataRunDefinitions.SampleInfo.minSize = minSize if minSize else 0
Definition at line 68 of file manageDataRunDefinitions.py.
projectVersion
s manageDataRunDefinitions.SampleInfo.projectVersion = SampleInfo._copyList(projectVersion)
Definition at line 67 of file manageDataRunDefinitions.py.
run
manageDataRunDefinitions.SampleInfo.run = SampleInfo._copyList(run)
Definition at line 64 of file manageDataRunDefinitions.py.
Referenced by sortDataLoggerFiles.FileInfoClass.__init__(), and sortDataLoggerFiles.FileInfoClass.__lt__().
stage
s manageDataRunDefinitions.SampleInfo.stage = SampleInfo._copyList(stage)
Definition at line 65 of file manageDataRunDefinitions.py.
stream
s manageDataRunDefinitions.SampleInfo.stream = SampleInfo._copyList(stream)
Definition at line 66 of file manageDataRunDefinitions.py.
Referenced by sortDataLoggerFiles.FileInfoClass.__init__(), and sortDataLoggerFiles.FileInfoClass.__lt__().
The documentation for this class was generated from the following file:
icaruscode/scripts/manageDataRunDefinitions.py