CAF format: icarus::trigger::LVDSHWbitID Struct Reference
icarus::trigger::LVDSHWbitID Struct Reference
#include <LVDSbitMaps.h>
Public Types
using Connector_t = unsigned short int
Type for connector number.
using ConnectorBit_t = unsigned short int
Type for connector bit.
using Index_t = unsigned short int
Type for LVDS bit ID index.
Public Member Functions
constexpr bool hasCryostat () const
Returns if the cryostat is set; ID is valid even if this is false.
constexpr Index_t index () const
Returns an "unique" index for this information.
constexpr bool isValid () const
Returns whether this ID is valid (does not require hasCryostat()).
constexpr operator bool () const
Returns whether this ID is valid (does not require hasCryostat()).
Static Public Member Functions
static LVDSHWbitID fromIndex (Index_t index)
Rebuilds an ID object from its index.
static constexpr Index_t NIndices ()
Returns the number of possible indices (0 to NIndices() - 1).
Public Attributes
unsigned short int cryostat = NoCryostat
The cryostat the bit comes from (sbn::ExtraTriggerInfo convention).
Connector_t connector = NoConnector
The number of connector within the appropriate wall.
ConnectorBit_t bit = NoConnectorBit
The bit index within the 32-bit connector word (0 = least significant).
Static Public Attributes
static constexpr unsigned short int NCryostats = PMTpairBitID::NCryostats
How many cryostats in the detector.
static constexpr unsigned short int NConnectorsPerCryostat = 4
How many 32-bit connectors come out of each cryostat.
static constexpr unsigned short int NoCryostat = std::numeric_limits<unsigned short int>::max()
Special value to identify the absence of cryostat information.
static constexpr Connector_t NoConnector = std::numeric_limits<Connector_t>::max()
Special value to identify the absence of a connector.
static constexpr ConnectorBit_t NoConnectorBit = std::numeric_limits<ConnectorBit_t>::max()
Special value to identify the absence of a connector bit.
static constexpr Index_t InvalidIndex = std::numeric_limits<Index_t>::max()
Special value for an invalid bit index.
Detailed Description
Identifier of a "hardware" LVDS bit featured in the PMT channel mapping databases.
Definition at line 168 of file LVDSbitMaps.h.
Member Typedef Documentation
Connector_t
using icarus::trigger::LVDSHWbitID::Connector_t = unsigned short int
Type for connector number.
Definition at line 170 of file LVDSbitMaps.h.
ConnectorBit_t
using icarus::trigger::LVDSHWbitID::ConnectorBit_t = unsigned short int
Type for connector bit.
Definition at line 171 of file LVDSbitMaps.h.
Index_t
using icarus::trigger::LVDSHWbitID::Index_t = unsigned short int
Type for LVDS bit ID index.
Definition at line 172 of file LVDSbitMaps.h.
Member Function Documentation
fromIndex()
auto icarus::trigger::LVDSHWbitID::fromIndex (Index_t index) static
Rebuilds an ID object from its index.
Definition at line 55 of file LVDSbitMaps.cxx.
hasCryostat()
bool icarus::trigger::LVDSHWbitID::hasCryostat () const inline constexpr
Returns if the cryostat is set; ID is valid even if this is false.
Definition at line 210 of file LVDSbitMaps.h.
References cryostat, and NoCryostat.
Referenced by index().
index()
Index_t icarus::trigger::LVDSHWbitID::index () const inline constexpr
Returns an "unique" index for this information.
Definition at line 213 of file LVDSbitMaps.h.
References bit, connector, cryostat, hasCryostat(), InvalidIndex, isValid(), and NConnectorsPerCryostat.
Referenced by icarus::trigger::LVDSbitMaps::LVDSchannel_t::index().
isValid()
bool icarus::trigger::LVDSHWbitID::isValid () const inline constexpr
Returns whether this ID is valid (does not require hasCryostat()).
Definition at line 223 of file LVDSbitMaps.h.
References bit, connector, NoConnector, and NoConnectorBit.
Referenced by index(), and operator bool().
NIndices()
static constexpr Index_t icarus::trigger::LVDSHWbitID::NIndices () inline static constexpr
Returns the number of possible indices (0 to NIndices() - 1).
Definition at line 234 of file LVDSbitMaps.h.
References NConnectorsPerCryostat, and NCryostats.
Referenced by icarus::trigger::LVDSbitMaps::buildAdderSourceMap(), and icarus::trigger::LVDSbitMaps::buildPMTpairSourceMap().
operator bool()
icarus::trigger::LVDSHWbitID::operator bool () const inline constexpr
Returns whether this ID is valid (does not require hasCryostat()).
Definition at line 227 of file LVDSbitMaps.h.
References isValid().
Member Data Documentation
bit
ConnectorBit_t icarus::trigger::LVDSHWbitID::bit = NoConnectorBit
The bit index within the 32-bit connector word (0 = least significant).
Definition at line 205 of file LVDSbitMaps.h.
Referenced by daq::TriggerDecoderV3::encodeLVDSbits(), daq::TriggerDecoderV3::encodeSectorBits(), index(), and isValid().
connector
Connector_t icarus::trigger::LVDSHWbitID::connector = NoConnector
The number of connector within the appropriate wall.
Definition at line 202 of file LVDSbitMaps.h.
Referenced by daq::TriggerDecoderV3::encodeLVDSbits(), daq::TriggerDecoderV3::encodeSectorBits(), index(), and isValid().
cryostat
unsigned short int icarus::trigger::LVDSHWbitID::cryostat = NoCryostat
The cryostat the bit comes from (sbn::ExtraTriggerInfo convention).
Definition at line 199 of file LVDSbitMaps.h.
Referenced by daq::TriggerDecoderV3::encodeLVDSbits(), daq::TriggerDecoderV3::encodeSectorBits(), hasCryostat(), and index().
InvalidIndex
Index_t icarus::trigger::LVDSHWbitID::InvalidIndex = std::numeric_limits<Index_t>::max() static constexpr
Special value for an invalid bit index.
Definition at line 193 of file LVDSbitMaps.h.
Referenced by index().
NConnectorsPerCryostat
unsigned short int icarus::trigger::LVDSHWbitID::NConnectorsPerCryostat = 4 static constexpr
How many 32-bit connectors come out of each cryostat.
Definition at line 178 of file LVDSbitMaps.h.
Referenced by index(), and NIndices().
NCryostats
unsigned short int icarus::trigger::LVDSHWbitID::NCryostats = PMTpairBitID::NCryostats static constexpr
How many cryostats in the detector.
Definition at line 175 of file LVDSbitMaps.h.
Referenced by NIndices().
NoConnector
Connector_t icarus::trigger::LVDSHWbitID::NoConnector = std::numeric_limits<Connector_t>::max() static constexpr
Special value to identify the absence of a connector.
Definition at line 185 of file LVDSbitMaps.h.
Referenced by isValid().
NoConnectorBit
ConnectorBit_t icarus::trigger::LVDSHWbitID::NoConnectorBit = std::numeric_limits<ConnectorBit_t>::max() static constexpr
Special value to identify the absence of a connector bit.
Definition at line 189 of file LVDSbitMaps.h.
Referenced by isValid().
NoCryostat
unsigned short int icarus::trigger::LVDSHWbitID::NoCryostat = std::numeric_limits<unsigned short int>::max() static constexpr
Special value to identify the absence of cryostat information.
Definition at line 181 of file LVDSbitMaps.h.
Referenced by hasCryostat().
The documentation for this struct was generated from the following files:
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.h
icaruscode/icaruscode/PMT/Trigger/Algorithms/LVDSbitMaps.cxx