CAF format: opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits > Class Reference
opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits > Class Reference
Framework interface to pmtana::PedAlgoFixed.
Public Member Functions
FWInterfaced (fhicl::ParameterSet const &pset)
Public Member Functions inherited from opdet::factory::FWInterfacedIF< pmtana::PMTPedestalBase, ArtTraits >
Algo_t & algo () const
Access to the algorithm.
void initialize (Module_t &module)
void beginEvent (Event_t const &event)
void endEvent (Event_t const &event)
Private Types
using IFBase_t
Private Member Functions
virtual void doInitialize (typename IFBase_t::Module_t &module)
Declares the consumables.
virtual void doBeginEvent (typename IFBase_t::Event_t const &event)
Reads and reports to the algorithm the pedestals for this event.
virtual void doEndEvent (typename IFBase_t::Event_t const &)
Clear the event information (just "safety").
Additional Inherited Members
Public Types inherited from opdet::factory::FWInterfacedBase< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >
using Algo_t
Public Types inherited from opdet::factory::FWInterfacedIF< pmtana::PMTPedestalBase, ArtTraits >
using Algo_t
using Event_t
using Module_t
Protected Member Functions inherited from opdet::factory::FWInterfacedBase< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >
FWInterfacedBase (fhicl::ParameterSet const &pset)
virtual RealAlgo_t * getAlgo () const override
Returns the stored algorithm.
Detailed Description
Framework interface to pmtana::PedAlgoFixed.
Definition at line 339 of file ICARUSOpHitFinder_module.cc.
Member Typedef Documentation
IFBase_t
using opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::IFBase_t private
Initial value:
 opdet::factory::FWInterfacedBase
    <pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits>
Definition at line 344 of file ICARUSOpHitFinder_module.cc.
Constructor & Destructor Documentation
FWInterfaced()
opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::FWInterfaced (fhicl::ParameterSet const & pset) inline
Definition at line 348 of file ICARUSOpHitFinder_module.cc.
Member Function Documentation
doBeginEvent()
virtual void opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::doBeginEvent (typename IFBase_t::Event_t const & event) inline private virtual
Reads and reports to the algorithm the pedestals for this event.
Definition at line 366 of file ICARUSOpHitFinder_module.cc.
References opdet::factory::FWInterfacedIF< Base, FWTraits >::algo(), icarus::WaveformBaseline::baseline(), icarus::WaveformRMS::RMS(), and pmtana::PedAlgoFixed::InputSet_t::waveforms.
doEndEvent()
virtual void opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::doEndEvent (typename IFBase_t::Event_t const &) inline private virtual
Clear the event information (just "safety").
Definition at line 415 of file ICARUSOpHitFinder_module.cc.
doInitialize()
virtual void opdet::factory::FWInterfaced< pmtana::PedAlgoFixed, pmtana::PMTPedestalBase, ArtTraits >::doInitialize (typename IFBase_t::Module_t & module) inline private virtual
Declares the consumables.
Reimplemented from opdet::factory::FWInterfacedIF< pmtana::PMTPedestalBase, ArtTraits >.
Definition at line 354 of file ICARUSOpHitFinder_module.cc.
References opdet::factory::FWInterfacedIF< Base, FWTraits >::algo().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/OpReco/ICARUSOpHitFinder_module.cc