CAF format: anonymous_namespace{ReassociatePMTbaselines_module.cc} Namespace Reference
anonymous_namespace{ReassociatePMTbaselines_module.cc} Namespace Reference
Classes
class PtrFinder
Keeps a map of the art pointers of some objects.
Functions
template<typename Handle , typename Comp = std::less<typename Handle::value_type>>
PtrFinder< typename Handle::element_type::value_type, Comp > makePtrFinder (Handle const &handle, Comp comp=Comp{})
Creates a IndexMap object with the specified collection and comparison.
template<typename T >
std::unique_ptr< T > moveToUniquePtr (T &obj)
Function Documentation
makePtrFinder()
template<typename Handle , typename Comp = std::less<typename Handle::value_type>> PtrFinder< typename Handle::element_type::value_type, Comp > anonymous_namespace{ReassociatePMTbaselines_module.cc}::makePtrFinder (Handle const & handle, Comp comp = Comp{})
Creates a IndexMap object with the specified collection and comparison.
Definition at line 327 of file ReassociatePMTbaselines_module.cc.
References makePtrFinder().
Referenced by makePtrFinder(), and icarus::trigger::ReassociatePMTbaselines::produce().
moveToUniquePtr()
template<typename T > std::unique_ptr< T > anonymous_namespace{ReassociatePMTbaselines_module.cc}::moveToUniquePtr (T & obj)
Definition at line 347 of file ReassociatePMTbaselines_module.cc.