CAF format: icaruscode/icaruscode/Utilities/TrajectoryUtils.h File Reference
TrajectoryUtils.h File Reference
Algorithms dealing with a trajectory as a sequence of 3D points.
#include "larcorealg/Geometry/geo_vectors_utils.h"
#include <vector>
#include <utility>
#include <iterator>
Classes
struct util::PathPointInfo_t< Iter >
Data returned by findMiddlePointInPath().
Functions
template<typename FIter , typename LIter >
PathPointInfo_t< FIter > util::findMiddlePointInPath (FIter itFirst, LIter itLast, double relTarget=0.5)
Returns information to identify the middle of the specified path.
template<typename FIter , typename LIter >
auto util::pathMiddlePoint (FIter itFirst, LIter itLast, double relTarget=0.5)
Returns the geometric point in the middle of the specified path.
template<typename BIter , typename EIter >
double util::pathLength (BIter begin, EIter end)
Returns the total length of the specified path.
template<typename BIter , typename EIter >
std::vector< double > util::partialPathLengths (BIter begin, EIter end)
Returns a sequences of partial lengths for the specified path.
template<typename Iter , typename SideFunc >
std::pair< Iter, Iter > util::findCrossingSegment (Iter begin, Iter end, SideFunc sideOf)
Returns a path segment with ends on different sides than path ends.
Detailed Description
Algorithms dealing with a trajectory as a sequence of 3D points.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Date
July 26, 2022
This is a header-only library.
Todo
Move this file into icarusalg/Utilities.
Definition in file TrajectoryUtils.h.
Function Documentation
findCrossingSegment()
template<typename Iter , typename SideFunc > std::pair< Iter, Iter > util::findCrossingSegment (Iter begin, Iter end, SideFunc sideOf)
Returns a path segment with ends on different sides than path ends.
Template Parameters
Iter type of iterator to the points in the path
SideFunc type of functor returning the side of a point
Parameters
begin iterator to the first point of the path
end iterator past the last point of the path
sideOf functor returning the side of the point in argument
Returns
a pair of iterators pointing to the points found, { end, end } if the path does not change side at all
The path is defined as a sequence of positions of arbitrary types. The functor sideOf takes as argument one such position, and returns an also arbitrary value representing the side of that position. This algorithm returns a pair with the first point where the side changes, and the point after the last side change. The two points match only if there is no side change at all (in which case a pair with two end iterators is returned). The two returned iterators are adjacent only if there is only one change of side.
Note that this algorithm is effectively not specific to a space path but it's rather a generic classification algorithm: given an ordered sequence, it finds the first and the last change of class.
Requirements
Iter must be a bidirectional operator (ask if this is too restrictive)
SideFunc must support a call like. Side SideFunc::operator() (Iter::value_type) const, i.e. must accept as argument the position pointed by an iterator of type Iter and return an arbitrary Side value.
Side type (returned by sideOf) must support operator!= (Side, Side).
Definition at line 454 of file TrajectoryUtils.h.
References util::findCrossingSegment().
Referenced by util::findCrossingSegment(), and util::findMiddlePointInPath().
findMiddlePointInPath()
template<typename FIter , typename LIter > PathPointInfo_t< FIter > util::findMiddlePointInPath (FIter itFirst, LIter itLast, double relTarget = 0.5)
Returns information to identify the middle of the specified path.
Template Parameters
FIter type of iterator to a point in the path
LIter type of iterator to a point in the path
Parameters
itFirst iterator to the first point in the path
itLast iterator to the last point in the path (must be valid point)
relTarget (default: 0.5) fraction of the total length to pursue
Returns
information to identify the desired point
The sequence between the iterators itFirst and itLast, both included, defines a path. This function returns the point that cuts that path into two subpaths of the same length. The point usually does not match any of the points in the sequence, but rather is in between two of them.
The path is considered a sequence of straight segments connecting the points.
Example of use with a LArSoft recob::Track object (track):
auto const& path = track.Trajectory().Positions();
geo::Point_t const middle
  = util::PathMiddlePoint(path.begin(), std::prev(path.end()));
(note that here the function actually returns a recob::tracking::Point_t).
Requirements
The FIter type is a forward iterator, the type LIter is a backward iterator.
FIter must support prefix operator++, LIter must support prefix operator--().
FIter and LIter must compare equal (operator == (FIter, LIter)) if they point to the same element of the sequence.
The two iterators must point to the same type of point (called Point in the following text).
The type Point must satisfy the following operations.
Vector operator- (Point, Point) returns an object describing the displacement to go from the second point to the first one.
geo::vect::norm(Vector) is a function returning the magnitude of the specified displacement vector.
LArSoft geo::Point_t type is known to satisfy the requirements of Point (geo::Vector_t being its corresponding Vector type). The modulus function geo::vect::norm() is provided for geo::Vector_t in the LArSoft header larcorealg/CoreUtils/geo_vector_utils.h.
References util::findCrossingSegment(), util::findMiddlePointInPath(), util::partialPathLengths(), util::pathLength(), and util::pathMiddlePoint().
Referenced by util::findMiddlePointInPath(), and util::pathMiddlePoint().
partialPathLengths()
template<typename BIter , typename EIter > std::vector< double > util::partialPathLengths (BIter begin, EIter end)
Returns a sequences of partial lengths for the specified path.
Template Parameters
BIter type of iterator to the start of the trajectory
EIter type of iterator to the end of the trajectory
Parameters
begin iterator to the first point of the trajectory
end iterator past the last point of the trajectory
Returns
a sequence of partial lengths, one per point
See also
pathLength()
The sequence of partial lengths is returned, with one entry per point. A partial length up to the point i is the sum of the distances between adjacent points starting from the first point (*begin) to the i-th, included. The first entry of the sequence is always 0.
The length are in the same units as the input point coordinates.
Requirements
The BIter type is a forward iterator.
BIter must support prefix operator++
operator != (BIter, EIter) must return whether the first iterator is equivalent to the second (or rather, whether the sequence is over).
The type Point must satisfy the following operations.
Vector operator- (Point, Point) returns an object describing the displacement to go from the second point to the first one.
geo::vect::norm(Vector) is a function returning the magnitude of the specified displacement vector.
Definition at line 437 of file TrajectoryUtils.h.
References util::partialPathLengths().
Referenced by util::findMiddlePointInPath(), and util::partialPathLengths().
pathLength()
template<typename BIter , typename EIter > double util::pathLength (BIter begin, EIter end)
Returns the total length of the specified path.
Template Parameters
BIter type of iterator to the start of the trajectory
EIter type of iterator to the end of the trajectory
Parameters
begin iterator to the first point of the trajectory
end iterator past the last point of the trajectory
Returns
the length of the path
See also
partialPathLengths()
The sequence of partial lengths is returned, with one entry per point. The length is the sum of the distances between adjacent points of the sequence. Empty sequences and sequences of a single points have length 0.
The length are in the same units as the input point coordinates.
Requirements
The BIter type is a forward iterator.
BIter must support prefix operator++
operator != (BIter, EIter) must return whether the first iterator is equivalent to the second (or rather, whether the sequence is over).
The type Point must satisfy the following operations.
Vector operator- (Point, Point) returns an object describing the displacement to go from the second point to the first one.
geo::vect::norm(Vector) is a function returning the magnitude of the specified displacement vector.
Definition at line 420 of file TrajectoryUtils.h.
References util::pathLength().
Referenced by util::findMiddlePointInPath(), and util::pathLength().
pathMiddlePoint()
template<typename FIter , typename LIter > auto util::pathMiddlePoint (FIter itFirst, LIter itLast, double relTarget = 0.5)
Returns the geometric point in the middle of the specified path.
Template Parameters
FIter type of iterator to a point in the path
LIter type of iterator to a point in the path
Parameters
itFirst iterator to the first point in the path
itLast iterator to the last point in the path (must be valid point)
relTarget (default: 0.5) fraction of the total length to pursue
Returns
the geometric middle point of the path
The sequence between the iterators itFirst and itLast, both included, defines a path. This function returns the point that cuts that path into two subpaths, the first of which has relTarget fraction of the length of the total path (hence, with the default relTarget value of 0.5 the two subpaths have the same length). The point usually does not match any of the points in the sequence, but rather is in between two of them.
The path is considered a sequence of straight segments connecting the points.
Example of use with a LArSoft recob::Track object (track):
auto const& path = track.Trajectory().Positions();
geo::Point_t const middle
  = util::PathMiddlePoint(path.begin(), std::prev(path.end()));
(note that here the function actually returns a recob::tracking::Point_t).
Requirements
The FIter type is a forward iterator, the type LIter is a backward iterator.
FIter must support prefix operator++, LIter must support prefix operator--().
FIter and LIter must compare equal (operator == (FIter, LIter)) if they point to the same element of the sequence.
The two iterators must point to the same type of point (called Point in the following text).
The type Point must satisfy the following operations.
Vector operator- (Point, Point) returns an object describing the displacement to go from the second point to the first one.
Point operator+ (Point, Vector) returns the point after being displaced by the specified vector.
Vector operator* (double) returns a displacement vector with its magnitude rescaled by the specified factor.
geo::vect::norm(Vector) is a function returning the magnitude of the specified displacement vector.
The returned object is an instance of Point.
LArSoft geo::Point_t type is known to satisfy the requirements of Point (geo::Vector_t being its corresponding Vector type). The modulus function geo::vect::norm() is provided for geo::Vector_t in the LArSoft header larcorealg/CoreUtils/geo_vector_utils.h.
Definition at line 398 of file TrajectoryUtils.h.
References util::findMiddlePointInPath(), util::PathPointInfo_t< Iter >::frac, util::PathPointInfo_t< Iter >::itPoint, and util::pathMiddlePoint().
Referenced by util::findMiddlePointInPath(), and util::pathMiddlePoint().