CAF format: icarus::PMTWaveformBaselines Class Reference
icarus::PMTWaveformBaselines Class Reference
Extracts the baseline of PMT waveforms.
Classes
struct Config
Public Types
using Parameters = art::EDProducer::Table<Config>
Public Member Functions
PMTWaveformBaselines (Parameters const &config)
virtual void beginJob () override
Prepares the plots to be filled.
virtual void produce (art::Event &event) override
Creates the data products.
virtual void endJob () override
Remove empty plots.
Private Member Functions
void setupPlots ()
Creates all the plots to be filled by the module.
void buildBaselineGraphs ()
Removes the empty plots.
icarus::WaveformBaseline baselineFromMedian (raw::OpDetWaveform const &waveform) const
Extracts a baseline as median from a single waveform.
Private Attributes
art::InputTag const fOpDetWaveformTag
Input optical waveform tag.
bool fPlotBaselines
Whether to produce plots.
double const fBaselineTimeAverage { 0.0 }
Width of baseline time profile binning [s].
std::string const fLogCategory
Category name for the console output stream.
std::size_t fNPlotChannels = 0U
Number of plotted channels.
TH2 * fHBaselines = nullptr
All baselines, per channel.
std::vector< std::vector< std::pair< double, double > > > fBaselinesVsTime
For each channel, all event times and their baselines.
Detailed Description
Extracts the baseline of PMT waveforms.
This module produces a baseline data product for each optical detector waveform.
The waveforms on the same channels are currently treated as independent (which is less than ideal).
Output data products
a data product of type std::vector<icarus::WaveformBaseline>, with one baseline per input waveform; the baselines are guaranteed to be in the same order as the waveforms in the input collection;
an art association, one baseline per input optical waveform; normally this is not needed as long as the original PMT waveform data product is available; the type of the association is art::Assns<icarus::WaveformBaseline, raw::OpDetWaveform>.
Output plots
Baselines: baseline distribution, per channel; average baseline [ADC] per event per channel; all waveforms on the same channels in a single event contribute to the average, and channels with no waveforms in an event do not contribute an entry for that event.
Input data products
std::vector<raw::OpDetWaveform>: a single waveform for each recorded optical detector activity; the activity belongs to a single channel, but there may be multiple waveforms on the same channel.
Service requirements
TFileService and Geometry if PlotBaselines is enabled
Configuration parameters
A terse description of the parameters is printed by running lar --print-description PMTWaveformBaselines.
OpticalWaveforms (input tag, mandatory): the data product containing all optical detector waveforms;
OutputCategory (string, default: "PMTWaveformBaselines"): label for the category of messages in the console output; this is the label that can be used for filtering messages via MessageFacility service configuration;
PlotBaselines (flag, default: true): whether to produce distributions of the extracted baselines.
BaselineTimeAverage (real number, default: 600.0): binning of the baseline profile vs. time, in seconds. Requires PlotBaselines to be set.
Definition at line 116 of file PMTWaveformBaselines_module.cc.
Class Documentation
icarus::PMTWaveformBaselines::Config
struct icarus::PMTWaveformBaselines::Config
Definition at line 121 of file PMTWaveformBaselines_module.cc.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
Atom< double > BaselineTimeAverage
Atom< InputTag > OpticalWaveforms
Atom< string > OutputCategory
Atom< bool > PlotBaselines
Member Typedef Documentation
Parameters
using icarus::PMTWaveformBaselines::Parameters = art::EDProducer::Table<Config>
Definition at line 152 of file PMTWaveformBaselines_module.cc.
Constructor & Destructor Documentation
PMTWaveformBaselines()
icarus::PMTWaveformBaselines::PMTWaveformBaselines (Parameters const & config) explicit
Definition at line 249 of file PMTWaveformBaselines_module.cc.
Member Function Documentation
baselineFromMedian()
icarus::WaveformBaseline icarus::PMTWaveformBaselines::baselineFromMedian (raw::OpDetWaveform const & waveform) const private
Extracts a baseline as median from a single waveform.
Definition at line 477 of file PMTWaveformBaselines_module.cc.
beginJob()
void icarus::PMTWaveformBaselines::beginJob () override virtual
Prepares the plots to be filled.
Definition at line 284 of file PMTWaveformBaselines_module.cc.
References fPlotBaselines, and setupPlots().
buildBaselineGraphs()
void icarus::PMTWaveformBaselines::buildBaselineGraphs () private
Removes the empty plots.
Definition at line 414 of file PMTWaveformBaselines_module.cc.
endJob()
void icarus::PMTWaveformBaselines::endJob () override virtual
Remove empty plots.
Definition at line 382 of file PMTWaveformBaselines_module.cc.
produce()
void icarus::PMTWaveformBaselines::produce (art::Event & event) override virtual
Creates the data products.
Definition at line 295 of file PMTWaveformBaselines_module.cc.
References icarus::WaveformBaseline::baseline().
setupPlots()
void icarus::PMTWaveformBaselines::setupPlots () private
Creates all the plots to be filled by the module.
Definition at line 390 of file PMTWaveformBaselines_module.cc.
Referenced by beginJob().
Member Data Documentation
fBaselinesVsTime
std::vector<std::vector<std::pair<double, double> > > icarus::PMTWaveformBaselines::fBaselinesVsTime private
For each channel, all event times and their baselines.
Definition at line 205 of file PMTWaveformBaselines_module.cc.
fBaselineTimeAverage
double const icarus::PMTWaveformBaselines::fBaselineTimeAverage { 0.0 } private
Width of baseline time profile binning [s].
Definition at line 185 of file PMTWaveformBaselines_module.cc.
fHBaselines
TH2* icarus::PMTWaveformBaselines::fHBaselines = nullptr private
All baselines, per channel.
Definition at line 202 of file PMTWaveformBaselines_module.cc.
fLogCategory
std::string const icarus::PMTWaveformBaselines::fLogCategory private
Category name for the console output stream.
Definition at line 187 of file PMTWaveformBaselines_module.cc.
fNPlotChannels
std::size_t icarus::PMTWaveformBaselines::fNPlotChannels = 0U private
Number of plotted channels.
Definition at line 201 of file PMTWaveformBaselines_module.cc.
fOpDetWaveformTag
art::InputTag const icarus::PMTWaveformBaselines::fOpDetWaveformTag private
Input optical waveform tag.
Definition at line 180 of file PMTWaveformBaselines_module.cc.
fPlotBaselines
bool icarus::PMTWaveformBaselines::fPlotBaselines private
Whether to produce plots.
Definition at line 182 of file PMTWaveformBaselines_module.cc.
Referenced by beginJob().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/PMTWaveformBaselines_module.cc