CAF format: HitMerger Class Reference
HitMerger Class Reference
Public Member Functions
HitMerger (fhicl::ParameterSet const &pset)
virtual ~HitMerger ()
Destructor.
virtual void reconfigure (fhicl::ParameterSet const &pset)
virtual void produce (art::Event &e)
virtual void beginJob ()
Begin job method.
virtual void endJob ()
End job method.
Private Types
using RecobHitToPtrMap = std::unordered_map<const recob::Hit*, art::Ptr<recob::Hit>>
using HitPtrVector = std::vector<art::Ptr<recob::Hit>>
Private Member Functions
void makeWireAssns (const art::Event &, art::Assns< recob::Wire, recob::Hit > &, RecobHitToPtrMap &) const
Create recob::Wire to recob::Hit associations.
void makeRawDigitAssns (const art::Event &, art::Assns< raw::RawDigit, recob::Hit > &, RecobHitToPtrMap &) const
Create raw::RawDigit to recob::Hit associations.
Private Attributes
std::vector< art::InputTag > HitMergerfHitProducerLabelVec
The full collection of hits.
Detailed Description
Definition at line 40 of file HitMerger_module.cc.
Member Typedef Documentation
HitPtrVector
using HitMerger::HitPtrVector = std::vector<art::Ptr<recob::Hit>> private
Definition at line 68 of file HitMerger_module.cc.
RecobHitToPtrMap
using HitMerger::RecobHitToPtrMap = std::unordered_map<const recob::Hit*, art::Ptr<recob::Hit>> private
Definition at line 55 of file HitMerger_module.cc.
Constructor & Destructor Documentation
HitMerger()
HitMerger::HitMerger (fhicl::ParameterSet const & pset) explicit
Constructor.
Arguments:
pset - Fcl parameters.
Definition at line 83 of file HitMerger_module.cc.
~HitMerger()
HitMerger::~HitMerger () virtual
Destructor.
Definition at line 97 of file HitMerger_module.cc.
Member Function Documentation
beginJob()
void HitMerger::beginJob () virtual
Begin job method.
Definition at line 114 of file HitMerger_module.cc.
endJob()
void HitMerger::endJob () virtual
End job method.
Definition at line 270 of file HitMerger_module.cc.
makeRawDigitAssns()
void HitMerger::makeRawDigitAssns (const art::Event & evt, art::Assns< raw::RawDigit, recob::Hit > & rawDigitAssns, RecobHitToPtrMap & recobHitPtrMap) const private
Create raw::RawDigit to recob::Hit associations.
Definition at line 226 of file HitMerger_module.cc.
References HitMergerfHitProducerLabelVec.
Referenced by produce().
makeWireAssns()
void HitMerger::makeWireAssns (const art::Event & evt, art::Assns< recob::Wire, recob::Hit > & wireAssns, RecobHitToPtrMap & recobHitPtrMap) const private
Create recob::Wire to recob::Hit associations.
Definition at line 184 of file HitMerger_module.cc.
References HitMergerfHitProducerLabelVec.
Referenced by produce().
produce()
void HitMerger::produce (art::Event & evt) virtual
Produce method.
Arguments:
evt - Art event.
This is the primary method. The goal is to merge input hit collections and output a single hit collection on the backside.
Associations with wires.
Associations with raw digits.
Definition at line 131 of file HitMerger_module.cc.
References HitMergerfHitProducerLabelVec, makeRawDigitAssns(), and makeWireAssns().
reconfigure()
void HitMerger::reconfigure (fhicl::ParameterSet const & pset) virtual
Reconfigure method.
Arguments:
pset - Fcl parameter set.
Definition at line 107 of file HitMerger_module.cc.
References HitMergerfHitProducerLabelVec.
Member Data Documentation
HitMergerfHitProducerLabelVec
std::vector<art::InputTag> HitMerger::HitMergerfHitProducerLabelVec private
The full collection of hits.
Definition at line 71 of file HitMerger_module.cc.
Referenced by makeRawDigitAssns(), makeWireAssns(), produce(), and reconfigure().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/TPC/SignalProcessing/HitFinder/HitMerger_module.cc