CAF format: sbn::PMTconfiguration Struct Reference
sbn::PMTconfiguration Struct Reference
Class containing configuration for PMT readout.
#include <PMTconfiguration.h>
Public Member Functions
bool operator== (PMTconfiguration const &other) const
Comparison: all fields need to have the same values.
bool operator!= (PMTconfiguration const &other) const
void dump (std::ostream &out, std::string const &indent, std::string const &firstIndent, unsigned int verbosity=MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, std::string const &indent="") const
Dumps the content of the configuration into out stream.
void dump (std::ostream &out, unsigned int verbosity, std::string const &indent="") const
Dumps the content of the configuration into out stream.
Public Attributes
std::vector< sbn::V1730Configuration > boards
Configuration of all PMT readout boards.
Static Public Attributes
static constexpr unsigned int MaxDumpVerbosity = V1730Configuration::MaxDumpVerbosity + 1U
Maximum supported verbosity level supported by dump().
static constexpr unsigned int DefaultDumpVerbosity = MaxDumpVerbosity
Default verbosity level for dump().
Detailed Description
Class containing configuration for PMT readout.
This is an informative class containing configuration of all V1730 boards extracted from some other source (typically, DAQ) made readily available to the users.
This class does not include any configuration extraction code.
The class is default-constructible only, and its content needs to be added element by element.
Definition at line 45 of file PMTconfiguration.h.
Member Function Documentation
dump() [1/3]
void sbn::PMTconfiguration::dump (std::ostream & out, std::string const & indent, std::string const & firstIndent, unsigned int verbosity = MaxDumpVerbosity) const
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation string
firstIndent special indentation string for the first line
verbosity (default: DefaultDumpVerbosity) level of verbosity
The indentation string is prepended to each new line of the dump. The first line indentation string is prepended before the first line of the dump. The dump ends on a new empty line.
The amount of information printed depends on the verbosity level:
0: only the number of boards in the configuration
1: information on each board, as in V1730Configuration::dump() with verbosity one level smaller than the value of verbosity argument
Definition at line 22 of file PMTconfiguration.cxx.
References boards, sbn::V1730Configuration::dump(), and MaxDumpVerbosity.
Referenced by sbn::DumpPMTconfiguration::beginRun(), dump(), and dump().
dump() [2/3]
void sbn::PMTconfiguration::dump (std::ostream & out, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent indentation level
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with same first indentation level as the rest, and default verbosity.
Definition at line 111 of file PMTconfiguration.h.
References dump().
dump() [3/3]
void sbn::PMTconfiguration::dump (std::ostream & out, unsigned int verbosity, std::string const & indent = "") const inline
Dumps the content of the configuration into out stream.
Parameters
out stream to dump the information into
indent (default: none) indentation string
See also
dump(std::ostream&, std::string const&, std::string const&, unsigned int) const
Version of dump() with the specified verbosity level and same first indentation level as the rest.
Definition at line 123 of file PMTconfiguration.h.
References dump().
operator!=()
bool sbn::PMTconfiguration::operator!= (PMTconfiguration const & other) const inline
Definition at line 60 of file PMTconfiguration.h.
operator==()
bool sbn::PMTconfiguration::operator== (sbn::PMTconfiguration const & other) const inline
Comparison: all fields need to have the same values.
Definition at line 138 of file PMTconfiguration.h.
Member Data Documentation
boards
std::vector<sbn::V1730Configuration> sbn::PMTconfiguration::boards
Configuration of all PMT readout boards.
Definition at line 52 of file PMTconfiguration.h.
Referenced by dump(), icarus::PMTconfigurationExtractor::extract(), icarus::PMTconfigurationExtractor::finalize(), and icarus::PMTWaveformBaselinesFromChannelData::getPretriggerBuffer().
DefaultDumpVerbosity
unsigned int sbn::PMTconfiguration::DefaultDumpVerbosity = MaxDumpVerbosity static constexpr
Default verbosity level for dump().
Definition at line 76 of file PMTconfiguration.h.
MaxDumpVerbosity
unsigned int sbn::PMTconfiguration::MaxDumpVerbosity = V1730Configuration::MaxDumpVerbosity + 1U static constexpr
Maximum supported verbosity level supported by dump().
Definition at line 72 of file PMTconfiguration.h.
Referenced by dump().
The documentation for this struct was generated from the following files:
sbnobj/sbnobj/Common/PMT/Data/PMTconfiguration.h
sbnobj/sbnobj/Common/PMT/Data/PMTconfiguration.cxx