CAF format: phot::ICARUSPhotonMappingTransformations Class Reference
phot::ICARUSPhotonMappingTransformations Class Reference
Photon library mapping for ICARUS geometry.
#include <ICARUSPhotonMappingTransformations.h>
Classes
struct Config
Public Types
using Parameters = art::ToolConfigTable<Config>
Public Member Functions
ICARUSPhotonMappingTransformations (Config const &config)
Constructor.
ICARUSPhotonMappingTransformations (Parameters const &config)
Constructor: ignores the configuration.
template<typename OutputIndex , typename InputIndex , template< typename... > typename Container>
auto invertMapping (Container< OutputIndex > const &directMap, std::size_t size, InputIndex invalidIndex) -> Container< InputIndex >
Inverts a given mapping.
Geometry mapping interface
virtual geo::Point_t detectorToLibrary (geo::Point_t const &location) const override
Returns the representation within the library of a detector location.
Optical detector mapping interface
virtual LibraryIndex_t opDetToLibraryIndex (geo::Point_t const &location, OpDetID_t opDetID) const override
Returns the library index for the specified optical detector.
virtual OpDetID_t libraryIndexToOpDet (geo::Point_t const &location, LibraryIndex_t libIndex) const override
Returns the optical detector ID for the specified library index.
virtual OpDetToLibraryIndexMap const & opDetsToLibraryIndices (geo::Point_t const &location) const override
Returns a map of library indices as function of optical detectors.
virtual std::size_t opDetMappingSize () const override
Expected number of mappings of optical detector into library index.
virtual LibraryIndexToOpDetMap const & libraryIndicesToOpDets (geo::Point_t const &location) const override
Returns a map of identifiers of optical detectors for each library index, for the library appropriate around location
virtual std::size_t libraryMappingSize (geo::Point_t const &location) const override
Expected size of the mapping from library to optical detectors.
Protected Member Functions
geo::CryostatID whichCryostat (geo::Point_t const &point) const
Returns which cryostat better contain point. Never invalid so far.
OpDetToLibraryIndexMap const & opDetsToLibraryIndicesImpl (geo::Point_t const &location) const
LibraryIndexToOpDetMap const & libraryIndicesToOpDetsImpl (geo::Point_t const &location) const
void prepareGeometryMapping ()
void prepareLibraryMappings (LibraryIndexToOpDetMap const &libraryIndices)
void prepareMappings (LibraryIndexToOpDetMap const &libraryIndices)
Extracts the necessary information for mapping from the geometry.
void dumpMapping () const
Writes the current mapping information into the console. Debug stuff.
Static Protected Member Functions
template<typename OutputIndex , typename InputIndex , template< typename... > typename Container>
static Container< InputIndex > invertMapping (Container< OutputIndex > const &directMap, std::size_t size, InputIndex invalidIndex)
Inverts a given mapping.
Protected Attributes
bool fDumpMapping = false
Whether to dump mapping on initialization.
geo::GeometryCore const * fGeom = nullptr
Detector geometry service provider. Not really used.
std::vector< geo::Vector_t > fTranslations
Translation of the point.
geo::Length_t fSwitchPoint
Switch coordinate on x axis [cm].
unsigned int fNOpDetChannels
std::vector< int > fChannelShifts
Amount of channel number shifting indexed by cryostat. Not really used.
std::vector< LibraryIndexToOpDetMap > fLibraryIndexToOpDetMaps
Library to detector channel mappings, indexed by cryostat number.
LibraryIndexToOpDetMap fInvalidLibraryIndexToOpDetMap
A library-to-detector mapping for invalid points.
std::vector< OpDetToLibraryIndexMap > fOpDetToLibraryIndexMaps
Detector channel to library mappings, indexed by cryostat number.
OpDetToLibraryIndexMap fInvalidOpDetToLibraryIndexMap
A detector-to-library mapping for invalid points.
Detailed Description
Photon library mapping for ICARUS geometry.
This is an implementation of phot::IPhotonMappingTransformation interface to exploit ICARUS detector symmetries.
The current implementation only exploits the fact that the two cryostats are identical, and ignores the symmetry respect to the cathode within each of the cryostats.
The required library is expected to cover the first 180 PMT channels (the ones pertaining the first cryostat, C:0), and the full volume of the TPC.
When requested a point in the first cryostat (C:0), the point is used directly in the visibility library to get visibility on PMT channels 0 to 179 (the lower half). The mapping then maps the remaining PMT channels (180 to 359) to be invalid and with default value of 0.
When requested a point in the other cryostat (C:1), the point is translated into the first one to get visibility of PMT channels 0 to 179 (the lower half). The mapping then translates those channels into the range 180 to 359, and maps the remaining PMT channels (0 to 179) to be invalid and with default value of 0.
Note that the content of the library for channels 180 to 359 is always ignored, and it may well be absent.
Definition at line 58 of file ICARUSPhotonMappingTransformations.h.
Class Documentation
phot::ICARUSPhotonMappingTransformations::Config
struct phot::ICARUSPhotonMappingTransformations::Config
Definition at line 63 of file ICARUSPhotonMappingTransformations.h.
Class Members
typedef Comment Comment fhicl::Comment
typedef Name Name fhicl::Name
Class Members
OptionalSequence< OpDetID_t > CryostatChannelRemap
Atom< bool > DumpMapping
Member Typedef Documentation
Parameters
using phot::ICARUSPhotonMappingTransformations::Parameters = art::ToolConfigTable<Config>
Definition at line 82 of file ICARUSPhotonMappingTransformations.h.
Constructor & Destructor Documentation
ICARUSPhotonMappingTransformations() [1/2]
phot::ICARUSPhotonMappingTransformations::ICARUSPhotonMappingTransformations (Config const & config)
Constructor.
Definition at line 30 of file ICARUSPhotonMappingTransformations.cxx.
References prepareMappings().
ICARUSPhotonMappingTransformations() [2/2]
phot::ICARUSPhotonMappingTransformations::ICARUSPhotonMappingTransformations (Parameters const & config) inline
Constructor: ignores the configuration.
Definition at line 89 of file ICARUSPhotonMappingTransformations.h.
Member Function Documentation
detectorToLibrary()
geo::Point_t phot::ICARUSPhotonMappingTransformations::detectorToLibrary (geo::Point_t const & location) const override virtual
Returns the representation within the library of a detector location.
Parameters
location position in world coordinates [cm]
Returns
a vector expressing location in the library space
The returned vector is shifted as it were on the first cryostat.
No exception is ever thrown.
Definition at line 49 of file ICARUSPhotonMappingTransformations.cxx.
dumpMapping()
void phot::ICARUSPhotonMappingTransformations::dumpMapping () const protected
Writes the current mapping information into the console. Debug stuff.
Definition at line 315 of file ICARUSPhotonMappingTransformations.cxx.
invertMapping() [1/2]
template<typename OutputIndex , typename InputIndex , template< typename... > typename Container> static Container< InputIndex > phot::ICARUSPhotonMappingTransformations::invertMapping (Container< OutputIndex > const & directMap, std::size_t size, InputIndex invalidIndex) static protected
Inverts a given mapping.
Template Parameters
OutputIndex the output index of the mapping to invert
IndexIndex the input index of the mapping to invert
Container container used for the mapping (be it std::vector)
Parameters
directMap the mapping (input index to output index) to be inverted
size the total number of output indices (some may be not mapped)
invalidIndex input index to associate to unmapped output indices
Returns
a mapping (output index to input index) reversing directMap
The resulting, "inverse" mapping has exactly size entries. If the input mapping maps out beyond that, those indices are not mapped back.
invertMapping() [2/2]
template<typename OutputIndex , typename InputIndex , template< typename... > typename Container> auto phot::ICARUSPhotonMappingTransformations::invertMapping (Container< OutputIndex > const & directMap, std::size_t size, InputIndex invalidIndex) -> Container<InputIndex>
Inverts a given mapping.
Template Parameters
OutputIndex the output index of the mapping to invert
IndexIndex the input index of the mapping to invert
Container type of container used for the mapping (be it std::vector)
Parameters
directMap the mapping (input index to output index) to be inverted
size the total number of output indices (some may be not mapped)
invalidIndex the input index to associate to unmapped output indices
Returns
a mapping (output index to input index) reversing directMap
The resulting, "inverse" mapping has exactly size entries. If the input mapping maps out beyond that, those indices are not mapped back.
Definition at line 332 of file ICARUSPhotonMappingTransformations.h.
libraryIndexToOpDet()
virtual OpDetID_t phot::ICARUSPhotonMappingTransformations::libraryIndexToOpDet (geo::Point_t const & location, LibraryIndex_t libIndex) const inline override virtual
Returns the optical detector ID for the specified library index.
Parameters
location where the scintillation source is in world frame [cm]
libIndex library index to be mapped
Returns
optical detector corresponding to libIndex (as used, e.g., in geo::GeometryCore::OpDetGeoFromOpDet()), or InvalidOpDetID
Exceptions
std::out_of_range if input library index can't be handled TODO not implemented this way (yet?)
See also
opDetToLibraryIndex(), libraryIndicesToOpDets()
Definition at line 144 of file ICARUSPhotonMappingTransformations.h.
libraryIndicesToOpDets()
virtual LibraryIndexToOpDetMap const & phot::ICARUSPhotonMappingTransformations::libraryIndicesToOpDets (geo::Point_t const & location) const inline override virtual
Returns a map of identifiers of optical detectors for each library index, for the library appropriate around location
Parameters
location where the scintillation source is in world frame [cm]
Returns
optical detector identifiers for all library indices
See also
opDetsToLibraryIndices(), libraryIndexToOpDet()
We use this mapping when we have information from the visibility library appropriate for a source at the specified location: this information is addressed via a "library index" with the reduced range (i.e. 0 to 179) and we need to know which are the optical detector channels that visibility covers.
For ICARUS, this mapping is expected to be straightforward:
[ 0, 179 ] => [ 0, 179 ] if location is in the first cryostat (C:0)
[ 0, 179 ] => [ 180, 359 ] if location is in the other one (C:1)
The specified location is used to provide context in a similar fashion as detectorToLibrary() does. It can be used to choose the correct mapping among the available ones.
The returned value is a mapping object (see LibraryIndexToOpDetMap documentation for the interface). If a library index does not map to any optical detector in the library at location (which is unusual!), the optical detector ID corresponding to it is InvalidOpDetID.
Definition at line 198 of file ICARUSPhotonMappingTransformations.h.
Referenced by libraryMappingSize().
libraryIndicesToOpDetsImpl()
auto phot::ICARUSPhotonMappingTransformations::libraryIndicesToOpDetsImpl (geo::Point_t const & location) const protected
Definition at line 68 of file ICARUSPhotonMappingTransformations.cxx.
libraryMappingSize()
virtual std::size_t phot::ICARUSPhotonMappingTransformations::libraryMappingSize (geo::Point_t const & location) const inline override virtual
Expected size of the mapping from library to optical detectors.
Parameters
location where the scintillation source is in world frame [cm]
Returns
the expected size of the mapping from library indices to optical detectors
See also
libraryIndicesToOpDets()
This is effectively the size of the mapping returned by libraryIndicesToOpDets(). It represents how many library indices are provided by the library for the specified location, that is 180.
Definition at line 213 of file ICARUSPhotonMappingTransformations.h.
References libraryIndicesToOpDets().
opDetMappingSize()
virtual std::size_t phot::ICARUSPhotonMappingTransformations::opDetMappingSize () const inline override virtual
Expected number of mappings of optical detector into library index.
Returns
the expected size of the mapping of optical detectors
See also
opDetsToLibraryIndices()
This is effectively the number of available optical detectors, as well as the size of the mapping as returned by opDetsToLibraryIndices().
Definition at line 168 of file ICARUSPhotonMappingTransformations.h.
opDetsToLibraryIndices()
virtual OpDetToLibraryIndexMap const & phot::ICARUSPhotonMappingTransformations::opDetsToLibraryIndices (geo::Point_t const & location) const inline override virtual
Returns a map of library indices as function of optical detectors.
Parameters
location where the scintillation source is in world frame [cm]
Returns
library indices for all optical detectors
See also
opDetToLibraryIndex(), opDetsToLibraryIndices()
Definition at line 155 of file ICARUSPhotonMappingTransformations.h.
opDetsToLibraryIndicesImpl()
auto phot::ICARUSPhotonMappingTransformations::opDetsToLibraryIndicesImpl (geo::Point_t const & location) const protected
Definition at line 58 of file ICARUSPhotonMappingTransformations.cxx.
opDetToLibraryIndex()
virtual LibraryIndex_t phot::ICARUSPhotonMappingTransformations::opDetToLibraryIndex (geo::Point_t const & location, OpDetID_t opDetID) const inline override virtual
Returns the library index for the specified optical detector.
Parameters
location where the scintillation source is in world frame [cm]
opDetID optical detector identifier (as used, e.g., in geo::GeometryCore::OpDetGeoFromOpDet())
Returns
index corresponding to opDetID, or InvalidLibraryIndex
Exceptions
std::out_of_range if input optical detector ID can't be handled TODO not implemented this way (yet?)
See also
opDetFromLibrary()
The mapping reduces the optical detector ID to the corresponding one in the first cryostat.
Definition at line 131 of file ICARUSPhotonMappingTransformations.h.
prepareGeometryMapping()
void phot::ICARUSPhotonMappingTransformations::prepareGeometryMapping () protected
Definition at line 78 of file ICARUSPhotonMappingTransformations.cxx.
prepareLibraryMappings()
void phot::ICARUSPhotonMappingTransformations::prepareLibraryMappings (LibraryIndexToOpDetMap const & libraryIndices) protected
Definition at line 115 of file ICARUSPhotonMappingTransformations.cxx.
prepareMappings()
void phot::ICARUSPhotonMappingTransformations::prepareMappings (LibraryIndexToOpDetMap const & libraryIndices) protected
Extracts the necessary information for mapping from the geometry.
Definition at line 259 of file ICARUSPhotonMappingTransformations.cxx.
Referenced by ICARUSPhotonMappingTransformations().
whichCryostat()
geo::CryostatID phot::ICARUSPhotonMappingTransformations::whichCryostat (geo::Point_t const & point) const inline protected
Returns which cryostat better contain point. Never invalid so far.
Definition at line 262 of file ICARUSPhotonMappingTransformations.h.
References fSwitchPoint.
Member Data Documentation
fChannelShifts
std::vector<int> phot::ICARUSPhotonMappingTransformations::fChannelShifts protected
Amount of channel number shifting indexed by cryostat. Not really used.
Total number of optical detector channels.
Definition at line 247 of file ICARUSPhotonMappingTransformations.h.
fDumpMapping
bool phot::ICARUSPhotonMappingTransformations::fDumpMapping = false protected
Whether to dump mapping on initialization.
Definition at line 226 of file ICARUSPhotonMappingTransformations.h.
fGeom
geo::GeometryCore const* phot::ICARUSPhotonMappingTransformations::fGeom = nullptr protected
Detector geometry service provider. Not really used.
Definition at line 233 of file ICARUSPhotonMappingTransformations.h.
fInvalidLibraryIndexToOpDetMap
LibraryIndexToOpDetMap phot::ICARUSPhotonMappingTransformations::fInvalidLibraryIndexToOpDetMap protected
A library-to-detector mapping for invalid points.
Definition at line 251 of file ICARUSPhotonMappingTransformations.h.
fInvalidOpDetToLibraryIndexMap
OpDetToLibraryIndexMap phot::ICARUSPhotonMappingTransformations::fInvalidOpDetToLibraryIndexMap protected
A detector-to-library mapping for invalid points.
Definition at line 255 of file ICARUSPhotonMappingTransformations.h.
fLibraryIndexToOpDetMaps
std::vector<LibraryIndexToOpDetMap> phot::ICARUSPhotonMappingTransformations::fLibraryIndexToOpDetMaps protected
Library to detector channel mappings, indexed by cryostat number.
Definition at line 249 of file ICARUSPhotonMappingTransformations.h.
fNOpDetChannels
unsigned int phot::ICARUSPhotonMappingTransformations::fNOpDetChannels protected
Definition at line 245 of file ICARUSPhotonMappingTransformations.h.
fOpDetToLibraryIndexMaps
std::vector<OpDetToLibraryIndexMap> phot::ICARUSPhotonMappingTransformations::fOpDetToLibraryIndexMaps protected
Detector channel to library mappings, indexed by cryostat number.
Definition at line 253 of file ICARUSPhotonMappingTransformations.h.
fSwitchPoint
geo::Length_t phot::ICARUSPhotonMappingTransformations::fSwitchPoint protected
Switch coordinate on x axis [cm].
Definition at line 240 of file ICARUSPhotonMappingTransformations.h.
Referenced by whichCryostat().
fTranslations
std::vector<geo::Vector_t> phot::ICARUSPhotonMappingTransformations::fTranslations protected
Translation of the point.
Definition at line 239 of file ICARUSPhotonMappingTransformations.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/LibraryMappingTools/ICARUSPhotonMappingTransformations.h
icaruscode/icaruscode/PMT/LibraryMappingTools/ICARUSPhotonMappingTransformations.cxx