CAF format: recob::OpHitTimeSelector Class Reference
recob::OpHitTimeSelector Class Reference
Extracts a configured time from reconstructed optical hits.
#include <OpHitTimeSelector.h>
Public Types
enum class Type { Peak , Start , Rise }
Type of optical hit reconstructed time.
Public Member Functions
OpHitTimeSelector (Type timeType=DefaultType)
OpHitTimeSelector (std::string const &timeTypeName)
Time type extraction management
Type getType () const
Returns the type of time being extracted.
std::string getTypeName () const
Returns the type of time being extracted.
Type selectType (Type newType)
Type selectType (std::string const &newTypeName)
Static Public Attributes
static constexpr Type DefaultType { Type::Peak }
Type used for default construction.
static util::MultipleChoiceSelection< Type > const TypeSelector
Helper to convert a type from and to a string.
Private Types
using TimeProc_t = double (*)(recob::OpHit const&)
Type of method of this class used to extract the time.
Static Private Member Functions
static double relToAbs (recob::OpHit const &opHit)
static double extractPeakTime (recob::OpHit const &opHit)
static double extractStartTime (recob::OpHit const &opHit)
static double extractRiseTime (recob::OpHit const &opHit)
static TimeProc_t selectTimeProc (Type type)
Returns the method to extract the specified time type.
static Type parseTypeName (std::string const &name)
Returns the type associated to the specified name (or alias).
Private Attributes
Type fType
Type of time being extracted (for book-keeping).
TimeProc_t fTimeProc
Pointer to the method extracting the right time.
Time extraction
double operator() (recob::OpHit const &opHit) const
double timeOf (recob::OpHit const &opHit) const
double absTimeOf (recob::OpHit const &opHit) const
detinfo::timescales::electronics_time elecTimeOf (recob::OpHit const &opHit) const
static double timeOf (recob::OpHit const &opHit, Type type)
static double absTimeOf (recob::OpHit const &opHit, Type type)
static detinfo::timescales::electronics_time elecTimeOf (recob::OpHit const &opHit, Type type)
Detailed Description
Extracts a configured time from reconstructed optical hits.
This class provides three functionalities:
Type: an enumerator listing all the optical hit times supported by the extractor;
timeOf() (also operator()): returns the type of time configured in the object;
timeOf() (static version): returns the type of time specified as argument.
Note that the exact definition of each of the times depends on the algorithm used for the reconstruction of optical hits.
Example of usage:
recob::OpHitTimeSelector const hitTime { recob::OpHitTimeSelector::Start };
for (recob::OpHit const& opHit: OpHits) {
  double const time = hitTime(opHit);
  // ... do something with it
}
The supported time types are defined in Type enumerator.
Definition at line 58 of file OpHitTimeSelector.h.
Member Typedef Documentation
TimeProc_t
using recob::OpHitTimeSelector::TimeProc_t = double (*)(recob::OpHit const&) private
Type of method of this class used to extract the time.
Definition at line 162 of file OpHitTimeSelector.h.
Member Enumeration Documentation
Type
enum class recob::OpHitTimeSelector::Type strong
Type of optical hit reconstructed time.
Enumerator
Peak
recob::OpHit::PeakTime(): representing the maximum light.
Start
recob::OpHit::StartTime(): representing the earliest light.
Rise
recob::OpHit::StartTime() + recob::OpHit::RiseTime(): fine reconstruction of earliest light.
Definition at line 63 of file OpHitTimeSelector.h.
Constructor & Destructor Documentation
OpHitTimeSelector() [1/2]
recob::OpHitTimeSelector::OpHitTimeSelector (Type timeType = DefaultType) inline
Initializes the extractor with the specified timeType
Parameters
timeType (default: DefaultType) the type of time to extract
Definition at line 211 of file OpHitTimeSelector.h.
OpHitTimeSelector() [2/2]
recob::OpHitTimeSelector::OpHitTimeSelector (std::string const & timeTypeName) inline
Initializes the extractor with the type specified by timeTypeName.
Parameters
timeType name of the type to extract (see TypeSelector)
Definition at line 218 of file OpHitTimeSelector.h.
Member Function Documentation
absTimeOf() [1/2]
double recob::OpHitTimeSelector::absTimeOf (recob::OpHit const & opHit) const inline
Returns the configured time of the hit, in the same scale as recob::OpHit::PeakTimeAbs().
Definition at line 128 of file OpHitTimeSelector.h.
References relToAbs(), and timeOf().
Referenced by elecTimeOf(), and elecTimeOf().
absTimeOf() [2/2]
static double recob::OpHitTimeSelector::absTimeOf (recob::OpHit const & opHit, Type type) inline static
Returns the opHit time of the specified type, in the same scale as recob::OpHit::PeakTimeAbs().
Definition at line 146 of file OpHitTimeSelector.h.
References relToAbs(), and timeOf().
elecTimeOf() [1/2]
detinfo::timescales::electronics_time recob::OpHitTimeSelector::elecTimeOf (recob::OpHit const & opHit) const inline
Returns the configured time of the hit, on the electronics time scale.
Note
Hit absolute time is assumed to be electronics time scale already.
Definition at line 134 of file OpHitTimeSelector.h.
References absTimeOf().
elecTimeOf() [2/2]
static detinfo::timescales::electronics_time recob::OpHitTimeSelector::elecTimeOf (recob::OpHit const & opHit, Type type) inline static
Returns the opHit time of the specified type, on the electronics time scale.
Note
Hit absolute time is assumed to be electronics time scale already.
Definition at line 152 of file OpHitTimeSelector.h.
References absTimeOf().
extractPeakTime()
static double recob::OpHitTimeSelector::extractPeakTime (recob::OpHit const & opHit) inline static private
Definition at line 177 of file OpHitTimeSelector.h.
extractRiseTime()
static double recob::OpHitTimeSelector::extractRiseTime (recob::OpHit const & opHit) inline static private
Definition at line 183 of file OpHitTimeSelector.h.
extractStartTime()
static double recob::OpHitTimeSelector::extractStartTime (recob::OpHit const & opHit) inline static private
Definition at line 180 of file OpHitTimeSelector.h.
getType()
Type recob::OpHitTimeSelector::getType () const inline
Returns the type of time being extracted.
Definition at line 94 of file OpHitTimeSelector.h.
References fType.
getTypeName()
std::string recob::OpHitTimeSelector::getTypeName () const inline
Returns the type of time being extracted.
Definition at line 225 of file OpHitTimeSelector.h.
operator()()
double recob::OpHitTimeSelector::operator() (recob::OpHit const & opHit) const inline
Returns the configured time of the hit, in the same scale as recob::OpHit::PeakTime().
See also
timeOf(recob::OpHit const&)
Definition at line 119 of file OpHitTimeSelector.h.
References timeOf().
parseTypeName()
static Type recob::OpHitTimeSelector::parseTypeName (std::string const & name) inline static private
Returns the type associated to the specified name (or alias).
Definition at line 193 of file OpHitTimeSelector.h.
References TypeSelector.
Referenced by selectType().
relToAbs()
double recob::OpHitTimeSelector::relToAbs (recob::OpHit const & opHit) inline static private
Returns the offset to add to a relative time to make it absolute.
Note
Assumes both recob::OpHit::PeakTime() and recob::OpHit::PeakTimeAbs() to be correctly set.
Definition at line 238 of file OpHitTimeSelector.h.
Referenced by absTimeOf(), and absTimeOf().
selectTimeProc()
auto recob::OpHitTimeSelector::selectTimeProc (Type type) inline static private
Returns the method to extract the specified time type.
Definition at line 244 of file OpHitTimeSelector.h.
Referenced by timeOf().
selectType() [1/2]
Type recob::OpHitTimeSelector::selectType (std::string const & newTypeName) inline
Changes the time type to be extracted to the one with name newTypeName.
Returns
the type that was being extracted before the change
Definition at line 105 of file OpHitTimeSelector.h.
References parseTypeName(), and selectType().
selectType() [2/2]
auto recob::OpHitTimeSelector::selectType (Type newType) inline
Changes the time type to be extracted to newType.
Returns
the type that was being extracted before the change
Definition at line 231 of file OpHitTimeSelector.h.
Referenced by selectType().
timeOf() [1/2]
double recob::OpHitTimeSelector::timeOf (recob::OpHit const & opHit) const inline
Returns the configured time of the hit, in the same scale as recob::OpHit::PeakTime().
Definition at line 123 of file OpHitTimeSelector.h.
References fTimeProc.
Referenced by absTimeOf(), absTimeOf(), and operator()().
timeOf() [2/2]
static double recob::OpHitTimeSelector::timeOf (recob::OpHit const & opHit, Type type) inline static
Returns the opHit time of the specified type, in the same scale as recob::OpHit::PeakTime().
Definition at line 141 of file OpHitTimeSelector.h.
References selectTimeProc().
Member Data Documentation
DefaultType
Type recob::OpHitTimeSelector::DefaultType { Type::Peak } static constexpr
Type used for default construction.
Definition at line 70 of file OpHitTimeSelector.h.
fTimeProc
TimeProc_t recob::OpHitTimeSelector::fTimeProc private
Pointer to the method extracting the right time.
Definition at line 167 of file OpHitTimeSelector.h.
Referenced by timeOf().
fType
Type recob::OpHitTimeSelector::fType private
Type of time being extracted (for book-keeping).
Definition at line 165 of file OpHitTimeSelector.h.
Referenced by getType().
TypeSelector
util::MultipleChoiceSelection< recob::OpHitTimeSelector::Type > const recob::OpHitTimeSelector::TypeSelector inline static
Initial value:
{
    { Type::Peak,  "Peak",  "PeakTime" }
  , { Type::Start, "Start", "StartTime" }
  , { Type::Rise,  "Rise",  "RiseTime" }
}
Helper to convert a type from and to a string.
Definition at line 203 of file OpHitTimeSelector.h.
Referenced by recob::opHitTimeType(), and parseTypeName().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/OpReco/Algorithms/OpHitTimeSelector.h