CAF format: daq::details::BoardSetup_t Struct Reference
daq::details::BoardSetup_t Struct Reference
Information of the setup of a V1730 readout board.
#include <PMTDecoderUtils.h>
Classes
struct ChannelSetup_t
Special settings for one channel on the board.
Public Types
using AllChannelSetup_t = std::array<ChannelSetup_t, NBoardChannels>
Public Member Functions
constexpr bool hasFragmentID () const
Returns whether this object contains a valid fragment ID.
Public Attributes
std::string name
Board name as specified in DAQ configuration.
unsigned int fragmentID = NoFragmentID
ID of the DAQ fragment associated to this board.
nanoseconds triggerDelay = 0_ns
Delay from global trigger to TTT set.
nanoseconds TTTresetDelay = 0_ns
Delay from TTT reset issue to enact.
AllChannelSetup_t channelSettings
Set of settings channel by channel.
Static Public Attributes
static constexpr std::size_t NBoardChannels = 16U
< V1730B has 16 channels (can become a template parameter).
static constexpr unsigned int NoFragmentID = std::numeric_limits<unsigned int>::max()
Special value to mark the absence of fragment ID information.
Detailed Description
Information of the setup of a V1730 readout board.
Definition at line 41 of file PMTDecoderUtils.h.
Member Typedef Documentation
AllChannelSetup_t
using daq::details::BoardSetup_t::AllChannelSetup_t = std::array<ChannelSetup_t, NBoardChannels>
Definition at line 91 of file PMTDecoderUtils.h.
Member Function Documentation
hasFragmentID()
bool daq::details::BoardSetup_t::hasFragmentID () const inline constexpr
Returns whether this object contains a valid fragment ID.
Definition at line 106 of file PMTDecoderUtils.h.
References fragmentID, and NoFragmentID.
Member Data Documentation
channelSettings
AllChannelSetup_t daq::details::BoardSetup_t::channelSettings
Set of settings channel by channel.
Definition at line 103 of file PMTDecoderUtils.h.
fragmentID
unsigned int daq::details::BoardSetup_t::fragmentID = NoFragmentID
ID of the DAQ fragment associated to this board.
Definition at line 96 of file PMTDecoderUtils.h.
Referenced by hasFragmentID().
name
std::string daq::details::BoardSetup_t::name
Board name as specified in DAQ configuration.
Definition at line 93 of file PMTDecoderUtils.h.
Referenced by sortDataLoggerFiles.FileInfoClass::__init__().
NBoardChannels
std::size_t daq::details::BoardSetup_t::NBoardChannels = 16U static constexpr
< V1730B has 16 channels (can become a template parameter).
Definition at line 44 of file PMTDecoderUtils.h.
NoFragmentID
unsigned int daq::details::BoardSetup_t::NoFragmentID = std::numeric_limits<unsigned int>::max() static constexpr
Special value to mark the absence of fragment ID information.
Definition at line 47 of file PMTDecoderUtils.h.
Referenced by icarus::convert(), hasFragmentID(), and icarus::DaqDecoderICARUSPMT::matchBoardConfigurationAndSetup().
triggerDelay
nanoseconds daq::details::BoardSetup_t::triggerDelay = 0_ns
Delay from global trigger to TTT set.
Definition at line 98 of file PMTDecoderUtils.h.
TTTresetDelay
nanoseconds daq::details::BoardSetup_t::TTTresetDelay = 0_ns
Delay from TTT reset issue to enact.
Definition at line 100 of file PMTDecoderUtils.h.
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/details/PMTDecoderUtils.h