CAF format: daq::TriggerDecoder Class Reference
daq::TriggerDecoder Class Reference
Tool decoding the trigger information from DAQ.
Classes
struct TriggerGateTypes
Codes of gate types from the trigger hardware.
Public Member Functions
TriggerDecoder (fhicl::ParameterSet const &pset)
virtual void produces (art::ProducesCollector &) override
The space point building should output the hit collection for those hits which combine to form space points - a nice noise filter!
virtual void configure (const fhicl::ParameterSet &) override
Interface for configuring the particular algorithm tool.
virtual void initializeDataProducts () override
Initialize any data products the tool will output.
virtual void process_fragment (const artdaq::Fragment &fragment) override
Given a set of recob hits, run DBscan to form 3D clusters.
virtual void outputDataProducts (art::Event &event) override
Output the data products to the event store.
Public Member Functions inherited from daq::IDecoder
virtual ~IDecoder () noexcept=default
Virtual Destructor.
virtual void consumes (art::ConsumesCollector &)
Declare to the framework what you expect to read.
virtual void setupRun (art::Run const &run)
Preparation to process a new run.
virtual std::optional< art::InputTag > preferredInput () const
Returns the tag of the input fragment, if known (empty otherwise).
virtual void setupEvent (art::Event const &event)
Preparation to process a new event.
Private Types
using nanoseconds = util::quantities::nanosecond
using TriggerCollection = std::vector<raw::ExternalTrigger>
using TriggerPtr = std::unique_ptr<TriggerCollection>
using RelativeTriggerCollection = std::vector<raw::Trigger>
using BeamGateInfoCollection = std::vector<sim::BeamGateInfo>
using BeamGateInfoPtr = std::unique_ptr<BeamGateInfoCollection>
using ExtraInfoPtr = std::unique_ptr<sbn::ExtraTriggerInfo>
Private Member Functions
icarus::ICARUSTriggerUDPFragment makeTriggerFragment (artdaq::Fragment const &fragment) const
Creates a ICARUSTriggerInfo from a generic fragment.
icarus::ICARUSTriggerInfo parseTriggerString (std::string_view data) const
Parses the trigger data packet with the "standard" parser.
Static Private Member Functions
static std::string_view firstLine (std::string const &s, std::string const &endl="\0\n\r"s)
static std::uint64_t makeTimestamp (unsigned int s, unsigned int ns)
Combines second and nanosecond counts into a 64-bit timestamp.
static long long int timestampDiff (std::uint64_t a, std::uint64_t b)
Returns the difference a - b.
Private Attributes
TriggerPtr fTrigger
TriggerPtr fPrevTrigger
std::unique_ptr< RelativeTriggerCollection > fRelTrigger
ExtraInfoPtr fTriggerExtra
BeamGateInfoPtr fBeamGateInfo
bool fDiagnosticOutput
bool fDebug
long fLastEvent = 0
detinfo::DetectorTimings const fDetTimings
Detector clocks and timings.
Static Private Attributes
static std::string const CurrentTriggerInstanceName {}
Name of the data product instance for the current trigger.
static std::string const PreviousTriggerInstanceName { "previous" }
Name of the data product instance for the previous trigger.
static constexpr double UnknownBeamTime = std::numeric_limits<double>::max()
static constexpr nanoseconds BNBgateDuration { 1600. }
static constexpr nanoseconds NuMIgateDuration { 9500. }
Detailed Description
Tool decoding the trigger information from DAQ.
Produces:
std::vector<raw::ExternalTrigger> containing the absolute trigger time stamp from the White Rabbit system, and a trigger count; it always includes a single entry (zero might be supported).
std::vector<raw::Trigger> containing:
TriggerTime(): the relative time of the trigger as reported in the White Rabbit timestamp, measured in the electronics time scale (for ICARUS it will always be detinfo::DetectorClocksData::TriggerTime()).
BeamGateTime(): relative time of the announced arrival of the beam (currently not available) also in electronics time scale.
TriggerCount(): the trigger count from the beginning of the run.
TriggerBits(): includes the beam(s) with an open gate when the trigger happened (currently only one beam gate per trigger); definitions are in sbn::beamType namespace.
It always includes a single entry (zero might be supported).
std::vector<sim::BeamGateInfo> containing information on the "main" beam gate associated to each trigger (a way to say that if by any chance there are more than one bits set for the trigger, this gate will pick only one of them):
Start(): relative time of the announced arrival of the beam (currently not available), in simulation time scale.
Width(): duration of the gate, in nanoseconds; currently set to a nominal value.
BeamType(): the type of the beam gate being described (BNB, NuMI).
sbn::ExtraTriggerInfo: the most complete collection of information, duplicating also some from the other data products. Some of the information is not available yet: if a count is not available, its value is set to 0 (which is an invalid value because their valid range starts with 1 since they include the current event), and if a timestamp is not available it is set to sbn::ExtraTriggerInfo::NoTimestamp; these two conditions can be checked with static methods sbn::ExtraTriggerInfo::isValidTimestamp() and sbn::ExtraTriggerInfo::isValidCount() respectively. Note that differently from the usual, this is a single object, not a collection; also, this data product has no instance name. The information already available includes:
sourceType: the type of beam or trigger source, a value from sbn::triggerSource (equivalent to raw::Trigger::TriggerBits(), but in the form of an enumerator rather than a bit mask).
triggerTimestamp: same as raw::ExternalTrigger::GetTrigTime() (nanoseconds from the Epoch, Coordinated Universal Time).
beamGateTimestamp: absolute time of the beam gate opening as reported by the trigger hardware, directly comparable with triggerTimestamp (same scale and unit).
triggerID: same as raw::ExternalTrigger::GetTrigID(). Should match the event number.
gateID: the count of gates since the beginning of the run, as reported by the trigger hardware.
Besides the main data product (empty instance name) an additional std::vector<raw::ExternalTrigger> data product with instance name "previous" is also produced, which relays the same kind of information but for the previous trigger. This information also comes from the trigger DAQ. If no previous trigger is available, this collection will be empty.
Timestamps and corrections
The reference trigger time is driven by the trigger fragment time, which is expected to have been derived from the actual trigger time from the White Rabbit system properly corrected to UTC by the board reader.
All absolute timestamps are corrected to be on that same scale. The absolute timestamps related to the White Rabbit time are added an offset to achieve this correction; this offset is stored in the data product (sbn::ExtraTriggerInfo::WRtimeToTriggerTime).
Definition at line 128 of file TriggerDecoder_tool.cc.
Member Typedef Documentation
BeamGateInfoCollection
using daq::TriggerDecoder::BeamGateInfoCollection = std::vector<sim::BeamGateInfo> private
Definition at line 144 of file TriggerDecoder_tool.cc.
BeamGateInfoPtr
using daq::TriggerDecoder::BeamGateInfoPtr = std::unique_ptr<BeamGateInfoCollection> private
Definition at line 145 of file TriggerDecoder_tool.cc.
ExtraInfoPtr
using daq::TriggerDecoder::ExtraInfoPtr = std::unique_ptr<sbn::ExtraTriggerInfo> private
Definition at line 146 of file TriggerDecoder_tool.cc.
nanoseconds
using daq::TriggerDecoder::nanoseconds = util::quantities::nanosecond private
Definition at line 130 of file TriggerDecoder_tool.cc.
RelativeTriggerCollection
using daq::TriggerDecoder::RelativeTriggerCollection = std::vector<raw::Trigger> private
Definition at line 143 of file TriggerDecoder_tool.cc.
TriggerCollection
using daq::TriggerDecoder::TriggerCollection = std::vector<raw::ExternalTrigger> private
Definition at line 141 of file TriggerDecoder_tool.cc.
TriggerPtr
using daq::TriggerDecoder::TriggerPtr = std::unique_ptr<TriggerCollection> private
Definition at line 142 of file TriggerDecoder_tool.cc.
Constructor & Destructor Documentation
TriggerDecoder()
daq::TriggerDecoder::TriggerDecoder (fhicl::ParameterSet const & pset) explicit
Definition at line 205 of file TriggerDecoder_tool.cc.
Member Function Documentation
configure()
void daq::TriggerDecoder::configure (const fhicl::ParameterSet &) override virtual
Interface for configuring the particular algorithm tool.
Parameters
ParameterSet The input set of parameters for configuration
Implements daq::IDecoder.
Definition at line 223 of file TriggerDecoder_tool.cc.
firstLine()
std::string_view daq::TriggerDecoder::firstLine (std::string const & s, std::string const & endl = "\0\n\r"s) static private
Definition at line 479 of file TriggerDecoder_tool.cc.
initializeDataProducts()
void daq::TriggerDecoder::initializeDataProducts () override virtual
Initialize any data products the tool will output.
Implements daq::IDecoder.
Definition at line 230 of file TriggerDecoder_tool.cc.
makeTimestamp()
static std::uint64_t daq::TriggerDecoder::makeTimestamp (unsigned int s, unsigned int ns) inline static private
Combines second and nanosecond counts into a 64-bit timestamp.
Definition at line 192 of file TriggerDecoder_tool.cc.
Referenced by process_fragment().
makeTriggerFragment()
icarus::ICARUSTriggerUDPFragment daq::TriggerDecoder::makeTriggerFragment (artdaq::Fragment const & fragment) const private
Creates a ICARUSTriggerInfo from a generic fragment.
Definition at line 243 of file TriggerDecoder_tool.cc.
Referenced by process_fragment().
outputDataProducts()
void daq::TriggerDecoder::outputDataProducts (art::Event & event) override virtual
Output the data products to the event store.
Parameters
event The event store objects
Implements daq::IDecoder.
Definition at line 468 of file TriggerDecoder_tool.cc.
References CurrentTriggerInstanceName, and PreviousTriggerInstanceName.
parseTriggerString()
icarus::ICARUSTriggerInfo daq::TriggerDecoder::parseTriggerString (std::string_view data) const private
Parses the trigger data packet with the "standard" parser.
Definition at line 265 of file TriggerDecoder_tool.cc.
Referenced by process_fragment().
process_fragment()
void daq::TriggerDecoder::process_fragment (const artdaq::Fragment & fragment) override virtual
Given a set of recob hits, run DBscan to form 3D clusters.
Parameters
fragment The artdaq fragment to process
Implements daq::IDecoder.
Definition at line 288 of file TriggerDecoder_tool.cc.
References sbn::ExtraTriggerInfo::beamGateTimestamp, sbn::bits::BNB, fDetTimings, sbn::ExtraTriggerInfo::gateID, makeTimestamp(), makeTriggerFragment(), sbn::bits::NuMI, sbn::bits::OffbeamBNB, sbn::bits::OffbeamNuMI, parseTriggerString(), sbn::ExtraTriggerInfo::sourceType, timestampDiff(), sbn::ExtraTriggerInfo::triggerID, sbn::ExtraTriggerInfo::triggerTimestamp, sbn::bits::Unknown, and sbn::ExtraTriggerInfo::WRtimeToTriggerTime.
produces()
void daq::TriggerDecoder::produces (art::ProducesCollector &) override virtual
The space point building should output the hit collection for those hits which combine to form space points - a nice noise filter!
Implements daq::IDecoder.
Definition at line 213 of file TriggerDecoder_tool.cc.
References CurrentTriggerInstanceName, and PreviousTriggerInstanceName.
timestampDiff()
static long long int daq::TriggerDecoder::timestampDiff (std::uint64_t a, std::uint64_t b) inline static private
Returns the difference a - b.
Definition at line 195 of file TriggerDecoder_tool.cc.
Referenced by process_fragment().
Member Data Documentation
BNBgateDuration
nanoseconds daq::TriggerDecoder::BNBgateDuration { 1600. } static constexpr private
Definition at line 185 of file TriggerDecoder_tool.cc.
CurrentTriggerInstanceName
std::string const daq::TriggerDecoder::CurrentTriggerInstanceName {} static private
Name of the data product instance for the current trigger.
Definition at line 170 of file TriggerDecoder_tool.cc.
Referenced by outputDataProducts(), and produces().
fBeamGateInfo
BeamGateInfoPtr daq::TriggerDecoder::fBeamGateInfo private
Definition at line 151 of file TriggerDecoder_tool.cc.
fDebug
bool daq::TriggerDecoder::fDebug private
Definition at line 153 of file TriggerDecoder_tool.cc.
fDetTimings
detinfo::DetectorTimings const daq::TriggerDecoder::fDetTimings private
Detector clocks and timings.
Definition at line 160 of file TriggerDecoder_tool.cc.
Referenced by process_fragment().
fDiagnosticOutput
bool daq::TriggerDecoder::fDiagnosticOutput private
Definition at line 152 of file TriggerDecoder_tool.cc.
fLastEvent
long daq::TriggerDecoder::fLastEvent = 0 private
Definition at line 158 of file TriggerDecoder_tool.cc.
fPrevTrigger
TriggerPtr daq::TriggerDecoder::fPrevTrigger private
Definition at line 148 of file TriggerDecoder_tool.cc.
fRelTrigger
std::unique_ptr<RelativeTriggerCollection> daq::TriggerDecoder::fRelTrigger private
Definition at line 149 of file TriggerDecoder_tool.cc.
fTrigger
TriggerPtr daq::TriggerDecoder::fTrigger private
Definition at line 147 of file TriggerDecoder_tool.cc.
fTriggerExtra
ExtraInfoPtr daq::TriggerDecoder::fTriggerExtra private
Definition at line 150 of file TriggerDecoder_tool.cc.
NuMIgateDuration
nanoseconds daq::TriggerDecoder::NuMIgateDuration { 9500. } static constexpr private
Definition at line 186 of file TriggerDecoder_tool.cc.
PreviousTriggerInstanceName
std::string const daq::TriggerDecoder::PreviousTriggerInstanceName { "previous" } static private
Name of the data product instance for the previous trigger.
Definition at line 173 of file TriggerDecoder_tool.cc.
Referenced by outputDataProducts(), and produces().
UnknownBeamTime
double daq::TriggerDecoder::UnknownBeamTime = std::numeric_limits<double>::max() static constexpr private
Definition at line 175 of file TriggerDecoder_tool.cc.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Decode/DecoderTools/TriggerDecoder_tool.cc