CAF format: util::details::ProvenanceGetter< Handle, typename > Class Template Reference
util::details::ProvenanceGetter< Handle, typename > Class Template Reference
#include <ArtHandleTrackerManager.h>
Static Public Member Functions
static std::string productClass (Handle const &handle)
Returns the name of the class pointed by the handle.
static std::type_info const * productType ()
Returns the C++ type of the handled data product.
static std::type_info const * productType (Handle const &)
Returns the C++ type of the handled data product.
static art::InputTag inputTag (Handle const &handle)
Static Private Member Functions
static art::Provenance const * provenance (Handle const &handle)
Detailed Description
template<typename Handle, typename>
class util::details::ProvenanceGetter< Handle, typename >
Helper to extract basic information from one handle. The default implementation supports art::Handle and art::ValidHandle.
Definition at line 666 of file ArtHandleTrackerManager.h.
Member Function Documentation
inputTag()
template<typename Handle , typename > static art::InputTag util::details::ProvenanceGetter< Handle, typename >::inputTag (Handle const & handle) inline static
Returns the input tag of the handled data product. Deferred implementation of inputTag().
Definition at line 689 of file ArtHandleTrackerManager.h.
productClass()
template<typename Handle , typename > static std::string util::details::ProvenanceGetter< Handle, typename >::productClass (Handle const & handle) inline static
Returns the name of the class pointed by the handle.
Definition at line 673 of file ArtHandleTrackerManager.h.
productType() [1/2]
template<typename Handle , typename > static std::type_info const * util::details::ProvenanceGetter< Handle, typename >::productType () inline static
Returns the C++ type of the handled data product.
Definition at line 680 of file ArtHandleTrackerManager.h.
Referenced by util::details::ArtHandleTracker< Event, Handle >::doProductType(), and util::details::ProvenanceGetter< Handle, typename >::productType().
productType() [2/2]
template<typename Handle , typename > static std::type_info const * util::details::ProvenanceGetter< Handle, typename >::productType (Handle const &) inline static
Returns the C++ type of the handled data product.
Definition at line 684 of file ArtHandleTrackerManager.h.
References util::details::ProvenanceGetter< Handle, typename >::productType().
provenance()
template<typename Handle , typename > static art::Provenance const * util::details::ProvenanceGetter< Handle, typename >::provenance (Handle const & handle) inline static private
Definition at line 668 of file ArtHandleTrackerManager.h.
The documentation for this class was generated from the following file:
icaruscode/icaruscode/Utilities/ArtHandleTrackerManager.h