CAF format: anonymous_namespace{DaqDecoderICARUSPMT_module.cc} Namespace Reference
anonymous_namespace{DaqDecoderICARUSPMT_module.cc} Namespace Reference
Functions
template<typename T , typename U >
T clampInto (U v)
Converts v into type T, returning min()/max() if out of T range.
template<typename T >
std::vector< T > & appendTo (std::vector< T > &dest, std::vector< T > &&src)
Moves the contend of src into the end of dest.
template<typename Coll , typename T >
bool contains (Coll const &coll, T const &value)
Returns whether an element value is found in coll.
template<typename T >
std::unique_ptr< T > moveToUniquePtr (T &data)
Moves the content of data into a std::unique_ptr.
Function Documentation
appendTo()
template<typename T > std::vector< T > & anonymous_namespace{DaqDecoderICARUSPMT_module.cc}::appendTo (std::vector< T > & dest, std::vector< T > && src)
Moves the contend of src into the end of dest.
Definition at line 1404 of file DaqDecoderICARUSPMT_module.cc.
References appendTo().
Referenced by appendTo().
clampInto()
template<typename T , typename U > T anonymous_namespace{DaqDecoderICARUSPMT_module.cc}::clampInto (U v)
Converts v into type T, returning min()/max() if out of T range.
Definition at line 1393 of file DaqDecoderICARUSPMT_module.cc.
References clampInto().
Referenced by clampInto().
contains()
template<typename Coll , typename T > bool anonymous_namespace{DaqDecoderICARUSPMT_module.cc}::contains (Coll const & coll, T const & value)
Returns whether an element value is found in coll.
Definition at line 1416 of file DaqDecoderICARUSPMT_module.cc.
References contains().
Referenced by contains().
moveToUniquePtr()
template<typename T > std::unique_ptr< T > anonymous_namespace{DaqDecoderICARUSPMT_module.cc}::moveToUniquePtr (T & data)
Moves the content of data into a std::unique_ptr.
Definition at line 1423 of file DaqDecoderICARUSPMT_module.cc.