CAF format: icarus::trigger::BeamGateStruct Struct Reference
icarus::trigger::BeamGateStruct Struct Reference
Object representing a time gate, with a start and and end.
#include <BeamGateStruct.h>
Classes
struct TimeRange
Utility class expressing a time range.
Public Types
using microseconds = util::quantities::intervals::microseconds
using electronics_time = detinfo::timescales::electronics_time
using simulation_time = detinfo::timescales::simulation_time
using optical_tick = detinfo::timescales::optical_tick
Public Member Functions
BeamGateStruct (microseconds duration, microseconds delay, detinfo::DetectorTimings const &detTimings)
Constructor: gate of specified duration and start.
bool operator== (BeamGateStruct const &other) const
Comparison operators.
bool operator!= (BeamGateStruct const &other) const
Access
icarus::trigger::OpticalTriggerGate const & asGate () const
Returns the gate as an OpticalTriggerGate (electronics time).
TimeRange< simulation_time > const & asSimulationRange () const
Returns the gate as start/stop pair in simulation time scale.
TimeRange< optical_tick > const & asOptTickRange () const
Returns the gate as start/stop pair in optical ticks.
TimeRange< electronics_time > const & asElectronicsTimeRange () const
Returns the gate as start/stop pair in electronics time scale.
template<typename Time = microseconds>
Time duration () const
Returns the time duration of the gate in the specified time unit.
Private Attributes
icarus::trigger::OpticalTriggerGate const fGate
TimeRange< electronics_time > const fRangeElec
TimeRange< simulation_time > const fRangeSim
TimeRange< optical_tick > const fRangeOpt
Detailed Description
Object representing a time gate, with a start and and end.
The object caches the gate in a few formats.
Definition at line 58 of file BeamGateStruct.h.
Member Typedef Documentation
electronics_time
using icarus::trigger::BeamGateStruct::electronics_time = detinfo::timescales::electronics_time
Definition at line 62 of file BeamGateStruct.h.
microseconds
using icarus::trigger::BeamGateStruct::microseconds = util::quantities::intervals::microseconds
Definition at line 61 of file BeamGateStruct.h.
optical_tick
using icarus::trigger::BeamGateStruct::optical_tick = detinfo::timescales::optical_tick
Definition at line 64 of file BeamGateStruct.h.
simulation_time
using icarus::trigger::BeamGateStruct::simulation_time = detinfo::timescales::simulation_time
Definition at line 63 of file BeamGateStruct.h.
Constructor & Destructor Documentation
BeamGateStruct()
icarus::trigger::BeamGateStruct::BeamGateStruct (microseconds duration, microseconds delay, detinfo::DetectorTimings const & detTimings)
Constructor: gate of specified duration and start.
Parameters
duration length of the gate [µs]
delay (default: 0_us) time the gate opens relative to beam gate opening [µs]
detTimings object used for time conversions
Definition at line 140 of file BeamGateStruct.h.
References duration().
Member Function Documentation
asElectronicsTimeRange()
TimeRange< electronics_time > const & icarus::trigger::BeamGateStruct::asElectronicsTimeRange () const inline
Returns the gate as start/stop pair in electronics time scale.
Definition at line 105 of file BeamGateStruct.h.
Referenced by duration().
asGate()
icarus::trigger::OpticalTriggerGate const & icarus::trigger::BeamGateStruct::asGate () const inline
Returns the gate as an OpticalTriggerGate (electronics time).
Definition at line 94 of file BeamGateStruct.h.
Referenced by icarus::trigger::ApplyBeamGateClass::gate(), and operator==().
asOptTickRange()
TimeRange< optical_tick > const & icarus::trigger::BeamGateStruct::asOptTickRange () const inline
Returns the gate as start/stop pair in optical ticks.
Definition at line 101 of file BeamGateStruct.h.
Referenced by icarus::trigger::ApplyBeamGateClass::tickRange().
asSimulationRange()
TimeRange< simulation_time > const & icarus::trigger::BeamGateStruct::asSimulationRange () const inline
Returns the gate as start/stop pair in simulation time scale.
Definition at line 97 of file BeamGateStruct.h.
Referenced by icarus::trigger::MakeTriggerSimulationTree::analyze(), icarus::trigger::ApplyBeamGateClass::asSimulationTime(), and icarus::trigger::ExtractEnergyDepositionSummary::produce().
duration()
template<typename Time = microseconds> Time icarus::trigger::BeamGateStruct::duration () const inline
Returns the time duration of the gate in the specified time unit.
Definition at line 110 of file BeamGateStruct.h.
References asElectronicsTimeRange().
Referenced by BeamGateStruct(), and icarus::trigger::ApplyBeamGateClass::length().
operator!=()
bool icarus::trigger::BeamGateStruct::operator!= (BeamGateStruct const & other) const inline
Definition at line 119 of file BeamGateStruct.h.
operator==()
bool icarus::trigger::BeamGateStruct::operator== (BeamGateStruct const & other) const inline
Comparison operators.
Definition at line 117 of file BeamGateStruct.h.
References asGate().
Member Data Documentation
fGate
icarus::trigger::OpticalTriggerGate const icarus::trigger::BeamGateStruct::fGate private
Definition at line 126 of file BeamGateStruct.h.
fRangeElec
TimeRange<electronics_time> const icarus::trigger::BeamGateStruct::fRangeElec private
Definition at line 128 of file BeamGateStruct.h.
fRangeOpt
TimeRange<optical_tick> const icarus::trigger::BeamGateStruct::fRangeOpt private
Definition at line 132 of file BeamGateStruct.h.
fRangeSim
TimeRange<simulation_time> const icarus::trigger::BeamGateStruct::fRangeSim private
Definition at line 130 of file BeamGateStruct.h.
The documentation for this struct was generated from the following file:
icaruscode/icaruscode/PMT/Trigger/Algorithms/BeamGateStruct.h