CAF format: icarus::trigger::OpticalTriggerGate Class Reference
icarus::trigger::OpticalTriggerGate Class Reference
Logical multi-level gate associated to one or more waveforms.
#include <OpticalTriggerGate.h>
Public Types
using GateData_t = OpticalTriggerGateData_t
Type for gate data access.
using ChannelID_t = GateData_t::ChannelID_t
Type of channel identifier.
Public Types inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
using ClockTick_t = Tick
Tick point.
using ClockTicks_t = TickInterval
Tick interval.
using ChannelID_t = ChannelIDType
Type of stored channel ID.
using GateData_t = Base_t
Type for gate data access.
using ChannelList_t = std::vector<ChannelID_t>
Type of list of associated channels.
Public Types inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
using triggergatedata_t = TriggerGateData<Tick, TickInterval>
This type.
using ClockTick_t = Tick
Type of a point in time, measured in ticks.
using ClockTicks_t = TickInterval
Type of a time interval, measured in ticks.
using OpeningCount_t = unsigned int
Type of count of number of open channels.
using OpeningDiff_t = std::make_signed_t<OpeningCount_t>
Type representing a variation of open channels.
Public Member Functions
OpticalTriggerGate ()=default
Constructor: a closed gate with no associated waveform (add() them).
OpticalTriggerGate (OpticalTriggerGate const &)=default
OpticalTriggerGate (OpticalTriggerGate &&)=default
OpticalTriggerGate & operator= (OpticalTriggerGate const &)=default
OpticalTriggerGate & operator= (OpticalTriggerGate &&)=default
OpticalTriggerGate (raw::OpDetWaveform const &waveform)
Constructor: a closed gate for the channel in waveform.
OpticalTriggerGate (ChannelID_t channel)
Constructor: a closed gate for the specified channel.
bool add (raw::OpDetWaveform const &waveform)
Adds another waveform to the gate (unless it has already been added).
OpticalTriggerGate & operator= (GateData_t const &data)
Copies/steals all the levels and channels from the specified data.
OpticalTriggerGate & operator= (GateData_t &&data)
bool operator== (OpticalTriggerGate const &) const
bool operator!= (OpticalTriggerGate const &) const
template<typename Op >
icarus::trigger::OpticalTriggerGate SymmetricCombination (Op &&op, OpticalTriggerGate const &a, OpticalTriggerGate const &b, TriggerGateTicks_t aDelay, TriggerGateTicks_t bDelay)
Query
GateData_t & gateLevels ()
Access to the underlying gate level data (mutable).
GateData_t const & gateLevels () const
Access to the underlying gate level data (immutable).
std::vector< raw::OpDetWaveform const * > waveforms () const
Public Member Functions inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
ReadoutTriggerGate ()=default
ReadoutTriggerGate (ReadoutTriggerGate const &)=default
ReadoutTriggerGate (ReadoutTriggerGate &&)=default
ReadoutTriggerGate & operator= (ReadoutTriggerGate const &)=default
ReadoutTriggerGate & operator= (ReadoutTriggerGate &&)=default
ReadoutTriggerGate (std::initializer_list< ChannelID_t > channels)
Constructor: a closed gate associated to the specified channels.
ReadoutTriggerGate & operator= (GateData_t const &data)
Copies/steals all the levels from the specified data.
ReadoutTriggerGate & operator= (GateData_t &&data)
bool hasChannels () const
Returns whether there is any channel id associated to the gate data.
bool hasChannel () const
Returns whether exactly one channel id associated to the gate data.
std::size_t nChannels () const
Returns the number of associated channels.
decltype(auto) channels () const
Returns the channels associated to the gate data.
ChannelID_t channel () const
Returns the channel associated to the gate data.
This_t & addChannel (ChannelID_t const channel)
Associates the specified channel to this readout gate.
This_t & addChannels (std::initializer_list< ChannelID_t > channels)
Associates the specified channels to this readout gate.
This_t & removeChannel (ChannelID_t const channel)
This_t & removeChannels (std::initializer_list< ChannelID_t > channels)
This_t & resetChannels ()
Removes all channel numbers from this gate.
bool operator== (ReadoutTriggerGate const &) const
bool operator!= (ReadoutTriggerGate const &) const
template<typename BIter , typename EIter >
auto mergeSortedChannelsInto (ChannelList_t &channels, BIter b, EIter e) -> ChannelList_t &
template<typename BIter , typename EIter >
auto mergeChannelsInto (ChannelList_t &channels, BIter b, EIter e) -> ChannelList_t &
template<typename Op >
auto SymmetricCombination (Op &&op, This_t const &a, This_t const &b, ClockTicks_t aDelay, ClockTicks_t bDelay) -> This_t
GateData_t const & gateLevels () const
Access to the underlying gate level data.
GateData_t & gateLevels ()
Access to the underlying gate level data (mutable).
ReadoutTriggerGate & Min (ReadoutTriggerGate const &other)
Combines with a gate, keeping the minimum opening among the two.
ReadoutTriggerGate & Max (ReadoutTriggerGate const &other)
Combines with a gate, keeping the maximum opening among the two.
ReadoutTriggerGate & Sum (ReadoutTriggerGate const &other)
Combines with a gate, keeping the sum of openings of the two.
ReadoutTriggerGate & Mul (ReadoutTriggerGate const &other)
Combines with a gate, keeping the product of openings of the two.
Public Member Functions inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
TriggerGateData ()
Constructor: a closed gate for the channel in waveform.
bool operator== (TriggerGateData const &) const
bool operator!= (TriggerGateData const &) const
template<typename Op >
auto SymmetricCombination (Op &&op, triggergatedata_t const &a, triggergatedata_t const &b, ClockTicks_t aDelay, ClockTicks_t bDelay) -> triggergatedata_t
template<typename Op >
auto findStatus (Op op, ClockTick_t start, ClockTick_t end) const -> status_const_iterator
ClockTick_t lastTick () const
Returns the number of ticks this gate covers.
OpeningCount_t openingCount (ClockTick_t tick) const
Returns the opening count of the gate at the specified tick.
bool alwaysClosed () const
Returns whether this gate never opened.
bool isOpen (ClockTick_t tick) const
Returns whether the gate is open at all at the specified tick.
ClockTick_t findOpen (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate opened.
ClockTick_t findClose (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate closed.
ClockTick_t findMaxOpen (ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate has the maximum opening.
std::pair< OpeningCount_t, OpeningCount_t > openingRange (ClockTick_t start, ClockTick_t end) const
Returns the range of trigger opening values in the specified range.
void setOpeningAt (ClockTick_t tick, OpeningCount_t openingCount)
Changes the opening to match openingCount at the specified time.
void openAt (ClockTick_t tick, OpeningDiff_t count)
Open this gate at the specified time (increase the opening by count).
void openAt (ClockTick_t tick)
Open this gate at the specified time (increase the opening by 1).
void openBetween (ClockTick_t start, ClockTick_t end, OpeningDiff_t count=1)
Open this gate at specified start tick, and close it at end tick.
void openFor (ClockTick_t tick, ClockTicks_t length, OpeningDiff_t count=1)
Open this gate at the specified time, and close it length ticks later.
void closeAt (ClockTick_t tick, OpeningDiff_t count)
Close this gate at the specified time (decrease the opening by count).
void closeAt (ClockTick_t tick)
Close this gate at the specified time.
void closeAllAt (ClockTick_t tick)
Completely close this gate at the specified time.
void clear ()
Sets the gate levels in the state at construction.
triggergatedata_t & Min (triggergatedata_t const &other)
Combines with a gate, keeping the minimum opening among the two.
triggergatedata_t & Max (triggergatedata_t const &other)
Combines with a gate, keeping the maximum opening among the two.
triggergatedata_t & Sum (triggergatedata_t const &other)
Combines with a gate, keeping the sum of openings of the two.
triggergatedata_t & Mul (triggergatedata_t const &other)
Combines with a gate, keeping the product of openings of the two.
Protected Types
using Waveforms_t = std::vector<raw::OpDetWaveform const*>
Internal list of registered waveforms.
Protected Types inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
using GateEvolution_t = typename Base_t::GateEvolution_t
Protected Types inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
using EventType = details::TriggerGateEventType
using Status = details::TriggerGateStatus<ClockTick_t, OpeningCount_t>
using GateEvolution_t = std::vector<Status>
Type to describe the time evolution of the gate.
Protected Member Functions
OpticalTriggerGate (GateEvolution_t &&gateLevel, Waveforms_t &&waveforms)
Protected constructor: set the data directly.
void registerWaveforms (Waveforms_t const &moreWaveforms)
Registers the waveforms from the specified list.
void mergeWaveformsFromGate (OpticalTriggerGate const &other)
Registers the waveforms from the other gate into this one.
Protected Member Functions inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
ReadoutTriggerGate (GateEvolution_t &&gateLevel, ChannelList_t &&channels)
Protected constructor: set the data directly.
template<typename BIter , typename EIter >
ReadoutTriggerGate (GateEvolution_t &&gateLevel, BIter b, EIter e)
Protected constructor: set the data directly.
ChannelList_t & normalizeChannels ()
Removes duplicate channel IDs and sorts the remaining ones.
void associateChannels (std::initializer_list< ChannelID_t > const &moreChannels)
Associates this data with the channels from the specified list.
void associateChannels (ChannelList_t const &moreChannels)
void associateChannelsFromGate (ReadoutTriggerGate const &other)
Associates this data with the channels from the other gate.
Protected Member Functions inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
TriggerGateData (GateEvolution_t &&gateLevel)
Protected constructor: set the data directly.
Static Protected Member Functions
static Waveforms_t mergeWaveforms (Waveforms_t const &a, Waveforms_t const &b)
Registers the waveforms from the other gate into this one.
Static Protected Member Functions inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
template<typename BIter , typename EIter >
static ChannelList_t & mergeSortedChannelsInto (ChannelList_t &channels, BIter b, EIter e)
static ChannelList_t & normalizeSortedChannels (ChannelList_t &channels)
Removes duplicate channel IDs.
static ChannelList_t & normalizeChannels (ChannelList_t &channels)
Removes duplicate channel IDs and sorts the remaining ones.
static ChannelList_t normalizeChannels (ChannelList_t &&channels)
template<typename BIter , typename EIter >
static ChannelList_t & mergeChannelsInto (ChannelList_t &channels, BIter b, EIter e)
Adds channels from iterators b to e into channels (returned).
static ChannelList_t mergeChannels (ChannelList_t const &a, ChannelList_t const &b)
Returns a merged list of channels from a and b.
Static Private Member Functions
static GateData_t::ChannelList_t extractChannels (Waveforms_t const &waveforms)
Returns the list of all channels from the waveforms (duplicate allowed).
static GateData_t::ChannelList_t waveformChannels (Waveforms_t const &waveforms)
Returns the list of all unique channels (sorted) from the waveforms.
Private Attributes
std::vector< raw::OpDetWaveform const * > fWaveforms
List of waveforms involved in this channel.
Combination operations
OpticalTriggerGate & Min (OpticalTriggerGate const &other)
Combines with a gate, keeping the minimum opening among the two.
OpticalTriggerGate & Max (OpticalTriggerGate const &other)
Combines with a gate, keeping the maximum opening among the two.
OpticalTriggerGate & Sum (OpticalTriggerGate const &other)
Combines with a gate, keeping the sum of openings of the two.
OpticalTriggerGate & Mul (OpticalTriggerGate const &other)
Combines with a gate, keeping the product of openings of the two.
static OpticalTriggerGate Min (OpticalTriggerGate const &a, OpticalTriggerGate const &b)
Returns a gate with the minimum opening between the specified two.
static OpticalTriggerGate Max (OpticalTriggerGate const &a, OpticalTriggerGate const &b)
Returns a gate with the maximum opening between the specified two.
static OpticalTriggerGate Sum (OpticalTriggerGate const &a, OpticalTriggerGate const &b)
Returns a gate with opening sum of the specified two.
static OpticalTriggerGate Mul (OpticalTriggerGate const &a, OpticalTriggerGate const &b)
Returns a gate with opening product of the specified two.
template<typename Op >
static OpticalTriggerGate SymmetricCombination (Op &&op, OpticalTriggerGate const &a, OpticalTriggerGate const &b, TriggerGateTicks_t aDelay=TriggerGateTicks_t{ 0 }, TriggerGateTicks_t bDelay=TriggerGateTicks_t{ 0 })
Returns a gate combination of the openings of two other gates.
Additional Inherited Members
Static Public Member Functions inherited from icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >
static ReadoutTriggerGate Min (ReadoutTriggerGate const &a, ReadoutTriggerGate const &b)
Returns a gate with the minimum opening between the specified two.
static ReadoutTriggerGate Max (ReadoutTriggerGate const &a, ReadoutTriggerGate const &b)
Returns a gate with the maximum opening between the specified two.
static ReadoutTriggerGate Sum (ReadoutTriggerGate const &a, ReadoutTriggerGate const &b)
Returns a gate with opening sum of the specified two.
static ReadoutTriggerGate Mul (ReadoutTriggerGate const &a, ReadoutTriggerGate const &b)
Returns a gate with opening product of the specified two.
template<typename Op >
static ReadoutTriggerGate SymmetricCombination (Op &&op, ReadoutTriggerGate const &a, ReadoutTriggerGate const &b, ClockTicks_t aDelay=ClockTicks_t{ 0 }, ClockTicks_t bDelay=ClockTicks_t{ 0 })
Returns a gate combination of the openings of two other gates.
Static Public Member Functions inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
static triggergatedata_t Min (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with the minimum opening between the specified two.
static triggergatedata_t Max (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with the maximum opening between the specified two.
static triggergatedata_t Sum (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with opening sum of the specified two.
static triggergatedata_t Mul (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with opening product of the specified two.
template<typename Op >
static triggergatedata_t SymmetricCombination (Op &&op, triggergatedata_t const &a, triggergatedata_t const &b, ClockTicks_t aDelay=ClockTicks_t{}, ClockTicks_t bDelay=ClockTicks_t{})
Returns a gate combination of the openings of two other gates.
Static Public Attributes inherited from icarus::trigger::TriggerGateData< Tick, TickInterval >
static constexpr ClockTick_t MinTick = std::numeric_limits<ClockTick_t>::min()
An unbearably small tick number.
static constexpr ClockTick_t MaxTick = std::numeric_limits<ClockTick_t>::max()
An unbearably large tick number.
Detailed Description
Logical multi-level gate associated to one or more waveforms.
This object is a trigger gate associated with one or more optical waveforms.
Note
This object should be parametrized with optical ticks (detinfo::timescales::optical_tick). But currently the quantities (util::quantity derived objects) are not well suited to be serialized by ROOT, because
they are defined in lardataalg rather than lardataobj
writing all their serialization is daunting (see how ROOT dealt with GenVector vectors for an example of how to do it) So we chicken out here and use simple data types instead.
Definition at line 62 of file OpticalTriggerGate.h.
Member Typedef Documentation
ChannelID_t
using icarus::trigger::OpticalTriggerGate::ChannelID_t = GateData_t::ChannelID_t
Type of channel identifier.
Definition at line 70 of file OpticalTriggerGate.h.
GateData_t
using icarus::trigger::OpticalTriggerGate::GateData_t = OpticalTriggerGateData_t
Type for gate data access.
Definition at line 68 of file OpticalTriggerGate.h.
Waveforms_t
using icarus::trigger::OpticalTriggerGate::Waveforms_t = std::vector<raw::OpDetWaveform const*> protected
Internal list of registered waveforms.
Definition at line 236 of file OpticalTriggerGate.h.
Constructor & Destructor Documentation
OpticalTriggerGate() [1/4]
icarus::trigger::OpticalTriggerGate::OpticalTriggerGate () default
Constructor: a closed gate with no associated waveform (add() them).
OpticalTriggerGate() [2/4]
icarus::trigger::OpticalTriggerGate::OpticalTriggerGate (raw::OpDetWaveform const & waveform) inline
Constructor: a closed gate for the channel in waveform.
Definition at line 81 of file OpticalTriggerGate.h.
OpticalTriggerGate() [3/4]
icarus::trigger::OpticalTriggerGate::OpticalTriggerGate (ChannelID_t channel) inline
Constructor: a closed gate for the specified channel.
Definition at line 87 of file OpticalTriggerGate.h.
OpticalTriggerGate() [4/4]
icarus::trigger::OpticalTriggerGate::OpticalTriggerGate (GateEvolution_t && gateLevel, Waveforms_t && waveforms) inline protected
Protected constructor: set the data directly.
Definition at line 239 of file OpticalTriggerGate.h.
Member Function Documentation
add()
bool icarus::trigger::OpticalTriggerGate::add (raw::OpDetWaveform const & waveform)
Adds another waveform to the gate (unless it has already been added).
Definition at line 200 of file OpticalTriggerGate.cxx.
Referenced by icarus::trigger::SingleChannelOpticalTriggerGate::add().
extractChannels()
auto icarus::trigger::OpticalTriggerGate::extractChannels (Waveforms_t const & waveforms) static private
Returns the list of all channels from the waveforms (duplicate allowed).
Definition at line 215 of file OpticalTriggerGate.cxx.
Referenced by registerWaveforms().
gateLevels() [1/2]
GateData_t & icarus::trigger::OpticalTriggerGate::gateLevels () inline
Access to the underlying gate level data (mutable).
Definition at line 107 of file OpticalTriggerGate.h.
Referenced by icarus::trigger::BeamGateMaker::make().
gateLevels() [2/2]
GateData_t const & icarus::trigger::OpticalTriggerGate::gateLevels () const inline
Access to the underlying gate level data (immutable).
Definition at line 110 of file OpticalTriggerGate.h.
Max() [1/2]
icarus::trigger::OpticalTriggerGate icarus::trigger::OpticalTriggerGate::Max (OpticalTriggerGate const & a, OpticalTriggerGate const & b) static
Returns a gate with the maximum opening between the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the maximum opening among a and b
See also
Min(), Sum()
Multi-level equivalent of an or logical operation.
Definition at line 146 of file OpticalTriggerGate.cxx.
References Max().
Max() [2/2]
icarus::trigger::OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::Max (OpticalTriggerGate const & other)
Combines with a gate, keeping the maximum opening among the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Sum()
Multi-level equivalent of an or logical operation.
Definition at line 110 of file OpticalTriggerGate.cxx.
Referenced by Max().
mergeWaveforms()
auto icarus::trigger::OpticalTriggerGate::mergeWaveforms (Waveforms_t const & a, Waveforms_t const & b) static protected
Registers the waveforms from the other gate into this one.
Definition at line 80 of file OpticalTriggerGate.cxx.
mergeWaveformsFromGate()
void icarus::trigger::OpticalTriggerGate::mergeWaveformsFromGate (OpticalTriggerGate const & other) inline protected
Registers the waveforms from the other gate into this one.
Definition at line 249 of file OpticalTriggerGate.h.
References registerWaveforms(), and waveforms().
Min() [1/2]
icarus::trigger::OpticalTriggerGate icarus::trigger::OpticalTriggerGate::Min (OpticalTriggerGate const & a, OpticalTriggerGate const & b) static
Returns a gate with the minimum opening between the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the minimum opening among a and b
See also
Max()
Multi-level equivalent of an and logical operation.
Definition at line 140 of file OpticalTriggerGate.cxx.
References Min().
Min() [2/2]
icarus::trigger::OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::Min (OpticalTriggerGate const & other)
Combines with a gate, keeping the minimum opening among the two.
Parameters
other gate to combine to
Returns
this object
See also
Max()
Multi-level equivalent of an and logical operation.
Definition at line 100 of file OpticalTriggerGate.cxx.
Referenced by Min().
Mul() [1/2]
icarus::trigger::OpticalTriggerGate icarus::trigger::OpticalTriggerGate::Mul (OpticalTriggerGate const & a, OpticalTriggerGate const & b) static
Returns a gate with opening product of the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the product of openings of a and b
See also
Max()
Definition at line 158 of file OpticalTriggerGate.cxx.
References Mul().
Mul() [2/2]
icarus::trigger::OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::Mul (OpticalTriggerGate const & other)
Combines with a gate, keeping the product of openings of the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Max(), Sum()
Definition at line 130 of file OpticalTriggerGate.cxx.
Referenced by Mul().
operator!=()
bool icarus::trigger::OpticalTriggerGate::operator!= (OpticalTriggerGate const & other) const
Definition at line 191 of file OpticalTriggerGate.cxx.
operator=() [1/2]
OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::operator= (GateData_t && data) inline
Definition at line 97 of file OpticalTriggerGate.h.
operator=() [2/2]
OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::operator= (GateData_t const & data) inline
Copies/steals all the levels and channels from the specified data.
Definition at line 95 of file OpticalTriggerGate.h.
operator==()
bool icarus::trigger::OpticalTriggerGate::operator== (OpticalTriggerGate const & other) const
Definition at line 182 of file OpticalTriggerGate.cxx.
registerWaveforms()
void icarus::trigger::OpticalTriggerGate::registerWaveforms (Waveforms_t const & moreWaveforms) protected
Registers the waveforms from the specified list.
Definition at line 54 of file OpticalTriggerGate.cxx.
References icarus::trigger::ReadoutTriggerGate< Tick, TickInterval, ChannelIDType >::associateChannels(), extractChannels(), and fWaveforms.
Referenced by mergeWaveformsFromGate().
Sum() [1/2]
icarus::trigger::OpticalTriggerGate icarus::trigger::OpticalTriggerGate::Sum (OpticalTriggerGate const & a, OpticalTriggerGate const & b) static
Returns a gate with opening sum of the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the total opening of a and b
See also
Max()
Definition at line 152 of file OpticalTriggerGate.cxx.
References Sum().
Sum() [2/2]
icarus::trigger::OpticalTriggerGate & icarus::trigger::OpticalTriggerGate::Sum (OpticalTriggerGate const & other)
Combines with a gate, keeping the sum of openings of the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Max()
Definition at line 120 of file OpticalTriggerGate.cxx.
Referenced by Sum().
SymmetricCombination() [1/2]
template<typename Op > icarus::trigger::OpticalTriggerGate icarus::trigger::OpticalTriggerGate::SymmetricCombination (Op && op, OpticalTriggerGate const & a, OpticalTriggerGate const & b, TriggerGateTicks_t aDelay, TriggerGateTicks_t bDelay)
Definition at line 166 of file OpticalTriggerGate.cxx.
SymmetricCombination() [2/2]
template<typename Op > static OpticalTriggerGate icarus::trigger::OpticalTriggerGate::SymmetricCombination (Op && op, OpticalTriggerGate const & a, OpticalTriggerGate const & b, TriggerGateTicks_t aDelay = TriggerGateTicks_t{ 0 }, TriggerGateTicks_t bDelay = TriggerGateTicks_t{ 0 }) static
Returns a gate combination of the openings of two other gates.
Template Parameters
Op binary operation: OpeningCount_t (x2) to OpeningCount_t
Parameters
op symmetric binary combination operation
a first gate
b second gate
Returns
gate with opening combination of a and b
For this algorithm to work, the operation needs to be symmetric, i.e. op(c1, c2) == op(c2, c1) for every valid combinations of counts c1 and c2.
waveformChannels()
auto icarus::trigger::OpticalTriggerGate::waveformChannels (Waveforms_t const & waveforms) static private
Returns the list of all unique channels (sorted) from the waveforms.
Definition at line 229 of file OpticalTriggerGate.cxx.
waveforms()
std::vector< raw::OpDetWaveform const * > icarus::trigger::OpticalTriggerGate::waveforms () const inline
Returns a list of pointers to the waveforms associated to the gate, sorted.
Definition at line 114 of file OpticalTriggerGate.h.
References fWaveforms.
Referenced by icarus::trigger::SingleChannelOpticalTriggerGate::hasRefWaveform(), mergeWaveformsFromGate(), and icarus::trigger::SingleChannelOpticalTriggerGate::refWaveform().
Member Data Documentation
fWaveforms
std::vector<raw::OpDetWaveform const*> icarus::trigger::OpticalTriggerGate::fWaveforms private
List of waveforms involved in this channel.
Definition at line 259 of file OpticalTriggerGate.h.
Referenced by registerWaveforms(), and waveforms().
The documentation for this class was generated from the following files:
sbnobj/sbnobj/ICARUS/PMT/Trigger/Data/OpticalTriggerGate.h
sbnobj/sbnobj/ICARUS/PMT/Trigger/Data/OpticalTriggerGate.cxx