CAF format: CheckPhotonLibraryJobs.JobChecker Class Reference
CheckPhotonLibraryJobs.JobChecker Class Reference
Public Member Functions
__init__ (self, "name used for the check (defaults are shaped after it)" baseName, "name of good job list (None: automatic; False: no list)" goodList=None, "name of bad job list (None: automatic; False: no list)" badList=None, "name of output file list (None: automatic; False: no list)" fileList=None, "do not check the jobs already in the good list" skipKnownGoodJobs=False, "do not check the jobs already in the bad list" skipKnownBadJobs=False)
setupList (self, listName, listTag, mustExist=False)
reset (self)
"if the output file list is being filled" isCollectingOutput (self)
checkFromFile (self, "path to the file containing XML job configuration" XMLfilePath, "target the specified project name in the file" projectName="", "target the specified stage name in the file" stageName="", "if not None, process at most this many jobs" maxJobs=None)
checkJob (self, "path to the file containing XML job configuration" XMLfilePath, "target the specified project name in the file" projectName="", "target the specified stage name in the file" stageName="")
getJobInfo (self, "path to the file containing XML job configuration" jobConfigFile, "target the specified project name in the file" projectName="", "target the specified stage name in the file" stageName="")
checkJobGoodness (self, jobInfo, jobName)
collectJobOutputFiles (self, jobInfo)
"Whether the file list was written" writeList (self, content, fileName, tag)
writeSummary (self)
Public Attributes
checkBaseDir = os.path.dirname(baseName)
checkBaseName
goodListName
list goodList
badListName
list badList = 0:
outputFileListName = self.setupList(badList, 'badxml', mustExist=skipKnownBadJobs)
list outputFileList
knownGoodJobs = set()
knownBadJobs = set()
Detailed Description
Performs checks on job output and collects output files.
Definition at line 134 of file CheckPhotonLibraryJobs.py.
Constructor & Destructor Documentation
__init__()
CheckPhotonLibraryJobs.JobChecker.__init__ (self, "name used for the check (defaults are shaped after it)" baseName, "name of good job list (None: automatic; False: no list)" goodList = None, "name of bad job list (None: automatic; False: no list)" badList = None, "name of output file list (None: automatic; False: no list)" fileList = None, "do not check the jobs already in the good list" skipKnownGoodJobs = False, "do not check the jobs already in the bad list" skipKnownBadJobs = False)
Definition at line 139 of file CheckPhotonLibraryJobs.py.
Member Function Documentation
checkFromFile()
CheckPhotonLibraryJobs.JobChecker.checkFromFile (self, "path to the file containing XML job configuration" XMLfilePath, "target the specified project name in the file" projectName = "", "target the specified stage name in the file" stageName = "", "if not None, process at most this many jobs" maxJobs = None)
Definition at line 208 of file CheckPhotonLibraryJobs.py.
checkJob()
CheckPhotonLibraryJobs.JobChecker.checkJob (self, "path to the file containing XML job configuration" XMLfilePath, "target the specified project name in the file" projectName = "", "target the specified stage name in the file" stageName = "")
Definition at line 236 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
checkJobGoodness()
CheckPhotonLibraryJobs.JobChecker.checkJobGoodness (self, jobInfo, jobName)
Definition at line 304 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
collectJobOutputFiles()
CheckPhotonLibraryJobs.JobChecker.collectJobOutputFiles (self, jobInfo)
Definition at line 367 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
getJobInfo()
CheckPhotonLibraryJobs.JobChecker.getJobInfo (self, "path to the file containing XML job configuration" jobConfigFile, "target the specified project name in the file" projectName = "", "target the specified stage name in the file" stageName = "")
Definition at line 272 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
isCollectingOutput()
"if the output file list is being filled" CheckPhotonLibraryJobs.JobChecker.isCollectingOutput (self)
Definition at line 205 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
reset()
CheckPhotonLibraryJobs.JobChecker.reset (self)
Resets all the counters and records.
Definition at line 196 of file CheckPhotonLibraryJobs.py.
References CheckPhotonLibraryJobs.JobChecker.badList, CheckPhotonLibraryJobs.JobChecker.badListName, CheckPhotonLibraryJobs.JobChecker.checkJob(), CheckPhotonLibraryJobs.JobChecker.checkJobGoodness(), CheckPhotonLibraryJobs.JobChecker.collectJobOutputFiles(), CheckPhotonLibraryJobs.JobChecker.getJobInfo(), CheckPhotonLibraryJobs.JobChecker.goodList, CheckPhotonLibraryJobs.JobChecker.goodListName, CheckPhotonLibraryJobs.JobChecker.isCollectingOutput(), CheckPhotonLibraryJobs.JobChecker.knownBadJobs, CheckPhotonLibraryJobs.JobChecker.knownGoodJobs, CheckPhotonLibraryJobs.JobChecker.outputFileList, CheckPhotonLibraryJobs.JobChecker.outputFileListName, and CheckPhotonLibraryJobs.JobChecker.writeList().
setupList()
CheckPhotonLibraryJobs.JobChecker.setupList (self, listName, listTag, mustExist = False)
Returns the name of the list, an empty list to be filled and the existing
content.
Definition at line 168 of file CheckPhotonLibraryJobs.py.
References CheckPhotonLibraryJobs.JobChecker.checkBaseDir, and CheckPhotonLibraryJobs.JobChecker.checkBaseName.
writeList()
"Whether the file list was written" CheckPhotonLibraryJobs.JobChecker.writeList (self, content, fileName, tag)
Definition at line 375 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
writeSummary()
CheckPhotonLibraryJobs.JobChecker.writeSummary (self)
Definition at line 411 of file CheckPhotonLibraryJobs.py.
Member Data Documentation
badList
CheckPhotonLibraryJobs.JobChecker.badList = 0:
Definition at line 157 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
badListName
CheckPhotonLibraryJobs.JobChecker.badListName
Definition at line 157 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
checkBaseDir
CheckPhotonLibraryJobs.JobChecker.checkBaseDir = os.path.dirname(baseName)
Definition at line 148 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.setupList().
checkBaseName
CheckPhotonLibraryJobs.JobChecker.checkBaseName
Initial value:
=  removeSuffixes(
     os.path.splitext(os.path.basename(baseName))[0], # start with basename
     '_xml', '-xml'
     )
Definition at line 150 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.setupList().
goodList
CheckPhotonLibraryJobs.JobChecker.goodList
Definition at line 155 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
goodListName
CheckPhotonLibraryJobs.JobChecker.goodListName
Definition at line 155 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
knownBadJobs
CheckPhotonLibraryJobs.JobChecker.knownBadJobs = set()
Definition at line 163 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
knownGoodJobs
CheckPhotonLibraryJobs.JobChecker.knownGoodJobs = set()
Definition at line 162 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
outputFileList
CheckPhotonLibraryJobs.JobChecker.outputFileList
Definition at line 159 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
outputFileListName
CheckPhotonLibraryJobs.JobChecker.outputFileListName = self.setupList(badList, 'badxml', mustExist=skipKnownBadJobs)
Definition at line 159 of file CheckPhotonLibraryJobs.py.
Referenced by CheckPhotonLibraryJobs.JobChecker.reset().
The documentation for this class was generated from the following file:
icaruscode/icaruscode/PMT/scripts/CheckPhotonLibraryJobs.py