CAF format: icarus::trigger::TriggerGateData< Tick, TickInterval > Class Template Reference
icarus::trigger::TriggerGateData< Tick, TickInterval > Class Template Reference
Logical multi-level gate.
#include <TriggerGateData.h>
Classes
struct CompareTick
Comparison by tick number.
Public Types
using triggergatedata_t = TriggerGateData<Tick, TickInterval>
This type.
using ClockTick_t = Tick
Type of a point in time, measured in ticks.
using ClockTicks_t = TickInterval
Type of a time interval, measured in ticks.
using OpeningCount_t = unsigned int
Type of count of number of open channels.
using OpeningDiff_t = std::make_signed_t<OpeningCount_t>
Type representing a variation of open channels.
Public Member Functions
TriggerGateData ()
Constructor: a closed gate for the channel in waveform.
bool operator== (TriggerGateData const &) const
bool operator!= (TriggerGateData const &) const
template<typename Op >
auto SymmetricCombination (Op &&op, triggergatedata_t const &a, triggergatedata_t const &b, ClockTicks_t aDelay, ClockTicks_t bDelay) -> triggergatedata_t
template<typename Op >
auto findStatus (Op op, ClockTick_t start, ClockTick_t end) const -> status_const_iterator
Query
ClockTick_t lastTick () const
Returns the number of ticks this gate covers.
OpeningCount_t openingCount (ClockTick_t tick) const
Returns the opening count of the gate at the specified tick.
bool alwaysClosed () const
Returns whether this gate never opened.
bool isOpen (ClockTick_t tick) const
Returns whether the gate is open at all at the specified tick.
ClockTick_t findOpen (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate opened.
ClockTick_t findClose (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate closed.
ClockTick_t findMaxOpen (ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns the tick at which the gate has the maximum opening.
std::pair< OpeningCount_t, OpeningCount_t > openingRange (ClockTick_t start, ClockTick_t end) const
Returns the range of trigger opening values in the specified range.
Gate opening and closing operations
void setOpeningAt (ClockTick_t tick, OpeningCount_t openingCount)
Changes the opening to match openingCount at the specified time.
void openAt (ClockTick_t tick, OpeningDiff_t count)
Open this gate at the specified time (increase the opening by count).
void openAt (ClockTick_t tick)
Open this gate at the specified time (increase the opening by 1).
void openBetween (ClockTick_t start, ClockTick_t end, OpeningDiff_t count=1)
Open this gate at specified start tick, and close it at end tick.
void openFor (ClockTick_t tick, ClockTicks_t length, OpeningDiff_t count=1)
Open this gate at the specified time, and close it length ticks later.
void closeAt (ClockTick_t tick, OpeningDiff_t count)
Close this gate at the specified time (decrease the opening by count).
void closeAt (ClockTick_t tick)
Close this gate at the specified time.
void closeAllAt (ClockTick_t tick)
Completely close this gate at the specified time.
void clear ()
Sets the gate levels in the state at construction.
Static Public Attributes
static constexpr ClockTick_t MinTick = std::numeric_limits<ClockTick_t>::min()
An unbearably small tick number.
static constexpr ClockTick_t MaxTick = std::numeric_limits<ClockTick_t>::max()
An unbearably large tick number.
Protected Types
using EventType = details::TriggerGateEventType
using Status = details::TriggerGateStatus<ClockTick_t, OpeningCount_t>
using GateEvolution_t = std::vector<Status>
Type to describe the time evolution of the gate.
Protected Member Functions
TriggerGateData (GateEvolution_t &&gateLevel)
Protected constructor: set the data directly.
Private Types
using status_iterator = typename GateEvolution_t::iterator
using status_const_iterator = typename GateEvolution_t::const_iterator
Private Member Functions
std::optional< status_const_iterator > findLastStatusFor (ClockTick_t tick) const
Returns a const-iterator to the status current at tick, or no value.
std::optional< status_iterator > findLastStatusFor (ClockTick_t tick)
Returns an iterator to the status current at tick, or no value.
status_iterator findLastStatusForTickOrThrow (ClockTick_t tick)
status_const_iterator findLastStatusForTickOrThrow (ClockTick_t tick) const
template<typename Op >
status_const_iterator findStatus (Op op, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns an iterator to the first status for which op(status) is true.
status_const_iterator findOpenStatus (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns an iterator to the first open status (.
status_const_iterator findCloseStatus (OpeningCount_t minOpening=1U, ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns an iterator to the first close status (.
status_const_iterator findMaxOpenStatus (ClockTick_t start=MinTick, ClockTick_t end=MaxTick) const
Returns an iterator to the maximum open status (.
void compact ()
Maintenance operation: removes unconsequential stati.
Static Private Member Functions
static GateEvolution_t startingGateLevel ()
Helper returning the starting state of the levels at construction time.
Private Attributes
GateEvolution_t fGateLevel
Evolution of the gate in time.
Static Private Attributes
static Status const NewGateStatus { EventType::Set, MinTick, 0U }
A new gate starts with this status: opening level set to 0.
Friends
std::ostream & operator (std::ostream &, triggergatedata_t const &)
std::ostream & operator (std::ostream &, Status const &)
Combination operations
triggergatedata_t & Min (triggergatedata_t const &other)
Combines with a gate, keeping the minimum opening among the two.
triggergatedata_t & Max (triggergatedata_t const &other)
Combines with a gate, keeping the maximum opening among the two.
triggergatedata_t & Sum (triggergatedata_t const &other)
Combines with a gate, keeping the sum of openings of the two.
triggergatedata_t & Mul (triggergatedata_t const &other)
Combines with a gate, keeping the product of openings of the two.
static triggergatedata_t Min (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with the minimum opening between the specified two.
static triggergatedata_t Max (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with the maximum opening between the specified two.
static triggergatedata_t Sum (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with opening sum of the specified two.
static triggergatedata_t Mul (triggergatedata_t const &a, triggergatedata_t const &b)
Returns a gate with opening product of the specified two.
template<typename Op >
static triggergatedata_t SymmetricCombination (Op &&op, triggergatedata_t const &a, triggergatedata_t const &b, ClockTicks_t aDelay=ClockTicks_t{}, ClockTicks_t bDelay=ClockTicks_t{})
Returns a gate combination of the openings of two other gates.
Detailed Description
template<typename Tick, typename TickInterval>
class icarus::trigger::TriggerGateData< Tick, TickInterval >
Logical multi-level gate.
Template Parameters
Tick type used to count the ticks
TickInterval type used to quantify tick difference
A TriggerGate object tracks a logical multi-level gate, that is a gate whose level can be not only 0 or 1, but an arbitrary integral number. The gate level is defined as a positive number. The general convention is that a level of 0 means the gate is closed, while any other level (typically 1) means it's open. In a multi-level gate, one can choose to interpret the gate as open only if it reaches a chosen level higher than 1. The time domain of the gate is measured in ticks, which in this context are optical detector clock ticks defined on the electronics time scale. That means that tick #0 is set at the origin of that time scale. The gate is unlimited, i.e. it can accommodate changes on any time tick from #0 on (up to the machine limitations, MaxTick). For practical purposes, lastTick() is instrumental to find the tick of the last gate change.
Internally, the gate is represented by "events". The first event, at tick #0, sets the level of the gate to the lowest possible (0, closed). Each event may change the level at a given tick and all the following ones until MaxTick. An actual gate is therefore defined by two events, an opening event (that is an increase in level) and a closing one (a shift of the same amount in the opposite direction).
Definition at line 132 of file TriggerGateData.h.
Member Typedef Documentation
ClockTick_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::ClockTick_t = Tick
Type of a point in time, measured in ticks.
Definition at line 140 of file TriggerGateData.h.
ClockTicks_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::ClockTicks_t = TickInterval
Type of a time interval, measured in ticks.
Definition at line 143 of file TriggerGateData.h.
EventType
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::EventType = details::TriggerGateEventType protected
Definition at line 410 of file TriggerGateData.h.
GateEvolution_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::GateEvolution_t = std::vector<Status> protected
Type to describe the time evolution of the gate.
Definition at line 414 of file TriggerGateData.h.
OpeningCount_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::OpeningCount_t = unsigned int
Type of count of number of open channels.
Definition at line 146 of file TriggerGateData.h.
OpeningDiff_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::OpeningDiff_t = std::make_signed_t<OpeningCount_t>
Type representing a variation of open channels.
Definition at line 149 of file TriggerGateData.h.
Status
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::Status = details::TriggerGateStatus<ClockTick_t, OpeningCount_t> protected
Definition at line 411 of file TriggerGateData.h.
status_const_iterator
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::status_const_iterator = typename GateEvolution_t::const_iterator private
Definition at line 431 of file TriggerGateData.h.
status_iterator
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::status_iterator = typename GateEvolution_t::iterator private
Definition at line 430 of file TriggerGateData.h.
triggergatedata_t
template<typename Tick , typename TickInterval > using icarus::trigger::TriggerGateData< Tick, TickInterval >::triggergatedata_t = TriggerGateData<Tick, TickInterval>
This type.
Definition at line 137 of file TriggerGateData.h.
Constructor & Destructor Documentation
TriggerGateData() [1/2]
template<typename Tick , typename TickInterval > icarus::trigger::TriggerGateData< Tick, TickInterval >::TriggerGateData () inline
Constructor: a closed gate for the channel in waveform.
Definition at line 164 of file TriggerGateData.h.
TriggerGateData() [2/2]
template<typename Tick , typename TickInterval > icarus::trigger::TriggerGateData< Tick, TickInterval >::TriggerGateData (GateEvolution_t && gateLevel) inline protected
Protected constructor: set the data directly.
Definition at line 417 of file TriggerGateData.h.
Member Function Documentation
alwaysClosed()
template<typename Tick , typename TickInterval > bool icarus::trigger::TriggerGateData< Tick, TickInterval >::alwaysClosed () const inline
Returns whether this gate never opened.
Definition at line 178 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::fGateLevel, and icarus::trigger::TriggerGateData< Tick, TickInterval >::findOpenStatus().
clear()
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::clear () inline
Sets the gate levels in the state at construction.
Definition at line 283 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::fGateLevel, and icarus::trigger::TriggerGateData< Tick, TickInterval >::startingGateLevel().
closeAllAt()
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAllAt (ClockTick_t tick) inline
Completely close this gate at the specified time.
Definition at line 280 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::setOpeningAt().
closeAt() [1/2]
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAt (ClockTick_t tick) inline
Close this gate at the specified time.
Definition at line 277 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAt().
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAt().
closeAt() [2/2]
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAt (ClockTick_t tick, OpeningDiff_t count) inline
Close this gate at the specified time (decrease the opening by count).
Definition at line 273 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt().
compact()
template<typename TK , typename TI > void icarus::trigger::TriggerGateData< TK, TI >::compact () private
Maintenance operation: removes unconsequential stati.
Definition at line 78 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::SymmetricCombination().
findClose()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findClose (OpeningCount_t minOpening = 1U, ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const
Returns the tick at which the gate closed.
Parameters
minOpening minimum count to consider the gate open (default: 1)
start first tick to check (by default, the first available one)
end if getting to this tick, give up (by default, to the end)
Returns
the tick at which the gate closed, or end if never
See also
findOpen()
The closing is defined as the opening count being changed to strictly below minOpening.
If the count is already below minOpening at the specified start tick, the current level is ignored and only the next change which keeps the gate closed is reported.
Definition at line 54 of file TriggerGateData.tcc.
findCloseStatus()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findCloseStatus (OpeningCount_t minOpening = 1U, ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const private
Returns an iterator to the first close status (.
See also
findClose()).
Definition at line 758 of file TriggerGateData.tcc.
findLastStatusFor() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findLastStatusFor (ClockTick_t tick) private
Returns an iterator to the status current at tick, or no value.
Definition at line 604 of file TriggerGateData.tcc.
findLastStatusFor() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findLastStatusFor (ClockTick_t tick) const private
Returns a const-iterator to the status current at tick, or no value.
Definition at line 619 of file TriggerGateData.tcc.
findLastStatusForTickOrThrow() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findLastStatusForTickOrThrow (ClockTick_t tick) private
Returns an iterator to the status current at tick.
Exceptions
cet::exception if tick can't be handled
Definition at line 634 of file TriggerGateData.tcc.
findLastStatusForTickOrThrow() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findLastStatusForTickOrThrow (ClockTick_t tick) const private
Returns a const-iterator to the status current at tick.
Exceptions
cet::exception if tick can't be handled
Definition at line 652 of file TriggerGateData.tcc.
findMaxOpen()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findMaxOpen (ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const
Returns the tick at which the gate has the maximum opening.
Parameters
start first tick to check (by default, the first available one)
end if getting to this tick, give up (by default, to the end)
Returns
the first tick with the maximum opening, or end if never
Definition at line 66 of file TriggerGateData.tcc.
findMaxOpenStatus()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findMaxOpenStatus (ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const private
Returns an iterator to the maximum open status (.
See also
findMaxOpen()).
Definition at line 771 of file TriggerGateData.tcc.
findOpen()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findOpen (OpeningCount_t minOpening = 1U, ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const
Returns the tick at which the gate opened.
Parameters
minOpening minimum count to consider the gate open (default: 1)
start first tick to check (by default, the first available one)
end if getting to this tick, give up (by default, to the end)
Returns
the tick at which the gate opened, or end if never
See also
findClose(), findMaxOpen()
If the count is already above (or equal to) minOpening at the specified start tick, the current level is ignored and only the next change which keeps the gate open is reported.
Definition at line 42 of file TriggerGateData.tcc.
findOpenStatus()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::findOpenStatus (OpeningCount_t minOpening = 1U, ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const private
Returns an iterator to the first open status (.
See also
findOpen()).
Definition at line 711 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::alwaysClosed().
findStatus() [1/2]
template<typename Tick , typename TickInterval > template<typename Op > auto icarus::trigger::TriggerGateData< Tick, TickInterval >::findStatus (Op op, ClockTick_t start, ClockTick_t end) const -> status_const_iterator
Definition at line 671 of file TriggerGateData.tcc.
findStatus() [2/2]
template<typename Tick , typename TickInterval > template<typename Op > status_const_iterator icarus::trigger::TriggerGateData< Tick, TickInterval >::findStatus (Op op, ClockTick_t start = MinTick, ClockTick_t end = MaxTick) const private
Returns an iterator to the first status for which op(status) is true.
isOpen()
template<typename Tick , typename TickInterval > bool icarus::trigger::TriggerGateData< Tick, TickInterval >::isOpen (ClockTick_t tick) const inline
Returns whether the gate is open at all at the specified tick.
Definition at line 181 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::openingCount().
lastTick()
template<typename Tick , typename TickInterval > ClockTick_t icarus::trigger::TriggerGateData< Tick, TickInterval >::lastTick () const inline
Returns the number of ticks this gate covers.
Definition at line 172 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::fGateLevel.
Max() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Max (triggergatedata_t const & a, triggergatedata_t const & b) static
Returns a gate with the maximum opening between the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the maximum opening among a and b
See also
Min(), Sum()
Multi-level equivalent of an or logical operation.
Definition at line 382 of file TriggerGateData.tcc.
Max() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Max (triggergatedata_t const & other)
Combines with a gate, keeping the maximum opening among the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Sum()
Multi-level equivalent of an or logical operation.
Definition at line 342 of file TriggerGateData.tcc.
Min() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Min (triggergatedata_t const & a, triggergatedata_t const & b) static
Returns a gate with the minimum opening between the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the minimum opening among a and b
See also
Max()
Multi-level equivalent of an and logical operation.
Definition at line 372 of file TriggerGateData.tcc.
Min() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Min (triggergatedata_t const & other)
Combines with a gate, keeping the minimum opening among the two.
Parameters
other gate to combine to
Returns
this object
See also
Max()
Multi-level equivalent of an and logical operation.
Definition at line 332 of file TriggerGateData.tcc.
Mul() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Mul (triggergatedata_t const & a, triggergatedata_t const & b) static
Returns a gate with opening product of the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the product of openings of a and b
See also
Max(), Sum()
Definition at line 401 of file TriggerGateData.tcc.
Mul() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Mul (triggergatedata_t const & other)
Combines with a gate, keeping the product of openings of the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Max(), Sum()
Multi-level equivalent of an extended and.
Definition at line 362 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerEfficiencyPlots::analyze().
openAt() [1/2]
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt (ClockTick_t tick) inline
Open this gate at the specified time (increase the opening by 1).
Definition at line 263 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt().
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt().
openAt() [2/2]
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt (ClockTick_t tick, OpeningDiff_t count) inline
Open this gate at the specified time (increase the opening by count).
Definition at line 259 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::MaxTick, and icarus::trigger::TriggerGateData< Tick, TickInterval >::openBetween().
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAt().
openBetween()
template<typename TK , typename TI > void icarus::trigger::TriggerGateData< TK, TI >::openBetween (ClockTick_t start, ClockTick_t end, OpeningDiff_t count = 1)
Open this gate at specified start tick, and close it at end tick.
Definition at line 218 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt(), and icarus::trigger::TriggerGateData< Tick, TickInterval >::openFor().
openFor()
template<typename Tick , typename TickInterval > void icarus::trigger::TriggerGateData< Tick, TickInterval >::openFor (ClockTick_t tick, ClockTicks_t length, OpeningDiff_t count = 1) inline
Open this gate at the specified time, and close it length ticks later.
Definition at line 269 of file TriggerGateData.h.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::openBetween().
Referenced by icarus::trigger::BeamGateMaker::make().
openingCount()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::openingCount (ClockTick_t tick) const
Returns the opening count of the gate at the specified tick.
Definition at line 165 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::isOpen().
openingRange()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::openingRange (ClockTick_t start, ClockTick_t end) const
Returns the range of trigger opening values in the specified range.
Parameters
start the first tick to consider
end the first tick to exclude
Returns
a pair, { lower, upper } opening values
This method returns the lowest opening value seen in the tick range, and the lowest opening value above that one not seen in the same range. Therefore, a gate always closed (opening value 0) in the full range will return { 0, 1 }, a gate always opened (opening value 1) will return { 1, 2 }, a gate which opened or closed within the tick range will return { 0, 2 }. In case the tick range is empty, the returned value contains the same value for both extremes.
This function does not describe where the two extreme counts were found.
Definition at line 124 of file TriggerGateData.tcc.
operator!=()
template<typename TK , typename TI > bool icarus::trigger::TriggerGateData< TK, TI >::operator!= (TriggerGateData< Tick, TickInterval > const & other) const
Definition at line 595 of file TriggerGateData.tcc.
operator==()
template<typename TK , typename TI > bool icarus::trigger::TriggerGateData< TK, TI >::operator== (TriggerGateData< Tick, TickInterval > const & other) const
Definition at line 586 of file TriggerGateData.tcc.
setOpeningAt()
template<typename TK , typename TI > void icarus::trigger::TriggerGateData< TK, TI >::setOpeningAt (ClockTick_t tick, OpeningCount_t openingCount)
Changes the opening to match openingCount at the specified time.
Definition at line 174 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::closeAllAt(), and icarus::trigger::DiscriminatedAdderSignal::computeTimeInterval().
startingGateLevel()
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::startingGateLevel () static private
Helper returning the starting state of the levels at construction time.
Definition at line 807 of file TriggerGateData.tcc.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::clear().
Sum() [1/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Sum (triggergatedata_t const & a, triggergatedata_t const & b) static
Returns a gate with opening sum of the specified two.
Parameters
a first gate
b second gate
Returns
gate with at every tick the total opening of a and b
See also
Max()
Definition at line 392 of file TriggerGateData.tcc.
Sum() [2/2]
template<typename TK , typename TI > auto icarus::trigger::TriggerGateData< TK, TI >::Sum (triggergatedata_t const & other)
Combines with a gate, keeping the sum of openings of the two.
Parameters
other gate to combine to
Returns
this object
See also
Min(), Max()
Definition at line 352 of file TriggerGateData.tcc.
SymmetricCombination() [1/2]
template<typename Tick , typename TickInterval > template<typename Op > auto icarus::trigger::TriggerGateData< Tick, TickInterval >::SymmetricCombination (Op && op, triggergatedata_t const & a, triggergatedata_t const & b, ClockTicks_t aDelay, ClockTicks_t bDelay) -> triggergatedata_t
Keeps track of information travelling with a gate.
Returns the tick of the current status (delay is properly applied).
Returns the current opening level.
Returns whether current opening level is different from the previous.
Returns the gate status to be considered.
Returns the gate status that is not current.
Applies the specified operation on the current status.
Returns whether both sides are over.
Prepares for the next entry, and returns false if we are done.
< Helper for the left gate.
< Helper for the right gate.
< To the gate with the next time tick.
< To the gate not with the next time tick.
Swap the current and the other gate status.
Definition at line 411 of file TriggerGateData.tcc.
References icarus::trigger::TriggerGateData< Tick, TickInterval >::compact(), and icarus::trigger::TriggerGateData< Tick, TickInterval >::fGateLevel.
SymmetricCombination() [2/2]
template<typename Tick , typename TickInterval > template<typename Op > static triggergatedata_t icarus::trigger::TriggerGateData< Tick, TickInterval >::SymmetricCombination (Op && op, triggergatedata_t const & a, triggergatedata_t const & b, ClockTicks_t aDelay = ClockTicks_t{}, ClockTicks_t bDelay = ClockTicks_t{}) static
Returns a gate combination of the openings of two other gates.
Template Parameters
Op binary operation: OpeningCount_t (x2) to OpeningCount_t
Parameters
op symmetric binary combination operation
a first gate
b second gate
aDelay ticks of delay to be added to the first gate
bDelay ticks of delay to be added to the second gate
Returns
gate with opening combination of a and b
For this algorithm to work, the operation needs to be symmetric, i.e. op(c1, c2) == op(c2, c1) for every valid combinations of counts c1 and c2.
Member Data Documentation
fGateLevel
template<typename Tick , typename TickInterval > GateEvolution_t icarus::trigger::TriggerGateData< Tick, TickInterval >::fGateLevel private
Evolution of the gate in time.
Definition at line 451 of file TriggerGateData.h.
Referenced by icarus::trigger::TriggerGateData< Tick, TickInterval >::alwaysClosed(), icarus::trigger::TriggerGateData< Tick, TickInterval >::clear(), icarus::trigger::TriggerGateData< Tick, TickInterval >::lastTick(), and icarus::trigger::TriggerGateData< Tick, TickInterval >::SymmetricCombination().
MaxTick
template<typename Tick , typename TickInterval > ClockTick_t icarus::trigger::TriggerGateData< Tick, TickInterval >::MaxTick = std::numeric_limits<ClockTick_t>::max() static constexpr
An unbearably large tick number.
Definition at line 159 of file TriggerGateData.h.
Referenced by icarus::trigger::MakeTriggerSimulationTree::extractTriggerInfo(), and icarus::trigger::TriggerGateData< Tick, TickInterval >::openAt().
MinTick
template<typename Tick , typename TickInterval > ClockTick_t icarus::trigger::TriggerGateData< Tick, TickInterval >::MinTick = std::numeric_limits<ClockTick_t>::min() static constexpr
An unbearably small tick number.
Definition at line 155 of file TriggerGateData.h.
NewGateStatus
template<typename TK , typename TI > icarus::trigger::TriggerGateData< TK, TI >::Status const icarus::trigger::TriggerGateData< TK, TI >::NewGateStatus { EventType::Set, MinTick, 0U } static private
A new gate starts with this status: opening level set to 0.
Definition at line 448 of file TriggerGateData.h.
The documentation for this class was generated from the following files:
sbnobj/sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.h
sbnobj/sbnobj/ICARUS/PMT/Trigger/Data/TriggerGateData.tcc