CAF format: icaruscode/icaruscode/Utilities/DetectorClocksHelpers.h File Reference
DetectorClocksHelpers.h File Reference
Simple functions to streamline the creation of DetectorClocksData.
#include "lardata/DetectorInfoServices/DetectorClocksService.h"
#include "lardataalg/DetectorInfo/DetectorTimings.h"
#include "lardataalg/DetectorInfo/DetectorClocksData.h"
#include "art/Framework/Services/Registry/ServiceHandle.h"
Namespaces
namespace icarus
Cluster finding and building.
Functions
DetectorClocksData helpers
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData (art::Event const *event)
Returns a detinfo::DetectorClocksData from DetectorClocksService.
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData (art::Event const &event)
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData ()
DetectorTimings helpers
detinfo::DetectorTimings icarus::ns::util::makeDetTimings (art::Event const *event)
Returns a detinfo::DetectorTimings from DetectorClocksService.
detinfo::DetectorTimings icarus::ns::util::makeDetTimings (art::Event const &event)
detinfo::DetectorTimings icarus::ns::util::makeDetTimings ()
Detailed Description
Simple functions to streamline the creation of DetectorClocksData.
Author
Gianluca Petrillo (petrillo@slac.stanford.edu)
Date
September 16, 2020
Definition in file DetectorClocksHelpers.h.
Function Documentation
makeDetClockData() [1/3]
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData ()
Returns generic detector clock data for the job.
See also
makeDetClockData(art::Event const*)
Definition at line 63 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetClockData().
makeDetClockData() [2/3]
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData (art::Event const & event)
Returns detector clock data for the specified event.
See also
makeDetClockData(art::Event const*)
Definition at line 58 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetClockData().
makeDetClockData() [3/3]
detinfo::DetectorClocksData icarus::ns::util::makeDetClockData (art::Event const * event)
Returns a detinfo::DetectorClocksData from DetectorClocksService.
Parameters
event pointer to an art event
Returns
a detinfo::DetectorClocksData object (see the details below)
The detinfo::DetectorClocksService is queried to obtain a detinfo::DetectorClocksData object. The returned object is a static copy whose values will never update, even if the DetectorClocksService state changes.
If the event pointer is valid (i.e. not nullptr), the event is passed to the service DataFor() method for a complete timing record. Otherwise, DataForJob() is used, and the information might be incomplete or become outdated by the time a new event, run or file is accessed.
Note
This function is art dependent and accesses DetectorClocksService service.
Definition at line 49 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetClockData().
Referenced by icarus::ns::util::makeDetClockData(), icarus::ns::util::makeDetClockData(), icarus::ns::util::makeDetClockData(), and icarus::ns::util::makeDetTimings().
makeDetTimings() [1/3]
detinfo::DetectorTimings icarus::ns::util::makeDetTimings ()
Returns a detinfo::DetectorTimings for the job.
See also
makeDetTimings(art::Event const*)
Definition at line 96 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetTimings().
makeDetTimings() [2/3]
detinfo::DetectorTimings icarus::ns::util::makeDetTimings (art::Event const & event)
Returns a detinfo::DetectorTimings for the specified event.
See also
makeDetTimings(art::Event const*)
Definition at line 91 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetTimings().
makeDetTimings() [3/3]
detinfo::DetectorTimings icarus::ns::util::makeDetTimings (art::Event const * event)
Returns a detinfo::DetectorTimings from DetectorClocksService.
Parameters
event pointer to an art event
Returns
a detinfo::DetectorTimings object (see the details below)
See also
makeDetClockData(art::Event const*)
A detinfo::DetectorTimings object is created out of information obtained from detinfo::DetectorClocksService.
All the considerations described in makeDetClockData(art::Event const*) also hold for this function.
Definition at line 86 of file DetectorClocksHelpers.h.
References icarus::ns::util::makeDetClockData(), and icarus::ns::util::makeDetTimings().
Referenced by icarus::ns::util::makeDetTimings(), icarus::ns::util::makeDetTimings(), and icarus::ns::util::makeDetTimings().