CAF format: icarus::details::KeyedCSVparser Class Reference
icarus::details::KeyedCSVparser Class Reference
Parser to fill a KeyValuesData structure out of a character buffer.
#include <KeyedCSVparser.h>
Classes
struct InvalidFormat
struct MissingValues
struct ParserError
Public Types
using ParsedData_t = icarus::KeyValuesData
using Error = icarus::KeyValuesData::Error
Base of all errors by KeyedCSVparser.
using ErrorOnKey = icarus::KeyValuesData::ErrorOnKey
using MissingSize = KeyValuesData::MissingSize
Expected number of values is missing.
Public Member Functions
KeyedCSVparser (char sep=',')
Constructor: specifies the separator character.
ParsedData_t parse (std::string_view const &s) const
Parses the buffer s and returns a data structure with the content.
ParsedData_t parse (std::string const &s) const
template<typename BIter , typename EIter >
ParsedData_t parse (BIter b, EIter e) const
ParsedData_t operator() (std::string_view const &s) const
ParsedData_t operator() (std::string const &s) const
template<typename BIter , typename EIter >
ParsedData_t operator() (BIter b, EIter e) const
void parse (std::string_view const &s, ParsedData_t &data) const
Parses the buffer s and fills data with it.
template<typename String >
auto makeBuffer (String const &s) noexcept -> Buffer_t
template<char... Chars>
auto stripRightChars (SubBuffer_t s) noexcept -> SubBuffer_t
template<typename BIter , typename EIter >
auto parse (BIter b, EIter e) const -> ParsedData_t
Know patterns
The parser normally treats as a value everything that does not start with a letter. Known patterns may override this behaviour: if a token matches a known pattern, it is considered a key and it is possible to specify the expected number of values.
The number of values can be:
a number: exactly that number of values are required; an exception will be thrown if not enough tokens are available;
FixedSize: the next token must be a non-negative integer specifying how many other values to add (read this with Item::getSizedVector()); an exception will be thrown if not enough tokens are available;
DynamicSize: the standard algorithm is used and values are added as long as they don't look like keys; the token matching the pattern is interpreted as a key though.
Patterns are considered in the order they were added.
KeyedCSVparser & addPattern (std::regex pattern, unsigned int values)
Adds a single known pattern.
KeyedCSVparser & addPattern (std::string const &pattern, unsigned int values)
Adds a single known pattern.
KeyedCSVparser & addPatterns (std::initializer_list< std::pair< std::regex, unsigned int > > patterns)
Adds known patterns.
KeyedCSVparser & addPatterns (std::initializer_list< std::pair< std::string, unsigned int > > patterns)
Adds a single known pattern.
Static Public Attributes
static constexpr unsigned int FixedSize = std::numeric_limits<unsigned int>::max()
Expected values are missing.
static constexpr unsigned int DynamicSize = FixedSize - 1U
Mnemonic size value used in addPattern() calls.
Private Types
using Buffer_t = std::string_view
using SubBuffer_t = std::string_view
Private Member Functions
std::size_t findTokenLength (Buffer_t const &buffer) const noexcept
Returns the length of the next toke, up to the next separator (excluded).
SubBuffer_t peekToken (Buffer_t const &buffer) const noexcept
Returns the value of the next token, stripped.
SubBuffer_t extractToken (Buffer_t &buffer) const noexcept
Extracts the next token from the buffer and returns its value, stripped.
bool isKey (SubBuffer_t const &buffer) const noexcept
Is content of buffer a key (as opposed to a value)?
Static Private Member Functions
template<typename String >
static Buffer_t makeBuffer (String const &s) noexcept
static Buffer_t & moveBufferHead (Buffer_t &buffer, std::size_t size) noexcept
static SubBuffer_t strip (SubBuffer_t s) noexcept
static SubBuffer_t stripLeft (SubBuffer_t s) noexcept
static SubBuffer_t stripRight (SubBuffer_t s) noexcept
static SubBuffer_t stripRightChar (SubBuffer_t s, char c) noexcept
template<char... Chars>
static SubBuffer_t stripRightChars (SubBuffer_t s) noexcept
Private Attributes
char const fSep = ','
Character used as token separator.
std::vector< std::pair< std::regex, unsigned int > > fPatterns
List of known patterns for matching keys, and how many values they hold.
Detailed Description
Parser to fill a KeyValuesData structure out of a character buffer.
It currently supports only single-line buffer.
The parser operates one "line" at a time, returning a KeyValuesData with the values assigned to each detected key. No data type is implied: all elements are treated as strings, either a key or a value. The parser separates the elements according to a separator, strips them of trailing and heading spaces, then it decides whether each element is a value to be assigned to the last key found, or a new key. Keys are elements that have letters in them, values are anything else. This simple (and arguable) criterion can be broken with specific parser configuration: a pattern can be specified that when matched to an element will make it a key; the pattern can also set the number of values that key will require.
For example:
icarus::details::KeyedCSVparser parser;
parser.addPatterns({
      { "TriggerType", 1U } // expect one value (even if contains letters)
    , { "TriggerWindows", 1U } // expect one value (even if contains letters)
    , { "TPChitTimes", icarus::details::KeyedCSVparser::FixedSize }
         // the first value is an integer, count of how many other values
  });
icarus::KeyValuesData data = parser(
  "TriggerType, S5, Triggers, TriggerWindows, 0C0B,"
  " TPChits, 12, 130, 0, 0, TPChitTimes, 3, -1.1, -0.3, 0.1, PMThits, 8"
  );
will return data with 6 items.
Definition at line 68 of file KeyedCSVparser.h.
Member Typedef Documentation
Buffer_t
using icarus::details::KeyedCSVparser::Buffer_t = std::string_view private
Definition at line 164 of file KeyedCSVparser.h.
Error
using icarus::details::KeyedCSVparser::Error = icarus::KeyValuesData::Error
Base of all errors by KeyedCSVparser.
Definition at line 75 of file KeyedCSVparser.h.
ErrorOnKey
using icarus::details::KeyedCSVparser::ErrorOnKey = icarus::KeyValuesData::ErrorOnKey
Definition at line 76 of file KeyedCSVparser.h.
MissingSize
using icarus::details::KeyedCSVparser::MissingSize = KeyValuesData::MissingSize
Expected number of values is missing.
Parsing format is not understood.
Definition at line 80 of file KeyedCSVparser.h.
ParsedData_t
using icarus::details::KeyedCSVparser::ParsedData_t = icarus::KeyValuesData
Definition at line 72 of file KeyedCSVparser.h.
SubBuffer_t
using icarus::details::KeyedCSVparser::SubBuffer_t = std::string_view private
Definition at line 165 of file KeyedCSVparser.h.
Constructor & Destructor Documentation
KeyedCSVparser()
icarus::details::KeyedCSVparser::KeyedCSVparser (char sep = ',') inline
Constructor: specifies the separator character.
Definition at line 91 of file KeyedCSVparser.h.
Member Function Documentation
addPattern() [1/2]
KeyedCSVparser & icarus::details::KeyedCSVparser::addPattern (std::regex pattern, unsigned int values) inline
Adds a single known pattern.
Parameters
pattern the regular expression matching the key for this pattern
values the number of values for this pattern
Returns
this parser (addPattern() calls may be chained)
Definition at line 141 of file KeyedCSVparser.h.
References fPatterns.
Referenced by addPattern().
addPattern() [2/2]
KeyedCSVparser & icarus::details::KeyedCSVparser::addPattern (std::string const & pattern, unsigned int values) inline
Adds a single known pattern.
Parameters
pattern the regular expression matching the key for this pattern
values the number of values for this pattern
Returns
this parser (addPattern() calls may be chained)
Definition at line 143 of file KeyedCSVparser.h.
References addPattern().
addPatterns() [1/2]
auto icarus::details::KeyedCSVparser::addPatterns (std::initializer_list< std::pair< std::regex, unsigned int > > patterns)
Adds known patterns.
Parameters
patterns sequence of patterns to be added
Returns
this parser (addPatterns() calls may be chained)
Each pattern is a pair key regex/number of values, like in addPattern().
Definition at line 113 of file KeyedCSVparser.cxx.
addPatterns() [2/2]
auto icarus::details::KeyedCSVparser::addPatterns (std::initializer_list< std::pair< std::string, unsigned int > > patterns)
Adds a single known pattern.
Parameters
pattern the regular expression matching the key for this pattern
values the number of values for this pattern
Returns
this parser (addPattern() calls may be chained)
Definition at line 123 of file KeyedCSVparser.cxx.
extractToken()
auto icarus::details::KeyedCSVparser::extractToken (Buffer_t & buffer) const private noexcept
Extracts the next token from the buffer and returns its value, stripped.
Definition at line 164 of file KeyedCSVparser.cxx.
Referenced by parse().
findTokenLength()
std::size_t icarus::details::KeyedCSVparser::findTokenLength (Buffer_t const & buffer) const private noexcept
Returns the length of the next toke, up to the next separator (excluded).
Definition at line 140 of file KeyedCSVparser.cxx.
isKey()
bool icarus::details::KeyedCSVparser::isKey (SubBuffer_t const & buffer) const private noexcept
Is content of buffer a key (as opposed to a value)?
Definition at line 191 of file KeyedCSVparser.cxx.
Referenced by parse().
makeBuffer()
template<typename String > auto icarus::details::KeyedCSVparser::makeBuffer (String const & s) -> Buffer_t noexcept
Definition at line 202 of file KeyedCSVparser.cxx.
moveBufferHead()
auto icarus::details::KeyedCSVparser::moveBufferHead (Buffer_t & buffer, std::size_t size) static private noexcept
Definition at line 209 of file KeyedCSVparser.cxx.
operator()() [1/3]
template<typename BIter , typename EIter > ParsedData_t icarus::details::KeyedCSVparser::operator() (BIter b, EIter e) const inline
Definition at line 103 of file KeyedCSVparser.h.
operator()() [2/3]
ParsedData_t icarus::details::KeyedCSVparser::operator() (std::string const & s) const inline
Definition at line 101 of file KeyedCSVparser.h.
operator()() [3/3]
ParsedData_t icarus::details::KeyedCSVparser::operator() (std::string_view const & s) const inline
Definition at line 100 of file KeyedCSVparser.h.
parse() [1/4]
template<typename BIter , typename EIter > auto icarus::details::KeyedCSVparser::parse (BIter b, EIter e) const -> ParsedData_t
Definition at line 244 of file KeyedCSVparser.h.
parse() [2/4]
auto icarus::details::KeyedCSVparser::parse (std::string const & s) const
Definition at line 134 of file KeyedCSVparser.cxx.
parse() [3/4]
auto icarus::details::KeyedCSVparser::parse (std::string_view const & s) const inline
Parses the buffer s and returns a data structure with the content.
Definition at line 235 of file KeyedCSVparser.h.
parse() [4/4]
void icarus::details::KeyedCSVparser::parse (std::string_view const & s, ParsedData_t & data) const
Parses the buffer s and fills data with it.
Definition at line 21 of file KeyedCSVparser.cxx.
References icarus::KeyValuesData::Item::addValue(), DynamicSize, extractToken(), FixedSize, fPatterns, isKey(), icarus::KeyValuesData::Item::key(), icarus::KeyValuesData::makeItem(), and peekToken().
peekToken()
auto icarus::details::KeyedCSVparser::peekToken (Buffer_t const & buffer) const private noexcept
Returns the value of the next token, stripped.
Definition at line 156 of file KeyedCSVparser.cxx.
Referenced by parse().
strip()
auto icarus::details::KeyedCSVparser::strip (SubBuffer_t s) static private noexcept
Definition at line 220 of file KeyedCSVparser.cxx.
stripLeft()
auto icarus::details::KeyedCSVparser::stripLeft (SubBuffer_t s) static private noexcept
Definition at line 226 of file KeyedCSVparser.cxx.
stripRight()
auto icarus::details::KeyedCSVparser::stripRight (SubBuffer_t s) static private noexcept
Definition at line 240 of file KeyedCSVparser.cxx.
stripRightChar()
auto icarus::details::KeyedCSVparser::stripRightChar (SubBuffer_t s, char c) static private noexcept
Definition at line 254 of file KeyedCSVparser.cxx.
stripRightChars()
template<char... Chars> auto icarus::details::KeyedCSVparser::stripRightChars (SubBuffer_t s) -> SubBuffer_t noexcept
Definition at line 269 of file KeyedCSVparser.cxx.
Member Data Documentation
DynamicSize
unsigned int icarus::details::KeyedCSVparser::DynamicSize = FixedSize - 1U static constexpr
Mnemonic size value used in addPattern() calls.
Definition at line 87 of file KeyedCSVparser.h.
Referenced by parse().
FixedSize
unsigned int icarus::details::KeyedCSVparser::FixedSize = std::numeric_limits<unsigned int>::max() static constexpr
Expected values are missing.
Mnemonic size value used in addPattern() calls.
Definition at line 84 of file KeyedCSVparser.h.
Referenced by parse().
fPatterns
std::vector<std::pair<std::regex, unsigned int> > icarus::details::KeyedCSVparser::fPatterns private
List of known patterns for matching keys, and how many values they hold.
Definition at line 170 of file KeyedCSVparser.h.
Referenced by addPattern(), and parse().
fSep
char const icarus::details::KeyedCSVparser::fSep = ',' private
Character used as token separator.
Definition at line 167 of file KeyedCSVparser.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/Decode/DecoderTools/details/KeyedCSVparser.h
icaruscode/icaruscode/Decode/DecoderTools/details/KeyedCSVparser.cxx