CAF format: icarus::details::KeyValueParser Class Reference
icarus::details::KeyValueParser Class Reference
Parser to fill a KeyValuesData structure out of a character buffer.
#include <KeyValueParser.h>
Classes
struct FormatParams_t
Parameters of the format.
struct ParserError
Public Types
using Error = icarus::KeyValuesData::Error
Base of all errors by KeyValueParser.
using ParsedData_t = icarus::KeyValuesData
Generic error: base of all errors by KeyValueParser.
Public Member Functions
KeyValueParser (FormatParams_t formatParams=DefaultFormatParameters, icarus::ParsingToolkit::Params_t parserParams=icarus::ParsingToolkit::DefaultParameters)
Creates a parser with the specified parsing parameters.
ParsedData_t parse (std::istream &stream) const
Parses the stream and returns a data structure with the content.
ParsedData_t parse (std::istream &&stream) const
ParsedData_t operator() (std::istream &stream) const
ParsedData_t parse (std::string const &s) const
Runs the parser on a string.
template<typename Key >
auto keySepType (Key const &key) const -> keyType
Static Public Attributes
static const FormatParams_t DefaultFormatParameters
Private Types
enum class keyType { unsupported , create , add }
Private Member Functions
keyType highlightSeparator (std::vector< std::string_view > &tokens) const
Modifies tokens placing the key/value separator in its own token.
template<typename Key >
keyType keySepType (Key const &key) const
Returns the type of key.
Private Attributes
icarus::ParsingToolkit fPTK
Parsing toolkit (and its parameters).
FormatParams_t fFmt
Parser format parameters.
std::vector< std::string > fKeys
Sorted keys cache.
Detailed Description
Parser to fill a KeyValuesData structure out of a character buffer.
The parser processes an input stream or string. Parsing produces a data structure of type icarus::KeyValuesData; it is not possible to reconstruct the input from that structure, since quotations, escapes, formatting and comments are lost.
The supported format is:
one key/value pair per line
all keys and values are stripped of trailing and ending blank characters
key is everything before the key separator (by default, : to create/overwrite, :+ to create/append values)
array values are separated by spaces
quotation supports both single and double quotes
comments start with a word beginning with # and extend to the end of the line
escape character (backslash by default) drops the special meaning of comment, key and quote symbols
Example of format
This is the text from the unit test:
# SPR test input file
Description: "
This is a test for the key-values parser with default settings.
It is expected to be used to describe the Single Photoelectron Response.
"
Contact: Gianluca Petrillo (petrillo@slac.stanford.edu)
Gain: 9.7e6  # from amplitude 4 mV
Tick: '2 ns'
Samples: 0.0 1.0 2.5 \
         4.5 3.0 2.5
Samples:+1.8 1.6 1.2 0.8 0.8 0.7 0.7 0.6
Definition at line 73 of file KeyValueParser.h.
Class Documentation
icarus::details::KeyValueParser::FormatParams_t
struct icarus::details::KeyValueParser::FormatParams_t
Parameters of the format.
Definition at line 84 of file KeyValueParser.h.
Class Members
string addKey { ":+" } Sequence appending the values.
string newKey { ":" } Sequence starting the values.
Member Typedef Documentation
Error
using icarus::details::KeyValueParser::Error = icarus::KeyValuesData::Error
Base of all errors by KeyValueParser.
Definition at line 78 of file KeyValueParser.h.
ParsedData_t
using icarus::details::KeyValueParser::ParsedData_t = icarus::KeyValuesData
Generic error: base of all errors by KeyValueParser.
Type of returned data.
Definition at line 81 of file KeyValueParser.h.
Member Enumeration Documentation
keyType
enum class icarus::details::KeyValueParser::keyType strong private
Definition at line 113 of file KeyValueParser.h.
Constructor & Destructor Documentation
KeyValueParser()
icarus::details::KeyValueParser::KeyValueParser (FormatParams_t formatParams = DefaultFormatParameters, icarus::ParsingToolkit::Params_t parserParams = icarus::ParsingToolkit::DefaultParameters)
Creates a parser with the specified parsing parameters.
Definition at line 56 of file KeyValueParser.cxx.
References icarus::details::KeyValueParser::FormatParams_t::addKey, fFmt, and icarus::details::KeyValueParser::FormatParams_t::newKey.
Member Function Documentation
highlightSeparator()
auto icarus::details::KeyValueParser::highlightSeparator (std::vector< std::string_view > & tokens) const private
Modifies tokens placing the key/value separator in its own token.
Parameters
[in,out] tokens list of tokens
Returns
the type of separator found
On success, the first token is the key, the second the separator that was found, and the rest are values. The list of tokens is modified in place. In case of failure, where the separator is not found where expected, tokens are unchanged.
The separator is expected to be either unquoted and unescaped in the first of the tokens, or otherwise at the beginning of the second token.
Definition at line 133 of file KeyValueParser.cxx.
keySepType() [1/2]
template<typename Key > keyType icarus::details::KeyValueParser::keySepType (Key const & key) const private
Returns the type of key.
keySepType() [2/2]
template<typename Key > auto icarus::details::KeyValueParser::keySepType (Key const & key) const -> keyType
Definition at line 192 of file KeyValueParser.cxx.
operator()()
ParsedData_t icarus::details::KeyValueParser::operator() (std::istream & stream) const inline
Definition at line 104 of file KeyValueParser.h.
parse() [1/3]
ParsedData_t icarus::details::KeyValueParser::parse (std::istream && stream) const inline
Definition at line 102 of file KeyValueParser.h.
parse() [2/3]
auto icarus::details::KeyValueParser::parse (std::istream & stream) const
Parses the stream and returns a data structure with the content.
Definition at line 68 of file KeyValueParser.cxx.
References icarus::KeyValuesData::Item::addValues(), icarus::KeyValuesData::Item::clear(), and icarus::KeyValuesData::makeOrFetchItem().
parse() [3/3]
auto icarus::details::KeyValueParser::parse (std::string const & s) const
Runs the parser on a string.
Definition at line 127 of file KeyValueParser.cxx.
Member Data Documentation
DefaultFormatParameters
const icarus::details::KeyValueParser::FormatParams_t icarus::details::KeyValueParser::DefaultFormatParameters static
Definition at line 89 of file KeyValueParser.h.
fFmt
FormatParams_t icarus::details::KeyValueParser::fFmt private
Parser format parameters.
Definition at line 116 of file KeyValueParser.h.
Referenced by KeyValueParser().
fKeys
std::vector<std::string> icarus::details::KeyValueParser::fKeys private
Sorted keys cache.
Definition at line 118 of file KeyValueParser.h.
fPTK
icarus::ParsingToolkit icarus::details::KeyValueParser::fPTK private
Parsing toolkit (and its parameters).
Definition at line 115 of file KeyValueParser.h.
The documentation for this class was generated from the following files:
icaruscode/icaruscode/PMT/Algorithms/KeyValueParser.h
icaruscode/icaruscode/PMT/Algorithms/KeyValueParser.cxx